import Link from "next/link";
import { SafeActionForm } from "@/components/forms/safe-action-form";
import { SubmitButton } from "@/components/forms/submit-button";
import { createPortalAnnouncementAction, togglePortalAnnouncementAction, togglePortalEventFeatureAction } from "@/lib/actions/client-portal";
import { requireModuleView } from "@/lib/auth/guards";
import { prisma } from "@/lib/prisma";

export default async function ClientPortalSettingsPage() {
  const auth = await requireModuleView("arena");
  const now = new Date();
  const [announcements, events] = await Promise.all([
    prisma.portalAnnouncement.findMany({ where: { arenaId: auth.arenaId }, orderBy: { createdAt: "desc" } }),
    prisma.calendarEvent.findMany({ where: { arenaId: auth.arenaId, scheduledAt: { gte: now } }, orderBy: { scheduledAt: "asc" }, take: 20 }),
  ]);
  return <div className="stack-md client-portal-settings"><header className="page-header"><div><p className="eyebrow">PORTAL DO CLIENTE</p><h1>Início do portal</h1><p>Publique avisos e selecione os próximos eventos em destaque.</p></div><Link className="button" href="/arena">Voltar</Link></header><section className="section-card"><header><h2>Avisos para o portal</h2><p>Os avisos ativos ficam visíveis na tela inicial do cliente.</p></header><SafeActionForm action={createPortalAnnouncementAction} className="grid-form" resetOnSuccess successMessage="Aviso publicado."><div className="field"><label>Título<input name="title" required /></label></div><div className="field"><label>Início da publicação<input name="startsAt" type="datetime-local" /></label></div><div className="field"><label>Fim da publicação<input name="endsAt" type="datetime-local" /></label></div><div className="field form-full"><label>Aviso<textarea name="message" rows={3} required /></label></div><SubmitButton label="Publicar aviso" pendingLabel="Publicando..." className="button button-primary" /></SafeActionForm><div className="client-portal-settings-list">{announcements.map((announcement) => <article key={announcement.id}><div><strong>{announcement.title}</strong><span>{announcement.message}</span></div><SafeActionForm action={togglePortalAnnouncementAction}><input type="hidden" name="announcementId" value={announcement.id} /><SubmitButton label={announcement.active ? "Desativar" : "Ativar"} pendingLabel="Salvando..." className="button button-small" /></SafeActionForm></article>)}{!announcements.length ? <p className="muted">Nenhum aviso publicado.</p> : null}</div></section><section className="section-card"><header><h2>Eventos em destaque</h2><p>Selecione apenas os eventos que deseja anunciar no portal.</p></header><div className="client-portal-settings-list">{events.map((event) => <article key={event.id}><div><strong>{event.title}</strong><span>{new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(event.scheduledAt)}</span></div><SafeActionForm action={togglePortalEventFeatureAction}><input type="hidden" name="calendarEventId" value={event.id} /><SubmitButton label={event.featuredInPortal ? "Em destaque" : "Destacar"} pendingLabel="Salvando..." className={event.featuredInPortal ? "button button-primary button-small" : "button button-small"} /></SafeActionForm></article>)}{!events.length ? <p className="muted">Não há eventos futuros no calendário.</p> : null}</div></section></div>;
}
