import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "stack_md_workspace_page": "stack-md workspace-page dashboard-page tw:grid tw:min-w-0 tw:gap-4 tw:pb-4 tw:[&_.card]:rounded-xl tw:[&_.card]:border tw:[&_.card]:border-solid tw:[&_.card]:border-[var(--line)] tw:[&_.card]:bg-white tw:[&_.card]:p-4 tw:[&_.card]:shadow-[var(--shadow)] tw:[&_.card_h2]:text-base tw:[&_.card_h2]:font-semibold",
  "page_header_dashboard_header": "page-header dashboard-header tw:grid tw:gap-4 tw:pb-4 tw:border-0 tw:border-b tw:border-solid tw:border-[var(--line)] tw:[&_h1]:text-[1.5rem] tw:[&_h1]:font-semibold",
  "eyebrow": sharedUtilities.eyebrow,
  "dashboard_filters": "dashboard-filters tw:grid tw:grid-cols-[repeat(4,minmax(0,1fr))_auto] tw:items-end tw:gap-3 tw:text-xs tw:viewport-1000:grid-cols-2 tw:viewport-620:grid-cols-2 tw:[&_label]:grid tw:[&_label]:min-w-0 tw:[&_label]:gap-1 tw:[&_input]:min-w-0 tw:[&_input]:w-full tw:[&_input]:min-h-[40px] tw:[&_select]:min-w-0 tw:[&_select]:w-full tw:[&_select]:min-h-[40px] tw:[&_button]:min-h-[40px] tw:[&_.dashboard-presets]:col-span-full tw:[&_.dashboard-presets]:w-fit",
  "dashboard_presets": "dashboard-presets tw:flex tw:flex-wrap tw:gap-1 tw:items-center tw:rounded-lg tw:bg-[var(--panel-muted)] tw:p-1 tw:[&_a]:rounded-md tw:[&_a]:px-2.5 tw:[&_a]:py-2 tw:[&_a]:text-xs tw:[&_a]:font-medium tw:[&_a]:text-[var(--muted)] tw:[&_a]:no-underline tw:[&_a:hover]:bg-white tw:[&_.dashboard-period-preset-active]:bg-white tw:[&_.dashboard-period-preset-active]:text-[var(--brand)]",
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "dashboard_financial_summary": "dashboard-financial-summary tw:min-w-0",
  "stats_grid": "stats-grid tw:grid tw:grid-cols-3 tw:gap-3 tw:viewport-1120:grid-cols-2 tw:viewport-620:grid-cols-1",
  "dashboard_cash_flow": "dashboard-cash-flow tw:min-w-0",
  "dashboard_chart_legend": [
    "dashboard-chart-legend", "tw:flex", "tw:justify-end", "tw:gap-y-[14px]",
    "tw:gap-x-[14px]", "tw:text-[color:var(--muted)]", "tw:text-[.72rem]", "tw:[&_span]:inline-flex",
    "tw:[&_span]:items-center", "tw:[&_span]:gap-y-[5px]", "tw:[&_span]:gap-x-[5px]", "tw:[&_i]:w-[8px]",
    "tw:[&_i]:h-[8px]", "tw:[&_i]:rounded-[2px]",
  ].join(" "),
  "dashboard_chart_income": [
    "dashboard-chart-income", "tw:bg-[color:#238b45]", "tw:[background-image:none]",
  ].join(" "),
  "dashboard_chart_expense": [
    "dashboard-chart-expense", "tw:bg-[color:#d95b4f]", "tw:[background-image:none]",
  ].join(" "),
  "dashboard_cash_chart": "dashboard-cash-chart tw:h-[190px] tw:overflow-x-auto tw:py-2",
  "dashboard_cash_bars": [
    "dashboard-cash-bars", "tw:grid", "tw:grid-cols-[repeat(30,_minmax(0,_1fr))]", "tw:h-[100%]",
    "tw:gap-y-[4px]", "tw:viewport-620:gap-y-[2px]", "tw:gap-x-[4px]", "tw:viewport-620:gap-x-[2px]",
  ].join(" "),
  "dashboard_cash_day": [
    "dashboard-cash-day", "tw:grid", "tw:grid-rows-[1fr_auto]", "tw:min-w-[0]",
    "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:[&:hover_span]:opacity-[.72]", "tw:[&_small]:[overflow-x:hidden]",
    "tw:[&_small]:[overflow-y:hidden]", "tw:[&_small]:text-[color:var(--muted)]", "tw:[&_small]:text-[.55rem]", "tw:[&_small]:text-center",
    "tw:[&_small]:whitespace-nowrap", "tw:viewport-620:[&_small]:hidden",
  ].join(" "),
  "dashboard_cash_column": [
    "dashboard-cash-column", "tw:flex", "tw:[align-items:end]", "tw:justify-center",
    "tw:gap-y-[2px]", "tw:gap-x-[2px]", "tw:min-h-[0]", "tw:[&_span]:w-[min(9px,_42%)]",
    "tw:[&_span]:rounded-[3px_3px_0_0]", "tw:[&_span]:[transition:opacity_150ms_var(--ease-standard)]",
  ].join(" "),
  "dashboard_cash_income": [
    "dashboard-cash-income", "tw:bg-[color:#238b45]", "tw:[background-image:none]",
  ].join(" "),
  "dashboard_cash_expense": [
    "dashboard-cash-expense", "tw:bg-[color:#d95b4f]", "tw:[background-image:none]",
  ].join(" "),
  "dashboard_payment_towers": [
    "dashboard-payment-towers", "tw:flex", "tw:min-h-[210px]", "tw:[align-items:end]",
    "tw:gap-y-[18px]", "tw:viewport-600:gap-y-[12px]", "tw:gap-x-[18px]", "tw:viewport-600:gap-x-[12px]",
    "tw:pt-[10px]", "tw:pr-[8px]", "tw:pb-[2px]", "tw:pl-[8px]",
    "tw:[&_article]:grid", "tw:[&_article]:[flex:1_1_120px]", "tw:[&_article]:min-w-[0]", "tw:[&_article]:gap-y-[6px]",
    "tw:[&_article]:gap-x-[6px]", "tw:[&_article_>_div]:flex", "tw:[&_article_>_div]:h-[142px]", "tw:viewport-600:[&_article_>_div]:h-[124px]",
    "tw:[&_article_>_div]:[align-items:end]", "tw:[&_article_>_div]:justify-center", "tw:[&_article_>_div]:border-b-[length:1px]", "tw:[&_article_>_div]:[border-bottom-style:solid]",
    "tw:[&_article_>_div]:border-b-[color:#d9e5ef]", "tw:[&_article_>_div]:bg-[color:transparent]", "tw:[&_article_>_div]:[background-image:repeating-linear-gradient(to_top,_transparent_0_34px,_#edf3f8_35px_36px)]", "tw:[&_article_i]:block",
    "tw:[&_article_i]:w-[min(60px,_68%)]", "tw:[&_article_i]:min-h-[8px]", "tw:[&_article_i]:rounded-[7px_7px_2px_2px]", "tw:[&_article_i]:bg-[color:transparent]",
    "tw:[&_article_i]:[background-image:linear-gradient(180deg,_#4d9ee9,_#1c62ae)]", "tw:[&_article_i]:[box-shadow:0_5px_12px_rgb(38_106_182_/_.18)]", "tw:[&_strong]:[overflow-x:hidden]", "tw:[&_strong]:[overflow-y:hidden]",
    "tw:[&_strong]:text-[color:#193b62]", "tw:[&_strong]:text-[.76rem]", "tw:[&_strong]:text-ellipsis", "tw:[&_strong]:whitespace-nowrap",
    "tw:[&_span]:text-[color:#16704a]", "tw:[&_span]:text-[.74rem]", "tw:[&_span]:font-[800]", "tw:[&_>_.muted]:[align-self:center]",
    "tw:viewport-600:[overflow-x:auto]", "tw:viewport-600:[&_article]:[flex-basis:112px]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "dashboard_ranking_chart": [
    "dashboard-ranking-chart", "tw:grid", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:[&_>_div]:grid", "tw:[&_>_div]:grid-cols-[minmax(75px,_1fr)_minmax(60px,_1.6fr)_auto]", "tw:[&_>_div]:items-center", "tw:[&_>_div]:gap-y-[8px]",
    "tw:[&_>_div]:gap-x-[8px]", "tw:[&_span]:[overflow-x:hidden]", "tw:[&_span]:[overflow-y:hidden]", "tw:[&_span]:text-[.76rem]",
    "tw:[&_span]:font-[700]", "tw:[&_span]:text-ellipsis", "tw:[&_span]:whitespace-nowrap", "tw:[&_i]:block",
    "tw:[&_i]:h-[7px]", "tw:[&_i]:[overflow-x:hidden]", "tw:[&_i]:[overflow-y:hidden]", "tw:[&_i]:rounded-[99px]",
    "tw:[&_i]:bg-[color:var(--panel-muted)]", "tw:[&_i]:[background-image:none]", "tw:[&_b]:block", "tw:[&_b]:h-[100%]",
    "tw:[&_b]:rounded-[inherit]", "tw:[&_b]:bg-[color:transparent]", "tw:[&_b]:[background-image:linear-gradient(90deg,_var(--brand),_#52a3e8)]", "tw:[&_strong]:text-[color:var(--muted)]",
    "tw:[&_strong]:text-[.72rem]",
  ].join(" "),
  "dashboard_ranking_chart_dashboard_ranking_chart_financial": [
    "dashboard-ranking-chart", "dashboard-ranking-chart-financial", "tw:grid", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:[&_>_div]:grid", "tw:[&_>_div]:grid-cols-[minmax(90px,_1fr)_minmax(50px,_1.35fr)_auto]", "tw:[&_>_div]:items-center",
    "tw:[&_>_div]:gap-y-[8px]", "tw:[&_>_div]:gap-x-[8px]", "tw:[&_span]:[overflow-x:hidden]", "tw:[&_span]:[overflow-y:hidden]",
    "tw:[&_span]:text-[.76rem]", "tw:[&_span]:font-[700]", "tw:[&_span]:text-ellipsis", "tw:[&_span]:whitespace-nowrap",
    "tw:[&_i]:block", "tw:[&_i]:h-[7px]", "tw:[&_i]:[overflow-x:hidden]", "tw:[&_i]:[overflow-y:hidden]",
    "tw:[&_i]:rounded-[99px]", "tw:[&_i]:bg-[color:var(--panel-muted)]", "tw:[&_i]:[background-image:none]", "tw:[&_b]:block",
    "tw:[&_b]:h-[100%]", "tw:[&_b]:rounded-[inherit]", "tw:[&_b]:bg-[color:transparent]", "tw:[&_b]:[background-image:linear-gradient(90deg,_var(--brand),_#52a3e8)]",
    "tw:[&_strong]:text-[color:#216245]", "tw:[&_strong]:text-[.72rem]", "tw:[&_strong]:min-w-[64px]", "tw:[&_strong]:[font-variant-numeric:tabular-nums]",
    "tw:[&_strong]:text-right",
  ].join(" "),
} as const;
