import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "stack_md_workspace_page": [
    "stack-md", "workspace-page", "dashboard-analytics-page", "tw:grid",
    "tw:gap-y-[24px]", "tw:viewport-720:gap-y-[18px]", "tw:gap-x-[24px]", "tw:viewport-720:gap-x-[18px]",
    "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]", "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]",
    "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]", "tw:pt-[5px]",
    "tw:pr-[0]", "tw:pb-[44px]", "tw:pl-[0]", "tw:[&_.page-header]:pt-[4px]",
    "tw:[&_.page-header]:pr-[0]", "tw:[&_.page-header]:pb-[20px]", "tw:[&_.page-header]:pl-[0]", "tw:[&_.page-header]:border-b-[length:1px]",
    "tw:[&_.page-header]:[border-bottom-style:solid]", "tw:[&_.page-header]:border-b-[color:#dfe7f1]", "tw:[&_.page-header_h1]:text-[color:#102b56]", "tw:[&_.page-header_h1]:text-[clamp(1.75rem,_2.3vw,_2.25rem)]",
    "tw:[&_.page-header_h1]:tracking-[-.045em]", "tw:[&_.stats-grid]:gap-y-[16px]", "tw:[&_.stats-grid]:gap-x-[16px]", "tw:[&_.stat-card]:pt-[20px]",
    "tw:[&_.stat-card]:pr-[20px]", "tw:[&_.stat-card]:pb-[20px]", "tw:[&_.stat-card]:pl-[20px]", "tw:[&_.stat-card]:border-t-[length:1px]",
    "tw:[&_.stat-card]:[border-top-style:solid]", "tw:[&_.stat-card]:border-t-[color:#e2e9f3]", "tw:[&_.stat-card]:border-r-[length:1px]", "tw:[&_.stat-card]:[border-right-style:solid]",
    "tw:[&_.stat-card]:border-r-[color:#e2e9f3]", "tw:[&_.stat-card]:border-b-[length:1px]", "tw:[&_.stat-card]:[border-bottom-style:solid]", "tw:[&_.stat-card]:border-b-[color:#e2e9f3]",
    "tw:[&_.stat-card]:border-l-[length:1px]", "tw:[&_.stat-card]:[border-left-style:solid]", "tw:[&_.stat-card]:border-l-[color:#e2e9f3]", "tw:[&_.stat-card]:rounded-[14px]",
    "tw:[&_.stat-card]:bg-[color:#fff]", "tw:[&_.stat-card]:[background-image:none]", "tw:[&_.stat-card]:[box-shadow:0_8px_22px_rgba(19,_55,_104,_.06)]", "tw:[&_.dashboard-grid]:gap-y-[18px]",
    "tw:[&_.dashboard-grid]:gap-x-[18px]", "tw:[&_.section-card]:pt-[21px]", "tw:viewport-720:[&_.section-card]:pt-[16px]", "tw:[&_.section-card]:pr-[21px]",
    "tw:viewport-720:[&_.section-card]:pr-[16px]", "tw:[&_.section-card]:pb-[21px]", "tw:viewport-720:[&_.section-card]:pb-[16px]", "tw:[&_.section-card]:pl-[21px]",
    "tw:viewport-720:[&_.section-card]:pl-[16px]", "tw:[&_.section-card]:border-t-[length:1px]", "tw:[&_.section-card]:[border-top-style:solid]", "tw:[&_.section-card]:border-t-[color:#e2e9f3]",
    "tw:[&_.section-card]:border-r-[length:1px]", "tw:[&_.section-card]:[border-right-style:solid]", "tw:[&_.section-card]:border-r-[color:#e2e9f3]", "tw:[&_.section-card]:border-b-[length:1px]",
    "tw:[&_.section-card]:[border-bottom-style:solid]", "tw:[&_.section-card]:border-b-[color:#e2e9f3]", "tw:[&_.section-card]:border-l-[length:1px]", "tw:[&_.section-card]:[border-left-style:solid]",
    "tw:[&_.section-card]:border-l-[color:#e2e9f3]", "tw:[&_.section-card]:rounded-[14px]", "tw:[&_.section-card]:bg-[color:#fff]", "tw:[&_.section-card]:[background-image:none]",
    "tw:[&_.section-card]:[box-shadow:0_8px_22px_rgba(19,_55,_104,_.05)]", "tw:[&_.section-card_+_.section-card]:border-t-[length:1px]", "tw:[&_.section-card_+_.section-card]:[border-top-style:solid]", "tw:[&_.section-card_+_.section-card]:border-t-[color:#e2e9f3]",
  ].join(" "),
  "page_header_dashboard_header": [
    "page-header", "dashboard-header", "tw:flex", "tw:justify-between",
    "tw:items-end", "tw:viewport-720:items-start", "tw:gap-y-[18px]", "tw:gap-x-[18px]",
    "tw:mb-[0]", "tw:pt-[4px]", "tw:pr-[0]", "tw:pb-[22px]",
    "tw:pl-[0]", "tw:border-t-[length:0]", "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]",
    "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:2px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:color-mix(in_srgb,_var(--brand)_24%,_var(--line))]", "tw:border-l-[length:0]", "tw:[border-left-style:none]",
    "tw:border-l-[color:currentColor]", "tw:rounded-[0]", "tw:bg-[color:transparent]", "tw:[background-image:none]",
    "tw:[box-shadow:none]", "tw:[animation:hero-rise_620ms_var(--ease-standard)_both]", "tw:mt-[0]", "tw:mr-[0]",
    "tw:ml-[0]", "tw:[&_h1]:mt-[0]", "tw:[&_h1]:mr-[0]", "tw:[&_h1]:mb-[0]",
    "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[clamp(1.8rem,_2vw,_2.4rem)]", "tw:[&_h1]:leading-[1.04]", "tw:[&_h1]:tracking-[-0.04em]",
    "tw:[&_p]:max-w-[760px]", "tw:[&::after]:[content:'']", "tw:[&::after]:absolute", "tw:viewport-720:flex-col",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "dashboard_filters": [
    "dashboard-filters", "tw:flex", "tw:flex-wrap", "tw:[align-items:end]",
    "tw:justify-end", "tw:viewport-620:[justify-content:stretch]", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:[&_label]:grid", "tw:[&_label]:gap-y-[4px]", "tw:[&_label]:gap-x-[4px]", "tw:[&_label]:text-[color:var(--muted)]",
    "tw:[&_label]:text-[.68rem]", "tw:[&_label]:font-[800]", "tw:[&_input]:min-h-[34px]", "tw:[&_input]:min-w-[132px]",
    "tw:[&_input]:pt-[5px]", "tw:[&_input]:pr-[8px]", "tw:[&_input]:pb-[5px]", "tw:[&_input]:pl-[8px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:var(--line)]",
    "tw:[&_input]:rounded-[var(--radius-control)]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:var(--text)]",
    "tw:[&_select]:min-h-[34px]", "tw:[&_select]:min-w-[132px]", "tw:[&_select]:pt-[5px]", "tw:[&_select]:pr-[8px]",
    "tw:[&_select]:pb-[5px]", "tw:[&_select]:pl-[8px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]",
    "tw:[&_select]:border-t-[color:var(--line)]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]",
    "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]",
    "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:var(--line)]", "tw:[&_select]:rounded-[var(--radius-control)]", "tw:[&_select]:bg-[color:var(--panel)]",
    "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:var(--text)]", "tw:[&_.button]:min-h-[34px]", "tw:viewport-620:w-[100%]",
    "tw:viewport-620:[&_label]:[flex:1_1_100%]", "tw:viewport-620:[&_label]:w-[100%]", "tw:viewport-620:[&_input]:[flex:1_1_100%]", "tw:viewport-620:[&_input]:w-[100%]",
    "tw:viewport-620:[&_select]:[flex:1_1_100%]", "tw:viewport-620:[&_select]:w-[100%]", "tw:viewport-620:[&_.button]:[flex:1_1_100%]", "tw:viewport-620:[&_.button]:w-[100%]",
  ].join(" "),
  "dashboard_presets": [
    "dashboard-presets", "tw:flex", "tw:flex-wrap", "tw:gap-y-[5px]",
    "tw:gap-x-[5px]", "tw:[&_a]:pt-[5px]", "tw:[&_a]:pr-[7px]", "tw:[&_a]:pb-[5px]",
    "tw:[&_a]:pl-[7px]", "tw:[&_a]:border-t-[length:1px]", "tw:[&_a]:[border-top-style:solid]", "tw:[&_a]:border-t-[color:var(--line)]",
    "tw:[&_a]:border-r-[length:1px]", "tw:[&_a]:[border-right-style:solid]", "tw:[&_a]:border-r-[color:var(--line)]", "tw:[&_a]:border-b-[length:1px]",
    "tw:[&_a]:[border-bottom-style:solid]", "tw:[&_a]:border-b-[color:var(--line)]", "tw:[&_a]:border-l-[length:1px]", "tw:[&_a]:[border-left-style:solid]",
    "tw:[&_a]:border-l-[color:var(--line)]", "tw:[&_a]:rounded-[6px]", "tw:[&_a]:text-[color:var(--brand-strong)]", "tw:[&_a]:text-[.7rem]",
    "tw:[&_a]:font-[700]", "tw:[&_a]:[text-decoration:none]", "tw:[&_a:hover]:border-t-[color:var(--brand)]", "tw:[&_a:hover]:border-r-[color:var(--brand)]",
    "tw:[&_a:hover]:border-b-[color:var(--brand)]", "tw:[&_a:hover]:border-l-[color:var(--brand)]", "tw:[&_a:hover]:bg-[color:var(--brand-soft)]", "tw:[&_a:hover]:[background-image:none]",
    "tw:[&_.dashboard-period-preset-active]:border-t-[color:var(--brand-strong)]", "tw:[&_.dashboard-period-preset-active]:border-r-[color:var(--brand-strong)]", "tw:[&_.dashboard-period-preset-active]:border-b-[color:var(--brand-strong)]", "tw:[&_.dashboard-period-preset-active]:border-l-[color:var(--brand-strong)]",
    "tw:[&_.dashboard-period-preset-active]:bg-[color:var(--brand-strong)]", "tw:[&_.dashboard-period-preset-active]:[background-image:none]", "tw:[&_.dashboard-period-preset-active]:text-[color:#fff]", "tw:[&_.dashboard-period-preset-active]:[box-shadow:0_3px_8px_rgb(11_88_147_/_.2)]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "dashboard_financial_summary": [
    "dashboard-financial-summary", "tw:[&_.stats-grid]:gap-y-[0]", "tw:[&_.stats-grid]:gap-x-[0]", "tw:[&_.stats-grid]:grid-cols-[repeat(4,_minmax(0,_1fr))]",
    "tw:viewport-900:[&_.stats-grid]:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-620:[&_.stats-grid]:grid-cols-[1fr]", "tw:[&_.stat-card]:pt-[3px]", "tw:viewport-620:[&_.stat-card]:pt-[12px]",
    "tw:[&_.stat-card]:pr-[18px]", "tw:viewport-620:[&_.stat-card]:pr-[0]", "tw:[&_.stat-card]:pb-[3px]", "tw:viewport-620:[&_.stat-card]:pb-[12px]",
    "tw:[&_.stat-card]:pl-[18px]", "tw:viewport-620:[&_.stat-card]:pl-[0]", "tw:[&_.stat-card]:border-t-[length:0]", "tw:viewport-620:[&_.stat-card]:border-t-[length:1px]",
    "tw:[&_.stat-card]:[border-top-style:none]", "tw:viewport-620:[&_.stat-card]:[border-top-style:solid]", "tw:[&_.stat-card]:border-t-[color:currentColor]", "tw:viewport-620:[&_.stat-card]:border-t-[color:var(--line)]",
    "tw:[&_.stat-card]:border-r-[length:1px]", "tw:viewport-620:[&_.stat-card]:border-r-[length:0]", "tw:[&_.stat-card]:[border-right-style:solid]", "tw:viewport-620:[&_.stat-card]:[border-right-style:none]",
    "tw:[&_.stat-card]:border-r-[color:var(--line)]", "tw:viewport-620:[&_.stat-card]:border-r-[color:currentColor]", "tw:[&_.stat-card]:border-b-[length:0]", "tw:[&_.stat-card]:[border-bottom-style:none]",
    "tw:[&_.stat-card]:border-b-[color:currentColor]", "tw:[&_.stat-card]:border-l-[length:0]", "tw:[&_.stat-card]:[border-left-style:none]", "tw:[&_.stat-card]:border-l-[color:currentColor]",
    "tw:[&_.stat-card]:rounded-[0]", "tw:[&_.stat-card]:bg-[color:transparent]", "tw:[&_.stat-card]:[background-image:none]", "tw:[&_.stat-card]:[box-shadow:none]",
    "tw:[&_.stat-card:last-child]:border-r-[length:0]", "tw:[&_.stat-card:last-child]:[border-right-style:none]", "tw:[&_.stat-card:last-child]:border-r-[color:currentColor]", "tw:[&_.stat-card_strong]:text-[1.35rem]",
    "tw:viewport-900:[&_.stat-card:nth-child(2)]:border-r-[length:0]", "tw:viewport-900:[&_.stat-card:nth-child(2)]:[border-right-style:none]", "tw:viewport-900:[&_.stat-card:nth-child(2)]:border-r-[color:currentColor]", "tw:viewport-900:[&_.stat-card:nth-child(n_+_3)]:pt-[14px]",
    "tw:viewport-900:[&_.stat-card:nth-child(n_+_3)]:border-t-[length:1px]", "tw:viewport-900:[&_.stat-card:nth-child(n_+_3)]:[border-top-style:solid]", "tw:viewport-900:[&_.stat-card:nth-child(n_+_3)]:border-t-[color:var(--line)]", "tw:viewport-620:[&_.stat-card:first-child]:pt-[0]",
    "tw:viewport-620:[&_.stat-card:first-child]:border-t-[length:0]", "tw:viewport-620:[&_.stat-card:first-child]:[border-top-style:none]", "tw:viewport-620:[&_.stat-card:first-child]:border-t-[color:currentColor]",
  ].join(" "),
  "stats_grid": sharedUtilities.statsGrid,
  "dashboard_cash_flow": [
    "dashboard-cash-flow", "tw:min-h-[330px]",
  ].join(" "),
  "dashboard_chart_legend": [
    "dashboard-chart-legend", "tw:flex", "tw:justify-end", "tw:gap-y-[14px]",
    "tw:gap-x-[14px]", "tw:text-[color:var(--muted)]", "tw:text-[.72rem]", "tw:[&_span]:inline-flex",
    "tw:[&_span]:items-center", "tw:[&_span]:gap-y-[5px]", "tw:[&_span]:gap-x-[5px]", "tw:[&_i]:w-[8px]",
    "tw:[&_i]:h-[8px]", "tw:[&_i]:rounded-[2px]",
  ].join(" "),
  "dashboard_chart_income": [
    "dashboard-chart-income", "tw:bg-[color:#238b45]", "tw:[background-image:none]",
  ].join(" "),
  "dashboard_chart_expense": [
    "dashboard-chart-expense", "tw:bg-[color:#d95b4f]", "tw:[background-image:none]",
  ].join(" "),
  "dashboard_cash_chart": [
    "dashboard-cash-chart", "tw:h-[220px]", "tw:pt-[8px]", "tw:pr-[0]",
    "tw:pb-[2px]", "tw:pl-[0]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]",
  ].join(" "),
  "dashboard_cash_bars": [
    "dashboard-cash-bars", "tw:grid", "tw:grid-cols-[repeat(30,_minmax(0,_1fr))]", "tw:h-[100%]",
    "tw:gap-y-[4px]", "tw:viewport-620:gap-y-[2px]", "tw:gap-x-[4px]", "tw:viewport-620:gap-x-[2px]",
  ].join(" "),
  "dashboard_cash_day": [
    "dashboard-cash-day", "tw:grid", "tw:grid-rows-[1fr_auto]", "tw:min-w-[0]",
    "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:[&:hover_span]:opacity-[.72]", "tw:[&_small]:[overflow-x:hidden]",
    "tw:[&_small]:[overflow-y:hidden]", "tw:[&_small]:text-[color:var(--muted)]", "tw:[&_small]:text-[.55rem]", "tw:[&_small]:text-center",
    "tw:[&_small]:whitespace-nowrap", "tw:viewport-620:[&_small]:hidden",
  ].join(" "),
  "dashboard_cash_column": [
    "dashboard-cash-column", "tw:flex", "tw:[align-items:end]", "tw:justify-center",
    "tw:gap-y-[2px]", "tw:gap-x-[2px]", "tw:min-h-[0]", "tw:[&_span]:w-[min(9px,_42%)]",
    "tw:[&_span]:rounded-[3px_3px_0_0]", "tw:[&_span]:[transition:opacity_150ms_var(--ease-standard)]",
  ].join(" "),
  "dashboard_cash_income": [
    "dashboard-cash-income", "tw:bg-[color:#238b45]", "tw:[background-image:none]",
  ].join(" "),
  "dashboard_cash_expense": [
    "dashboard-cash-expense", "tw:bg-[color:#d95b4f]", "tw:[background-image:none]",
  ].join(" "),
  "dashboard_payment_towers": [
    "dashboard-payment-towers", "tw:flex", "tw:min-h-[210px]", "tw:[align-items:end]",
    "tw:gap-y-[18px]", "tw:viewport-600:gap-y-[12px]", "tw:gap-x-[18px]", "tw:viewport-600:gap-x-[12px]",
    "tw:pt-[10px]", "tw:pr-[8px]", "tw:pb-[2px]", "tw:pl-[8px]",
    "tw:[&_article]:grid", "tw:[&_article]:[flex:1_1_120px]", "tw:[&_article]:min-w-[0]", "tw:[&_article]:gap-y-[6px]",
    "tw:[&_article]:gap-x-[6px]", "tw:[&_article_>_div]:flex", "tw:[&_article_>_div]:h-[142px]", "tw:viewport-600:[&_article_>_div]:h-[124px]",
    "tw:[&_article_>_div]:[align-items:end]", "tw:[&_article_>_div]:justify-center", "tw:[&_article_>_div]:border-b-[length:1px]", "tw:[&_article_>_div]:[border-bottom-style:solid]",
    "tw:[&_article_>_div]:border-b-[color:#d9e5ef]", "tw:[&_article_>_div]:bg-[color:transparent]", "tw:[&_article_>_div]:[background-image:repeating-linear-gradient(to_top,_transparent_0_34px,_#edf3f8_35px_36px)]", "tw:[&_article_i]:block",
    "tw:[&_article_i]:w-[min(60px,_68%)]", "tw:[&_article_i]:min-h-[8px]", "tw:[&_article_i]:rounded-[7px_7px_2px_2px]", "tw:[&_article_i]:bg-[color:transparent]",
    "tw:[&_article_i]:[background-image:linear-gradient(180deg,_#4d9ee9,_#1c62ae)]", "tw:[&_article_i]:[box-shadow:0_5px_12px_rgb(38_106_182_/_.18)]", "tw:[&_strong]:[overflow-x:hidden]", "tw:[&_strong]:[overflow-y:hidden]",
    "tw:[&_strong]:text-[color:#193b62]", "tw:[&_strong]:text-[.76rem]", "tw:[&_strong]:text-ellipsis", "tw:[&_strong]:whitespace-nowrap",
    "tw:[&_span]:text-[color:#16704a]", "tw:[&_span]:text-[.74rem]", "tw:[&_span]:font-[800]", "tw:[&_>_.muted]:[align-self:center]",
    "tw:viewport-600:[overflow-x:auto]", "tw:viewport-600:[&_article]:[flex-basis:112px]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "dashboard_ranking_chart": [
    "dashboard-ranking-chart", "tw:grid", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:[&_>_div]:grid", "tw:[&_>_div]:grid-cols-[minmax(75px,_1fr)_minmax(60px,_1.6fr)_auto]", "tw:[&_>_div]:items-center", "tw:[&_>_div]:gap-y-[8px]",
    "tw:[&_>_div]:gap-x-[8px]", "tw:[&_span]:[overflow-x:hidden]", "tw:[&_span]:[overflow-y:hidden]", "tw:[&_span]:text-[.76rem]",
    "tw:[&_span]:font-[700]", "tw:[&_span]:text-ellipsis", "tw:[&_span]:whitespace-nowrap", "tw:[&_i]:block",
    "tw:[&_i]:h-[7px]", "tw:[&_i]:[overflow-x:hidden]", "tw:[&_i]:[overflow-y:hidden]", "tw:[&_i]:rounded-[99px]",
    "tw:[&_i]:bg-[color:var(--panel-muted)]", "tw:[&_i]:[background-image:none]", "tw:[&_b]:block", "tw:[&_b]:h-[100%]",
    "tw:[&_b]:rounded-[inherit]", "tw:[&_b]:bg-[color:transparent]", "tw:[&_b]:[background-image:linear-gradient(90deg,_var(--brand),_#52a3e8)]", "tw:[&_strong]:text-[color:var(--muted)]",
    "tw:[&_strong]:text-[.72rem]",
  ].join(" "),
  "dashboard_ranking_chart_dashboard_ranking_chart_financial": [
    "dashboard-ranking-chart", "dashboard-ranking-chart-financial", "tw:grid", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:[&_>_div]:grid", "tw:[&_>_div]:grid-cols-[minmax(90px,_1fr)_minmax(50px,_1.35fr)_auto]", "tw:[&_>_div]:items-center",
    "tw:[&_>_div]:gap-y-[8px]", "tw:[&_>_div]:gap-x-[8px]", "tw:[&_span]:[overflow-x:hidden]", "tw:[&_span]:[overflow-y:hidden]",
    "tw:[&_span]:text-[.76rem]", "tw:[&_span]:font-[700]", "tw:[&_span]:text-ellipsis", "tw:[&_span]:whitespace-nowrap",
    "tw:[&_i]:block", "tw:[&_i]:h-[7px]", "tw:[&_i]:[overflow-x:hidden]", "tw:[&_i]:[overflow-y:hidden]",
    "tw:[&_i]:rounded-[99px]", "tw:[&_i]:bg-[color:var(--panel-muted)]", "tw:[&_i]:[background-image:none]", "tw:[&_b]:block",
    "tw:[&_b]:h-[100%]", "tw:[&_b]:rounded-[inherit]", "tw:[&_b]:bg-[color:transparent]", "tw:[&_b]:[background-image:linear-gradient(90deg,_var(--brand),_#52a3e8)]",
    "tw:[&_strong]:text-[color:#216245]", "tw:[&_strong]:text-[.72rem]", "tw:[&_strong]:min-w-[64px]", "tw:[&_strong]:[font-variant-numeric:tabular-nums]",
    "tw:[&_strong]:text-right",
  ].join(" "),
} as const;
