import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "stack_md": [
    "stack-md", "tw:[max-width:1180px]", "tw:[margin:0_auto]", "tw:[padding:24px]",
    "tw:grid", "tw:gap-y-[18px]", "tw:gap-x-[18px]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]",
    "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]", "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:[&_>_.section-card:last-child]:border-b-[length:1px]",
    "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]",
  ].join(" "),
  "page_header": sharedUtilities.pageHeader,
  "stack_xs": [
    "stack-xs", "tw:grid", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "muted": sharedUtilities.muted,
  "public_tournament_tabs": [
    "public-tournament-tabs", "tw:flex", "tw:flex-wrap", "tw:viewport-600:flex-nowrap",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#dbe5f1]", "tw:pb-[12px]", "tw:viewport-600:pb-[10px]", "tw:[&_a]:inline-flex",
    "tw:[&_a]:items-center", "tw:[&_a]:min-h-[38px]", "tw:[&_a]:pt-[0]", "tw:[&_a]:pr-[14px]",
    "tw:[&_a]:pb-[0]", "tw:[&_a]:pl-[14px]", "tw:[&_a]:border-t-[length:1px]", "tw:[&_a]:[border-top-style:solid]",
    "tw:[&_a]:border-t-[color:#cfdaea]", "tw:[&_a]:border-r-[length:1px]", "tw:[&_a]:[border-right-style:solid]", "tw:[&_a]:border-r-[color:#cfdaea]",
    "tw:[&_a]:border-b-[length:1px]", "tw:[&_a]:[border-bottom-style:solid]", "tw:[&_a]:border-b-[color:#cfdaea]", "tw:[&_a]:border-l-[length:1px]",
    "tw:[&_a]:[border-left-style:solid]", "tw:[&_a]:border-l-[color:#cfdaea]", "tw:[&_a]:rounded-[8px]", "tw:[&_a]:text-[color:#526681]",
    "tw:[&_a]:text-[.86rem]", "tw:[&_a]:font-[650]", "tw:[&_a]:[text-decoration:none]", "tw:[&_a:hover]:border-t-[color:var(--brand)]",
    "tw:[&_a:hover]:border-r-[color:var(--brand)]", "tw:[&_a:hover]:border-b-[color:var(--brand)]", "tw:[&_a:hover]:border-l-[color:var(--brand)]", "tw:[&_a:hover]:bg-[color:#edf5ff]",
    "tw:[&_a:hover]:[background-image:none]", "tw:[&_a:hover]:text-[color:var(--brand)]", "tw:[&_a.is-active]:border-t-[color:var(--brand)]", "tw:[&_a.is-active]:border-r-[color:var(--brand)]",
    "tw:[&_a.is-active]:border-b-[color:var(--brand)]", "tw:[&_a.is-active]:border-l-[color:var(--brand)]", "tw:[&_a.is-active]:bg-[color:#edf5ff]", "tw:[&_a.is-active]:[background-image:none]",
    "tw:[&_a.is-active]:text-[color:var(--brand)]", "tw:viewport-600:[overflow-x:auto]", "tw:viewport-600:[&_a]:[flex:0_0_auto]",
  ].join(" "),
  "section_card_public_tournament_content": [
    "section-card", "public-tournament-content", "tw:pt-[22px]", "tw:pr-[0]",
    "tw:pb-[22px]", "tw:pl-[0]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[0]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:[box-shadow:none]", "tw:grid", "tw:gap-y-[16px]",
    "tw:gap-x-[16px]", "tw:[&_>_header_h2]:mt-[0]", "tw:[&_>_header_h2]:mr-[0]", "tw:[&_>_header_h2]:mb-[0]",
    "tw:[&_>_header_h2]:ml-[0]", "tw:[&_>_header_p]:mt-[0]", "tw:[&_>_header_p]:mr-[0]", "tw:[&_>_header_p]:mb-[0]",
    "tw:[&_>_header_p]:ml-[0]",
  ].join(" "),
  "public_tournament_group": [
    "public-tournament-group", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:pt-[16px]", "tw:pr-[16px]", "tw:pb-[16px]", "tw:pl-[16px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#e0e8f3]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#e0e8f3]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#e0e8f3]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#e0e8f3]",
    "tw:rounded-[10px]", "tw:bg-[color:#fbfdff]", "tw:[background-image:none]", "tw:[&_h3]:mt-[0]",
    "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]", "tw:[&_p]:mt-[0]",
    "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_ul]:grid",
    "tw:[&_ul]:gap-y-[7px]", "tw:[&_ul]:gap-x-[7px]", "tw:[&_ul]:mt-[0]", "tw:[&_ul]:mr-[0]",
    "tw:[&_ul]:mb-[0]", "tw:[&_ul]:ml-[0]", "tw:[&_ul]:pt-[0]", "tw:[&_ul]:pr-[0]",
    "tw:[&_ul]:pb-[0]", "tw:[&_ul]:pl-[0]", "tw:[&_ul]:[list-style:none]", "tw:[&_li]:flex",
    "tw:[&_li]:flex-wrap", "tw:[&_li]:justify-between", "tw:[&_li]:gap-y-[8px]", "tw:[&_li]:gap-x-[18px]",
    "tw:[&_li]:pt-[10px]", "tw:[&_li]:pr-[12px]", "tw:[&_li]:pb-[10px]", "tw:[&_li]:pl-[12px]",
    "tw:[&_li]:rounded-[7px]", "tw:[&_li]:bg-[color:#f1f6fb]", "tw:[&_li]:[background-image:none]", "tw:[&_li]:text-[color:#27415f]",
    "tw:[&_li]:text-[.88rem]", "tw:[&_li_span]:text-[color:#61758f]", "tw:viewport-600:[&_li]:items-start", "tw:viewport-600:[&_li]:flex-col",
  ].join(" "),
} as const;
