import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "checkout_shell": [
    "checkout-shell", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)_minmax(360px,_0.48fr)]", "tw:viewport-1120:grid-cols-[1fr]",
    "tw:gap-y-[18px]", "tw:gap-x-[18px]", "tw:[align-items:start]",
  ].join(" "),
  "checkout_products": [
    "checkout-products", "tw:grid", "tw:gap-y-[16px]", "tw:gap-x-[16px]",
    "tw:pt-[20px]", "tw:pr-[20px]", "tw:pb-[20px]", "tw:pl-[20px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]",
    "tw:rounded-[var(--radius-lg)]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:[box-shadow:var(--shadow)]",
  ].join(" "),
  "field": [
    "checkout-search", "field", "tw:grid", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]", "tw:[&_input]:w-[100%]",
    "tw:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[14px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:text-[color:var(--text)]", "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[44px]",
    "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[14px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:var(--line)]",
    "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:var(--text)]",
    "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_input:focus]:[transform:translateY(-1px)]",
    "tw:[&_select:focus]:[outline:none]", "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]", "tw:[&_input[type=file]]:pt-[10px]",
    "tw:[&_input[type=file]]:pr-[14px]", "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]", "tw:[&_input[type=checkbox]]:w-[auto]",
    "tw:[&_input[type=checkbox]]:min-h-[auto]", "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]", "tw:[&_input[type=checkbox]]:pb-[0]",
    "tw:[&_input[type=checkbox]]:pl-[0]", "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]", "tw:[&_input[type=radio]]:pt-[0]",
    "tw:[&_input[type=radio]]:pr-[0]", "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]",
  ].join(" "),
  "checkout_product_grid": [
    "checkout-product-grid", "tw:grid", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:grid-cols-[repeat(auto-fill,_minmax(180px,_1fr))]",
  ].join(" "),
  "checkout_product": [
    "checkout-product", "tw:grid", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:min-h-[136px]", "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]",
    "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[var(--radius-md)]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]",
    "tw:text-[color:var(--text)]", "tw:text-left", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard)]", "tw:[&:hover:not(:disabled)]:[transform:translateY(-2px)]",
    "tw:[&:hover:not(:disabled)]:border-t-[color:var(--line-strong)]", "tw:[&:hover:not(:disabled)]:border-r-[color:var(--line-strong)]", "tw:[&:hover:not(:disabled)]:border-b-[color:var(--line-strong)]", "tw:[&:hover:not(:disabled)]:border-l-[color:var(--line-strong)]",
    "tw:[&:hover:not(:disabled)]:bg-[color:#ffffff]", "tw:[&:hover:not(:disabled)]:[background-image:none]", "tw:disabled:opacity-[0.58]", "tw:disabled:cursor-not-allowed",
    "tw:[&_strong]:leading-[1.2]", "tw:[&_span]:text-[color:var(--muted)]", "tw:[&_small]:text-[color:var(--muted)]", "tw:[&_em]:text-[color:var(--brand-strong)]",
    "tw:[&_em]:not-italic", "tw:[&_em]:font-[800]", "tw:[&.is-zero]:border-t-[color:#e7ad49]", "tw:[&.is-zero]:border-r-[color:#e7ad49]",
    "tw:[&.is-zero]:border-b-[color:#e7ad49]", "tw:[&.is-zero]:border-l-[color:#e7ad49]", "tw:[&.is-zero]:bg-[color:#fff9ec]", "tw:[&.is-zero]:[background-image:none]",
    "tw:[&.is-negative]:border-t-[color:#dc6666]", "tw:[&.is-negative]:border-r-[color:#dc6666]", "tw:[&.is-negative]:border-b-[color:#dc6666]", "tw:[&.is-negative]:border-l-[color:#dc6666]",
    "tw:[&.is-negative]:bg-[color:#fff2f2]", "tw:[&.is-negative]:[background-image:none]", "tw:[&.is-zero_small]:text-[color:#98640b]", "tw:[&.is-zero_small]:font-[800]",
    "tw:[&.is-negative_small]:text-[color:#b42318]", "tw:[&.is-negative_small]:font-[850]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "checkout_cart": [
    "checkout-cart", "tw:grid", "tw:gap-y-[16px]", "tw:gap-x-[16px]",
    "tw:pt-[20px]", "tw:pr-[20px]", "tw:pb-[20px]", "tw:pl-[20px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]",
    "tw:rounded-[var(--radius-lg)]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:[box-shadow:var(--shadow)]",
    "tw:sticky", "tw:viewport-1120:static", "tw:top-[18px]",
  ].join(" "),
  "checkout_cart_head": [
    "checkout-cart-head", "tw:flex", "tw:items-center", "tw:justify-between",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]",
    "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[1.8rem]", "tw:[&_>_strong]:text-[1.45rem]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "checkout_items": [
    "checkout-items", "tw:grid", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
    "tw:min-h-[180px]", "tw:[align-content:start]",
  ].join(" "),
  "checkout_item": [
    "checkout-item", "tw:flex", "tw:items-center", "tw:justify-between",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:pt-[12px]", "tw:pr-[12px]",
    "tw:pb-[12px]", "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[var(--radius-md)]", "tw:bg-[color:var(--panel-muted)]",
    "tw:[background-image:none]", "tw:[&_>_div:first-child]:grid", "tw:[&_>_div:first-child]:gap-y-[4px]", "tw:[&_>_div:first-child]:gap-x-[4px]",
    "tw:[&_>_div:first-child]:min-w-[0]", "tw:[&_span]:text-[color:var(--muted)]", "tw:[&_span]:text-[0.9rem]",
  ].join(" "),
  "checkout_quantity": [
    "checkout-quantity", "tw:grid", "tw:grid-cols-[34px_56px_34px]", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:items-center", "tw:[&_button]:min-h-[34px]", "tw:[&_button]:border-t-[length:1px]",
    "tw:[&_button]:[border-top-style:solid]", "tw:[&_button]:border-t-[color:var(--line)]", "tw:[&_button]:border-r-[length:1px]", "tw:[&_button]:[border-right-style:solid]",
    "tw:[&_button]:border-r-[color:var(--line)]", "tw:[&_button]:border-b-[length:1px]", "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:var(--line)]",
    "tw:[&_button]:border-l-[length:1px]", "tw:[&_button]:[border-left-style:solid]", "tw:[&_button]:border-l-[color:var(--line)]", "tw:[&_button]:rounded-[999px]",
    "tw:[&_button]:bg-[color:#ffffff]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-center", "tw:[&_button]:font-[800]",
    "tw:[&_input]:min-h-[34px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[999px]", "tw:[&_input]:bg-[color:#ffffff]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:text-center",
  ].join(" "),
  "checkout_fields": [
    "checkout-fields", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)_minmax(150px,_0.72fr)]", "tw:viewport-1120:grid-cols-[1fr]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]",
  ].join(" "),
  "field_2": sharedUtilities.field,
  "checkout_total": [
    "checkout-total", "tw:flex", "tw:items-center", "tw:justify-between",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:pt-[14px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:[&_strong]:text-[1.45rem]", "tw:[&_span]:text-[color:var(--muted)]",
    "tw:[&_span]:font-[700]", "tw:[&_span]:uppercase",
  ].join(" "),
  "checkout_actions": [
    "checkout-actions", "tw:flex", "tw:items-center", "tw:justify-between",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]",
  ].join(" "),
  "button": sharedUtilities.button,
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
} as const;
