import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "accounts_ledger_stack_md": [
    "accounts-ledger", "stack-md", "tw:w-[100%]", "tw:max-w-[none]",
    "tw:text-[90%]", "tw:viewport-700:[&_>_*]:min-w-[0]", "tw:grid", "tw:gap-y-[18px]",
    "tw:gap-x-[18px]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]",
    "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]",
  ].join(" "),
  "command_modal_backdrop": sharedUtilities.commandModalBackdrop,
  "financial_entry_modal_financial_entry_modal_small": [
    "financial-entry-modal", "financial-entry-modal-small", "tw:w-[min(100%,_1080px)]", "tw:max-h-[calc(100vh_-_44px)]",
    "tw:[overflow-x:auto]", "tw:[overflow-y:auto]", "tw:pt-[20px]", "tw:viewport-600:pt-[16px]",
    "tw:pr-[20px]", "tw:viewport-600:pr-[16px]", "tw:pb-[20px]", "tw:viewport-600:pb-[16px]",
    "tw:pl-[20px]", "tw:viewport-600:pl-[16px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(255_255_255_/_.7)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(255_255_255_/_.7)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(255_255_255_/_.7)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(255_255_255_/_.7)]", "tw:rounded-[14px]", "tw:bg-[color:var(--panel)]",
    "tw:[background-image:none]", "tw:[box-shadow:0_26px_80px_rgb(15_23_42_/_.34)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:justify-between",
    "tw:[&_>_header]:gap-y-[12px]", "tw:[&_>_header]:gap-x-[12px]", "tw:[&_>_header]:items-start", "tw:[&_>_header]:mb-[18px]",
    "tw:[&_>_header]:pb-[14px]", "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:var(--line)]",
    "tw:[&_header_span]:block", "tw:[&_header_span]:mb-[3px]", "tw:[&_header_span]:text-[color:var(--brand)]", "tw:[&_header_span]:text-[.68rem]",
    "tw:[&_header_span]:font-[800]", "tw:[&_header_span]:tracking-[.1em]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]",
    "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_>_p]:mb-[16px]", "tw:[&_>_p]:text-[color:var(--muted)]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "accounts_ledger_header": [
    "accounts-ledger-header", "tw:flex", "tw:items-center", "tw:viewport-600:items-start",
    "tw:justify-between", "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:[&_h1]:mt-[0]",
    "tw:[&_h1]:mr-[0]", "tw:[&_h1]:mb-[0]", "tw:[&_h1]:ml-[0]", "tw:[&_p]:mt-[4px]",
    "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:viewport-600:flex-col",
    "tw:viewport-700:flex-wrap",
  ].join(" "),
  "accounts_filters": [
    "accounts-filters", "tw:grid", "tw:grid-cols-[repeat(6,_minmax(120px,_1fr))]", "tw:viewport-980:grid-cols-[repeat(3,_minmax(150px,_1fr))]",
    "tw:viewport-700:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:items-center",
    "tw:pt-[12px]", "tw:pr-[12px]", "tw:pb-[12px]", "tw:pl-[12px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]",
    "tw:rounded-[10px]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]", "tw:[&_input]:w-[100%]",
    "tw:[&_input]:min-w-[0]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-w-[0]", "tw:[&_label]:flex",
    "tw:[&_label]:items-center", "tw:[&_label]:gap-y-[6px]", "tw:[&_label]:gap-x-[6px]", "tw:[&_label]:text-[color:var(--muted)]",
    "tw:[&_label]:text-[.75rem]", "tw:[&_label]:whitespace-nowrap", "tw:viewport-700:[&_label]:[white-space:normal]", "tw:[&_label_input]:w-[auto]",
    "tw:[&_.accounts-filters-submit]:min-h-[38px]", "tw:[&_.accounts-filters-submit]:font-[800]", "tw:[&_.accounts-filters-submit]:[box-shadow:0_5px_12px_rgb(20_92_179_/_.2)]",
  ].join(" "),
  "accounts_client_filter": [
    "accounts-client-filter", "tw:relative", "tw:min-w-[0]",
  ].join(" "),
  "client_search_panel_accounts_client_suggestions": [
    "client-search-panel", "accounts-client-suggestions", "tw:grid", "tw:max-h-[260px]",
    "tw:mt-[-6px]", "tw:[overflow-y:auto]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line-strong)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line-strong)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line-strong)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line-strong)]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--panel-muted)]",
    "tw:[background-image:none]", "tw:[box-shadow:0_10px_22px_rgb(15_23_42_/_.12)]", "tw:absolute", "tw:z-[8]",
    "tw:top-[calc(100%_+_5px)]", "tw:right-[0]", "tw:left-[0]",
  ].join(" "),
  "client_search_result": [
    "client-search-result", "tw:grid", "tw:grid-cols-[30px_minmax(0,_1fr)]", "tw:gap-y-[9px]",
    "tw:gap-x-[9px]", "tw:w-[100%]", "tw:pt-[9px]", "tw:pr-[11px]",
    "tw:pb-[9px]", "tw:pl-[11px]", "tw:border-t-[length:0]", "tw:[border-top-style:none]",
    "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:bg-[color:transparent]", "tw:[background-image:none]",
    "tw:text-[color:var(--text)]", "tw:text-left", "tw:[&:last-child]:border-b-[length:0]", "tw:[&:last-child]:[border-bottom-style:none]",
    "tw:[&:last-child]:border-b-[color:currentColor]", "tw:hover:bg-[color:var(--brand-soft)]", "tw:hover:[background-image:none]", "tw:hover:[outline:none]",
    "tw:focus-visible:bg-[color:var(--brand-soft)]", "tw:focus-visible:[background-image:none]", "tw:focus-visible:[outline:none]", "tw:[&_>_span:last-child]:grid",
    "tw:[&_>_span:last-child]:gap-y-[2px]", "tw:[&_>_span:last-child]:gap-x-[2px]", "tw:[&_>_span:last-child]:min-w-[0]", "tw:[&_strong]:[overflow-x:hidden]",
    "tw:[&_strong]:[overflow-y:hidden]", "tw:[&_strong]:text-ellipsis", "tw:[&_strong]:whitespace-nowrap", "tw:[&_strong]:text-[.82rem]",
    "tw:[&_small]:text-[color:var(--muted)]", "tw:[&_small]:text-[.72rem]",
  ].join(" "),
  "client_search_avatar": [
    "client-search-avatar", "tw:grid", "tw:w-[30px]", "tw:h-[30px]",
    "tw:place-items-center", "tw:rounded-[50%]", "tw:bg-[color:var(--brand)]", "tw:[background-image:none]",
    "tw:text-[color:#fff]", "tw:text-[.72rem]", "tw:font-[800]",
  ].join(" "),
  "client_search_empty": [
    "client-search-empty", "tw:pt-[12px]", "tw:pr-[12px]", "tw:pb-[12px]",
    "tw:pl-[12px]", "tw:text-[color:var(--muted)]", "tw:text-[.8rem]",
  ].join(" "),
  "control_toggle": sharedUtilities.controlToggle,
  "button_button_primary_accounts_filters_submit": [
    "button", "button-primary", "accounts-filters-submit", "tw:inline-flex",
    "tw:items-center", "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:min-h-[36px]", "tw:pt-[0]", "tw:pr-[12px]", "tw:pb-[0]",
    "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--brand)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--brand)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--brand)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--brand)]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--brand)]", "tw:[background-image:none]",
    "tw:text-[color:#ffffff]", "tw:text-[0.86rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--brand-strong)]",
    "tw:hover:border-r-[color:var(--brand-strong)]", "tw:hover:border-b-[color:var(--brand-strong)]", "tw:hover:border-l-[color:var(--brand-strong)]", "tw:hover:[transform:translateY(-1px)]",
    "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]",
    "tw:[&:active]:[box-shadow:none]", "tw:hover:bg-[color:var(--brand-strong)]", "tw:hover:[background-image:none]", "tw:viewport-700:[grid-column:1_/_-1]",
  ].join(" "),
  "accounts_ledger_totals": [
    "accounts-ledger-totals", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_220px))]", "tw:viewport-700:grid-cols-[repeat(2,_minmax(0,_1fr))]",
    "tw:viewport-440:grid-cols-[minmax(0,_1fr)]", "tw:gap-y-[9px]", "tw:gap-x-[9px]", "tw:[&_article]:grid",
    "tw:[&_article]:gap-y-[3px]", "tw:[&_article]:gap-x-[3px]", "tw:[&_article]:pt-[10px]", "tw:[&_article]:pr-[12px]",
    "tw:[&_article]:pb-[10px]", "tw:[&_article]:pl-[12px]", "tw:[&_article]:border-t-[length:1px]", "tw:[&_article]:[border-top-style:solid]",
    "tw:[&_article]:border-t-[color:var(--line)]", "tw:[&_article]:border-r-[length:1px]", "tw:[&_article]:[border-right-style:solid]", "tw:[&_article]:border-r-[color:var(--line)]",
    "tw:[&_article]:border-b-[length:1px]", "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:var(--line)]", "tw:[&_article]:border-l-[length:1px]",
    "tw:[&_article]:[border-left-style:solid]", "tw:[&_article]:border-l-[color:var(--line)]", "tw:[&_article]:rounded-[9px]", "tw:[&_article]:bg-[color:var(--panel-muted)]",
    "tw:[&_article]:[background-image:none]", "tw:[&_span]:text-[color:var(--muted)]", "tw:[&_span]:text-[.69rem]", "tw:[&_span]:font-[800]",
    "tw:[&_span]:uppercase", "tw:[&_small]:text-[color:var(--muted)]", "tw:[&_small]:text-[.69rem]", "tw:[&_strong]:text-[color:var(--text)]",
    "tw:[&_strong]:text-[.96rem]", "tw:[&_.accounts-ledger-total-selected]:border-t-[color:#95bee8]", "tw:[&_.accounts-ledger-total-selected]:border-r-[color:#95bee8]", "tw:[&_.accounts-ledger-total-selected]:border-b-[color:#95bee8]",
    "tw:[&_.accounts-ledger-total-selected]:border-l-[color:#95bee8]", "tw:[&_.accounts-ledger-total-selected]:bg-[color:#eff7ff]", "tw:[&_.accounts-ledger-total-selected]:[background-image:none]", "tw:[&_.accounts-ledger-total-selected_strong]:text-[color:var(--brand-strong)]",
  ].join(" "),
  "form_success": sharedUtilities.formSuccess,
  "accounts_bulk_actions": [
    "accounts-bulk-actions", "tw:flex", "tw:flex-wrap", "tw:items-center",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:pt-[9px]", "tw:pr-[12px]",
    "tw:pb-[9px]", "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#c8dceb]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#c8dceb]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#c8dceb]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#c8dceb]", "tw:rounded-[9px]", "tw:bg-[color:#f5faff]",
    "tw:[background-image:none]", "tw:[&_strong]:text-[color:#153b61]", "tw:[&_strong]:text-[.8rem]", "tw:[&_>_span]:mr-[auto]",
    "tw:[&_>_span]:text-[color:#60748a]", "tw:[&_>_span]:text-[.73rem]",
  ].join(" "),
  "button_button_primary_button_small": sharedUtilities.buttonButtonPrimaryButtonSmall,
  "button_button_danger_button_small": sharedUtilities.buttonButtonDangerButtonSmall,
  "accounts_ledger_list": [
    "accounts-ledger-list", "tw:[overflow-x:hidden]", "tw:viewport-980:[overflow-x:auto]", "tw:[overflow-y:hidden]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]",
    "tw:rounded-[12px]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:viewport-700:max-w-[100%]",
  ].join(" "),
  "accounts_ledger_columns": [
    "accounts-ledger-columns", "tw:grid", "tw:grid-cols-[30px_112px_minmax(130px,_.95fr)_minmax(100px,_.75fr)_minmax(180px,_1.4fr)_minmax(125px,_.8fr)_minmax(104px,_.72fr)_minmax(360px,_1.65fr)]", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:items-center", "tw:pt-[9px]", "tw:pr-[13px]",
    "tw:pb-[9px]", "tw:pl-[13px]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]", "tw:text-[color:var(--muted)]",
    "tw:text-[.62rem]", "tw:font-[800]", "tw:tracking-[.02em]", "tw:uppercase",
    "tw:[&_input]:w-[15px]", "tw:[&_input]:h-[15px]", "tw:[&_input]:[accent-color:var(--brand)]", "tw:viewport-980:min-w-[920px]",
  ].join(" "),
  "accounts_ledger_row_accounts_ledger_row_clickable": [
    "accounts-ledger-row", "accounts-ledger-row-clickable", "tw:grid", "tw:grid-cols-[30px_112px_minmax(130px,_.95fr)_minmax(100px,_.75fr)_minmax(180px,_1.4fr)_minmax(125px,_.8fr)_minmax(104px,_.72fr)_minmax(360px,_1.65fr)]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:items-center", "tw:min-h-[56px]",
    "tw:pt-[9px]", "tw:pr-[13px]", "tw:pb-[9px]", "tw:pl-[13px]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:text-[.74rem]",
    "tw:[&:nth-of-type(even)]:bg-[color:color-mix(in_srgb,_var(--panel-muted)_42%,_var(--panel))]", "tw:[&:nth-of-type(even)]:[background-image:none]", "tw:[&:last-child]:border-b-[length:0]", "tw:[&:last-child]:[border-bottom-style:none]",
    "tw:[&:last-child]:border-b-[color:currentColor]", "tw:[&_>_span]:grid", "tw:[&_>_span]:gap-y-[3px]", "tw:[&_>_span]:gap-x-[3px]",
    "tw:[&_>_span]:min-w-[0]", "tw:[&_>_strong]:min-w-[0]", "tw:[&_>_strong]:[overflow-x:hidden]", "tw:[&_>_strong]:[overflow-y:hidden]",
    "tw:[&_>_strong]:text-ellipsis", "tw:[&_>_strong]:whitespace-nowrap", "tw:[&_small]:text-[color:var(--muted)]", "tw:[&_small]:text-[.7rem]",
    "tw:viewport-980:min-w-[920px]", "tw:cursor-pointer", "tw:[transition:background_150ms_var(--ease-standard)]", "tw:hover:bg-[color:color-mix(in_srgb,_var(--brand-soft)_52%,_var(--panel))]",
    "tw:hover:[background-image:none]", "tw:[&_strong_a]:text-[color:var(--brand-strong)]", "tw:[&_strong_a]:[text-decoration:underline]", "tw:[&_strong_a]:[text-decoration-color:transparent]",
    "tw:[&_strong_a]:[text-underline-offset:3px]", "tw:[&_strong_a:hover]:[text-decoration-color:currentColor]",
  ].join(" "),
  "accounts_ledger_row_overdue": [
    "accounts-ledger-row-overdue", "tw:border-l-[length:4px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#c92a2a]",
    "tw:bg-[color:#fff1f1]", "tw:[background-image:none]", "tw:[&:nth-of-type(even)]:border-l-[length:4px]", "tw:[&:nth-of-type(even)]:[border-left-style:solid]",
    "tw:[&:nth-of-type(even)]:border-l-[color:#c92a2a]", "tw:[&:nth-of-type(even)]:bg-[color:#fff1f1]", "tw:[&:nth-of-type(even)]:[background-image:none]", "tw:hover:bg-[color:#ffe4e4]",
    "tw:hover:[background-image:none]",
  ].join(" "),
  "accounts_ledger_selection": [
    "accounts-ledger-selection", "tw:place-items-center", "tw:[&_input]:w-[15px]", "tw:[&_input]:h-[15px]",
    "tw:[&_input]:[accent-color:var(--brand)]",
  ].join(" "),
  "account_comanda_link": [
    "account-comanda-link", "tw:block", "tw:w-[fit-content]", "tw:mt-[4px]",
    "tw:text-[color:#1f68af]", "tw:text-[.69rem]", "tw:font-[700]", "tw:[text-decoration:none]",
    "tw:hover:[text-decoration:underline]",
  ].join(" "),
  "account_status": [
    "account-status", "tw:w-[fit-content]", "tw:pt-[3px]", "tw:pr-[6px]",
    "tw:pb-[3px]", "tw:pl-[6px]", "tw:rounded-[6px]", "tw:bg-[color:var(--panel-muted)]",
    "tw:[background-image:none]", "tw:text-[color:var(--muted)]", "tw:text-[.68rem]", "tw:not-italic",
    "tw:font-[800]", "tw:[&.account-status-paid]:bg-[color:#e6f6eb]", "tw:[&.account-status-paid]:[background-image:none]", "tw:[&.account-status-paid]:text-[color:#16723a]",
    "tw:[&.account-status-pending]:bg-[color:#fff5df]", "tw:[&.account-status-pending]:[background-image:none]", "tw:[&.account-status-pending]:text-[color:#936400]", "tw:[&.account-status-voided]:bg-[color:#fce9e8]",
    "tw:[&.account-status-voided]:[background-image:none]", "tw:[&.account-status-voided]:text-[color:#b42318]", "tw:[&.account-status-overdue]:w-[fit-content]", "tw:[&.account-status-overdue]:pt-[3px]",
    "tw:[&.account-status-overdue]:pr-[6px]", "tw:[&.account-status-overdue]:pb-[3px]", "tw:[&.account-status-overdue]:pl-[6px]", "tw:[&.account-status-overdue]:rounded-[5px]",
    "tw:[&.account-status-overdue]:bg-[color:#b42318]", "tw:[&.account-status-overdue]:[background-image:none]", "tw:[&.account-status-overdue]:text-[color:#fff]", "tw:[&.account-status-overdue]:text-[.65rem]",
    "tw:[&.account-status-overdue]:not-italic", "tw:[&.account-status-overdue]:font-[850]", "tw:[&.account-status-overdue]:tracking-[.03em]",
  ].join(" "),
  "account_status_overdue": [
    "account-status-overdue", "tw:w-[fit-content]", "tw:pt-[3px]", "tw:pr-[6px]",
    "tw:pb-[3px]", "tw:pl-[6px]", "tw:rounded-[5px]", "tw:bg-[color:#b42318]",
    "tw:[background-image:none]", "tw:text-[color:#fff]", "tw:text-[.65rem]", "tw:not-italic",
    "tw:font-[850]", "tw:tracking-[.03em]",
  ].join(" "),
  "accounts_ledger_actions": [
    "accounts-ledger-actions", "tw:flex!", "tw:flex-nowrap", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:justify-end", "tw:whitespace-nowrap",
  ].join(" "),
  "button_button_small_button_primary": sharedUtilities.buttonButtonSmallButtonPrimary,
  "button_button_small_button_danger": [
    "button", "button-small", "button-danger", "tw:inline-flex",
    "tw:items-center", "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:min-h-[30px]", "tw:pt-[5px]", "tw:pr-[8px]", "tw:pb-[5px]",
    "tw:pl-[8px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#b42318]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#b42318]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#b42318]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#b42318]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:#b42318]", "tw:[background-image:none]",
    "tw:text-[color:#fff]", "tw:text-[.72rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--danger)]",
    "tw:hover:border-r-[color:var(--danger)]", "tw:hover:border-b-[color:var(--danger)]", "tw:hover:border-l-[color:var(--danger)]", "tw:hover:[transform:translateY(-1px)]",
    "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]",
    "tw:[&:active]:[box-shadow:none]", "tw:hover:bg-[color:rgba(191,_63,_56,_0.14)]", "tw:hover:[background-image:none]", "tw:hover:text-[color:#992f29]",
  ].join(" "),
  "accounts_ledger_empty": [
    "accounts-ledger-empty", "tw:grid", "tw:min-h-[180px]", "tw:place-items-center",
    "tw:text-[color:var(--muted)]",
  ].join(" "),
  "financial_entry_modal": [
    "financial-entry-modal", "tw:w-[min(100%,_1080px)]", "tw:max-h-[calc(100vh_-_44px)]", "tw:[overflow-x:auto]",
    "tw:[overflow-y:auto]", "tw:pt-[20px]", "tw:viewport-600:pt-[16px]", "tw:pr-[20px]",
    "tw:viewport-600:pr-[16px]", "tw:pb-[20px]", "tw:viewport-600:pb-[16px]", "tw:pl-[20px]",
    "tw:viewport-600:pl-[16px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(255_255_255_/_.7)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(255_255_255_/_.7)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(255_255_255_/_.7)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgb(255_255_255_/_.7)]", "tw:rounded-[14px]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]",
    "tw:[box-shadow:0_26px_80px_rgb(15_23_42_/_.34)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[12px]",
    "tw:[&_>_header]:gap-x-[12px]", "tw:[&_>_header]:items-start", "tw:[&_>_header]:mb-[18px]", "tw:[&_>_header]:pb-[14px]",
    "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:var(--line)]", "tw:[&_header_span]:block",
    "tw:[&_header_span]:mb-[3px]", "tw:[&_header_span]:text-[color:var(--brand)]", "tw:[&_header_span]:text-[.68rem]", "tw:[&_header_span]:font-[800]",
    "tw:[&_header_span]:tracking-[.1em]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]",
    "tw:[&_h2]:ml-[0]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_>_p]:mb-[16px]", "tw:[&_>_p]:text-[color:var(--muted)]",
  ].join(" "),
  "grid_form": sharedUtilities.gridForm,
  "field": sharedUtilities.field,
  "client_search_panel_form_full": [
    "client-search-panel", "form-full", "tw:grid", "tw:max-h-[260px]",
    "tw:mt-[-6px]", "tw:[overflow-y:auto]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line-strong)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line-strong)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line-strong)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line-strong)]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--panel-muted)]",
    "tw:[background-image:none]", "tw:[box-shadow:0_10px_22px_rgb(15_23_42_/_.12)]", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  "supplier_suggestions_form_full": [
    "supplier-suggestions", "form-full", "tw:flex", "tw:flex-wrap",
    "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:mt-[-6px]", "tw:[&_button]:pt-[5px]",
    "tw:[&_button]:pr-[8px]", "tw:[&_button]:pb-[5px]", "tw:[&_button]:pl-[8px]", "tw:[&_button]:border-t-[length:1px]",
    "tw:[&_button]:[border-top-style:solid]", "tw:[&_button]:border-t-[color:var(--line)]", "tw:[&_button]:border-r-[length:1px]", "tw:[&_button]:[border-right-style:solid]",
    "tw:[&_button]:border-r-[color:var(--line)]", "tw:[&_button]:border-b-[length:1px]", "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:var(--line)]",
    "tw:[&_button]:border-l-[length:1px]", "tw:[&_button]:[border-left-style:solid]", "tw:[&_button]:border-l-[color:var(--line)]", "tw:[&_button]:rounded-[6px]",
    "tw:[&_button]:bg-[color:var(--panel-muted)]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:var(--text)]", "tw:[&_button]:text-[.74rem]",
    "tw:[&_.supplier-create]:border-t-[color:var(--brand)]", "tw:[&_.supplier-create]:border-r-[color:var(--brand)]", "tw:[&_.supplier-create]:border-b-[color:var(--brand)]", "tw:[&_.supplier-create]:border-l-[color:var(--brand)]",
    "tw:[&_.supplier-create]:text-[color:var(--brand)]", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  "field_select_button": [
    "field-select-button", "tw:w-[100%]", "tw:min-h-[36px]", "tw:pt-[8px]",
    "tw:pr-[10px]", "tw:pb-[8px]", "tw:pl-[10px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[7px]",
    "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:text-[color:var(--text)]", "tw:text-left",
  ].join(" "),
  "field_form_full": sharedUtilities.fieldFormFull,
  "discount_control": [
    "discount-control", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)_76px]", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:[&_input]:min-w-[0]", "tw:[&_select]:min-w-[0]", "tw:[&_select]:whitespace-nowrap",
  ].join(" "),
  "form_full_financial_entry_toggles": [
    "form-full", "financial-entry-toggles", "tw:[grid-column:1_/_-1]", "tw:flex",
    "tw:flex-wrap", "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:items-center",
    "tw:[&_.control-toggle_input:disabled_+_span]:opacity-[.45]", "tw:[&_.control-toggle_input:disabled_+_span]:cursor-not-allowed",
  ].join(" "),
  "financial_boleto_validation": [
    "form-message", "form-message-error", "financial-boleto-validation", "tw:grid",
    "tw:gap-y-[3px]", "tw:gap-x-[3px]", "tw:mt-[8px]", "tw:pt-[10px]",
    "tw:pr-[12px]", "tw:pb-[10px]", "tw:pl-[12px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#efb9b2]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#efb9b2]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#efb9b2]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#efb9b2]", "tw:rounded-[8px]",
    "tw:bg-[color:#fff4f2]", "tw:[background-image:none]", "tw:text-[color:#9f291f]", "tw:text-[.76rem]",
    "tw:font-[600]", "tw:leading-[1.35]", "tw:[&_strong]:text-[color:#8d2119]", "tw:[&_strong]:text-[.78rem]",
  ].join(" "),
  "financial_notes_field": [
    "financial-notes-field", "tw:w-[100%]", "tw:min-h-[92px]", "tw:[resize:vertical]",
    "tw:leading-[1.45]",
  ].join(" "),
  "modal_actions_form_full": [
    "modal-actions", "form-full", "tw:flex", "tw:justify-end",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:mt-[8px]", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  "button": sharedUtilities.button,
  "button_button_success": [
    "button", "button-success", "tw:inline-flex", "tw:items-center",
    "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:min-h-[36px]",
    "tw:pt-[0]", "tw:pr-[12px]", "tw:pb-[0]", "tw:pl-[12px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#16803c]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#16803c]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#16803c]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#16803c]",
    "tw:rounded-[var(--radius-control)]", "tw:bg-[color:#238b45]", "tw:[background-image:none]", "tw:text-[color:#fff]",
    "tw:text-[0.86rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--line-strong)]", "tw:hover:border-r-[color:var(--line-strong)]",
    "tw:hover:border-b-[color:var(--line-strong)]", "tw:hover:border-l-[color:var(--line-strong)]", "tw:hover:[transform:translateY(-1px)]", "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]",
    "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]", "tw:[&:active]:[box-shadow:none]",
    "tw:hover:bg-[color:#176f36]", "tw:hover:[background-image:none]",
  ].join(" "),
  "financial_setting_quick_create": [
    "financial-setting-quick-create", "tw:flex", "tw:items-center", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:w-[fit-content]", "tw:max-w-[100%]", "tw:mb-[12px]",
    "tw:[&_input]:w-[min(250px,_55vw)]", "tw:[&_input]:min-w-[0]", "tw:[&_input]:[flex:0_1_250px]",
  ].join(" "),
  "simple_list_financial_category_list": [
    "simple-list", "financial-category-list", "tw:flex", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]",
    "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:flex-wrap", "tw:[&_.button]:w-[auto]", "tw:[&_.button]:min-h-[32px]",
    "tw:[&_.button]:pt-[5px]", "tw:[&_.button]:pr-[10px]", "tw:[&_.button]:pb-[5px]", "tw:[&_.button]:pl-[10px]",
    "tw:[&_.button]:text-[.76rem]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "form_full_account_settlement_history": [
    "form-full", "account-settlement-history", "tw:[grid-column:1_/_-1]", "tw:grid",
    "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:pt-[11px]", "tw:pr-[11px]",
    "tw:pb-[11px]", "tw:pl-[11px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--panel-muted)]",
    "tw:[background-image:none]", "tw:[&_strong]:text-[.78rem]", "tw:[&_span]:text-[color:var(--muted)]", "tw:[&_span]:text-[.74rem]",
  ].join(" "),
  "account_payment_summary": [
    "account-payment-summary", "tw:grid", "tw:grid-cols-[repeat(4,_minmax(0,_1fr))]", "tw:viewport-980:grid-cols-[repeat(2,_minmax(0,_1fr))]",
    "tw:viewport-600:grid-cols-[1fr]", "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:mb-[16px]",
    "tw:[&_span]:grid", "tw:[&_span]:gap-y-[4px]", "tw:[&_span]:gap-x-[4px]", "tw:[&_span]:pt-[9px]",
    "tw:[&_span]:pr-[9px]", "tw:[&_span]:pb-[9px]", "tw:[&_span]:pl-[9px]", "tw:[&_span]:border-t-[length:1px]",
    "tw:[&_span]:[border-top-style:solid]", "tw:[&_span]:border-t-[color:var(--line)]", "tw:[&_span]:border-r-[length:1px]", "tw:[&_span]:[border-right-style:solid]",
    "tw:[&_span]:border-r-[color:var(--line)]", "tw:[&_span]:border-b-[length:1px]", "tw:[&_span]:[border-bottom-style:solid]", "tw:[&_span]:border-b-[color:var(--line)]",
    "tw:[&_span]:border-l-[length:1px]", "tw:[&_span]:[border-left-style:solid]", "tw:[&_span]:border-l-[color:var(--line)]", "tw:[&_span]:rounded-[8px]",
    "tw:[&_span]:bg-[color:var(--panel-muted)]", "tw:[&_span]:[background-image:none]", "tw:[&_span]:text-[color:var(--muted)]", "tw:[&_span]:text-[.7rem]",
    "tw:[&_b]:text-[color:var(--text)]", "tw:[&_b]:text-[.84rem]",
  ].join(" "),
  "modal_actions": [
    "modal-actions", "tw:flex", "tw:justify-end", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:mt-[8px]",
  ].join(" "),
  "button_button_danger": sharedUtilities.buttonButtonDanger,
} as const;
