import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "client_workspace": [
    "client-workspace", "tw:grid", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:pt-[16px]",
  ].join(" "),
  "client_filter_bar": [
    "client-filter-bar", "tw:grid", "tw:grid-cols-[repeat(6,_minmax(130px,_1fr))]", "tw:viewport-1000:grid-cols-[repeat(3,_minmax(0,_1fr))]",
    "tw:viewport-620:grid-cols-[1fr]", "tw:gap-y-[9px]", "tw:gap-x-[9px]", "tw:pt-[13px]",
    "tw:pr-[13px]", "tw:pb-[13px]", "tw:pl-[13px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#d7e2ef]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#d7e2ef]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d7e2ef]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d7e2ef]", "tw:rounded-[10px]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[4px]",
    "tw:[&_label]:gap-x-[4px]", "tw:[&_label]:text-[color:#526681]", "tw:[&_label]:text-[.67rem]", "tw:[&_label]:font-[750]",
    "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[33px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[8px]",
    "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[8px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]",
    "tw:[&_input]:border-t-[color:#c9d8e9]", "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#c9d8e9]",
    "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:#c9d8e9]", "tw:[&_input]:border-l-[length:1px]",
    "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#c9d8e9]", "tw:[&_input]:rounded-[6px]", "tw:[&_input]:bg-[color:#fbfdff]",
    "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:#203650]", "tw:[&_input]:[font:inherit]", "tw:[&_input]:text-[.76rem]",
    "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[33px]", "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[8px]",
    "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[8px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]",
    "tw:[&_select]:border-t-[color:#c9d8e9]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#c9d8e9]",
    "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:#c9d8e9]", "tw:[&_select]:border-l-[length:1px]",
    "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#c9d8e9]", "tw:[&_select]:rounded-[6px]", "tw:[&_select]:bg-[color:#fbfdff]",
    "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:#203650]", "tw:[&_select]:[font:inherit]", "tw:[&_select]:text-[.76rem]",
    "tw:min-w-0 tw:[&>*]:min-w-0 tw:[&_input]:min-w-0 tw:[&_select]:min-w-0",
  ].join(" "),
  "client_filter_actions": [
    "client-filter-actions", "tw:[grid-column:1_/_-1]", "tw:flex", "tw:flex-wrap",
    "tw:gap-y-[7px]", "tw:gap-x-[7px]", "tw:pt-[2px]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "button": sharedUtilities.button,
  "button_client_import_control": [
    "button", "client-import-control", "tw:inline-flex!", "tw:items-center",
    "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:min-h-[36px]",
    "tw:pt-[0]", "tw:pr-[12px]", "tw:pb-[0]", "tw:pl-[12px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]",
    "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:text-[color:var(--text)]",
    "tw:text-[0.86rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--line-strong)]", "tw:hover:border-r-[color:var(--line-strong)]",
    "tw:hover:border-b-[color:var(--line-strong)]", "tw:hover:border-l-[color:var(--line-strong)]", "tw:hover:[transform:translateY(-1px)]", "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]",
    "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]", "tw:[&:active]:[box-shadow:none]",
    "tw:cursor-pointer", "tw:[&_input]:hidden",
  ].join(" "),
  "client_workspace_message": [
    "client-workspace-message", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:pt-[8px]", "tw:pr-[10px]", "tw:pb-[8px]",
    "tw:pl-[10px]", "tw:border-l-[length:3px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#2379cf]",
    "tw:bg-[color:#f2f8ff]", "tw:[background-image:none]", "tw:text-[color:#23598f]", "tw:text-[.74rem]",
  ].join(" "),
  "client_bulk_actions": [
    "client-bulk-actions", "tw:flex", "tw:flex-wrap", "tw:items-center",
    "tw:viewport-620:items-stretch", "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:pt-[10px]",
    "tw:pr-[13px]", "tw:pb-[10px]", "tw:pl-[13px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#d7e2ef]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#d7e2ef]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d7e2ef]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d7e2ef]", "tw:rounded-[10px]",
    "tw:bg-[color:#f8fbff]", "tw:[background-image:none]", "tw:text-[color:#536b87]", "tw:text-[.74rem]",
    "tw:[&_label]:inline-flex", "tw:[&_label]:items-center", "tw:[&_label]:gap-y-[7px]", "tw:[&_label]:gap-x-[7px]",
    "tw:[&_label]:text-[color:#183c67]", "tw:[&_label]:font-[750]", "tw:[&_span]:[flex:1]", "tw:[&_input]:w-[16px]",
    "tw:[&_input]:h-[16px]", "tw:[&_input]:[accent-color:#1769c2]", "tw:[&_input]:cursor-pointer", "tw:viewport-620:flex-col",
    "tw:viewport-620:[&_.button]:w-[100%]", "tw:viewport-620:[&_.button]:justify-center",
  ].join(" "),
  "button_button_danger_button_small": sharedUtilities.buttonButtonDangerButtonSmall,
  "client_list_head": [
    "client-list-head", "tw:grid", "tw:viewport-1160:hidden", "tw:grid-cols-[28px_minmax(200px,_1.3fr)_minmax(115px,_.8fr)_minmax(130px,_.9fr)_minmax(160px,_1fr)_minmax(140px,_.9fr)_minmax(130px,_.7fr)]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:items-center", "tw:pt-[0]",
    "tw:pr-[13px]", "tw:pb-[0]", "tw:pl-[13px]", "tw:text-[color:#5c7290]",
    "tw:text-[.62rem]", "tw:font-[800]", "tw:tracking-[.04em]", "tw:uppercase",
    "tw:[&_input]:w-[16px]", "tw:[&_input]:h-[16px]", "tw:[&_input]:[accent-color:#1769c2]", "tw:[&_input]:cursor-pointer",
  ].join(" "),
  "client_list": [
    "client-list", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#d7e2ef]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#d7e2ef]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d7e2ef]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d7e2ef]", "tw:rounded-[10px]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]",
  ].join(" "),
  "client_row_client_row_clickable": [
    "client-row", "client-row-clickable", "tw:grid", "tw:grid-cols-[28px_minmax(200px,_1.3fr)_minmax(115px,_.8fr)_minmax(130px,_.9fr)_minmax(160px,_1fr)_minmax(140px,_.9fr)_minmax(130px,_.7fr)]",
    "tw:viewport-1160:grid-cols-[28px_1fr_1fr]", "tw:viewport-620:grid-cols-[28px_1fr]", "tw:gap-y-[12px]", "tw:viewport-620:gap-y-[5px]",
    "tw:gap-x-[12px]", "tw:viewport-620:gap-x-[5px]", "tw:items-center", "tw:min-h-[61px]",
    "tw:pt-[10px]", "tw:pr-[13px]", "tw:pb-[10px]", "tw:pl-[13px]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#edf1f6]", "tw:text-[color:#40546e]",
    "tw:text-[.75rem]", "tw:[&:last-child]:border-b-[length:0]", "tw:[&:last-child]:[border-bottom-style:none]", "tw:[&:last-child]:border-b-[color:currentColor]",
    "tw:[&_>_div:first-child]:grid", "tw:[&_>_div:first-child]:gap-y-[2px]", "tw:[&_>_div:first-child]:gap-x-[2px]", "tw:[&_strong]:text-[color:#14355e]",
    "tw:[&_strong]:text-[.82rem]", "tw:[&_small]:text-[color:#76879c]", "tw:[&_small]:text-[.65rem]", "tw:viewport-1160:[&_>_*]:min-w-[0]",
    "tw:cursor-pointer", "tw:[transition:background_.15s_ease]", "tw:hover:bg-[color:#f5f9ff]", "tw:hover:[background-image:none]",
    "tw:viewport-1160:grid-cols-[24px_minmax(0,1fr)]! tw:viewport-1160:items-start tw:viewport-1160:[&>_*:not(:first-child)]:col-start-2 tw:viewport-1160:[&>_*:first-child]:row-span-6 tw:viewport-1160:[&>_[data-label]]:before:content-[attr(data-label)] tw:viewport-1160:[&>_[data-label]]:before:block tw:viewport-1160:[&>_[data-label]]:before:text-[.65rem] tw:viewport-1160:[&>_[data-label]]:before:text-[var(--muted)] tw:viewport-1160:[&>_*]:break-words",
  ].join(" "),
  "client_row_select": [
    "client-row-select", "tw:grid", "tw:place-items-center", "tw:[&_input]:w-[16px]",
    "tw:[&_input]:h-[16px]", "tw:[&_input]:[accent-color:#1769c2]", "tw:[&_input]:cursor-pointer", "tw:viewport-1000:[grid-row:1]",
  ].join(" "),
  "client_identity": [
    "client-identity", "tw:flex!", "tw:items-center", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:min-w-[0]", "tw:[&_strong]:[overflow-x:hidden]", "tw:[&_strong]:[overflow-y:hidden]",
    "tw:[&_strong]:text-ellipsis", "tw:[&_strong]:whitespace-nowrap",
    "tw:viewport-1160:[&_strong]:whitespace-normal! tw:viewport-1160:[&_strong]:overflow-visible!",
  ].join(" "),
  "client_status_dot": [
    "client-status-dot", "tw:inline-block", "tw:w-[9px]", "tw:h-[9px]",
    "tw:[flex:0_0_9px]", "tw:border-t-[length:2px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(255_255_255_/_.88)]",
    "tw:border-r-[length:2px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(255_255_255_/_.88)]", "tw:border-b-[length:2px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(255_255_255_/_.88)]", "tw:border-l-[length:2px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgb(255_255_255_/_.88)]", "tw:rounded-[50%]", "tw:[box-shadow:0_0_0_1px_rgb(15_50_88_/_.16)]", "tw:relative",
    "tw:[cursor:help]", "tw:[&.is-active]:bg-[color:#1aaf67]", "tw:[&.is-active]:[background-image:none]", "tw:[&.is-inactive]:bg-[color:#df4444]",
    "tw:[&.is-inactive]:[background-image:none]", "tw:[&::after]:absolute", "tw:[&::after]:z-[8]", "tw:[&::after]:bottom-[calc(100%_+_7px)]",
    "tw:[&::after]:left-[50%]", "tw:[&::after]:pt-[5px]", "tw:[&::after]:pr-[7px]", "tw:[&::after]:pb-[5px]",
    "tw:[&::after]:pl-[7px]", "tw:[&::after]:rounded-[5px]", "tw:[&::after]:text-[color:#f6fbff]", "tw:[&::after]:bg-[color:#153d58]",
    "tw:[&::after]:[background-image:none]", "tw:[&::after]:[box-shadow:0_5px_12px_rgb(9_35_58_/_.2)]", "tw:[&::after]:[content:attr(data-status)]", "tw:[&::after]:text-[.66rem]",
    "tw:[&::after]:font-[700]", "tw:[&::after]:leading-[1]", "tw:[&::after]:opacity-[0]", "tw:[&::after]:[pointer-events:none]",
    "tw:[&::after]:[transform:translate(-50%,_3px)]", "tw:[&::after]:[transition:opacity_.14s_ease,_transform_.14s_ease]", "tw:[&::after]:whitespace-nowrap", "tw:[&:hover::after]:opacity-[1]",
    "tw:[&:hover::after]:[transform:translate(-50%,_0)]", "tw:[&:focus-visible::after]:opacity-[1]", "tw:[&:focus-visible::after]:[transform:translate(-50%,_0)]",
  ].join(" "),
  "client_financial_status": [
    "client-financial-status", "tw:w-[fit-content]", "tw:pt-[3px]", "tw:pr-[6px]",
    "tw:pb-[3px]", "tw:pl-[6px]", "tw:rounded-[4px]", "tw:text-[.65rem]",
    "tw:font-[750]", "tw:[&.client-financial-status-current]:bg-[color:#e7f8ed]", "tw:[&.client-financial-status-current]:[background-image:none]", "tw:[&.client-financial-status-current]:text-[color:#167845]",
    "tw:[&.client-financial-status-open]:bg-[color:#fff4dc]", "tw:[&.client-financial-status-open]:[background-image:none]", "tw:[&.client-financial-status-open]:text-[color:#996100]", "tw:[&.client-financial-status-overdue]:bg-[color:#fff0ef]",
    "tw:[&.client-financial-status-overdue]:[background-image:none]", "tw:[&.client-financial-status-overdue]:text-[color:#b42318]",
  ].join(" "),
  "client_row_actions": [
    "client-row-actions", "tw:flex", "tw:flex-wrap", "tw:gap-y-[5px]",
    "tw:gap-x-[5px]",
    "tw:flex-wrap tw:viewport-620:[&_button]:min-h-10",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "client_empty": sharedUtilities.clientEmpty,
  "client_modal_backdrop": [
    "client-modal-backdrop", "tw:fixed", "tw:z-[80]", "tw:top-[0]",
    "tw:right-[0]", "tw:bottom-[0]", "tw:left-[0]", "tw:grid",
    "tw:place-items-center", "tw:pt-[20px]", "tw:pr-[20px]", "tw:pb-[20px]",
    "tw:pl-[20px]", "tw:bg-[color:rgb(16_29_47_/_.48)]", "tw:[background-image:none]", "tw:[backdrop-filter:blur(3px)]",
  ].join(" "),
  "client_modal": [
    "client-modal", "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[33px]", "tw:[&_input]:pt-[0]",
    "tw:[&_input]:pr-[8px]", "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[8px]", "tw:[&_input]:border-t-[length:1px]",
    "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#c9d8e9]", "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]",
    "tw:[&_input]:border-r-[color:#c9d8e9]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:#c9d8e9]",
    "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#c9d8e9]", "tw:[&_input]:rounded-[6px]",
    "tw:[&_input]:bg-[color:#fbfdff]", "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:#203650]", "tw:[&_input]:[font:inherit]",
    "tw:[&_input]:text-[.76rem]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[33px]", "tw:[&_select]:pt-[0]",
    "tw:[&_select]:pr-[8px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[8px]", "tw:[&_select]:border-t-[length:1px]",
    "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:#c9d8e9]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]",
    "tw:[&_select]:border-r-[color:#c9d8e9]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:#c9d8e9]",
    "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#c9d8e9]", "tw:[&_select]:rounded-[6px]",
    "tw:[&_select]:bg-[color:#fbfdff]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:#203650]", "tw:[&_select]:[font:inherit]",
    "tw:[&_select]:text-[.76rem]", "tw:w-[min(100%,_720px)]", "tw:max-h-[min(760px,_calc(100vh_-_40px))]", "tw:[overflow-x:auto]",
    "tw:[overflow-y:auto]", "tw:pt-[20px]", "tw:viewport-620:pt-[15px]", "tw:pr-[20px]",
    "tw:viewport-620:pr-[15px]", "tw:pb-[20px]", "tw:viewport-620:pb-[15px]", "tw:pl-[20px]",
    "tw:viewport-620:pl-[15px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d5e1ee]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d5e1ee]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d5e1ee]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#d5e1ee]", "tw:rounded-[12px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[box-shadow:0_20px_60px_rgb(7_28_54_/_.28)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[16px]",
    "tw:[&_>_header]:gap-x-[16px]", "tw:[&_>_header]:items-start", "tw:[&_>_header]:pb-[13px]", "tw:[&_>_header]:border-b-[length:1px]",
    "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#e0e8f1]", "tw:[&_h2]:mt-[3px]", "tw:[&_h2]:mr-[0]",
    "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#12335a]", "tw:[&_h2]:text-[1.1rem]",
    "tw:[&_header_p]:mt-[0]", "tw:[&_header_p]:mr-[0]", "tw:[&_header_p]:mb-[0]", "tw:[&_header_p]:ml-[0]",
    "tw:[&_header_p]:text-[color:#697d93]", "tw:[&_header_p]:text-[.74rem]",
    "tw:min-w-0 tw:viewport-620:[&_header]:flex-wrap tw:viewport-620:[&_header>div]:min-w-0 tw:viewport-620:[&_h2]:break-words tw:viewport-620:[&_footer]:flex-wrap tw:viewport-620:[&_footer>button]:min-h-10 tw:viewport-620:[&_footer>button]:flex-1 tw:[&_input]:min-w-0 tw:[&_select]:min-w-0",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "client_plan_history": [
    "client-plan-history", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:pt-[14px]", "tw:[&_article]:grid", "tw:[&_article]:grid-cols-[1fr_auto]", "tw:[&_article]:gap-y-[4px]",
    "tw:[&_article]:gap-x-[12px]", "tw:[&_article]:pt-[11px]", "tw:[&_article]:pr-[11px]", "tw:[&_article]:pb-[11px]",
    "tw:[&_article]:pl-[11px]", "tw:[&_article]:border-t-[length:1px]", "tw:[&_article]:[border-top-style:solid]", "tw:[&_article]:border-t-[color:#dce7f1]",
    "tw:[&_article]:border-r-[length:1px]", "tw:[&_article]:[border-right-style:solid]", "tw:[&_article]:border-r-[color:#dce7f1]", "tw:[&_article]:border-b-[length:1px]",
    "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#dce7f1]", "tw:[&_article]:border-l-[length:1px]", "tw:[&_article]:[border-left-style:solid]",
    "tw:[&_article]:border-l-[color:#dce7f1]", "tw:[&_article]:rounded-[8px]", "tw:[&_article]:bg-[color:#fafcff]", "tw:[&_article]:[background-image:none]",
    "tw:[&_article_strong]:text-[color:#17385e]", "tw:[&_article_span]:text-[color:#168047]", "tw:[&_article_span]:text-[.68rem]", "tw:[&_article_span]:font-[750]",
    "tw:[&_article_small]:[grid-column:1_/_-1]", "tw:[&_article_small]:text-[color:#657990]", "tw:[&_article_small]:text-[.7rem]",
  ].join(" "),
  "client_modal_client_merge_modal": [
    "client-modal", "client-merge-modal", "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[33px]",
    "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[8px]", "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[8px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#c9d8e9]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#c9d8e9]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:#c9d8e9]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#c9d8e9]",
    "tw:[&_input]:rounded-[6px]", "tw:[&_input]:bg-[color:#fbfdff]", "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:#203650]",
    "tw:[&_input]:[font:inherit]", "tw:[&_input]:text-[.76rem]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[33px]",
    "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[8px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[8px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:#c9d8e9]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#c9d8e9]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:#c9d8e9]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#c9d8e9]",
    "tw:[&_select]:rounded-[6px]", "tw:[&_select]:bg-[color:#fbfdff]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:#203650]",
    "tw:[&_select]:[font:inherit]", "tw:[&_select]:text-[.76rem]", "tw:w-[min(100%,_920px)]", "tw:max-h-[min(800px,_calc(100vh_-_40px))]",
    "tw:[overflow-x:visible]", "tw:viewport-620:[overflow-x:auto]", "tw:[overflow-y:visible]", "tw:viewport-620:[overflow-y:auto]",
    "tw:pt-[20px]", "tw:viewport-620:pt-[15px]", "tw:pr-[20px]", "tw:viewport-620:pr-[15px]",
    "tw:pb-[20px]", "tw:viewport-620:pb-[15px]", "tw:pl-[20px]", "tw:viewport-620:pl-[15px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d5e1ee]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#d5e1ee]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#d5e1ee]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d5e1ee]",
    "tw:rounded-[12px]", "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[box-shadow:0_20px_60px_rgb(7_28_54_/_.28)]",
    "tw:[&_>_header]:flex", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[16px]", "tw:[&_>_header]:gap-x-[16px]",
    "tw:[&_>_header]:items-start", "tw:[&_>_header]:pb-[13px]", "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]",
    "tw:[&_>_header]:border-b-[color:#e0e8f1]", "tw:[&_h2]:mt-[3px]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]",
    "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#12335a]", "tw:[&_h2]:text-[1.1rem]", "tw:[&_header_p]:mt-[0]",
    "tw:[&_header_p]:mr-[0]", "tw:[&_header_p]:mb-[0]", "tw:[&_header_p]:ml-[0]", "tw:[&_header_p]:text-[color:#697d93]",
    "tw:[&_header_p]:text-[.74rem]", "tw:[&_>_label]:grid", "tw:[&_>_label]:gap-y-[5px]", "tw:[&_>_label]:gap-x-[5px]",
    "tw:[&_>_label]:text-[color:#51657d]", "tw:[&_>_label]:text-[.7rem]", "tw:[&_>_label]:font-[750]", "tw:grid",
    "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:[&_footer]:flex", "tw:[&_footer]:justify-end",
    "tw:[&_footer]:gap-y-[7px]", "tw:[&_footer]:gap-x-[7px]",
    "tw:min-w-0 tw:viewport-620:[&_header]:flex-wrap tw:viewport-620:[&_header>div]:min-w-0 tw:viewport-620:[&_h2]:break-words tw:viewport-620:[&_footer]:flex-wrap tw:viewport-620:[&_footer>button]:min-h-10 tw:viewport-620:[&_footer>button]:flex-1 tw:[&_input]:min-w-0 tw:[&_select]:min-w-0",
  ].join(" "),
  "client_merge_preview": [
    "client-merge-preview", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:pt-[9px]", "tw:pr-[10px]", "tw:pb-[9px]",
    "tw:pl-[10px]", "tw:border-l-[length:3px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#e0a12a]",
    "tw:bg-[color:#fff8e9]", "tw:[background-image:none]", "tw:text-[color:#76520b]", "tw:text-[.75rem]",
  ].join(" "),
  "client_modal_client_edit_modal": [
    "client-modal", "client-edit-modal", "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[33px]",
    "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[8px]", "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[8px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#c9d8e9]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#c9d8e9]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:#c9d8e9]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#c9d8e9]",
    "tw:[&_input]:rounded-[6px]", "tw:[&_input]:bg-[color:#fbfdff]", "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:#203650]",
    "tw:[&_input]:[font:inherit]", "tw:[&_input]:text-[.76rem]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[33px]",
    "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[8px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[8px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:#c9d8e9]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#c9d8e9]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:#c9d8e9]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#c9d8e9]",
    "tw:[&_select]:rounded-[6px]", "tw:[&_select]:bg-[color:#fbfdff]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:#203650]",
    "tw:[&_select]:[font:inherit]", "tw:[&_select]:text-[.76rem]", "tw:w-[min(100%,_760px)]", "tw:max-h-[min(760px,_calc(100vh_-_40px))]",
    "tw:[overflow-x:auto]", "tw:[overflow-y:auto]", "tw:pt-[20px]", "tw:viewport-620:pt-[15px]",
    "tw:pr-[20px]", "tw:viewport-620:pr-[15px]", "tw:pb-[20px]", "tw:viewport-620:pb-[15px]",
    "tw:pl-[20px]", "tw:viewport-620:pl-[15px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#d5e1ee]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d5e1ee]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d5e1ee]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#d5e1ee]", "tw:rounded-[12px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[box-shadow:0_20px_60px_rgb(7_28_54_/_.28)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:justify-between",
    "tw:[&_>_header]:gap-y-[16px]", "tw:[&_>_header]:gap-x-[16px]", "tw:[&_>_header]:items-start", "tw:[&_>_header]:pb-[13px]",
    "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#e0e8f1]", "tw:[&_h2]:mt-[3px]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#12335a]",
    "tw:[&_h2]:text-[1.1rem]", "tw:[&_header_p]:mt-[0]", "tw:[&_header_p]:mr-[0]", "tw:[&_header_p]:mb-[0]",
    "tw:[&_header_p]:ml-[0]", "tw:[&_header_p]:text-[color:#697d93]", "tw:[&_header_p]:text-[.74rem]",
    "tw:min-w-0 tw:viewport-620:[&_header]:flex-wrap tw:viewport-620:[&_header>div]:min-w-0 tw:viewport-620:[&_h2]:break-words tw:viewport-620:[&_footer]:flex-wrap tw:viewport-620:[&_footer>button]:min-h-10 tw:viewport-620:[&_footer>button]:flex-1 tw:[&_input]:min-w-0 tw:[&_select]:min-w-0",
  ].join(" "),
  "client_modal_heading": [
    "client-modal-heading", "tw:flex", "tw:items-center", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]",
  ].join(" "),
  "client_avatar": [
    "client-avatar", "tw:shrink-0", "tw:grid", "tw:w-[44px]", "tw:h-[44px]",
    "tw:place-items-center", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:border-t-[length:2px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#e2edf1]", "tw:border-r-[length:2px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#e2edf1]", "tw:border-b-[length:2px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e2edf1]",
    "tw:border-l-[length:2px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#e2edf1]", "tw:rounded-[50%]",
    "tw:bg-[color:#e7f3f5]", "tw:[background-image:none]", "tw:text-[color:#1a6681]", "tw:text-[.8rem]",
    "tw:font-[850]", "tw:[&_img]:w-[100%]", "tw:[&_img]:h-[100%]", "tw:[&_img]:[object-fit:cover]",
  ].join(" "),
  "client_edit_form": [
    "client-edit-form", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-620:grid-cols-[1fr]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:pt-[16px]", "tw:[&_label]:grid",
    "tw:[&_label]:gap-y-[5px]", "tw:[&_label]:gap-x-[5px]", "tw:[&_label]:text-[color:#51657d]", "tw:[&_label]:text-[.7rem]",
    "tw:[&_label]:font-[750]", "tw:[&_footer]:[grid-column:1_/_-1]", "tw:[&_footer]:flex", "tw:[&_footer]:justify-end",
    "tw:[&_footer]:gap-y-[8px]", "tw:[&_footer]:gap-x-[8px]", "tw:[&_footer]:pt-[4px]",
  ].join(" "),
  "form_full": [
    "form-full", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  "control_toggle": sharedUtilities.controlToggle,
  "button_button_danger": sharedUtilities.buttonButtonDanger,
  "client_modal_2": [
    "client-modal", "client-balance-modal", "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[33px]",
    "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[8px]", "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[8px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#c9d8e9]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#c9d8e9]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:#c9d8e9]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#c9d8e9]",
    "tw:[&_input]:rounded-[6px]", "tw:[&_input]:bg-[color:#fbfdff]", "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:#203650]",
    "tw:[&_input]:[font:inherit]", "tw:[&_input]:text-[.76rem]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[33px]",
    "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[8px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[8px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:#c9d8e9]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#c9d8e9]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:#c9d8e9]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#c9d8e9]",
    "tw:[&_select]:rounded-[6px]", "tw:[&_select]:bg-[color:#fbfdff]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:#203650]",
    "tw:[&_select]:[font:inherit]", "tw:[&_select]:text-[.76rem]", "tw:w-[min(100%,_720px)]", "tw:max-h-[min(760px,_calc(100vh_-_40px))]",
    "tw:[overflow-x:auto]", "tw:[overflow-y:auto]", "tw:pt-[20px]", "tw:viewport-620:pt-[15px]",
    "tw:pr-[20px]", "tw:viewport-620:pr-[15px]", "tw:pb-[20px]", "tw:viewport-620:pb-[15px]",
    "tw:pl-[20px]", "tw:viewport-620:pl-[15px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#d5e1ee]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d5e1ee]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d5e1ee]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#d5e1ee]", "tw:rounded-[12px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[box-shadow:0_20px_60px_rgb(7_28_54_/_.28)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:justify-between",
    "tw:[&_>_header]:gap-y-[16px]", "tw:[&_>_header]:gap-x-[16px]", "tw:[&_>_header]:items-start", "tw:[&_>_header]:pb-[13px]",
    "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#e0e8f1]", "tw:[&_h2]:mt-[3px]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#12335a]",
    "tw:[&_h2]:text-[1.1rem]", "tw:[&_header_p]:mt-[0]", "tw:[&_header_p]:mr-[0]", "tw:[&_header_p]:mb-[0]",
    "tw:[&_header_p]:ml-[0]", "tw:[&_header_p]:text-[color:#697d93]", "tw:[&_header_p]:text-[.74rem]",
    "tw:min-w-0 tw:viewport-620:[&_header]:flex-wrap tw:viewport-620:[&_header>div]:min-w-0 tw:viewport-620:[&_h2]:break-words tw:viewport-620:[&_footer]:flex-wrap tw:viewport-620:[&_footer>button]:min-h-10 tw:viewport-620:[&_footer>button]:flex-1 tw:[&_input]:min-w-0 tw:[&_select]:min-w-0",
  ].join(" "),
  "client_balance_summary": [
    "client-balance-summary", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-620:grid-cols-[1fr]",
    "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:pt-[15px]", "tw:pr-[0]",
    "tw:pb-[15px]", "tw:pl-[0]", "tw:[&_article]:grid", "tw:[&_article]:gap-y-[4px]",
    "tw:[&_article]:gap-x-[4px]", "tw:[&_article]:pt-[12px]", "tw:[&_article]:pr-[12px]", "tw:[&_article]:pb-[12px]",
    "tw:[&_article]:pl-[12px]", "tw:[&_article]:border-t-[length:1px]", "tw:[&_article]:[border-top-style:solid]", "tw:[&_article]:border-t-[color:#dce7f1]",
    "tw:[&_article]:border-r-[length:1px]", "tw:[&_article]:[border-right-style:solid]", "tw:[&_article]:border-r-[color:#dce7f1]", "tw:[&_article]:border-b-[length:1px]",
    "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#dce7f1]", "tw:[&_article]:border-l-[length:1px]", "tw:[&_article]:[border-left-style:solid]",
    "tw:[&_article]:border-l-[color:#dce7f1]", "tw:[&_article]:rounded-[8px]", "tw:[&_article]:bg-[color:#f8fbff]", "tw:[&_article]:[background-image:none]",
    "tw:[&_span]:text-[color:#63758d]", "tw:[&_span]:text-[.68rem]", "tw:[&_strong]:text-[color:#0f5d41]", "tw:[&_strong]:text-[1rem]",
  ].join(" "),
  "client_balance_form": [
    "client-balance-form", "tw:grid", "tw:grid-cols-[repeat(3,_minmax(0,_1fr))]", "tw:viewport-620:grid-cols-[1fr]",
    "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:pt-[13px]", "tw:pr-[13px]",
    "tw:pb-[13px]", "tw:pl-[13px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dce7f1]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce7f1]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce7f1]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dce7f1]", "tw:rounded-[8px]", "tw:bg-[color:#fbfdff]",
    "tw:[background-image:none]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[5px]", "tw:[&_label]:gap-x-[5px]",
    "tw:[&_label]:text-[color:#51657d]", "tw:[&_label]:text-[.7rem]", "tw:[&_label]:font-[750]", "tw:[&_.client-balance-reason]:[grid-column:1_/_-1]",
    "tw:[&_.button]:[justify-self:start]",
  ].join(" "),
  "client_balance_history": [
    "client-balance-history", "tw:grid", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:pt-[16px]", "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[2px]",
    "tw:[&_h3]:ml-[0]", "tw:[&_h3]:text-[color:#17385e]", "tw:[&_h3]:text-[.85rem]", "tw:[&_article]:grid",
    "tw:[&_article]:grid-cols-[82px_100px_1fr]", "tw:viewport-620:[&_article]:grid-cols-[1fr]", "tw:[&_article]:gap-y-[8px]", "tw:viewport-620:[&_article]:gap-y-[3px]",
    "tw:[&_article]:gap-x-[8px]", "tw:viewport-620:[&_article]:gap-x-[3px]", "tw:[&_article]:pt-[8px]", "tw:[&_article]:pr-[0]",
    "tw:[&_article]:pb-[8px]", "tw:[&_article]:pl-[0]", "tw:[&_article]:border-b-[length:1px]", "tw:[&_article]:[border-bottom-style:solid]",
    "tw:[&_article]:border-b-[color:#edf1f6]", "tw:[&_article]:text-[color:#64768d]", "tw:[&_article]:text-[.7rem]", "tw:[&_strong]:text-[color:#176a42]",
    "tw:[&_small]:text-[color:#51657d]",
  ].join(" "),
} as const;
