"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { adjustClientBalanceAction, importClientsAction, mergeClientsAction } from "@/lib/actions/client-management";
import { archivePlayerAction, updatePlayerAction } from "@/lib/actions/tournament";

type Client = { id: string; name: string; phone: string; email: string; cpf: string; birthDate: string; gender: string; class: string; isTeacher: boolean; points: number; leagueTier: string; active: boolean; financialStatus: string; moneyBalanceCents: number; classBalance: number; plans: { id: string; name: string; status: string; startedAt: string; endedAt: string | null; classesPerMonth: number; dueDay: number }[]; balanceMovements: { id: string; kind: string; amountCents: number; classesDelta: number; reason: string; createdAt: string }[] };
type Props = { clients: Client[]; plans: { id: string; name: string }[]; teachers: { id: string; name: string }[]; filters: { q: string; phone: string; financial: string; planId: string; active: string; teacherId: string } };
const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value / 100);
const date = (value: string) => new Intl.DateTimeFormat("pt-BR", { dateStyle: "short" }).format(new Date(value));

export function ClientManagementWorkspace({ clients, plans, teachers, filters }: Props) {
  const router = useRouter();
  const [balanceClient, setBalanceClient] = useState<Client | null>(null);
  const [plansClient, setPlansClient] = useState<Client | null>(null);
  const [editingClient, setEditingClient] = useState<Client | null>(null);
  const [mergeOpen, setMergeOpen] = useState(false);
  const [primaryPlayerId, setPrimaryPlayerId] = useState("");
  const [duplicatePlayerId, setDuplicatePlayerId] = useState("");
  const [message, setMessage] = useState("");
  const [pending, startTransition] = useTransition();
  const clientsById = useMemo(() => new Map(clients.map((client) => [client.id, client])), [clients]);
  const closeAll = () => { setBalanceClient(null); setPlansClient(null); setEditingClient(null); setMergeOpen(false); };
  const exportClients = () => {
    const csv = ["Nome;Telefone;CPF;Status financeiro;Status cadastral;Saldo financeiro;Saldo aulas", ...clients.map((client) => [client.name, client.phone, client.cpf, client.financialStatus, client.active ? "Ativo" : "Inativo", (client.moneyBalanceCents / 100).toFixed(2), client.classBalance].join(";"))].join("\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "clientes.csv"; anchor.click(); URL.revokeObjectURL(url);
  };
  const merge = () => { const data = new FormData(); data.set("primaryPlayerId", primaryPlayerId); data.set("duplicatePlayerId", duplicatePlayerId); setMessage(""); startTransition(async () => { try { await mergeClientsAction(data); closeAll(); setMessage("Contatos mesclados com sucesso."); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível mesclar os contatos."); } }); };
  const importFile = (file: File | undefined) => { if (!file) return; const data = new FormData(); data.set("file", file); setMessage(""); startTransition(async () => { try { const result = await importClientsAction(data); setMessage(`${result.imported} cliente(s) importado(s).`); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível importar o arquivo."); } }); };

  return <>
    <section className="client-workspace" aria-label="Gestão de clientes"><form className="client-filter-bar" action="/jogadores"><label>Nome<input name="q" defaultValue={filters.q} placeholder="Pesquisar por nome" /></label><label>Telefone<input name="phone" defaultValue={filters.phone} placeholder="(00) 00000-0000" /></label><label>Status financeiro<select name="financial" defaultValue={filters.financial}><option value="ALL">Todos</option><option value="CURRENT">Adimplente</option><option value="OPEN">Com débitos em aberto</option><option value="OVERDUE">Em atraso</option></select></label><label>Plano/pacote ativo<select name="planId" defaultValue={filters.planId}><option value="">Todos</option>{plans.map((plan) => <option value={plan.id} key={plan.id}>{plan.name}</option>)}</select></label><label>Status do cadastro<select name="active" defaultValue={filters.active}><option value="ALL">Todos</option><option value="ACTIVE">Ativo</option><option value="INACTIVE">Inativo</option></select></label><label>Aluno de<select name="teacherId" defaultValue={filters.teacherId}><option value="">Todos os professores</option>{teachers.map((teacher) => <option value={teacher.id} key={teacher.id}>{teacher.name}</option>)}</select></label><div className="client-filter-actions"><button className="button button-primary" type="submit">Aplicar filtros</button><a className="button" href="/jogadores">Limpar filtros</a><button className="button" type="button" onClick={() => setMergeOpen(true)}>Mesclar contatos</button><button className="button" type="button" onClick={exportClients}>Exportar</button><label className="button client-import-control">{pending ? "Importando..." : "Importar"}<input type="file" accept=".csv,text/csv" onChange={(event) => importFile(event.target.files?.[0])} /></label></div></form>
      {message ? <p className="client-workspace-message" role="status">{message}</p> : null}
      <div className="client-list-head"><span>Cliente</span><span>Telefone</span><span>Financeiro</span><span>Planos ativos</span><span>Saldos</span><span>Ações</span></div>
      <div className="client-list">{clients.length ? clients.map((client) => <article className="client-row client-row-clickable" key={client.id} onClick={() => setEditingClient(client)}><div><strong>{client.name}</strong><small>{client.active ? "Cadastro ativo" : "Cadastro inativo"}</small></div><span>{client.phone || "Não informado"}</span><span className={`client-financial-status client-financial-status-${client.financialStatus === "Adimplente" ? "current" : client.financialStatus === "Em atraso" ? "overdue" : "open"}`}>{client.financialStatus}</span><span>{client.plans.filter((plan) => plan.status === "ACTIVE").map((plan) => plan.name).join(" · ") || "Sem plano ativo"}</span><span>{money(client.moneyBalanceCents)} · {client.classBalance} aula(s)</span><div className="client-row-actions"><button className="button button-small" type="button" onClick={(event) => { event.stopPropagation(); setBalanceClient(client); }}>Saldo</button><button className="button button-small" type="button" onClick={(event) => { event.stopPropagation(); setPlansClient(client); }}>Planos</button></div></article>) : <p className="client-empty">Nenhum cliente encontrado para os filtros informados.</p>}</div>
    </section>
    {balanceClient ? <BalanceDialog client={balanceClient} pending={pending} onClose={() => setBalanceClient(null)} onSubmit={(form) => { setMessage(""); startTransition(async () => { try { await adjustClientBalanceAction(form); setBalanceClient(null); setMessage("Saldo atualizado com sucesso."); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível atualizar o saldo."); } }); }} /> : null}
    {editingClient ? <ClientEditDialog client={editingClient} pending={pending} onClose={() => setEditingClient(null)} onSubmit={(form) => { setMessage(""); startTransition(async () => { try { await updatePlayerAction(form); setEditingClient(null); router.refresh(); setMessage("Cadastro atualizado com sucesso."); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível atualizar o cadastro."); } }); }} onArchive={(form) => { if (!window.confirm("Excluir este cliente da lista ativa? O histórico financeiro, comandas e reservas será preservado.")) return; setMessage(""); startTransition(async () => { try { await archivePlayerAction(form); setEditingClient(null); router.refresh(); setMessage("Cliente inativado com sucesso."); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível excluir o cliente."); } }); }} /> : null}
    {plansClient ? <div className="client-modal-backdrop" onMouseDown={() => setPlansClient(null)}><section className="client-modal" role="dialog" aria-modal="true" aria-label="Histórico de planos" onMouseDown={(event) => event.stopPropagation()}><header><div><p className="eyebrow">CLIENTE</p><h2>Histórico de planos · {plansClient.name}</h2></div><button className="button button-small" onClick={() => setPlansClient(null)}>Fechar</button></header><div className="client-plan-history">{plansClient.plans.length ? plansClient.plans.map((plan) => <article key={plan.id}><strong>{plan.name}</strong><span>{plan.status === "ACTIVE" ? "Ativo" : plan.status}</span><small>Início: {date(plan.startedAt)} · {plan.endedAt ? `Fim: ${date(plan.endedAt)}` : "Em vigência"}</small><small>{plan.classesPerMonth} aula(s)/mês · vencimento dia {plan.dueDay}</small></article>) : <p>Nenhum plano vinculado a este cliente.</p>}</div></section></div> : null}
    {mergeOpen ? <div className="client-modal-backdrop" onMouseDown={closeAll}><section className="client-modal client-merge-modal" role="dialog" aria-modal="true" aria-label="Mesclar contatos" onMouseDown={(event) => event.stopPropagation()}><header><div><p className="eyebrow">DUPLICIDADE</p><h2>Mesclar contatos</h2><p>O cliente duplicado será inativado; comandas, saldo e aulas serão associados ao cliente principal.</p></div><button className="button button-small" onClick={closeAll}>Fechar</button></header><label>Manter como cliente principal<select value={primaryPlayerId} onChange={(event) => setPrimaryPlayerId(event.target.value)}><option value="">Selecione</option>{clients.map((client) => <option value={client.id} key={client.id}>{client.name} · {client.phone}</option>)}</select></label><label>Contato duplicado<select value={duplicatePlayerId} onChange={(event) => setDuplicatePlayerId(event.target.value)}><option value="">Selecione</option>{clients.filter((client) => client.id !== primaryPlayerId).map((client) => <option value={client.id} key={client.id}>{client.name} · {client.phone}</option>)}</select></label>{primaryPlayerId && duplicatePlayerId ? <p className="client-merge-preview">Mesclar <strong>{clientsById.get(duplicatePlayerId)?.name}</strong> em <strong>{clientsById.get(primaryPlayerId)?.name}</strong>.</p> : null}<footer><button className="button" onClick={closeAll}>Cancelar</button><button className="button button-primary" disabled={pending || !primaryPlayerId || !duplicatePlayerId} onClick={merge}>{pending ? "Mesclando..." : "Confirmar mesclagem"}</button></footer></section></div> : null}
  </>;
}

function ClientEditDialog({ client, pending, onClose, onSubmit, onArchive }: { client: Client; pending: boolean; onClose: () => void; onSubmit: (data: FormData) => void; onArchive: (data: FormData) => void }) {
  return <div className="client-modal-backdrop" onMouseDown={onClose}><section className="client-modal client-edit-modal" role="dialog" aria-modal="true" aria-label="Editar cliente" onMouseDown={(event) => event.stopPropagation()}><header><div><p className="eyebrow">CLIENTE</p><h2>{client.name}</h2></div><button type="button" className="button button-small" onClick={onClose}>Fechar</button></header><form className="client-edit-form" onSubmit={(event) => { event.preventDefault(); onSubmit(new FormData(event.currentTarget)); }}><input type="hidden" name="playerId" value={client.id} /><input type="hidden" name="points" value={client.points} /><input type="hidden" name="class" value={client.class} /><label>Nome<input name="name" defaultValue={client.name} required /></label><label>Telefone<input name="phone" defaultValue={client.phone} required /></label><label>E-mail<input name="email" type="email" defaultValue={client.email} /></label><label>CPF<input name="cpf" defaultValue={client.cpf} inputMode="numeric" /></label><label>Data de nascimento<input name="birthDate" type="date" defaultValue={client.birthDate} /></label><label>Gênero<select name="gender" defaultValue={client.gender}><option value="">Não informar</option><option value="Feminino">Feminino</option><option value="Masculino">Masculino</option><option value="Outro">Outro</option></select></label><label>Liga do atleta<select name="leagueTier" defaultValue={client.leagueTier}><option value="">Sem definição</option><option value="A">Liga A</option><option value="B">Liga B</option></select></label><label className="check-option"><input name="isTeacher" type="checkbox" defaultChecked={client.isTeacher} /><span>É professor</span></label><footer><button type="button" className="button button-danger" disabled={pending} onClick={() => { const form = new FormData(); form.set("playerId", client.id); onArchive(form); }}>Excluir cliente</button><span /><button type="button" className="button" onClick={onClose}>Cancelar</button><button className="button button-primary" disabled={pending}>{pending ? "Salvando..." : "Salvar alterações"}</button></footer></form></section></div>;
}

function BalanceDialog({ client, pending, onClose, onSubmit }: { client: Client; pending: boolean; onClose: () => void; onSubmit: (data: FormData) => void }) {
  const [kind, setKind] = useState<"MONEY" | "CLASSES">("MONEY"); const [operation, setOperation] = useState<"ADD" | "REMOVE">("ADD");
  return <div className="client-modal-backdrop" onMouseDown={onClose}><section className="client-modal client-balance-modal" role="dialog" aria-modal="true" aria-label="Controle de saldo" onMouseDown={(event) => event.stopPropagation()}><header><div><p className="eyebrow">CLIENTE</p><h2>Controle de saldo · {client.name}</h2></div><button className="button button-small" onClick={onClose}>Fechar</button></header><div className="client-balance-summary"><article><span>Saldo de crédito</span><strong>{money(client.moneyBalanceCents)}</strong></article><article><span>Saldo de aulas/reposições</span><strong>{client.classBalance} aula(s)</strong></article></div><form onSubmit={(event) => { event.preventDefault(); onSubmit(new FormData(event.currentTarget)); }} className="client-balance-form"><input type="hidden" name="playerId" value={client.id} /><label>Tipo de saldo<select name="kind" value={kind} onChange={(event) => setKind(event.target.value as "MONEY" | "CLASSES")}><option value="MONEY">Crédito financeiro</option><option value="CLASSES">Aulas/reposições</option></select></label><label>Movimentação<select name="operation" value={operation} onChange={(event) => setOperation(event.target.value as "ADD" | "REMOVE")}><option value="ADD">Adicionar saldo</option><option value="REMOVE">Remover saldo</option></select></label><label>{kind === "MONEY" ? "Valor (R$)" : "Quantidade de aulas"}<input name="amount" inputMode={kind === "MONEY" ? "decimal" : "numeric"} placeholder={kind === "MONEY" ? "0,00" : "0"} required /></label><label className="client-balance-reason">Motivo<input name="reason" placeholder="Ex.: crédito concedido pela arena" required /></label><button className="button button-primary" disabled={pending}>{pending ? "Salvando..." : "Registrar movimentação"}</button></form><section className="client-balance-history"><h3>Histórico de movimentações</h3>{client.balanceMovements.length ? client.balanceMovements.map((movement) => <article key={movement.id}><span>{date(movement.createdAt)}</span><strong>{movement.kind === "MONEY" ? money(movement.amountCents) : `${movement.classesDelta > 0 ? "+" : ""}${movement.classesDelta} aula(s)`}</strong><small>{movement.reason}</small></article>) : <p>Nenhuma movimentação manual registrada.</p>}</section></section></div>;
}
