/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "client_merge_picker": [
    "client-merge-picker", "tw:relative", "tw:grid", "tw:gap-y-[5px]",
    "tw:gap-x-[5px]", "tw:text-[color:#51657d]", "tw:text-[.7rem]", "tw:font-[750]",
    "tw:min-w-[0]", "tw:[&_input]:min-h-[40px]",
  ].join(" "),
  "client_merge_search_results": [
    "client-merge-search-results", "tw:absolute", "tw:z-[90]", "tw:top-[calc(100%_+_4px)]",
    "tw:right-[0]", "tw:left-[0]", "tw:grid", "tw:max-h-[260px]",
    "tw:[overflow-y:auto]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#c9d8e9]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#c9d8e9]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#c9d8e9]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#c9d8e9]", "tw:rounded-[7px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[box-shadow:0_12px_24px_rgb(15_23_42_/_.14)]", "tw:[&_button]:grid", "tw:[&_button]:gap-y-[2px]", "tw:[&_button]:gap-x-[2px]",
    "tw:[&_button]:pt-[10px]", "tw:[&_button]:pr-[12px]", "tw:[&_button]:pb-[10px]", "tw:[&_button]:pl-[12px]",
    "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]", "tw:[&_button]:border-r-[length:0]",
    "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:1px]", "tw:[&_button]:[border-bottom-style:solid]",
    "tw:[&_button]:border-b-[color:#e2eaf3]", "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]", "tw:[&_button]:border-l-[color:currentColor]",
    "tw:[&_button]:bg-[color:transparent]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:#203650]", "tw:[&_button]:[font:inherit]",
    "tw:[&_button]:text-[.76rem]", "tw:[&_button]:text-left", "tw:[&_button]:cursor-pointer", "tw:[&_button]:w-[100%]",
    "tw:[&_button]:[overflow-wrap:anywhere]", "tw:[&_em]:grid", "tw:[&_em]:gap-y-[2px]", "tw:[&_em]:gap-x-[2px]",
    "tw:[&_em]:pt-[10px]", "tw:[&_em]:pr-[12px]", "tw:[&_em]:pb-[10px]", "tw:[&_em]:pl-[12px]",
    "tw:[&_em]:border-t-[length:0]", "tw:[&_em]:[border-top-style:none]", "tw:[&_em]:border-t-[color:currentColor]", "tw:[&_em]:border-r-[length:0]",
    "tw:[&_em]:[border-right-style:none]", "tw:[&_em]:border-r-[color:currentColor]", "tw:[&_em]:border-b-[length:1px]", "tw:[&_em]:[border-bottom-style:solid]",
    "tw:[&_em]:border-b-[color:#e2eaf3]", "tw:[&_em]:border-l-[length:0]", "tw:[&_em]:[border-left-style:none]", "tw:[&_em]:border-l-[color:currentColor]",
    "tw:[&_em]:bg-[color:transparent]", "tw:[&_em]:[background-image:none]", "tw:[&_em]:text-[color:#687b90]", "tw:[&_em]:[font:inherit]",
    "tw:[&_em]:text-[.68rem]", "tw:[&_em]:text-left", "tw:[&_em]:not-italic", "tw:[&_em]:w-[100%]",
    "tw:[&_em]:[overflow-wrap:anywhere]", "tw:[&_button:hover]:bg-[color:#f2f8ff]", "tw:[&_button:hover]:[background-image:none]", "tw:[&_button:hover]:[outline:none]",
    "tw:[&_button:focus-visible]:bg-[color:#f2f8ff]", "tw:[&_button:focus-visible]:[background-image:none]", "tw:[&_button:focus-visible]:[outline:none]", "tw:[&_small]:text-[color:#687b90]",
    "tw:[&_small]:text-[.68rem]", "tw:[&_small]:not-italic", "tw:[&_>_:last-child]:border-b-[length:0]", "tw:[&_>_:last-child]:[border-bottom-style:none]",
    "tw:[&_>_:last-child]:border-b-[color:currentColor]", "tw:[&_strong]:[white-space:normal]",
  ].join(" "),
} as const;
