import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "player_name_edit_form": [
    "player-name-edit-form", "tw:flex", "tw:items-center", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]", "tw:min-w-[0]",
  ].join(" "),
  "player_name_input": [
    "player-name-input", "tw:w-[min(100%,_280px)]", "tw:min-h-[38px]", "tw:pt-[0]",
    "tw:pr-[12px]", "tw:pb-[0]", "tw:pl-[12px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[12px]",
    "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:text-[color:var(--text)]", "tw:focus:[outline:none]",
    "tw:focus:border-t-[color:rgba(18,_93,_156,_0.35)]", "tw:focus:border-r-[color:rgba(18,_93,_156,_0.35)]", "tw:focus:border-b-[color:rgba(18,_93,_156,_0.35)]", "tw:focus:border-l-[color:rgba(18,_93,_156,_0.35)]",
    "tw:focus:[box-shadow:0_0_0_4px_rgba(18,_93,_156,_0.1)]", "tw:focus-visible:[outline:none]", "tw:focus-visible:[box-shadow:0_0_0_4px_rgba(18,_93,_156,_0.1)]",
  ].join(" "),
  "player_inline_actions": sharedUtilities.playerInlineActions,
  "player_inline_text_button_player_inline_text_button_save": sharedUtilities.playerInlineTextButtonPlayerInlineTextButtonSave,
  "player_inline_text_button": sharedUtilities.playerInlineTextButton,
  "player_name_cell": [
    "player-name-cell", "tw:flex", "tw:items-center", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]", "tw:min-w-[0]",
  ].join(" "),
  "player_avatar": [
    "player-avatar", "tw:[display:inline-grid]", "tw:place-items-center", "tw:[flex:0_0_auto]",
    "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:rounded-[50%]", "tw:bg-[color:var(--brand-soft)]",
    "tw:[background-image:none]", "tw:text-[color:var(--brand-strong)]", "tw:font-[800]", "tw:w-[34px]",
    "tw:h-[34px]", "tw:text-[0.86rem]", "tw:[&_img]:w-[100%]", "tw:[&_img]:h-[100%]",
    "tw:[&_img]:[object-fit:cover]",
  ].join(" "),
  "player_name_label": [
    "player-name-label", "tw:min-w-[0]", "tw:font-[600]", "tw:text-[color:var(--text)]",
  ].join(" "),
  "player_name_tools": [
    "player-name-tools", "tw:inline-flex", "tw:items-center", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:[flex-shrink:0]", "tw:relative",
  ].join(" "),
  "player_inline_icon_button": sharedUtilities.playerInlineIconButton,
  "player_action_menu": [
    "player-action-menu", "tw:absolute", "tw:z-[4]", "tw:top-[calc(100%_+_6px)]",
    "tw:right-[0]", "tw:grid", "tw:min-w-[232px]", "tw:pt-[6px]",
    "tw:pr-[6px]", "tw:pb-[6px]", "tw:pl-[6px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[12px]",
    "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:[box-shadow:0_14px_32px_rgba(18,_30,_49,_0.16)]", "tw:[&_form]:contents",
  ].join(" "),
  "player_action_menu_item": [
    "player-action-menu-item", "tw:w-[100%]", "tw:min-h-[36px]", "tw:pt-[0]",
    "tw:pr-[10px]", "tw:pb-[0]", "tw:pl-[10px]", "tw:border-t-[length:0]",
    "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]",
    "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[8px]",
    "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:text-[color:var(--text)]", "tw:cursor-pointer",
    "tw:[font:inherit]", "tw:text-[0.9rem]", "tw:font-[650]", "tw:text-left",
    "tw:[&:hover:not(:disabled)]:bg-[color:rgba(18,_93,_156,_0.08)]", "tw:[&:hover:not(:disabled)]:[background-image:none]", "tw:[&:hover:not(:disabled)]:text-[color:var(--brand)]", "tw:[&:hover:not(:disabled)]:[outline:none]",
    "tw:[&:focus-visible:not(:disabled)]:bg-[color:rgba(18,_93,_156,_0.08)]", "tw:[&:focus-visible:not(:disabled)]:[background-image:none]", "tw:[&:focus-visible:not(:disabled)]:text-[color:var(--brand)]", "tw:[&:focus-visible:not(:disabled)]:[outline:none]",
    "tw:disabled:cursor-not-allowed", "tw:disabled:opacity-[0.48]",
  ].join(" "),
  "player_action_menu_delete_block": [
    "player-action-menu-delete-block", "tw:grid", "tw:gap-y-[2px]", "tw:gap-x-[2px]",
    "tw:pt-[4px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
    "tw:[&_p]:pt-[0]", "tw:[&_p]:pr-[10px]", "tw:[&_p]:pb-[6px]", "tw:[&_p]:pl-[10px]",
    "tw:[&_p]:text-[color:var(--muted)]", "tw:[&_p]:text-[0.76rem]", "tw:[&_p]:leading-[1.35]",
  ].join(" "),
  "player_action_menu_item_player_action_menu_danger": [
    "player-action-menu-item", "player-action-menu-danger", "tw:w-[100%]", "tw:min-h-[36px]",
    "tw:pt-[0]", "tw:pr-[10px]", "tw:pb-[0]", "tw:pl-[10px]",
    "tw:border-t-[length:0]", "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]",
    "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]",
    "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]",
    "tw:rounded-[8px]", "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:text-[color:var(--danger)]",
    "tw:cursor-pointer", "tw:[font:inherit]", "tw:text-[0.9rem]", "tw:font-[650]",
    "tw:text-left", "tw:[&:hover:not(:disabled)]:bg-[color:rgba(191,_63,_56,_0.08)]", "tw:[&:hover:not(:disabled)]:[background-image:none]", "tw:[&:hover:not(:disabled)]:text-[color:var(--danger)]",
    "tw:[&:hover:not(:disabled)]:[outline:none]", "tw:[&:focus-visible:not(:disabled)]:bg-[color:rgba(191,_63,_56,_0.08)]", "tw:[&:focus-visible:not(:disabled)]:[background-image:none]", "tw:[&:focus-visible:not(:disabled)]:text-[color:var(--danger)]",
    "tw:[&:focus-visible:not(:disabled)]:[outline:none]", "tw:disabled:cursor-not-allowed", "tw:disabled:opacity-[0.48]",
  ].join(" "),
  "player_action_menu_form": [
    "player-action-menu-form", "tw:contents", "tw:[&_>_.form-full]:mt-[6px]", "tw:[&_>_.form-full]:mr-[4px]",
    "tw:[&_>_.form-full]:mb-[4px]", "tw:[&_>_.form-full]:ml-[4px]", "tw:[&_.inline-form]:flex-wrap",
  ].join(" "),
} as const;
