import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "stack_md": sharedUtilities.stackMd,
  "section_card_stack_md_category_operation_panel": sharedUtilities.sectionCardStackMdCategoryOperationPanel,
  "league_registration_panel": [
    "league-registration-panel", "tw:gap-y-[18px]", "tw:gap-x-[18px]", "tw:pt-[22px]",
    "tw:viewport-760:pt-[17px]", "tw:pr-[22px]", "tw:viewport-760:pr-[17px]", "tw:pb-[22px]",
    "tw:viewport-760:pb-[17px]", "tw:pl-[22px]", "tw:viewport-760:pl-[17px]", "tw:border-t-[color:#d9e5f2]",
    "tw:border-r-[color:#d9e5f2]", "tw:border-b-[color:#d9e5f2]", "tw:border-l-[color:#d9e5f2]", "tw:rounded-[15px]",
    "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_#fff,_#fbfdff)]", "tw:[box-shadow:0_11px_28px_rgb(15_54_104_/_.055)]", "tw:[&_>_.muted]:mt-[-12px]",
    "tw:[&_>_.muted]:mr-[0]", "tw:[&_>_.muted]:mb-[0]", "tw:[&_>_.muted]:ml-[0]", "tw:[&_>_.muted]:text-[color:#62738c]",
    "tw:[&_>_.muted]:text-[.88rem]",
  ].join(" "),
  "page_header": sharedUtilities.pageHeader,
  "league_registration_hero": [
    "league-registration-hero", "tw:items-start!", "tw:pb-[17px]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dfe8f2]", "tw:[&_h3]:text-[color:#081d46]", "tw:[&_h3]:text-[clamp(1.35rem,_2.2vw,_1.8rem)]",
    "tw:[&_h3]:tracking-[-.045em]", "tw:[&_.muted]:text-[color:#64738d]", "tw:[&_.muted]:text-[.86rem]",
  ].join(" "),
  "stack_xs": [
    "stack-xs", "tw:grid", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "league_registration_list_section": [
    "league-registration-list-section", "tw:[&_>_h4]:mt-[0]", "tw:[&_>_h4]:mr-[0]", "tw:[&_>_h4]:mb-[0]",
    "tw:[&_>_h4]:ml-[0]", "tw:[&_>_h4]:text-[color:#0d1d40]", "tw:[&_>_h4]:text-[1.05rem]",
  ].join(" "),
  "simple_list": sharedUtilities.simpleList,
  "league_registration_list": [
    "league-registration-list", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
  ].join(" "),
  "simple_item": sharedUtilities.simpleItem,
  "league_registration_card": [
    "league-registration-card", "tw:grid!", "tw:grid-cols-[minmax(0,_1fr)_auto_auto]", "tw:viewport-1180:grid-cols-[minmax(0,_1fr)_auto]",
    "tw:viewport-760:grid-cols-[1fr]", "tw:items-center!", "tw:gap-y-[13px]", "tw:gap-x-[13px]",
    "tw:min-h-[68px]", "tw:pt-[10px]!", "tw:pr-[14px]!", "tw:pb-[10px]!",
    "tw:pl-[14px]!", "tw:border-t-[color:#dce7f2]!", "tw:border-r-[color:#dce7f2]!", "tw:border-b-[color:#dce7f2]!",
    "tw:border-l-[color:#dce7f2]!", "tw:rounded-[10px]!", "tw:bg-[color:#fff]!", "tw:[background-image:none]!",
    "tw:[&:focus-within]:relative", "tw:[&:focus-within]:z-[20]", "tw:[&:focus-within]:[overflow-x:visible]", "tw:[&:focus-within]:[overflow-y:visible]",
    "tw:[&_>_form_.button]:min-h-[36px]", "tw:[&_>_form_.button]:[padding-inline:12px]", "tw:[&_>_form_.button]:text-[.74rem]", "tw:viewport-760:[&_>_form]:[justify-self:start]",
  ].join(" "),
  "match_copy": [
    "match-copy", "tw:grid", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:[&_span]:text-[color:var(--muted)]",
  ].join(" "),
  "league_registration_pair_name": [
    "league-registration-pair-name", "tw:[&_strong]:text-[color:#0c1d40]", "tw:[&_strong]:text-[.88rem]", "tw:[&_strong]:leading-[1.4]",
  ].join(" "),
  "button_button_danger": sharedUtilities.buttonButtonDanger,
  "stack_xs_league_registration_replacements": [
    "stack-xs", "league-registration-replacements", "tw:grid", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:[&_.inline-pair-edit]:grid", "tw:[&_.inline-pair-edit]:grid-cols-[minmax(230px,_1fr)_auto]", "tw:viewport-1180:[&_.inline-pair-edit]:grid-cols-[minmax(0,_1fr)_auto]",
    "tw:viewport-460:[&_.inline-pair-edit]:grid-cols-[1fr]", "tw:[&_.inline-pair-edit]:gap-y-[8px]", "tw:[&_.inline-pair-edit]:gap-x-[8px]", "tw:[&_.inline-pair-edit_select]:min-w-[0]",
    "tw:[&_.inline-pair-edit_select]:min-h-[36px]", "tw:[&_.inline-pair-edit_select]:border-t-[color:#cdddeb]", "tw:[&_.inline-pair-edit_select]:border-r-[color:#cdddeb]", "tw:[&_.inline-pair-edit_select]:border-b-[color:#cdddeb]",
    "tw:[&_.inline-pair-edit_select]:border-l-[color:#cdddeb]", "tw:[&_.inline-pair-edit_select]:rounded-[8px]", "tw:[&_.inline-pair-edit_select]:text-[color:#223757]", "tw:[&_.inline-pair-edit_select]:text-[.84rem]",
    "tw:[&_.inline-pair-edit_.category-athlete-search]:min-w-[0]", "tw:[&_.inline-pair-edit_.category-athlete-search]:mt-[0]", "tw:[&_.inline-pair-edit_.category-athlete-search]:mr-[0]", "tw:[&_.inline-pair-edit_.category-athlete-search]:mb-[0]",
    "tw:[&_.inline-pair-edit_.category-athlete-search]:ml-[0]", "tw:[&_.inline-pair-edit_.category-athlete-search-input]:min-w-[0]", "tw:[&_.inline-pair-edit_.category-athlete-search-input]:min-h-[36px]", "tw:[&_.inline-pair-edit_.category-athlete-search-input]:border-t-[color:#cdddeb]",
    "tw:[&_.inline-pair-edit_.category-athlete-search-input]:border-r-[color:#cdddeb]", "tw:[&_.inline-pair-edit_.category-athlete-search-input]:border-b-[color:#cdddeb]", "tw:[&_.inline-pair-edit_.category-athlete-search-input]:border-l-[color:#cdddeb]", "tw:[&_.inline-pair-edit_.category-athlete-search-input]:rounded-[8px]",
    "tw:[&_.inline-pair-edit_.category-athlete-search-input]:text-[color:#223757]", "tw:[&_.inline-pair-edit_.category-athlete-search-input]:text-[.84rem]", "tw:[&_.inline-pair-edit_.form-error]:[grid-column:1_/_-1]", "tw:[&_.inline-pair-edit_.form-error]:mt-[0]",
    "tw:[&_.inline-pair-edit_.form-error]:mr-[0]", "tw:[&_.inline-pair-edit_.form-error]:mb-[0]", "tw:[&_.inline-pair-edit_.form-error]:ml-[0]", "tw:[&_.inline-pair-edit_.form-success]:[grid-column:1_/_-1]",
    "tw:[&_.inline-pair-edit_.form-success]:mt-[0]", "tw:[&_.inline-pair-edit_.form-success]:mr-[0]", "tw:[&_.inline-pair-edit_.form-success]:mb-[0]", "tw:[&_.inline-pair-edit_.form-success]:ml-[0]",
    "tw:[&_.inline-pair-edit_.button]:min-h-[36px]", "tw:[&_.inline-pair-edit_.button]:border-t-[color:#d0dfed]", "tw:[&_.inline-pair-edit_.button]:border-r-[color:#d0dfed]", "tw:[&_.inline-pair-edit_.button]:border-b-[color:#d0dfed]",
    "tw:[&_.inline-pair-edit_.button]:border-l-[color:#d0dfed]", "tw:[&_.inline-pair-edit_.button]:bg-[color:#fff]", "tw:[&_.inline-pair-edit_.button]:[background-image:none]", "tw:[&_.inline-pair-edit_.button]:text-[color:#1c63bd]",
    "tw:[&_.inline-pair-edit_.button]:[box-shadow:none]", "tw:[&_.inline-pair-edit_.button]:text-[.74rem]", "tw:viewport-1180:[grid-column:1_/_-1]", "tw:viewport-760:[grid-column:auto]",
    "tw:viewport-1180:[grid-row:2]", "tw:viewport-760:[grid-row:auto]", "tw:viewport-760:w-[100%]", "tw:viewport-460:[&_.inline-pair-edit_.button]:w-[100%]",
  ].join(" "),
  "inline_pair_edit": [
    "inline-pair-edit", "tw:flex", "tw:items-center", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:flex-wrap", "tw:[&_select]:min-w-[180px]", "tw:[&_select]:min-h-[38px]",
    "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[12px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[12px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:var(--line)]",
    "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:var(--text)]",
    "tw:[&_.button]:min-h-[38px]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
} as const;
