import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "field_category_athlete_search": [
    "field", "category-athlete-search", "tw:grid", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]", "tw:[&_input]:w-[100%]",
    "tw:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[14px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:text-[color:var(--text)]", "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[44px]",
    "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[14px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:var(--line)]",
    "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:var(--text)]",
    "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_input:focus]:[transform:translateY(-1px)]",
    "tw:[&_select:focus]:[outline:none]", "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]", "tw:[&_input[type=file]]:pt-[10px]",
    "tw:[&_input[type=file]]:pr-[14px]", "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]", "tw:[&_input[type=checkbox]]:w-[auto]",
    "tw:[&_input[type=checkbox]]:min-h-[auto]", "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]", "tw:[&_input[type=checkbox]]:pb-[0]",
    "tw:[&_input[type=checkbox]]:pl-[0]", "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]", "tw:[&_input[type=radio]]:pt-[0]",
    "tw:[&_input[type=radio]]:pr-[0]", "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]", "tw:relative",
  ].join(" "),
  "category_athlete_search_results": [
    "category-athlete-search-results", "tw:absolute", "tw:z-[12]", "tw:top-[calc(100%_+_4px)]",
    "tw:right-[0]", "tw:left-[0]", "tw:grid", "tw:max-h-[218px]",
    "tw:[overflow-y:auto]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line-strong)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line-strong)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line-strong)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line-strong)]", "tw:rounded-[8px]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]",
    "tw:[box-shadow:0_12px_24px_rgb(15_23_42_/_.14)]", "tw:[&_button]:pt-[9px]", "tw:[&_button]:pr-[11px]", "tw:[&_button]:pb-[9px]",
    "tw:[&_button]:pl-[11px]", "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]",
    "tw:[&_button]:border-r-[length:0]", "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:1px]",
    "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:var(--line)]", "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]",
    "tw:[&_button]:border-l-[color:currentColor]", "tw:[&_button]:bg-[color:transparent]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:var(--text)]",
    "tw:[&_button]:[font:inherit]", "tw:[&_button]:text-[.8rem]", "tw:[&_button]:text-left", "tw:[&_button]:cursor-pointer",
    "tw:[&_span]:pt-[9px]", "tw:[&_span]:pr-[11px]", "tw:[&_span]:pb-[9px]", "tw:[&_span]:pl-[11px]",
    "tw:[&_span]:border-t-[length:0]", "tw:[&_span]:[border-top-style:none]", "tw:[&_span]:border-t-[color:currentColor]", "tw:[&_span]:border-r-[length:0]",
    "tw:[&_span]:[border-right-style:none]", "tw:[&_span]:border-r-[color:currentColor]", "tw:[&_span]:border-b-[length:1px]", "tw:[&_span]:[border-bottom-style:solid]",
    "tw:[&_span]:border-b-[color:var(--line)]", "tw:[&_span]:border-l-[length:0]", "tw:[&_span]:[border-left-style:none]", "tw:[&_span]:border-l-[color:currentColor]",
    "tw:[&_span]:bg-[color:transparent]", "tw:[&_span]:[background-image:none]", "tw:[&_span]:text-[color:var(--muted)]", "tw:[&_span]:[font:inherit]",
    "tw:[&_span]:text-[.8rem]", "tw:[&_span]:text-left", "tw:[&_button:hover]:bg-[color:var(--brand-soft)]", "tw:[&_button:hover]:[background-image:none]",
    "tw:[&_button:hover]:[outline:none]", "tw:[&_button:focus-visible]:bg-[color:var(--brand-soft)]", "tw:[&_button:focus-visible]:[background-image:none]", "tw:[&_button:focus-visible]:[outline:none]",
    "tw:[&_>_:last-child]:border-b-[length:0]", "tw:[&_>_:last-child]:[border-bottom-style:none]", "tw:[&_>_:last-child]:border-b-[color:currentColor]",
  ].join(" "),
  "grid_form_category_pair_form": [
    "grid-form", "category-pair-form", "tw:grid", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]", "tw:grid-cols-[minmax(0,_1fr)_minmax(0,_1fr)_auto]", "tw:viewport-760:grid-cols-[1fr]", "tw:[&_textarea]:w-[100%]",
    "tw:[&_textarea]:pt-[12px]", "tw:[&_textarea]:pr-[14px]", "tw:[&_textarea]:pb-[12px]", "tw:[&_textarea]:pl-[14px]",
    "tw:[&_textarea]:border-t-[length:1px]", "tw:[&_textarea]:[border-top-style:solid]", "tw:[&_textarea]:border-t-[color:var(--line)]", "tw:[&_textarea]:border-r-[length:1px]",
    "tw:[&_textarea]:[border-right-style:solid]", "tw:[&_textarea]:border-r-[color:var(--line)]", "tw:[&_textarea]:border-b-[length:1px]", "tw:[&_textarea]:[border-bottom-style:solid]",
    "tw:[&_textarea]:border-b-[color:var(--line)]", "tw:[&_textarea]:border-l-[length:1px]", "tw:[&_textarea]:[border-left-style:solid]", "tw:[&_textarea]:border-l-[color:var(--line)]",
    "tw:[&_textarea]:rounded-[var(--radius-md)]", "tw:[&_textarea]:bg-[color:var(--panel)]", "tw:[&_textarea]:[background-image:none]", "tw:[&_textarea]:text-[color:var(--text)]",
    "tw:[align-items:end]", "tw:[&_.field]:min-w-[0]", "tw:[&_.category-pair-submit]:[grid-column:auto]", "tw:viewport-760:[&_.category-pair-submit]:[grid-column:1]",
    "tw:[&_.category-pair-submit]:[align-self:end]", "tw:[&_>_.form-full]:[grid-column:1_/_-1]",
  ].join(" "),
  "field_field_submit_category_pair_submit": [
    "field", "field-submit", "category-pair-submit", "tw:grid",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]",
    "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]",
    "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[14px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]",
    "tw:[&_input]:border-t-[color:var(--line)]", "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]",
    "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]",
    "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]",
    "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:var(--text)]", "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]",
    "tw:[&_select]:min-h-[44px]", "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]",
    "tw:[&_select]:pl-[14px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]",
    "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]",
    "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]",
    "tw:[&_select]:border-l-[color:var(--line)]", "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]",
    "tw:[&_select]:text-[color:var(--text)]", "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]",
    "tw:[&_input:focus]:[transform:translateY(-1px)]", "tw:[&_select:focus]:[outline:none]", "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]",
    "tw:[&_input[type=file]]:pt-[10px]", "tw:[&_input[type=file]]:pr-[14px]", "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]",
    "tw:[&_input[type=checkbox]]:w-[auto]", "tw:[&_input[type=checkbox]]:min-h-[auto]", "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]",
    "tw:[&_input[type=checkbox]]:pb-[0]", "tw:[&_input[type=checkbox]]:pl-[0]", "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]",
    "tw:[&_input[type=radio]]:pt-[0]", "tw:[&_input[type=radio]]:pr-[0]", "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]",
    "tw:[align-self:end]", "tw:[&_.button]:w-[auto]", "tw:[&_.button]:min-h-[38px]", "tw:[&_.button]:[padding-inline:14px]",
    "tw:[&_.button]:whitespace-nowrap",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "muted_form_full": sharedUtilities.mutedFormFull,
} as const;
