import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "event_quick_actions": [
    "event-quick-actions", "tw:pt-[22px]", "tw:viewport-760:pt-[16px]", "tw:pr-[22px]",
    "tw:viewport-760:pr-[16px]", "tw:pb-[22px]", "tw:viewport-760:pb-[16px]", "tw:pl-[22px]",
    "tw:viewport-760:pl-[16px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#e3eaf3]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#e3eaf3]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e3eaf3]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#e3eaf3]", "tw:rounded-[14px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[box-shadow:0_8px_22px_rgba(19,_55,_104,_.055)]", "tw:[&_header]:flex", "tw:[&_header]:items-center", "tw:[&_header]:gap-y-[9px]",
    "tw:[&_header]:gap-x-[9px]", "tw:[&_header]:mb-[14px]", "tw:[&_header]:min-h-[24px]", "tw:[&_h2]:mt-[0]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#172e56]",
    "tw:[&_h2]:text-[.98rem]", "tw:[&_header_span]:text-[color:#0660dc]", "tw:[&_header_span]:text-[1.2rem]", "tw:[&_>_a]:relative",
    "tw:[&_>_a]:grid", "tw:[&_>_a]:gap-y-[4px]", "tw:[&_>_a]:gap-x-[10px]", "tw:[&_>_a]:mt-[8px]",
    "tw:[&_>_a]:pt-[11px]", "tw:[&_>_a]:pr-[12px]", "tw:[&_>_a]:pb-[11px]", "tw:[&_>_a]:pl-[12px]",
    "tw:[&_>_a]:border-t-[length:1px]", "tw:[&_>_a]:[border-top-style:solid]", "tw:[&_>_a]:border-t-[color:#dce6f3]", "tw:[&_>_a]:border-r-[length:1px]",
    "tw:[&_>_a]:[border-right-style:solid]", "tw:[&_>_a]:border-r-[color:#dce6f3]", "tw:[&_>_a]:border-b-[length:1px]", "tw:[&_>_a]:[border-bottom-style:solid]",
    "tw:[&_>_a]:border-b-[color:#dce6f3]", "tw:[&_>_a]:border-l-[length:1px]", "tw:[&_>_a]:[border-left-style:solid]", "tw:[&_>_a]:border-l-[color:#dce6f3]",
    "tw:[&_>_a]:rounded-[9px]", "tw:[&_>_a]:text-[color:#1a3560]", "tw:[&_>_a]:grid-cols-[34px_minmax(0,_1fr)_16px]", "tw:[&_>_a]:items-center",
    "tw:[&_>_a]:min-h-[72px]", "tw:[&_>_a:hover]:border-t-[color:#9bbdea]", "tw:[&_>_a:hover]:border-r-[color:#9bbdea]", "tw:[&_>_a:hover]:border-b-[color:#9bbdea]",
    "tw:[&_>_a:hover]:border-l-[color:#9bbdea]", "tw:[&_>_a:hover]:bg-[color:#f7fbff]", "tw:[&_>_a:hover]:[background-image:none]", "tw:[&_>_a_strong]:text-[.76rem]",
    "tw:[&_>_a_strong]:[grid-column:2]", "tw:[&_>_a_strong]:[align-self:end]", "tw:[&_>_a_small]:text-[color:#6780a4]", "tw:[&_>_a_small]:text-[.68rem]",
    "tw:[&_>_a_small]:leading-[1.35]", "tw:[&_>_a_small]:[grid-column:2]", "tw:[&_>_a_small]:[align-self:start]", "tw:[&_>_a_b]:absolute",
    "tw:[&_>_a_b]:top-[50%]", "tw:[&_>_a_b]:right-[14px]", "tw:[&_>_a_b]:text-[color:#2d73dc]", "tw:[&_>_a_b]:[transform:translateY(-50%)]",
    "tw:viewport-1080:[grid-row:span_2]", "tw:[&_header_>_.event-icon]:text-[color:#0964dc]", "tw:[&_>_a_>_.event-icon]:[grid-column:3]", "tw:[&_>_a_>_.event-icon]:[grid-row:1_/_span_2]",
    "tw:[&_>_a_>_.event-icon]:text-[color:#4d78bc]",
  ].join(" "),
  "event_quick_action_button": [
    "event-quick-action-button", "tw:grid", "tw:grid-cols-[34px_minmax(0,_1fr)_16px]", "tw:gap-x-[10px]",
    "tw:items-center", "tw:w-[100%]", "tw:min-h-[58px]", "tw:mt-[8px]",
    "tw:pt-[11px]", "tw:pr-[12px]", "tw:pb-[11px]", "tw:pl-[12px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dce6f3]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#dce6f3]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#dce6f3]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#dce6f3]",
    "tw:rounded-[9px]", "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:text-[color:#1a3560]",
    "tw:text-left", "tw:cursor-pointer", "tw:hover:border-t-[color:#9bbdea]", "tw:hover:border-r-[color:#9bbdea]",
    "tw:hover:border-b-[color:#9bbdea]", "tw:hover:border-l-[color:#9bbdea]", "tw:hover:bg-[color:#f7fbff]", "tw:hover:[background-image:none]",
    "tw:[&_strong]:[grid-column:2]", "tw:[&_strong]:text-[.78rem]", "tw:[&_>_.event-icon]:[grid-column:3]", "tw:[&_>_.event-icon]:text-[color:#4d78bc]",
  ].join(" "),
  "event_quick_action_icon": [
    "event-quick-action-icon", "tw:grid", "tw:[grid-column:1]", "tw:[grid-row:1_/_span_2]",
    "tw:w-[32px]", "tw:h-[32px]", "tw:place-items-center", "tw:rounded-[8px]",
    "tw:bg-[color:#eaf2ff]", "tw:[background-image:none]", "tw:text-[color:#1166d3]", "tw:[&.event-quick-action-icon-success]:bg-[color:#e6f9ee]",
    "tw:[&.event-quick-action-icon-success]:[background-image:none]", "tw:[&.event-quick-action-icon-success]:text-[color:#16a25c]", "tw:[&.event-quick-action-icon-purple]:bg-[color:#f1eaff]", "tw:[&.event-quick-action-icon-purple]:[background-image:none]",
    "tw:[&.event-quick-action-icon-purple]:text-[color:#7a48d9]",
  ].join(" "),
  "event_action_modal_backdrop": [
    "event-action-modal-backdrop", "tw:fixed", "tw:z-[80]", "tw:top-[0]",
    "tw:right-[0]", "tw:bottom-[0]", "tw:left-[0]", "tw:grid",
    "tw:place-items-center", "tw:pt-[24px]", "tw:pr-[24px]", "tw:pb-[24px]",
    "tw:pl-[24px]", "tw:bg-[color:rgba(14,_31,_59,_.42)]", "tw:[background-image:none]", "tw:[backdrop-filter:blur(4px)]",
  ].join(" "),
  "event_action_modal": [
    "event-action-modal", "tw:w-[min(860px,_100%)]", "tw:viewport-620:w-[min(100%,_calc(100vw_-_24px))]", "tw:max-h-[min(86vh,_880px)]",
    "tw:[overflow-x:auto]", "tw:[overflow-y:auto]", "tw:pt-[28px]", "tw:viewport-620:pt-[18px]",
    "tw:pr-[28px]", "tw:viewport-620:pr-[18px]", "tw:pb-[28px]", "tw:viewport-620:pb-[18px]",
    "tw:pl-[28px]", "tw:viewport-620:pl-[18px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dce6f3]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce6f3]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce6f3]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dce6f3]", "tw:rounded-[14px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[box-shadow:0_28px_70px_rgba(10,_33,_74,_.25)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:items-start",
    "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[18px]", "tw:[&_>_header]:gap-x-[18px]", "tw:[&_>_header]:pb-[16px]",
    "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#e5edf6]", "tw:[&_h2]:mt-[3px]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#122c57]",
    "tw:[&_h2]:text-[1.3rem]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "event_action_modal_content": [
    "event-action-modal-content", "tw:pt-[20px]",
  ].join(" "),
  "event_action_public_page": [
    "event-action-public-page", "tw:grid", "tw:[justify-items:start]", "tw:gap-y-[16px]",
    "tw:gap-x-[16px]", "tw:text-[color:#58708f]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
} as const;
