"use client";
import { viewStyles } from "./league-category-settings-dialog.utilities";

import { useState } from "react";
import { updateLeagueCategoryAction } from "@/lib/actions/category-competition";
import { CATEGORY_CLASS_OPTIONS, CATEGORY_GENDER_OPTIONS } from "@/lib/tournament-category/options";

export function LeagueCategorySettingsDialog({ category }: { category: { id: string; name: string; class: string; gender: string; leagueTier: string; registrationFeeCents: number } }) {
  const [open, setOpen] = useState(false);
  return <><button type="button" className={viewStyles.button_button_small_league_category_edit_trigger} onClick={() => setOpen(true)}>Editar Liga</button>{open ? <div className={viewStyles.league_settings_overlay} role="presentation" onMouseDown={() => setOpen(false)}><form action={updateLeagueCategoryAction} className={viewStyles.league_settings_dialog} role="dialog" aria-modal="true" aria-label="Editar Liga" onMouseDown={(event) => event.stopPropagation()}><header><div><p className={viewStyles.eyebrow}>Liga</p><h2>Editar Liga</h2></div><button type="button" className={viewStyles.button_button_small} onClick={() => setOpen(false)}>Fechar</button></header><input type="hidden" name="categoryId" value={category.id} /><label className={viewStyles.field}>Nome da Liga<input name="name" defaultValue={category.name} required /></label><div className={viewStyles.league_settings_grid}><label className={viewStyles.field}>Classe<select name="class" defaultValue={category.class}>{CATEGORY_CLASS_OPTIONS.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className={viewStyles.field}>Gênero<select name="gender" defaultValue={category.gender}>{CATEGORY_GENDER_OPTIONS.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className={viewStyles.field}>Nível da Liga<select name="leagueTier" defaultValue={category.leagueTier || "A"}><option value="A">Liga A</option><option value="B">Liga B</option></select></label><label className={viewStyles.field}>Valor da inscrição<input name="registrationFee" inputMode="decimal" defaultValue={(category.registrationFeeCents / 100).toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} placeholder="0,00" required /></label></div><footer><button type="button" className={viewStyles.button} onClick={() => setOpen(false)}>Cancelar</button><button className={viewStyles.button_button_primary} type="submit">Salvar alterações</button></footer></form></div> : null}</>;
}
