"use client";

import { useState } from "react";
import { updateLeagueCategoryAction } from "@/lib/actions/category-competition";
import { CATEGORY_CLASS_OPTIONS, CATEGORY_GENDER_OPTIONS } from "@/lib/tournament-category/options";

export function LeagueCategorySettingsDialog({ category }: { category: { id: string; name: string; class: string; gender: string; leagueTier: string } }) {
  const [open, setOpen] = useState(false);
  return <><button type="button" className="button button-small league-category-edit-trigger" onClick={() => setOpen(true)}>Editar categoria</button>{open ? <div className="league-settings-overlay" role="presentation" onMouseDown={() => setOpen(false)}><form action={updateLeagueCategoryAction} className="league-settings-dialog" role="dialog" aria-modal="true" aria-label="Editar categoria da Liga" onMouseDown={(event) => event.stopPropagation()}><header><div><p className="eyebrow">Liga</p><h2>Editar categoria</h2></div><button type="button" className="button button-small" onClick={() => setOpen(false)}>Fechar</button></header><input type="hidden" name="categoryId" value={category.id} /><label className="field">Nome<input name="name" defaultValue={category.name} required /></label><div className="league-settings-grid"><label className="field">Classe<select name="class" defaultValue={category.class}>{CATEGORY_CLASS_OPTIONS.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="field">Gênero<select name="gender" defaultValue={category.gender}>{CATEGORY_GENDER_OPTIONS.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="field">Nível da Liga<select name="leagueTier" defaultValue={category.leagueTier || "A"}><option value="A">Liga A</option><option value="B">Liga B</option></select></label></div><footer><button type="button" className="button" onClick={() => setOpen(false)}>Cancelar</button><button className="button button-primary" type="submit">Salvar alterações</button></footer></form></div> : null}</>;
}
