import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "button_button_primary_public_league_schedule_trigger": [
    "button", "button-primary", "public-league-schedule-trigger", "tw:inline-flex",
    "tw:items-center", "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:min-h-[36px]", "tw:pt-[0]", "tw:pr-[12px]", "tw:pb-[0]",
    "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--brand)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--brand)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--brand)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--brand)]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--brand)]", "tw:[background-image:none]",
    "tw:text-[color:#ffffff]", "tw:text-[0.86rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--brand-strong)]",
    "tw:hover:border-r-[color:var(--brand-strong)]", "tw:hover:border-b-[color:var(--brand-strong)]", "tw:hover:border-l-[color:var(--brand-strong)]", "tw:hover:[transform:translateY(-1px)]",
    "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]",
    "tw:[&:active]:[box-shadow:none]", "tw:hover:bg-[color:var(--brand-strong)]", "tw:hover:[background-image:none]", "tw:w-[fit-content]",
  ].join(" "),
  "public_league_schedule_modal_backdrop": [
    "public-league-schedule-modal-backdrop", "tw:fixed", "tw:z-[80]", "tw:top-[0]",
    "tw:right-[0]", "tw:bottom-[0]", "tw:left-[0]", "tw:grid",
    "tw:[overflow-y:auto]", "tw:place-items-center", "tw:pt-[20px]", "tw:viewport-620:pt-[0]",
    "tw:pr-[20px]", "tw:viewport-620:pr-[0]", "tw:pb-[20px]", "tw:viewport-620:pb-[0]",
    "tw:pl-[20px]", "tw:viewport-620:pl-[0]", "tw:bg-[color:rgb(2_12_23_/_.72)]", "tw:[background-image:none]",
    "tw:[backdrop-filter:blur(5px)]", "tw:viewport-620:[align-items:end]",
  ].join(" "),
  "public_league_schedule_modal": [
    "public-league-schedule-modal", "tw:grid", "tw:w-[min(100%,_720px)]", "tw:viewport-620:w-[100%]",
    "tw:max-h-[min(820px,_calc(100vh_-_40px))]", "tw:viewport-620:max-h-[min(88vh,_760px)]", "tw:gap-y-[16px]", "tw:gap-x-[16px]",
    "tw:[overflow-y:auto]", "tw:pt-[22px]", "tw:viewport-620:pt-[17px]", "tw:pr-[22px]",
    "tw:viewport-620:pr-[15px]", "tw:pb-[22px]", "tw:viewport-620:pb-[calc(17px_+_env(safe-area-inset-bottom))]", "tw:pl-[22px]",
    "tw:viewport-620:pl-[15px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(93_167_204_/_.4)]",
    "tw:border-r-[length:1px]", "tw:viewport-620:border-r-[length:0]", "tw:[border-right-style:solid]", "tw:viewport-620:[border-right-style:none]",
    "tw:border-r-[color:rgb(93_167_204_/_.4)]", "tw:viewport-620:border-r-[color:currentColor]", "tw:border-b-[length:1px]", "tw:viewport-620:border-b-[length:0]",
    "tw:[border-bottom-style:solid]", "tw:viewport-620:[border-bottom-style:none]", "tw:border-b-[color:rgb(93_167_204_/_.4)]", "tw:viewport-620:border-b-[color:currentColor]",
    "tw:border-l-[length:1px]", "tw:viewport-620:border-l-[length:0]", "tw:[border-left-style:solid]", "tw:viewport-620:[border-left-style:none]",
    "tw:border-l-[color:rgb(93_167_204_/_.4)]", "tw:viewport-620:border-l-[color:currentColor]", "tw:rounded-[16px]", "tw:viewport-620:rounded-[18px_18px_0_0]",
    "tw:text-[color:#eaf6ff]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_#0e2740,_#081a2d)]", "tw:[box-shadow:0_24px_70px_rgb(0_0_0_/_.42)]",
    "tw:[&_>_header]:flex", "tw:[&_>_header]:items-start", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[14px]",
    "tw:[&_>_header]:gap-x-[14px]", "tw:[&_>_footer]:flex", "tw:[&_>_footer]:items-start", "tw:viewport-620:[&_>_footer]:items-stretch",
    "tw:[&_>_footer]:justify-between", "tw:[&_>_footer]:gap-y-[14px]", "tw:[&_>_footer]:gap-x-[14px]", "tw:[&_header_>_div]:grid",
    "tw:[&_header_>_div]:gap-y-[4px]", "tw:[&_header_>_div]:gap-x-[4px]", "tw:[&_header_span]:text-[color:#58dfae]", "tw:[&_header_span]:text-[.66rem]",
    "tw:[&_header_span]:font-[850]", "tw:[&_header_span]:tracking-[.1em]", "tw:[&_footer_span]:text-[color:#58dfae]", "tw:[&_footer_span]:text-[.66rem]",
    "tw:[&_footer_span]:font-[850]", "tw:[&_footer_span]:tracking-[.1em]", "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]",
    "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]", "tw:[&_h3]:text-[color:#f3f9ff]", "tw:[&_h3]:text-[1.3rem]",
    "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
    "tw:[&_header_p]:text-[color:#a8c3d2]", "tw:[&_header_p]:text-[.78rem]", "tw:[&_header_p]:leading-[1.4]", "tw:[&_.field]:grid",
    "tw:[&_.field]:gap-y-[5px]", "tw:[&_.field]:gap-x-[5px]", "tw:[&_.field]:text-[color:#b9d1de]", "tw:[&_.field]:text-[.72rem]",
    "tw:[&_.field]:font-[800]", "tw:[&_select]:min-h-[40px]", "tw:[&_select]:border-t-[color:rgb(95_167_205_/_.5)]", "tw:[&_select]:border-r-[color:rgb(95_167_205_/_.5)]",
    "tw:[&_select]:border-b-[color:rgb(95_167_205_/_.5)]", "tw:[&_select]:border-l-[color:rgb(95_167_205_/_.5)]", "tw:[&_select]:text-[color:#f1f9ff]", "tw:[&_select]:bg-[color:#102f4a]",
    "tw:[&_select]:[background-image:none]", "tw:[&_.public-booking-court-picker]:grid", "tw:[&_.public-booking-court-picker]:gap-y-[8px]", "tw:[&_.public-booking-court-picker]:gap-x-[8px]",
    "tw:[&_.public-booking-court-picker_>_strong]:text-[color:#dceefa]", "tw:[&_.public-booking-court-picker_>_strong]:text-[.78rem]", "tw:[&_.public-booking-slot-blocks_>_strong]:text-[color:#dceefa]", "tw:[&_.public-booking-slot-blocks_>_strong]:text-[.78rem]",
    "tw:[&_.public-booking-court-picker_>_div]:grid", "tw:[&_.public-booking-court-picker_>_div]:grid-cols-[repeat(auto-fit,_minmax(150px,_1fr))]", "tw:viewport-620:[&_.public-booking-court-picker_>_div]:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:[&_.public-booking-court-picker_>_div]:gap-y-[8px]",
    "tw:[&_.public-booking-court-picker_>_div]:gap-x-[8px]", "tw:[&_.public-booking-court-card]:min-h-[60px]", "tw:[&_.public-booking-court-card]:text-[color:#dceefa]", "tw:[&_.public-booking-court-card]:bg-[color:#102b43]",
    "tw:[&_.public-booking-court-card]:[background-image:none]", "tw:[&_.public-booking-court-card_small]:text-[color:#9bb6c8]", "tw:[&_.public-booking-slot-blocks]:grid", "tw:[&_.public-booking-slot-blocks]:gap-y-[8px]",
    "tw:[&_.public-booking-slot-blocks]:gap-x-[8px]", "tw:[&_.public-booking-slot-blocks_>_div]:grid", "tw:[&_.public-booking-slot-blocks_>_div]:grid-cols-[repeat(auto-fill,_minmax(78px,_1fr))]", "tw:[&_.public-booking-slot-blocks_>_div]:gap-y-[7px]",
    "tw:[&_.public-booking-slot-blocks_>_div]:gap-x-[7px]", "tw:[&_.public-booking-slot-block]:min-h-[52px]", "tw:[&_.public-booking-slot-block]:border-t-[color:rgb(94_166_202_/_.34)]", "tw:[&_.public-booking-slot-block]:border-r-[color:rgb(94_166_202_/_.34)]",
    "tw:[&_.public-booking-slot-block]:border-b-[color:rgb(94_166_202_/_.34)]", "tw:[&_.public-booking-slot-block]:border-l-[color:rgb(94_166_202_/_.34)]", "tw:[&_.public-booking-slot-block]:text-[color:#dceef8]", "tw:[&_.public-booking-slot-block]:bg-[color:#102d47]",
    "tw:[&_.public-booking-slot-block]:[background-image:none]", "tw:[&_.public-booking-slot-block_small]:text-[color:#9bbccf]", "tw:[&_.public-booking-slot-block-active]:border-t-[color:#4ce0ae]", "tw:[&_.public-booking-slot-block-active]:border-r-[color:#4ce0ae]",
    "tw:[&_.public-booking-slot-block-active]:border-b-[color:#4ce0ae]", "tw:[&_.public-booking-slot-block-active]:border-l-[color:#4ce0ae]", "tw:[&_.public-booking-slot-block-active]:bg-[color:#176758]", "tw:[&_.public-booking-slot-block-active]:[background-image:none]",
    "tw:[&_footer]:items-center", "tw:[&_footer]:pt-[14px]", "tw:[&_footer]:border-t-[length:1px]", "tw:[&_footer]:[border-top-style:solid]",
    "tw:[&_footer]:border-t-[color:rgb(98_162_197_/_.25)]", "tw:[&_footer_>_div]:grid", "tw:[&_footer_>_div]:gap-y-[3px]", "tw:[&_footer_>_div]:gap-x-[3px]",
    "tw:[&_footer_strong]:text-[color:#ecf8ff]", "tw:[&_footer_strong]:text-[.8rem]", "tw:[&_footer_small]:text-[color:#a9c3d3]", "tw:[&_footer_small]:text-[.69rem]",
    "tw:[&_footer_.button]:[flex:0_0_auto]", "tw:viewport-620:[&_>_footer]:flex-col", "tw:viewport-620:[&_footer_.button]:w-[100%]", "tw:viewport-620:[&_.public-booking-court-card]:min-w-[0]",
    "tw:viewport-620:[&_.public-booking-court-card]:pt-[8px]", "tw:viewport-620:[&_.public-booking-court-card]:pr-[8px]", "tw:viewport-620:[&_.public-booking-court-card]:pb-[8px]", "tw:viewport-620:[&_.public-booking-court-card]:pl-[8px]",
    "tw:viewport-620:[&_.public-booking-court-card_span]:text-[.74rem]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "field": sharedUtilities.field,
  "public_booking_court_picker": [
    "public-booking-court-picker", "tw:grid", "tw:[grid-column:1_/_-1]", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:[&_>_strong]:text-[color:#43536b]", "tw:[&_>_strong]:text-[.74rem]", "tw:[&_>_div]:grid",
    "tw:[&_>_div]:grid-cols-[repeat(auto-fit,_minmax(145px,_1fr))]", "tw:viewport-520:[&_>_div]:grid-cols-[1fr]", "tw:[&_>_div]:gap-y-[8px]", "tw:[&_>_div]:gap-x-[8px]",
    "tw:[&_>_div]:max-w-[580px]", "tw:viewport-520:[&_>_div]:max-w-[none]",
  ].join(" "),
  "public_booking_court_card": [
    "public-booking-court-card", "tw:grid", "tw:grid-cols-[8px_minmax(0,_1fr)]", "tw:gap-y-[2px]",
    "tw:gap-x-[8px]", "tw:min-h-[57px]", "tw:pt-[8px]", "tw:pr-[10px]",
    "tw:pb-[8px]", "tw:pl-[10px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#9dcde2]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#9dcde2]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#9dcde2]", "tw:border-l-[length:5px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#9dcde2]", "tw:rounded-[9px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:text-[color:#26364d]", "tw:[font:inherit]", "tw:text-left",
    "tw:cursor-pointer", "tw:[&_i]:w-[8px]", "tw:[&_i]:h-[8px]", "tw:[&_i]:[align-self:center]",
    "tw:[&_i]:rounded-[999px]", "tw:[&_span]:min-w-[0]", "tw:[&_span]:[overflow-x:hidden]", "tw:[&_span]:[overflow-y:hidden]",
    "tw:[&_span]:text-[.8rem]", "tw:[&_span]:font-[750]", "tw:[&_span]:text-ellipsis", "tw:[&_span]:whitespace-nowrap",
    "tw:[&_small]:[grid-column:2]", "tw:[&_small]:text-[color:#63748b]", "tw:[&_small]:text-[.67rem]", "tw:hover:border-t-[color:#4ecda4]",
    "tw:hover:border-r-[color:#4ecda4]", "tw:hover:border-b-[color:#4ecda4]", "tw:hover:border-l-[color:#4ecda4]", "tw:[&.is-active]:border-t-[color:#1aa87d]",
    "tw:[&.is-active]:border-r-[color:#1aa87d]", "tw:[&.is-active]:border-b-[color:#1aa87d]", "tw:[&.is-active]:border-l-[color:#1aa87d]", "tw:[&.is-active]:bg-[color:#0a725d]",
    "tw:[&.is-active]:[background-image:none]", "tw:[&.is-active]:text-[color:#fff]", "tw:[&.is-active]:[box-shadow:0_4px_10px_rgb(8_119_95_/_.2)]", "tw:[&.is-active_small]:text-[color:rgb(232_255_246_/_.78)]",
  ].join(" "),
  "public_league_schedule_dates": [
    "public-league-schedule-dates", "tw:[&_>_strong]:text-[color:#dceefa]", "tw:[&_>_strong]:text-[.78rem]", "tw:grid",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:[&_>_div]:flex", "tw:[&_>_div]:gap-y-[7px]",
    "tw:[&_>_div]:gap-x-[7px]", "tw:[&_>_div]:[overflow-x:auto]", "tw:[&_>_div]:pb-[2px]", "tw:[&_button]:[flex:0_0_auto]",
    "tw:[&_button]:min-h-[34px]", "tw:[&_button]:pt-[6px]", "tw:[&_button]:pr-[10px]", "tw:[&_button]:pb-[6px]",
    "tw:[&_button]:pl-[10px]", "tw:[&_button]:border-t-[length:1px]", "tw:[&_button]:[border-top-style:solid]", "tw:[&_button]:border-t-[color:rgb(93_164_201_/_.34)]",
    "tw:[&_button]:border-r-[length:1px]", "tw:[&_button]:[border-right-style:solid]", "tw:[&_button]:border-r-[color:rgb(93_164_201_/_.34)]", "tw:[&_button]:border-b-[length:1px]",
    "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:rgb(93_164_201_/_.34)]", "tw:[&_button]:border-l-[length:1px]", "tw:[&_button]:[border-left-style:solid]",
    "tw:[&_button]:border-l-[color:rgb(93_164_201_/_.34)]", "tw:[&_button]:rounded-[7px]", "tw:[&_button]:text-[color:#bed1de]", "tw:[&_button]:bg-[color:#0d2940]",
    "tw:[&_button]:[background-image:none]", "tw:[&_button]:[font:inherit]", "tw:[&_button]:text-[.7rem]", "tw:[&_button]:font-[750]",
    "tw:[&_button]:[text-transform:capitalize]", "tw:[&_button.is-active]:border-t-[color:#4ce0ae]", "tw:[&_button.is-active]:border-r-[color:#4ce0ae]", "tw:[&_button.is-active]:border-b-[color:#4ce0ae]",
    "tw:[&_button.is-active]:border-l-[color:#4ce0ae]", "tw:[&_button.is-active]:text-[color:#effff8]", "tw:[&_button.is-active]:bg-[color:#156557]", "tw:[&_button.is-active]:[background-image:none]",
  ].join(" "),
  "public_booking_slot_blocks": [
    "public-booking-slot-blocks", "tw:[grid-column:1_/_-1]", "tw:grid", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:[&_strong]:text-[color:#43536b]", "tw:[&_strong]:text-[.74rem]", "tw:[&_>_div]:flex",
    "tw:viewport-720:[&_>_div]:grid", "tw:[&_>_div]:flex-wrap", "tw:[&_>_div]:gap-y-[7px]", "tw:[&_>_div]:gap-x-[7px]",
    "tw:viewport-720:[&_>_div]:grid-cols-[repeat(2,_minmax(0,_1fr))]",
  ].join(" "),
  "public_booking_slot_block": [
    "public-booking-slot-block", "tw:grid", "tw:gap-y-[2px]", "tw:gap-x-[2px]",
    "tw:min-w-[78px]", "tw:viewport-720:min-w-[0]", "tw:pt-[8px]", "tw:pr-[9px]",
    "tw:pb-[8px]", "tw:pl-[9px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#9dcde2]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#9dcde2]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#9dcde2]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#9dcde2]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:text-[color:#26364d]", "tw:text-left", "tw:cursor-pointer",
    "tw:[&_b]:text-[.78rem]", "tw:[&_small]:text-[color:#63748b]", "tw:[&_small]:text-[.68rem]", "tw:hover:border-t-[color:#08775f]",
    "tw:hover:border-r-[color:#08775f]", "tw:hover:border-b-[color:#08775f]", "tw:hover:border-l-[color:#08775f]", "tw:hover:bg-[color:#dff7ea]",
    "tw:hover:[background-image:none]", "tw:hover:text-[color:#075d48]", "tw:hover:[box-shadow:0_3px_8px_rgb(8_119_95_/_.13)]",
  ].join(" "),
  "public_booking_slot_block_active": [
    "public-booking-slot-block-active", "tw:border-t-[color:#08775f]", "tw:border-r-[color:#08775f]", "tw:border-b-[color:#08775f]",
    "tw:border-l-[color:#08775f]", "tw:bg-[color:#dff7ea]", "tw:[background-image:none]", "tw:text-[color:#075d48]",
    "tw:[box-shadow:0_3px_8px_rgb(8_119_95_/_.13)]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
} as const;
