import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "public_league_portal_section_card_stack_md": [
    "public-league-portal", "section-card", "stack-md", "tw:bg-[color:#0d1b28]",
    "tw:[background-image:none]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(120_162_185_/_.2)]",
    "tw:w-[min(calc(100%_-_32px),_1060px)]", "tw:viewport-700:w-[calc(100%_-_28px)]", "tw:[margin-inline:auto]", "tw:mt-[22px]",
    "tw:viewport-700:mt-[16px]", "tw:pt-[26px]", "tw:viewport-700:pt-[16px]", "tw:pr-[26px]",
    "tw:viewport-700:pr-[16px]", "tw:pb-[26px]", "tw:viewport-700:pb-[16px]", "tw:pl-[26px]",
    "tw:viewport-700:pl-[16px]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(120_162_185_/_.2)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(120_162_185_/_.2)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(120_162_185_/_.2)]", "tw:rounded-[15px]", "tw:[box-shadow:0_18px_42px_rgb(0_0_0_/_.2)]",
    "tw:text-[color:#dbeaf2]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]",
    "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#edf7fb]", "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]",
    "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]", "tw:[&_h3]:text-[color:#edf7fb]", "tw:[&_p]:mt-[0]",
    "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_.portal-league-category-picker]:w-[fit-content]",
    "tw:viewport-700:[&_.portal-league-category-picker]:w-[100%]", "tw:[&_.portal-league-category-picker]:max-w-[100%]", "tw:[&_.portal-league-category-picker]:[align-items:end]", "tw:viewport-700:[&_.portal-league-category-picker]:items-stretch",
    "tw:[&_.portal-league-category-picker]:gap-y-[10px]", "tw:viewport-700:[&_.portal-league-category-picker]:gap-y-[8px]", "tw:[&_.portal-league-category-picker]:gap-x-[10px]", "tw:viewport-700:[&_.portal-league-category-picker]:gap-x-[8px]",
    "tw:[&_.portal-league-category-picker]:mt-[18px]", "tw:[&_.portal-league-category-picker]:pt-[0]", "tw:[&_.portal-league-category-picker]:pr-[0]", "tw:[&_.portal-league-category-picker]:pb-[0]",
    "tw:[&_.portal-league-category-picker]:pl-[0]", "tw:[&_.portal-league-category-picker]:border-t-[length:0]", "tw:[&_.portal-league-category-picker]:[border-top-style:none]", "tw:[&_.portal-league-category-picker]:border-t-[color:currentColor]",
    "tw:[&_.portal-league-category-picker]:border-r-[length:0]", "tw:[&_.portal-league-category-picker]:[border-right-style:none]", "tw:[&_.portal-league-category-picker]:border-r-[color:currentColor]", "tw:[&_.portal-league-category-picker]:border-b-[length:0]",
    "tw:[&_.portal-league-category-picker]:[border-bottom-style:none]", "tw:[&_.portal-league-category-picker]:border-b-[color:currentColor]", "tw:[&_.portal-league-category-picker]:border-l-[length:0]", "tw:[&_.portal-league-category-picker]:[border-left-style:none]",
    "tw:[&_.portal-league-category-picker]:border-l-[color:currentColor]", "tw:[&_.portal-league-category-picker]:rounded-[0]", "tw:[&_.portal-league-category-picker]:bg-[color:transparent]", "tw:[&_.portal-league-category-picker]:[background-image:none]",
    "tw:[&_.portal-league-category-picker_label]:grid", "tw:[&_.portal-league-category-picker_label]:[flex:0_1_350px]", "tw:[&_.portal-league-category-picker_label]:gap-y-[5px]", "tw:[&_.portal-league-category-picker_label]:gap-x-[5px]",
    "tw:[&_.portal-league-category-picker_label]:min-w-[min(270px,_100%)]", "tw:viewport-700:[&_.portal-league-category-picker_label]:min-w-[0]", "tw:[&_.portal-league-category-picker_label]:text-[color:#9bb5c5]", "tw:[&_.portal-league-category-picker_label]:text-[.66rem]",
    "tw:[&_.portal-league-category-picker_label]:font-[850]", "tw:[&_.portal-league-category-picker_label]:tracking-[.055em]", "tw:[&_.portal-league-category-picker_label]:leading-[1.15]", "tw:[&_.portal-league-category-picker_label]:uppercase",
    "tw:[&_.portal-league-category-picker_select]:w-[100%]", "tw:[&_.portal-league-category-picker_select]:min-w-[0]", "tw:[&_.portal-league-category-picker_select]:min-h-[38px]", "tw:[&_.portal-league-category-picker_select]:pt-[0]",
    "tw:[&_.portal-league-category-picker_select]:pr-[31px]", "tw:[&_.portal-league-category-picker_select]:pb-[0]", "tw:[&_.portal-league-category-picker_select]:pl-[11px]", "tw:[&_.portal-league-category-picker_select]:border-t-[length:1px]",
    "tw:[&_.portal-league-category-picker_select]:[border-top-style:solid]", "tw:[&_.portal-league-category-picker_select]:border-t-[color:rgb(124_171_198_/_.38)]", "tw:[&_.portal-league-category-picker_select]:border-r-[length:1px]", "tw:[&_.portal-league-category-picker_select]:[border-right-style:solid]",
    "tw:[&_.portal-league-category-picker_select]:border-r-[color:rgb(124_171_198_/_.38)]", "tw:[&_.portal-league-category-picker_select]:border-b-[length:1px]", "tw:[&_.portal-league-category-picker_select]:[border-bottom-style:solid]", "tw:[&_.portal-league-category-picker_select]:border-b-[color:rgb(124_171_198_/_.38)]",
    "tw:[&_.portal-league-category-picker_select]:border-l-[length:1px]", "tw:[&_.portal-league-category-picker_select]:[border-left-style:solid]", "tw:[&_.portal-league-category-picker_select]:border-l-[color:rgb(124_171_198_/_.38)]", "tw:[&_.portal-league-category-picker_select]:rounded-[8px]",
    "tw:[&_.portal-league-category-picker_select]:text-[color:#ecf7fc]", "tw:[&_.portal-league-category-picker_select]:bg-[color:#122b3e]", "tw:[&_.portal-league-category-picker_select]:[background-image:none]", "tw:[&_.portal-league-category-picker_select]:[box-shadow:none]",
    "tw:[&_.portal-league-category-picker_select]:text-[.8rem]", "tw:[&_.portal-league-category-picker_select]:font-[750]", "tw:[&_.portal-league-category-picker_.button]:min-h-[38px]", "tw:[&_.portal-league-category-picker_.button]:pt-[0]",
    "tw:[&_.portal-league-category-picker_.button]:pr-[13px]", "tw:[&_.portal-league-category-picker_.button]:pb-[0]", "tw:[&_.portal-league-category-picker_.button]:pl-[13px]", "tw:[&_.portal-league-category-picker_.button]:border-t-[color:rgb(124_171_198_/_.38)]",
    "tw:[&_.portal-league-category-picker_.button]:border-r-[color:rgb(124_171_198_/_.38)]", "tw:[&_.portal-league-category-picker_.button]:border-b-[color:rgb(124_171_198_/_.38)]", "tw:[&_.portal-league-category-picker_.button]:border-l-[color:rgb(124_171_198_/_.38)]", "tw:[&_.portal-league-category-picker_.button]:text-[color:#ecf7fc]",
    "tw:[&_.portal-league-category-picker_.button]:bg-[color:#122b3e]", "tw:[&_.portal-league-category-picker_.button]:[background-image:none]", "tw:[&_.portal-league-category-picker_.button]:[box-shadow:none]", "tw:[&_.portal-league-category-picker_.button]:text-[.74rem]",
    "tw:[&_.portal-league-category-picker_.button]:font-[750]", "tw:[&_.portal-league-category-picker_.button]:whitespace-nowrap", "tw:[&_.portal-league-category-picker_.button:hover]:border-t-[color:#9dbad6]", "tw:[&_.portal-league-category-picker_.button:hover]:border-r-[color:#9dbad6]",
    "tw:[&_.portal-league-category-picker_.button:hover]:border-b-[color:#9dbad6]", "tw:[&_.portal-league-category-picker_.button:hover]:border-l-[color:#9dbad6]", "tw:[&_.portal-league-category-picker_.button:hover]:text-[color:#164b7b]", "tw:[&_.portal-league-category-picker_.button:hover]:bg-[color:#f2f8fd]",
    "tw:[&_.portal-league-category-picker_.button:hover]:[background-image:none]", "tw:[&_.portal-league-category-context]:mt-[7px]", "tw:[&_.portal-league-category-context]:mr-[0]", "tw:[&_.portal-league-category-context]:mb-[0]",
    "tw:[&_.portal-league-category-context]:ml-[0]", "tw:[&_.portal-league-category-context]:text-[color:#9bb5c5]", "tw:[&_.portal-league-category-context]:text-[.78rem]", "tw:[&_.portal-league-category-context]:leading-[1.45]",
    "tw:[&_.portal-league-category-summary]:flex", "tw:[&_.portal-league-category-summary]:items-center", "tw:viewport-700:[&_.portal-league-category-summary]:items-start", "tw:[&_.portal-league-category-summary]:justify-between",
    "tw:[&_.portal-league-category-summary]:gap-y-[12px]", "tw:viewport-700:[&_.portal-league-category-summary]:gap-y-[2px]", "tw:[&_.portal-league-category-summary]:gap-x-[12px]", "tw:viewport-700:[&_.portal-league-category-summary]:gap-x-[2px]",
    "tw:[&_.portal-league-registration-fee]:inline-flex", "tw:[&_.portal-league-registration-fee]:[flex:0_0_auto]", "tw:[&_.portal-league-registration-fee]:items-baseline", "tw:[&_.portal-league-registration-fee]:gap-y-[5px]",
    "tw:[&_.portal-league-registration-fee]:gap-x-[5px]", "tw:[&_.portal-league-registration-fee]:mt-[7px]", "tw:[&_.portal-league-registration-fee]:mr-[0]", "tw:[&_.portal-league-registration-fee]:mb-[0]",
    "tw:[&_.portal-league-registration-fee]:ml-[0]", "tw:[&_.portal-league-registration-fee]:pt-[6px]", "tw:[&_.portal-league-registration-fee]:pr-[8px]", "tw:[&_.portal-league-registration-fee]:pb-[6px]",
    "tw:[&_.portal-league-registration-fee]:pl-[8px]", "tw:[&_.portal-league-registration-fee]:border-t-[length:1px]", "tw:[&_.portal-league-registration-fee]:[border-top-style:solid]", "tw:[&_.portal-league-registration-fee]:border-t-[color:rgb(64_210_167_/_.34)]",
    "tw:[&_.portal-league-registration-fee]:border-r-[length:1px]", "tw:[&_.portal-league-registration-fee]:[border-right-style:solid]", "tw:[&_.portal-league-registration-fee]:border-r-[color:rgb(64_210_167_/_.34)]", "tw:[&_.portal-league-registration-fee]:border-b-[length:1px]",
    "tw:[&_.portal-league-registration-fee]:[border-bottom-style:solid]", "tw:[&_.portal-league-registration-fee]:border-b-[color:rgb(64_210_167_/_.34)]", "tw:[&_.portal-league-registration-fee]:border-l-[length:1px]", "tw:[&_.portal-league-registration-fee]:[border-left-style:solid]",
    "tw:[&_.portal-league-registration-fee]:border-l-[color:rgb(64_210_167_/_.34)]", "tw:[&_.portal-league-registration-fee]:rounded-[8px]", "tw:[&_.portal-league-registration-fee]:text-[color:#a9efda]", "tw:[&_.portal-league-registration-fee]:bg-[color:#12352f]",
    "tw:[&_.portal-league-registration-fee]:[background-image:none]", "tw:[&_.portal-league-registration-fee]:text-[.71rem]", "tw:[&_.portal-league-registration-fee]:leading-[1.2]", "tw:[&_.portal-league-registration-fee_span]:text-[color:#a8cdbf]",
    "tw:[&_.portal-league-registration-fee_span]:font-[700]", "tw:[&_.portal-league-registration-fee_strong]:text-[color:#59e4b7]", "tw:[&_.portal-league-registration-fee_strong]:text-[.8rem]", "tw:[&_.portal-league-registration-fee_small]:text-[color:#a8cdbf]",
    "tw:[&_.portal-league-registration-fee_small]:text-[.66rem]", "tw:[&_.public-portal-pair]:gap-y-[9px]", "tw:[&_.public-portal-pair]:gap-x-[9px]", "tw:[&_.public-portal-pair]:pt-[12px]",
    "tw:[&_.public-portal-pair]:pr-[12px]", "tw:[&_.public-portal-pair]:pb-[12px]", "tw:[&_.public-portal-pair]:pl-[12px]", "tw:[&_.public-portal-pair]:border-t-[color:rgb(122_165_188_/_.24)]",
    "tw:[&_.public-portal-pair]:border-r-[color:rgb(122_165_188_/_.24)]", "tw:[&_.public-portal-pair]:border-b-[color:rgb(122_165_188_/_.24)]", "tw:[&_.public-portal-pair]:border-l-[color:rgb(122_165_188_/_.24)]", "tw:[&_.public-portal-pair]:rounded-[12px]",
    "tw:[&_.public-portal-pair]:bg-[color:#102333]", "tw:[&_.public-portal-pair]:[background-image:none]", "tw:[&_.public-portal-pair]:[box-shadow:0_4px_14px_rgb(18_62_103_/_.035)]", "tw:[&_.public-portal-pair]:text-[color:#eaf5fa]",
    "tw:[&_.public-portal-pair_>_header_strong]:text-[color:#eef9fc]", "tw:[&_.public-portal-pair_>_header_strong]:text-[.88rem]", "tw:[&_.public-portal-pair_>_header_strong]:leading-[1.3]", "tw:[&_.public-medical-request]:mt-[1px]",
    "tw:[&_.public-medical-request]:pt-[0]", "tw:[&_.public-medical-request]:pr-[0]", "tw:[&_.public-medical-request]:pb-[0]", "tw:[&_.public-medical-request]:pl-[0]",
    "tw:[&_.public-medical-request]:[overflow-x:hidden]", "tw:[&_.public-medical-request]:[overflow-y:hidden]", "tw:[&_.public-medical-request]:border-t-[length:1px]", "tw:[&_.public-medical-request]:[border-top-style:solid]",
    "tw:[&_.public-medical-request]:border-t-[color:rgb(121_168_195_/_.28)]", "tw:[&_.public-medical-request]:border-r-[length:1px]", "tw:[&_.public-medical-request]:[border-right-style:solid]", "tw:[&_.public-medical-request]:border-r-[color:rgb(121_168_195_/_.28)]",
    "tw:[&_.public-medical-request]:border-b-[length:1px]", "tw:[&_.public-medical-request]:[border-bottom-style:solid]", "tw:[&_.public-medical-request]:border-b-[color:rgb(121_168_195_/_.28)]", "tw:[&_.public-medical-request]:border-l-[length:1px]",
    "tw:[&_.public-medical-request]:[border-left-style:solid]", "tw:[&_.public-medical-request]:border-l-[color:rgb(121_168_195_/_.28)]", "tw:[&_.public-medical-request]:rounded-[9px]", "tw:[&_.public-medical-request]:text-[color:#274a69]",
    "tw:[&_.public-medical-request]:bg-[color:#102333]", "tw:[&_.public-medical-request]:[background-image:none]", "tw:[&_.public-medical-request_summary]:flex", "tw:[&_.public-medical-request_summary]:items-center",
    "tw:[&_.public-medical-request_summary]:min-h-[38px]", "tw:[&_.public-medical-request_summary]:pt-[10px]", "tw:[&_.public-medical-request_summary]:pr-[12px]", "tw:[&_.public-medical-request_summary]:pb-[10px]",
    "tw:[&_.public-medical-request_summary]:pl-[12px]", "tw:[&_.public-medical-request_summary]:[list-style:none]", "tw:[&_.public-medical-request_summary]:text-[color:#d9e9f2]", "tw:[&_.public-medical-request_summary]:bg-[color:transparent]",
    "tw:[&_.public-medical-request_summary]:[background-image:none]", "tw:[&_.public-medical-request_summary]:text-[.73rem]", "tw:[&_.public-medical-request_summary]:font-[800]", "tw:[&_.public-medical-request_summary]:tracking-[.01em]",
    "tw:[&_.public-medical-request_summary]:leading-[1.35]", "tw:[&_.public-medical-request_summary]:cursor-pointer", "tw:[&_.public-medical-request_summary::-webkit-details-marker]:hidden", "tw:[&_.public-medical-request_summary::before]:grid",
    "tw:[&_.public-medical-request_summary::before]:w-[18px]", "tw:[&_.public-medical-request_summary::before]:h-[18px]", "tw:[&_.public-medical-request_summary::before]:mr-[7px]", "tw:[&_.public-medical-request_summary::before]:place-items-center",
    "tw:[&_.public-medical-request_summary::before]:border-t-[length:1px]", "tw:[&_.public-medical-request_summary::before]:[border-top-style:solid]", "tw:[&_.public-medical-request_summary::before]:border-t-[color:#bad2e4]", "tw:[&_.public-medical-request_summary::before]:border-r-[length:1px]",
    "tw:[&_.public-medical-request_summary::before]:[border-right-style:solid]", "tw:[&_.public-medical-request_summary::before]:border-r-[color:#bad2e4]", "tw:[&_.public-medical-request_summary::before]:border-b-[length:1px]", "tw:[&_.public-medical-request_summary::before]:[border-bottom-style:solid]",
    "tw:[&_.public-medical-request_summary::before]:border-b-[color:#bad2e4]", "tw:[&_.public-medical-request_summary::before]:border-l-[length:1px]", "tw:[&_.public-medical-request_summary::before]:[border-left-style:solid]", "tw:[&_.public-medical-request_summary::before]:border-l-[color:#bad2e4]",
    "tw:[&_.public-medical-request_summary::before]:rounded-[50%]", "tw:[&_.public-medical-request_summary::before]:text-[color:#2b618a]", "tw:[&_.public-medical-request_summary::before]:[content:'+']", "tw:[&_.public-medical-request_summary::before]:text-[.9rem]",
    "tw:[&_.public-medical-request_summary::before]:font-[600]", "tw:[&_.public-medical-request_summary::before]:leading-[1]", "tw:[&_.public-medical-request[open]_summary]:border-b-[length:1px]", "tw:[&_.public-medical-request[open]_summary]:[border-bottom-style:solid]",
    "tw:[&_.public-medical-request[open]_summary]:border-b-[color:#d7e5ef]", "tw:[&_.public-medical-request[open]_summary]:text-[color:#176a59]", "tw:[&_.public-medical-request[open]_summary]:bg-[color:#eff9f5]", "tw:[&_.public-medical-request[open]_summary]:[background-image:none]",
    "tw:[&_.public-medical-request[open]_summary::before]:border-t-[color:#8bcdbb]", "tw:[&_.public-medical-request[open]_summary::before]:border-r-[color:#8bcdbb]", "tw:[&_.public-medical-request[open]_summary::before]:border-b-[color:#8bcdbb]", "tw:[&_.public-medical-request[open]_summary::before]:border-l-[color:#8bcdbb]",
    "tw:[&_.public-medical-request[open]_summary::before]:text-[color:#177460]", "tw:[&_.public-medical-request[open]_summary::before]:[content:'−']", "tw:[&_.public-medical-request_form]:gap-y-[9px]", "tw:[&_.public-medical-request_form]:gap-x-[9px]",
    "tw:[&_.public-medical-request_form]:mt-[0]", "tw:[&_.public-medical-request_form]:pt-[11px]", "tw:[&_.public-medical-request_form]:pr-[12px]", "tw:[&_.public-medical-request_form]:pb-[11px]",
    "tw:[&_.public-medical-request_form]:pl-[12px]", "tw:[&_.public-medical-request_form]:border-t-[color:rgb(121_168_195_/_.22)]", "tw:[&_.public-medical-request_form]:border-r-[color:rgb(121_168_195_/_.22)]", "tw:[&_.public-medical-request_form]:border-b-[color:rgb(121_168_195_/_.22)]",
    "tw:[&_.public-medical-request_form]:border-l-[color:rgb(121_168_195_/_.22)]", "tw:[&_.public-medical-request_form]:bg-[color:#0c1d2b]", "tw:[&_.public-medical-request_form]:[background-image:none]", "tw:[&_.public-medical-request_form]:grid",
    "tw:[&_.public-medical-request_form]:border-t-[length:1px]", "tw:[&_.public-medical-request_form]:[border-top-style:solid]", "tw:[&_.public-medical-request_label]:gap-y-[5px]", "tw:[&_.public-medical-request_label]:gap-x-[5px]",
    "tw:[&_.public-medical-request_label]:text-[color:#b7cad8]", "tw:[&_.public-medical-request_label]:text-[.7rem]", "tw:[&_.public-medical-request_label]:font-[750]", "tw:[&_.public-medical-request_label]:tracking-[.035em]",
    "tw:[&_.public-medical-request_label]:uppercase", "tw:[&_.public-medical-request_label]:grid", "tw:[&_.public-medical-request_textarea]:min-h-[68px]", "tw:[&_.public-medical-request_textarea]:leading-[1.4]",
    "tw:[&_.public-medical-request_textarea]:border-t-[color:rgb(114_164_194_/_.43)]", "tw:[&_.public-medical-request_textarea]:border-r-[color:rgb(114_164_194_/_.43)]", "tw:[&_.public-medical-request_textarea]:border-b-[color:rgb(114_164_194_/_.43)]", "tw:[&_.public-medical-request_textarea]:border-l-[color:rgb(114_164_194_/_.43)]",
    "tw:[&_.public-medical-request_textarea]:text-[color:#edf8fc]", "tw:[&_.public-medical-request_textarea]:bg-[color:#102b3c]", "tw:[&_.public-medical-request_textarea]:[background-image:none]", "tw:[&_.public-medical-request_>_.muted]:mt-[0]",
    "tw:[&_.public-medical-request_>_.muted]:mr-[0]", "tw:[&_.public-medical-request_>_.muted]:mb-[0]", "tw:[&_.public-medical-request_>_.muted]:ml-[0]", "tw:[&_.public-medical-request_>_.muted]:pt-[11px]",
    "tw:[&_.public-medical-request_>_.muted]:pr-[12px]", "tw:[&_.public-medical-request_>_.muted]:pb-[11px]", "tw:[&_.public-medical-request_>_.muted]:pl-[12px]", "tw:[&_.public-medical-request_>_.muted]:text-[color:#61798c]",
    "tw:[&_.public-medical-request_>_.muted]:text-[.76rem]", "tw:[&_.public-medical-request_>_.muted]:leading-[1.4]", "tw:viewport-700:[&_.portal-league-category-picker_label]:[flex-basis:100%]", "tw:viewport-700:[&_.portal-league-category-picker_.button]:w-[auto]",
    "tw:viewport-700:[&_.portal-league-category-summary]:flex-col", "tw:viewport-700:[&_.public-medical-request_form]:grid-cols-[1fr]", "tw:[&_strong]:text-[color:#edf7fb]", "tw:[&_.portal-league-results_h3]:text-[color:#edf7fb]",
    "tw:[&_.portal-league-pairs_h3]:text-[color:#edf7fb]", "tw:[&_.portal-league-results_>_header_>_small]:text-[color:#9bb5c5]", "tw:[&_.portal-league-week_>_header_span]:text-[color:#9bb5c5]", "tw:[&_.portal-league-week_>_header_small]:text-[color:#9bb5c5]",
    "tw:[&_.portal-league-results_small]:text-[color:#9bb5c5]", "tw:[&_.portal-league-pairs_span]:text-[color:#9bb5c5]", "tw:[&_.portal-league-pairs_small]:text-[color:#9bb5c5]", "tw:[&_.portal-league-match-schedule]:text-[color:#9bb5c5]",
    "tw:[&_.portal-league-results_>_header]:border-t-[color:rgb(123_169_192_/_.22)]", "tw:[&_.portal-league-results_>_header]:border-r-[color:rgb(123_169_192_/_.22)]", "tw:[&_.portal-league-results_>_header]:border-b-[color:rgb(123_169_192_/_.22)]", "tw:[&_.portal-league-results_>_header]:border-l-[color:rgb(123_169_192_/_.22)]",
    "tw:[&_.portal-league-week]:border-t-[color:rgb(122_165_188_/_.28)]", "tw:[&_.portal-league-week]:border-r-[color:rgb(122_165_188_/_.28)]", "tw:[&_.portal-league-week]:border-b-[color:rgb(122_165_188_/_.28)]", "tw:[&_.portal-league-week]:border-l-[color:rgb(122_165_188_/_.28)]",
    "tw:[&_.portal-league-week]:bg-[color:#102333]", "tw:[&_.portal-league-week]:[background-image:none]", "tw:[&_.portal-league-week_>_header]:border-t-[color:rgb(122_165_188_/_.2)]", "tw:[&_.portal-league-week_>_header]:border-r-[color:rgb(122_165_188_/_.2)]",
    "tw:[&_.portal-league-week_>_header]:border-b-[color:rgb(122_165_188_/_.2)]", "tw:[&_.portal-league-week_>_header]:border-l-[color:rgb(122_165_188_/_.2)]", "tw:[&_.portal-league-week_>_header]:bg-[color:transparent]", "tw:[&_.portal-league-week_>_header]:[background-image:linear-gradient(90deg,_#123530,_#122737)]",
    "tw:[&_.portal-league-week_>_header_strong]:text-[color:#eef9fc]", "tw:[&_.portal-league-results_article_>_strong]:text-[color:#eef9fc]", "tw:[&_.portal-league-pairs_strong]:text-[color:#eef9fc]", "tw:[&_.portal-league-match-sides_>_span]:text-[color:#eef9fc]",
    "tw:[&_.portal-league-results_article]:border-t-[color:rgb(122_165_188_/_.16)]", "tw:[&_.portal-league-results_article]:border-r-[color:rgb(122_165_188_/_.16)]", "tw:[&_.portal-league-results_article]:border-b-[color:rgb(122_165_188_/_.16)]", "tw:[&_.portal-league-results_article]:border-l-[color:rgb(122_165_188_/_.16)]",
    "tw:[&_.portal-league-results_article]:bg-[color:#102333]", "tw:[&_.portal-league-results_article]:[background-image:none]", "tw:[&_.portal-league-pairs_article]:border-t-[color:rgb(122_165_188_/_.16)]", "tw:[&_.portal-league-pairs_article]:border-r-[color:rgb(122_165_188_/_.16)]",
    "tw:[&_.portal-league-pairs_article]:border-b-[color:rgb(122_165_188_/_.16)]", "tw:[&_.portal-league-pairs_article]:border-l-[color:rgb(122_165_188_/_.16)]", "tw:[&_.portal-league-pairs_article]:bg-[color:#102333]", "tw:[&_.portal-league-pairs_article]:[background-image:none]",
    "tw:[&_.portal-league-match-sides_small]:bg-[color:#193b36]", "tw:[&_.portal-league-match-sides_small]:[background-image:none]", "tw:[&_.portal-league-match-sides_small]:text-[color:#6ce4bb]", "tw:[&_.portal-league-match-sides_i]:bg-[color:#193b36]",
    "tw:[&_.portal-league-match-sides_i]:[background-image:none]", "tw:[&_.portal-league-match-sides_i]:text-[color:#6ce4bb]", "tw:[&_.portal-league-match-sides_>_span:last-child_i]:bg-[color:#1c3344]", "tw:[&_.portal-league-match-sides_>_span:last-child_i]:[background-image:none]",
    "tw:[&_.portal-league-match-sides_>_span:last-child_i]:text-[color:#a6c8df]", "tw:[&_.portal-league-match-status]:bg-[color:#203243]", "tw:[&_.portal-league-match-status]:[background-image:none]", "tw:[&_.portal-league-match-status]:text-[color:#bed1df]",
    "tw:[&_.portal-league-match-status.is-finished]:bg-[color:#183451]", "tw:[&_.portal-league-match-status.is-finished]:[background-image:none]", "tw:[&_.portal-league-match-status.is-finished]:text-[color:#80b9ff]", "tw:[&_.portal-league-match-status.is-scheduled]:bg-[color:#174537]",
    "tw:[&_.portal-league-match-status.is-scheduled]:[background-image:none]", "tw:[&_.portal-league-match-status.is-scheduled]:text-[color:#69e0b2]", "tw:[&_.portal-league-pairs_article_>_small]:bg-[color:#183b36]", "tw:[&_.portal-league-pairs_article_>_small]:[background-image:none]",
    "tw:[&_.portal-league-pairs_article_>_small]:text-[color:#6de4ba]", "tw:[&_.public-challenge-list_>_article]:border-t-[color:rgb(122_165_188_/_.24)]", "tw:[&_.public-challenge-list_>_article]:border-r-[color:rgb(122_165_188_/_.24)]", "tw:[&_.public-challenge-list_>_article]:border-b-[color:rgb(122_165_188_/_.24)]",
    "tw:[&_.public-challenge-list_>_article]:border-l-[color:rgb(122_165_188_/_.24)]", "tw:[&_.public-challenge-list_>_article]:text-[color:#eaf5fa]", "tw:[&_.public-challenge-list_>_article]:bg-[color:#102333]", "tw:[&_.public-challenge-list_>_article]:[background-image:none]",
    "tw:[&_.public-challenge-list_>_article]:items-start", "tw:[&_.public-challenge-list_>_article]:pt-[12px]", "tw:[&_.public-challenge-list_>_article]:pr-[12px]", "tw:[&_.public-challenge-list_>_article]:pb-[12px]",
    "tw:[&_.public-challenge-list_>_article]:pl-[12px]", "tw:[&_.public-portal-notifications_a]:border-t-[color:rgb(122_165_188_/_.24)]", "tw:[&_.public-portal-notifications_a]:border-r-[color:rgb(122_165_188_/_.24)]", "tw:[&_.public-portal-notifications_a]:border-b-[color:rgb(122_165_188_/_.24)]",
    "tw:[&_.public-portal-notifications_a]:border-l-[color:rgb(122_165_188_/_.24)]", "tw:[&_.public-portal-notifications_a]:text-[color:#eaf5fa]", "tw:[&_.public-portal-notifications_a]:bg-[color:#102333]", "tw:[&_.public-portal-notifications_a]:[background-image:none]",
    "tw:[&_.public-challenge-title-row_>_strong]:text-[color:#eef9fc]", "tw:[&_.public-portal-notification-copy_strong]:text-[color:#eef9fc]", "tw:[&_.public-portal-notification-copy_small]:text-[color:#a5bdcc]", "tw:[&_.public-challenge-details_span]:text-[color:#a5bdcc]",
    "tw:[&_.public-challenge-details_small]:text-[color:#a5bdcc]", "tw:[&_.public-portal-pair_>_header]:min-h-[24px]", "tw:[&_.public-league-schedule-trigger]:[justify-self:start]", "tw:[&_.public-league-schedule-trigger]:min-h-[34px]",
    "tw:[&_.public-league-schedule-trigger]:pt-[7px]", "tw:[&_.public-league-schedule-trigger]:pr-[11px]", "tw:[&_.public-league-schedule-trigger]:pb-[7px]", "tw:[&_.public-league-schedule-trigger]:pl-[11px]",
    "tw:[&_.public-league-schedule-trigger]:border-t-[color:rgb(58_159_232_/_.55)]", "tw:[&_.public-league-schedule-trigger]:border-r-[color:rgb(58_159_232_/_.55)]", "tw:[&_.public-league-schedule-trigger]:border-b-[color:rgb(58_159_232_/_.55)]", "tw:[&_.public-league-schedule-trigger]:border-l-[color:rgb(58_159_232_/_.55)]",
    "tw:[&_.public-league-schedule-trigger]:rounded-[8px]", "tw:[&_.public-league-schedule-trigger]:bg-[color:#1763ae]", "tw:[&_.public-league-schedule-trigger]:[background-image:none]", "tw:[&_.public-league-schedule-trigger]:text-[.74rem]",
    "tw:[&_.public-league-result-entry]:[overflow-x:hidden]", "tw:[&_.public-league-result-entry]:[overflow-y:hidden]", "tw:[&_.public-league-result-entry]:border-t-[length:1px]", "tw:[&_.public-league-result-entry]:[border-top-style:solid]",
    "tw:[&_.public-league-result-entry]:border-t-[color:rgb(121_168_195_/_.28)]", "tw:[&_.public-league-result-entry]:border-r-[length:1px]", "tw:[&_.public-league-result-entry]:[border-right-style:solid]", "tw:[&_.public-league-result-entry]:border-r-[color:rgb(121_168_195_/_.28)]",
    "tw:[&_.public-league-result-entry]:border-b-[length:1px]", "tw:[&_.public-league-result-entry]:[border-bottom-style:solid]", "tw:[&_.public-league-result-entry]:border-b-[color:rgb(121_168_195_/_.28)]", "tw:[&_.public-league-result-entry]:border-l-[length:1px]",
    "tw:[&_.public-league-result-entry]:[border-left-style:solid]", "tw:[&_.public-league-result-entry]:border-l-[color:rgb(121_168_195_/_.28)]", "tw:[&_.public-league-result-entry]:rounded-[9px]", "tw:[&_.public-league-result-entry]:bg-[color:#102333]",
    "tw:[&_.public-league-result-entry]:[background-image:none]", "tw:[&_.public-league-result-entry_summary]:min-h-[38px]", "tw:[&_.public-league-result-entry_summary]:pt-[10px]", "tw:[&_.public-league-result-entry_summary]:pr-[12px]",
    "tw:[&_.public-league-result-entry_summary]:pb-[10px]", "tw:[&_.public-league-result-entry_summary]:pl-[12px]", "tw:[&_.public-league-result-entry_summary]:text-[color:#d9e9f2]", "tw:[&_.public-league-result-entry_summary]:bg-[color:transparent]",
    "tw:[&_.public-league-result-entry_summary]:[background-image:none]", "tw:[&_.public-league-result-entry_summary]:text-[.73rem]", "tw:[&_.public-league-result-entry_summary]:font-[800]", "tw:[&_.public-league-result-entry_summary]:leading-[1.35]",
    "tw:[&_.public-league-result-entry_summary]:cursor-pointer", "tw:[&_.public-league-result-entry_summary:hover]:bg-[color:#152d3e]", "tw:[&_.public-league-result-entry_summary:hover]:[background-image:none]", "tw:[&_.public-medical-request_summary:hover]:bg-[color:#152d3e]",
    "tw:[&_.public-medical-request_summary:hover]:[background-image:none]", "tw:[&_.public-league-result-entry[open]]:border-t-[color:rgb(72_215_173_/_.52)]", "tw:[&_.public-league-result-entry[open]]:border-r-[color:rgb(72_215_173_/_.52)]", "tw:[&_.public-league-result-entry[open]]:border-b-[color:rgb(72_215_173_/_.52)]",
    "tw:[&_.public-league-result-entry[open]]:border-l-[color:rgb(72_215_173_/_.52)]", "tw:[&_.public-medical-request[open]]:border-t-[color:rgb(72_215_173_/_.52)]", "tw:[&_.public-medical-request[open]]:border-r-[color:rgb(72_215_173_/_.52)]", "tw:[&_.public-medical-request[open]]:border-b-[color:rgb(72_215_173_/_.52)]",
    "tw:[&_.public-medical-request[open]]:border-l-[color:rgb(72_215_173_/_.52)]", "tw:[&_.public-league-result-form]:border-t-[color:rgb(121_168_195_/_.22)]", "tw:[&_.public-league-result-form]:border-r-[color:rgb(121_168_195_/_.22)]", "tw:[&_.public-league-result-form]:border-b-[color:rgb(121_168_195_/_.22)]",
    "tw:[&_.public-league-result-form]:border-l-[color:rgb(121_168_195_/_.22)]", "tw:[&_.public-league-result-form]:bg-[color:#0c1d2b]", "tw:[&_.public-league-result-form]:[background-image:none]", "tw:[&_.public-medical-request_>_p]:mt-[0]",
    "tw:[&_.public-medical-request_>_p]:mr-[0]", "tw:[&_.public-medical-request_>_p]:mb-[0]", "tw:[&_.public-medical-request_>_p]:ml-[0]", "tw:[&_.public-medical-request_>_p]:pt-[0]",
    "tw:[&_.public-medical-request_>_p]:pr-[12px]", "tw:[&_.public-medical-request_>_p]:pb-[11px]", "tw:[&_.public-medical-request_>_p]:pl-[12px]", "tw:[&_.public-medical-request_>_p]:text-[color:#a9c0ce]",
    "tw:[&_.public-medical-request_>_p]:text-[.74rem]", "tw:[&_.public-medical-request_select]:border-t-[color:rgb(114_164_194_/_.43)]", "tw:[&_.public-medical-request_select]:border-r-[color:rgb(114_164_194_/_.43)]", "tw:[&_.public-medical-request_select]:border-b-[color:rgb(114_164_194_/_.43)]",
    "tw:[&_.public-medical-request_select]:border-l-[color:rgb(114_164_194_/_.43)]", "tw:[&_.public-medical-request_select]:text-[color:#edf8fc]", "tw:[&_.public-medical-request_select]:bg-[color:#102b3c]", "tw:[&_.public-medical-request_select]:[background-image:none]",
    "tw:[&_.public-league-result-form_input]:border-t-[color:rgb(114_164_194_/_.43)]", "tw:[&_.public-league-result-form_input]:border-r-[color:rgb(114_164_194_/_.43)]", "tw:[&_.public-league-result-form_input]:border-b-[color:rgb(114_164_194_/_.43)]", "tw:[&_.public-league-result-form_input]:border-l-[color:rgb(114_164_194_/_.43)]",
    "tw:[&_.public-league-result-form_input]:text-[color:#edf8fc]", "tw:[&_.public-league-result-form_input]:bg-[color:#102b3c]", "tw:[&_.public-league-result-form_input]:[background-image:none]", "tw:[&_.public-medical-request_.button]:min-h-[33px]",
    "tw:[&_.public-medical-request_.button]:pt-[7px]", "tw:[&_.public-medical-request_.button]:pr-[11px]", "tw:[&_.public-medical-request_.button]:pb-[7px]", "tw:[&_.public-medical-request_.button]:pl-[11px]",
    "tw:[&_.public-medical-request_.button]:rounded-[8px]", "tw:[&_.public-medical-request_.button]:text-[.72rem]", "tw:[&_.public-league-result-form_.button]:min-h-[33px]", "tw:[&_.public-league-result-form_.button]:pt-[7px]",
    "tw:[&_.public-league-result-form_.button]:pr-[11px]", "tw:[&_.public-league-result-form_.button]:pb-[7px]", "tw:[&_.public-league-result-form_.button]:pl-[11px]", "tw:[&_.public-league-result-form_.button]:rounded-[8px]",
    "tw:[&_.public-league-result-form_.button]:text-[.72rem]", "tw:[&_.public-challenge-list]:gap-y-[9px]", "tw:[&_.public-challenge-list]:gap-x-[9px]", "tw:[&_.public-challenge-list]:mt-[3px]",
    "tw:[&_.public-challenge-list_>_h3]:pt-[3px]", "tw:[&_.public-challenge-list_>_h3]:pr-[1px]", "tw:[&_.public-challenge-list_>_h3]:pb-[3px]", "tw:[&_.public-challenge-list_>_h3]:pl-[1px]",
    "tw:[&_.public-challenge-list_>_h3]:text-[.92rem]", "tw:[&_.public-challenge-actions]:gap-y-[7px]", "tw:[&_.public-challenge-actions]:gap-x-[7px]", "tw:[&_.public-challenge-actions_.button]:min-h-[33px]",
    "tw:[&_.public-challenge-actions_.button]:pt-[7px]", "tw:[&_.public-challenge-actions_.button]:pr-[11px]", "tw:[&_.public-challenge-actions_.button]:pb-[7px]", "tw:[&_.public-challenge-actions_.button]:pl-[11px]",
    "tw:[&_.public-challenge-actions_.button]:rounded-[8px]", "tw:[&_.public-challenge-actions_.button]:text-[.72rem]", "tw:viewport-700:[&_.public-challenge-list_>_article]:gap-y-[10px]", "tw:viewport-700:[&_.public-challenge-list_>_article]:gap-x-[10px]",
    "tw:viewport-700:[&_.public-challenge-actions]:w-[100%]", "tw:viewport-700:[&_.public-challenge-actions_form]:[flex:1]", "tw:viewport-700:[&_.public-challenge-actions_.button]:w-[100%]", "tw:viewport-700:[&_.public-challenge-actions_.button]:justify-center",
    "tw:grid", "tw:gap-y-[18px]", "tw:gap-x-[18px]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]",
    "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]", "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:[&_>_.section-card:last-child]:border-b-[length:1px]",
    "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]",
  ].join(" "),
  "public_league_portal_header": [
    "public-league-portal-header", "tw:flex", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:justify-between", "tw:items-center", "tw:viewport-700:items-start", "tw:viewport-700:flex-col",
  ].join(" "),
  "public_league_portal_header_public_league_portal_hero_card": [
    "public-league-portal-header", "public-league-portal-hero-card", "tw:flex", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:justify-between", "tw:items-center", "tw:viewport-700:items-start",
    "tw:viewport-700:flex-col", "tw:relative", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]",
    "tw:min-h-[148px]", "tw:viewport-700:min-h-[137px]", "tw:pt-[25px]", "tw:viewport-700:pt-[20px]",
    "tw:pr-[26px]", "tw:viewport-700:pr-[17px]", "tw:pb-[25px]", "tw:viewport-700:pb-[20px]",
    "tw:pl-[26px]", "tw:viewport-700:pl-[17px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(57_211_187_/_.47)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(57_211_187_/_.47)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(57_211_187_/_.47)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(57_211_187_/_.47)]", "tw:rounded-[15px]", "tw:text-[color:#fff]",
    "tw:bg-[color:transparent]", "tw:[background-image:radial-gradient(circle_at_90%_12%,_rgb(76_255_160_/_.42),_transparent_23%),_radial-gradient(circle_at_80%_72%,_rgb(0_158_224_/_.22),_transparent_29%),_linear-gradient(110deg,_#071b36_4%,_#0b3153_65%,_#0a4e47)]", "tw:[box-shadow:inset_0_1px_rgb(220_255_243_/_.2),_0_15px_26px_rgb(0_0_0_/_.18)]", "tw:[&::after]:absolute",
    "tw:[&::after]:top-[-40px]", "tw:[&::after]:right-[96px]", "tw:viewport-700:[&::after]:right-[30px]", "tw:[&::after]:w-[190px]",
    "tw:viewport-700:[&::after]:w-[148px]", "tw:[&::after]:h-[190px]", "tw:viewport-700:[&::after]:h-[148px]", "tw:[&::after]:border-t-[length:2px]",
    "tw:[&::after]:[border-top-style:dotted]", "tw:[&::after]:border-t-[color:rgb(141_255_209_/_.2)]", "tw:[&::after]:border-r-[length:2px]", "tw:[&::after]:[border-right-style:dotted]",
    "tw:[&::after]:border-r-[color:rgb(141_255_209_/_.2)]", "tw:[&::after]:border-b-[length:2px]", "tw:[&::after]:[border-bottom-style:dotted]", "tw:[&::after]:border-b-[color:rgb(141_255_209_/_.2)]",
    "tw:[&::after]:border-l-[length:2px]", "tw:[&::after]:[border-left-style:dotted]", "tw:[&::after]:border-l-[color:rgb(141_255_209_/_.2)]", "tw:[&::after]:rounded-[50%]",
    "tw:[&::after]:[content:'']", "tw:[&::after]:[transform:rotate(-25deg)]", "tw:[&_>_span]:relative", "tw:[&_>_span]:z-[1]",
    "tw:[&_>_span]:text-[color:#70f6c2]", "tw:[&_>_span]:text-[.62rem]", "tw:[&_>_span]:font-[900]", "tw:[&_>_span]:tracking-[.34em]",
    "tw:[&_h2]:relative", "tw:[&_h2]:z-[1]", "tw:[&_h2]:mt-[7px]", "tw:[&_h2]:mr-[0]",
    "tw:[&_h2]:mb-[9px]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#fff]", "tw:[&_h2]:text-[clamp(1.55rem,_3vw,_2.3rem)]",
    "tw:viewport-700:[&_h2]:text-[1.56rem]", "tw:[&_h2]:tracking-[-.035em]", "tw:[&_p]:relative", "tw:[&_p]:z-[1]",
    "tw:[&_p]:max-w-[455px]", "tw:viewport-700:[&_p]:max-w-[250px]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#bdcee0]", "tw:[&_p]:text-[.83rem]",
    "tw:viewport-700:[&_p]:text-[.72rem]", "tw:[&_p]:leading-[1.45]", "tw:[&_>_b]:absolute", "tw:[&_>_b]:z-[1]",
    "tw:[&_>_b]:right-[24px]", "tw:viewport-700:[&_>_b]:right-[14px]", "tw:[&_>_b]:bottom-[19px]", "tw:viewport-700:[&_>_b]:bottom-[14px]",
    "tw:[&_>_b]:text-[color:#b6ffc9]", "tw:[&_>_b]:text-[.62rem]", "tw:viewport-700:[&_>_b]:text-[.5rem]", "tw:[&_>_b]:font-[900]",
    "tw:[&_>_b]:tracking-[.12em]", "tw:[&_>_b]:leading-[1.18]", "tw:[&_>_b]:text-right",
  ].join(" "),
  "portal_league_category_context": [
    "portal-league-category-context", "tw:mt-[-4px]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-[color:#5b7587]", "tw:text-[.78rem]",
  ].join(" "),
  "portal_league_category_picker": [
    "portal-league-category-picker", "tw:flex", "tw:[align-items:end]", "tw:viewport-700:items-stretch",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:pt-[8px]", "tw:pr-[9px]",
    "tw:pb-[8px]", "tw:pl-[9px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#d8e8ee]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d8e8ee]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d8e8ee]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#d8e8ee]", "tw:rounded-[10px]", "tw:bg-[color:#f7fbfc]",
    "tw:[background-image:none]", "tw:w-[fit-content]", "tw:viewport-700:w-[100%]", "tw:max-w-[100%]",
    "tw:mt-[18px]", "tw:[&_label]:grid", "tw:[&_label]:[flex:0_1_330px]", "tw:[&_label]:gap-y-[4px]",
    "tw:[&_label]:gap-x-[4px]", "tw:[&_label]:text-[color:#557184]", "tw:[&_label]:text-[.7rem]", "tw:[&_label]:font-[800]",
    "tw:[&_label]:min-w-[min(260px,_100%)]", "tw:[&_select]:min-h-[36px]", "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[9px]",
    "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[9px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]",
    "tw:[&_select]:border-t-[color:#c9dce7]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#c9dce7]",
    "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:#c9dce7]", "tw:[&_select]:border-l-[length:1px]",
    "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#c9dce7]", "tw:[&_select]:rounded-[7px]", "tw:[&_select]:bg-[color:#fff]",
    "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:#153f5d]", "tw:[&_select]:[font:inherit]", "tw:[&_select]:w-[100%]",
    "tw:[&_select]:min-w-[0]", "tw:[&_.button]:min-h-[36px]", "tw:[&_.button]:pt-[0]", "tw:[&_.button]:pr-[12px]",
    "tw:[&_.button]:pb-[0]", "tw:[&_.button]:pl-[12px]", "tw:[&_.button]:text-[.76rem]", "tw:viewport-700:flex-col",
  ].join(" "),
  "portal_league_pairs": [
    "portal-league-pairs", "tw:grid", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
    "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]",
    "tw:[&_h3]:text-[color:#174660]", "tw:[&_h3]:text-[.94rem]", "tw:[&_>_div]:grid", "tw:[&_>_div]:gap-y-[10px]",
    "tw:[&_>_div]:gap-x-[10px]", "tw:[&_article]:grid", "tw:[&_article]:grid-cols-[minmax(0,_1fr)_auto]", "tw:viewport-700:[&_article]:grid-cols-[1fr]",
    "tw:[&_article]:items-center", "tw:[&_article]:gap-y-[10px]", "tw:viewport-700:[&_article]:gap-y-[4px]", "tw:[&_article]:gap-x-[10px]",
    "tw:viewport-700:[&_article]:gap-x-[4px]", "tw:[&_article]:pt-[11px]", "tw:[&_article]:pr-[12px]", "tw:[&_article]:pb-[11px]",
    "tw:[&_article]:pl-[12px]", "tw:[&_article]:border-t-[length:0]", "tw:[&_article]:[border-top-style:none]", "tw:[&_article]:border-t-[color:currentColor]",
    "tw:[&_article]:border-r-[length:0]", "tw:[&_article]:[border-right-style:none]", "tw:[&_article]:border-r-[color:currentColor]", "tw:[&_article]:border-b-[length:1px]",
    "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#edf2f5]", "tw:[&_article]:border-l-[length:0]", "tw:[&_article]:[border-left-style:none]",
    "tw:[&_article]:border-l-[color:currentColor]", "tw:[&_article]:rounded-[0]", "tw:[&_article]:bg-[color:#fff]", "tw:[&_article]:[background-image:none]",
    "tw:[&_span]:text-[color:#688091]", "tw:[&_span]:text-[.73rem]", "tw:[&_small]:text-[color:#688091]", "tw:[&_small]:text-[.73rem]",
    "tw:[&_strong]:text-[color:#164269]", "tw:[&_strong]:text-[.8rem]", "tw:[&_article_>_div]:grid", "tw:[&_article_>_div]:gap-y-[3px]",
    "tw:[&_article_>_div]:gap-x-[3px]", "tw:[&_article_>_small]:pt-[4px]", "tw:[&_article_>_small]:pr-[7px]", "tw:[&_article_>_small]:pb-[4px]",
    "tw:[&_article_>_small]:pl-[7px]", "tw:[&_article_>_small]:rounded-[999px]", "tw:[&_article_>_small]:bg-[color:#eff8f6]", "tw:[&_article_>_small]:[background-image:none]",
    "tw:[&_article_>_small]:text-[color:#237154]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "public_portal_notifications": [
    "public-portal-notifications", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:[&_a]:grid", "tw:[&_a]:grid-cols-[26px_minmax(0,_1fr)_auto]", "tw:[&_a]:gap-y-[9px]", "tw:[&_a]:gap-x-[9px]",
    "tw:[&_a]:items-center", "tw:[&_a]:pt-[10px]", "tw:[&_a]:pr-[11px]", "tw:[&_a]:pb-[10px]",
    "tw:[&_a]:pl-[11px]", "tw:[&_a]:border-t-[length:1px]", "tw:[&_a]:[border-top-style:solid]", "tw:[&_a]:border-t-[color:#c9e0ef]",
    "tw:[&_a]:border-r-[length:1px]", "tw:[&_a]:[border-right-style:solid]", "tw:[&_a]:border-r-[color:#c9e0ef]", "tw:[&_a]:border-b-[length:1px]",
    "tw:[&_a]:[border-bottom-style:solid]", "tw:[&_a]:border-b-[color:#c9e0ef]", "tw:[&_a]:border-l-[length:1px]", "tw:[&_a]:[border-left-style:solid]",
    "tw:[&_a]:border-l-[color:#c9e0ef]", "tw:[&_a]:rounded-[var(--radius-control)]", "tw:[&_a]:bg-[color:#fff]", "tw:[&_a]:[background-image:none]",
    "tw:[&_a]:text-[color:#173e5d]", "tw:[&_a]:[text-decoration:none]", "tw:[&_a:hover]:border-t-[color:#93c2da]", "tw:[&_a:hover]:border-r-[color:#93c2da]",
    "tw:[&_a:hover]:border-b-[color:#93c2da]", "tw:[&_a:hover]:border-l-[color:#93c2da]", "tw:[&_a:hover]:bg-[color:#fbfeff]", "tw:[&_a:hover]:[background-image:none]",
  ].join(" "),
  "public_portal_notification_reservation": [
    "public-portal-notification-reservation", "tw:border-t-[color:#bde4d2]!", "tw:border-r-[color:#bde4d2]!", "tw:border-b-[color:#bde4d2]!",
    "tw:border-l-[color:#bde4d2]!", "tw:bg-[color:transparent]!", "tw:[background-image:linear-gradient(90deg,_#f3fcf7,_#fff)]!", "tw:[&_.public-portal-notification-icon]:bg-[color:#2eaa70]",
    "tw:[&_.public-portal-notification-icon]:[background-image:none]", "tw:[&_.public-portal-notification-icon]:text-[color:#fff]", "tw:[&_.public-portal-notification-icon]:[box-shadow:0_3px_8px_rgb(29_139_86_/_.22)]", "tw:[&_.public-portal-notification-copy_strong]:text-[color:#1d7450]",
    "tw:[&_.public-portal-notification-copy_small]:text-[color:#4f7a69]",
  ].join(" "),
  "public_portal_notification_icon": [
    "public-portal-notification-icon", "tw:grid", "tw:w-[24px]", "tw:h-[24px]",
    "tw:place-items-center", "tw:rounded-[50%]", "tw:bg-[color:#edf4f8]", "tw:[background-image:none]",
    "tw:text-[color:#607b90]", "tw:text-[.9rem]", "tw:font-[900]",
  ].join(" "),
  "public_portal_notification_copy": [
    "public-portal-notification-copy", "tw:grid", "tw:gap-y-[2px]", "tw:gap-x-[2px]",
    "tw:min-w-[0]", "tw:[&_strong]:text-[color:#1a4164]", "tw:[&_strong]:text-[.78rem]", "tw:[&_small]:text-[color:#698197]",
    "tw:[&_small]:text-[.69rem]", "tw:[&_small]:leading-[1.35]",
  ].join(" "),
  "public_portal_notification_view": [
    "public-portal-notification-view", "tw:[justify-self:end]", "tw:pt-[4px]", "tw:pr-[7px]",
    "tw:pb-[4px]", "tw:pl-[7px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#b9dfce]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#b9dfce]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#b9dfce]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#b9dfce]", "tw:rounded-[6px]", "tw:text-[color:#197154]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:text-[.66rem]", "tw:font-[850]",
  ].join(" "),
  "public_league_prizes": [
    "public-league-prizes", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]", "tw:pl-[14px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d7d6ff]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#d7d6ff]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#d7d6ff]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d7d6ff]",
    "tw:rounded-[10px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(135deg,_#f7f5ff,_#fff)]", "tw:[&_h3]:mt-[0]",
    "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]", "tw:[&_p]:mt-[0]",
    "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_article]:grid",
    "tw:[&_article]:gap-y-[3px]", "tw:[&_article]:gap-x-[3px]",
  ].join(" "),
  "public_league_prize_description": [
    "public-league-prize-description", "tw:[white-space:pre-line]",
  ].join(" "),
  "portal_league_results": [
    "portal-league-results", "tw:grid", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
    "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]",
    "tw:[&_h3]:text-[color:#174660]", "tw:[&_h3]:text-[.94rem]", "tw:[&_>_header]:flex", "tw:[&_>_header]:[align-items:end]",
    "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[12px]", "tw:[&_>_header]:gap-x-[12px]", "tw:[&_>_header]:pb-[9px]",
    "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#dce9ef]", "tw:[&_>_header_div]:grid",
    "tw:[&_>_header_div]:gap-y-[3px]", "tw:[&_>_header_div]:gap-x-[3px]", "tw:[&_>_header_span]:text-[color:#0a8c70]", "tw:[&_>_header_span]:text-[.62rem]",
    "tw:[&_>_header_span]:font-[900]", "tw:[&_>_header_span]:tracking-[.1em]", "tw:[&_>_header_>_small]:text-[color:#688091]", "tw:[&_>_header_>_small]:text-[.69rem]",
    "tw:[&_article]:grid", "tw:[&_article]:grid-cols-[minmax(0,_1fr)_auto]", "tw:viewport-700:[&_article]:grid-cols-[1fr]", "tw:[&_article]:items-center",
    "tw:[&_article]:gap-y-[10px]", "tw:viewport-700:[&_article]:gap-y-[4px]", "tw:[&_article]:gap-x-[10px]", "tw:viewport-700:[&_article]:gap-x-[4px]",
    "tw:[&_article]:pt-[11px]", "tw:[&_article]:pr-[12px]", "tw:[&_article]:pb-[11px]", "tw:[&_article]:pl-[12px]",
    "tw:[&_article]:border-t-[length:0]", "tw:[&_article]:[border-top-style:none]", "tw:[&_article]:border-t-[color:currentColor]", "tw:[&_article]:border-r-[length:0]",
    "tw:[&_article]:[border-right-style:none]", "tw:[&_article]:border-r-[color:currentColor]", "tw:[&_article]:border-b-[length:1px]", "tw:[&_article]:[border-bottom-style:solid]",
    "tw:[&_article]:border-b-[color:#edf2f5]", "tw:[&_article]:border-l-[length:0]", "tw:[&_article]:[border-left-style:none]", "tw:[&_article]:border-l-[color:currentColor]",
    "tw:[&_article]:rounded-[0]", "tw:[&_article]:bg-[color:#fff]", "tw:[&_article]:[background-image:none]", "tw:[&_small]:text-[color:#688091]",
    "tw:[&_small]:text-[.73rem]", "tw:[&_article_>_strong]:text-[color:#164269]", "tw:[&_article_>_strong]:text-[.8rem]", "tw:[&_article_b]:inline-block",
    "tw:[&_article_b]:min-w-[42px]", "tw:[&_article_b]:text-[color:#087b63]", "tw:[&_article_b]:text-center", "tw:[&_article[id^=jogo-]]:[scroll-margin-top:88px]",
    "tw:[&_article.is-notification-highlight]:[animation:portal-league-match-highlight_1.3s_ease-in-out_2]",
  ].join(" "),
  "portal_league_week_list": [
    "portal-league-week-list", "tw:grid", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
  ].join(" "),
  "portal_league_week_tabs": [
    "portal-league-week-tabs", "tw:flex", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:[overflow-x:auto]", "tw:pt-[1px]", "tw:pr-[1px]", "tw:pb-[3px]",
    "tw:pl-[1px]", "tw:[scrollbar-width:none]", "tw:[&::-webkit-scrollbar]:hidden", "tw:[&_button]:min-w-[66px]",
    "tw:[&_button]:min-h-[32px]", "tw:[&_button]:pt-[6px]", "tw:[&_button]:pr-[9px]", "tw:[&_button]:pb-[6px]",
    "tw:[&_button]:pl-[9px]", "tw:[&_button]:border-t-[length:1px]", "tw:[&_button]:[border-top-style:solid]", "tw:[&_button]:border-t-[color:rgb(103_153_194_/_.32)]",
    "tw:[&_button]:border-r-[length:1px]", "tw:[&_button]:[border-right-style:solid]", "tw:[&_button]:border-r-[color:rgb(103_153_194_/_.32)]", "tw:[&_button]:border-b-[length:1px]",
    "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:rgb(103_153_194_/_.32)]", "tw:[&_button]:border-l-[length:1px]", "tw:[&_button]:[border-left-style:solid]",
    "tw:[&_button]:border-l-[color:rgb(103_153_194_/_.32)]", "tw:[&_button]:rounded-[8px]", "tw:[&_button]:text-[color:#a9c1d1]", "tw:[&_button]:bg-[color:#0c2037]",
    "tw:[&_button]:[background-image:none]", "tw:[&_button]:[font:inherit]", "tw:[&_button]:text-[.66rem]", "tw:[&_button]:font-[800]",
    "tw:[&_button]:cursor-pointer", "tw:[&_button]:whitespace-nowrap", "tw:[&_button.active]:border-t-[color:rgb(73_231_180_/_.66)]", "tw:[&_button.active]:border-r-[color:rgb(73_231_180_/_.66)]",
    "tw:[&_button.active]:border-b-[color:rgb(73_231_180_/_.66)]", "tw:[&_button.active]:border-l-[color:rgb(73_231_180_/_.66)]", "tw:[&_button.active]:text-[color:#d8fff0]", "tw:[&_button.active]:bg-[color:transparent]",
    "tw:[&_button.active]:[background-image:linear-gradient(135deg,_#0d5a52,_#0b3b4b)]", "tw:[&_button.active]:[box-shadow:inset_0_0_0_1px_rgb(95_246_190_/_.14)]",
  ].join(" "),
  "portal_league_week": [
    "portal-league-week", "tw:grid", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d3e4ec]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#d3e4ec]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#d3e4ec]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d3e4ec]",
    "tw:rounded-[10px]", "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[&_>_header]:flex",
    "tw:[&_>_header]:items-center", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[10px]", "tw:[&_>_header]:gap-x-[10px]",
    "tw:[&_>_header]:pt-[10px]", "tw:[&_>_header]:pr-[12px]", "tw:[&_>_header]:pb-[10px]", "tw:[&_>_header]:pl-[12px]",
    "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#e1edf2]", "tw:[&_>_header]:bg-[color:transparent]",
    "tw:[&_>_header]:[background-image:linear-gradient(90deg,_#edf9f6,_#f5fbff)]", "tw:[&_>_header_div]:grid", "tw:[&_>_header_div]:gap-y-[2px]", "tw:[&_>_header_div]:gap-x-[2px]",
    "tw:[&_>_header_strong]:text-[color:#08765f]", "tw:[&_>_header_strong]:text-[.81rem]", "tw:[&_>_header_span]:text-[color:#55758a]", "tw:[&_>_header_span]:text-[.7rem]",
    "tw:[&_>_header_small]:text-[color:#55758a]", "tw:[&_>_header_small]:text-[.7rem]", "tw:[&_>_div]:grid", "tw:[&_article:last-child]:border-b-[length:0]",
    "tw:[&_article:last-child]:[border-bottom-style:none]", "tw:[&_article:last-child]:border-b-[color:currentColor]",
  ].join(" "),
  "portal_league_match_sides": [
    "portal-league-match-sides", "tw:inline-flex", "tw:items-center", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]", "tw:[&_>_span]:grid", "tw:[&_>_span]:gap-y-[2px]", "tw:[&_>_span]:gap-x-[2px]",
    "tw:[&_>_span]:text-[color:#164269]", "tw:[&_>_span]:text-[.8rem]", "tw:[&_i]:w-[fit-content]", "tw:[&_i]:pt-[2px]",
    "tw:[&_i]:pr-[5px]", "tw:[&_i]:pb-[2px]", "tw:[&_i]:pl-[5px]", "tw:[&_i]:rounded-[999px]",
    "tw:[&_i]:bg-[color:#e6f4ed]", "tw:[&_i]:[background-image:none]", "tw:[&_i]:text-[color:#147348]", "tw:[&_i]:text-[.58rem]",
    "tw:[&_i]:not-italic", "tw:[&_i]:font-[800]", "tw:[&_i]:tracking-[.02em]", "tw:[&_i]:uppercase",
    "tw:[&_>_b]:text-[color:var(--muted)]", "tw:[&_>_b]:text-[.78rem]", "tw:[&_>_span:last-child_i]:bg-[color:#edf3f8]", "tw:[&_>_span:last-child_i]:[background-image:none]",
    "tw:[&_>_span:last-child_i]:text-[color:#587184]",
  ].join(" "),
  "portal_league_match_score": [
    "portal-league-match-score", "tw:grid", "tw:[justify-items:center]", "tw:gap-y-[3px]",
    "tw:gap-x-[3px]", "tw:min-w-[48px]", "tw:leading-[1.1]", "tw:[&_small]:text-[color:#9eb9c8]",
    "tw:[&_small]:text-[.6rem]", "tw:[&_small]:font-[750]", "tw:[&_small]:tracking-[.02em]", "tw:[&_small]:whitespace-nowrap",
  ].join(" "),
  "public_portal_pairs": [
    "public-portal-pairs", "tw:grid", "tw:grid-cols-[repeat(auto-fit,_minmax(320px,_1fr))]", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]",
  ].join(" "),
  "public_portal_pair": [
    "public-portal-pair", "tw:[&_>_header]:flex", "tw:[&_>_header]:gap-y-[12px]", "tw:[&_>_header]:gap-x-[12px]",
    "tw:[&_>_header]:justify-between", "tw:[&_>_header]:items-start", "tw:grid", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]",
    "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#c6dae8]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#c6dae8]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#c6dae8]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#c6dae8]", "tw:rounded-[10px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[&_header_>_div]:grid", "tw:[&_header_>_div]:gap-y-[3px]", "tw:[&_header_>_div]:gap-x-[3px]", "tw:viewport-700:[&_>_header]:flex-col",
  ].join(" "),
  "public_league_result_entry": [
    "public-league-result-entry", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#d7e5ef]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#d7e5ef]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d7e5ef]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d7e5ef]", "tw:rounded-[10px]",
    "tw:bg-[color:#f8fbfd]", "tw:[background-image:none]", "tw:[&_summary]:min-h-[40px]", "tw:[&_summary]:pt-[11px]",
    "tw:[&_summary]:pr-[12px]", "tw:[&_summary]:pb-[11px]", "tw:[&_summary]:pl-[12px]", "tw:[&_summary]:text-[color:#31536f]",
    "tw:[&_summary]:text-[.74rem]", "tw:[&_summary]:font-[800]", "tw:[&_summary]:cursor-pointer",
  ].join(" "),
  "public_league_result_form": [
    "public-league-result-form", "tw:grid-cols-[34px_minmax(0,_1fr)_minmax(0,_1fr)]", "tw:pt-[11px]", "tw:pr-[11px]",
    "tw:pb-[11px]", "tw:pl-[11px]", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:[&_>_span]:text-[.68rem]", "tw:[&_>_strong]:text-[.68rem]", "tw:grid", "tw:items-center",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d7e5ef]", "tw:[&_>_span]:min-w-[0]",
    "tw:[&_>_span]:text-[color:#416078]", "tw:[&_>_span]:text-center", "tw:[&_>_strong]:min-w-[0]", "tw:[&_>_strong]:text-[color:#193d5b]",
    "tw:[&_>_strong]:text-center", "tw:[&_>_strong]:[overflow-x:hidden]", "tw:[&_>_strong]:[overflow-y:hidden]", "tw:[&_>_strong]:text-ellipsis",
    "tw:[&_>_strong]:whitespace-nowrap", "tw:[&_small]:[grid-column:1_/_-1]", "tw:[&_small]:text-[color:#617b8f]", "tw:[&_small]:text-[.66rem]",
    "tw:[&_.button]:[grid-column:1_/_-1]", "tw:[&_.button]:[justify-self:end]",
  ].join(" "),
  "public_league_result_score": [
    "public-league-result-score", "tw:[&_input]:h-[30px]", "tw:contents!", "tw:[&_i]:text-[color:#5f7b90]",
    "tw:[&_i]:text-[.7rem]", "tw:[&_i]:not-italic", "tw:[&_i]:text-center", "tw:[&_input]:min-w-[0]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#c9dce8]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#c9dce8]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:#c9dce8]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#c9dce8]",
    "tw:[&_input]:rounded-[7px]", "tw:[&_input]:text-center",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "public_medical_request": [
    "public-medical-request", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#e3edf4]",
    "tw:pt-[10px]", "tw:text-[color:#274762]", "tw:text-[.78rem]", "tw:[&_summary]:cursor-pointer",
    "tw:[&_summary]:font-[800]", "tw:[&_form]:grid", "tw:[&_form]:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-700:[&_form]:grid-cols-[1fr]",
    "tw:[&_form]:gap-y-[8px]", "tw:[&_form]:gap-x-[8px]", "tw:[&_form]:mt-[10px]", "tw:[&_label]:grid",
    "tw:[&_label]:gap-y-[4px]", "tw:[&_label]:gap-x-[4px]", "tw:[&_label]:font-[700]", "tw:[&_textarea]:min-h-[68px]",
    "tw:[&_label:last-of-type]:[grid-column:1_/_-1]",
  ].join(" "),
  "button": sharedUtilities.button,
  "public_challenge_list": [
    "public-challenge-list", "tw:[&_>_article]:flex", "tw:[&_>_article]:gap-y-[12px]", "tw:[&_>_article]:gap-x-[12px]",
    "tw:[&_>_article]:justify-between", "tw:[&_>_article]:items-center", "tw:viewport-700:[&_>_article]:items-start", "tw:[&_>_article]:pt-[11px]",
    "tw:[&_>_article]:pr-[11px]", "tw:[&_>_article]:pb-[11px]", "tw:[&_>_article]:pl-[11px]", "tw:[&_>_article]:border-t-[length:1px]",
    "tw:[&_>_article]:[border-top-style:solid]", "tw:[&_>_article]:border-t-[color:#d6e4ee]", "tw:[&_>_article]:border-r-[length:1px]", "tw:[&_>_article]:[border-right-style:solid]",
    "tw:[&_>_article]:border-r-[color:#d6e4ee]", "tw:[&_>_article]:border-b-[length:1px]", "tw:[&_>_article]:[border-bottom-style:solid]", "tw:[&_>_article]:border-b-[color:#d6e4ee]",
    "tw:[&_>_article]:border-l-[length:1px]", "tw:[&_>_article]:[border-left-style:solid]", "tw:[&_>_article]:border-l-[color:#d6e4ee]", "tw:[&_>_article]:rounded-[var(--radius-control)]",
    "tw:[&_>_article]:bg-[color:#fff]", "tw:[&_>_article]:[background-image:none]", "tw:grid", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[&_article_>_div:first-child]:grid", "tw:[&_article_>_div:first-child]:gap-y-[3px]", "tw:[&_article_>_div:first-child]:gap-x-[3px]",
    "tw:viewport-700:[&_>_article]:flex-col", "tw:[&_.public-league-reservation-status]:inline-flex", "tw:[&_.public-league-reservation-status]:items-center", "tw:[&_.public-league-reservation-status]:gap-y-[4px]",
    "tw:[&_.public-league-reservation-status]:gap-x-[4px]", "tw:[&_.public-league-reservation-status]:pt-[3px]", "tw:[&_.public-league-reservation-status]:pr-[7px]", "tw:[&_.public-league-reservation-status]:pb-[3px]",
    "tw:[&_.public-league-reservation-status]:pl-[7px]", "tw:[&_.public-league-reservation-status]:border-t-[length:1px]", "tw:[&_.public-league-reservation-status]:[border-top-style:solid]", "tw:[&_.public-league-reservation-status]:border-t-[color:#c8e4d8]",
    "tw:[&_.public-league-reservation-status]:border-r-[length:1px]", "tw:[&_.public-league-reservation-status]:[border-right-style:solid]", "tw:[&_.public-league-reservation-status]:border-r-[color:#c8e4d8]", "tw:[&_.public-league-reservation-status]:border-b-[length:1px]",
    "tw:[&_.public-league-reservation-status]:[border-bottom-style:solid]", "tw:[&_.public-league-reservation-status]:border-b-[color:#c8e4d8]", "tw:[&_.public-league-reservation-status]:border-l-[length:1px]", "tw:[&_.public-league-reservation-status]:[border-left-style:solid]",
    "tw:[&_.public-league-reservation-status]:border-l-[color:#c8e4d8]", "tw:[&_.public-league-reservation-status]:rounded-[999px]", "tw:[&_.public-league-reservation-status]:text-[color:#237154]", "tw:[&_.public-league-reservation-status]:bg-[color:#f3fbf7]",
    "tw:[&_.public-league-reservation-status]:[background-image:none]", "tw:[&_.public-league-reservation-status]:text-[.63rem]", "tw:[&_.public-league-reservation-status]:font-[750]", "tw:[&_.public-league-reservation-status]:leading-[1.2]",
    "tw:[&_.public-league-reservation-status]:whitespace-nowrap", "tw:[&_article]:[scroll-margin-top:145px]",
  ].join(" "),
  "public_challenge_details": [
    "public-challenge-details", "tw:grid", "tw:gap-y-[4px]", "tw:gap-x-[4px]",
    "tw:min-w-[0]",
  ].join(" "),
  "public_challenge_title_row": [
    "public-challenge-title-row", "tw:flex", "tw:items-center", "tw:flex-wrap",
    "tw:gap-y-[7px]", "tw:gap-x-[7px]", "tw:[&_>_strong]:text-[color:#164269]", "tw:[&_>_strong]:text-[.81rem]",
  ].join(" "),
  "public_league_reservation_status": [
    "public-league-reservation-status", "tw:[&_b]:grid", "tw:[&_b]:w-[12px]", "tw:[&_b]:h-[12px]",
    "tw:[&_b]:place-items-center", "tw:[&_b]:rounded-[50%]", "tw:[&_b]:bg-[color:#29a36b]", "tw:[&_b]:[background-image:none]",
    "tw:[&_b]:text-[color:#fff]", "tw:[&_b]:text-[.56rem]", "tw:[&_b]:leading-[1]",
  ].join(" "),
  "public_challenge_actions": [
    "public-challenge-actions", "tw:flex", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:justify-end", "tw:viewport-700:justify-start", "tw:items-center", "tw:[&_form]:mt-[0]",
    "tw:[&_form]:mr-[0]", "tw:[&_form]:mb-[0]", "tw:[&_form]:ml-[0]", "tw:viewport-700:w-[100%]",
  ].join(" "),
  "public_booking_message": sharedUtilities.publicBookingMessage,
} as const;
