"use client";

import { useState, useTransition } from "react";
import { createLeagueChallengeAction, respondLeagueProposalAction } from "@/lib/actions/league-challenges";
import { requestLeagueMedicalSubstitutionAction } from "@/lib/actions/league-medical-substitutions";

type Portal = NonNullable<Awaited<ReturnType<typeof import("@/lib/services/public-league-portal").getPublicLeaguePortal>>>;

export function PublicLeaguePortal({ arenaSlug, playerName, portal, view = "games", showPrize = true }: { arenaSlug: string; playerName: string; portal: Portal; view?: "games" | "pairs"; showPrize?: boolean }) {
  const [message, setMessage] = useState("");
  const [pending, startTransition] = useTransition();
  const submit = (form: HTMLFormElement, action: (data: FormData) => Promise<void>, success: string) => startTransition(async () => {
    try { await action(new FormData(form)); setMessage(success); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível concluir a ação."); }
  });
  const ownPairs = portal.pairs.filter((pair) => pair.categoryId === portal.selectedLeagueCategoryId);
  const challenges = portal.challenges.filter((challenge) => challenge.categoryId === portal.selectedLeagueCategoryId);
  const selectedCategory = portal.leagueCategories.find((category) => category.id === portal.selectedLeagueCategoryId);

  return <section className="public-league-portal section-card stack-md">
    <header className="public-league-portal-header"><h2>{view === "pairs" ? "Duplas da Liga" : `Olá, ${playerName}`}</h2>{view === "games" ? <span className="public-portal-badge">{portal.leagueNotifications.length} notificação{portal.leagueNotifications.length === 1 ? "" : "ões"}</span> : null}</header>
    <form method="get" className="portal-league-category-picker"><input type="hidden" name="section" value="leagues" /><input type="hidden" name="leagueTab" value={view} /><input type="hidden" name="tab" value="games" /><label>Categoria da Liga<select name="leagueCategory" defaultValue={portal.selectedLeagueCategoryId ?? ""}>{portal.leagueCategories.map((category) => <option value={category.id} key={category.id}>{category.label}{category.member ? " · Minha Liga" : ""}</option>)}</select></label><button className="button button-secondary" type="submit">Ver categoria</button></form>
    {selectedCategory ? <p className="portal-league-category-context">{selectedCategory.member ? "Você participa desta categoria. As ações da sua dupla aparecem abaixo." : "Visualização pública: acompanhe as duplas e os resultados desta categoria."}</p> : <p className="muted">Nenhuma categoria de Liga ativa foi encontrada.</p>}
    {view === "pairs" ? <section className="portal-league-pairs"><h3>Duplas inscritas</h3>{portal.selectedLeaguePairs.length ? <div>{portal.selectedLeaguePairs.map((pair) => <article key={pair.id}><div><strong>{pair.name}</strong></div>{pair.groupName ? <small>{pair.groupName}</small> : null}</article>)}</div> : <p className="muted">Ainda não há duplas nesta categoria.</p>}</section> : <>
      {portal.leagueNotifications.length ? <section className="public-portal-notifications">{portal.leagueNotifications.map((notification) => <a className="public-portal-notification-reservation" href={notification.href || "#"} key={notification.id}><span className="public-portal-notification-icon" aria-hidden="true">⌁</span><span className="public-portal-notification-copy"><strong>{notification.title}</strong><small>{notification.message}</small></span></a>)}</section> : null}
      {showPrize && portal.prizes.length ? <section className="public-league-prizes"><h3>Premiação da Liga</h3>{portal.prizes.map((prize) => <article key={prize.id}><strong>{prize.eventName} · {prize.categoryName}</strong><p className="public-league-prize-description">{prize.description}</p></article>)}</section> : null}
      <section className="portal-league-results"><h3>Jogos e resultados</h3>{portal.leagueResults.length ? <div>{portal.leagueResults.map((result) => <article key={result.id}><span>Semana {result.block ?? "—"}</span><strong>{result.homePairName} <b>{result.finished ? `${result.homeScore ?? 0} × ${result.awayScore ?? 0}` : "×"}</b> {result.awayPairName}</strong><small>{result.finished ? "Resultado registrado" : "Aguardando resultado"}</small></article>)}</div> : <p className="muted">Ainda não há jogos para esta categoria.</p>}</section>
      {ownPairs.length ? <section className="public-portal-pairs">{ownPairs.map((pair) => <article className="public-portal-pair" key={pair.id}><header><strong>{pair.name}</strong></header>{pair.opponents.length ? <form onSubmit={(event) => { event.preventDefault(); submit(event.currentTarget, createLeagueChallengeAction, "Sugestão enviada para a dupla."); }} className="public-challenge-form"><strong className="public-league-host-title">Sugerir horário para este jogo</strong><input type="hidden" name="arenaSlug" value={arenaSlug} /><input type="hidden" name="proposerPairId" value={pair.id} /><label>Confronto mandante<select name="opponentPairId" required>{pair.opponents.map((opponent) => <option value={opponent.id} key={opponent.matchId}>Semana {opponent.block} · {opponent.name}</option>)}</select></label><label>Horário disponível<select name="slot" required onChange={(event) => { const [courtId, startsAt, durationMinutes] = event.target.value.split("|"); const form = event.currentTarget.form!; (form.elements.namedItem("courtId") as HTMLInputElement).value = courtId; (form.elements.namedItem("startsAt") as HTMLInputElement).value = startsAt; (form.elements.namedItem("durationMinutes") as HTMLInputElement).value = durationMinutes; }}>{portal.slots.map((slot) => <option value={slot.value} key={slot.value}>{slot.label}</option>)}</select></label><input type="hidden" name="courtId" defaultValue={portal.slots[0]?.value.split("|")[0] ?? ""} /><input type="hidden" name="startsAt" defaultValue={portal.slots[0]?.value.split("|")[1] ?? ""} /><input type="hidden" name="durationMinutes" defaultValue={portal.slots[0]?.value.split("|")[2] ?? "60"} /><button type="submit" className="button button-primary" disabled={pending || !portal.slots.length}>{pending ? "Enviando..." : "Sugerir horário"}</button></form> : null}<details className="public-medical-request"><summary>Solicitar substituição médica</summary>{pair.medicalRequestPending ? <p className="muted">Solicitação já enviada para a arena.</p> : <form onSubmit={(event) => { event.preventDefault(); submit(event.currentTarget, requestLeagueMedicalSubstitutionAction, "Solicitação enviada para a arena."); }}><input type="hidden" name="arenaSlug" value={arenaSlug} /><input type="hidden" name="pairId" value={pair.id} /><label>Atleta afastado<select name="previousPlayerId">{pair.players.map((player) => <option value={player.id} key={player.id}>{player.name}</option>)}</select></label><label>Substituto<select name="replacementPlayerId">{portal.replacementPlayers.filter((player) => !pair.players.some((member) => member.id === player.id)).map((player) => <option value={player.id} key={player.id}>{player.name}</option>)}</select></label><label>Motivo médico<textarea name="reason" minLength={10} required /></label><button type="submit" className="button" disabled={pending}>Enviar solicitação</button></form>}</details></article>)}</section> : null}
      <section className="public-challenge-list"><h3>Sugestões de horário</h3>{challenges.length ? challenges.map((challenge) => <article id={`desafio-${challenge.id}`} key={challenge.id}><div className="public-challenge-details"><div className="public-challenge-title-row"><strong>Semana {challenge.block ?? "—"} · {challenge.proposer} × {challenge.opponent}</strong>{challenge.status === "ACCEPTED" ? <span className="public-league-reservation-status"><b aria-hidden="true">✓</b> Reserva confirmada</span> : null}</div><span>{challenge.court} · {challenge.proposedAt}</span>{challenge.status === "PENDING" ? <small>Responder até {challenge.responseDueAt}</small> : challenge.status === "REJECTED" ? <small>Recusado</small> : null}</div>{challenge.incoming && challenge.status === "PENDING" ? <div className="public-challenge-actions"><form onSubmit={(event) => { event.preventDefault(); submit(event.currentTarget, respondLeagueProposalAction, "Sugestão aceita."); }}><input type="hidden" name="arenaSlug" value={arenaSlug} /><input type="hidden" name="proposalId" value={challenge.id} /><input type="hidden" name="response" value="ACCEPTED" /><button className="button button-primary" disabled={pending}>Aceitar</button></form><form onSubmit={(event) => { event.preventDefault(); submit(event.currentTarget, respondLeagueProposalAction, "Sugestão recusada."); }}><input type="hidden" name="arenaSlug" value={arenaSlug} /><input type="hidden" name="proposalId" value={challenge.id} /><input type="hidden" name="response" value="REJECTED" /><button className="button" disabled={pending}>Recusar</button></form></div> : null}</article>) : <p className="muted">Nenhuma sugestão nesta categoria.</p>}</section>
    </>}
    {message ? <p className="public-booking-message" role="status">{message}</p> : null}
  </section>;
}
