/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "stack_md_category_detail_layout": [
    "stack-md", "category-detail-layout", "tw:grid", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]",
    "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]",
    "tw:[&_.t-tabs]:gap-y-[4px]", "tw:[&_.t-tabs]:gap-x-[4px]", "tw:[&_.t-tabs]:pt-[4px]", "tw:[&_.t-tabs]:pr-[4px]",
    "tw:[&_.t-tabs]:pb-[4px]", "tw:[&_.t-tabs]:pl-[4px]", "tw:[&_.t-tabs]:border-t-[length:1px]", "tw:[&_.t-tabs]:[border-top-style:solid]",
    "tw:[&_.t-tabs]:border-t-[color:#d5e3f2]", "tw:[&_.t-tabs]:border-r-[length:1px]", "tw:[&_.t-tabs]:[border-right-style:solid]", "tw:[&_.t-tabs]:border-r-[color:#d5e3f2]",
    "tw:[&_.t-tabs]:border-b-[length:1px]", "tw:[&_.t-tabs]:[border-bottom-style:solid]", "tw:[&_.t-tabs]:border-b-[color:#d5e3f2]", "tw:[&_.t-tabs]:border-l-[length:1px]",
    "tw:[&_.t-tabs]:[border-left-style:solid]", "tw:[&_.t-tabs]:border-l-[color:#d5e3f2]", "tw:[&_.t-tabs]:rounded-[11px]", "tw:[&_.t-tabs]:bg-[color:#f8fbff]",
    "tw:[&_.t-tabs]:[background-image:none]", "tw:[&_.t-tab]:pt-[8px]", "tw:[&_.t-tab]:pr-[11px]", "tw:[&_.t-tab]:pb-[8px]",
    "tw:[&_.t-tab]:pl-[11px]", "tw:[&_.t-tab]:border-t-[length:0]", "tw:[&_.t-tab]:[border-top-style:none]", "tw:[&_.t-tab]:border-t-[color:currentColor]",
    "tw:[&_.t-tab]:border-r-[length:0]", "tw:[&_.t-tab]:[border-right-style:none]", "tw:[&_.t-tab]:border-r-[color:currentColor]", "tw:[&_.t-tab]:border-b-[length:0]",
    "tw:[&_.t-tab]:[border-bottom-style:none]", "tw:[&_.t-tab]:border-b-[color:currentColor]", "tw:[&_.t-tab]:border-l-[length:0]", "tw:[&_.t-tab]:[border-left-style:none]",
    "tw:[&_.t-tab]:border-l-[color:currentColor]", "tw:[&_.t-tab]:rounded-[8px]", "tw:[&_.t-tab]:text-[color:#59718d]", "tw:[&_.t-tab]:text-[.76rem]",
    "tw:[&_.t-tab]:inline-flex", "tw:[&_.t-tab]:items-center", "tw:[&_.t-tab]:justify-center", "tw:viewport-580:[&_.t-tab]:justify-start",
    "tw:[&_.t-tab]:gap-y-[7px]", "tw:[&_.t-tab]:gap-x-[7px]", "tw:[&_.t-tab-icon]:inline-flex", "tw:[&_.t-tab-icon]:w-[17px]",
    "tw:[&_.t-tab-icon]:h-[17px]", "tw:[&_.t-tab-icon]:place-items-center", "tw:[&_.t-tab-icon]:text-[.94rem]", "tw:[&_.t-tab-icon]:font-[700]",
    "tw:[&_.t-tab-icon]:leading-[1]", "tw:[&_.t-tab-icon]:items-center", "tw:[&_.t-tab-icon]:justify-center", "tw:[&_.t-tab:hover]:text-[color:#155caf]",
    "tw:[&_.t-tab:hover]:bg-[color:#edf5ff]", "tw:[&_.t-tab:hover]:[background-image:none]", "tw:[&_.t-tab-active]:text-[color:#fff]", "tw:[&_.t-tab-active]:bg-[color:transparent]",
    "tw:[&_.t-tab-active]:[background-image:linear-gradient(135deg,_#0d62c2,_#1879d5)]", "tw:[&_.t-tab-active]:[box-shadow:0_4px_10px_rgb(20_99_194_/_.2)]", "tw:[&_.league-history-panel]:pt-[15px]", "tw:[&_.league-history-panel]:pr-[18px]",
    "tw:[&_.league-history-panel]:pb-[15px]", "tw:[&_.league-history-panel]:pl-[18px]", "tw:[&_.league-history-panel]:border-t-[color:#d7e4f1]", "tw:[&_.league-history-panel]:border-r-[color:#d7e4f1]",
    "tw:[&_.league-history-panel]:border-b-[color:#d7e4f1]", "tw:[&_.league-history-panel]:border-l-[color:#d7e4f1]", "tw:[&_.league-history-panel]:rounded-[13px]", "tw:[&_.league-history-panel]:bg-[color:#fff]",
    "tw:[&_.league-history-panel]:[background-image:none]", "tw:[&_.league-history-panel]:[box-shadow:0_8px_22px_rgb(17_62_112_/_.055)]", "tw:[&_.league-history-panel]:gap-y-[13px]", "tw:[&_.league-history-panel]:gap-x-[13px]",
    "tw:[&_.league-history-empty]:pt-[15px]", "tw:[&_.league-history-empty]:pr-[18px]", "tw:[&_.league-history-empty]:pb-[15px]", "tw:[&_.league-history-empty]:pl-[18px]",
    "tw:[&_.league-history-empty]:border-t-[color:#d7e4f1]", "tw:[&_.league-history-empty]:border-r-[color:#d7e4f1]", "tw:[&_.league-history-empty]:border-b-[color:#d7e4f1]", "tw:[&_.league-history-empty]:border-l-[color:#d7e4f1]",
    "tw:[&_.league-history-empty]:rounded-[13px]", "tw:[&_.league-history-empty]:bg-[color:#fff]", "tw:[&_.league-history-empty]:[background-image:none]", "tw:[&_.league-history-empty]:[box-shadow:0_8px_22px_rgb(17_62_112_/_.055)]",
    "tw:[&_.league-history-empty]:gap-y-[13px]", "tw:[&_.league-history-empty]:gap-x-[13px]", "tw:[&_.league-history-list_article]:border-t-[color:#dce7f2]", "tw:[&_.league-history-list_article]:border-r-[color:#dce7f2]",
    "tw:[&_.league-history-list_article]:border-b-[color:#dce7f2]", "tw:[&_.league-history-list_article]:border-l-[color:#dce7f2]", "tw:[&_.league-history-list_article]:rounded-[9px]", "tw:[&_.league-history-list_article]:bg-[color:#f8fbff]",
    "tw:[&_.league-history-list_article]:[background-image:none]", "tw:[&_.league-history-list_article]:gap-y-[3px]", "tw:[&_.league-history-list_article]:gap-x-[3px]", "tw:[&_.league-history-list_article]:pt-[11px]",
    "tw:[&_.league-history-list_article]:pr-[11px]", "tw:[&_.league-history-list_article]:pb-[11px]", "tw:[&_.league-history-list_article]:pl-[11px]", "tw:[&_.t-tab-icon_.league-icon]:w-[15px]",
    "tw:[&_.t-tab-icon_.league-icon]:h-[15px]", "tw:[&_.t-tab-icon_.league-icon]:[stroke-width:1.9]", "tw:[&_.button]:min-h-[36px]", "tw:[&_.button]:pt-[7px]",
    "tw:[&_.button]:pr-[11px]", "tw:[&_.button]:pb-[7px]", "tw:[&_.button]:pl-[11px]", "tw:[&_.button]:rounded-[7px]",
    "tw:[&_.button]:text-[.76rem]",
  ].join(" "),
} as const;
