import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "tournament_category_detail_form": [
    "tournament-category-detail-form", "tw:grid", "tw:gap-y-[18px]", "tw:gap-x-[18px]",
    "tw:max-w-[980px]", "tw:[&_header]:grid", "tw:[&_header]:gap-y-[5px]", "tw:[&_header]:gap-x-[5px]",
    "tw:[&_header]:pb-[15px]", "tw:[&_header]:border-b-[length:1px]", "tw:[&_header]:[border-bottom-style:solid]", "tw:[&_header]:border-b-[color:var(--line)]",
    "tw:[&_header_h2]:mt-[0]", "tw:[&_header_h2]:mr-[0]", "tw:[&_header_h2]:mb-[0]", "tw:[&_header_h2]:ml-[0]",
    "tw:[&_header_p]:mt-[0]", "tw:[&_header_p]:mr-[0]", "tw:[&_header_p]:mb-[0]", "tw:[&_header_p]:ml-[0]",
    "tw:[&_header_>_p:last-child]:text-[color:var(--muted)]", "tw:[&_header_>_p:last-child]:text-[.86rem]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "tournament_category_detail_grid": [
    "tournament-category-detail-grid", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-620:grid-cols-[1fr]",
    "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[6px]",
    "tw:[&_label]:gap-x-[6px]", "tw:[&_label]:text-[color:#254364]", "tw:[&_label]:text-[.8rem]", "tw:[&_label]:font-[700]",
    "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[42px]", "tw:[&_small]:text-[color:var(--muted)]", "tw:[&_small]:text-[.7rem]",
    "tw:[&_small]:font-[500]",
  ].join(" "),
  "tournament_category_restrictions": [
    "tournament-category-restrictions", "tw:grid", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:text-[color:#254364]", "tw:text-[.8rem]", "tw:font-[700]", "tw:pt-[15px]",
    "tw:pr-[15px]", "tw:pb-[15px]", "tw:pl-[15px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#dce7f3]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#dce7f3]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce7f3]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#dce7f3]", "tw:rounded-[10px]",
    "tw:bg-[color:#f8fbff]", "tw:[background-image:none]", "tw:[&_p]:mt-[4px]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:var(--muted)]", "tw:[&_p]:text-[.76rem]",
    "tw:[&_p]:font-[500]", "tw:[&_p]:leading-[1.45]",
  ].join(" "),
  "tournament_category_standard_options": [
    "tournament-category-standard-options", "tw:flex", "tw:viewport-620:grid", "tw:flex-wrap",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:[&_label]:inline-flex", "tw:[&_label]:items-center",
    "tw:[&_label]:gap-y-[7px]", "tw:[&_label]:gap-x-[7px]", "tw:[&_label]:text-[color:#234364]", "tw:[&_label]:text-[.78rem]",
    "tw:[&_label]:font-[700]", "tw:[&_label]:pt-[8px]", "tw:[&_label]:pr-[10px]", "tw:[&_label]:pb-[8px]",
    "tw:[&_label]:pl-[10px]", "tw:[&_label]:border-t-[length:1px]", "tw:[&_label]:[border-top-style:solid]", "tw:[&_label]:border-t-[color:#d5e1ef]",
    "tw:[&_label]:border-r-[length:1px]", "tw:[&_label]:[border-right-style:solid]", "tw:[&_label]:border-r-[color:#d5e1ef]", "tw:[&_label]:border-b-[length:1px]",
    "tw:[&_label]:[border-bottom-style:solid]", "tw:[&_label]:border-b-[color:#d5e1ef]", "tw:[&_label]:border-l-[length:1px]", "tw:[&_label]:[border-left-style:solid]",
    "tw:[&_label]:border-l-[color:#d5e1ef]", "tw:[&_label]:rounded-[7px]", "tw:[&_label]:bg-[color:#fff]", "tw:[&_label]:[background-image:none]",
    "tw:viewport-620:grid-cols-[1fr]", "tw:viewport-620:[&_label]:w-[100%]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "tournament_category_active_toggle": [
    "tournament-category-active-toggle", "tw:inline-flex", "tw:items-center", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:text-[color:#147347]", "tw:text-[.78rem]", "tw:font-[700]",
    "tw:w-[fit-content]", "tw:min-h-[40px]", "tw:pt-[0]", "tw:pr-[10px]",
    "tw:pb-[0]", "tw:pl-[10px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#c9e6d6]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#c9e6d6]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#c9e6d6]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#c9e6d6]", "tw:rounded-[8px]", "tw:bg-[color:#f0fbf5]",
    "tw:[background-image:none]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
} as const;
