ALTER TABLE "Super12Event" ADD COLUMN "knockoutState" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Super12Match" ADD COLUMN "roundNumber" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Super12Match" ADD COLUMN "stage" TEXT NOT NULL DEFAULT 'GROUP';
ALTER TABLE "Super12Match" ALTER COLUMN "groupId" DROP NOT NULL;
ALTER TABLE "Super12Match" ALTER COLUMN "homePairId" DROP NOT NULL;
ALTER TABLE "Super12Match" ALTER COLUMN "awayPairId" DROP NOT NULL;
