import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "class_group_workspace": [
    "class-group-workspace", "tw:grid", "tw:gap-y-[16px]", "tw:gap-x-[16px]",
    "tw:pt-[20px]", "tw:viewport-700:pt-[16px]", "tw:pr-[20px]", "tw:viewport-700:pr-[16px]",
    "tw:pb-[20px]", "tw:viewport-700:pb-[16px]", "tw:pl-[20px]", "tw:viewport-700:pl-[16px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d7e4f1]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#d7e4f1]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#d7e4f1]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d7e4f1]",
    "tw:rounded-[16px]", "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[box-shadow:0_8px_22px_rgb(17_62_112_/_.05)]",
  ].join(" "),
  "class_group_workspace_header": [
    "class-group-workspace-header", "tw:[&_h2]:mt-[3px]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[4px]",
    "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#0c376b]", "tw:[&_h2]:text-[1.12rem]", "tw:[&_.muted]:mt-[0]",
    "tw:[&_.muted]:mr-[0]", "tw:[&_.muted]:mb-[0]", "tw:[&_.muted]:ml-[0]", "tw:[&_.muted]:text-[.83rem]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "muted": sharedUtilities.muted,
  "class_group_form": [
    "class-group-form", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-700:grid-cols-[1fr]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:pt-[14px]", "tw:pr-[14px]",
    "tw:pb-[14px]", "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dce8f3]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce8f3]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce8f3]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dce8f3]", "tw:rounded-[12px]", "tw:bg-[color:#f8fbfe]",
    "tw:[background-image:none]", "tw:[&_>_label]:grid", "tw:[&_>_label]:gap-y-[5px]", "tw:[&_>_label]:gap-x-[5px]",
    "tw:[&_>_label]:text-[color:#5d768e]", "tw:[&_>_label]:text-[.67rem]", "tw:[&_>_label]:font-[800]", "tw:[&_>_label]:tracking-[.035em]",
    "tw:[&_>_label]:uppercase", "tw:[&_>_.button-primary]:[justify-self:start]", "tw:[&_>_.button-primary]:min-h-[38px]", "tw:[&_>_.button-primary]:[padding-inline:15px]",
  ].join(" "),
  "class_group_plans": [
    "class-group-plans", "tw:[grid-column:1_/_-1]", "tw:grid", "tw:gap-y-[9px]",
    "tw:gap-x-[9px]", "tw:min-w-[0]", "tw:mt-[0]", "tw:mr-[0]",
    "tw:mb-[0]", "tw:ml-[0]", "tw:pt-[12px]", "tw:pr-[12px]",
    "tw:pb-[12px]", "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dce8f3]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce8f3]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce8f3]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dce8f3]", "tw:rounded-[10px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:grid-cols-[repeat(auto-fit,_minmax(150px,_1fr))]", "tw:[&_legend]:pt-[0]", "tw:[&_legend]:pr-[4px]",
    "tw:[&_legend]:pb-[0]", "tw:[&_legend]:pl-[4px]", "tw:[&_legend]:text-[color:#365b7e]", "tw:[&_legend]:text-[.75rem]",
    "tw:[&_legend]:font-[800]", "tw:[&_>_label]:inline-flex", "tw:[&_>_label]:items-center", "tw:[&_>_label]:gap-y-[7px]",
    "tw:[&_>_label]:gap-x-[7px]", "tw:[&_>_label]:text-[color:#365b7e]", "tw:[&_>_label]:text-[.77rem]",
  ].join(" "),
  "class_group_schedules": [
    "class-group-schedules", "tw:[grid-column:1_/_-1]", "tw:grid", "tw:gap-y-[9px]",
    "tw:gap-x-[9px]", "tw:min-w-[0]", "tw:mt-[0]", "tw:mr-[0]",
    "tw:mb-[0]", "tw:ml-[0]", "tw:pt-[12px]", "tw:pr-[12px]",
    "tw:pb-[12px]", "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dce8f3]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce8f3]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce8f3]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dce8f3]", "tw:rounded-[10px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]",
  ].join(" "),
  "class_group_schedules_title": [
    "class-group-schedules-title", "tw:flex", "tw:items-baseline", "tw:justify-between",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:text-[color:#143f6d]", "tw:text-[.82rem]",
    "tw:[&_span]:text-[color:#6b849a]", "tw:[&_span]:text-[.71rem]",
  ].join(" "),
  "class_group_schedule_row": [
    "class-group-schedule-row", "tw:[&_>_label]:grid", "tw:[&_>_label]:gap-y-[5px]", "tw:[&_>_label]:gap-x-[5px]",
    "tw:[&_>_label]:text-[color:#5d768e]", "tw:[&_>_label]:text-[.67rem]", "tw:[&_>_label]:font-[800]", "tw:[&_>_label]:tracking-[.035em]",
    "tw:[&_>_label]:uppercase", "tw:grid", "tw:grid-cols-[minmax(150px,_1fr)_minmax(110px,_.55fr)_minmax(90px,_.42fr)_auto]", "tw:viewport-700:grid-cols-[1fr_1fr]",
    "tw:[align-items:end]", "tw:gap-y-[9px]", "tw:gap-x-[9px]", "tw:pt-[9px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#e5edf5]", "tw:viewport-700:[&_>_.button]:[grid-column:1_/_-1]",
    "tw:viewport-700:[&_>_.button]:[justify-self:start]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "button_button_secondary_button_small": sharedUtilities.buttonButtonSecondaryButtonSmall,
  "class_group_notes": [
    "class-group-notes", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "class_group_list": [
    "class-group-list", "tw:grid", "tw:grid-cols-[repeat(auto-fit,_minmax(270px,_1fr))]", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]", "tw:[&_article]:grid", "tw:[&_article]:gap-y-[10px]", "tw:[&_article]:gap-x-[10px]",
    "tw:[&_article]:pt-[14px]", "tw:[&_article]:pr-[14px]", "tw:[&_article]:pb-[14px]", "tw:[&_article]:pl-[14px]",
    "tw:[&_article]:border-t-[length:1px]", "tw:[&_article]:[border-top-style:solid]", "tw:[&_article]:border-t-[color:#dce7f2]", "tw:[&_article]:border-r-[length:1px]",
    "tw:[&_article]:[border-right-style:solid]", "tw:[&_article]:border-r-[color:#dce7f2]", "tw:[&_article]:border-b-[length:1px]", "tw:[&_article]:[border-bottom-style:solid]",
    "tw:[&_article]:border-b-[color:#dce7f2]", "tw:[&_article]:border-l-[length:1px]", "tw:[&_article]:[border-left-style:solid]", "tw:[&_article]:border-l-[color:#dce7f2]",
    "tw:[&_article]:rounded-[12px]", "tw:[&_article]:bg-[color:#fff]", "tw:[&_article]:[background-image:none]", "tw:[&_article_header_div]:grid",
    "tw:[&_article_header_div]:gap-y-[2px]", "tw:[&_article_header_div]:gap-x-[2px]", "tw:[&_article_strong]:text-[color:#123b70]", "tw:[&_article_strong]:text-[.9rem]",
    "tw:[&_article_header_span]:text-[color:#698196]", "tw:[&_article_header_span]:text-[.76rem]", "tw:[&_article_>_div]:grid", "tw:[&_article_>_div]:gap-y-[5px]",
    "tw:[&_article_>_div]:gap-x-[5px]", "tw:[&_article_>_div_span]:text-[color:#45647f]", "tw:[&_article_>_div_span]:text-[.76rem]", "tw:[&_article_>_div_span]:leading-[1.35]",
  ].join(" "),
  "button_button_primary_button_small": sharedUtilities.buttonButtonPrimaryButtonSmall,
} as const;
