import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "teacher_groups_panel_teacher_class_directory": [
    "teacher-groups-panel", "teacher-class-directory", "tw:grid", "tw:gap-y-[20px]",
    "tw:gap-x-[20px]",
  ].join(" "),
  "teacher_class_create_modal": [
    "teacher-class-create-modal", "tw:fixed", "tw:z-[90]", "tw:top-[0]",
    "tw:right-[0]", "tw:bottom-[0]", "tw:left-[0]", "tw:grid",
    "tw:place-items-center", "tw:pt-[20px]", "tw:viewport-640:pt-[12px]", "tw:pr-[20px]",
    "tw:viewport-640:pr-[12px]", "tw:pb-[20px]", "tw:viewport-640:pb-[12px]", "tw:pl-[20px]",
    "tw:viewport-640:pl-[12px]", "tw:bg-[color:rgb(10_29_54_/_.38)]", "tw:[background-image:none]", "tw:[backdrop-filter:blur(4px)]",
    "tw:[&_.teacher-class-create-panel]:grid", "tw:[&_.teacher-class-create-panel]:gap-y-[17px]", "tw:[&_.teacher-class-create-panel]:gap-x-[17px]", "tw:[&_.teacher-class-create-panel]:w-[min(760px,_100%)]",
    "tw:[&_.teacher-class-create-panel]:max-h-[calc(100vh_-_40px)]", "tw:viewport-640:[&_.teacher-class-create-panel]:max-h-[calc(100vh_-_24px)]", "tw:[&_.teacher-class-create-panel]:[overflow-x:auto]", "tw:[&_.teacher-class-create-panel]:[overflow-y:auto]",
    "tw:[&_.teacher-class-create-panel]:pt-[22px]", "tw:viewport-640:[&_.teacher-class-create-panel]:pt-[18px]", "tw:[&_.teacher-class-create-panel]:pr-[22px]", "tw:viewport-640:[&_.teacher-class-create-panel]:pr-[14px]",
    "tw:[&_.teacher-class-create-panel]:pb-[22px]", "tw:viewport-640:[&_.teacher-class-create-panel]:pb-[18px]", "tw:[&_.teacher-class-create-panel]:pl-[22px]", "tw:viewport-640:[&_.teacher-class-create-panel]:pl-[14px]",
    "tw:[&_.teacher-class-create-panel]:[box-shadow:0_22px_58px_rgb(12_33_61_/_.2)]", "tw:viewport-640:[align-items:end]", "tw:viewport-640:[&_.teacher-class-create-panel]:rounded-[14px]",
  ].join(" "),
  "section_card_teacher_detail_section_teacher_class_create_panel": [
    "section-card", "teacher-detail-section", "teacher-class-create-panel", "tw:pt-[22px]",
    "tw:pr-[0]", "tw:pb-[22px]", "tw:pl-[0]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:0]", "tw:[border-right-style:none]",
    "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[0]",
    "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:[box-shadow:none]", "tw:grid",
    "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:[&_>_header]:flex", "tw:[&_>_header]:items-start",
    "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[14px]", "tw:[&_>_header]:gap-x-[14px]", "tw:[&_h2]:mt-[0]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[1rem]",
    "tw:[&_>_header]:pb-[14px]", "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#e2eaf2]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "teacher_class_create_close": [
    "teacher-class-create-close", "tw:grid", "tw:w-[30px]", "tw:h-[30px]",
    "tw:place-items-center", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d5e1ec]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d5e1ec]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d5e1ec]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#d5e1ec]", "tw:rounded-[8px]", "tw:text-[color:#46627e]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:text-[1.18rem]", "tw:leading-[1]", "tw:cursor-pointer",
    "tw:hover:border-t-[color:#9ebbd6]", "tw:hover:border-r-[color:#9ebbd6]", "tw:hover:border-b-[color:#9ebbd6]", "tw:hover:border-l-[color:#9ebbd6]",
    "tw:hover:bg-[color:#f1f7fc]", "tw:hover:[background-image:none]", "tw:hover:text-[color:#185793]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "teacher_group_create_form": [
    "teacher-group-create-form", "tw:grid", "tw:grid-cols-[minmax(220px,_.75fr)_minmax(280px,_1.25fr)]", "tw:viewport-900:grid-cols-[1fr]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:pt-[14px]", "tw:pr-[14px]",
    "tw:pb-[14px]", "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dce8f3]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce8f3]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce8f3]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dce8f3]", "tw:rounded-[12px]", "tw:bg-[color:#f8fbfe]",
    "tw:[background-image:none]", "tw:[&_>_label]:grid", "tw:[&_>_label]:gap-y-[5px]", "tw:[&_>_label]:gap-x-[5px]",
    "tw:[&_>_label]:text-[color:#526d89]", "tw:[&_>_label]:text-[.72rem]", "tw:[&_>_label]:font-[750]", "tw:[&_fieldset]:min-w-[0]",
    "tw:[&_fieldset]:mt-[0]", "tw:[&_fieldset]:mr-[0]", "tw:[&_fieldset]:mb-[0]", "tw:[&_fieldset]:ml-[0]",
    "tw:[&_fieldset]:pt-[11px]", "tw:[&_fieldset]:pr-[11px]", "tw:[&_fieldset]:pb-[11px]", "tw:[&_fieldset]:pl-[11px]",
    "tw:[&_fieldset]:border-t-[length:1px]", "tw:[&_fieldset]:[border-top-style:solid]", "tw:[&_fieldset]:border-t-[color:#dce8f3]", "tw:[&_fieldset]:border-r-[length:1px]",
    "tw:[&_fieldset]:[border-right-style:solid]", "tw:[&_fieldset]:border-r-[color:#dce8f3]", "tw:[&_fieldset]:border-b-[length:1px]", "tw:[&_fieldset]:[border-bottom-style:solid]",
    "tw:[&_fieldset]:border-b-[color:#dce8f3]", "tw:[&_fieldset]:border-l-[length:1px]", "tw:[&_fieldset]:[border-left-style:solid]", "tw:[&_fieldset]:border-l-[color:#dce8f3]",
    "tw:[&_fieldset]:rounded-[10px]", "tw:[&_fieldset]:bg-[color:#fff]", "tw:[&_fieldset]:[background-image:none]", "tw:[&_fieldset]:grid",
    "tw:[&_fieldset]:grid-cols-[repeat(auto-fit,_minmax(150px,_1fr))]", "tw:[&_fieldset]:gap-y-[8px]", "tw:[&_fieldset]:gap-x-[8px]", "tw:[&_fieldset_legend]:pt-[0]",
    "tw:[&_fieldset_legend]:pr-[4px]", "tw:[&_fieldset_legend]:pb-[0]", "tw:[&_fieldset_legend]:pl-[4px]", "tw:[&_fieldset_legend]:text-[color:#365b7e]",
    "tw:[&_fieldset_legend]:text-[.75rem]", "tw:[&_fieldset_legend]:font-[800]", "tw:[&_fieldset_label]:inline-flex", "tw:[&_fieldset_label]:items-center",
    "tw:[&_fieldset_label]:gap-y-[7px]", "tw:[&_fieldset_label]:gap-x-[7px]", "tw:[&_fieldset_label]:text-[color:#365b7e]", "tw:[&_fieldset_label]:text-[.78rem]",
    "tw:[&_>_.button-primary]:[justify-self:start]",
  ].join(" "),
  "teacher_group_schedules": [
    "teacher-group-schedules", "tw:min-w-[0]", "tw:mt-[0]", "tw:mr-[0]",
    "tw:mb-[0]", "tw:ml-[0]", "tw:pt-[11px]", "tw:pr-[11px]",
    "tw:pb-[11px]", "tw:pl-[11px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dce8f3]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce8f3]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce8f3]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dce8f3]", "tw:rounded-[10px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[grid-column:1_/_-1]", "tw:grid", "tw:gap-y-[9px]",
    "tw:gap-x-[9px]", "tw:[&_>_div:first-child]:flex", "tw:[&_>_div:first-child]:items-baseline", "tw:[&_>_div:first-child]:justify-between",
    "tw:[&_>_div:first-child]:gap-y-[10px]", "tw:[&_>_div:first-child]:gap-x-[10px]", "tw:[&_>_div:first-child]:text-[color:#173f6d]", "tw:[&_>_div:first-child]:text-[.82rem]",
    "tw:[&_>_div:first-child_span]:text-[color:#6b849a]", "tw:[&_>_div:first-child_span]:text-[.72rem]",
  ].join(" "),
  "teacher_group_schedule_row": [
    "teacher-group-schedule-row", "tw:[&_>_label]:grid", "tw:[&_>_label]:gap-y-[5px]", "tw:[&_>_label]:gap-x-[5px]",
    "tw:[&_>_label]:text-[color:#526d89]", "tw:[&_>_label]:text-[.72rem]", "tw:[&_>_label]:font-[750]", "tw:[&_>_label]:min-w-[0]",
    "tw:grid", "tw:grid-cols-[minmax(0,_1fr)_minmax(0,_.62fr)_minmax(0,_.48fr)]", "tw:viewport-600:grid-cols-[1fr_1fr]", "tw:gap-y-[9px]",
    "tw:gap-x-[9px]", "tw:[align-items:end]", "tw:pt-[9px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#e5edf5]", "tw:[&.has-remove]:grid-cols-[minmax(0,_1fr)_minmax(0,_.62fr)_minmax(0,_.48fr)_auto]", "tw:[&_input]:min-w-[0]",
    "tw:[&_select]:min-w-[0]", "tw:viewport-600:[&_>_.button]:[grid-column:1_/_-1]", "tw:viewport-600:[&_>_.button]:[justify-self:start]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "button_button_secondary_button_small": sharedUtilities.buttonButtonSecondaryButtonSmall,
  "teacher_group_generated_name": [
    "teacher-group-generated-name", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-[color:#5a7189]", "tw:text-[.74rem]", "tw:[&_strong]:text-[color:#173f6d]",
  ].join(" "),
  "teacher_group_notes": [
    "teacher-group-notes", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "button": sharedUtilities.button,
  "section_card_teacher_detail_section_teacher_class_list_panel": [
    "section-card", "teacher-detail-section", "teacher-class-list-panel", "tw:pt-[22px]",
    "tw:pr-[0]", "tw:pb-[22px]", "tw:pl-[0]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:0]", "tw:[border-right-style:none]",
    "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[0]",
    "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:[box-shadow:none]", "tw:grid",
    "tw:gap-y-[24px]", "tw:gap-x-[24px]", "tw:[&_>_header]:flex", "tw:[&_>_header]:items-center",
    "tw:viewport-580:[&_>_header]:items-start", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[10px]", "tw:[&_>_header]:gap-x-[10px]",
    "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]",
    "tw:[&_h2]:text-[1rem]", "tw:[overflow-x:visible]", "tw:[overflow-y:visible]", "tw:[&_>_header]:pt-[0]",
    "tw:[&_>_header]:pr-[0]", "tw:[&_>_header]:pb-[4px]", "tw:[&_>_header]:pl-[0]", "tw:[&_>_header_h2]:text-[color:#12213f]",
    "tw:[&_>_header_h2]:text-[1.18rem]", "tw:[&_>_header_.muted]:mt-[6px]", "tw:[&_>_header_.muted]:mr-[0]", "tw:[&_>_header_.muted]:mb-[0]",
    "tw:[&_>_header_.muted]:ml-[0]", "tw:[&_>_header_.muted]:text-[color:#5e738f]", "tw:[&_>_header_.muted]:text-[.91rem]", "tw:[&_>_header_.teacher-class-create-trigger]:min-h-[32px]",
    "tw:[&_>_header_.teacher-class-create-trigger]:[padding-inline:10px]", "tw:[&_>_header_.teacher-class-create-trigger]:rounded-[7px]", "tw:[&_>_header_.teacher-class-create-trigger]:text-[.74rem]", "tw:[&_>_header_.teacher-class-create-trigger]:[box-shadow:none]",
    "tw:viewport-580:[&_>_header]:flex-col",
  ].join(" "),
  "button_button_primary_button_small": [
    "button", "button-primary", "button-small", "teacher-class-create-trigger",
    "tw:inline-flex", "tw:items-center", "tw:justify-center", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:min-h-[30px]", "tw:pt-[5px]", "tw:pr-[8px]",
    "tw:pb-[5px]", "tw:pl-[8px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--brand)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--brand)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--brand)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--brand)]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--brand)]",
    "tw:[background-image:none]", "tw:text-[color:#ffffff]", "tw:text-[.72rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]",
    "tw:hover:border-t-[color:var(--brand-strong)]", "tw:hover:border-r-[color:var(--brand-strong)]", "tw:hover:border-b-[color:var(--brand-strong)]", "tw:hover:border-l-[color:var(--brand-strong)]",
    "tw:hover:[transform:translateY(-1px)]", "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait",
    "tw:[&:active]:[transform:translateY(0)]", "tw:[&:active]:[box-shadow:none]", "tw:hover:bg-[color:var(--brand-strong)]", "tw:hover:[background-image:none]",
  ].join(" "),
  "teacher_class_row_list": [
    "teacher-class-row-list", "tw:grid", "tw:gap-y-[0]", "tw:gap-x-[0]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#e0e8f1]",
  ].join(" "),
  "teacher_class_list_heading": [
    "teacher-class-list-heading", "tw:grid", "tw:viewport-580:hidden", "tw:grid-cols-[minmax(180px,_1.2fr)_minmax(190px,_1fr)_minmax(150px,_.72fr)_42px]",
    "tw:viewport-880:grid-cols-[minmax(150px,_1fr)_minmax(170px,_1fr)_minmax(120px,_.7fr)_42px]", "tw:items-center", "tw:gap-x-[18px]", "tw:viewport-880:gap-x-[12px]",
    "tw:min-h-[32px]", "tw:pt-[0]", "tw:pr-[12px]", "tw:pb-[0]",
    "tw:pl-[12px]", "tw:text-[color:#5d7490]", "tw:text-[.66rem]", "tw:font-[800]",
    "tw:tracking-[.035em]", "tw:uppercase", "tw:[&_span:last-child]:text-center",
  ].join(" "),
  "teacher_class_row": [
    "teacher-class-row", "tw:grid", "tw:grid-cols-[minmax(180px,_1.2fr)_minmax(190px,_1fr)_minmax(150px,_.72fr)_42px]", "tw:viewport-880:grid-cols-[minmax(150px,_1fr)_minmax(170px,_1fr)_minmax(120px,_.7fr)_42px]",
    "tw:viewport-580:grid-cols-[minmax(0,_1fr)_auto]", "tw:items-center", "tw:gap-x-[18px]", "tw:viewport-880:gap-x-[12px]",
    "tw:relative", "tw:min-h-[50px]", "tw:viewport-580:min-h-[0]", "tw:pt-[7px]",
    "tw:viewport-580:pt-[11px]", "tw:pr-[12px]", "tw:viewport-580:pr-[0]", "tw:pb-[7px]",
    "tw:viewport-580:pb-[11px]", "tw:pl-[12px]", "tw:viewport-580:pl-[0]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e6edf4]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:hover:bg-[color:#fbfdff]", "tw:hover:[background-image:none]", "tw:viewport-580:gap-y-[8px]",
  ].join(" "),
  "teacher_class_name": [
    "teacher-class-name", "tw:grid", "tw:gap-y-[2px]", "tw:gap-x-[2px]",
    "tw:min-w-[0]", "tw:text-[color:#122b4c]", "tw:[&_strong]:[overflow-x:hidden]", "tw:[&_strong]:[overflow-y:hidden]",
    "tw:[&_strong]:text-[.82rem]", "tw:[&_strong]:text-ellipsis", "tw:[&_strong]:whitespace-nowrap", "tw:[&_small]:text-[color:#68809b]",
    "tw:[&_small]:text-[.67rem]", "tw:viewport-580:[grid-column:1]", "tw:viewport-580:[grid-row:1]",
  ].join(" "),
  "teacher_class_time": [
    "teacher-class-time", "tw:inline-flex", "tw:items-center", "tw:gap-y-[9px]",
    "tw:gap-x-[9px]", "tw:text-[color:#284462]", "tw:text-[.8rem]", "tw:viewport-580:[grid-column:1]",
    "tw:viewport-580:[grid-row:2]",
  ].join(" "),
  "teacher_class_weekday": [
    "teacher-class-weekday", "tw:inline-flex", "tw:w-[fit-content]", "tw:items-center",
    "tw:justify-center", "tw:min-h-[25px]", "tw:pt-[0]", "tw:pr-[8px]",
    "tw:pb-[0]", "tw:pl-[8px]", "tw:rounded-[5px]", "tw:text-[color:#1261c4]",
    "tw:bg-[color:#eaf2ff]", "tw:[background-image:none]", "tw:text-[.68rem]", "tw:font-[800]",
    "tw:[&.weekday-0]:text-[color:#7a4c11]", "tw:[&.weekday-0]:bg-[color:#fff3d9]", "tw:[&.weekday-0]:[background-image:none]", "tw:[&.weekday-1]:text-[color:#1261c4]",
    "tw:[&.weekday-1]:bg-[color:#eaf2ff]", "tw:[&.weekday-1]:[background-image:none]", "tw:[&.weekday-2]:text-[color:#009b61]", "tw:[&.weekday-2]:bg-[color:#e4faef]",
    "tw:[&.weekday-2]:[background-image:none]", "tw:[&.weekday-3]:text-[color:#15776f]", "tw:[&.weekday-3]:bg-[color:#ddf7f1]", "tw:[&.weekday-3]:[background-image:none]",
    "tw:[&.weekday-4]:text-[color:#743bd5]", "tw:[&.weekday-4]:bg-[color:#f1eaff]", "tw:[&.weekday-4]:[background-image:none]", "tw:[&.weekday-5]:text-[color:#c66713]",
    "tw:[&.weekday-5]:bg-[color:#fff0df]", "tw:[&.weekday-5]:[background-image:none]", "tw:[&.weekday-6]:text-[color:#5b42d8]", "tw:[&.weekday-6]:bg-[color:#f0ecff]",
    "tw:[&.weekday-6]:[background-image:none]",
  ].join(" "),
  "teacher_class_capacity": [
    "teacher-class-capacity", "tw:inline-flex", "tw:items-center", "tw:gap-y-[9px]",
    "tw:gap-x-[9px]", "tw:text-[color:#284462]", "tw:text-[.8rem]", "tw:[&_.event-icon]:[box-sizing:content-box]",
    "tw:[&_.event-icon]:w-[14px]", "tw:[&_.event-icon]:h-[14px]", "tw:[&_.event-icon]:pt-[5px]", "tw:[&_.event-icon]:pr-[5px]",
    "tw:[&_.event-icon]:pb-[5px]", "tw:[&_.event-icon]:pl-[5px]", "tw:[&_.event-icon]:rounded-[50%]", "tw:[&_.event-icon]:text-[color:#395672]",
    "tw:[&_.event-icon]:bg-[color:#f1f5f9]", "tw:[&_.event-icon]:[background-image:none]", "tw:[&_strong]:text-[.8rem]", "tw:viewport-580:[grid-column:1]",
    "tw:viewport-580:[grid-row:3]",
  ].join(" "),
  "teacher_class_actions": [
    "teacher-class-actions", "tw:relative", "tw:[&_>_summary]:grid", "tw:[&_>_summary]:w-[30px]",
    "tw:[&_>_summary]:h-[30px]", "tw:[&_>_summary]:place-items-center", "tw:[&_>_summary]:border-t-[length:1px]", "tw:[&_>_summary]:[border-top-style:solid]",
    "tw:[&_>_summary]:border-t-[color:#d5e1ed]", "tw:[&_>_summary]:border-r-[length:1px]", "tw:[&_>_summary]:[border-right-style:solid]", "tw:[&_>_summary]:border-r-[color:#d5e1ed]",
    "tw:[&_>_summary]:border-b-[length:1px]", "tw:[&_>_summary]:[border-bottom-style:solid]", "tw:[&_>_summary]:border-b-[color:#d5e1ed]", "tw:[&_>_summary]:border-l-[length:1px]",
    "tw:[&_>_summary]:[border-left-style:solid]", "tw:[&_>_summary]:border-l-[color:#d5e1ed]", "tw:[&_>_summary]:rounded-[7px]", "tw:[&_>_summary]:text-[color:#31506f]",
    "tw:[&_>_summary]:bg-[color:#fff]", "tw:[&_>_summary]:[background-image:none]", "tw:[&_>_summary]:cursor-pointer", "tw:[&_>_summary]:text-[1.15rem]",
    "tw:[&_>_summary]:leading-[1]", "tw:[&_>_summary]:[list-style:none]", "tw:[&_>_summary::-webkit-details-marker]:hidden", "tw:[&[open]_>_summary]:border-t-[color:#94b7dd]",
    "tw:[&[open]_>_summary]:border-r-[color:#94b7dd]", "tw:[&[open]_>_summary]:border-b-[color:#94b7dd]", "tw:[&[open]_>_summary]:border-l-[color:#94b7dd]", "tw:[&[open]_>_summary]:bg-[color:#f3f8fe]",
    "tw:[&[open]_>_summary]:[background-image:none]", "tw:[&_>_div]:absolute", "tw:[&_>_div]:z-[12]", "tw:[&_>_div]:top-[calc(100%_+_8px)]",
    "tw:[&_>_div]:right-[0]", "tw:[&_>_div]:grid", "tw:[&_>_div]:gap-y-[12px]", "tw:[&_>_div]:gap-x-[12px]",
    "tw:[&_>_div]:w-[min(390px,_72vw)]", "tw:viewport-580:[&_>_div]:w-[min(330px,_calc(100vw_-_52px))]", "tw:[&_>_div]:pt-[16px]", "tw:[&_>_div]:pr-[16px]",
    "tw:[&_>_div]:pb-[16px]", "tw:[&_>_div]:pl-[16px]", "tw:[&_>_div]:border-t-[length:1px]", "tw:[&_>_div]:[border-top-style:solid]",
    "tw:[&_>_div]:border-t-[color:#cdddeb]", "tw:[&_>_div]:border-r-[length:1px]", "tw:[&_>_div]:[border-right-style:solid]", "tw:[&_>_div]:border-r-[color:#cdddeb]",
    "tw:[&_>_div]:border-b-[length:1px]", "tw:[&_>_div]:[border-bottom-style:solid]", "tw:[&_>_div]:border-b-[color:#cdddeb]", "tw:[&_>_div]:border-l-[length:1px]",
    "tw:[&_>_div]:[border-left-style:solid]", "tw:[&_>_div]:border-l-[color:#cdddeb]", "tw:[&_>_div]:rounded-[12px]", "tw:[&_>_div]:bg-[color:#fff]",
    "tw:[&_>_div]:[background-image:none]", "tw:[&_>_div]:[box-shadow:0_16px_34px_rgb(17_54_95_/_.18)]", "tw:[&_>_div_>_strong]:text-[color:#17365d]", "tw:[&_>_div_>_strong]:text-[.93rem]",
    "tw:[&_.teacher-group-capacity]:grid-cols-[minmax(0,_1fr)_auto]", "tw:[&_.teacher-group-capacity]:pt-[0]", "tw:[&_.teacher-group-capacity]:pr-[0]", "tw:[&_.teacher-group-capacity]:pb-[0]",
    "tw:[&_.teacher-group-capacity]:pl-[0]", "tw:[&_.teacher-group-capacity]:bg-[color:transparent]", "tw:[&_.teacher-group-capacity]:[background-image:none]", "tw:[&_.teacher-group-capacity_label]:grid",
    "tw:[&_.teacher-group-capacity_label]:gap-y-[4px]", "tw:[&_.teacher-group-capacity_label]:gap-x-[4px]", "tw:[&_.teacher-group-capacity_label]:text-[color:#607892]", "tw:[&_.teacher-group-capacity_label]:text-[.7rem]",
    "tw:[&_.teacher-group-capacity_label]:font-[750]", "tw:[&_.teacher-group-capacity_input]:min-h-[36px]", "tw:[&_.teacher-group-capacity_input]:border-t-[length:1px]", "tw:[&_.teacher-group-capacity_input]:[border-top-style:solid]",
    "tw:[&_.teacher-group-capacity_input]:border-t-[color:#cfdeec]", "tw:[&_.teacher-group-capacity_input]:border-r-[length:1px]", "tw:[&_.teacher-group-capacity_input]:[border-right-style:solid]", "tw:[&_.teacher-group-capacity_input]:border-r-[color:#cfdeec]",
    "tw:[&_.teacher-group-capacity_input]:border-b-[length:1px]", "tw:[&_.teacher-group-capacity_input]:[border-bottom-style:solid]", "tw:[&_.teacher-group-capacity_input]:border-b-[color:#cfdeec]", "tw:[&_.teacher-group-capacity_input]:border-l-[length:1px]",
    "tw:[&_.teacher-group-capacity_input]:[border-left-style:solid]", "tw:[&_.teacher-group-capacity_input]:border-l-[color:#cfdeec]", "tw:[&_.teacher-group-capacity_input]:rounded-[7px]", "tw:[&_.teacher-group-capacity_.button]:min-h-[36px]",
    "tw:[&_.teacher-group-capacity_.button]:[align-self:end]", "tw:[&_.teacher-group-students]:max-h-[210px]", "tw:[&_.teacher-group-students]:[overflow-x:auto]", "tw:[&_.teacher-group-students]:[overflow-y:auto]",
    "tw:[&_.teacher-group-students]:pt-[3px]", "tw:viewport-580:[grid-column:2]", "tw:viewport-580:[grid-row:1]",
  ].join(" "),
  "button_button_secondary_button_small_2": [
    "button", "button-secondary", "button-small", "teacher-class-edit-trigger",
    "tw:inline-flex", "tw:items-center", "tw:justify-center", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:min-h-[30px]", "tw:pt-[5px]", "tw:pr-[8px]",
    "tw:pb-[5px]", "tw:pl-[8px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:text-[color:var(--text)]", "tw:text-[.72rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]",
    "tw:hover:border-t-[color:var(--line-strong)]", "tw:hover:border-r-[color:var(--line-strong)]", "tw:hover:border-b-[color:var(--line-strong)]", "tw:hover:border-l-[color:var(--line-strong)]",
    "tw:hover:[transform:translateY(-1px)]", "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait",
    "tw:[&:active]:[transform:translateY(0)]", "tw:[&:active]:[box-shadow:none]",
  ].join(" "),
  "teacher_group_capacity": [
    "teacher-group-capacity", "tw:grid", "tw:grid-cols-[minmax(130px,_1fr)_78px_auto]", "tw:viewport-600:grid-cols-[1fr_1fr]",
    "tw:[align-items:end]", "tw:gap-y-[7px]", "tw:gap-x-[7px]", "tw:pt-[8px]",
    "tw:pr-[8px]", "tw:pb-[8px]", "tw:pl-[8px]", "tw:rounded-[8px]",
    "tw:bg-[color:#f6f9fc]", "tw:[background-image:none]", "tw:[&_>_span]:[align-self:center]", "tw:[&_>_span]:text-[color:#476581]",
    "tw:[&_>_span]:text-[.76rem]", "tw:[&_>_span]:font-[700]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[3px]",
    "tw:[&_label]:gap-x-[3px]", "tw:[&_label]:text-[color:#637c93]", "tw:[&_label]:text-[.65rem]", "tw:[&_label]:font-[750]",
    "tw:[&_input]:min-w-[0]", "tw:[&_input]:pt-[7px]", "tw:[&_input]:pr-[8px]", "tw:[&_input]:pb-[7px]",
    "tw:[&_input]:pl-[8px]", "tw:viewport-600:[&_>_.button]:[grid-column:1_/_-1]", "tw:viewport-600:[&_>_.button]:[justify-self:start]", "tw:viewport-600:[&_>_span]:[grid-column:1_/_-1]",
  ].join(" "),
  "teacher_group_students": [
    "teacher-group-students", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:[&_>_div]:flex", "tw:[&_>_div]:items-center", "tw:viewport-600:[&_>_div]:items-start", "tw:[&_>_div]:justify-between",
    "tw:[&_>_div]:gap-y-[8px]", "tw:[&_>_div]:gap-x-[8px]", "tw:[&_>_div]:pt-[8px]", "tw:[&_>_div]:border-t-[length:1px]",
    "tw:[&_>_div]:[border-top-style:solid]", "tw:[&_>_div]:border-t-[color:#edf2f7]", "tw:[&_>_div]:text-[color:#264c73]", "tw:[&_>_div]:text-[.8rem]",
    "tw:viewport-600:[&_>_div]:flex-col",
  ].join(" "),
  "teacher_group_move": [
    "teacher-group-move", "tw:flex", "tw:items-center", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:[&_select]:max-w-[150px]", "tw:viewport-600:[&_select]:max-w-[none]", "tw:[&_select]:pt-[6px]",
    "tw:[&_select]:pr-[7px]", "tw:[&_select]:pb-[6px]", "tw:[&_select]:pl-[7px]", "tw:[&_select]:text-[.74rem]",
    "tw:viewport-600:w-[100%]", "tw:viewport-600:[&_select]:[flex:1]",
  ].join(" "),
  "muted_teacher_class_empty": [
    "muted", "teacher-class-empty", "tw:mt-[0]", "tw:mr-[0]",
    "tw:mb-[0]", "tw:ml-[0]", "tw:text-[color:var(--muted)]", "tw:pt-[38px]",
    "tw:pr-[12px]", "tw:pb-[38px]", "tw:pl-[12px]", "tw:text-center",
  ].join(" "),
  "teacher_class_footer": [
    "teacher-class-footer", "tw:pt-[19px]", "tw:viewport-580:pt-[17px]", "tw:pr-[0]",
    "tw:pb-[24px]", "tw:viewport-580:pb-[20px]", "tw:pl-[0]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#e5edf4]", "tw:text-[color:#5d728d]", "tw:text-[.9rem]",
    "tw:viewport-580:text-[.8rem]",
  ].join(" "),
} as const;
