import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "teacher_modal_backdrop": [
    "teacher-modal-backdrop", "tw:fixed", "tw:top-[0]", "tw:right-[0]",
    "tw:bottom-[0]", "tw:left-[0]", "tw:z-[80]", "tw:grid",
    "tw:pt-[24px]", "tw:pr-[24px]", "tw:pb-[24px]", "tw:pl-[24px]",
    "tw:place-items-center", "tw:bg-[color:rgb(15_23_42_/_.46)]", "tw:[background-image:none]", "tw:[backdrop-filter:blur(3px)]",
  ].join(" "),
  "teacher_modal": [
    "teacher-modal", "tw:w-[min(100%,_700px)]", "tw:pt-[20px]", "tw:pr-[20px]",
    "tw:pb-[20px]", "tw:pl-[20px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(255_255_255_/_.8)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(255_255_255_/_.8)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(255_255_255_/_.8)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(255_255_255_/_.8)]", "tw:rounded-[14px]", "tw:bg-[color:var(--panel)]",
    "tw:[background-image:none]", "tw:[box-shadow:0_25px_70px_rgb(15_23_42_/_.34)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:items-start",
    "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[12px]", "tw:[&_>_header]:gap-x-[12px]", "tw:[&_>_header]:mb-[16px]",
    "tw:[&_>_header]:pb-[14px]", "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:var(--line)]",
    "tw:[&_h2]:mt-[3px]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]",
    "tw:[&_.grid-form_:where(input,_select)]:rounded-[7px]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "grid_form": sharedUtilities.gridForm,
  "field_form_full": sharedUtilities.fieldFormFull,
  "field": sharedUtilities.field,
  "modal_actions_form_full": [
    "modal-actions", "form-full", "tw:flex", "tw:justify-end",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:mt-[8px]", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  "button": sharedUtilities.button,
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "teacher_directory": [
    "teacher-directory", "tw:grid", "tw:gap-y-[26px]", "tw:viewport-760:gap-y-[16px]",
    "tw:gap-x-[26px]", "tw:viewport-760:gap-x-[16px]", "tw:relative", "tw:[&_.teacher-management-toolbar]:absolute",
    "tw:viewport-1160:[&_.teacher-management-toolbar]:static", "tw:[&_.teacher-management-toolbar]:z-[1]", "tw:[&_.teacher-management-toolbar]:top-[-72px]", "tw:[&_.teacher-management-toolbar]:right-[0]",
    "tw:viewport-1160:[&_.teacher-management-toolbar]:justify-end", "tw:viewport-1160:[&_.teacher-management-toolbar]:mt-[-10px]",
  ].join(" "),
  "teacher_management_toolbar": [
    "teacher-management-toolbar", "tw:[&_.button]:inline-flex", "tw:[&_.button]:items-center", "tw:[&_.button]:gap-y-[11px]",
    "tw:[&_.button]:gap-x-[11px]", "tw:[&_.button]:min-h-[34px]", "tw:[&_.button]:[padding-inline:11px]", "tw:[&_.button]:rounded-[11px]",
    "tw:[&_.button]:text-[.76rem]", "tw:[&_.button_span]:text-[1.6rem]", "tw:[&_.button_span]:font-[400]", "tw:[&_.button_span]:leading-[1]",
    "tw:viewport-760:[&_.button]:w-[100%]", "tw:flex", "tw:items-center", "tw:justify-between",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]",
    "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]",
  ].join(" "),
  "button_button_primary_button_small": sharedUtilities.buttonButtonPrimaryButtonSmall,
  "teacher_directory_filters": [
    "teacher-directory-filters", "tw:grid", "tw:grid-cols-[minmax(250px,_1.25fr)_minmax(160px,_.5fr)_minmax(220px,_.7fr)]", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]", "tw:pt-[10px]", "tw:pr-[10px]", "tw:pb-[10px]",
    "tw:pl-[10px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dbe6f2]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dbe6f2]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dbe6f2]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#dbe6f2]", "tw:rounded-[13px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[box-shadow:0_8px_20px_rgb(13_50_96_/_.035)]", "tw:[&_label]:relative", "tw:[&_label]:min-w-[0]", "tw:[&_label_>_span]:absolute",
    "tw:[&_label_>_span]:z-[1]", "tw:[&_label_>_span]:top-[50%]", "tw:[&_label_>_span]:left-[11px]", "tw:[&_label_>_span]:text-[color:#62738c]",
    "tw:[&_label_>_span]:text-[1.1rem]", "tw:[&_label_>_span]:leading-[1]", "tw:[&_label_>_span]:[transform:translateY(-50%)]", "tw:[&_input]:w-[100%]",
    "tw:[&_input]:min-h-[38px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[17px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[38px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#d3dfed]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#d3dfed]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:#d3dfed]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:#d3dfed]", "tw:[&_input]:rounded-[7px]", "tw:[&_input]:text-[color:#21314d]", "tw:[&_input]:bg-[color:#fff]",
    "tw:[&_input]:[background-image:none]", "tw:[&_input]:[box-shadow:0_3px_10px_rgb(13_50_96_/_.025)]", "tw:[&_input]:[font:inherit]", "tw:[&_input]:text-[.78rem]",
    "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[38px]", "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[17px]",
    "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[17px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]",
    "tw:[&_select]:border-t-[color:#d3dfed]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#d3dfed]",
    "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:#d3dfed]", "tw:[&_select]:border-l-[length:1px]",
    "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#d3dfed]", "tw:[&_select]:rounded-[7px]", "tw:[&_select]:text-[color:#21314d]",
    "tw:[&_select]:bg-[color:#fff]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:[box-shadow:0_3px_10px_rgb(13_50_96_/_.025)]", "tw:[&_select]:[font:inherit]",
    "tw:[&_select]:text-[.78rem]",
  ].join(" "),
  "teacher_directory_list": [
    "teacher-directory-list", "tw:grid", "tw:gap-y-[0]", "tw:gap-x-[0]",
    "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dbe6f2]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dbe6f2]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dbe6f2]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dbe6f2]", "tw:rounded-[10px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[box-shadow:0_8px_21px_rgb(13_50_96_/_.035)]",
  ].join(" "),
  "teacher_directory_item": [
    "teacher-directory-item", "tw:grid", "tw:items-center", "tw:viewport-600:items-start",
    "tw:justify-between", "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:pt-[10px]",
    "tw:viewport-760:pt-[11px]", "tw:pr-[12px]", "tw:viewport-760:pr-[11px]", "tw:pb-[10px]",
    "tw:viewport-760:pb-[11px]", "tw:pl-[12px]", "tw:viewport-760:pl-[11px]", "tw:border-t-[length:0]",
    "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]",
    "tw:border-r-[color:currentColor]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e2eaf3]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[0]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:text-[color:inherit]", "tw:[text-decoration:none]",
    "tw:[box-shadow:none]", "tw:grid-cols-[42px_minmax(180px,_1fr)_auto_minmax(150px,_.5fr)_32px]", "tw:viewport-760:grid-cols-[38px_minmax(0,_1fr)_auto]", "tw:min-h-[68px]",
    "tw:viewport-760:min-h-[0]", "tw:hover:border-t-[color:#e2eaf3]", "tw:hover:border-r-[color:#e2eaf3]", "tw:hover:border-b-[color:#e2eaf3]",
    "tw:hover:border-l-[color:#e2eaf3]", "tw:hover:bg-[color:transparent]", "tw:hover:[background-image:linear-gradient(90deg,_#fff,_#f8fbff)]", "tw:hover:[box-shadow:none]",
    "tw:[&_>_div]:grid", "tw:[&_>_div]:gap-y-[3px]", "tw:[&_>_div]:gap-x-[3px]", "tw:[&_>_div:last-child]:flex",
    "tw:[&_>_div:last-child]:items-center", "tw:[&_>_div:last-child]:gap-y-[14px]", "tw:[&_>_div:last-child]:gap-x-[14px]", "tw:[&_>_div:last-child]:text-[color:#627590]",
    "tw:[&_>_div:last-child]:text-[.78rem]", "tw:[&_b]:text-[color:#1266a4]", "tw:viewport-600:flex-col", "tw:viewport-600:[&_>_div:last-child]:flex-wrap",
    "tw:[&:last-child]:border-b-[length:0]", "tw:[&:last-child]:[border-bottom-style:none]", "tw:[&:last-child]:border-b-[color:currentColor]",
  ].join(" "),
  "teacher_directory_avatar": [
    "teacher-directory-avatar", "tw:relative", "tw:grid", "tw:w-[38px]",
    "tw:h-[38px]", "tw:place-items-center", "tw:[align-self:center]", "tw:rounded-[50%]",
    "tw:text-[color:#125bc1]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_#edf4ff,_#dce9fb)]", "tw:text-[.76rem]",
    "tw:font-[850]", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:[&_i]:absolute",
    "tw:[&_i]:right-[1px]", "tw:[&_i]:bottom-[1px]", "tw:[&_i]:w-[16px]", "tw:viewport-760:[&_i]:w-[13px]",
    "tw:[&_i]:h-[16px]", "tw:viewport-760:[&_i]:h-[13px]", "tw:[&_i]:border-t-[length:2px]", "tw:[&_i]:[border-top-style:solid]",
    "tw:[&_i]:border-t-[color:#fff]", "tw:[&_i]:border-r-[length:2px]", "tw:[&_i]:[border-right-style:solid]", "tw:[&_i]:border-r-[color:#fff]",
    "tw:[&_i]:border-b-[length:2px]", "tw:[&_i]:[border-bottom-style:solid]", "tw:[&_i]:border-b-[color:#fff]", "tw:[&_i]:border-l-[length:2px]",
    "tw:[&_i]:[border-left-style:solid]", "tw:[&_i]:border-l-[color:#fff]", "tw:[&_i]:rounded-[50%]", "tw:[&_i]:bg-[color:#d7e0eb]",
    "tw:[&_i]:[background-image:none]", "tw:[&_i.is-active]:bg-[color:#12bc76]", "tw:[&_i.is-active]:[background-image:none]", "tw:[&_img]:w-[100%]",
    "tw:[&_img]:h-[100%]", "tw:[&_img]:[object-fit:cover]",
  ].join(" "),
  "teacher_directory_person": [
    "teacher-directory-person", "tw:grid!", "tw:[align-content:center]", "tw:gap-y-[3px]!",
    "tw:gap-x-[3px]!", "tw:min-w-[0]", "tw:[&_strong]:text-[color:#101d39]", "tw:[&_strong]:text-[.84rem]",
    "tw:[&_>_span]:text-[color:#60748f]", "tw:[&_>_span]:text-[.72rem]", "tw:[&_>_span]:[overflow-x:hidden]", "tw:[&_>_span]:[overflow-y:hidden]",
    "tw:[&_>_span]:text-ellipsis", "tw:[&_>_span]:whitespace-nowrap", "tw:[&_b]:text-[color:#135fc3]", "tw:[&_b]:text-[.9rem]",
  ].join(" "),
  "teacher_directory_status": [
    "teacher-directory-status", "is-active", "tw:inline-flex", "tw:[align-self:center]",
    "tw:[justify-self:center]", "tw:viewport-760:[justify-self:start]", "tw:min-w-[0]", "tw:justify-center",
    "tw:pt-[4px]", "tw:pr-[7px]", "tw:pb-[4px]", "tw:pl-[7px]",
    "tw:rounded-[999px]", "tw:text-[color:#6b7d91]", "tw:bg-[color:#f0f3f7]", "tw:[background-image:none]",
    "tw:text-[.7rem]", "tw:font-[700]", "tw:items-center", "tw:gap-y-[5px]",
    "tw:gap-x-[5px]", "tw:[&.is-active]:text-[color:#18764f]", "tw:[&.is-active]:bg-[color:#e8f8ef]", "tw:[&.is-active]:[background-image:none]",
    "tw:viewport-760:[grid-column:2]",
  ].join(" "),
  "teacher_directory_status_2": [
    "teacher-directory-status", "tw:inline-flex", "tw:[align-self:center]", "tw:[justify-self:center]",
    "tw:viewport-760:[justify-self:start]", "tw:min-w-[0]", "tw:justify-center", "tw:pt-[4px]",
    "tw:pr-[7px]", "tw:pb-[4px]", "tw:pl-[7px]", "tw:rounded-[999px]",
    "tw:text-[color:#6b7d91]", "tw:bg-[color:#f0f3f7]", "tw:[background-image:none]", "tw:text-[.7rem]",
    "tw:font-[700]", "tw:items-center", "tw:gap-y-[5px]", "tw:gap-x-[5px]",
    "tw:[&.is-active]:text-[color:#18764f]", "tw:[&.is-active]:bg-[color:#e8f8ef]", "tw:[&.is-active]:[background-image:none]", "tw:viewport-760:[grid-column:2]",
  ].join(" "),
  "teacher_directory_status_dot": [
    "teacher-directory-status-dot", "tw:w-[6px]", "tw:h-[6px]", "tw:rounded-[50%]",
    "tw:bg-[color:currentColor]", "tw:[background-image:none]",
  ].join(" "),
  "teacher_directory_metrics": [
    "teacher-directory-metrics", "tw:grid!", "tw:grid-cols-[repeat(2,_minmax(90px,_1fr))]", "tw:viewport-760:grid-cols-[auto_auto]",
    "tw:gap-y-[0]!", "tw:gap-x-[0]!", "tw:[align-self:center]", "tw:viewport-1160:[grid-column:3_/_5]",
    "tw:viewport-760:[grid-column:1_/_-1]", "tw:viewport-760:w-[auto]", "tw:viewport-760:mt-[0]", "tw:viewport-760:pt-[6px]",
    "tw:viewport-760:border-t-[length:1px]", "tw:viewport-760:[border-top-style:solid]", "tw:viewport-760:border-t-[color:#e3ebf3]", "tw:viewport-760:[justify-content:start]",
    "tw:viewport-760:mr-[0]", "tw:viewport-760:mb-[0]", "tw:viewport-760:ml-[0]", "tw:viewport-760:pr-[0]",
    "tw:viewport-760:pb-[0]", "tw:viewport-760:pl-[0]",
  ].join(" "),
  "teacher_directory_metric": [
    "teacher-directory-metric", "tw:grid", "tw:[justify-items:center]", "tw:gap-y-[5px]",
    "tw:gap-x-[5px]", "tw:pt-[0]", "tw:pr-[10px]", "tw:pb-[0]",
    "tw:pl-[10px]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#e1e9f2]",
    "tw:[&:last-child]:border-r-[length:0]", "tw:[&:last-child]:[border-right-style:none]", "tw:[&:last-child]:border-r-[color:currentColor]", "tw:[&_strong]:text-[color:#101d39]",
    "tw:[&_strong]:text-[.82rem]", "tw:[&_small]:text-[color:#60738e]", "tw:[&_small]:text-[.66rem]", "tw:[&_small]:whitespace-nowrap",
    "tw:[&:first-child_small::after]:[content:'_ativos']",
  ].join(" "),
  "teacher_directory_arrow": [
    "teacher-directory-arrow", "tw:grid", "tw:w-[30px]", "tw:h-[30px]",
    "tw:place-items-center", "tw:[align-self:center]", "tw:[justify-self:end]", "tw:border-t-[length:0]",
    "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]",
    "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[9px]",
    "tw:text-[color:#14233f]", "tw:text-[1.6rem]", "tw:font-[400]", "tw:leading-[1]",
    "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:viewport-1160:[grid-column:4]", "tw:viewport-760:[grid-column:3]",
    "tw:viewport-1160:[grid-row:1]", "tw:[&_.event-icon]:w-[16px]", "tw:[&_.event-icon]:h-[16px]",
  ].join(" "),
  "muted_teacher_directory_empty": [
    "muted", "teacher-directory-empty", "tw:mt-[0]", "tw:mr-[0]",
    "tw:mb-[0]", "tw:ml-[0]", "tw:text-[color:var(--muted)]", "tw:pt-[48px]",
    "tw:pr-[24px]", "tw:pb-[48px]", "tw:pl-[24px]", "tw:text-center",
  ].join(" "),
  "teacher_directory_footer": [
    "teacher-directory-footer", "tw:flex", "tw:items-center", "tw:justify-between",
    "tw:gap-y-[20px]", "tw:gap-x-[20px]", "tw:mt-[-14px]", "tw:pt-[13px]",
    "tw:pr-[16px]", "tw:pb-[13px]", "tw:pl-[16px]", "tw:border-t-[length:0]",
    "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#dbe6f2]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dbe6f2]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#dbe6f2]", "tw:rounded-[0_0_10px_10px]",
    "tw:text-[color:#5b708b]", "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[box-shadow:0_8px_21px_rgb(13_50_96_/_.035)]",
    "tw:text-[.76rem]", "tw:[&_>_div]:flex", "tw:[&_>_div]:items-center", "tw:[&_>_div]:gap-y-[18px]",
    "tw:viewport-760:[&_>_div]:gap-y-[8px]", "tw:[&_>_div]:gap-x-[18px]", "tw:viewport-760:[&_>_div]:gap-x-[8px]", "tw:[&_.button]:min-w-[30px]",
    "tw:[&_.button]:min-h-[30px]", "tw:[&_.button]:text-[.82rem]", "tw:[&_.button]:w-[30px]", "tw:[&_.button]:h-[30px]",
    "tw:[&_b]:grid", "tw:[&_b]:w-[30px]", "tw:[&_b]:h-[30px]", "tw:[&_b]:place-items-center",
    "tw:[&_b]:rounded-[10px]", "tw:[&_b]:text-[color:#1760bc]", "tw:[&_b]:bg-[color:#eaf2ff]", "tw:[&_b]:[background-image:none]",
    "tw:[&_b]:min-w-[30px]", "tw:[&_b]:min-h-[30px]", "tw:[&_b]:text-[.82rem]",
  ].join(" "),
} as const;
