import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "teacher_enrollment_form": [
    "teacher-enrollment-form", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)_auto]", "tw:viewport-600:grid-cols-[1fr]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:[align-items:end]", "tw:pt-[14px]",
    "tw:pr-[14px]", "tw:pb-[14px]", "tw:pl-[14px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#dbe6f0]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#dbe6f0]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dbe6f0]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#dbe6f0]", "tw:rounded-[12px]",
    "tw:bg-[color:#f8fbfe]", "tw:[background-image:none]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[4px]",
    "tw:[&_label]:gap-x-[4px]", "tw:[&_label]:text-[color:#425a78]", "tw:[&_label]:text-[.7rem]", "tw:[&_label]:font-[700]",
    "tw:[&_>_.button]:min-w-[106px]", "tw:[&_>_.button]:[grid-column:2]", "tw:viewport-600:[&_>_.button]:[grid-column:1]", "tw:[&_>_.button]:[justify-self:end]",
    "tw:[&_>_.button]:w-[auto]", "tw:viewport-600:[&_>_.button]:w-[100%]", "tw:[&_>_.button]:min-h-[38px]", "tw:[&_>_.button]:[padding-inline:14px]",
    "tw:[&_>_.button]:text-[.78rem]",
  ].join(" "),
  "teacher_enrollment_students": [
    "teacher-enrollment-students", "tw:grid-cols-[1fr]", "tw:gap-y-[14px]", "tw:gap-x-[14px]",
    "tw:pt-[0]", "tw:pr-[0]", "tw:pb-[0]", "tw:pl-[0]",
    "tw:border-t-[color:currentColor]", "tw:border-r-[color:currentColor]", "tw:border-b-[color:currentColor]", "tw:border-l-[color:currentColor]",
    "tw:rounded-[8px]", "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:border-t-[length:0]",
    "tw:[border-top-style:none]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-b-[length:0]",
    "tw:[border-bottom-style:none]", "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:[&_.teacher-enrollment-primary]:grid-cols-[minmax(170px,_.55fr)_minmax(260px,_1fr)]",
    "tw:viewport-760:[&_.teacher-enrollment-primary]:grid-cols-[1fr]", "tw:[&_.teacher-enrollment-primary]:gap-y-[12px]", "tw:[&_.teacher-enrollment-primary]:gap-x-[12px]", "tw:[&_.teacher-enrollment-financial]:grid-cols-[repeat(3,_minmax(0,_1fr))]",
    "tw:viewport-760:[&_.teacher-enrollment-financial]:grid-cols-[1fr]", "tw:[&_.teacher-enrollment-financial]:gap-y-[12px]", "tw:[&_.teacher-enrollment-financial]:gap-x-[12px]", "tw:[&_label]:text-[color:#64738d]",
    "tw:[&_label]:text-[.69rem]", "tw:[&_input]:min-h-[36px]", "tw:[&_input]:border-t-[color:#d3dfed]", "tw:[&_input]:border-r-[color:#d3dfed]",
    "tw:[&_input]:border-b-[color:#d3dfed]", "tw:[&_input]:border-l-[color:#d3dfed]", "tw:[&_input]:rounded-[7px]", "tw:[&_input]:text-[color:#1c2d49]",
    "tw:[&_input]:text-[.78rem]", "tw:[&_select]:min-h-[36px]", "tw:[&_select]:border-t-[color:#d3dfed]", "tw:[&_select]:border-r-[color:#d3dfed]",
    "tw:[&_select]:border-b-[color:#d3dfed]", "tw:[&_select]:border-l-[color:#d3dfed]", "tw:[&_select]:rounded-[7px]", "tw:[&_select]:text-[color:#1c2d49]",
    "tw:[&_select]:text-[.78rem]", "tw:[&_.teacher-client-search_input]:pl-[34px]", "tw:[&_.teacher-client-search::before]:absolute", "tw:[&_.teacher-client-search::before]:z-[1]",
    "tw:[&_.teacher-client-search::before]:top-[25px]", "tw:[&_.teacher-client-search::before]:left-[12px]", "tw:[&_.teacher-client-search::before]:text-[color:#58708d]", "tw:[&_.teacher-client-search::before]:[content:'⌕']",
    "tw:[&_.teacher-client-search::before]:text-[1rem]", "tw:[&_.teacher-client-search::before]:leading-[1]", "tw:[&_.teacher-client-search]:relative", "tw:[&_.teacher-client-search]:[grid-column:1_/_-1]",
    "tw:[&_>_.button]:[justify-self:end]", "tw:viewport-760:[&_>_.button]:[justify-self:stretch]", "tw:[&_>_.button]:min-h-[34px]", "tw:[&_>_.button]:[padding-inline:11px]",
    "tw:[&_>_.button]:border-t-[length:1px]", "tw:[&_>_.button]:[border-top-style:solid]", "tw:[&_>_.button]:border-t-[color:#2372e1]", "tw:[&_>_.button]:border-r-[length:1px]",
    "tw:[&_>_.button]:[border-right-style:solid]", "tw:[&_>_.button]:border-r-[color:#2372e1]", "tw:[&_>_.button]:border-b-[length:1px]", "tw:[&_>_.button]:[border-bottom-style:solid]",
    "tw:[&_>_.button]:border-b-[color:#2372e1]", "tw:[&_>_.button]:border-l-[length:1px]", "tw:[&_>_.button]:[border-left-style:solid]", "tw:[&_>_.button]:border-l-[color:#2372e1]",
    "tw:[&_>_.button]:rounded-[7px]", "tw:[&_>_.button]:text-[color:#1261d6]", "tw:[&_>_.button]:bg-[color:#fff]", "tw:[&_>_.button]:[background-image:none]",
    "tw:[&_>_.button]:[box-shadow:none]", "tw:[&_>_.button]:[grid-column:auto]", "tw:[&_>_.button]:text-[.74rem]", "tw:[&_>_.button]:min-w-[0]",
    "tw:[&_>_.button:hover]:text-[color:#fff]", "tw:[&_>_.button:hover]:bg-[color:#1768d6]", "tw:[&_>_.button:hover]:[background-image:none]", "tw:[&_>_.button::first-letter]:text-[1.1rem]",
    "tw:viewport-760:[&_>_.button]:w-[100%]", "tw:[&_>_.button:disabled]:border-t-[color:#c8d6e5]", "tw:[&_>_.button:disabled]:border-r-[color:#c8d6e5]", "tw:[&_>_.button:disabled]:border-b-[color:#c8d6e5]",
    "tw:[&_>_.button:disabled]:border-l-[color:#c8d6e5]", "tw:[&_>_.button:disabled]:text-[color:#8aa0b7]", "tw:[&_>_.button:disabled]:bg-[color:#edf2f7]", "tw:[&_>_.button:disabled]:[background-image:none]",
    "tw:[&_>_.button:disabled]:cursor-not-allowed",
  ].join(" "),
  "teacher_enrollment_primary": [
    "teacher-enrollment-primary", "tw:grid", "tw:grid-cols-[minmax(150px,_.7fr)_minmax(220px,_1.3fr)]", "tw:viewport-600:grid-cols-[1fr]",
    "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:min-w-[0]", "tw:[&_>_.teacher-client-search:only-child]:[grid-column:1_/_-1]",
  ].join(" "),
  "teacher_client_search": [
    "teacher-client-search", "tw:relative",
  ].join(" "),
  "teacher_client_options": [
    "teacher-client-options", "tw:absolute", "tw:z-[12]", "tw:top-[calc(100%_+_4px)]",
    "tw:left-[0]", "tw:right-[0]", "tw:max-h-[220px]", "tw:[overflow-x:auto]",
    "tw:[overflow-y:auto]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#cad8e8]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#cad8e8]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#cad8e8]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#cad8e8]", "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[box-shadow:0_12px_28px_rgb(15_37_66_/_.18)]",
    "tw:[&_button]:grid", "tw:[&_button]:w-[100%]", "tw:[&_button]:gap-y-[2px]", "tw:[&_button]:gap-x-[2px]",
    "tw:[&_button]:pt-[8px]", "tw:[&_button]:pr-[10px]", "tw:[&_button]:pb-[8px]", "tw:[&_button]:pl-[10px]",
    "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]", "tw:[&_button]:border-r-[length:0]",
    "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:1px]", "tw:[&_button]:[border-bottom-style:solid]",
    "tw:[&_button]:border-b-[color:#edf2f7]", "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]", "tw:[&_button]:border-l-[color:currentColor]",
    "tw:[&_button]:bg-[color:#fff]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:#173a62]", "tw:[&_button]:text-left",
    "tw:[&_button]:cursor-pointer", "tw:[&_button:hover]:bg-[color:#edf6ff]", "tw:[&_button:hover]:[background-image:none]", "tw:[&_span]:text-[color:#697d94]",
    "tw:[&_span]:text-[.72rem]",
  ].join(" "),
  "teacher_enrollment_financial": [
    "teacher-enrollment-financial", "tw:[grid-column:1_/_-1]", "tw:grid", "tw:grid-cols-[repeat(3,_minmax(0,_1fr))]",
    "tw:viewport-900:grid-cols-[1fr_1fr]", "tw:viewport-600:grid-cols-[1fr]", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
    "tw:[&_>_label]:min-w-[0]", "tw:[&_input]:w-[100%]", "tw:[&_input]:min-w-[0]", "tw:[&_select]:w-[100%]",
    "tw:[&_select]:min-w-[0]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "form_full": [
    "form-note", "form-full", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  "button_button_primary_button_small_teacher_insert_student_trigger": [
    "button", "button-primary", "button-small", "teacher-insert-student-trigger",
    "tw:inline-flex", "tw:items-center", "tw:justify-center", "tw:gap-y-[5px]",
    "tw:gap-x-[5px]", "tw:min-h-[32px]", "tw:pt-[6px]", "tw:pr-[10px]",
    "tw:pb-[6px]", "tw:pl-[10px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--brand)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--brand)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--brand)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--brand)]", "tw:rounded-[7px]", "tw:bg-[color:var(--brand)]",
    "tw:[background-image:none]", "tw:text-[color:#ffffff]", "tw:text-[.75rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]",
    "tw:hover:border-t-[color:var(--brand-strong)]", "tw:hover:border-r-[color:var(--brand-strong)]", "tw:hover:border-b-[color:var(--brand-strong)]", "tw:hover:border-l-[color:var(--brand-strong)]",
    "tw:hover:[transform:translateY(-1px)]", "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait",
    "tw:[&:active]:[transform:translateY(0)]", "tw:[&:active]:[box-shadow:none]", "tw:hover:bg-[color:var(--brand-strong)]", "tw:hover:[background-image:none]",
    "tw:font-[700]", "tw:[justify-self:start]", "tw:w-[fit-content]", "tw:min-w-[0]",
  ].join(" "),
  "teacher_student_enrollment_modal": [
    "teacher-student-enrollment-modal", "tw:fixed", "tw:z-[90]", "tw:top-[0]",
    "tw:right-[0]", "tw:bottom-[0]", "tw:left-[0]", "tw:grid",
    "tw:place-items-center", "tw:pt-[20px]", "tw:viewport-760:pt-[12px]", "tw:pr-[20px]",
    "tw:viewport-760:pr-[12px]", "tw:pb-[20px]", "tw:viewport-760:pb-[12px]", "tw:pl-[20px]",
    "tw:viewport-760:pl-[12px]", "tw:bg-[color:rgb(10_29_54_/_.34)]", "tw:[background-image:none]", "tw:[backdrop-filter:blur(3px)]",
    "tw:[&_>_section]:grid", "tw:[&_>_section]:gap-y-[16px]", "tw:[&_>_section]:gap-x-[16px]", "tw:[&_>_section]:w-[min(900px,_100%)]",
    "tw:[&_>_section]:max-h-[calc(100vh_-_40px)]", "tw:viewport-760:[&_>_section]:max-h-[calc(100vh_-_24px)]", "tw:[&_>_section]:[overflow-x:auto]", "tw:[&_>_section]:[overflow-y:auto]",
    "tw:[&_>_section]:pt-[20px]", "tw:viewport-760:[&_>_section]:pt-[16px]", "tw:[&_>_section]:pr-[22px]", "tw:viewport-760:[&_>_section]:pr-[16px]",
    "tw:[&_>_section]:pb-[20px]", "tw:viewport-760:[&_>_section]:pb-[16px]", "tw:[&_>_section]:pl-[22px]", "tw:viewport-760:[&_>_section]:pl-[16px]",
    "tw:[&_>_section]:border-t-[length:1px]", "tw:[&_>_section]:[border-top-style:solid]", "tw:[&_>_section]:border-t-[color:#d8e5f0]", "tw:[&_>_section]:border-r-[length:1px]",
    "tw:[&_>_section]:[border-right-style:solid]", "tw:[&_>_section]:border-r-[color:#d8e5f0]", "tw:[&_>_section]:border-b-[length:1px]", "tw:[&_>_section]:[border-bottom-style:solid]",
    "tw:[&_>_section]:border-b-[color:#d8e5f0]", "tw:[&_>_section]:border-l-[length:1px]", "tw:[&_>_section]:[border-left-style:solid]", "tw:[&_>_section]:border-l-[color:#d8e5f0]",
    "tw:[&_>_section]:rounded-[13px]", "tw:viewport-760:[&_>_section]:rounded-[12px]", "tw:[&_>_section]:bg-[color:#fff]", "tw:[&_>_section]:[background-image:none]",
    "tw:[&_>_section]:[box-shadow:0_22px_54px_rgb(12_33_61_/_.22)]", "tw:[&_>_section]:grid-cols-[minmax(0,_1fr)]", "tw:[&_header]:flex", "tw:[&_header]:items-start",
    "tw:[&_header]:justify-between", "tw:[&_header]:pb-[11px]", "tw:[&_header]:border-b-[length:1px]", "tw:[&_header]:[border-bottom-style:solid]",
    "tw:[&_header]:border-b-[color:#e4ecf3]", "tw:[&_h2]:mt-[3px]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]",
    "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[1.05rem]", "tw:[&_header_>_button]:w-[30px]", "tw:[&_header_>_button]:h-[30px]",
    "tw:[&_header_>_button]:border-t-[length:1px]", "tw:[&_header_>_button]:[border-top-style:solid]", "tw:[&_header_>_button]:border-t-[color:#d4e0ed]", "tw:[&_header_>_button]:border-r-[length:1px]",
    "tw:[&_header_>_button]:[border-right-style:solid]", "tw:[&_header_>_button]:border-r-[color:#d4e0ed]", "tw:[&_header_>_button]:border-b-[length:1px]", "tw:[&_header_>_button]:[border-bottom-style:solid]",
    "tw:[&_header_>_button]:border-b-[color:#d4e0ed]", "tw:[&_header_>_button]:border-l-[length:1px]", "tw:[&_header_>_button]:[border-left-style:solid]", "tw:[&_header_>_button]:border-l-[color:#d4e0ed]",
    "tw:[&_header_>_button]:rounded-[7px]", "tw:[&_header_>_button]:bg-[color:#fff]", "tw:[&_header_>_button]:[background-image:none]", "tw:[&_header_>_button]:text-[color:#42607e]",
    "tw:[&_header_>_button]:text-[1.1rem]", "tw:[&_header_>_button]:cursor-pointer", "tw:viewport-760:[align-items:end]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
} as const;
