import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "event_dashboard": [
    "event-dashboard", "tw:grid", "tw:gap-y-[24px]", "tw:gap-x-[24px]",
    "tw:pt-[6px]", "tw:pr-[0]", "tw:pb-[40px]", "tw:pl-[0]",
  ].join(" "),
  "event_operation_header": [
    "event-operation-header", "tw:flex", "tw:items-center", "tw:justify-between",
    "tw:gap-y-[24px]", "tw:gap-x-[24px]", "tw:pb-[20px]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dfe7f1]", "tw:min-h-[88px]", "tw:viewport-760:flex-col",
  ].join(" "),
  "event_operation_title": [
    "event-operation-title", "tw:[&_h1]:mt-[5px]", "tw:[&_h1]:mr-[0]", "tw:[&_h1]:mb-[8px]",
    "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[color:#0a2858]", "tw:[&_h1]:text-[clamp(2rem,_3vw,_2.7rem)]", "tw:[&_h1]:tracking-[-.055em]",
    "tw:[&_h1]:font-[750]", "tw:[&_.eyebrow]:text-[.76rem]", "tw:[&_.eyebrow]:tracking-[0]", "tw:[&_.eyebrow]:normal-case",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "event_breadcrumb": [
    "event-breadcrumb", "tw:flex", "tw:gap-y-[9px]", "tw:gap-x-[9px]",
    "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]", "tw:ml-[0]",
    "tw:text-[color:#7184a3]", "tw:text-[.82rem]", "tw:items-center", "tw:[&_a]:text-[color:var(--brand)]",
    "tw:[&_.event-icon]:text-[color:#8495b1]",
  ].join(" "),
  "event_operation_actions": [
    "event-operation-actions", "tw:flex", "tw:flex-wrap", "tw:justify-end",
    "tw:viewport-760:justify-start", "tw:gap-y-[9px]", "tw:gap-x-[9px]", "tw:items-center",
    "tw:[&_.section-actions]:contents", "tw:[&_.button]:min-h-[40px]", "tw:[&_.button]:[padding-inline:15px]", "tw:[&_.button]:border-t-[color:#cfdaea]",
    "tw:[&_.button]:border-r-[color:#cfdaea]", "tw:[&_.button]:border-b-[color:#cfdaea]", "tw:[&_.button]:border-l-[color:#cfdaea]", "tw:[&_.button]:[box-shadow:none]",
    "tw:[&_.button]:font-[700]", "tw:[&_.button]:pt-[0]", "tw:[&_.button]:pr-[15px]", "tw:[&_.button]:pb-[0]",
    "tw:[&_.button]:pl-[15px]", "tw:[&_.button]:rounded-[8px]", "tw:[&_.button]:text-[.8rem]", "tw:[&_.button]:leading-[1]",
    "tw:viewport-760:[&_.button]:[flex:1]", "tw:[&_.section-actions_.button]:min-h-[40px]", "tw:[&_.section-actions_.button]:pt-[0]", "tw:[&_.section-actions_.button]:pr-[15px]",
    "tw:[&_.section-actions_.button]:pb-[0]", "tw:[&_.section-actions_.button]:pl-[15px]", "tw:[&_.section-actions_.button]:rounded-[8px]", "tw:[&_.section-actions_.button]:text-[.8rem]",
    "tw:[&_.section-actions_.button]:font-[700]", "tw:[&_.section-actions_.button]:leading-[1]", "tw:[&_.button_.event-icon]:w-[16px]", "tw:[&_.button_.event-icon]:h-[16px]",
    "tw:[&_.button-danger]:border-t-[color:#d9302c]", "tw:[&_.button-danger]:border-r-[color:#d9302c]", "tw:[&_.button-danger]:border-b-[color:#d9302c]", "tw:[&_.button-danger]:border-l-[color:#d9302c]",
    "tw:[&_.button-danger]:bg-[color:#d9302c]", "tw:[&_.button-danger]:[background-image:none]", "tw:[&_.button-danger]:text-[color:#fff]",
  ].join(" "),
  "event_editing_badge": [
    "event-editing-badge", "tw:inline-flex", "tw:items-center", "tw:justify-center",
    "tw:gap-y-[5px]", "tw:gap-x-[5px]", "tw:min-h-[32px]", "tw:pt-[0]",
    "tw:pr-[12px]", "tw:pb-[0]", "tw:pl-[12px]", "tw:rounded-[8px]",
    "tw:bg-[color:#e8f1ff]", "tw:[background-image:none]", "tw:text-[color:#075bcc]", "tw:text-[.78rem]",
    "tw:font-[750]", "tw:[&_.event-icon]:text-[color:#1b72da]",
  ].join(" "),
  "button": sharedUtilities.button,
  "tournament_delete_action": [
    "tournament-delete-action", "tw:relative", "tw:inline-flex", "tw:[&_.safe-action-confirmation]:absolute",
    "tw:[&_.safe-action-confirmation]:z-[30]", "tw:[&_.safe-action-confirmation]:top-[calc(100%_+_8px)]", "tw:[&_.safe-action-confirmation]:right-[0]", "tw:viewport-600:[&_.safe-action-confirmation]:right-[auto]",
    "tw:[&_.safe-action-confirmation]:grid", "tw:[&_.safe-action-confirmation]:gap-y-[9px]", "tw:[&_.safe-action-confirmation]:gap-x-[9px]", "tw:[&_.safe-action-confirmation]:w-[min(360px,_calc(100vw_-_40px))]",
    "tw:[&_.safe-action-confirmation]:pt-[14px]", "tw:[&_.safe-action-confirmation]:pr-[14px]", "tw:[&_.safe-action-confirmation]:pb-[14px]", "tw:[&_.safe-action-confirmation]:pl-[14px]",
    "tw:[&_.safe-action-confirmation]:border-t-[length:1px]", "tw:[&_.safe-action-confirmation]:[border-top-style:solid]", "tw:[&_.safe-action-confirmation]:border-t-[color:#f0c9c4]", "tw:[&_.safe-action-confirmation]:border-r-[length:1px]",
    "tw:[&_.safe-action-confirmation]:[border-right-style:solid]", "tw:[&_.safe-action-confirmation]:border-r-[color:#f0c9c4]", "tw:[&_.safe-action-confirmation]:border-b-[length:1px]", "tw:[&_.safe-action-confirmation]:[border-bottom-style:solid]",
    "tw:[&_.safe-action-confirmation]:border-b-[color:#f0c9c4]", "tw:[&_.safe-action-confirmation]:border-l-[length:1px]", "tw:[&_.safe-action-confirmation]:[border-left-style:solid]", "tw:[&_.safe-action-confirmation]:border-l-[color:#f0c9c4]",
    "tw:[&_.safe-action-confirmation]:rounded-[10px]", "tw:[&_.safe-action-confirmation]:bg-[color:#fff]", "tw:[&_.safe-action-confirmation]:[background-image:none]", "tw:[&_.safe-action-confirmation]:[box-shadow:0_16px_36px_rgb(32_48_71_/_.2)]",
    "tw:[&_.safe-action-confirmation_.muted]:mt-[0]", "tw:[&_.safe-action-confirmation_.muted]:mr-[0]", "tw:[&_.safe-action-confirmation_.muted]:mb-[0]", "tw:[&_.safe-action-confirmation_.muted]:ml-[0]",
    "tw:[&_.safe-action-confirmation_.muted]:text-[.78rem]", "tw:[&_.safe-action-confirmation_.muted]:leading-[1.45]", "tw:[&_.safe-action-confirmation-actions]:flex", "tw:[&_.safe-action-confirmation-actions]:flex-wrap",
    "tw:[&_.safe-action-confirmation-actions]:gap-y-[7px]", "tw:[&_.safe-action-confirmation-actions]:gap-x-[7px]", "tw:[&_.safe-action-confirmation-actions_input]:min-w-[118px]", "tw:[&_.safe-action-confirmation-actions_input]:min-h-[34px]",
    "tw:viewport-600:[&_.safe-action-confirmation]:left-[0]",
  ].join(" "),
  "button_button_danger": sharedUtilities.buttonButtonDanger,
  "event_metrics_grid": [
    "event-metrics-grid", "tw:grid", "tw:grid-cols-[repeat(4,_minmax(0,_1fr))]", "tw:viewport-1080:grid-cols-[repeat(2,_minmax(0,_1fr))]",
    "tw:viewport-760:grid-cols-[1fr]", "tw:gap-y-[16px]", "tw:gap-x-[16px]",
  ].join(" "),
  "event_metric_card": [
    "event-metric-card", "tw:flex", "tw:min-h-[142px]", "tw:gap-y-[14px]",
    "tw:gap-x-[14px]", "tw:pt-[25px]", "tw:pr-[22px]", "tw:pb-[25px]",
    "tw:pl-[22px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#e5ebf4]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#e5ebf4]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e5ebf4]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#e5ebf4]", "tw:rounded-[14px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[box-shadow:0_8px_22px_rgba(19,_55,_104,_.065)]", "tw:[&_>_div]:grid", "tw:[&_>_div]:[align-content:start]", "tw:[&_>_div]:gap-y-[7px]",
    "tw:[&_>_div]:gap-x-[7px]", "tw:[&_small]:text-[color:#6e81a3]", "tw:[&_small]:text-[.66rem]", "tw:[&_small]:font-[800]",
    "tw:[&_small]:tracking-[.035em]", "tw:[&_small]:uppercase", "tw:[&_strong]:text-[color:#112b53]", "tw:[&_strong]:text-[1.34rem]",
    "tw:[&_strong]:tracking-[-.035em]", "tw:[&_strong]:font-[760]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#667b9f]", "tw:[&_p]:text-[.76rem]",
    "tw:[&_p]:leading-[1.45]",
  ].join(" "),
  "event_metric_icon": [
    "event-metric-icon", "tw:grid", "tw:[flex:0_0_48px]", "tw:w-[48px]",
    "tw:h-[48px]", "tw:place-items-center", "tw:rounded-[10px]", "tw:bg-[color:#eaf1ff]",
    "tw:[background-image:none]", "tw:text-[color:#0759d6]", "tw:text-[1.45rem]", "tw:font-[800]",
    "tw:[&_.event-icon]:w-[24px]", "tw:[&_.event-icon]:h-[24px]",
  ].join(" "),
  "event_metric_icon_event_metric_icon_success": [
    "event-metric-icon", "event-metric-icon-success", "tw:grid", "tw:[flex:0_0_48px]",
    "tw:w-[48px]", "tw:h-[48px]", "tw:place-items-center", "tw:rounded-[10px]",
    "tw:bg-[color:#e6faef]", "tw:[background-image:none]", "tw:text-[color:#009a4e]", "tw:text-[1.45rem]",
    "tw:font-[800]", "tw:[&_.event-icon]:w-[24px]", "tw:[&_.event-icon]:h-[24px]",
  ].join(" "),
  "event_metric_icon_event_metric_icon_purple": [
    "event-metric-icon", "event-metric-icon-purple", "tw:grid", "tw:[flex:0_0_48px]",
    "tw:w-[48px]", "tw:h-[48px]", "tw:place-items-center", "tw:rounded-[10px]",
    "tw:bg-[color:#f1ebff]", "tw:[background-image:none]", "tw:text-[color:#7845dd]", "tw:text-[1.45rem]",
    "tw:font-[800]", "tw:[&_.event-icon]:w-[24px]", "tw:[&_.event-icon]:h-[24px]",
  ].join(" "),
  "event_detail_grid": [
    "event-detail-grid", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)_318px]", "tw:viewport-1080:grid-cols-[1fr]",
    "tw:gap-y-[18px]", "tw:gap-x-[18px]", "tw:[align-items:start]",
  ].join(" "),
  "event_main_column": [
    "event-main-column", "tw:grid", "tw:gap-y-[18px]", "tw:gap-x-[18px]",
  ].join(" "),
  "section_card": [
    "section-card", "tournament-bonus-list", "tw:pt-[22px]", "tw:pr-[0]",
    "tw:pb-[22px]", "tw:pl-[0]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[0]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:[box-shadow:none]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "event_side_column": [
    "event-side-column", "tw:grid", "tw:gap-y-[18px]", "tw:gap-x-[18px]",
    "tw:viewport-1080:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-760:grid-cols-[1fr]",
  ].join(" "),
  "event_information": [
    "event-information", "tw:pt-[22px]", "tw:viewport-760:pt-[16px]", "tw:pr-[22px]",
    "tw:viewport-760:pr-[16px]", "tw:pb-[22px]", "tw:viewport-760:pb-[16px]", "tw:pl-[22px]",
    "tw:viewport-760:pl-[16px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#e3eaf3]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#e3eaf3]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e3eaf3]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#e3eaf3]", "tw:rounded-[14px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[box-shadow:0_8px_22px_rgba(19,_55,_104,_.055)]", "tw:[&_header]:flex", "tw:[&_header]:items-center", "tw:[&_header]:gap-y-[9px]",
    "tw:[&_header]:gap-x-[9px]", "tw:[&_header]:mb-[14px]", "tw:[&_header]:min-h-[24px]", "tw:[&_h2]:mt-[0]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#172e56]",
    "tw:[&_h2]:text-[.98rem]", "tw:[&_header_span]:text-[color:#0660dc]", "tw:[&_header_span]:text-[1.2rem]", "tw:[&_dl]:grid",
    "tw:[&_dl]:grid-cols-[1fr_1fr]", "tw:[&_dl]:gap-y-[18px]", "tw:[&_dl]:gap-x-[12px]", "tw:[&_dl]:mt-[0]",
    "tw:[&_dl]:mr-[0]", "tw:[&_dl]:mb-[0]", "tw:[&_dl]:ml-[0]", "tw:[&_dl]:border-t-[length:1px]",
    "tw:[&_dl]:[border-top-style:solid]", "tw:[&_dl]:border-t-[color:#e4ebf4]", "tw:[&_dl]:pt-[15px]", "tw:[&_dt]:text-[color:#7184a5]",
    "tw:[&_dt]:text-[.65rem]", "tw:[&_dd]:mt-[4px]", "tw:[&_dd]:mr-[0]", "tw:[&_dd]:mb-[0]",
    "tw:[&_dd]:ml-[0]", "tw:[&_dd]:text-[color:#183360]", "tw:[&_dd]:text-[.76rem]", "tw:[&_dd]:font-[750]",
    "tw:[&_header_>_.event-icon]:text-[color:#0964dc]",
  ].join(" "),
  "tournament_status_form": [
    "tournament-status-form", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)]", "tw:gap-y-[9px]",
    "tw:gap-x-[9px]", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[16px]",
    "tw:ml-[0]", "tw:pt-[12px]", "tw:pr-[12px]", "tw:pb-[12px]",
    "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dce6f3]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce6f3]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce6f3]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#dce6f3]", "tw:rounded-[10px]", "tw:bg-[color:#f8fbff]", "tw:[background-image:none]",
    "tw:[&_label]:grid", "tw:[&_label]:gap-y-[6px]", "tw:[&_label]:gap-x-[6px]", "tw:[&_label]:text-[color:#3a5278]",
    "tw:[&_label]:text-[.72rem]", "tw:[&_label]:font-[700]", "tw:[&_select]:min-w-[0]", "tw:[&_select]:w-[100%]",
    "tw:[&_select]:min-h-[38px]", "tw:[&_select]:text-[.8rem]", "tw:[&_.button]:[justify-self:start]", "tw:[&_.button]:min-h-[36px]",
    "tw:[&_.button]:whitespace-nowrap",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
} as const;
