/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "agenda_page": [
    "agenda-page", "tw:grid", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:min-w-[0]", "tw:w-[100%]", "tw:max-w-[none]", "tw:pt-[4px]",
    "tw:pr-[18px]", "tw:pb-[28px]", "tw:pl-[18px]", "tw:viewport-700:pr-[0]", "tw:viewport-700:pl-[0]",
  ].join(" "),
  "agenda_date_strip": [
    "agenda-date-strip", "tw:flex", "tw:items-stretch", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:pt-[8px]", "tw:pr-[8px]", "tw:pb-[8px]",
    "tw:pl-[8px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[14px]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]",
    "tw:[box-shadow:var(--shadow)]", "tw:viewport-700:flex-wrap", "tw:viewport-700:[overflow-x:visible]", "tw:[&_.agenda-online-settings-trigger]:w-[38px]", "tw:[&_.agenda-online-settings-trigger]:min-w-[38px]", "tw:[&_.agenda-online-settings-trigger]:h-[38px]",
    "tw:[&_.agenda-online-settings-trigger]:pt-[0]", "tw:[&_.agenda-online-settings-trigger]:pr-[0]", "tw:[&_.agenda-online-settings-trigger]:pb-[0]", "tw:[&_.agenda-online-settings-trigger]:pl-[0]",
    "tw:[&_.agenda-online-settings-trigger:hover]:[box-shadow:0_4px_10px_rgb(19_89_143_/_.25)]", "tw:[&_.agenda-online-settings-trigger:hover]:[transform:translateY(-1px)]",
  ].join(" "),
  "agenda_date_arrow": [
    "agenda-date-arrow", "tw:[transition:transform_150ms_var(--ease-standard),_background_150ms_var(--ease-standard),_box-shadow_150ms_var(--ease-standard)]", "tw:grid", "tw:place-items-center",
    "tw:min-w-[42px]", "tw:rounded-[var(--radius-control)]", "tw:text-[color:var(--muted)]", "tw:[text-decoration:none]",
    "tw:font-[700]", "tw:text-[2rem]", "tw:leading-[1]", "tw:hover:[transform:translateY(-1px)]",
    "tw:hover:bg-[color:#eaf4fd]", "tw:hover:[background-image:none]", "tw:hover:[box-shadow:inset_0_0_0_1px_#a9c9e6]",
  ].join(" "),
  "agenda_date_list": [
    "agenda-date-list", "tw:grid", "tw:grid-cols-[repeat(7,_minmax(54px,_1fr))]", "tw:[flex:1]",
    "tw:gap-y-[4px]", "tw:gap-x-[4px]", "tw:viewport-700:min-w-[0]", "tw:viewport-700:basis-[calc(100%_-_96px)]", "tw:viewport-700:grid-cols-[repeat(3,_minmax(0,_1fr))]",
    "tw:viewport-700:[&>a:nth-child(-n+2)]:hidden", "tw:viewport-700:[&>a:nth-child(n+6)]:hidden",
  ].join(" "),
  "agenda_date_item_agenda_date_item_active_agenda_date_item_centered": [
    "agenda-date-item", "agenda-date-item-active", "agenda-date-item-centered", "tw:[transition:transform_150ms_var(--ease-standard),_background_150ms_var(--ease-standard),_box-shadow_150ms_var(--ease-standard)]",
    "tw:grid", "tw:place-items-center", "tw:min-w-[42px]", "tw:rounded-[var(--radius-control)]",
    "tw:text-[color:#fff]", "tw:[text-decoration:none]", "tw:font-[700]", "tw:gap-y-[1px]",
    "tw:gap-x-[1px]", "tw:min-h-[52px]", "tw:pt-[5px]", "tw:pr-[10px]",
    "tw:pb-[5px]", "tw:pl-[10px]", "tw:uppercase", "tw:text-[.67rem]",
    "tw:hover:[transform:translateY(-1px)]", "tw:hover:bg-[color:#eaf4fd]", "tw:hover:[background-image:none]", "tw:hover:[box-shadow:inset_0_0_0_1px_#a9c9e6]",
    "tw:[&_strong]:text-[color:#fff]!", "tw:[&_strong]:text-[1.05rem]", "tw:bg-[color:#0f5f9f]!", "tw:[background-image:none]!",
    "tw:border-t-[length:2px]!", "tw:[border-top-style:solid]!", "tw:border-t-[color:#073d6a]!", "tw:border-r-[length:2px]!",
    "tw:[border-right-style:solid]!", "tw:border-r-[color:#073d6a]!", "tw:border-b-[length:2px]!", "tw:[border-bottom-style:solid]!",
    "tw:border-b-[color:#073d6a]!", "tw:border-l-[length:2px]!", "tw:[border-left-style:solid]!", "tw:border-l-[color:#073d6a]!",
    "tw:[box-shadow:0_0_0_2px_rgb(37_99_235_/_.22),_0_8px_18px_rgb(37_99_235_/_.28)]", "tw:[&_span]:text-[color:#fff]!", "tw:[transform:translateY(-2px)]",
  ].join(" "),
  "agenda_date_item": [
    "agenda-date-item", "tw:[transition:transform_150ms_var(--ease-standard),_background_150ms_var(--ease-standard),_box-shadow_150ms_var(--ease-standard)]", "tw:grid", "tw:place-items-center",
    "tw:min-w-[42px]", "tw:rounded-[var(--radius-control)]", "tw:text-[color:var(--muted)]", "tw:[text-decoration:none]",
    "tw:font-[700]", "tw:gap-y-[1px]", "tw:gap-x-[1px]", "tw:min-h-[52px]",
    "tw:pt-[5px]", "tw:pr-[10px]", "tw:pb-[5px]", "tw:pl-[10px]",
    "tw:uppercase", "tw:text-[.67rem]", "tw:hover:[transform:translateY(-1px)]", "tw:hover:bg-[color:#eaf4fd]",
    "tw:hover:[background-image:none]", "tw:hover:[box-shadow:inset_0_0_0_1px_#a9c9e6]", "tw:[&_strong]:text-[color:var(--ink)]", "tw:[&_strong]:text-[1.05rem]",
  ].join(" "),
  "agenda_today_link": [
    "agenda-today-link", "tw:[transition:transform_150ms_var(--ease-standard),_background_150ms_var(--ease-standard),_box-shadow_150ms_var(--ease-standard)]", "tw:grid", "tw:viewport-700:order-4",
    "tw:place-items-center", "tw:min-w-[42px]", "tw:rounded-[var(--radius-control)]", "tw:text-[color:var(--muted)]",
    "tw:[text-decoration:none]", "tw:font-[700]", "tw:pt-[0]", "tw:pr-[12px]",
    "tw:pb-[0]", "tw:pl-[12px]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]",
    "tw:text-[.78rem]", "tw:hover:[transform:translateY(-1px)]", "tw:hover:bg-[color:#eaf4fd]", "tw:hover:[background-image:none]",
    "tw:hover:[box-shadow:inset_0_0_0_1px_#a9c9e6]",
  ].join(" "),
  "agenda_calendar_controls": [
    "agenda-calendar-controls", "tw:flex", "tw:items-center", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:viewport-700:order-5", "tw:viewport-700:ml-auto",
  ].join(" "),
  "agenda_grid_caption": [
    "agenda-grid-caption", "tw:flex", "tw:justify-between", "tw:items-center",
    "tw:viewport-700:items-start", "tw:pt-[1px]", "tw:pr-[4px]", "tw:pb-[1px]",
    "tw:pl-[4px]", "tw:text-[color:var(--muted)]", "tw:text-[.8rem]", "tw:[&_strong]:text-[color:var(--ink)]",
    "tw:[&_strong]:[text-transform:capitalize]", "tw:viewport-700:flex-col", "tw:viewport-700:gap-y-[2px]", "tw:viewport-700:gap-x-[2px]",
  ].join(" "),
  "daily_court_grid_scroll": [
    "daily-court-grid-scroll", "tw:[overflow-x:auto]", "tw:[overflow-y:auto]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[12px]",
    "tw:[box-shadow:var(--shadow)]", "tw:max-w-[100%]", "tw:[overscroll-behavior-x:contain]",
  ].join(" "),
  "daily_court_grid": [
    "daily-court-grid", "tw:w-[100%]", "tw:min-w-[100%]", "tw:[border-collapse:separate]",
    "tw:[border-spacing:0]", "tw:[table-layout:fixed]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]",
    "tw:[&_th]:h-[25px]", "tw:[&_th]:min-h-[25px]", "tw:[&_th]:pt-[3px]", "tw:[&_th]:pr-[8px]",
    "tw:[&_th]:pb-[3px]", "tw:[&_th]:pl-[8px]", "tw:[&_th]:border-r-[length:1px]", "tw:[&_th]:[border-right-style:solid]",
    "tw:[&_th]:border-r-[color:var(--line)]", "tw:[&_th]:border-b-[length:1px]", "tw:[&_th]:[border-bottom-style:solid]", "tw:[&_th]:border-b-[color:var(--line)]",
    "tw:[&_th]:[vertical-align:top]", "tw:[&_td]:h-[25px]", "tw:[&_td]:min-h-[25px]", "tw:[&_td]:pt-[3px]",
    "tw:[&_td]:pr-[8px]", "tw:[&_td]:pb-[3px]", "tw:[&_td]:pl-[8px]", "tw:[&_td]:border-r-[length:1px]",
    "tw:[&_td]:[border-right-style:solid]", "tw:[&_td]:border-r-[color:var(--line)]", "tw:[&_td]:border-b-[length:1px]", "tw:[&_td]:[border-bottom-style:solid]",
    "tw:[&_td]:border-b-[color:var(--line)]", "tw:[&_td]:[vertical-align:top]", "tw:[&_tr:last-child_th]:border-b-[length:0]", "tw:[&_tr:last-child_th]:[border-bottom-style:none]",
    "tw:[&_tr:last-child_th]:border-b-[color:currentColor]", "tw:[&_tr:last-child_td]:border-b-[length:0]", "tw:[&_tr:last-child_td]:[border-bottom-style:none]", "tw:[&_tr:last-child_td]:border-b-[color:currentColor]",
    "tw:[&_th:last-child]:border-r-[length:0]", "tw:[&_th:last-child]:[border-right-style:none]", "tw:[&_th:last-child]:border-r-[color:currentColor]", "tw:[&_td:last-child]:border-r-[length:0]",
    "tw:[&_td:last-child]:[border-right-style:none]", "tw:[&_td:last-child]:border-r-[color:currentColor]", "tw:[&_thead_th]:sticky", "tw:[&_thead_th]:top-[0]",
    "tw:[&_thead_th]:z-[2]", "tw:[&_thead_th]:text-[color:var(--ink)]", "tw:[&_thead_th]:bg-[color:var(--panel)]", "tw:[&_thead_th]:[background-image:none]",
    "tw:[&_thead_th]:text-left", "tw:[&_thead_th]:pt-[7px]", "tw:[&_thead_th]:pr-[8px]", "tw:[&_thead_th]:pb-[7px]",
    "tw:[&_thead_th]:pl-[8px]", "tw:[&_thead_th]:text-[.78rem]", "tw:[&_thead_th:first-child]:w-[92px]", "tw:[&_tbody_>_tr_>_th]:text-[color:var(--muted)]",
    "tw:[&_tbody_>_tr_>_th]:bg-[color:var(--panel-muted)]", "tw:[&_tbody_>_tr_>_th]:[background-image:none]", "tw:[&_tbody_>_tr_>_th]:text-[.7rem]", "tw:[&_tbody_>_tr_>_th]:text-right",
    "tw:[&_tbody_>_tr_>_th]:w-[60px]", "tw:[&_tbody_>_tr_>_th]:pt-[3px]", "tw:[&_thead_th.daily-court-heading]:text-[color:#fff]", "tw:[&_thead_th.daily-court-heading]:bg-[color:var(--court-color)]",
    "tw:[&_thead_th.daily-court-heading]:[background-image:none]", "tw:[&_td_>_.agenda-slot-entry]:h-[100%]",
    "tw:viewport-700:[&_thead_th:first-child]:sticky", "tw:viewport-700:[&_thead_th:first-child]:left-[0]", "tw:viewport-700:[&_thead_th:first-child]:z-[4]",
    "tw:viewport-700:[&_tbody_>_tr_>_th]:sticky", "tw:viewport-700:[&_tbody_>_tr_>_th]:left-[0]", "tw:viewport-700:[&_tbody_>_tr_>_th]:z-[3]",
    "tw:viewport-700:[&_thead_th:first-child]:w-[64px]", "tw:viewport-700:[&_tbody_>_tr_>_th]:w-[64px]",
  ].join(" "),
  "daily_court_event_daily_court_event_online": [
    "daily-court-event", "daily-court-event-online", "tw:bg-[color:#e9faf0]!", "tw:[background-image:none]!",
    "tw:text-[color:#125b36]", "tw:min-h-[42px]", "tw:pt-[4px]!", "tw:pr-[4px]!",
    "tw:pb-[4px]!", "tw:pl-[4px]!", "tw:[&_strong]:block", "tw:[&_span]:block",
    "tw:[&_span]:mt-[4px]", "tw:[&_span]:text-[.72rem]", "tw:[&_span]:font-[700]", "tw:[&_span]:uppercase",
    "tw:[&_.agenda-slot-entry]:pr-[32px]", "tw:[&_.agenda-slot-trigger]:pr-[0]", "tw:[&_.agenda-slot-options]:top-[50%]", "tw:[&_.agenda-slot-options]:right-[7px]",
    "tw:[&_.agenda-slot-options]:[transform:translateY(-50%)]", "tw:[&_.agenda-slot-options-trigger]:grid", "tw:[&_.agenda-slot-options-trigger]:w-[22px]", "tw:[&_.agenda-slot-options-trigger]:h-[22px]",
    "tw:[&_.agenda-slot-options-trigger]:place-items-center", "tw:[&_.agenda-slot-options-trigger]:pt-[0]", "tw:[&_.agenda-slot-options-trigger]:pr-[0]", "tw:[&_.agenda-slot-options-trigger]:pb-[0]",
    "tw:[&_.agenda-slot-options-trigger]:pl-[0]", "tw:[&_.agenda-slot-options-trigger]:border-t-[length:0]", "tw:[&_.agenda-slot-options-trigger]:[border-top-style:none]", "tw:[&_.agenda-slot-options-trigger]:border-t-[color:currentColor]",
    "tw:[&_.agenda-slot-options-trigger]:border-r-[length:0]", "tw:[&_.agenda-slot-options-trigger]:[border-right-style:none]", "tw:[&_.agenda-slot-options-trigger]:border-r-[color:currentColor]", "tw:[&_.agenda-slot-options-trigger]:border-b-[length:0]",
    "tw:[&_.agenda-slot-options-trigger]:[border-bottom-style:none]", "tw:[&_.agenda-slot-options-trigger]:border-b-[color:currentColor]", "tw:[&_.agenda-slot-options-trigger]:border-l-[length:0]", "tw:[&_.agenda-slot-options-trigger]:[border-left-style:none]",
    "tw:[&_.agenda-slot-options-trigger]:border-l-[color:currentColor]", "tw:[&_.agenda-slot-options-trigger]:rounded-[6px]", "tw:[&_.agenda-slot-options-trigger]:bg-[color:rgb(255_255_255_/_.36)]", "tw:[&_.agenda-slot-options-trigger]:[background-image:none]",
    "tw:[&_.agenda-slot-options-trigger]:text-[color:currentColor]", "tw:[&_.agenda-slot-options-trigger]:[box-shadow:none]", "tw:[&_.agenda-slot-options-trigger:hover]:bg-[color:rgb(255_255_255_/_.72)]", "tw:[&_.agenda-slot-options-trigger:hover]:[background-image:none]",
    "tw:[&_.agenda-slot-options-trigger[aria-expanded=true]]:bg-[color:rgb(255_255_255_/_.72)]", "tw:[&_.agenda-slot-options-trigger[aria-expanded=true]]:[background-image:none]", "tw:[&_.agenda-slot-options-trigger_svg]:w-[15px]", "tw:[&_.agenda-slot-options-trigger_svg]:h-[15px]",
    "tw:[&_.agenda-slot-options-trigger_svg]:[fill:none]", "tw:[&_.agenda-slot-options-trigger_svg]:[stroke:currentColor]", "tw:[&_.agenda-slot-options-trigger_svg]:[stroke-linecap:round]", "tw:[&_.agenda-slot-options-trigger_svg]:[stroke-linejoin:round]",
    "tw:[&_.agenda-slot-options-trigger_svg]:[stroke-width:2]", "tw:[&_.agenda-slot-options-menu]:top-[calc(50%_+_17px)]", "tw:[&_.agenda-slot-options-menu]:right-[0]", "tw:[&_.agenda-slot-options-menu]:[transform:none]",
    "tw:relative", "tw:[&_.agenda-slot-trigger]:text-[color:#125b36]", "tw:[&_strong]:text-[color:#0c5731]", "tw:[&:has(.agenda-pending-confirmation)_.agenda-slot-entry]:pt-[0]",
    "tw:[&_.agenda-booking-event-card]:border-t-[color:#a8dfbf]", "tw:[&_.agenda-booking-event-card]:border-r-[color:#a8dfbf]", "tw:[&_.agenda-booking-event-card]:border-b-[color:#a8dfbf]", "tw:[&_.agenda-booking-event-card]:border-l-[color:#208a50]",
    "tw:[&_.agenda-booking-event-card]:bg-[color:transparent]", "tw:[&_.agenda-booking-event-card]:[background-image:linear-gradient(135deg,_#f6fff9,_#e1f7e9)]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:text-[color:#147342]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:bg-[color:#cff0da]",
    "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:[background-image:none]", "tw:[&_.agenda-booking-event-card_strong]:text-[color:#135635]",
  ].join(" "),
  "daily_court_event": [
    "daily-court-event", "tw:bg-[color:#edf5ff]", "tw:[background-image:none]", "tw:text-[color:var(--brand-strong)]",
    "tw:min-h-[42px]", "tw:pt-[4px]!", "tw:pr-[4px]!", "tw:pb-[4px]!",
    "tw:pl-[4px]!", "tw:[&_strong]:block", "tw:[&_span]:block", "tw:[&_span]:mt-[4px]",
    "tw:[&_span]:text-[.72rem]", "tw:[&_span]:font-[700]", "tw:[&_span]:uppercase", "tw:[&_.agenda-slot-entry]:pr-[32px]",
    "tw:[&_.agenda-slot-trigger]:pr-[0]", "tw:[&_.agenda-slot-options]:top-[50%]", "tw:[&_.agenda-slot-options]:right-[7px]", "tw:[&_.agenda-slot-options]:[transform:translateY(-50%)]",
    "tw:[&_.agenda-slot-options-trigger]:grid", "tw:[&_.agenda-slot-options-trigger]:w-[22px]", "tw:[&_.agenda-slot-options-trigger]:h-[22px]", "tw:[&_.agenda-slot-options-trigger]:place-items-center",
    "tw:[&_.agenda-slot-options-trigger]:pt-[0]", "tw:[&_.agenda-slot-options-trigger]:pr-[0]", "tw:[&_.agenda-slot-options-trigger]:pb-[0]", "tw:[&_.agenda-slot-options-trigger]:pl-[0]",
    "tw:[&_.agenda-slot-options-trigger]:border-t-[length:0]", "tw:[&_.agenda-slot-options-trigger]:[border-top-style:none]", "tw:[&_.agenda-slot-options-trigger]:border-t-[color:currentColor]", "tw:[&_.agenda-slot-options-trigger]:border-r-[length:0]",
    "tw:[&_.agenda-slot-options-trigger]:[border-right-style:none]", "tw:[&_.agenda-slot-options-trigger]:border-r-[color:currentColor]", "tw:[&_.agenda-slot-options-trigger]:border-b-[length:0]", "tw:[&_.agenda-slot-options-trigger]:[border-bottom-style:none]",
    "tw:[&_.agenda-slot-options-trigger]:border-b-[color:currentColor]", "tw:[&_.agenda-slot-options-trigger]:border-l-[length:0]", "tw:[&_.agenda-slot-options-trigger]:[border-left-style:none]", "tw:[&_.agenda-slot-options-trigger]:border-l-[color:currentColor]",
    "tw:[&_.agenda-slot-options-trigger]:rounded-[6px]", "tw:[&_.agenda-slot-options-trigger]:bg-[color:rgb(255_255_255_/_.36)]", "tw:[&_.agenda-slot-options-trigger]:[background-image:none]", "tw:[&_.agenda-slot-options-trigger]:text-[color:currentColor]",
    "tw:[&_.agenda-slot-options-trigger]:[box-shadow:none]", "tw:[&_.agenda-slot-options-trigger:hover]:bg-[color:rgb(255_255_255_/_.72)]", "tw:[&_.agenda-slot-options-trigger:hover]:[background-image:none]", "tw:[&_.agenda-slot-options-trigger[aria-expanded=true]]:bg-[color:rgb(255_255_255_/_.72)]",
    "tw:[&_.agenda-slot-options-trigger[aria-expanded=true]]:[background-image:none]", "tw:[&_.agenda-slot-options-trigger_svg]:w-[15px]", "tw:[&_.agenda-slot-options-trigger_svg]:h-[15px]", "tw:[&_.agenda-slot-options-trigger_svg]:[fill:none]",
    "tw:[&_.agenda-slot-options-trigger_svg]:[stroke:currentColor]", "tw:[&_.agenda-slot-options-trigger_svg]:[stroke-linecap:round]", "tw:[&_.agenda-slot-options-trigger_svg]:[stroke-linejoin:round]", "tw:[&_.agenda-slot-options-trigger_svg]:[stroke-width:2]",
    "tw:[&_.agenda-slot-options-menu]:top-[calc(50%_+_17px)]", "tw:[&_.agenda-slot-options-menu]:right-[0]", "tw:[&_.agenda-slot-options-menu]:[transform:none]",
  ].join(" "),
  "agenda_event_type_fixed_lesson": [
    "agenda-event-type-fixed-lesson", "tw:bg-[color:#e8f8ee]!", "tw:[background-image:none]!", "tw:[&_.agenda-booking-event-card]:border-t-[color:#a7ddb9]",
    "tw:[&_.agenda-booking-event-card]:border-r-[color:#a7ddb9]", "tw:[&_.agenda-booking-event-card]:border-b-[color:#a7ddb9]", "tw:[&_.agenda-booking-event-card]:border-l-[color:#259157]", "tw:[&_.agenda-booking-event-card]:bg-[color:transparent]",
    "tw:[&_.agenda-booking-event-card]:[background-image:linear-gradient(135deg,_#f4fff7,_#dcf4e5)]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:text-[color:#126638]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:bg-[color:#c9eed7]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:[background-image:none]",
    "tw:[&_.agenda-booking-event-card_strong]:text-[color:#104e2d]", "tw:[&_.agenda-booking-type-label]:text-[color:#357450]!",
  ].join(" "),
  "agenda_event_type_lesson": [
    "agenda-event-type-lesson", "tw:bg-[color:#fff3e8]!", "tw:[background-image:none]!", "tw:[&_.agenda-booking-event-card]:border-t-[color:#f2c48f]",
    "tw:[&_.agenda-booking-event-card]:border-r-[color:#f2c48f]", "tw:[&_.agenda-booking-event-card]:border-b-[color:#f2c48f]", "tw:[&_.agenda-booking-event-card]:border-l-[color:#e88925]", "tw:[&_.agenda-booking-event-card]:bg-[color:transparent]",
    "tw:[&_.agenda-booking-event-card]:[background-image:linear-gradient(135deg,_#fffaf4,_#ffead3)]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:text-[color:#a95710]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:bg-[color:#ffe0ba]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:[background-image:none]",
    "tw:[&_.agenda-booking-event-card_strong]:text-[color:#753d0c]", "tw:[&_.agenda-booking-type-label]:text-[color:#9a5a22]!",
  ].join(" "),
  "agenda_event_type_plan": [
    "agenda-event-type-plan", "tw:bg-[color:#2a3545]!", "tw:[background-image:none]!", "tw:[&_.agenda-booking-event-card]:border-t-[color:#53657a]",
    "tw:[&_.agenda-booking-event-card]:border-r-[color:#53657a]", "tw:[&_.agenda-booking-event-card]:border-b-[color:#53657a]", "tw:[&_.agenda-booking-event-card]:border-l-[color:#9dadbd]", "tw:[&_.agenda-booking-event-card]:bg-[color:transparent]",
    "tw:[&_.agenda-booking-event-card]:[background-image:linear-gradient(135deg,_#354354,_#26313f)]", "tw:[&_.agenda-booking-event-card]:[box-shadow:inset_0_1px_rgb(255_255_255_/_.1),_0_2px_5px_rgb(15_23_42_/_.2)]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:text-[color:#f3f7fb]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:bg-[color:rgb(255_255_255_/_.13)]",
    "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:[background-image:none]", "tw:[&_.agenda-booking-event-card_strong]:text-[color:#fff]!", "tw:[&_.agenda-booking-type-label]:text-[color:#fff]!", "tw:[&_.agenda-booking-type-label]:opacity-[.76]",
    "tw:[&_.agenda-slot-options-trigger]:text-[color:#fff]!",
  ].join(" "),
  "agenda_event_type_super12": [
    "agenda-event-type-super12", "tw:bg-[color:#fff0f0]!", "tw:[background-image:none]!", "tw:[&_.agenda-booking-event-card]:border-t-[color:#edaaaa]",
    "tw:[&_.agenda-booking-event-card]:border-r-[color:#edaaaa]", "tw:[&_.agenda-booking-event-card]:border-b-[color:#edaaaa]", "tw:[&_.agenda-booking-event-card]:border-l-[color:#cf3e3e]", "tw:[&_.agenda-booking-event-card]:bg-[color:transparent]",
    "tw:[&_.agenda-booking-event-card]:[background-image:linear-gradient(135deg,_#fff8f8,_#ffdedf)]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:text-[color:#a3232b]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:bg-[color:#ffcacc]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:[background-image:none]",
    "tw:[&_.agenda-booking-event-card_strong]:text-[color:#791b23]", "tw:[&_.agenda-booking-type-label]:text-[color:#a0474c]!",
  ].join(" "),
  "agenda_event_type_league": [
    "agenda-event-type-league", "tw:bg-[color:#fff9d9]!", "tw:[background-image:none]!", "tw:[&_.agenda-booking-event-card]:border-t-[color:#e5cf73]",
    "tw:[&_.agenda-booking-event-card]:border-r-[color:#e5cf73]", "tw:[&_.agenda-booking-event-card]:border-b-[color:#e5cf73]", "tw:[&_.agenda-booking-event-card]:border-l-[color:#c89f16]", "tw:[&_.agenda-booking-event-card]:bg-[color:transparent]",
    "tw:[&_.agenda-booking-event-card]:[background-image:linear-gradient(135deg,_#fffdf0,_#fff1ad)]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:text-[color:#825f00]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:bg-[color:#ffe98e]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:[background-image:none]",
    "tw:[&_.agenda-booking-event-card_strong]:text-[color:#5f4900]", "tw:[&_.agenda-booking-type-label]:text-[color:#866c16]!",
  ].join(" "),
  "agenda_event_type_booking": [
    "agenda-event-type-booking", "tw:bg-[color:#e9f3ff]!", "tw:[background-image:none]!", "tw:[&_.agenda-booking-event-card]:border-t-[color:#a9cfee]",
    "tw:[&_.agenda-booking-event-card]:border-r-[color:#a9cfee]", "tw:[&_.agenda-booking-event-card]:border-b-[color:#a9cfee]", "tw:[&_.agenda-booking-event-card]:border-l-[color:#2478c9]", "tw:[&_.agenda-booking-event-card]:bg-[color:transparent]",
    "tw:[&_.agenda-booking-event-card]:[background-image:linear-gradient(135deg,_#f6fbff,_#ddebfb)]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:text-[color:#155f9f]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:bg-[color:#cce4fa]", "tw:[&_.agenda-booking-event-card_>_.agenda-booking-type-icon]:[background-image:none]",
    "tw:[&_.agenda-booking-event-card_strong]:text-[color:#123f70]", "tw:[&_.agenda-booking-type-label]:text-[color:#41709e]!",
  ].join(" "),
  "agenda_event_content": [
    "agenda-event-content", "tw:relative", "tw:min-h-[30px]", "tw:[&:has(.agenda-slot-options)_.agenda-slot-confirmation-indicator]:right-[23px]",
  ].join(" "),
  "agenda_booking_event_card": [
    "agenda-booking-event-card", "tw:relative", "tw:grid", "tw:grid-cols-[18px_minmax(0,_1fr)]",
    "tw:[align-content:start]", "tw:gap-y-[2px]", "tw:gap-x-[7px]", "tw:h-[100%]",
    "tw:min-h-[42px]", "tw:[box-sizing:border-box]", "tw:pt-[7px]", "tw:pr-[8px]",
    "tw:pb-[7px]", "tw:pl-[7px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#bcd8f2]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#bcd8f2]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#bcd8f2]", "tw:border-l-[length:3px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#2374bd]", "tw:rounded-[7px]", "tw:bg-[color:transparent]",
    "tw:[background-image:linear-gradient(135deg,_#f7fbff,_#e5f1fc)]", "tw:[box-shadow:inset_0_1px_rgb(255_255_255_/_.8),_0_2px_5px_rgb(30_86_137_/_.08)]", "tw:text-left", "tw:[&_>_.agenda-booking-type-icon]:w-[18px]",
    "tw:[&_>_.agenda-booking-type-icon]:h-[18px]", "tw:[&_>_.agenda-booking-type-icon]:mt-[1px]", "tw:[&_>_.agenda-booking-type-icon]:mr-[0]", "tw:[&_>_.agenda-booking-type-icon]:mb-[0]",
    "tw:[&_>_.agenda-booking-type-icon]:ml-[0]", "tw:[&_>_.agenda-booking-type-icon]:pt-[2px]", "tw:[&_>_.agenda-booking-type-icon]:pr-[2px]", "tw:[&_>_.agenda-booking-type-icon]:pb-[2px]",
    "tw:[&_>_.agenda-booking-type-icon]:pl-[2px]", "tw:[&_>_.agenda-booking-type-icon]:[box-sizing:border-box]", "tw:[&_>_.agenda-booking-type-icon]:rounded-[5px]", "tw:[&_>_.agenda-booking-type-icon]:text-[color:#216aa8]",
    "tw:[&_>_.agenda-booking-type-icon]:bg-[color:#d5e9fa]", "tw:[&_>_.agenda-booking-type-icon]:[background-image:none]", "tw:[&_>_div]:grid", "tw:[&_>_div]:min-w-[0]",
    "tw:[&_>_div]:gap-y-[2px]", "tw:[&_>_div]:gap-x-[2px]", "tw:[&_strong]:[overflow-x:hidden]", "tw:[&_strong]:[overflow-y:hidden]",
    "tw:[&_strong]:text-[color:#123e70]", "tw:[&_strong]:text-[.77rem]", "tw:[&_strong]:font-[850]", "tw:[&_strong]:leading-[1.15]",
    "tw:[&_strong]:text-ellipsis", "tw:[&_strong]:whitespace-nowrap", "tw:[&_.agenda-booking-type-label]:block", "tw:[&_.agenda-booking-type-label]:mt-[0]",
    "tw:[&_.agenda-booking-type-label]:mr-[0]", "tw:[&_.agenda-booking-type-label]:mb-[0]", "tw:[&_.agenda-booking-type-label]:ml-[0]", "tw:[&_.agenda-booking-type-label]:text-[color:#4d7295]!",
    "tw:[&_.agenda-booking-type-label]:text-[.61rem]!", "tw:[&_.agenda-booking-type-label]:font-[750]", "tw:[&_.agenda-booking-type-label]:tracking-[.035em]", "tw:[&_.agenda-booking-type-label]:uppercase",
    "tw:[&_.agenda-payment-indicator]:absolute", "tw:[&_.agenda-payment-indicator]:right-[7px]", "tw:[&_.agenda-payment-indicator]:bottom-[7px]", "tw:[&_.agenda-payment-indicator]:w-[15px]",
    "tw:[&_.agenda-payment-indicator]:h-[15px]", "tw:[&_.agenda-payment-indicator]:mt-[0]", "tw:[&_.agenda-payment-indicator]:mr-[0]", "tw:[&_.agenda-payment-indicator]:mb-[0]",
    "tw:[&_.agenda-payment-indicator]:ml-[0]", "tw:[&_.agenda-payment-indicator]:rounded-[50%]", "tw:[&_.agenda-payment-indicator]:bg-[color:#1b9154]", "tw:[&_.agenda-payment-indicator]:[background-image:none]",
    "tw:[&_.agenda-payment-indicator]:text-[color:#fff]", "tw:[&_.agenda-payment-indicator]:text-[.58rem]", "tw:[&_.agenda-payment-indicator]:leading-[15px]", "tw:[&_.agenda-payment-indicator]:text-center",
    "tw:[&_.agenda-pending-confirmation]:mt-[1px]", "tw:[&_.agenda-pending-confirmation]:mr-[0]", "tw:[&_.agenda-pending-confirmation]:mb-[0]", "tw:[&_.agenda-pending-confirmation]:ml-[0]",
    "tw:[&_.agenda-pending-confirmation]:text-[color:#997010]", "tw:[&_.agenda-pending-confirmation]:text-[.55rem]",
  ].join(" "),
  "agenda_booking_type_icon": [
    "agenda-booking-type-icon", "tw:[display:inline-grid]", "tw:w-[15px]", "tw:h-[15px]",
    "tw:mr-[4px]", "tw:place-items-center", "tw:text-[color:#355b83]", "tw:text-[.62rem]",
    "tw:font-[850]", "tw:leading-[1]", "tw:[vertical-align:middle]", "tw:[&_svg]:w-[15px]",
    "tw:[&_svg]:h-[15px]", "tw:[&_svg]:[fill:none]", "tw:[&_svg]:[stroke:currentColor]", "tw:[&_svg]:[stroke-linecap:round]",
    "tw:[&_svg]:[stroke-linejoin:round]", "tw:[&_svg]:[stroke-width:1.9]",
  ].join(" "),
  "agenda_booking_type_label": [
    "agenda-booking-type-label", "tw:text-[color:#4e6b89]!", "tw:text-[.62rem]!", "tw:font-[750]!",
    "tw:tracking-[.02em]", "tw:normal-case!",
  ].join(" "),
  "agenda_pending_confirmation": [
    "agenda-pending-confirmation", "tw:static", "tw:top-[1px]", "tw:left-[0]",
    "tw:inline-flex", "tw:items-center", "tw:min-h-[15px]", "tw:pt-[0]",
    "tw:pr-[0]", "tw:pb-[0]", "tw:pl-[0]", "tw:border-t-[length:0]",
    "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]",
    "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[4px]",
    "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:text-[color:#8b5d12]", "tw:text-[.58rem]",
    "tw:font-[700]", "tw:leading-[1]", "tw:tracking-[0]", "tw:whitespace-nowrap",
    "tw:ml-[6px]", "tw:[&_i]:mr-[2px]", "tw:[&_i]:not-italic",
  ].join(" "),
  "agenda_payment_indicator": [
    "agenda-payment-indicator", "tw:inline-flex", "tw:items-center", "tw:justify-center",
    "tw:min-w-[15px]", "tw:h-[15px]", "tw:ml-[4px]", "tw:rounded-[50%]",
    "tw:bg-[color:#1f9d55]", "tw:[background-image:none]", "tw:text-[color:#fff]", "tw:text-[.68rem]",
    "tw:font-[900]", "tw:leading-[1]", "tw:[vertical-align:1px]",
  ].join(" "),
  "daily_court_unavailable": [
    "daily-court-unavailable", "tw:[&_span]:block", "tw:[&_span]:text-[.67rem]", "tw:text-[color:#9aa3af]",
    "tw:bg-[color:#f5f6f8]", "tw:[background-image:none]",
  ].join(" "),
  "daily_court_available": [
    "daily-court-available", "tw:bg-[color:#f5fbf7]", "tw:[background-image:none]", "tw:text-[color:#23633c]",
    "tw:pt-[1px]!", "tw:pr-[6px]!", "tw:pb-[1px]!", "tw:pl-[6px]!",
    "tw:[&_strong]:block", "tw:[&_strong]:text-[.68rem]", "tw:[&_span]:block", "tw:[&_span]:mt-[0]",
    "tw:[&_span]:text-[.58rem]",
  ].join(" "),
  "agenda_empty": [
    "agenda-empty", "tw:grid", "tw:[justify-items:start]", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:pt-[24px]", "tw:pr-[24px]", "tw:pb-[24px]",
    "tw:pl-[24px]", "tw:border-t-[length:1px]", "tw:[border-top-style:dashed]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:dashed]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:dashed]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:dashed]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[14px]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]",
    "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]",
    "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
  ].join(" "),
} as const;
