import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "stack_md_workspace_page_stock_balance_page": [
    "stack-md", "workspace-page", "stock-balance-page", "tw:grid",
    "tw:gap-y-[24px]", "tw:viewport-720:gap-y-[18px]", "tw:gap-x-[24px]", "tw:viewport-720:gap-x-[18px]",
    "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]", "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]",
    "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]", "tw:pt-[5px]",
    "tw:pr-[0]", "tw:pb-[44px]", "tw:pl-[0]", "tw:[&_.page-header]:pt-[4px]",
    "tw:[&_.page-header]:pr-[0]", "tw:[&_.page-header]:pb-[20px]", "tw:[&_.page-header]:pl-[0]", "tw:[&_.page-header]:border-b-[length:1px]",
    "tw:[&_.page-header]:[border-bottom-style:solid]", "tw:[&_.page-header]:border-b-[color:#dfe7f1]", "tw:[&_.page-header_h1]:text-[color:#102b56]", "tw:[&_.page-header_h1]:text-[clamp(1.75rem,_2.3vw,_2.25rem)]",
    "tw:[&_.page-header_h1]:tracking-[-.045em]", "tw:[&_.stats-grid]:gap-y-[16px]", "tw:[&_.stats-grid]:gap-x-[16px]", "tw:[&_.stat-card]:pt-[20px]",
    "tw:[&_.stat-card]:pr-[20px]", "tw:[&_.stat-card]:pb-[20px]", "tw:[&_.stat-card]:pl-[20px]", "tw:[&_.stat-card]:border-t-[length:1px]",
    "tw:[&_.stat-card]:[border-top-style:solid]", "tw:[&_.stat-card]:border-t-[color:#e2e9f3]", "tw:[&_.stat-card]:border-r-[length:1px]", "tw:[&_.stat-card]:[border-right-style:solid]",
    "tw:[&_.stat-card]:border-r-[color:#e2e9f3]", "tw:[&_.stat-card]:border-b-[length:1px]", "tw:[&_.stat-card]:[border-bottom-style:solid]", "tw:[&_.stat-card]:border-b-[color:#e2e9f3]",
    "tw:[&_.stat-card]:border-l-[length:1px]", "tw:[&_.stat-card]:[border-left-style:solid]", "tw:[&_.stat-card]:border-l-[color:#e2e9f3]", "tw:[&_.stat-card]:rounded-[14px]",
    "tw:[&_.stat-card]:bg-[color:#fff]", "tw:[&_.stat-card]:[background-image:none]", "tw:[&_.stat-card]:[box-shadow:0_8px_22px_rgba(19,_55,_104,_.06)]", "tw:[&_.dashboard-grid]:gap-y-[18px]",
    "tw:[&_.dashboard-grid]:gap-x-[18px]", "tw:[&_.section-card]:pt-[21px]", "tw:viewport-720:[&_.section-card]:pt-[16px]", "tw:[&_.section-card]:pr-[21px]",
    "tw:viewport-720:[&_.section-card]:pr-[16px]", "tw:[&_.section-card]:pb-[21px]", "tw:viewport-720:[&_.section-card]:pb-[16px]", "tw:[&_.section-card]:pl-[21px]",
    "tw:viewport-720:[&_.section-card]:pl-[16px]", "tw:[&_.section-card]:border-t-[length:1px]", "tw:[&_.section-card]:[border-top-style:solid]", "tw:[&_.section-card]:border-t-[color:#e2e9f3]",
    "tw:[&_.section-card]:border-r-[length:1px]", "tw:[&_.section-card]:[border-right-style:solid]", "tw:[&_.section-card]:border-r-[color:#e2e9f3]", "tw:[&_.section-card]:border-b-[length:1px]",
    "tw:[&_.section-card]:[border-bottom-style:solid]", "tw:[&_.section-card]:border-b-[color:#e2e9f3]", "tw:[&_.section-card]:border-l-[length:1px]", "tw:[&_.section-card]:[border-left-style:solid]",
    "tw:[&_.section-card]:border-l-[color:#e2e9f3]", "tw:[&_.section-card]:rounded-[14px]", "tw:[&_.section-card]:bg-[color:#fff]", "tw:[&_.section-card]:[background-image:none]",
    "tw:[&_.section-card]:[box-shadow:0_8px_22px_rgba(19,_55,_104,_.05)]", "tw:[&_.section-card_+_.section-card]:border-t-[length:1px]", "tw:[&_.section-card_+_.section-card]:[border-top-style:solid]", "tw:[&_.section-card_+_.section-card]:border-t-[color:#e2e9f3]",
    "tw:max-w-[1260px]", "tw:[&_.page-header]:items-end", "tw:viewport-680:[&_.page-header]:items-start",
  ].join(" "),
  "sr_only": sharedUtilities.srOnly,
  "page_header": sharedUtilities.pageHeader,
  "button": sharedUtilities.button,
  "stock_balance_form": [
    "stock-balance-form", "tw:grid", "tw:gap-y-[18px]", "tw:gap-x-[18px]",
  ].join(" "),
  "field_stock_balance_reason": [
    "field", "stock-balance-reason", "tw:grid", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]", "tw:[&_input]:w-[100%]",
    "tw:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[14px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:text-[color:var(--text)]", "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[44px]",
    "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[14px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:var(--line)]",
    "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:var(--text)]",
    "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_input:focus]:[transform:translateY(-1px)]",
    "tw:[&_select:focus]:[outline:none]", "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]", "tw:[&_input[type=file]]:pt-[10px]",
    "tw:[&_input[type=file]]:pr-[14px]", "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]", "tw:[&_input[type=checkbox]]:w-[auto]",
    "tw:[&_input[type=checkbox]]:min-h-[auto]", "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]", "tw:[&_input[type=checkbox]]:pb-[0]",
    "tw:[&_input[type=checkbox]]:pl-[0]", "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]", "tw:[&_input[type=radio]]:pt-[0]",
    "tw:[&_input[type=radio]]:pr-[0]", "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]", "tw:max-w-[430px]",
  ].join(" "),
  "stock_balance_table": [
    "stock-balance-table", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#dbe5ef]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#dbe5ef]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dbe5ef]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#dbe5ef]", "tw:rounded-[11px]",
  ].join(" "),
  "stock_balance_row_stock_balance_head": [
    "stock-balance-row", "stock-balance-head", "tw:grid", "tw:grid-cols-[minmax(190px,_1.5fr)_minmax(90px,_.45fr)_minmax(110px,_.55fr)_minmax(160px,_.8fr)]",
    "tw:viewport-680:grid-cols-[minmax(130px,_1fr)_54px_minmax(105px,_.7fr)]", "tw:gap-y-[16px]", "tw:viewport-680:gap-y-[9px]", "tw:gap-x-[16px]",
    "tw:viewport-680:gap-x-[9px]", "tw:items-center", "tw:min-h-[38px]", "tw:pt-[10px]",
    "tw:viewport-680:pt-[9px]", "tw:pr-[14px]", "tw:viewport-680:pr-[9px]", "tw:pb-[10px]",
    "tw:viewport-680:pb-[9px]", "tw:pl-[14px]", "tw:viewport-680:pl-[9px]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e6edf4]", "tw:text-[color:#60758e]", "tw:text-[.67rem]",
    "tw:[&:last-child]:border-b-[length:0]", "tw:[&:last-child]:[border-bottom-style:none]", "tw:[&:last-child]:border-b-[color:currentColor]", "tw:[&_>_span:first-child]:grid",
    "tw:[&_>_span:first-child]:gap-y-[2px]", "tw:[&_>_span:first-child]:gap-x-[2px]", "tw:[&_>_span:first-child]:min-w-[0]", "tw:[&_strong]:[overflow-x:hidden]",
    "tw:[&_strong]:[overflow-y:hidden]", "tw:[&_strong]:text-[color:#162c49]", "tw:[&_strong]:text-[.82rem]", "tw:[&_strong]:text-ellipsis",
    "tw:[&_strong]:whitespace-nowrap", "tw:[&_small]:text-[color:#71839a]", "tw:[&_small]:text-[.7rem]", "tw:[&_b]:text-[color:#123f70]",
    "tw:[&_b]:text-[.88rem]", "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[36px]", "tw:viewport-680:[&_input]:min-h-[34px]",
    "tw:viewport-680:[&_>_span:nth-child(3)]:hidden", "tw:[padding-block:8px]", "tw:bg-[color:#f5f8fc]", "tw:[background-image:none]",
    "tw:font-[800]", "tw:tracking-[.035em]", "tw:uppercase", "tw:viewport-680:[&_span:nth-child(3)]:hidden",
  ].join(" "),
  "stock_balance_row": [
    "stock-balance-row", "tw:grid", "tw:grid-cols-[minmax(190px,_1.5fr)_minmax(90px,_.45fr)_minmax(110px,_.55fr)_minmax(160px,_.8fr)]", "tw:viewport-680:grid-cols-[minmax(130px,_1fr)_54px_minmax(105px,_.7fr)]",
    "tw:gap-y-[16px]", "tw:viewport-680:gap-y-[9px]", "tw:gap-x-[16px]", "tw:viewport-680:gap-x-[9px]",
    "tw:items-center", "tw:min-h-[58px]", "tw:pt-[10px]", "tw:viewport-680:pt-[9px]",
    "tw:pr-[14px]", "tw:viewport-680:pr-[9px]", "tw:pb-[10px]", "tw:viewport-680:pb-[9px]",
    "tw:pl-[14px]", "tw:viewport-680:pl-[9px]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#e6edf4]", "tw:text-[color:#36506e]", "tw:text-[.8rem]", "tw:[&:last-child]:border-b-[length:0]",
    "tw:[&:last-child]:[border-bottom-style:none]", "tw:[&:last-child]:border-b-[color:currentColor]", "tw:[&_>_span:first-child]:grid", "tw:[&_>_span:first-child]:gap-y-[2px]",
    "tw:[&_>_span:first-child]:gap-x-[2px]", "tw:[&_>_span:first-child]:min-w-[0]", "tw:[&_strong]:[overflow-x:hidden]", "tw:[&_strong]:[overflow-y:hidden]",
    "tw:[&_strong]:text-[color:#162c49]", "tw:[&_strong]:text-[.82rem]", "tw:[&_strong]:text-ellipsis", "tw:[&_strong]:whitespace-nowrap",
    "tw:[&_small]:text-[color:#71839a]", "tw:[&_small]:text-[.7rem]", "tw:[&_b]:text-[color:#123f70]", "tw:[&_b]:text-[.88rem]",
    "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[36px]", "tw:viewport-680:[&_input]:min-h-[34px]", "tw:viewport-680:[&_>_span:nth-child(3)]:hidden",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "stock_balance_actions": [
    "stock-balance-actions", "tw:flex", "tw:justify-end",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "stock_balance_report": [
    "stock-balance-report", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:[&_article]:flex", "tw:[&_article]:items-center", "tw:[&_article]:justify-between", "tw:[&_article]:gap-y-[16px]",
    "tw:[&_article]:gap-x-[16px]", "tw:[&_article]:pt-[11px]", "tw:[&_article]:pr-[13px]", "tw:[&_article]:pb-[11px]",
    "tw:[&_article]:pl-[13px]", "tw:[&_article]:border-t-[length:1px]", "tw:[&_article]:[border-top-style:solid]", "tw:[&_article]:border-t-[color:#dce6ef]",
    "tw:[&_article]:border-r-[length:1px]", "tw:[&_article]:[border-right-style:solid]", "tw:[&_article]:border-r-[color:#dce6ef]", "tw:[&_article]:border-b-[length:1px]",
    "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#dce6ef]", "tw:[&_article]:border-l-[length:3px]", "tw:[&_article]:[border-left-style:solid]",
    "tw:[&_article]:border-l-[color:#7f9ab6]", "tw:[&_article]:rounded-[8px]", "tw:[&_article]:bg-[color:#fbfdff]", "tw:[&_article]:[background-image:none]",
    "tw:[&_article.is-loss]:border-l-[color:#cf5b4e]", "tw:[&_article.is-loss]:bg-[color:#fffafa]", "tw:[&_article.is-loss]:[background-image:none]", "tw:[&_article.is-surplus]:border-l-[color:#1c9b70]",
    "tw:[&_article.is-surplus]:bg-[color:#f7fdf9]", "tw:[&_article.is-surplus]:[background-image:none]", "tw:[&_article_>_div]:grid", "tw:[&_article_>_div]:min-w-[0]",
    "tw:[&_article_>_div]:gap-y-[2px]", "tw:[&_article_>_div]:gap-x-[2px]", "tw:[&_strong]:text-[color:#193553]", "tw:[&_strong]:text-[.82rem]",
    "tw:[&_span]:text-[color:#6c8096]", "tw:[&_span]:text-[.7rem]", "tw:[&_small]:text-[color:#6c8096]", "tw:[&_small]:text-[.7rem]",
    "tw:[&_small]:[overflow-x:hidden]", "tw:[&_small]:[overflow-y:hidden]", "tw:[&_small]:text-ellipsis", "tw:[&_small]:whitespace-nowrap",
    "tw:viewport-680:[&_small]:[white-space:normal]", "tw:[&_b]:min-w-[42px]", "tw:[&_b]:text-[color:#173d66]", "tw:[&_b]:text-[.9rem]",
    "tw:[&_b]:text-right", "tw:[&_.is-loss_b]:text-[color:#ba3e3e]", "tw:[&_.is-surplus_b]:text-[color:#167a54]",
  ].join(" "),
} as const;
