import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "stack_md_t_category_workspace_category_detail_workspace": [
    "stack-md", "t-category-workspace", "category-detail-workspace", "tw:grid",
    "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]",
    "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]", "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]",
    "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]", "tw:max-w-[1320px]",
  ].join(" "),
  "t_category_back": [
    "t-category-back", "tw:inline-flex", "tw:items-center", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:w-[fit-content]", "tw:text-[color:var(--muted)]", "tw:text-[0.9rem]",
    "tw:font-[700]", "tw:hover:text-[color:var(--brand)]",
  ].join(" "),
  "league_overview_dashboard": [
    "league-overview-dashboard", "tw:grid", "tw:gap-y-[18px]", "tw:gap-x-[18px]",
  ].join(" "),
  "league_overview_hero": [
    "league-overview-hero", "tw:pt-[26px]", "tw:viewport-760:pt-[18px]", "tw:pr-[26px]",
    "tw:viewport-760:pr-[18px]", "tw:pb-[26px]", "tw:viewport-760:pb-[18px]", "tw:pl-[26px]",
    "tw:viewport-760:pl-[18px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d9e5f2]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d9e5f2]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d9e5f2]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#d9e5f2]", "tw:rounded-[15px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_#fff_0%,_#fbfdff_100%)]",
    "tw:[box-shadow:0_12px_30px_rgb(15_54_104_/_.06)]",
  ].join(" "),
  "league_overview_header": [
    "league-overview-header", "tw:flex", "tw:viewport-580:grid", "tw:items-start",
    "tw:justify-between", "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:[&_.eyebrow]:mt-[0]",
    "tw:[&_.eyebrow]:mr-[0]", "tw:[&_.eyebrow]:mb-[10px]", "tw:[&_.eyebrow]:ml-[0]", "tw:[&_.eyebrow]:text-[color:#1262c4]",
    "tw:[&_.eyebrow]:text-[.68rem]", "tw:[&_.eyebrow]:font-[900]", "tw:[&_.eyebrow]:tracking-[.11em]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "league_overview_title_row": [
    "league-overview-title-row", "tw:flex", "tw:flex-wrap", "tw:items-center",
    "tw:gap-y-[11px]", "tw:gap-x-[11px]", "tw:[&_h1]:mt-[0]", "tw:[&_h1]:mr-[0]",
    "tw:[&_h1]:mb-[0]", "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[color:#081d46]", "tw:[&_h1]:text-[clamp(1.75rem,_2.6vw,_2.4rem)]",
    "tw:[&_h1]:tracking-[-.055em]", "tw:[&_h1]:leading-[1.05]", "tw:[&_.public-visibility-switch]:ml-[7px]", "tw:[&_.league-category-edit-trigger]:ml-[0]",
    "tw:[&_.league-category-edit-trigger]:min-h-[38px]", "tw:[&_.public-visibility-switch_label]:min-h-[38px]", "tw:viewport-580:[&_h1]:w-[100%]",
  ].join(" "),
  "league_overview_status": [
    "league-overview-status", "tw:[&_.status-badge]:pt-[7px]", "tw:[&_.status-badge]:pr-[13px]", "tw:[&_.status-badge]:pb-[7px]",
    "tw:[&_.status-badge]:pl-[13px]", "tw:[&_.status-badge]:rounded-[999px]", "tw:[&_.status-badge]:text-[.74rem]", "tw:viewport-580:[justify-self:start]",
  ].join(" "),
  "league_overview_context": [
    "league-overview-context", "tw:mt-[16px]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-[color:#64738d]", "tw:text-[.88rem]", "tw:leading-[1.5]",
  ].join(" "),
  "league_overview_summary_row": [
    "league-overview-summary-row", "tw:grid", "tw:grid-cols-[repeat(3,_minmax(0,_1fr))_minmax(235px,_.95fr)]", "tw:viewport-1100:grid-cols-[repeat(3,_minmax(0,_1fr))]",
    "tw:viewport-820:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-580:grid-cols-[1fr]", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:items-stretch", "tw:mt-[26px]", "tw:viewport-760:mt-[20px]",
  ].join(" "),
  "league_overview_metric": [
    "league-overview-metric", "tw:flex", "tw:items-center", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:min-h-[96px]", "tw:pt-[15px]", "tw:pr-[15px]",
    "tw:pb-[15px]", "tw:pl-[15px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dbe6f2]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dbe6f2]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dbe6f2]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dbe6f2]", "tw:rounded-[13px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[&_>_div]:grid", "tw:[&_>_div]:gap-y-[5px]", "tw:[&_>_div]:gap-x-[5px]",
    "tw:[&_>_div]:min-w-[0]", "tw:[&_span:not(.league-overview-metric-icon)]:text-[color:#63718a]", "tw:[&_span:not(.league-overview-metric-icon)]:text-[.78rem]", "tw:[&_span:not(.league-overview-metric-icon)]:font-[700]",
    "tw:[&_strong]:text-[color:#07173b]", "tw:[&_strong]:text-[1.45rem]", "tw:[&_strong]:tracking-[-.04em]", "tw:[&_strong]:leading-[1]",
  ].join(" "),
  "league_overview_metric_icon_league_overview_metric_icon_blue": [
    "league-overview-metric-icon", "league-overview-metric-icon-blue", "tw:grid", "tw:[flex:0_0_auto]",
    "tw:place-items-center", "tw:w-[38px]", "tw:h-[38px]", "tw:rounded-[50%]",
    "tw:text-[1rem]", "tw:font-[700]", "tw:leading-[1]", "tw:[&_.league-icon]:w-[19px]",
    "tw:[&_.league-icon]:h-[19px]", "tw:text-[color:#1264d2]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_#eaf2ff,_#dce9fb)]",
  ].join(" "),
  "league_overview_metric_icon_league_overview_metric_icon_green": [
    "league-overview-metric-icon", "league-overview-metric-icon-green", "tw:grid", "tw:[flex:0_0_auto]",
    "tw:place-items-center", "tw:w-[38px]", "tw:h-[38px]", "tw:rounded-[50%]",
    "tw:text-[1rem]", "tw:font-[700]", "tw:leading-[1]", "tw:[&_.league-icon]:w-[19px]",
    "tw:[&_.league-icon]:h-[19px]", "tw:text-[color:#159963]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_#e8faf1,_#dff5e9)]",
  ].join(" "),
  "league_overview_metric_icon_league_overview_metric_icon_purple": [
    "league-overview-metric-icon", "league-overview-metric-icon-purple", "tw:grid", "tw:[flex:0_0_auto]",
    "tw:place-items-center", "tw:w-[38px]", "tw:h-[38px]", "tw:rounded-[50%]",
    "tw:text-[1rem]", "tw:font-[700]", "tw:leading-[1]", "tw:[&_.league-icon]:w-[19px]",
    "tw:[&_.league-icon]:h-[19px]", "tw:text-[color:#654ce1]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_#f0edff,_#e6e2fb)]",
  ].join(" "),
  "league_overview_primary_action": [
    "league-overview-primary-action", "tw:grid", "tw:items-center", "tw:min-w-[0]",
    "tw:pl-[18px]", "tw:viewport-1100:pl-[0]", "tw:border-l-[length:1px]", "tw:viewport-1100:border-l-[length:0]",
    "tw:[border-left-style:solid]", "tw:viewport-1100:[border-left-style:none]", "tw:border-l-[color:#dbe6f2]", "tw:viewport-1100:border-l-[color:currentColor]",
    "tw:[&_.button]:inline-flex", "tw:[&_.button]:justify-center", "tw:[&_.button]:items-center", "tw:[&_.button]:gap-y-[7px]",
    "tw:[&_.button]:gap-x-[7px]", "tw:[&_.button]:min-h-[38px]", "tw:[&_.button]:pt-[7px]", "tw:[&_.button]:pr-[12px]",
    "tw:[&_.button]:pb-[7px]", "tw:[&_.button]:pl-[12px]", "tw:[&_.button]:rounded-[8px]", "tw:[&_.button]:text-[.78rem]",
    "tw:[&_.button]:whitespace-nowrap", "tw:[&_.button_span]:text-[1.1rem]", "tw:viewport-1100:[grid-column:1_/_-1]", "tw:viewport-1100:pt-[14px]",
    "tw:viewport-1100:pr-[0]", "tw:viewport-1100:pb-[0]", "tw:viewport-1100:border-t-[length:1px]", "tw:viewport-1100:[border-top-style:solid]",
    "tw:viewport-1100:border-t-[color:#dbe6f2]", "tw:viewport-580:[&_.button]:w-[100%]", "tw:[&_.button_.league-icon]:w-[16px]", "tw:[&_.button_.league-icon]:h-[16px]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "pill": sharedUtilities.pill,
  "league_overview_bottom": [
    "league-overview-bottom", "tw:grid", "tw:grid-cols-[minmax(0,_1.95fr)_minmax(270px,_.9fr)]", "tw:viewport-820:grid-cols-[1fr]",
    "tw:gap-y-[16px]", "tw:gap-x-[16px]",
  ].join(" "),
  "league_prize_card": [
    "league-prize-card", "tw:min-w-[0]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dbe6f2]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dbe6f2]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dbe6f2]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dbe6f2]", "tw:rounded-[15px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[box-shadow:0_10px_24px_rgb(15_54_104_/_.045)]", "tw:pt-[21px]", "tw:viewport-760:pt-[18px]",
    "tw:pr-[24px]", "tw:viewport-760:pr-[18px]", "tw:pb-[23px]", "tw:viewport-760:pb-[18px]",
    "tw:pl-[24px]", "tw:viewport-760:pl-[18px]", "tw:[&_.league-prize-form]:grid", "tw:[&_.league-prize-form]:gap-y-[16px]",
    "tw:[&_.league-prize-form]:gap-x-[16px]", "tw:[&_.league-prize-textarea]:min-h-[112px]", "tw:[&_.league-prize-textarea]:pt-[14px]", "tw:[&_.league-prize-textarea]:pr-[14px]",
    "tw:[&_.league-prize-textarea]:pb-[14px]", "tw:[&_.league-prize-textarea]:pl-[14px]", "tw:[&_.league-prize-textarea]:border-t-[color:#cddbea]", "tw:[&_.league-prize-textarea]:border-r-[color:#cddbea]",
    "tw:[&_.league-prize-textarea]:border-b-[color:#cddbea]", "tw:[&_.league-prize-textarea]:border-l-[color:#cddbea]", "tw:[&_.league-prize-textarea]:rounded-[11px]", "tw:[&_.league-prize-textarea]:text-[color:#253552]",
    "tw:[&_.league-prize-textarea]:text-[.87rem]", "tw:[&_.league-prize-textarea]:leading-[1.5]", "tw:[&_.league-prize-actions]:mt-[4px]", "tw:[&_.league-prize-actions_.button]:inline-flex",
    "tw:[&_.league-prize-actions_.button]:items-center", "tw:[&_.league-prize-actions_.button]:gap-y-[8px]", "tw:[&_.league-prize-actions_.button]:gap-x-[8px]", "tw:[&_.league-prize-actions_.button]:min-h-[36px]",
    "tw:viewport-580:[&_.league-prize-actions_.button]:min-h-[38px]", "tw:[&_.league-prize-actions_.button]:[padding-inline:12px]", "tw:[&_.league-prize-actions_.button]:rounded-[9px]", "tw:[&_.league-prize-actions_.button]:text-[.76rem]",
    "tw:[&_.league-prize-actions_.button_span]:text-[1.2rem]", "tw:viewport-580:[&_.league-prize-actions_.button]:w-[100%]", "tw:[&_.league-prize-actions_.league-icon]:w-[15px]", "tw:[&_.league-prize-actions_.league-icon]:h-[15px]",
  ].join(" "),
  "league_prize_form": [
    "league-prize-form", "tw:grid", "tw:[grid-column:1_/_-1]", "tw:grid-cols-[220px_minmax(0,_1fr)]",
    "tw:viewport-900:grid-cols-[1fr]", "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:[align-items:start]",
    "tw:min-w-[0]",
  ].join(" "),
  "league_prize_card_heading": [
    "league-prize-card-heading", "tw:flex", "tw:items-center", "tw:viewport-580:items-start",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:[&_.league-overview-section-icon]:w-[50px]", "tw:[&_.league-overview-section-icon]:h-[50px]",
    "tw:[&_.league-overview-section-icon]:text-[1.45rem]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]",
    "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#0c1c44]", "tw:[&_h2]:text-[1.06rem]", "tw:[&_h2]:tracking-[-.025em]",
    "tw:[&_p]:mt-[5px]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
    "tw:[&_p]:text-[color:#66748d]", "tw:[&_p]:text-[.83rem]",
  ].join(" "),
  "league_overview_section_icon": [
    "league-overview-section-icon", "tw:grid", "tw:[flex:0_0_auto]", "tw:place-items-center",
    "tw:w-[38px]", "tw:h-[38px]", "tw:rounded-[50%]", "tw:text-[1rem]",
    "tw:font-[700]", "tw:leading-[1]", "tw:text-[color:#1264d2]", "tw:bg-[color:transparent]",
    "tw:[background-image:linear-gradient(145deg,_#eaf2ff,_#dce9fb)]", "tw:[&_.league-icon]:w-[19px]", "tw:[&_.league-icon]:h-[19px]",
  ].join(" "),
  "league_prize_edit_icon": [
    "league-prize-edit-icon", "tw:grid", "tw:w-[32px]", "tw:h-[32px]",
    "tw:ml-[auto]", "tw:place-items-center", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#d5e2f0]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d5e2f0]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d5e2f0]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#d5e2f0]", "tw:rounded-[9px]", "tw:text-[color:#4c607b]",
    "tw:text-[1rem]", "tw:[&_.league-icon]:w-[16px]", "tw:[&_.league-icon]:h-[16px]",
  ].join(" "),
  "league_prize_editor": [
    "league-prize-editor", "tw:grid", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
    "tw:min-w-[0]",
  ].join(" "),
  "league_prize_textarea": [
    "league-prize-textarea", "tw:w-[100%]", "tw:min-h-[112px]", "tw:[resize:vertical]",
    "tw:pt-[13px]", "tw:pr-[14px]", "tw:pb-[13px]", "tw:pl-[14px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#cfdceb]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#cfdceb]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#cfdceb]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#cfdceb]",
    "tw:rounded-[9px]", "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:text-[color:#152d52]",
    "tw:[font:inherit]", "tw:text-[.9rem]", "tw:leading-[1.5]", "tw:focus:[outline:0]",
    "tw:focus:border-t-[color:#2670d8]", "tw:focus:border-r-[color:#2670d8]", "tw:focus:border-b-[color:#2670d8]", "tw:focus:border-l-[color:#2670d8]",
    "tw:focus:[box-shadow:0_0_0_3px_rgb(38_112_216_/_.12)]",
  ].join(" "),
  "league_prize_actions": [
    "league-prize-actions", "tw:flex", "tw:justify-end", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[&_.button]:min-h-[38px]",
  ].join(" "),
  "league_cycle_card": [
    "league-cycle-card", "tw:min-w-[0]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dbe6f2]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dbe6f2]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dbe6f2]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dbe6f2]", "tw:rounded-[15px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[box-shadow:0_10px_24px_rgb(15_54_104_/_.045)]", "tw:grid", "tw:[align-content:start]",
    "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:pt-[22px]", "tw:viewport-760:pt-[18px]",
    "tw:pr-[22px]", "tw:viewport-760:pr-[18px]", "tw:pb-[22px]", "tw:viewport-760:pb-[18px]",
    "tw:pl-[22px]", "tw:viewport-760:pl-[18px]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]",
    "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#0c1c44]", "tw:[&_h2]:text-[1.06rem]",
    "tw:[&_h2]:tracking-[-.025em]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#64728b]", "tw:[&_p]:text-[.87rem]", "tw:[&_p]:leading-[1.45]",
    "tw:[&_form]:mt-[2px]", "tw:[&_.button]:inline-flex", "tw:[&_.button]:items-center", "tw:[&_.button]:justify-center",
    "tw:[&_.button]:gap-y-[8px]", "tw:[&_.button]:gap-x-[8px]", "tw:[&_.button]:min-h-[36px]", "tw:viewport-580:[&_.button]:min-h-[38px]",
    "tw:[&_.button]:[padding-inline:12px]", "tw:[&_.button]:border-t-[color:#ccdbea]", "tw:[&_.button]:border-r-[color:#ccdbea]", "tw:[&_.button]:border-b-[color:#ccdbea]",
    "tw:[&_.button]:border-l-[color:#ccdbea]", "tw:[&_.button]:rounded-[9px]", "tw:[&_.button]:text-[color:#1e2d4b]", "tw:[&_.button]:bg-[color:#fff]",
    "tw:[&_.button]:[background-image:none]", "tw:[&_.button]:[box-shadow:none]", "tw:[&_.button]:text-[.76rem]", "tw:[&_.button:hover]:border-t-[color:#9bb8d8]",
    "tw:[&_.button:hover]:border-r-[color:#9bb8d8]", "tw:[&_.button:hover]:border-b-[color:#9bb8d8]", "tw:[&_.button:hover]:border-l-[color:#9bb8d8]", "tw:[&_.button:hover]:bg-[color:#f4f8fc]",
    "tw:[&_.button:hover]:[background-image:none]", "tw:[&_.button_span]:text-[color:#376392]", "tw:[&_.button_span]:text-[1.05rem]", "tw:viewport-580:[&_.button]:w-[100%]",
    "tw:[&_.league-icon]:w-[15px]", "tw:[&_.league-icon]:h-[15px]",
  ].join(" "),
  "league_cycle_card_heading": [
    "league-cycle-card-heading", "tw:flex", "tw:items-center", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:[&_.league-overview-section-icon]:w-[50px]", "tw:[&_.league-overview-section-icon]:h-[50px]", "tw:[&_.league-overview-section-icon]:text-[1.45rem]",
  ].join(" "),
  "button_button_secondary": sharedUtilities.buttonButtonSecondary,
  "category_overview_category_detail_hero": [
    "category-overview", "category-detail-hero", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)_auto]",
    "tw:viewport-980:grid-cols-[1fr]", "tw:gap-y-[12px]", "tw:gap-x-[18px]", "tw:pt-[18px]",
    "tw:viewport-760:pt-[16px]", "tw:pr-[20px]", "tw:viewport-760:pr-[16px]", "tw:pb-[18px]",
    "tw:viewport-760:pb-[16px]", "tw:pl-[20px]", "tw:viewport-760:pl-[16px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#d5e3f2]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#d5e3f2]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d5e3f2]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d5e3f2]", "tw:rounded-[16px]",
    "tw:bg-[color:#ffffff]", "tw:[background-image:none]", "tw:[box-shadow:0_8px_22px_rgb(17_62_112_/_.055)]", "tw:[&_.category-overview-head]:items-start",
    "tw:[&_.category-overview-head_h1]:text-[color:#092e5d]", "tw:[&_.category-overview-head_h1]:text-[clamp(1.45rem,_2.2vw,_1.9rem)]", "tw:[&_.category-overview-context]:pt-[2px]", "tw:[&_.category-overview-context]:text-[color:#607b98]",
    "tw:[&_.category-overview-context]:text-[.84rem]", "tw:[&_.category-overview-metrics]:gap-y-[8px]", "tw:[&_.category-overview-metrics]:gap-x-[8px]", "tw:[&_.category-overview-metrics_div]:min-h-[0]",
    "tw:[&_.category-overview-metrics_div]:pt-[9px]", "tw:[&_.category-overview-metrics_div]:pr-[12px]", "tw:[&_.category-overview-metrics_div]:pb-[9px]", "tw:[&_.category-overview-metrics_div]:pl-[12px]",
    "tw:[&_.category-overview-metrics_div]:border-t-[length:1px]", "tw:[&_.category-overview-metrics_div]:[border-top-style:solid]", "tw:[&_.category-overview-metrics_div]:border-t-[color:#e0eaf5]", "tw:[&_.category-overview-metrics_div]:border-r-[length:1px]",
    "tw:[&_.category-overview-metrics_div]:[border-right-style:solid]", "tw:[&_.category-overview-metrics_div]:border-r-[color:#e0eaf5]", "tw:[&_.category-overview-metrics_div]:border-b-[length:1px]", "tw:[&_.category-overview-metrics_div]:[border-bottom-style:solid]",
    "tw:[&_.category-overview-metrics_div]:border-b-[color:#e0eaf5]", "tw:[&_.category-overview-metrics_div]:border-l-[length:1px]", "tw:[&_.category-overview-metrics_div]:[border-left-style:solid]", "tw:[&_.category-overview-metrics_div]:border-l-[color:#e0eaf5]",
    "tw:[&_.category-overview-metrics_div]:rounded-[10px]", "tw:[&_.category-overview-metrics_div]:bg-[color:#f8fbff]", "tw:[&_.category-overview-metrics_div]:[background-image:none]", "tw:[&_.category-overview-metrics_dt]:text-[color:#6882a0]",
    "tw:[&_.category-overview-metrics_dt]:text-[.65rem]", "tw:[&_.category-overview-metrics_dd]:text-[color:#0b3568]", "tw:[&_.category-overview-metrics_dd]:text-[1.05rem]", "tw:viewport-760:[&_.category-overview-metrics]:grid-cols-[1fr]",
  ].join(" "),
  "category_overview_head": [
    "category-overview-head", "tw:[grid-column:1_/_-1]", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)_auto]",
    "tw:viewport-980:grid-cols-[1fr]", "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:[align-items:start]",
    "tw:[&_h1]:mt-[0]", "tw:[&_h1]:mr-[0]", "tw:[&_h1]:mb-[0]", "tw:[&_h1]:ml-[0]",
  ].join(" "),
  "stack_xs": [
    "stack-xs", "tw:grid", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
  ].join(" "),
  "category_overview_title_row": [
    "category-overview-title-row", "tw:flex", "tw:items-center", "tw:flex-wrap",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:[&_h1]:mt-[0]", "tw:[&_h1]:mr-[0]",
    "tw:[&_h1]:mb-[0]", "tw:[&_h1]:ml-[0]",
  ].join(" "),
  "category_overview_context_muted": [
    "category-overview-context", "muted", "tw:[grid-column:1_/_-1]", "tw:mt-[0]",
    "tw:mr-[0]", "tw:mb-[0]", "tw:ml-[0]", "tw:pt-[12px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:text-[color:var(--muted)]",
  ].join(" "),
  "category_overview_metrics": [
    "category-overview-metrics", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:grid", "tw:grid-cols-[repeat(3,_minmax(0,_1fr))]", "tw:viewport-980:grid-cols-[1fr]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:[&_div]:grid", "tw:[&_div]:gap-y-[2px]",
    "tw:[&_div]:gap-x-[2px]", "tw:[&_dt]:text-[color:var(--muted)]", "tw:[&_dt]:text-[0.75rem]", "tw:[&_dt]:font-[700]",
    "tw:[&_dt]:uppercase", "tw:[&_dd]:mt-[0]", "tw:[&_dd]:mr-[0]", "tw:[&_dd]:mb-[0]",
    "tw:[&_dd]:ml-[0]", "tw:[&_dd]:font-[700]",
  ].join(" "),
  "category_overview_action": [
    "category-overview-action", "tw:flex", "tw:items-center", "tw:justify-end",
    "tw:viewport-980:[justify-content:stretch]", "tw:text-right", "tw:viewport-980:text-left", "tw:viewport-980:[&_.button]:w-[100%]",
  ].join(" "),
  "section_card": sharedUtilities.sectionCard2,
} as const;
