import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "commands_icon": [
    "commands-icon", "tw:block", "tw:w-[1em]", "tw:h-[1em]",
  ].join(" "),
  "commands_page": [
    "commands-page", "tw:grid", "tw:gap-y-[28px]", "tw:viewport-760:gap-y-[18px]",
    "tw:gap-x-[28px]", "tw:viewport-760:gap-x-[18px]", "tw:w-[min(100%,_1320px)]", "tw:[margin-inline:auto]",
  ].join(" "),
  "commands_toolbar": [
    "commands-toolbar", "tw:grid", "tw:grid-cols-[auto_minmax(0,_1fr)]", "tw:viewport-1260:grid-cols-[1fr]",
    "tw:gap-y-[24px]", "tw:gap-x-[24px]", "tw:items-center",
  ].join(" "),
  "commands_toolbar_right": [
    "commands-toolbar-right", "tw:[grid-column:auto]", "tw:flex", "tw:justify-end",
    "tw:viewport-1260:justify-start", "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:items-center",
    "tw:viewport-760:items-stretch", "tw:viewport-760:[justify-self:stretch]", "tw:viewport-760:flex-col", "tw:viewport-1260:flex-wrap",
  ].join(" "),
  "commands_search": [
    "commands-search", "tw:flex", "tw:viewport-760:grid", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:items-center", "tw:relative", "tw:[&_input]:min-h-[46px]",
    "tw:viewport-760:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[12px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[47px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#dce7f2]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#dce7f2]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:#dce7f2]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:#dce7f2]", "tw:[&_input]:rounded-[9px]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:w-[320px]", "tw:viewport-1260:[&_input]:w-[min(320px,_36vw)]", "tw:[&_input]:text-[color:#182b48]", "tw:[&_input]:[box-shadow:0_5px_14px_rgb(13_50_96_/_.035)]",
    "tw:[&_input]:text-[.86rem]", "tw:viewport-760:w-[100%]", "tw:viewport-760:grid-cols-[minmax(0,_1fr)_auto]", "tw:viewport-760:[&_input]:[flex:1]",
    "tw:[&_>_span]:absolute", "tw:[&_>_span]:z-[1]", "tw:[&_>_span]:left-[14px]", "tw:[&_>_span]:text-[color:#61718b]",
    "tw:[&_>_span]:text-[1.2rem]", "tw:[&_>_span]:leading-[1]", "tw:[&_.button]:min-h-[46px]", "tw:viewport-760:[&_.button]:min-h-[44px]",
    "tw:[&_.button]:[padding-inline:16px]", "tw:[&_.button]:border-t-[color:#dce7f2]", "tw:[&_.button]:border-r-[color:#dce7f2]", "tw:[&_.button]:border-b-[color:#dce7f2]",
    "tw:[&_.button]:border-l-[color:#dce7f2]", "tw:[&_.button]:bg-[color:#fff]", "tw:[&_.button]:[background-image:none]", "tw:[&_.button]:text-[color:#1c2d49]",
    "tw:[&_.button]:[box-shadow:0_5px_14px_rgb(13_50_96_/_.025)]", "tw:[&_.button]:text-[.8rem]",
  ].join(" "),
  "button": sharedUtilities.button,
  "commands_actions": [
    "commands-actions", "tw:flex", "tw:viewport-760:grid", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:items-end", "tw:justify-end", "tw:viewport-760:justify-start",
    "tw:viewport-760:w-[100%]", "tw:viewport-760:grid-cols-[1fr_1fr]", "tw:viewport-430:grid-cols-[1fr]", "tw:[&_.button]:inline-flex",
    "tw:[&_.button]:items-center", "tw:[&_.button]:justify-center", "tw:[&_.button]:gap-y-[8px]", "tw:[&_.button]:gap-x-[8px]",
    "tw:[&_.button]:min-h-[46px]", "tw:viewport-760:[&_.button]:min-h-[44px]", "tw:[&_.button]:[padding-inline:17px]", "tw:[&_.button]:border-t-[color:#b8d0ed]",
    "tw:[&_.button]:border-r-[color:#b8d0ed]", "tw:[&_.button]:border-b-[color:#b8d0ed]", "tw:[&_.button]:border-l-[color:#b8d0ed]", "tw:[&_.button]:rounded-[9px]",
    "tw:[&_.button]:text-[color:#1760bc]", "tw:[&_.button]:bg-[color:#fff]", "tw:[&_.button]:[background-image:none]", "tw:[&_.button]:[box-shadow:0_5px_14px_rgb(13_50_96_/_.025)]",
    "tw:[&_.button]:text-[.84rem]", "tw:[&_.button]:whitespace-nowrap", "tw:[&_.button_span]:text-[1.5rem]", "tw:viewport-760:[&_.button_span]:text-[1.2rem]",
    "tw:[&_.button_span]:font-[400]", "tw:[&_.button_span]:leading-[1]", "tw:[&_.button.button-primary]:min-w-[164px]", "tw:[&_.button.button-primary]:border-t-[color:#1c68cc]",
    "tw:[&_.button.button-primary]:border-r-[color:#1c68cc]", "tw:[&_.button.button-primary]:border-b-[color:#1c68cc]", "tw:[&_.button.button-primary]:border-l-[color:#1c68cc]", "tw:[&_.button.button-primary]:text-[color:#fff]",
    "tw:[&_.button.button-primary]:bg-[color:transparent]", "tw:[&_.button.button-primary]:[background-image:linear-gradient(135deg,_#125bc1,_#176fd7)]", "tw:[&_.button.button-primary]:[box-shadow:0_9px_18px_rgb(16_94_196_/_.2)]", "tw:viewport-760:[&_.button]:min-w-[0]",
    "tw:viewport-760:[&_.button.button-primary]:min-h-[44px]", "tw:viewport-760:[&_.button.button-primary]:[padding-inline:10px]", "tw:viewport-760:[&_.button.button-primary]:text-[.77rem]", "tw:[&_.button_.commands-icon]:w-[17px]",
    "tw:[&_.button_.commands-icon]:h-[17px]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "commands_create_panel": [
    "commands-create-panel", "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]",
    "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[12px]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]",
  ].join(" "),
  "commands_create_form": [
    "commands-create-form", "tw:flex", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:items-end", "tw:viewport-760:items-stretch", "tw:justify-start", "tw:[&_.field]:min-w-[min(320px,_100%)]",
    "tw:viewport-760:flex-col",
  ].join(" "),
  "field": sharedUtilities.field,
  "commands_list_commands_day_panel": [
    "commands-list", "commands-day-panel", "tw:pt-[0]", "tw:pr-[0]",
    "tw:pb-[0]", "tw:pl-[0]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dce7f2]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce7f2]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce7f2]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dce7f2]", "tw:rounded-[15px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:min-h-[620px]", "tw:viewport-760:min-h-[500px]", "tw:[overflow-x:hidden]",
    "tw:[overflow-y:hidden]", "tw:[box-shadow:0_12px_28px_rgb(13_50_96_/_.07)]", "tw:[&_.commands-list-head]:flex", "tw:[&_.commands-list-head]:items-center",
    "tw:viewport-760:[&_.commands-list-head]:items-start", "tw:viewport-430:[&_.commands-list-head]:items-center", "tw:[&_.commands-list-head]:mt-[0]", "tw:[&_.commands-list-head]:mr-[0]",
    "tw:[&_.commands-list-head]:mb-[0]", "tw:[&_.commands-list-head]:ml-[0]", "tw:[&_.commands-list-head]:pt-[20px]", "tw:viewport-760:[&_.commands-list-head]:pt-[16px]",
    "tw:[&_.commands-list-head]:pr-[24px]", "tw:viewport-760:[&_.commands-list-head]:pr-[16px]", "tw:[&_.commands-list-head]:pb-[20px]", "tw:viewport-760:[&_.commands-list-head]:pb-[16px]",
    "tw:[&_.commands-list-head]:pl-[24px]", "tw:viewport-760:[&_.commands-list-head]:pl-[16px]", "tw:[&_.commands-list-head]:border-b-[length:1px]", "tw:[&_.commands-list-head]:[border-bottom-style:solid]",
    "tw:[&_.commands-list-head]:border-b-[color:#e2eaf3]", "tw:[&_.commands-list-head_strong]:text-[color:#14213b]", "tw:[&_.commands-list-head_strong]:text-[1.12rem]", "tw:[&_.commands-list-head_strong]:tracking-[-.02em]",
    "tw:[&_.commands-list-head_strong]:[text-transform:lowercase]", "tw:[&_.commands-list-head_>_span]:inline-flex", "tw:[&_.commands-list-head_>_span]:items-center", "tw:[&_.commands-list-head_>_span]:gap-y-[7px]",
    "tw:[&_.commands-list-head_>_span]:gap-x-[7px]", "tw:[&_.commands-list-head_>_span]:text-[color:#5e6f89]", "tw:[&_.commands-list-head_>_span]:text-[.82rem]", "tw:[&_.commands-list-head_>_span_i]:grid",
    "tw:viewport-760:[&_.commands-list-head_>_span_i]:hidden", "tw:[&_.commands-list-head_>_span_i]:w-[30px]", "tw:[&_.commands-list-head_>_span_i]:h-[30px]", "tw:[&_.commands-list-head_>_span_i]:place-items-center",
    "tw:[&_.commands-list-head_>_span_i]:rounded-[50%]", "tw:[&_.commands-list-head_>_span_i]:text-[color:#61748e]", "tw:[&_.commands-list-head_>_span_i]:bg-[color:#f1f5fa]", "tw:[&_.commands-list-head_>_span_i]:[background-image:none]",
    "tw:[&_.commands-list-head_>_span_i]:not-italic", "tw:[&_.commands-list-head_>_span_i]:text-[.9rem]", "tw:[&_.commands-list-head-compact]:justify-end", "tw:[&_.commands-list-head-compact]:[padding-block:11px]",
    "tw:[&_.commands-list-items]:pt-[18px]", "tw:[&_.commands-list-items]:pr-[24px]", "tw:[&_.commands-list-items]:pb-[24px]", "tw:[&_.commands-list-items]:pl-[24px]",
    "tw:viewport-760:[&_.commands-list-head]:gap-y-[12px]", "tw:viewport-760:[&_.commands-list-head]:gap-x-[12px]", "tw:viewport-760:[&_.commands-list-head_>_span]:whitespace-nowrap", "tw:viewport-430:[&_.commands-list-head_>_span]:[align-self:flex-start]",
    "tw:[&_.commands-list-head_>_span_i_.commands-icon]:w-[15px]", "tw:[&_.commands-list-head_>_span_i_.commands-icon]:h-[15px]",
  ].join(" "),
  "commands_list_head": [
    "commands-list-head", "commands-list-head-compact", "tw:flex", "tw:justify-between",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:items-baseline", "tw:mb-[12px]",
    "tw:[&_span]:text-[color:var(--muted)]", "tw:[&_span]:text-[.78rem]", "tw:[&_>_div]:flex", "tw:[&_>_div]:items-center",
    "tw:[&_>_div]:gap-y-[13px]", "tw:[&_>_div]:gap-x-[13px]",
  ].join(" "),
  "commands_list_items": [
    "commands-list-items", "tw:grid", "tw:grid-cols-[repeat(auto-fill,_minmax(220px,_1fr))]", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:[align-items:start]",
  ].join(" "),
  "commands_empty": [
    "commands-empty", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:min-h-[465px]", "tw:viewport-760:min-h-[365px]", "tw:[place-content:center]", "tw:border-t-[length:0]",
    "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]",
    "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:text-[color:#71819a]",
    "tw:text-center", "tw:[align-content:center]", "tw:[justify-items:center]", "tw:pt-[34px]",
    "tw:pr-[18px]", "tw:pb-[34px]", "tw:pl-[18px]", "tw:bg-[color:transparent]",
    "tw:[background-image:radial-gradient(circle_at_50%_28%,_#f6f9fd_0,_#fff_42%)]", "tw:[&_strong]:text-[color:#111d37]", "tw:[&_strong]:text-[1.08rem]", "tw:[&_strong]:tracking-[-.025em]",
    "tw:[&_>_span]:text-[.87rem]",
  ].join(" "),
  "commands_empty_illustration": [
    "commands-empty-illustration", "tw:grid", "tw:w-[104px]", "tw:viewport-760:w-[82px]",
    "tw:h-[104px]", "tw:viewport-760:h-[82px]", "tw:mb-[5px]", "tw:place-items-center",
    "tw:rounded-[50%]", "tw:text-[color:#aac7f5]", "tw:bg-[color:transparent]", "tw:[background-image:radial-gradient(circle_at_50%_25%,_#fff,_#edf3fc_64%,_#f9fbff)]",
    "tw:[box-shadow:inset_0_-12px_24px_rgb(157_190_240_/_.12)]", "tw:text-[1rem]", "tw:leading-[1]", "tw:[&_.commands-icon]:w-[50px]",
    "tw:viewport-760:[&_.commands-icon]:w-[39px]", "tw:[&_.commands-icon]:h-[50px]", "tw:viewport-760:[&_.commands-icon]:h-[39px]",
  ].join(" "),
  "button_button_primary_commands_empty_action": [
    "button", "button-primary", "commands-empty-action", "tw:inline-flex",
    "tw:items-center", "tw:justify-center", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:min-h-[46px]", "tw:pt-[0]", "tw:pr-[12px]", "tw:pb-[0]",
    "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--brand)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--brand)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--brand)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--brand)]", "tw:rounded-[9px]", "tw:bg-[color:var(--brand)]", "tw:[background-image:none]",
    "tw:text-[color:#ffffff]", "tw:text-[.84rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--brand-strong)]",
    "tw:hover:border-r-[color:var(--brand-strong)]", "tw:hover:border-b-[color:var(--brand-strong)]", "tw:hover:border-l-[color:var(--brand-strong)]", "tw:hover:[transform:translateY(-1px)]",
    "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]",
    "tw:[&:active]:[box-shadow:none]", "tw:hover:bg-[color:var(--brand-strong)]", "tw:hover:[background-image:none]", "tw:mt-[12px]",
    "tw:[padding-inline:18px]", "tw:[&_span]:text-[1.7rem]", "tw:[&_span]:font-[400]", "tw:[&_span]:leading-[1]",
    "tw:[&_.commands-icon]:w-[17px]", "tw:[&_.commands-icon]:h-[17px]",
  ].join(" "),
} as const;
