import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "commands_icon": [
    "commands-icon", "tw:block", "tw:w-[1em]", "tw:h-[1em]",
  ].join(" "),
  "commands_page": "commands-page tw:grid tw:w-full tw:min-w-0 tw:gap-4",
  "commands_toolbar": "commands-toolbar tw:flex tw:flex-wrap tw:items-center tw:gap-3",
  "commands_toolbar_right": "commands-toolbar-right tw:flex tw:min-w-0 tw:flex-1 tw:flex-wrap tw:items-center tw:justify-end tw:gap-3 tw:viewport-760:justify-start",
  "commands_search": "commands-search tw:flex tw:w-[min(100%,360px)] tw:min-w-0 tw:items-center tw:gap-2 tw:viewport-760:w-full tw:[&_>_span]:shrink-0 tw:[&_>_span]:text-[var(--muted)] tw:[&_input:not([type=hidden])]:min-w-0 tw:[&_input:not([type=hidden])]:w-full tw:[&_input:not([type=hidden])]:flex-1 tw:[&_button]:shrink-0 tw:[&_button]:min-h-[40px]",
  "button": sharedUtilities.button,
  "commands_actions": [
    "commands-actions", "tw:flex", "tw:viewport-760:grid", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:items-end", "tw:justify-end", "tw:viewport-760:justify-start",
    "tw:viewport-760:w-[100%]", "tw:viewport-760:grid-cols-[1fr_1fr]", "tw:viewport-430:grid-cols-[1fr]", "tw:[&_.button]:inline-flex",
    "tw:[&_.button]:items-center", "tw:[&_.button]:justify-center", "tw:[&_.button]:gap-y-[8px]", "tw:[&_.button]:gap-x-[8px]",
    "tw:[&_.button]:min-h-[46px]", "tw:viewport-760:[&_.button]:min-h-[44px]", "tw:[&_.button]:[padding-inline:17px]", "tw:[&_.button]:border-t-[color:#b8d0ed]",
    "tw:[&_.button]:border-r-[color:#b8d0ed]", "tw:[&_.button]:border-b-[color:#b8d0ed]", "tw:[&_.button]:border-l-[color:#b8d0ed]", "tw:[&_.button]:rounded-[9px]",
    "tw:[&_.button]:text-[color:#1760bc]", "tw:[&_.button]:bg-[color:#fff]", "tw:[&_.button]:[background-image:none]", "tw:[&_.button]:[box-shadow:0_5px_14px_rgb(13_50_96_/_.025)]",
    "tw:[&_.button]:text-[.84rem]", "tw:[&_.button]:whitespace-nowrap", "tw:[&_.button_span]:text-[1.5rem]", "tw:viewport-760:[&_.button_span]:text-[1.2rem]",
    "tw:[&_.button_span]:font-[400]", "tw:[&_.button_span]:leading-[1]", "tw:[&_.button.button-primary]:min-w-[164px]", "tw:[&_.button.button-primary]:border-t-[color:#1c68cc]",
    "tw:[&_.button.button-primary]:border-r-[color:#1c68cc]", "tw:[&_.button.button-primary]:border-b-[color:#1c68cc]", "tw:[&_.button.button-primary]:border-l-[color:#1c68cc]", "tw:[&_.button.button-primary]:text-[color:#fff]",
    "tw:[&_.button.button-primary]:bg-[color:transparent]", "tw:[&_.button.button-primary]:[background-image:linear-gradient(135deg,_#125bc1,_#176fd7)]", "tw:[&_.button.button-primary]:[box-shadow:0_9px_18px_rgb(16_94_196_/_.2)]", "tw:viewport-760:[&_.button]:min-w-[0]",
    "tw:viewport-760:[&_.button.button-primary]:min-h-[44px]", "tw:viewport-760:[&_.button.button-primary]:[padding-inline:10px]", "tw:viewport-760:[&_.button.button-primary]:text-[.77rem]", "tw:[&_.button_.commands-icon]:w-[17px]",
    "tw:[&_.button_.commands-icon]:h-[17px]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "commands_create_panel": [
    "commands-create-panel", "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]",
    "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[12px]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]",
  ].join(" "),
  "commands_create_form": [
    "commands-create-form", "tw:flex", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:items-end", "tw:viewport-760:items-stretch", "tw:justify-start", "tw:[&_.field]:min-w-[min(320px,_100%)]",
    "tw:viewport-760:flex-col",
  ].join(" "),
  "field": sharedUtilities.field,
  "commands_list_commands_day_panel": "commands-list commands-day-panel tw:rounded-xl tw:border tw:border-solid tw:border-[var(--line)] tw:bg-white tw:shadow-[var(--shadow)]",
  "commands_list_head": "commands-list-head commands-list-head-compact tw:flex tw:items-center tw:justify-between tw:border-0 tw:border-b tw:border-solid tw:border-[var(--line)] tw:px-4 tw:py-3 tw:text-sm tw:text-[var(--muted)] tw:[&_>_span]:inline-flex tw:[&_>_span]:items-center tw:[&_>_span]:gap-2 tw:[&_i]:not-italic",
  "commands_list_items": "commands-list-items tw:grid tw:grid-cols-[repeat(auto-fill,minmax(min(220px,100%),1fr))] tw:items-start tw:gap-3 tw:p-4",
  "commands_empty": "commands-empty tw:grid tw:justify-items-center tw:content-center tw:gap-2 tw:px-4 tw:py-10 tw:text-center tw:text-sm tw:text-[var(--muted)] tw:[&_strong]:text-[var(--text)] tw:[&_strong]:text-base",
  "commands_empty_illustration": "commands-empty-illustration tw:grid tw:size-12 tw:place-items-center tw:rounded-xl tw:bg-[var(--brand-soft)] tw:text-[var(--brand)] tw:[&_svg]:size-6",
  "button_button_primary_commands_empty_action": [
    "button", "button-primary", "commands-empty-action", "tw:inline-flex",
    "tw:items-center", "tw:justify-center", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:min-h-[46px]", "tw:pt-[0]", "tw:pr-[12px]", "tw:pb-[0]",
    "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--brand)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--brand)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--brand)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--brand)]", "tw:rounded-[9px]", "tw:bg-[color:var(--brand)]", "tw:[background-image:none]",
    "tw:text-[color:#ffffff]", "tw:text-[.84rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--brand-strong)]",
    "tw:hover:border-r-[color:var(--brand-strong)]", "tw:hover:border-b-[color:var(--brand-strong)]", "tw:hover:border-l-[color:var(--brand-strong)]", "tw:hover:[transform:translateY(-1px)]",
    "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]",
    "tw:[&:active]:[box-shadow:none]", "tw:hover:bg-[color:var(--brand-strong)]", "tw:hover:[background-image:none]", "tw:mt-[12px]",
    "tw:[padding-inline:18px]", "tw:[&_span]:text-[1.7rem]", "tw:[&_span]:font-[400]", "tw:[&_span]:leading-[1]",
    "tw:[&_.commands-icon]:w-[17px]", "tw:[&_.commands-icon]:h-[17px]",
  ].join(" "),
} as const;
