import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "workspace_page_tv_settings_page": [
    "workspace-page", "tv-settings-page", "tw:grid", "tw:gap-y-[24px]",
    "tw:viewport-720:gap-y-[18px]", "tw:gap-x-[24px]", "tw:viewport-720:gap-x-[18px]", "tw:pt-[5px]",
    "tw:pr-[0]", "tw:pb-[44px]", "tw:pl-[0]", "tw:[&_.page-header]:pt-[4px]",
    "tw:[&_.page-header]:pr-[0]", "tw:[&_.page-header]:pb-[20px]", "tw:[&_.page-header]:pl-[0]", "tw:[&_.page-header]:border-b-[length:1px]",
    "tw:[&_.page-header]:[border-bottom-style:solid]", "tw:[&_.page-header]:border-b-[color:#dfe7f1]", "tw:[&_.page-header_h1]:text-[color:#102b56]", "tw:[&_.page-header_h1]:text-[clamp(1.75rem,_2.3vw,_2.25rem)]",
    "tw:[&_.page-header_h1]:tracking-[-.045em]", "tw:[&_.stats-grid]:gap-y-[16px]", "tw:[&_.stats-grid]:gap-x-[16px]", "tw:[&_.stat-card]:pt-[20px]",
    "tw:[&_.stat-card]:pr-[20px]", "tw:[&_.stat-card]:pb-[20px]", "tw:[&_.stat-card]:pl-[20px]", "tw:[&_.stat-card]:border-t-[length:1px]",
    "tw:[&_.stat-card]:[border-top-style:solid]", "tw:[&_.stat-card]:border-t-[color:#e2e9f3]", "tw:[&_.stat-card]:border-r-[length:1px]", "tw:[&_.stat-card]:[border-right-style:solid]",
    "tw:[&_.stat-card]:border-r-[color:#e2e9f3]", "tw:[&_.stat-card]:border-b-[length:1px]", "tw:[&_.stat-card]:[border-bottom-style:solid]", "tw:[&_.stat-card]:border-b-[color:#e2e9f3]",
    "tw:[&_.stat-card]:border-l-[length:1px]", "tw:[&_.stat-card]:[border-left-style:solid]", "tw:[&_.stat-card]:border-l-[color:#e2e9f3]", "tw:[&_.stat-card]:rounded-[14px]",
    "tw:[&_.stat-card]:bg-[color:#fff]", "tw:[&_.stat-card]:[background-image:none]", "tw:[&_.stat-card]:[box-shadow:0_8px_22px_rgba(19,_55,_104,_.06)]", "tw:[&_.dashboard-grid]:gap-y-[18px]",
    "tw:[&_.dashboard-grid]:gap-x-[18px]", "tw:[&_.section-card]:pt-[21px]", "tw:viewport-720:[&_.section-card]:pt-[16px]", "tw:[&_.section-card]:pr-[21px]",
    "tw:viewport-720:[&_.section-card]:pr-[16px]", "tw:[&_.section-card]:pb-[21px]", "tw:viewport-720:[&_.section-card]:pb-[16px]", "tw:[&_.section-card]:pl-[21px]",
    "tw:viewport-720:[&_.section-card]:pl-[16px]", "tw:[&_.section-card]:border-t-[length:1px]", "tw:[&_.section-card]:[border-top-style:solid]", "tw:[&_.section-card]:border-t-[color:#e2e9f3]",
    "tw:[&_.section-card]:border-r-[length:1px]", "tw:[&_.section-card]:[border-right-style:solid]", "tw:[&_.section-card]:border-r-[color:#e2e9f3]", "tw:[&_.section-card]:border-b-[length:1px]",
    "tw:[&_.section-card]:[border-bottom-style:solid]", "tw:[&_.section-card]:border-b-[color:#e2e9f3]", "tw:[&_.section-card]:border-l-[length:1px]", "tw:[&_.section-card]:[border-left-style:solid]",
    "tw:[&_.section-card]:border-l-[color:#e2e9f3]", "tw:[&_.section-card]:rounded-[14px]", "tw:[&_.section-card]:bg-[color:#fff]", "tw:[&_.section-card]:[background-image:none]",
    "tw:[&_.section-card]:[box-shadow:0_8px_22px_rgba(19,_55,_104,_.05)]", "tw:[&_.section-card_+_.section-card]:border-t-[length:1px]", "tw:[&_.section-card_+_.section-card]:[border-top-style:solid]", "tw:[&_.section-card_+_.section-card]:border-t-[color:#e2e9f3]",
    "tw:max-w-[1240px]",
  ].join(" "),
  "tv_settings_toolbar": [
    "tv-settings-toolbar", "tw:flex", "tw:items-center", "tw:viewport-560:items-start",
    "tw:justify-end", "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:pt-[0]",
    "tw:pr-[0]", "tw:pb-[16px]", "tw:pl-[0]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dfe7f1]", "tw:[&_h1]:mt-[0]", "tw:[&_h1]:mr-[0]",
    "tw:[&_h1]:mb-[0]", "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[color:#102b56]", "tw:[&_h1]:text-[1.6rem]",
    "tw:[&_h1]:tracking-[-.035em]", "tw:[&_p]:mt-[4px]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#667d96]", "tw:[&_p]:text-[.8rem]", "tw:viewport-560:flex-col",
    "tw:viewport-560:[&_.button]:w-[100%]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "tv_settings_form": [
    "tv-settings-form", "tw:grid", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
  ].join(" "),
  "tv_config_section": [
    "tv-config-section", "tv-config-basics", "tw:grid", "tw:gap-y-[13px]",
    "tw:gap-x-[13px]", "tw:pt-[17px]", "tw:viewport-820:pt-[14px]", "tw:pr-[18px]",
    "tw:viewport-820:pr-[14px]", "tw:pb-[17px]", "tw:viewport-820:pb-[14px]", "tw:pl-[18px]",
    "tw:viewport-820:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dce7f1]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce7f1]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce7f1]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#dce7f1]", "tw:rounded-[11px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[box-shadow:0_6px_18px_rgb(24_57_93_/_.04)]",
  ].join(" "),
  "tv_config_section_head": [
    "tv-config-section-head", "tw:flex", "tw:items-center", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]", "tw:min-w-[0]", "tw:[&_>_span]:text-[color:#1d68ad]", "tw:[&_>_span]:text-[.65rem]",
    "tw:[&_>_span]:font-[800]", "tw:[&_>_span]:tracking-[.08em]", "tw:[&_>_strong]:text-[color:#173961]", "tw:[&_>_strong]:text-[.9rem]",
    "tw:[&_>_.button]:ml-[auto]", "tw:viewport-560:[&_>_.button]:ml-[0]", "tw:viewport-560:flex-wrap", "tw:[&_h2]:mt-[0]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#173961]",
    "tw:[&_h2]:text-[1.08rem]", "tw:[&_h2]:font-[400]", "tw:[&_h2]:leading-[1.35]",
  ].join(" "),
  "tv_config_fields": [
    "tv-config-fields", "tw:grid", "tw:grid-cols-[minmax(140px,_.55fr)_minmax(170px,_.8fr)_minmax(220px,_1fr)_minmax(250px,_1.15fr)]", "tw:viewport-1020:grid-cols-[repeat(2,_minmax(0,_1fr))]",
    "tw:viewport-620:grid-cols-[minmax(0,_1fr)]", "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:[&_.field]:grid",
    "tw:[&_.field]:gap-y-[6px]", "tw:[&_.field]:gap-x-[6px]", "tw:[&_.field]:text-[color:#455f7c]", "tw:[&_.field]:text-[.72rem]",
    "tw:[&_.field]:font-[750]", "tw:[&_.field]:min-w-[0]", "tw:[&_.field]:[align-content:start]", "tw:[&_.field]:grid-rows-[18px_38px_auto]",
    "tw:[&_input]:min-h-[36px]", "tw:[&_input]:pt-[6px]", "tw:[&_input]:pr-[9px]", "tw:[&_input]:pb-[6px]",
    "tw:[&_input]:pl-[9px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#cddbea]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#cddbea]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:#cddbea]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:#cddbea]", "tw:[&_input]:rounded-[7px]", "tw:[&_input]:text-[color:#193957]", "tw:[&_input]:bg-[color:#fff]",
    "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[.8rem]", "tw:[&_select]:min-h-[36px]", "tw:[&_select]:pt-[6px]",
    "tw:[&_select]:pr-[9px]", "tw:[&_select]:pb-[6px]", "tw:[&_select]:pl-[9px]", "tw:[&_select]:border-t-[length:1px]",
    "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:#cddbea]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]",
    "tw:[&_select]:border-r-[color:#cddbea]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:#cddbea]",
    "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#cddbea]", "tw:[&_select]:rounded-[7px]",
    "tw:[&_select]:text-[color:#193957]", "tw:[&_select]:bg-[color:#fff]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[.8rem]",
    "tw:[&_.field_>_label]:block", "tw:[&_.field_>_label]:[overflow-x:hidden]", "tw:[&_.field_>_label]:[overflow-y:hidden]", "tw:[&_.field_>_label]:text-ellipsis",
    "tw:[&_.field_>_label]:whitespace-nowrap", "tw:[&_.field_>_label]:leading-[18px]", "tw:[&_.field_>_label]:text-[color:#455f7c]", "tw:[&_.field_>_input]:[box-sizing:border-box]",
    "tw:[&_.field_>_input]:w-[100%]", "tw:[&_.field_>_input]:h-[38px]", "tw:[&_.field_>_input]:min-h-[38px]", "tw:[&_.field_>_input]:mt-[0]",
    "tw:[&_.field_>_input]:mr-[0]", "tw:[&_.field_>_input]:mb-[0]", "tw:[&_.field_>_input]:ml-[0]", "tw:[&_.field_>_select]:[box-sizing:border-box]",
    "tw:[&_.field_>_select]:w-[100%]", "tw:[&_.field_>_select]:h-[38px]", "tw:[&_.field_>_select]:min-h-[38px]", "tw:[&_.field_>_select]:mt-[0]",
    "tw:[&_.field_>_select]:mr-[0]", "tw:[&_.field_>_select]:mb-[0]", "tw:[&_.field_>_select]:ml-[0]", "tw:[&_.field_>_small]:text-[color:#6b8198]",
    "tw:[&_.field_>_small]:text-[.68rem]", "tw:[&_.field_>_small]:font-[400]", "tw:[&_.field_>_small]:leading-[1.3]",
  ].join(" "),
  "field": sharedUtilities.field,
  "field_2": [
    "field", "tv-prize-select", "tw:grid", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]", "tw:[&_input]:w-[100%]",
    "tw:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[14px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:text-[color:var(--text)]", "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[44px]",
    "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[14px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:var(--line)]",
    "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:var(--text)]",
    "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_input:focus]:[transform:translateY(-1px)]",
    "tw:[&_select:focus]:[outline:none]", "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]", "tw:[&_input[type=file]]:pt-[10px]",
    "tw:[&_input[type=file]]:pr-[14px]", "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]", "tw:[&_input[type=checkbox]]:w-[auto]",
    "tw:[&_input[type=checkbox]]:min-h-[auto]", "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]", "tw:[&_input[type=checkbox]]:pb-[0]",
    "tw:[&_input[type=checkbox]]:pl-[0]", "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]", "tw:[&_input[type=radio]]:pt-[0]",
    "tw:[&_input[type=radio]]:pr-[0]", "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]",
  ].join(" "),
  "tv_config_section_2": [
    "tv-config-section", "tw:grid", "tw:gap-y-[13px]", "tw:gap-x-[13px]",
    "tw:pt-[17px]", "tw:viewport-820:pt-[14px]", "tw:pr-[18px]", "tw:viewport-820:pr-[14px]",
    "tw:pb-[17px]", "tw:viewport-820:pb-[14px]", "tw:pl-[18px]", "tw:viewport-820:pl-[14px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dce7f1]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#dce7f1]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#dce7f1]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#dce7f1]",
    "tw:rounded-[11px]", "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[box-shadow:0_6px_18px_rgb(24_57_93_/_.04)]",
  ].join(" "),
  "tv_slide_options": [
    "tv-slide-options", "tw:grid", "tw:grid-cols-[repeat(3,_minmax(0,_1fr))]", "tw:viewport-820:grid-cols-[1fr]",
    "tw:gap-y-[9px]", "tw:gap-x-[9px]",
  ].join(" "),
  "tv_slide_option": [
    "tv-slide-option", "tw:grid", "tw:grid-cols-[18px_minmax(0,_1fr)]", "tw:[align-items:start]",
    "tw:gap-y-[9px]", "tw:gap-x-[9px]", "tw:min-h-[68px]", "tw:viewport-560:min-h-[60px]",
    "tw:pt-[11px]", "tw:pr-[11px]", "tw:pb-[11px]", "tw:pl-[11px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d9e5ef]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#d9e5ef]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#d9e5ef]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d9e5ef]",
    "tw:rounded-[8px]", "tw:text-[color:#526c87]", "tw:bg-[color:#fbfdff]", "tw:[background-image:none]",
    "tw:cursor-pointer", "tw:hover:border-t-[color:#a9cce7]", "tw:hover:border-r-[color:#a9cce7]", "tw:hover:border-b-[color:#a9cce7]",
    "tw:hover:border-l-[color:#a9cce7]", "tw:hover:bg-[color:#f5faff]", "tw:hover:[background-image:none]", "tw:[&_input]:absolute",
    "tw:[&_input]:opacity-[0]", "tw:[&_input:checked_+_.tv-slide-option-check]:border-t-[color:#1765ae]", "tw:[&_input:checked_+_.tv-slide-option-check]:border-r-[color:#1765ae]", "tw:[&_input:checked_+_.tv-slide-option-check]:border-b-[color:#1765ae]",
    "tw:[&_input:checked_+_.tv-slide-option-check]:border-l-[color:#1765ae]", "tw:[&_input:checked_+_.tv-slide-option-check]:text-[color:#fff]", "tw:[&_input:checked_+_.tv-slide-option-check]:bg-[color:#1765ae]", "tw:[&_input:checked_+_.tv-slide-option-check]:[background-image:none]",
    "tw:[&_b]:block", "tw:[&_b]:text-[color:#173a61]", "tw:[&_b]:text-[.78rem]", "tw:[&_small]:block",
    "tw:[&_small]:mt-[4px]", "tw:[&_small]:text-[color:#6d8299]", "tw:[&_small]:text-[.68rem]", "tw:[&_small]:leading-[1.35]",
  ].join(" "),
  "tv_slide_option_check": [
    "tv-slide-option-check", "tw:grid", "tw:w-[17px]", "tw:h-[17px]",
    "tw:place-items-center", "tw:mt-[1px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#aebfd0]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#aebfd0]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#aebfd0]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#aebfd0]", "tw:rounded-[4px]", "tw:text-[color:transparent]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:text-[.72rem]", "tw:font-[900]",
  ].join(" "),
  "tv_settings_actions": [
    "tv-settings-actions", "tw:flex", "tw:items-center", "tw:viewport-560:items-start",
    "tw:justify-between", "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:pt-[12px]",
    "tw:pr-[2px]", "tw:pb-[0]", "tw:pl-[2px]", "tw:[&_>_span]:text-[color:#70849a]",
    "tw:[&_>_span]:text-[.72rem]", "tw:[&_.button]:min-h-[34px]", "tw:viewport-560:flex-col", "tw:viewport-560:[&_.button]:w-[100%]",
  ].join(" "),
} as const;
