import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "stack_md_workspace_page_comanda_details_page": [
    "stack-md", "workspace-page", "comanda-details-page", "tw:grid",
    "tw:gap-y-[24px]", "tw:viewport-720:gap-y-[18px]", "tw:gap-x-[24px]", "tw:viewport-720:gap-x-[18px]",
    "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]", "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]",
    "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]", "tw:pt-[5px]",
    "tw:pr-[0]", "tw:pb-[44px]", "tw:pl-[0]", "tw:[&_.page-header]:pt-[4px]",
    "tw:[&_.page-header]:pr-[0]", "tw:[&_.page-header]:pb-[20px]", "tw:[&_.page-header]:pl-[0]", "tw:[&_.page-header]:border-b-[length:1px]",
    "tw:[&_.page-header]:[border-bottom-style:solid]", "tw:[&_.page-header]:border-b-[color:#dfe7f1]", "tw:[&_.page-header_h1]:text-[color:#102b56]", "tw:[&_.page-header_h1]:text-[clamp(1.75rem,_2.3vw,_2.25rem)]",
    "tw:[&_.page-header_h1]:tracking-[-.045em]", "tw:[&_.stats-grid]:gap-y-[16px]", "tw:[&_.stats-grid]:gap-x-[16px]", "tw:[&_.stat-card]:pt-[20px]",
    "tw:[&_.stat-card]:pr-[20px]", "tw:[&_.stat-card]:pb-[20px]", "tw:[&_.stat-card]:pl-[20px]", "tw:[&_.stat-card]:border-t-[length:1px]",
    "tw:[&_.stat-card]:[border-top-style:solid]", "tw:[&_.stat-card]:border-t-[color:#e2e9f3]", "tw:[&_.stat-card]:border-r-[length:1px]", "tw:[&_.stat-card]:[border-right-style:solid]",
    "tw:[&_.stat-card]:border-r-[color:#e2e9f3]", "tw:[&_.stat-card]:border-b-[length:1px]", "tw:[&_.stat-card]:[border-bottom-style:solid]", "tw:[&_.stat-card]:border-b-[color:#e2e9f3]",
    "tw:[&_.stat-card]:border-l-[length:1px]", "tw:[&_.stat-card]:[border-left-style:solid]", "tw:[&_.stat-card]:border-l-[color:#e2e9f3]", "tw:[&_.stat-card]:rounded-[14px]",
    "tw:[&_.stat-card]:bg-[color:#fff]", "tw:[&_.stat-card]:[background-image:none]", "tw:[&_.stat-card]:[box-shadow:0_8px_22px_rgba(19,_55,_104,_.06)]", "tw:[&_.dashboard-grid]:gap-y-[18px]",
    "tw:[&_.dashboard-grid]:gap-x-[18px]", "tw:[&_.section-card]:pt-[21px]", "tw:viewport-720:[&_.section-card]:pt-[16px]", "tw:[&_.section-card]:pr-[21px]",
    "tw:viewport-720:[&_.section-card]:pr-[16px]", "tw:[&_.section-card]:pb-[21px]", "tw:viewport-720:[&_.section-card]:pb-[16px]", "tw:[&_.section-card]:pl-[21px]",
    "tw:viewport-720:[&_.section-card]:pl-[16px]", "tw:[&_.section-card]:border-t-[length:1px]", "tw:[&_.section-card]:[border-top-style:solid]", "tw:[&_.section-card]:border-t-[color:#e2e9f3]",
    "tw:[&_.section-card]:border-r-[length:1px]", "tw:[&_.section-card]:[border-right-style:solid]", "tw:[&_.section-card]:border-r-[color:#e2e9f3]", "tw:[&_.section-card]:border-b-[length:1px]",
    "tw:[&_.section-card]:[border-bottom-style:solid]", "tw:[&_.section-card]:border-b-[color:#e2e9f3]", "tw:[&_.section-card]:border-l-[length:1px]", "tw:[&_.section-card]:[border-left-style:solid]",
    "tw:[&_.section-card]:border-l-[color:#e2e9f3]", "tw:[&_.section-card]:rounded-[14px]", "tw:[&_.section-card]:bg-[color:#fff]", "tw:[&_.section-card]:[background-image:none]",
    "tw:[&_.section-card]:[box-shadow:0_8px_22px_rgba(19,_55,_104,_.05)]", "tw:[&_.section-card_+_.section-card]:border-t-[length:1px]", "tw:[&_.section-card_+_.section-card]:[border-top-style:solid]", "tw:[&_.section-card_+_.section-card]:border-t-[color:#e2e9f3]",
    "tw:max-w-[840px]",
  ].join(" "),
  "page_header": sharedUtilities.pageHeader,
  "eyebrow": sharedUtilities.eyebrow,
  "muted": sharedUtilities.muted,
  "button": sharedUtilities.button,
  "section_card_comanda_receipt_card": [
    "section-card", "comanda-receipt-card", "tw:pt-[19px]", "tw:pr-[19px]",
    "tw:pb-[19px]", "tw:pl-[19px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[0]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:[box-shadow:none]", "tw:grid", "tw:gap-y-[15px]",
    "tw:gap-x-[15px]", "tw:[&_>_header]:flex", "tw:[&_>_header]:[align-items:start]", "tw:[&_>_header]:justify-between",
    "tw:[&_>_header]:gap-y-[14px]", "tw:[&_>_header]:gap-x-[14px]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]",
    "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#17365e]", "tw:[&_h2]:text-[1rem]",
    "tw:[&_p]:mt-[4px]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
    "tw:[&_p]:text-[color:#6a7d94]", "tw:[&_p]:text-[.78rem]", "tw:[&_>_header_>_strong]:text-[color:#19724f]", "tw:[&_>_header_>_strong]:text-[1.1rem]",
  ].join(" "),
  "comanda_receipt_items": [
    "comanda-receipt-items", "tw:grid", "tw:[&_>_div]:flex", "tw:[&_>_div]:items-center",
    "tw:[&_>_div]:justify-between", "tw:[&_>_div]:gap-y-[14px]", "tw:[&_>_div]:gap-x-[14px]", "tw:[&_>_div]:pt-[11px]",
    "tw:[&_>_div]:pr-[0]", "tw:[&_>_div]:pb-[11px]", "tw:[&_>_div]:pl-[0]", "tw:[&_>_div]:border-t-[length:1px]",
    "tw:[&_>_div]:[border-top-style:solid]", "tw:[&_>_div]:border-t-[color:#e4ebf2]", "tw:[&_>_div]:text-[color:#29435e]", "tw:[&_>_div]:text-[.84rem]",
    "tw:[&_span]:grid", "tw:[&_span]:gap-y-[3px]", "tw:[&_span]:gap-x-[3px]", "tw:[&_small]:text-[color:#73869b]",
    "tw:[&_small]:text-[.72rem]", "tw:[&_b]:text-[color:#14375f]", "tw:[&_strong]:text-[color:#14375f]",
  ].join(" "),
} as const;
