import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "athlete_portal_page": sharedUtilities.athletePortalPage,
  "athlete_portal_hero": sharedUtilities.athletePortalHero,
  "athlete_portal_hero_inner": sharedUtilities.athletePortalHeroInner,
  "athlete_portal_brand": sharedUtilities.athletePortalBrand,
  "athlete_portal_mark": sharedUtilities.athletePortalMark,
  "athlete_portal_brand_copy": sharedUtilities.athletePortalBrandCopy,
  "athlete_portal_global_actions": [
    "athlete-portal-global-actions", "tw:flex", "tw:flex-wrap", "tw:items-center",
    "tw:gap-y-[10px]", "tw:gap-x-[10px]",
  ].join(" "),
  "athlete_portal_profile_link": [
    "athlete-portal-profile-link", "tw:pt-[10px]", "tw:viewport-700:pt-[6px]", "tw:pr-[16px]",
    "tw:viewport-700:pr-[7px]", "tw:pb-[10px]", "tw:viewport-700:pb-[6px]", "tw:pl-[16px]",
    "tw:viewport-700:pl-[7px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(134_181_220_/_.26)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(134_181_220_/_.26)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(134_181_220_/_.26)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgb(134_181_220_/_.26)]", "tw:rounded-[12px]", "tw:text-[color:#effbff]", "tw:bg-[color:transparent]",
    "tw:[background-image:linear-gradient(135deg,_rgb(22_54_87_/_.9),_rgb(17_40_66_/_.88))]", "tw:text-[.88rem]", "tw:viewport-700:text-[.64rem]", "tw:font-[800]",
    "tw:[text-decoration:none]", "tw:whitespace-nowrap", "tw:min-h-[48px]", "tw:viewport-700:min-h-[34px]",
    "tw:inline-flex", "tw:items-center", "tw:hover:text-[color:#073f68]", "tw:hover:bg-[color:#d8ffef]",
    "tw:hover:[background-image:none]", "tw:viewport-700:ml-[auto]", "tw:viewport-700:[padding-inline:9px]",
  ].join(" "),
  "athlete_portal_logout": [
    "athlete-portal-logout", "tw:[flex:0_0_auto]", "tw:[&_button]:inline-flex", "tw:[&_button]:min-h-[48px]",
    "tw:viewport-700:[&_button]:min-h-[40px]", "tw:[&_button]:items-center", "tw:[&_button]:justify-center", "tw:[&_button]:pt-[10px]",
    "tw:viewport-700:[&_button]:pt-[8px]", "tw:[&_button]:pr-[16px]", "tw:viewport-700:[&_button]:pr-[12px]", "tw:[&_button]:pb-[10px]",
    "tw:viewport-700:[&_button]:pb-[8px]", "tw:[&_button]:pl-[16px]", "tw:viewport-700:[&_button]:pl-[12px]", "tw:[&_button]:border-t-[length:1px]",
    "tw:[&_button]:[border-top-style:solid]", "tw:[&_button]:border-t-[color:rgb(133_184_205_/_.3)]", "tw:[&_button]:border-r-[length:1px]", "tw:[&_button]:[border-right-style:solid]",
    "tw:[&_button]:border-r-[color:rgb(133_184_205_/_.3)]", "tw:[&_button]:border-b-[length:1px]", "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:rgb(133_184_205_/_.3)]",
    "tw:[&_button]:border-l-[length:1px]", "tw:[&_button]:[border-left-style:solid]", "tw:[&_button]:border-l-[color:rgb(133_184_205_/_.3)]", "tw:[&_button]:rounded-[12px]",
    "tw:[&_button]:text-[color:#d9f4f5]", "tw:[&_button]:bg-[color:rgb(9_32_52_/_.74)]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:[font:inherit]",
    "tw:[&_button]:text-[.82rem]", "tw:[&_button]:font-[800]", "tw:[&_button]:cursor-pointer", "tw:[&_button:hover]:border-t-[color:#66e1bd]",
    "tw:[&_button:hover]:border-r-[color:#66e1bd]", "tw:[&_button:hover]:border-b-[color:#66e1bd]", "tw:[&_button:hover]:border-l-[color:#66e1bd]", "tw:[&_button:hover]:text-[color:#fff]",
    "tw:[&_button:hover]:bg-[color:#134b5d]", "tw:[&_button:hover]:[background-image:none]", "tw:[&_button:focus-visible]:[outline:2px_solid_#70f0c6]", "tw:[&_button:focus-visible]:[outline-offset:3px]",
  ].join(" "),
  "athlete_portal_content_panel_global_athlete_arenas": [
    "athlete-portal-content-panel", "global-athlete-arenas", "tw:w-[min(calc(100%_-_32px),_1060px)]", "tw:viewport-700:w-[calc(100%_-_28px)]",
    "tw:[margin-inline:auto]", "tw:mt-[22px]", "tw:viewport-700:mt-[16px]", "tw:pt-[26px]",
    "tw:viewport-700:pt-[16px]", "tw:pr-[26px]", "tw:viewport-700:pr-[16px]", "tw:pb-[26px]",
    "tw:viewport-700:pb-[16px]", "tw:pl-[26px]", "tw:viewport-700:pl-[16px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(120_162_185_/_.2)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:rgb(120_162_185_/_.2)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(120_162_185_/_.2)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(120_162_185_/_.2)]", "tw:rounded-[15px]",
    "tw:bg-[color:#0d1b28]", "tw:[background-image:none]", "tw:[box-shadow:0_18px_42px_rgb(0_0_0_/_.2)]", "tw:[&_>_header]:grid",
    "tw:[&_>_header]:gap-y-[4px]", "tw:[&_>_header]:gap-x-[4px]", "tw:[&_>_header]:pb-[17px]", "tw:[&_>_header]:border-b-[length:1px]",
    "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-t-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-r-[color:rgb(135_178_196_/_.16)]",
    "tw:[&_>_header]:border-l-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header_span]:text-[color:#57d7ae]", "tw:[&_>_header_span]:text-[.66rem]", "tw:[&_>_header_span]:font-[900]",
    "tw:[&_>_header_span]:tracking-[.12em]", "tw:[&_>_header_h2]:mt-[0]", "tw:[&_>_header_h2]:mr-[0]", "tw:[&_>_header_h2]:mb-[0]",
    "tw:[&_>_header_h2]:ml-[0]", "tw:[&_>_header_h2]:text-[color:#f2f9fc]", "tw:[&_>_header_h2]:text-[1.3rem]", "tw:[&_>_div]:grid",
    "tw:[&_>_div]:gap-y-[9px]", "tw:[&_>_div]:gap-x-[9px]", "tw:[&_>_div]:mt-[16px]", "tw:[&_>_div_>_a]:grid",
    "tw:[&_>_div_>_a]:grid-cols-[42px_minmax(0,_1fr)_auto]", "tw:[&_>_div_>_a]:items-center", "tw:[&_>_div_>_a]:gap-y-[11px]", "tw:[&_>_div_>_a]:gap-x-[11px]",
    "tw:[&_>_div_>_a]:pt-[11px]", "tw:[&_>_div_>_a]:pr-[12px]", "tw:[&_>_div_>_a]:pb-[11px]", "tw:[&_>_div_>_a]:pl-[12px]",
    "tw:[&_>_div_>_a]:border-t-[length:1px]", "tw:[&_>_div_>_a]:[border-top-style:solid]", "tw:[&_>_div_>_a]:border-t-[color:#cfe2ea]", "tw:[&_>_div_>_a]:border-r-[length:1px]",
    "tw:[&_>_div_>_a]:[border-right-style:solid]", "tw:[&_>_div_>_a]:border-r-[color:#cfe2ea]", "tw:[&_>_div_>_a]:border-b-[length:1px]", "tw:[&_>_div_>_a]:[border-bottom-style:solid]",
    "tw:[&_>_div_>_a]:border-b-[color:#cfe2ea]", "tw:[&_>_div_>_a]:border-l-[length:1px]", "tw:[&_>_div_>_a]:[border-left-style:solid]", "tw:[&_>_div_>_a]:border-l-[color:#cfe2ea]",
    "tw:[&_>_div_>_a]:rounded-[10px]", "tw:[&_>_div_>_a]:text-[color:#174660]", "tw:[&_>_div_>_a]:bg-[color:#fbfeff]", "tw:[&_>_div_>_a]:[background-image:none]",
    "tw:[&_>_div_>_a]:[text-decoration:none]", "tw:[&_>_div_>_a:hover]:border-t-[color:#73bfa9]", "tw:[&_>_div_>_a:hover]:border-r-[color:#73bfa9]", "tw:[&_>_div_>_a:hover]:border-b-[color:#73bfa9]",
    "tw:[&_>_div_>_a:hover]:border-l-[color:#73bfa9]", "tw:[&_>_div_>_a:hover]:bg-[color:#f1fbf7]", "tw:[&_>_div_>_a:hover]:[background-image:none]", "tw:[&_img]:w-[42px]",
    "tw:[&_img]:h-[42px]", "tw:[&_img]:rounded-[9px]", "tw:[&_img]:[object-fit:contain]", "tw:[&_img]:bg-[color:#fff]",
    "tw:[&_img]:[background-image:none]", "tw:[&_b]:w-[42px]", "tw:[&_b]:h-[42px]", "tw:[&_b]:rounded-[9px]",
    "tw:[&_b]:[object-fit:contain]", "tw:[&_b]:bg-[color:#fff]", "tw:[&_b]:[background-image:none]", "tw:[&_b]:grid",
    "tw:[&_b]:place-items-center", "tw:[&_b]:text-[color:#08765f]", "tw:[&_span]:grid", "tw:[&_span]:gap-y-[3px]",
    "tw:[&_span]:gap-x-[3px]", "tw:[&_strong]:text-[.86rem]", "tw:[&_small]:text-[color:#6a8191]", "tw:[&_small]:text-[.72rem]",
    "tw:[&_i]:text-[color:#08765f]", "tw:[&_i]:not-italic", "tw:[&_i]:font-[900]",
  ].join(" "),
} as const;
