import Link from "next/link";
import { SafeActionForm } from "@/components/forms/safe-action-form";
import { SubmitButton } from "@/components/forms/submit-button";
import { SectionCard } from "@/components/section-card";
import styles from "./page.module.css";
import { closeCashRegisterAction, createCashMovementAction, openCashRegisterAction } from "@/lib/actions/cash-register";
import { requireModuleView } from "@/lib/auth/guards";
import { cashReferenceDate } from "@/lib/finance/cash-day";
import { withArenaTransaction } from "@/lib/rls";

const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value / 100);

export default async function CashRegisterPage() {
  const auth = await requireModuleView("pos");
  const register = await withArenaTransaction(auth.arenaId, (tx) => tx.cashRegister.findUnique({ where: { arenaId_referenceDate: { arenaId: auth.arenaId, referenceDate: cashReferenceDate() } }, include: { movements: { orderBy: { createdAt: "desc" } } } }));
  const shortcut = <div className="cash-register-shortcut"><Link className="button button-small" href="/pdv">Produtos e serviços</Link><Link className="button button-small" href="/relatorios/caixa">Relatório de caixa</Link></div>;

  if (!register || register.status !== "OPEN") return <div className="stack-md cash-register-page">{shortcut}<SectionCard title={register ? "Caixa encerrado hoje" : "Abrir caixa"} description={register ? `Fechado com ${money(register.countedAmountCents ?? 0)}. O próximo caixa poderá ser aberto amanhã.` : "Informe o fundo inicial para iniciar a operação de hoje."}>{register ? <div className={styles.summaryGrid}><article><span>Fundo inicial</span><strong>{money(register.openingAmountCents)}</strong></article><article><span>Saldo esperado</span><strong>{money(register.expectedAmountCents)}</strong></article><article><span>Diferença</span><strong>{money(register.differenceCents ?? 0)}</strong></article></div> : <SafeActionForm action={openCashRegisterAction} className="grid-form" successMessage="Caixa aberto."><label className="field">Fundo de caixa<input name="openingAmount" inputMode="decimal" defaultValue="0,00" required /></label><label className="field form-full">Observação de abertura<input name="openingNotes" placeholder="Ex.: troco inicial" /></label><div className="field field-submit"><SubmitButton className="button button-primary button-small" label="Abrir caixa" pendingLabel="Abrindo..." /></div></SafeActionForm>}</SectionCard></div>;

  return <div className="stack-md cash-register-page">{shortcut}<section className={styles.summaryGrid}><article><span>Fundo inicial</span><strong>{money(register.openingAmountCents)}</strong></article><article><span>Saldo esperado</span><strong>{money(register.expectedAmountCents)}</strong></article><article><span>Movimentos</span><strong>{register.movements.length}</strong></article></section><div className={styles.operationGrid}><SectionCard title="Sangria ou suprimento"><SafeActionForm action={createCashMovementAction} className="grid-form" resetOnSuccess successMessage="Movimentação registrada."><input type="hidden" name="registerId" value={register.id} /><label className="field">Tipo<select name="type"><option value="SUPPLY">Suprimento</option><option value="WITHDRAWAL">Sangria</option></select></label><label className="field">Valor<input name="amount" inputMode="decimal" placeholder="0,00" required /></label><label className="field form-full">Descrição<input name="description" placeholder="Ex.: retirada para depósito" /></label><div className="field field-submit"><SubmitButton className="button button-small button-primary" label="Registrar" pendingLabel="Registrando..." /></div></SafeActionForm></SectionCard><SectionCard title="Fechar caixa"><SafeActionForm action={closeCashRegisterAction} className="grid-form" successMessage="Caixa encerrado."><input type="hidden" name="registerId" value={register.id} /><label className="field">Valor contado<input name="countedAmount" inputMode="decimal" placeholder="0,00" required /></label><label className="field form-full">Observação de fechamento<input name="closingNotes" placeholder="Ex.: diferença justificada" /></label><div className="field field-submit"><SubmitButton className="button button-danger button-small" label="Fechar caixa" pendingLabel="Fechando..." /></div></SafeActionForm></SectionCard></div><SectionCard title="Movimentações de hoje"><div className={styles.movementList}>{register.movements.map((item) => <article key={item.id}><span><strong>{item.type === "SUPPLY" ? "Suprimento" : item.type === "SALE" ? "Venda" : "Sangria"}</strong>{item.description || "Sem observação"}</span><b className={item.amountCents < 0 ? styles.negative : styles.positive}>{item.amountCents < 0 ? "−" : "+"}{money(Math.abs(item.amountCents))}</b></article>)}{!register.movements.length ? <p className="muted">Nenhuma movimentação registrada.</p> : null}</div></SectionCard></div>;
}
