import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "nfe_import_start": [
    "nfe-import-start", "tw:flex", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:[align-items:end]", "tw:flex-wrap", "tw:[&_.field]:min-w-[min(100%,440px)]", "tw:[&_.field]:[flex:1]",
    "tw:viewport-760:[&_.button]:w-[100%]",
  ].join(" "),
  "field": sharedUtilities.field,
  "nfe_import_reading": [
    "nfe-import-reading", "tw:[align-self:end]", "tw:pb-[8px]", "tw:text-[color:#2b679e]",
    "tw:text-[.76rem]", "tw:font-[750]",
  ].join(" "),
  "command_modal_backdrop": sharedUtilities.commandModalBackdrop,
  "nfe_reconcile_modal": [
    "nfe-reconcile-modal", "tw:w-[min(1100px,calc(100vw_-_28px))]", "tw:max-h-[calc(100vh_-_32px)]", "tw:[overflow-x:auto]",
    "tw:[overflow-y:auto]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#cbd9ea]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#cbd9ea]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#cbd9ea]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#cbd9ea]", "tw:rounded-[16px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[box-shadow:0_24px_70px_rgba(11,36,66,.28)]", "tw:[&_>_header]:pt-[20px]", "tw:viewport-760:[&_>_header]:pt-[16px]", "tw:[&_>_header]:pr-[24px]",
    "tw:viewport-760:[&_>_header]:pr-[16px]", "tw:[&_>_header]:pb-[20px]", "tw:viewport-760:[&_>_header]:pb-[16px]", "tw:[&_>_header]:pl-[24px]",
    "tw:viewport-760:[&_>_header]:pl-[16px]", "tw:[&_>_header]:flex", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[18px]",
    "tw:[&_>_header]:gap-x-[18px]", "tw:[&_>_header]:items-center", "tw:viewport-760:[&_>_header]:items-start", "tw:[&_>_header]:border-b-[length:1px]",
    "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#dce7f4]", "tw:[&_>_footer]:pt-[20px]", "tw:viewport-760:[&_>_footer]:pt-[16px]",
    "tw:[&_>_footer]:pr-[24px]", "tw:viewport-760:[&_>_footer]:pr-[16px]", "tw:[&_>_footer]:pb-[20px]", "tw:viewport-760:[&_>_footer]:pb-[16px]",
    "tw:[&_>_footer]:pl-[24px]", "tw:viewport-760:[&_>_footer]:pl-[16px]", "tw:[&_>_footer]:flex", "tw:[&_>_footer]:justify-between",
    "tw:[&_>_footer]:gap-y-[18px]", "tw:[&_>_footer]:gap-x-[18px]", "tw:[&_>_footer]:items-center", "tw:viewport-760:[&_>_footer]:items-start",
    "tw:[&_>_footer]:border-b-[length:0]", "tw:[&_>_footer]:[border-bottom-style:none]", "tw:[&_>_footer]:border-b-[color:currentColor]", "tw:[&_>_footer]:border-t-[length:1px]",
    "tw:[&_>_footer]:[border-top-style:solid]", "tw:[&_>_footer]:border-t-[color:#dce7f4]", "tw:[&_>_footer_>_div]:flex", "tw:[&_>_footer_>_div]:gap-y-[8px]",
    "tw:[&_>_footer_>_div]:gap-x-[8px]", "tw:[&_h2]:mt-[2px]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[4px]",
    "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#16345e]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#60718b]", "tw:viewport-760:[&_>_footer]:flex-col",
    "tw:viewport-760:[&_>_footer_>_div]:w-[100%]", "tw:viewport-760:[&_>_footer_button]:[flex:1]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "nfe_reconcile_list": [
    "nfe-reconcile-list", "tw:pt-[16px]", "tw:viewport-760:pt-[12px]", "tw:pr-[24px]",
    "tw:viewport-760:pr-[12px]", "tw:pb-[16px]", "tw:viewport-760:pb-[12px]", "tw:pl-[24px]",
    "tw:viewport-760:pl-[12px]", "tw:grid", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
    "tw:[&_article]:grid", "tw:[&_article]:grid-cols-[minmax(170px,1.4fr)_minmax(180px,1.4fr)_minmax(105px,.7fr)_minmax(95px,.55fr)_minmax(105px,.7fr)]", "tw:viewport-760:[&_article]:grid-cols-[1fr_1fr]", "tw:[&_article]:gap-y-[10px]",
    "tw:[&_article]:gap-x-[10px]", "tw:[&_article]:[align-items:end]", "tw:[&_article]:pt-[14px]", "tw:[&_article]:pr-[14px]",
    "tw:[&_article]:pb-[14px]", "tw:[&_article]:pl-[14px]", "tw:[&_article]:border-t-[length:1px]", "tw:[&_article]:[border-top-style:solid]",
    "tw:[&_article]:border-t-[color:#d6e2ef]", "tw:[&_article]:border-r-[length:1px]", "tw:[&_article]:[border-right-style:solid]", "tw:[&_article]:border-r-[color:#d6e2ef]",
    "tw:[&_article]:border-b-[length:1px]", "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#d6e2ef]", "tw:[&_article]:border-l-[length:1px]",
    "tw:[&_article]:[border-left-style:solid]", "tw:[&_article]:border-l-[color:#d6e2ef]", "tw:[&_article]:rounded-[10px]", "tw:[&_article]:bg-[color:#fbfdff]",
    "tw:[&_article]:[background-image:none]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[5px]", "tw:[&_label]:gap-x-[5px]",
    "tw:[&_label]:text-[color:#365170]", "tw:[&_label]:text-[.74rem]", "tw:[&_label]:font-[700]", "tw:[&_input]:min-h-[36px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#b8cae0]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#b8cae0]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:#b8cae0]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#b8cae0]",
    "tw:[&_input]:rounded-[7px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[9px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[9px]", "tw:[&_input]:text-[color:#15355f]", "tw:[&_input]:bg-[color:#fff]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:[font:inherit]", "tw:[&_select]:min-h-[36px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]",
    "tw:[&_select]:border-t-[color:#b8cae0]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#b8cae0]",
    "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:#b8cae0]", "tw:[&_select]:border-l-[length:1px]",
    "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#b8cae0]", "tw:[&_select]:rounded-[7px]", "tw:[&_select]:pt-[0]",
    "tw:[&_select]:pr-[9px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[9px]", "tw:[&_select]:text-[color:#15355f]",
    "tw:[&_select]:bg-[color:#fff]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:[font:inherit]", "tw:viewport-760:[&_article_>_label:nth-child(2)]:[grid-column:1_/_-1]",
  ].join(" "),
  "nfe_reconcile_item_title": [
    "nfe-reconcile-item-title", "tw:grid", "tw:gap-y-[3px]", "tw:gap-x-[3px]",
    "tw:[&_strong]:text-[color:#173b68]", "tw:[&_small]:text-[color:#647993]", "tw:viewport-760:[grid-column:1_/_-1]",
  ].join(" "),
  "button": sharedUtilities.button,
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
} as const;
