ALTER TABLE "TvSponsor"
  ADD COLUMN "playerId" TEXT,
  ADD COLUMN "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "installments" INTEGER NOT NULL DEFAULT 12,
  ADD COLUMN "dueDay" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN "discountMode" TEXT NOT NULL DEFAULT 'AMOUNT',
  ADD COLUMN "discountValue" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "discountApplication" TEXT NOT NULL DEFAULT 'ONE_TIME';

CREATE INDEX "TvSponsor_playerId_idx" ON "TvSponsor"("playerId");

ALTER TABLE "TvSponsor"
  ADD CONSTRAINT "TvSponsor_playerId_fkey"
  FOREIGN KEY ("playerId") REFERENCES "Player"("id") ON DELETE SET NULL ON UPDATE CASCADE;
