import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "stack_md_workspace_page_teacher_detail_page": [
    "stack-md", "workspace-page", "teacher-detail-page", "tw:grid",
    "tw:gap-y-[24px]", "tw:viewport-720:gap-y-[18px]", "tw:gap-x-[24px]", "tw:viewport-720:gap-x-[18px]",
    "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]", "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]",
    "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]", "tw:pt-[5px]",
    "tw:pr-[0]", "tw:pb-[44px]", "tw:pl-[0]", "tw:[&_.page-header]:pt-[4px]",
    "tw:[&_.page-header]:pr-[0]", "tw:[&_.page-header]:pb-[20px]", "tw:[&_.page-header]:pl-[0]", "tw:[&_.page-header]:border-b-[length:1px]",
    "tw:[&_.page-header]:[border-bottom-style:solid]", "tw:[&_.page-header]:border-b-[color:#dfe7f1]", "tw:[&_.page-header_h1]:text-[color:#102b56]", "tw:[&_.page-header_h1]:text-[clamp(1.75rem,_2.3vw,_2.25rem)]",
    "tw:[&_.page-header_h1]:tracking-[-.045em]", "tw:[&_.stats-grid]:gap-y-[16px]", "tw:[&_.stats-grid]:gap-x-[16px]", "tw:[&_.stat-card]:pt-[20px]",
    "tw:[&_.stat-card]:pr-[20px]", "tw:[&_.stat-card]:pb-[20px]", "tw:[&_.stat-card]:pl-[20px]", "tw:[&_.stat-card]:border-t-[length:1px]",
    "tw:[&_.stat-card]:[border-top-style:solid]", "tw:[&_.stat-card]:border-t-[color:#e2e9f3]", "tw:[&_.stat-card]:border-r-[length:1px]", "tw:[&_.stat-card]:[border-right-style:solid]",
    "tw:[&_.stat-card]:border-r-[color:#e2e9f3]", "tw:[&_.stat-card]:border-b-[length:1px]", "tw:[&_.stat-card]:[border-bottom-style:solid]", "tw:[&_.stat-card]:border-b-[color:#e2e9f3]",
    "tw:[&_.stat-card]:border-l-[length:1px]", "tw:[&_.stat-card]:[border-left-style:solid]", "tw:[&_.stat-card]:border-l-[color:#e2e9f3]", "tw:[&_.stat-card]:rounded-[14px]",
    "tw:[&_.stat-card]:bg-[color:#fff]", "tw:[&_.stat-card]:[background-image:none]", "tw:[&_.stat-card]:[box-shadow:0_8px_22px_rgba(19,_55,_104,_.06)]", "tw:[&_.dashboard-grid]:gap-y-[18px]",
    "tw:[&_.dashboard-grid]:gap-x-[18px]", "tw:[&_.section-card]:pt-[21px]", "tw:viewport-720:[&_.section-card]:pt-[16px]", "tw:[&_.section-card]:pr-[21px]",
    "tw:viewport-720:[&_.section-card]:pr-[16px]", "tw:[&_.section-card]:pb-[21px]", "tw:viewport-720:[&_.section-card]:pb-[16px]", "tw:[&_.section-card]:pl-[21px]",
    "tw:viewport-720:[&_.section-card]:pl-[16px]", "tw:[&_.section-card]:border-t-[length:1px]", "tw:[&_.section-card]:[border-top-style:solid]", "tw:[&_.section-card]:border-t-[color:#e2e9f3]",
    "tw:[&_.section-card]:border-r-[length:1px]", "tw:[&_.section-card]:[border-right-style:solid]", "tw:[&_.section-card]:border-r-[color:#e2e9f3]", "tw:[&_.section-card]:border-b-[length:1px]",
    "tw:[&_.section-card]:[border-bottom-style:solid]", "tw:[&_.section-card]:border-b-[color:#e2e9f3]", "tw:[&_.section-card]:border-l-[length:1px]", "tw:[&_.section-card]:[border-left-style:solid]",
    "tw:[&_.section-card]:border-l-[color:#e2e9f3]", "tw:[&_.section-card]:rounded-[14px]", "tw:[&_.section-card]:bg-[color:#fff]", "tw:[&_.section-card]:[background-image:none]",
    "tw:[&_.section-card]:[box-shadow:0_8px_22px_rgba(19,_55,_104,_.05)]", "tw:[&_.section-card_+_.section-card]:border-t-[length:1px]", "tw:[&_.section-card_+_.section-card]:[border-top-style:solid]", "tw:[&_.section-card_+_.section-card]:border-t-[color:#e2e9f3]",
    "tw:max-w-[1460px]", "tw:[&_.teacher-page-actions]:gap-y-[12px]", "tw:[&_.teacher-page-actions]:gap-x-[12px]", "tw:[&_.teacher-page-actions]:pt-[64px]",
    "tw:viewport-760:[&_.teacher-page-actions]:pt-[0]", "tw:[&_.teacher-page-actions_.status-badge]:pt-[9px]", "tw:[&_.teacher-page-actions_.status-badge]:pr-[13px]", "tw:[&_.teacher-page-actions_.status-badge]:pb-[9px]",
    "tw:[&_.teacher-page-actions_.status-badge]:pl-[13px]", "tw:[&_.teacher-page-actions_.status-badge]:border-t-[length:1px]", "tw:[&_.teacher-page-actions_.status-badge]:[border-top-style:solid]", "tw:[&_.teacher-page-actions_.status-badge]:border-t-[color:#b9ecd0]",
    "tw:[&_.teacher-page-actions_.status-badge]:border-r-[length:1px]", "tw:[&_.teacher-page-actions_.status-badge]:[border-right-style:solid]", "tw:[&_.teacher-page-actions_.status-badge]:border-r-[color:#b9ecd0]", "tw:[&_.teacher-page-actions_.status-badge]:border-b-[length:1px]",
    "tw:[&_.teacher-page-actions_.status-badge]:[border-bottom-style:solid]", "tw:[&_.teacher-page-actions_.status-badge]:border-b-[color:#b9ecd0]", "tw:[&_.teacher-page-actions_.status-badge]:border-l-[length:1px]", "tw:[&_.teacher-page-actions_.status-badge]:[border-left-style:solid]",
    "tw:[&_.teacher-page-actions_.status-badge]:border-l-[color:#b9ecd0]", "tw:[&_.teacher-page-actions_.status-badge]:rounded-[7px]", "tw:[&_.teacher-page-actions_.status-badge]:text-[color:#0f9d59]", "tw:[&_.teacher-page-actions_.status-badge]:bg-[color:#effcf4]",
    "tw:[&_.teacher-page-actions_.status-badge]:[background-image:none]", "tw:[&_.teacher-page-actions_.status-badge]:text-[.82rem]", "tw:[&_.teacher-archive-form_.button]:min-h-[40px]", "tw:[&_.teacher-archive-form_.button]:[padding-inline:15px]",
    "tw:[&_.teacher-archive-form_.button]:border-t-[color:#ffaeae]", "tw:[&_.teacher-archive-form_.button]:border-r-[color:#ffaeae]", "tw:[&_.teacher-archive-form_.button]:border-b-[color:#ffaeae]", "tw:[&_.teacher-archive-form_.button]:border-l-[color:#ffaeae]",
    "tw:[&_.teacher-archive-form_.button]:rounded-[7px]", "tw:[&_.teacher-archive-form_.button]:bg-[color:#fff]", "tw:[&_.teacher-archive-form_.button]:[background-image:none]", "tw:[&_.teacher-archive-form_.button]:text-[color:#ec3c3c]",
    "tw:[&_.teacher-archive-form_.button]:[box-shadow:none]", "tw:[&_.teacher-detail-tabs]:gap-y-[20px]", "tw:viewport-760:[&_.teacher-detail-tabs]:gap-y-[0]", "tw:[&_.teacher-detail-tabs]:gap-x-[20px]",
    "tw:viewport-760:[&_.teacher-detail-tabs]:gap-x-[0]", "tw:[&_.teacher-detail-tabs]:pb-[0]", "tw:[&_.teacher-detail-tabs]:border-t-[color:#e0e8f1]", "tw:[&_.teacher-detail-tabs]:border-r-[color:#e0e8f1]",
    "tw:[&_.teacher-detail-tabs]:border-b-[color:#e0e8f1]", "tw:[&_.teacher-detail-tabs]:border-l-[color:#e0e8f1]", "tw:[&_.teacher-detail-tabs_a]:pt-[12px]", "tw:viewport-760:[&_.teacher-detail-tabs_a]:pt-[10px]",
    "tw:[&_.teacher-detail-tabs_a]:pr-[17px]", "tw:viewport-760:[&_.teacher-detail-tabs_a]:pr-[12px]", "tw:[&_.teacher-detail-tabs_a]:pb-[14px]", "tw:viewport-760:[&_.teacher-detail-tabs_a]:pb-[12px]",
    "tw:[&_.teacher-detail-tabs_a]:pl-[17px]", "tw:viewport-760:[&_.teacher-detail-tabs_a]:pl-[12px]", "tw:[&_.teacher-detail-tabs_a]:text-[color:#61718a]", "tw:[&_.teacher-detail-tabs_a]:text-[.9rem]",
    "tw:viewport-760:[&_.teacher-detail-tabs_a]:text-[.78rem]", "tw:[&_.teacher-detail-tabs_a.is-active]:border-t-[color:#1464e4]", "tw:[&_.teacher-detail-tabs_a.is-active]:border-r-[color:#1464e4]", "tw:[&_.teacher-detail-tabs_a.is-active]:border-b-[color:#1464e4]",
    "tw:[&_.teacher-detail-tabs_a.is-active]:border-l-[color:#1464e4]", "tw:[&_.teacher-detail-tabs_a.is-active]:text-[color:#1260d4]", "tw:[&_.teacher-detail-metrics]:gap-y-[16px]", "tw:[&_.teacher-detail-metrics]:gap-x-[16px]",
    "tw:[&_.teacher-detail-metrics_article]:flex", "tw:[&_.teacher-detail-metrics_article]:items-center", "tw:[&_.teacher-detail-metrics_article]:gap-y-[13px]", "tw:[&_.teacher-detail-metrics_article]:gap-x-[13px]",
    "tw:[&_.teacher-detail-metrics_article]:min-h-[92px]", "tw:[&_.teacher-detail-metrics_article]:pt-[14px]", "tw:[&_.teacher-detail-metrics_article]:pr-[14px]", "tw:[&_.teacher-detail-metrics_article]:pb-[14px]",
    "tw:[&_.teacher-detail-metrics_article]:pl-[14px]", "tw:[&_.teacher-detail-metrics_article]:border-t-[color:#dce6f1]", "tw:[&_.teacher-detail-metrics_article]:border-r-[color:#dce6f1]", "tw:[&_.teacher-detail-metrics_article]:border-b-[color:#dce6f1]",
    "tw:[&_.teacher-detail-metrics_article]:border-l-[color:#dce6f1]", "tw:[&_.teacher-detail-metrics_article]:rounded-[13px]", "tw:[&_.teacher-detail-metrics_article]:[box-shadow:0_6px_16px_rgb(13_50_96_/_.035)]", "tw:[&_.teacher-detail-metrics_article_>_div]:grid",
    "tw:[&_.teacher-detail-metrics_article_>_div]:gap-y-[3px]", "tw:[&_.teacher-detail-metrics_article_>_div]:gap-x-[3px]", "tw:[&_.teacher-detail-metrics_article_>_div]:min-w-[0]", "tw:[&_.teacher-detail-metrics_span:not(.teacher-detail-metric-icon)]:text-[color:#697992]",
    "tw:[&_.teacher-detail-metrics_span:not(.teacher-detail-metric-icon)]:text-[.82rem]", "tw:viewport-760:[&_.teacher-detail-metrics_span:not(.teacher-detail-metric-icon)]:text-[.69rem]", "tw:[&_.teacher-detail-metrics_strong]:text-[color:#111d3a]", "tw:[&_.teacher-detail-metrics_strong]:text-[1.45rem]",
    "tw:viewport-760:[&_.teacher-detail-metrics_strong]:text-[1.15rem]", "tw:viewport-760:[&_.teacher-detail-tabs]:[overflow-x:auto]", "tw:viewport-760:[&_.teacher-detail-tabs_a]:[flex:0_0_auto]", "tw:viewport-760:[&_.teacher-detail-metrics]:grid-cols-[repeat(2,_minmax(0,_1fr))]",
    "tw:[&_.teacher-detail-metrics_article_>_div_>_span]:leading-[1.2]", "tw:[&_.teacher-detail-metrics_article_>_div_>_strong]:leading-[1.1]", "tw:[&_.teacher-detail-metric-icon]:w-[50px]", "tw:viewport-760:[&_.teacher-detail-metric-icon]:w-[38px]",
    "tw:[&_.teacher-detail-metric-icon]:h-[50px]", "tw:viewport-760:[&_.teacher-detail-metric-icon]:h-[38px]", "tw:[&_.teacher-detail-metric-icon]:text-[1.45rem]", "tw:viewport-760:[&_.teacher-detail-metric-icon]:text-[1.1rem]",
  ].join(" "),
  "page_header_teacher_detail_hero": [
    "page-header", "teacher-detail-hero", "tw:flex", "tw:viewport-760:grid",
    "tw:justify-between", "tw:items-start", "tw:gap-y-[18px]", "tw:viewport-760:gap-y-[14px]",
    "tw:gap-x-[18px]", "tw:viewport-760:gap-x-[14px]", "tw:mb-[0]", "tw:pt-[4px]",
    "tw:pr-[0]", "tw:pb-[22px]", "tw:pl-[0]", "tw:border-t-[length:0]",
    "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]",
    "tw:border-r-[color:currentColor]", "tw:border-b-[length:2px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:color-mix(in_srgb,_var(--brand)_24%,_var(--line))]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[0]",
    "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:[box-shadow:none]", "tw:[animation:hero-rise_620ms_var(--ease-standard)_both]",
    "tw:mt-[0]", "tw:mr-[0]", "tw:ml-[0]", "tw:[&_h1]:mt-[0]",
    "tw:[&_h1]:mr-[0]", "tw:[&_h1]:mb-[0]", "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[clamp(1.8rem,_2vw,_2.4rem)]",
    "tw:[&_h1]:leading-[1.04]", "tw:[&_h1]:tracking-[-0.04em]", "tw:[&_p]:max-w-[760px]", "tw:[&::after]:[content:'']",
    "tw:[&::after]:absolute", "tw:viewport-720:flex-col", "tw:[&_.back-link]:inline-flex", "tw:[&_.back-link]:mb-[26px]",
    "tw:viewport-760:[&_.back-link]:mb-[16px]", "tw:[&_.back-link]:text-[color:#1263c7]", "tw:[&_.back-link]:text-[.92rem]",
  ].join(" "),
  "back_link": [
    "back-link", "tw:inline-flex", "tw:mb-[8px]", "tw:text-[color:#1464a1]",
    "tw:text-[.8rem]", "tw:font-[700]", "tw:[text-decoration:none]",
  ].join(" "),
  "teacher_detail_identity": [
    "teacher-detail-identity", "tw:flex", "tw:items-center", "tw:gap-y-[22px]",
    "tw:viewport-760:gap-y-[14px]", "tw:gap-x-[22px]", "tw:viewport-760:gap-x-[14px]", "tw:[&_.eyebrow]:mt-[0]",
    "tw:[&_.eyebrow]:mr-[0]", "tw:[&_.eyebrow]:mb-[8px]", "tw:[&_.eyebrow]:ml-[0]", "tw:[&_.eyebrow]:text-[color:#667692]",
    "tw:[&_.eyebrow]:text-[.72rem]", "tw:[&_h1]:mt-[0]", "tw:[&_h1]:mr-[0]", "tw:[&_h1]:mb-[0]",
    "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[color:#0b193a]", "tw:[&_h1]:text-[clamp(2rem,_3.1vw,_2.75rem)]", "tw:viewport-760:[&_h1]:text-[1.85rem]",
    "tw:[&_h1]:tracking-[-.055em]",
  ].join(" "),
  "teacher_detail_avatar": [
    "teacher-detail-avatar", "tw:grid", "tw:w-[78px]", "tw:viewport-760:w-[58px]",
    "tw:h-[78px]", "tw:viewport-760:h-[58px]", "tw:place-items-center", "tw:rounded-[50%]",
    "tw:text-[color:#fff]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_#2453ef,_#1737d6)]", "tw:[box-shadow:0_9px_19px_rgb(33_69_219_/_.18)]",
    "tw:text-[1.55rem]", "tw:viewport-760:text-[1.15rem]", "tw:font-[800]", "tw:[overflow-x:hidden]",
    "tw:[overflow-y:hidden]", "tw:[&_img]:w-[100%]", "tw:[&_img]:h-[100%]", "tw:[&_img]:[object-fit:cover]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "teacher_page_actions": [
    "teacher-page-actions", "tw:flex", "tw:items-center", "tw:viewport-640:items-start",
    "tw:justify-end", "tw:flex-wrap", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:[&_.status-badge]:inline-flex", "tw:[&_.status-badge]:items-center", "tw:[&_.status-badge]:gap-y-[5px]", "tw:[&_.status-badge]:gap-x-[5px]",
    "tw:[&_.status-badge]:min-h-[32px]", "tw:[&_.status-badge]:pt-[5px]", "tw:[&_.status-badge]:pr-[9px]", "tw:[&_.status-badge]:pb-[5px]",
    "tw:[&_.status-badge]:pl-[9px]", "tw:[&_.status-badge]:rounded-[999px]", "tw:[&_.status-badge]:font-[700]", "tw:[&_.status-badge_.event-icon]:w-[14px]",
    "tw:[&_.status-badge_.event-icon]:h-[14px]",
  ].join(" "),
  "teacher_actions_menu": [
    "teacher-actions-menu", "tw:relative", "tw:[&_summary]:inline-flex", "tw:[&_summary]:items-center",
    "tw:[&_summary]:gap-y-[7px]", "tw:[&_summary]:gap-x-[7px]", "tw:[&_summary]:min-h-[32px]", "tw:[&_summary]:pt-[5px]",
    "tw:[&_summary]:pr-[9px]", "tw:[&_summary]:pb-[5px]", "tw:[&_summary]:pl-[9px]", "tw:[&_summary]:border-t-[length:1px]",
    "tw:[&_summary]:[border-top-style:solid]", "tw:[&_summary]:border-t-[color:#d6e1eb]", "tw:[&_summary]:border-r-[length:1px]", "tw:[&_summary]:[border-right-style:solid]",
    "tw:[&_summary]:border-r-[color:#d6e1eb]", "tw:[&_summary]:border-b-[length:1px]", "tw:[&_summary]:[border-bottom-style:solid]", "tw:[&_summary]:border-b-[color:#d6e1eb]",
    "tw:[&_summary]:border-l-[length:1px]", "tw:[&_summary]:[border-left-style:solid]", "tw:[&_summary]:border-l-[color:#d6e1eb]", "tw:[&_summary]:rounded-[7px]",
    "tw:[&_summary]:text-[color:#35536f]", "tw:[&_summary]:bg-[color:#fff]", "tw:[&_summary]:[background-image:none]", "tw:[&_summary]:text-[.75rem]",
    "tw:[&_summary]:font-[650]", "tw:[&_summary]:cursor-pointer", "tw:[&_summary]:[list-style:none]", "tw:[&_summary::-webkit-details-marker]:hidden",
    "tw:[&_summary_span]:text-[color:#6e8195]", "tw:[&_summary_span]:text-[.86rem]", "tw:[&[open]_summary]:border-t-[color:#acc6de]", "tw:[&[open]_summary]:border-r-[color:#acc6de]",
    "tw:[&[open]_summary]:border-b-[color:#acc6de]", "tw:[&[open]_summary]:border-l-[color:#acc6de]", "tw:[&[open]_summary]:bg-[color:#f5f9fc]", "tw:[&[open]_summary]:[background-image:none]",
    "tw:[&_summary_.event-icon]:w-[14px]", "tw:[&_summary_.event-icon]:h-[14px]", "tw:[&_summary_.event-icon]:text-[color:#5e7790]", "tw:[&[open]_summary_.event-icon]:[transform:rotate(180deg)]",
  ].join(" "),
  "teacher_actions_menu_content": [
    "teacher-actions-menu-content", "tw:absolute", "tw:z-[24]", "tw:top-[calc(100%_+_7px)]",
    "tw:right-[0]", "tw:min-w-[150px]", "tw:pt-[6px]", "tw:pr-[6px]",
    "tw:pb-[6px]", "tw:pl-[6px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#d6e1eb]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d6e1eb]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d6e1eb]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#d6e1eb]", "tw:rounded-[9px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[box-shadow:0_12px_25px_rgb(35_53_77_/_.14)]", "tw:[&_.teacher-delete-form]:flex", "tw:[&_.teacher-archive-form]:flex",
    "tw:[&_.button]:w-[100%]", "tw:[&_.button]:justify-start",
  ].join(" "),
  "teacher_archive_form": [
    "teacher-archive-form", "tw:inline-flex", "tw:items-center", "tw:relative",
    "tw:[&_>_.button]:min-h-[34px]", "tw:[&_>_.button]:pt-[6px]", "tw:[&_>_.button]:pr-[10px]", "tw:[&_>_.button]:pb-[6px]",
    "tw:[&_>_.button]:pl-[10px]", "tw:[&_>_.button]:rounded-[7px]", "tw:[&_>_.button]:text-[.72rem]", "tw:[&_.safe-action-confirmation]:absolute",
    "tw:[&_.safe-action-confirmation]:z-[25]", "tw:[&_.safe-action-confirmation]:top-[calc(100%_+_7px)]", "tw:[&_.safe-action-confirmation]:right-[0]", "tw:viewport-600:[&_.safe-action-confirmation]:right-[auto]",
    "tw:[&_.safe-action-confirmation]:grid", "tw:[&_.safe-action-confirmation]:gap-y-[8px]", "tw:[&_.safe-action-confirmation]:gap-x-[8px]", "tw:[&_.safe-action-confirmation]:w-[min(330px,_78vw)]",
    "tw:viewport-600:[&_.safe-action-confirmation]:w-[min(320px,_calc(100vw_-_32px))]", "tw:[&_.safe-action-confirmation]:pt-[11px]", "tw:[&_.safe-action-confirmation]:pr-[11px]", "tw:[&_.safe-action-confirmation]:pb-[11px]",
    "tw:[&_.safe-action-confirmation]:pl-[11px]", "tw:[&_.safe-action-confirmation]:border-t-[length:1px]", "tw:[&_.safe-action-confirmation]:[border-top-style:solid]", "tw:[&_.safe-action-confirmation]:border-t-[color:#e6c9c5]",
    "tw:[&_.safe-action-confirmation]:border-r-[length:1px]", "tw:[&_.safe-action-confirmation]:[border-right-style:solid]", "tw:[&_.safe-action-confirmation]:border-r-[color:#e6c9c5]", "tw:[&_.safe-action-confirmation]:border-b-[length:1px]",
    "tw:[&_.safe-action-confirmation]:[border-bottom-style:solid]", "tw:[&_.safe-action-confirmation]:border-b-[color:#e6c9c5]", "tw:[&_.safe-action-confirmation]:border-l-[length:1px]", "tw:[&_.safe-action-confirmation]:[border-left-style:solid]",
    "tw:[&_.safe-action-confirmation]:border-l-[color:#e6c9c5]", "tw:[&_.safe-action-confirmation]:rounded-[10px]", "tw:[&_.safe-action-confirmation]:bg-[color:#fff]", "tw:[&_.safe-action-confirmation]:[background-image:none]",
    "tw:[&_.safe-action-confirmation]:[box-shadow:0_13px_30px_rgb(36_50_68_/_.18)]", "tw:[&_.safe-action-confirmation_.muted]:mt-[0]", "tw:[&_.safe-action-confirmation_.muted]:mr-[0]", "tw:[&_.safe-action-confirmation_.muted]:mb-[0]",
    "tw:[&_.safe-action-confirmation_.muted]:ml-[0]", "tw:[&_.safe-action-confirmation_.muted]:text-[color:#65758b]", "tw:[&_.safe-action-confirmation_.muted]:text-[.74rem]", "tw:[&_.safe-action-confirmation_.muted]:leading-[1.4]",
    "tw:[&_.safe-action-confirmation-actions]:flex", "tw:[&_.safe-action-confirmation-actions]:flex-wrap", "tw:[&_.safe-action-confirmation-actions]:gap-y-[6px]", "tw:[&_.safe-action-confirmation-actions]:gap-x-[6px]",
    "tw:[&_.safe-action-confirmation-actions]:items-center", "tw:[&_.safe-action-confirmation-actions_input]:w-[118px]", "tw:[&_.safe-action-confirmation-actions_input]:min-w-[112px]", "tw:[&_.safe-action-confirmation-actions_input]:min-h-[32px]",
    "tw:[&_.safe-action-confirmation-actions_input]:pt-[5px]", "tw:[&_.safe-action-confirmation-actions_input]:pr-[7px]", "tw:[&_.safe-action-confirmation-actions_input]:pb-[5px]", "tw:[&_.safe-action-confirmation-actions_input]:pl-[7px]",
    "tw:[&_.safe-action-confirmation-actions_input]:text-[.74rem]", "tw:[&_.safe-action-confirmation-actions_.button]:min-h-[32px]", "tw:[&_.safe-action-confirmation-actions_.button]:pt-[5px]", "tw:[&_.safe-action-confirmation-actions_.button]:pr-[9px]",
    "tw:[&_.safe-action-confirmation-actions_.button]:pb-[5px]", "tw:[&_.safe-action-confirmation-actions_.button]:pl-[9px]", "tw:[&_.safe-action-confirmation-actions_.button]:rounded-[7px]", "tw:[&_.safe-action-confirmation-actions_.button]:text-[.72rem]",
    "tw:viewport-600:[&_.safe-action-confirmation]:left-[0]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "teacher_delete_form": [
    "teacher-delete-form", "tw:inline-flex", "tw:relative", "tw:items-center",
    "tw:[&_>_.button]:min-h-[34px]", "tw:[&_>_.button]:pt-[6px]", "tw:[&_>_.button]:pr-[10px]", "tw:[&_>_.button]:pb-[6px]",
    "tw:[&_>_.button]:pl-[10px]", "tw:[&_>_.button]:rounded-[7px]", "tw:[&_>_.button]:text-[.72rem]", "tw:[&_.safe-action-confirmation]:absolute",
    "tw:[&_.safe-action-confirmation]:z-[25]", "tw:[&_.safe-action-confirmation]:top-[calc(100%_+_7px)]", "tw:[&_.safe-action-confirmation]:right-[0]", "tw:viewport-600:[&_.safe-action-confirmation]:right-[auto]",
    "tw:[&_.safe-action-confirmation]:grid", "tw:[&_.safe-action-confirmation]:gap-y-[8px]", "tw:[&_.safe-action-confirmation]:gap-x-[8px]", "tw:[&_.safe-action-confirmation]:w-[min(330px,_78vw)]",
    "tw:viewport-600:[&_.safe-action-confirmation]:w-[min(320px,_calc(100vw_-_32px))]", "tw:[&_.safe-action-confirmation]:pt-[11px]", "tw:[&_.safe-action-confirmation]:pr-[11px]", "tw:[&_.safe-action-confirmation]:pb-[11px]",
    "tw:[&_.safe-action-confirmation]:pl-[11px]", "tw:[&_.safe-action-confirmation]:border-t-[length:1px]", "tw:[&_.safe-action-confirmation]:[border-top-style:solid]", "tw:[&_.safe-action-confirmation]:border-t-[color:#e6c9c5]",
    "tw:[&_.safe-action-confirmation]:border-r-[length:1px]", "tw:[&_.safe-action-confirmation]:[border-right-style:solid]", "tw:[&_.safe-action-confirmation]:border-r-[color:#e6c9c5]", "tw:[&_.safe-action-confirmation]:border-b-[length:1px]",
    "tw:[&_.safe-action-confirmation]:[border-bottom-style:solid]", "tw:[&_.safe-action-confirmation]:border-b-[color:#e6c9c5]", "tw:[&_.safe-action-confirmation]:border-l-[length:1px]", "tw:[&_.safe-action-confirmation]:[border-left-style:solid]",
    "tw:[&_.safe-action-confirmation]:border-l-[color:#e6c9c5]", "tw:[&_.safe-action-confirmation]:rounded-[10px]", "tw:[&_.safe-action-confirmation]:bg-[color:#fff]", "tw:[&_.safe-action-confirmation]:[background-image:none]",
    "tw:[&_.safe-action-confirmation]:[box-shadow:0_13px_30px_rgb(36_50_68_/_.18)]", "tw:[&_.safe-action-confirmation_.muted]:mt-[0]", "tw:[&_.safe-action-confirmation_.muted]:mr-[0]", "tw:[&_.safe-action-confirmation_.muted]:mb-[0]",
    "tw:[&_.safe-action-confirmation_.muted]:ml-[0]", "tw:[&_.safe-action-confirmation_.muted]:text-[color:#65758b]", "tw:[&_.safe-action-confirmation_.muted]:text-[.74rem]", "tw:[&_.safe-action-confirmation_.muted]:leading-[1.4]",
    "tw:[&_.safe-action-confirmation-actions]:flex", "tw:[&_.safe-action-confirmation-actions]:flex-wrap", "tw:[&_.safe-action-confirmation-actions]:gap-y-[6px]", "tw:[&_.safe-action-confirmation-actions]:gap-x-[6px]",
    "tw:[&_.safe-action-confirmation-actions]:items-center", "tw:[&_.safe-action-confirmation-actions_input]:w-[118px]", "tw:[&_.safe-action-confirmation-actions_input]:min-w-[112px]", "tw:[&_.safe-action-confirmation-actions_input]:min-h-[32px]",
    "tw:[&_.safe-action-confirmation-actions_input]:pt-[5px]", "tw:[&_.safe-action-confirmation-actions_input]:pr-[7px]", "tw:[&_.safe-action-confirmation-actions_input]:pb-[5px]", "tw:[&_.safe-action-confirmation-actions_input]:pl-[7px]",
    "tw:[&_.safe-action-confirmation-actions_input]:text-[.74rem]", "tw:[&_.safe-action-confirmation-actions_.button]:min-h-[32px]", "tw:[&_.safe-action-confirmation-actions_.button]:pt-[5px]", "tw:[&_.safe-action-confirmation-actions_.button]:pr-[9px]",
    "tw:[&_.safe-action-confirmation-actions_.button]:pb-[5px]", "tw:[&_.safe-action-confirmation-actions_.button]:pl-[9px]", "tw:[&_.safe-action-confirmation-actions_.button]:rounded-[7px]", "tw:[&_.safe-action-confirmation-actions_.button]:text-[.72rem]",
    "tw:viewport-600:[&_.safe-action-confirmation]:left-[0]",
  ].join(" "),
  "button_button_danger_button_small": sharedUtilities.buttonButtonDangerButtonSmall,
  "teacher_detail_tabs": [
    "teacher-detail-tabs", "tw:flex", "tw:gap-y-[3px]", "tw:gap-x-[3px]",
    "tw:pb-[1px]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]",
    "tw:[&_a]:pt-[9px]", "tw:[&_a]:pr-[13px]", "tw:[&_a]:pb-[9px]", "tw:[&_a]:pl-[13px]",
    "tw:[&_a]:border-b-[length:2px]", "tw:[&_a]:[border-bottom-style:solid]", "tw:[&_a]:border-b-[color:transparent]", "tw:[&_a]:text-[color:#627590]",
    "tw:[&_a]:text-[.8rem]", "tw:[&_a]:font-[750]", "tw:[&_a]:[text-decoration:none]", "tw:[&_a:hover]:text-[color:#1464a1]",
    "tw:[&_a:hover]:bg-[color:#f4f9fd]", "tw:[&_a:hover]:[background-image:none]", "tw:[&_a.is-active]:border-t-[color:#146eb0]", "tw:[&_a.is-active]:border-r-[color:#146eb0]",
    "tw:[&_a.is-active]:border-b-[color:#146eb0]", "tw:[&_a.is-active]:border-l-[color:#146eb0]", "tw:[&_a.is-active]:text-[color:#105d99]",
  ].join(" "),
  "teacher_detail_metrics": [
    "teacher-detail-metrics", "tw:grid", "tw:grid-cols-[repeat(4,_minmax(0,_1fr))]", "tw:viewport-900:grid-cols-[repeat(2,_minmax(0,_1fr))]",
    "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:[&_article]:grid", "tw:[&_article]:gap-y-[5px]",
    "tw:[&_article]:gap-x-[5px]", "tw:[&_article]:pt-[15px]", "tw:[&_article]:pr-[15px]", "tw:[&_article]:pb-[15px]",
    "tw:[&_article]:pl-[15px]", "tw:[&_article]:border-t-[length:1px]", "tw:[&_article]:[border-top-style:solid]", "tw:[&_article]:border-t-[color:var(--line)]",
    "tw:[&_article]:border-r-[length:1px]", "tw:[&_article]:[border-right-style:solid]", "tw:[&_article]:border-r-[color:var(--line)]", "tw:[&_article]:border-b-[length:1px]",
    "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:var(--line)]", "tw:[&_article]:border-l-[length:1px]", "tw:[&_article]:[border-left-style:solid]",
    "tw:[&_article]:border-l-[color:var(--line)]", "tw:[&_article]:rounded-[10px]", "tw:[&_article]:bg-[color:#fff]", "tw:[&_article]:[background-image:none]",
    "tw:[&_span]:text-[color:#657896]", "tw:[&_span]:text-[.75rem]", "tw:[&_strong]:text-[color:#123c67]", "tw:[&_strong]:text-[1.4rem]",
  ].join(" "),
  "teacher_detail_metric_icon": [
    "teacher-detail-metric-icon", "metric-blue", "tw:grid", "tw:[flex:0_0_auto]",
    "tw:w-[58px]", "tw:viewport-760:w-[40px]", "tw:h-[58px]", "tw:viewport-760:h-[40px]",
    "tw:place-items-center", "tw:rounded-[50%]", "tw:text-[1.7rem]", "tw:viewport-760:text-[1.2rem]",
    "tw:font-[700]", "tw:[&.metric-blue]:text-[color:#1164db]", "tw:[&.metric-blue]:bg-[color:transparent]", "tw:[&.metric-blue]:[background-image:linear-gradient(145deg,_#eaf2ff,_#dce9fb)]",
    "tw:[&.metric-green]:text-[color:#18a35f]", "tw:[&.metric-green]:bg-[color:transparent]", "tw:[&.metric-green]:[background-image:linear-gradient(145deg,_#e5f9ed,_#d8f4e3)]", "tw:[&.metric-purple]:text-[color:#7444e7]",
    "tw:[&.metric-purple]:bg-[color:transparent]", "tw:[&.metric-purple]:[background-image:linear-gradient(145deg,_#f1ecff,_#e8e0fe)]",
  ].join(" "),
  "teacher_detail_metric_icon_2": [
    "teacher-detail-metric-icon", "metric-purple", "tw:grid", "tw:[flex:0_0_auto]",
    "tw:w-[58px]", "tw:viewport-760:w-[40px]", "tw:h-[58px]", "tw:viewport-760:h-[40px]",
    "tw:place-items-center", "tw:rounded-[50%]", "tw:text-[1.7rem]", "tw:viewport-760:text-[1.2rem]",
    "tw:font-[700]", "tw:[&.metric-blue]:text-[color:#1164db]", "tw:[&.metric-blue]:bg-[color:transparent]", "tw:[&.metric-blue]:[background-image:linear-gradient(145deg,_#eaf2ff,_#dce9fb)]",
    "tw:[&.metric-green]:text-[color:#18a35f]", "tw:[&.metric-green]:bg-[color:transparent]", "tw:[&.metric-green]:[background-image:linear-gradient(145deg,_#e5f9ed,_#d8f4e3)]", "tw:[&.metric-purple]:text-[color:#7444e7]",
    "tw:[&.metric-purple]:bg-[color:transparent]", "tw:[&.metric-purple]:[background-image:linear-gradient(145deg,_#f1ecff,_#e8e0fe)]",
  ].join(" "),
  "teacher_detail_metric_icon_3": [
    "teacher-detail-metric-icon", "metric-green", "tw:grid", "tw:[flex:0_0_auto]",
    "tw:w-[58px]", "tw:viewport-760:w-[40px]", "tw:h-[58px]", "tw:viewport-760:h-[40px]",
    "tw:place-items-center", "tw:rounded-[50%]", "tw:text-[1.7rem]", "tw:viewport-760:text-[1.2rem]",
    "tw:font-[700]", "tw:[&.metric-blue]:text-[color:#1164db]", "tw:[&.metric-blue]:bg-[color:transparent]", "tw:[&.metric-blue]:[background-image:linear-gradient(145deg,_#eaf2ff,_#dce9fb)]",
    "tw:[&.metric-green]:text-[color:#18a35f]", "tw:[&.metric-green]:bg-[color:transparent]", "tw:[&.metric-green]:[background-image:linear-gradient(145deg,_#e5f9ed,_#d8f4e3)]", "tw:[&.metric-purple]:text-[color:#7444e7]",
    "tw:[&.metric-purple]:bg-[color:transparent]", "tw:[&.metric-purple]:[background-image:linear-gradient(145deg,_#f1ecff,_#e8e0fe)]",
  ].join(" "),
  "section_card_teacher_detail_section_teacher_plans_panel": [
    "section-card", "teacher-detail-section", "teacher-plans-panel", "tw:pt-[22px]",
    "tw:pr-[0]", "tw:pb-[22px]", "tw:pl-[0]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:0]", "tw:[border-right-style:none]",
    "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[0]",
    "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:[box-shadow:none]", "tw:grid",
    "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:[&_>_header]:flex", "tw:[&_>_header]:items-center",
    "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[10px]", "tw:[&_>_header]:gap-x-[10px]", "tw:[&_h2]:mt-[0]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[1rem]",
  ].join(" "),
  "teacher_plan_panel_actions": [
    "teacher-plan-panel-actions", "tw:inline-flex", "tw:items-center", "tw:flex-wrap",
    "tw:justify-end", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
  ].join(" "),
  "teacher_plan_cards": [
    "teacher-plan-cards", "tw:grid", "tw:grid-cols-[repeat(auto-fit,_minmax(205px,_1fr))]", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[&_>_a]:grid", "tw:[&_>_a]:gap-y-[5px]", "tw:[&_>_a]:gap-x-[5px]",
    "tw:[&_>_a]:pt-[11px]", "tw:[&_>_a]:pr-[11px]", "tw:[&_>_a]:pb-[11px]", "tw:[&_>_a]:pl-[11px]",
    "tw:[&_>_a]:border-l-[length:3px]", "tw:[&_>_a]:[border-left-style:solid]", "tw:[&_>_a]:border-l-[color:#1f8a5b]", "tw:[&_>_a]:bg-[color:#f7fbf9]",
    "tw:[&_>_a]:[background-image:none]", "tw:[&_>_a]:text-[color:inherit]", "tw:[&_>_a]:[text-decoration:none]", "tw:[&_>_a:hover]:bg-[color:#e9f7ef]",
    "tw:[&_>_a:hover]:[background-image:none]", "tw:[&_>_a:hover]:[box-shadow:inset_0_0_0_1px_#9ed5b6]", "tw:[&_>_a.is-selected]:bg-[color:#e9f7ef]", "tw:[&_>_a.is-selected]:[background-image:none]",
    "tw:[&_>_a.is-selected]:[box-shadow:inset_0_0_0_1px_#9ed5b6]", "tw:[&_span]:text-[color:#627590]", "tw:[&_span]:text-[.75rem]", "tw:[&_small]:text-[color:#627590]",
    "tw:[&_small]:text-[.75rem]", "tw:[&_>_article]:flex", "tw:[&_>_article]:items-start", "tw:[&_>_article]:justify-between",
    "tw:[&_>_article]:gap-y-[10px]", "tw:[&_>_article]:gap-x-[10px]", "tw:[&_>_article]:pt-[12px]", "tw:[&_>_article]:pr-[12px]",
    "tw:[&_>_article]:pb-[12px]", "tw:[&_>_article]:pl-[12px]", "tw:[&_>_article]:border-l-[length:3px]", "tw:[&_>_article]:[border-left-style:solid]",
    "tw:[&_>_article]:border-l-[color:#1f8a5b]", "tw:[&_>_article]:bg-[color:#f7fbf9]", "tw:[&_>_article]:[background-image:none]", "tw:[&_>_article_>_div]:grid",
    "tw:[&_>_article_>_div]:gap-y-[4px]", "tw:[&_>_article_>_div]:gap-x-[4px]", "tw:[&_>_article_strong]:text-[color:#152643]", "tw:[&_>_article_strong]:text-[.88rem]",
    "tw:[&_>_article_span]:text-[color:#627590]", "tw:[&_>_article_span]:text-[.72rem]", "tw:[&_>_article_small]:text-[color:#627590]", "tw:[&_>_article_small]:text-[.72rem]",
    "tw:[&_>_article_b]:text-[color:#17395e]", "tw:[&_>_article_b]:text-[.84rem]", "tw:[&_.teacher-plan-edit-trigger]:[flex:0_0_auto]",
  ].join(" "),
  "teacher_plan_owner_tag": [
    "teacher-plan-owner-tag", "tw:w-[fit-content]", "tw:pt-[3px]", "tw:pr-[6px]",
    "tw:pb-[3px]", "tw:pl-[6px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#cbdcf0]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#cbdcf0]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#cbdcf0]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#cbdcf0]", "tw:rounded-[999px]", "tw:bg-[color:#eef5ff]",
    "tw:[background-image:none]", "tw:text-[color:#28598d]!", "tw:text-[.66rem]!", "tw:not-italic",
    "tw:font-[800]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "section_card_teacher_detail_section_teacher_active_students_panel": [
    "section-card", "teacher-detail-section", "teacher-active-students-panel", "tw:pt-[17px]",
    "tw:pr-[18px]", "tw:pb-[0]", "tw:pl-[18px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:0]", "tw:[border-right-style:none]",
    "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[0]",
    "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:[box-shadow:none]", "tw:grid",
    "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:[&_>_header]:flex", "tw:[&_>_header]:items-center",
    "tw:[&_>_header]:justify-start", "tw:[&_>_header]:gap-y-[12px]", "tw:[&_>_header]:gap-x-[12px]", "tw:[&_h2]:mt-[0]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[1rem]",
    "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:[&_>_header_h2]:text-[color:#101d39]", "tw:[&_>_header_h2]:text-[1rem]",
    "tw:[&_.teacher-student-plan-list]:mt-[0]", "tw:[&_.teacher-student-plan-list]:mr-[-18px]", "tw:[&_.teacher-student-plan-list]:mb-[0]", "tw:[&_.teacher-student-plan-list]:ml-[-18px]",
    "tw:[&_.teacher-student-plan-list]:pt-[12px]", "tw:[&_.teacher-student-plan-list]:pr-[18px]", "tw:[&_.teacher-student-plan-list]:pb-[18px]", "tw:[&_.teacher-student-plan-list]:pl-[18px]",
    "tw:[&_.teacher-student-plan-list]:border-t-[length:1px]", "tw:[&_.teacher-student-plan-list]:[border-top-style:solid]", "tw:[&_.teacher-student-plan-list]:border-t-[color:#e6edf4]", "tw:[&_.teacher-student-plan-list_article]:border-t-[color:#e3ebf3]",
    "tw:[&_.teacher-student-plan-list_article]:border-r-[color:#e3ebf3]", "tw:[&_.teacher-student-plan-list_article]:border-b-[color:#e3ebf3]", "tw:[&_.teacher-student-plan-list_article]:border-l-[color:#e3ebf3]", "tw:[&_.teacher-student-plan-list_article]:grid-cols-[minmax(0,_1fr)_auto]",
    "tw:[&_.teacher-student-plan-list_article]:min-h-[52px]", "tw:[&_.teacher-student-plan-list_article]:gap-y-[12px]", "tw:[&_.teacher-student-plan-list_article]:gap-x-[12px]", "tw:[&_.teacher-student-plan-list_article]:pt-[8px]",
    "tw:[&_.teacher-student-plan-list_article]:pr-[0]", "tw:[&_.teacher-student-plan-list_article]:pb-[8px]", "tw:[&_.teacher-student-plan-list_article]:pl-[0]", "tw:viewport-760:[padding-inline:14px]",
    "tw:viewport-760:[&_.teacher-student-plan-list]:[margin-inline:-14px]", "tw:viewport-760:[&_.teacher-student-plan-list]:[padding-inline:14px]",
  ].join(" "),
  "teacher_active_students_icon": [
    "teacher-active-students-icon", "tw:text-[color:#1264df]", "tw:text-[1.15rem]",
  ].join(" "),
  "teacher_student_plan_list": [
    "teacher-student-plan-list", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:[&_article]:grid", "tw:[&_article]:grid-cols-[1.4fr_auto_auto_auto]", "tw:[&_article]:items-center", "tw:viewport-600:[&_article]:items-start",
    "tw:[&_article]:gap-y-[14px]", "tw:[&_article]:gap-x-[14px]", "tw:[&_article]:pt-[11px]", "tw:[&_article]:pr-[11px]",
    "tw:[&_article]:pb-[11px]", "tw:[&_article]:pl-[11px]", "tw:[&_article]:border-b-[length:1px]", "tw:[&_article]:[border-bottom-style:solid]",
    "tw:[&_article]:border-b-[color:var(--line)]", "tw:[&_article_>_div]:grid", "tw:[&_article_>_div]:gap-y-[2px]", "tw:[&_article_>_div]:gap-x-[2px]",
    "tw:[&_article_span:not(.status-badge)]:text-[color:#627590]", "tw:[&_article_span:not(.status-badge)]:text-[.75rem]", "tw:viewport-600:[&_article]:flex-col",
  ].join(" "),
  "teacher_student_row_link": [
    "teacher-student-row-link", "tw:min-w-[0]", "tw:[&_>_summary]:flex", "tw:[&_>_summary]:items-center",
    "tw:viewport-760:[&_>_summary]:items-start", "tw:[&_>_summary]:justify-between", "tw:[&_>_summary]:gap-y-[12px]", "tw:viewport-760:[&_>_summary]:gap-y-[3px]",
    "tw:[&_>_summary]:gap-x-[12px]", "tw:viewport-760:[&_>_summary]:gap-x-[3px]", "tw:[&_>_summary]:min-h-[36px]", "tw:[&_>_summary]:cursor-pointer",
    "tw:[&_>_summary]:[list-style:none]", "tw:[&_>_summary::-webkit-details-marker]:hidden", "tw:[&_>_summary_>_span]:grid", "tw:[&_>_summary_>_span]:min-w-[0]",
    "tw:[&_>_summary_>_span]:gap-y-[2px]", "tw:[&_>_summary_>_span]:gap-x-[2px]", "tw:[&_>_summary_strong]:[overflow-x:hidden]", "tw:[&_>_summary_strong]:[overflow-y:hidden]",
    "tw:[&_>_summary_strong]:text-[color:#1c2d49]", "tw:[&_>_summary_strong]:text-[.82rem]", "tw:[&_>_summary_strong]:text-ellipsis", "tw:[&_>_summary_strong]:whitespace-nowrap",
    "tw:[&_>_summary_small]:text-[color:#64738d]", "tw:[&_>_summary_small]:text-[.71rem]", "tw:[&_>_summary_small]:not-italic", "tw:[&_>_summary_small]:whitespace-nowrap",
    "tw:[&_>_summary_em]:text-[color:#64738d]", "tw:[&_>_summary_em]:text-[.71rem]", "tw:[&_>_summary_em]:not-italic", "tw:[&_>_summary_em]:whitespace-nowrap",
    "tw:viewport-760:[&_>_summary]:flex-col",
  ].join(" "),
  "teacher_student_group_move": [
    "teacher-student-group-move", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:[align-items:end]", "tw:grid-cols-[minmax(180px,_1fr)_auto]", "tw:viewport-760:grid-cols-[1fr]", "tw:pt-[9px]",
    "tw:pr-[0]", "tw:pb-[2px]", "tw:pl-[0]", "tw:[&_select]:min-h-[30px]",
    "tw:[&_select]:max-w-[none]", "tw:[&_select]:text-[.72rem]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[3px]",
    "tw:[&_label]:gap-x-[3px]", "tw:[&_label]:text-[color:#627590]", "tw:[&_label]:text-[.66rem]", "tw:[&_label]:font-[700]",
    "tw:[&_.button]:min-h-[30px]", "tw:[&_.button]:[padding-inline:9px]", "tw:[&_.button]:text-[.7rem]",
  ].join(" "),
  "teacher_student_plan_remove": [
    "teacher-student-plan-remove", "tw:relative", "tw:inline-flex", "tw:items-center",
    "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:pt-[7px]", "tw:[&_>_.button]:min-h-[30px]",
    "tw:[&_>_.button]:[padding-inline:9px]", "tw:[&_>_.button]:rounded-[6px]", "tw:[&_>_.button]:text-[.7rem]", "tw:[&_.safe-action-confirmation]:fixed",
    "tw:[&_.safe-action-confirmation]:z-[100]", "tw:[&_.safe-action-confirmation]:top-[14vh]", "tw:[&_.safe-action-confirmation]:left-[50%]", "tw:[&_.safe-action-confirmation]:grid",
    "tw:[&_.safe-action-confirmation]:w-[min(520px,_calc(100vw_-_32px))]", "tw:[&_.safe-action-confirmation]:max-h-[72vh]", "tw:[&_.safe-action-confirmation]:[overflow-x:auto]", "tw:[&_.safe-action-confirmation]:[overflow-y:auto]",
    "tw:[&_.safe-action-confirmation]:[transform:translateX(-50%)]", "tw:[&_.safe-action-confirmation]:gap-y-[10px]", "tw:[&_.safe-action-confirmation]:gap-x-[10px]", "tw:[&_.safe-action-confirmation]:pt-[18px]",
    "tw:[&_.safe-action-confirmation]:pr-[18px]", "tw:[&_.safe-action-confirmation]:pb-[18px]", "tw:[&_.safe-action-confirmation]:pl-[18px]", "tw:[&_.safe-action-confirmation]:border-t-[length:1px]",
    "tw:[&_.safe-action-confirmation]:[border-top-style:solid]", "tw:[&_.safe-action-confirmation]:border-t-[color:#f0c5c5]", "tw:[&_.safe-action-confirmation]:border-r-[length:1px]", "tw:[&_.safe-action-confirmation]:[border-right-style:solid]",
    "tw:[&_.safe-action-confirmation]:border-r-[color:#f0c5c5]", "tw:[&_.safe-action-confirmation]:border-b-[length:1px]", "tw:[&_.safe-action-confirmation]:[border-bottom-style:solid]", "tw:[&_.safe-action-confirmation]:border-b-[color:#f0c5c5]",
    "tw:[&_.safe-action-confirmation]:border-l-[length:1px]", "tw:[&_.safe-action-confirmation]:[border-left-style:solid]", "tw:[&_.safe-action-confirmation]:border-l-[color:#f0c5c5]", "tw:[&_.safe-action-confirmation]:rounded-[12px]",
    "tw:[&_.safe-action-confirmation]:bg-[color:#fff]", "tw:[&_.safe-action-confirmation]:[background-image:none]", "tw:[&_.safe-action-confirmation]:[box-shadow:0_22px_50px_rgb(74_30_30_/_.22)]", "tw:[&_.safe-action-confirmation_.muted]:mt-[0]",
    "tw:[&_.safe-action-confirmation_.muted]:mr-[0]", "tw:[&_.safe-action-confirmation_.muted]:mb-[0]", "tw:[&_.safe-action-confirmation_.muted]:ml-[0]", "tw:[&_.safe-action-confirmation_.muted]:text-[color:#6b5960]",
    "tw:[&_.safe-action-confirmation_.muted]:text-[.7rem]", "tw:[&_.safe-action-confirmation-actions]:gap-y-[5px]", "tw:[&_.safe-action-confirmation-actions]:gap-x-[5px]", "tw:[&_.safe-action-confirmation-actions_input]:min-h-[30px]",
    "tw:[&_.safe-action-confirmation-actions_input]:pt-[5px]", "tw:[&_.safe-action-confirmation-actions_input]:pr-[7px]", "tw:[&_.safe-action-confirmation-actions_input]:pb-[5px]", "tw:[&_.safe-action-confirmation-actions_input]:pl-[7px]",
    "tw:[&_.safe-action-confirmation-actions_input]:text-[.72rem]", "tw:[&_.safe-action-confirmation-actions_.button]:min-h-[30px]", "tw:[&_.safe-action-confirmation-actions_.button]:pt-[5px]", "tw:[&_.safe-action-confirmation-actions_.button]:pr-[8px]",
    "tw:[&_.safe-action-confirmation-actions_.button]:pb-[5px]", "tw:[&_.safe-action-confirmation-actions_.button]:pl-[8px]", "tw:[&_.safe-action-confirmation-actions_.button]:text-[.7rem]",
  ].join(" "),
  "teacher_plan_removal_options": [
    "teacher-plan-removal-options", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:pt-[10px]", "tw:pr-[10px]", "tw:pb-[10px]", "tw:pl-[10px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#efcfb8]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#efcfb8]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#efcfb8]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#efcfb8]",
    "tw:rounded-[8px]", "tw:bg-[color:#fff8f3]", "tw:[background-image:none]", "tw:[&_label]:flex",
    "tw:[&_label]:items-start", "tw:[&_label]:gap-y-[7px]", "tw:[&_label]:gap-x-[7px]", "tw:[&_label]:text-[color:#573719]",
    "tw:[&_label]:text-[.74rem]", "tw:[&_label]:font-[700]", "tw:[&_label]:leading-[1.35]", "tw:[&_input]:w-[auto]",
    "tw:[&_input]:mt-[2px]", "tw:[&_input]:[accent-color:#b45416]", "tw:[&_small]:text-[color:#73583f]", "tw:[&_small]:text-[.68rem]",
    "tw:[&_small]:leading-[1.35]", "tw:[&_>_strong]:text-[color:#573719]", "tw:[&_>_strong]:text-[.81rem]",
  ].join(" "),
  "teacher_student_financial_link": [
    "teacher-student-financial-link", "tw:inline-flex", "tw:text-[color:inherit]", "tw:[text-decoration:none]",
    "tw:[&_.status-badge]:min-h-[26px]", "tw:[&_.status-badge]:pt-[4px]", "tw:[&_.status-badge]:pr-[8px]", "tw:[&_.status-badge]:pb-[4px]",
    "tw:[&_.status-badge]:pl-[8px]", "tw:[&_.status-badge]:text-[.68rem]", "tw:[&_.status-badge.status-active]:border-t-[color:#bce7cd]", "tw:[&_.status-badge.status-active]:border-r-[color:#bce7cd]",
    "tw:[&_.status-badge.status-active]:border-b-[color:#bce7cd]", "tw:[&_.status-badge.status-active]:border-l-[color:#bce7cd]", "tw:[&_.status-badge.status-active]:text-[color:#147345]", "tw:[&_.status-badge.status-active]:bg-[color:#edf9f1]",
    "tw:[&_.status-badge.status-active]:[background-image:none]", "tw:[&_.status-badge.status-pending]:border-t-[color:#f0c5c5]", "tw:[&_.status-badge.status-pending]:border-r-[color:#f0c5c5]", "tw:[&_.status-badge.status-pending]:border-b-[color:#f0c5c5]",
    "tw:[&_.status-badge.status-pending]:border-l-[color:#f0c5c5]", "tw:[&_.status-badge.status-pending]:text-[color:#b73939]", "tw:[&_.status-badge.status-pending]:bg-[color:#fff3f3]", "tw:[&_.status-badge.status-pending]:[background-image:none]",
    "tw:[&:hover_.status-badge]:[filter:brightness(.97)]", "tw:[&:hover_.status-badge]:[box-shadow:0_2px_7px_rgb(13_50_96_/_.12)]",
  ].join(" "),
  "status_pending": [
    "status-badge", "status-pending", "tw:inline-flex", "tw:w-[fit-content]",
    "tw:pt-[5px]", "tw:pr-[9px]", "tw:pb-[5px]", "tw:pl-[9px]",
    "tw:rounded-[999px]", "tw:text-[.78rem]", "tw:font-[800]", "tw:text-[color:#996200]",
    "tw:bg-[color:#fff3db]", "tw:[background-image:none]",
  ].join(" "),
  "teacher_active_students_empty": [
    "teacher-active-students-empty", "tw:grid", "tw:[justify-items:center]", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:min-h-[175px]", "tw:pt-[24px]", "tw:pr-[24px]",
    "tw:pb-[24px]", "tw:pl-[24px]", "tw:text-center", "tw:[&_>_span]:grid",
    "tw:[&_>_span]:w-[64px]", "tw:[&_>_span]:h-[64px]", "tw:[&_>_span]:place-items-center", "tw:[&_>_span]:rounded-[50%]",
    "tw:[&_>_span]:text-[color:#1665d9]", "tw:[&_>_span]:bg-[color:#eaf2ff]", "tw:[&_>_span]:[background-image:none]", "tw:[&_>_span]:text-[2rem]",
    "tw:[&_.muted]:mt-[0]", "tw:[&_.muted]:mr-[0]", "tw:[&_.muted]:mb-[0]", "tw:[&_.muted]:ml-[0]",
    "tw:[&_.muted]:text-[color:#64738d]", "tw:[&_.muted]:text-[.95rem]",
  ].join(" "),
  "section_card_teacher_detail_section": [
    "section-card", "teacher-detail-section", "tw:pt-[22px]", "tw:pr-[0]",
    "tw:pb-[22px]", "tw:pl-[0]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[0]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:[box-shadow:none]", "tw:grid", "tw:gap-y-[14px]",
    "tw:gap-x-[14px]", "tw:[&_>_header]:flex", "tw:[&_>_header]:items-center", "tw:[&_>_header]:justify-between",
    "tw:[&_>_header]:gap-y-[10px]", "tw:[&_>_header]:gap-x-[10px]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]",
    "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[1rem]",
  ].join(" "),
  "filter_bar_compact_teacher_report_filters": [
    "filter-bar-compact", "teacher-report-filters", "tw:pt-[8px]", "tw:pr-[0]",
    "tw:pb-[12px]", "tw:pl-[0]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:[&_label]:text-[color:#50657f]",
    "tw:[&_label]:text-[.7rem]", "tw:[&_label]:font-[700]", "tw:[&_input]:min-h-[34px]", "tw:[&_input]:pt-[6px]",
    "tw:[&_input]:pr-[8px]", "tw:[&_input]:pb-[6px]", "tw:[&_input]:pl-[8px]", "tw:[&_input]:text-[.78rem]",
    "tw:[&_select]:min-h-[34px]", "tw:[&_select]:pt-[6px]", "tw:[&_select]:pr-[8px]", "tw:[&_select]:pb-[6px]",
    "tw:[&_select]:pl-[8px]", "tw:[&_select]:text-[.78rem]", "tw:grid", "tw:grid-cols-[repeat(4,_minmax(0,_1fr))_auto]",
    "tw:viewport-900:grid-cols-[1fr_1fr]", "tw:viewport-600:grid-cols-[1fr]", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:[align-items:end]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[4px]", "tw:[&_label]:gap-x-[4px]",
    "tw:viewport-900:[&_.button]:[grid-column:1_/_-1]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
} as const;
