"use client";

import { useEffect, useMemo, useRef, useState, useTransition } from "react";
import { createWhatsAppContactAction, linkWhatsAppConversationToClientAction, markWhatsAppConversationReadAction, sendWhatsAppChatMessageAction, updateWhatsAppConversationAction, updateWhatsAppSlaAction } from "@/lib/actions/whatsapp-chat";
import { normalizeBrazilianPhone } from "@/lib/phone";

type Client = { id: string; name: string; phone: string; email: string };
type Conversation = { id: string; contactName: string; contactPhone: string; unreadCount: number; lastMessageAt: string; playerId: string | null; player: Client | null; archivedAt: string | null; pinned: boolean; favorite: boolean; listName: string; remoteJid: string; messages: { id: string; direction: string; body: string; sentAt: string }[] };
type Filter = "all" | "unread" | "groups" | "favorite" | "archived";
const time = (value: string) => new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const detailTime = (value: string) => new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const initials = (name: string) => name.split(/\s+/).filter(Boolean).slice(0, 2).map((word) => word[0]).join("").toUpperCase() || "WA";
const formatPhone = (value: string) => { const digits = value.replace(/\D/g, ""); return digits.length >= 10 ? `(${digits.slice(-11, -9)}) ${digits.slice(-9, -4)}-${digits.slice(-4)}` : value || "Não informado"; };

export function WhatsAppChatWorkspace({ conversations, connected, clients, slaMinutes }: { conversations: Conversation[]; connected: boolean; clients: Client[]; slaMinutes: number }) {
  const [activeId, setActiveId] = useState(conversations.find((item) => !item.archivedAt)?.id ?? conversations[0]?.id ?? "");
  const [body, setBody] = useState(""); const [query, setQuery] = useState(""); const [clientQuery, setClientQuery] = useState(""); const [filter, setFilter] = useState<Filter>("all"); const [menuId, setMenuId] = useState(""); const [showSla, setShowSla] = useState(false); const [showContact, setShowContact] = useState(false); const [slaValue, setSlaValue] = useState(String(slaMinutes)); const [notice, setNotice] = useState(""); const [pending, startTransition] = useTransition(); const fileInput = useRef<HTMLInputElement>(null);
  const active = conversations.find((conversation) => conversation.id === activeId) ?? conversations[0] ?? null;
  const visible = useMemo(() => conversations.filter((conversation) => {
    const searchMatches = `${conversation.contactName} ${conversation.contactPhone} ${conversation.player?.name ?? ""}`.toLowerCase().includes(query.trim().toLowerCase());
    if (!searchMatches) return false;
    if (filter === "unread") return conversation.unreadCount > 0 && !conversation.archivedAt;
    if (filter === "groups") return conversation.remoteJid.endsWith("@g.us") && !conversation.archivedAt;
    if (filter === "favorite") return conversation.favorite && !conversation.archivedAt;
    if (filter === "archived") return Boolean(conversation.archivedAt);
    return !conversation.archivedAt;
  }), [conversations, filter, query]);
  const matchedClient = useMemo(() => active ? clients.find((client) => normalizeBrazilianPhone(client.phone) === normalizeBrazilianPhone(active.contactPhone)) ?? null : null, [active, clients]);
  const clientOptions = useMemo(() => clients.filter((client) => `${client.name} ${client.phone}`.toLowerCase().includes(clientQuery.toLowerCase())).slice(0, 8), [clientQuery, clients]);
  const warning = (conversation: Conversation) => conversation.messages.at(-1)?.direction === "INBOUND" && (Date.now() - new Date(conversation.lastMessageAt).getTime()) / 60_000 >= (Number(slaValue) || slaMinutes) * .8;
  const menuAction = (conversation: Conversation, action: "archive" | "pin" | "unread" | "favorite" | "list" | "clear" | "delete") => { const form = new FormData(); form.set("conversationId", conversation.id); form.set("action", action); if (action === "list") form.set("listName", "Lista de atendimento"); startTransition(async () => { try { await updateWhatsAppConversationAction(form); setMenuId(""); setNotice(action === "delete" ? "Conversa excluída." : action === "clear" ? "Mensagens removidas da conversa." : "Conversa atualizada."); if (action === "delete") setActiveId(""); } catch { setNotice("Não foi possível atualizar a conversa."); } }); };
  const linkClient = (playerId: string) => { if (!active || !playerId) return; const form = new FormData(); form.set("conversationId", active.id); form.set("playerId", playerId); startTransition(async () => { try { await linkWhatsAppConversationToClientAction(form); setClientQuery(""); setNotice("Cliente vinculado à conversa."); } catch { setNotice("Não foi possível vincular o cliente."); } }); };
  const saveSla = () => { const form = new FormData(); form.set("minutes", slaValue); startTransition(async () => { try { await updateWhatsAppSlaAction(form); setShowSla(false); setNotice("SLA de atendimento atualizado."); } catch { setNotice("Informe um SLA entre 5 minutos e 24 horas."); } }); };
  useEffect(() => { if (active?.unreadCount) { const form = new FormData(); form.set("conversationId", active.id); void markWhatsAppConversationReadAction(form); } }, [active?.id, active?.unreadCount]);
  useEffect(() => { if (!activeId && visible[0]) setActiveId(visible[0].id); }, [activeId, visible]);
  if (!connected) return <section className="whatsapp-chat-empty"><strong>Conecte o WhatsApp da arena para começar.</strong><span>O QR Code fica em Configurações › Integrações.</span></section>;
  return <section className="whatsapp-chat-workspace whatsapp-inbox">
    <aside className="whatsapp-inbox-list"><header><div><span>CAIXA DE ENTRADA</span><strong>Conversas</strong></div><div className="whatsapp-header-actions"><button type="button" title="Configurar SLA" onClick={() => setShowSla((value) => !value)}>◷</button><button type="button" title="Novo contato" onClick={() => setShowContact(true)}>♙+</button>{showSla ? <div className="whatsapp-sla-popover"><label>Tempo de SLA <input value={slaValue} onChange={(event) => setSlaValue(event.target.value.replace(/\D/g, ""))} inputMode="numeric" /> min</label><button type="button" onClick={saveSla} disabled={pending}>Salvar</button></div> : null}</div></header>
      <div className="whatsapp-filters" role="tablist" aria-label="Filtros de conversas">{([ ["all", "Conversas", "▱"], ["unread", "Não lidas", "✉"], ["groups", "Grupos", "♧"], ["favorite", "Favoritas", "♡"], ["archived", "Arquivadas", "▣"] ] as [Filter, string, string][]).map(([id, label, icon]) => <button key={id} type="button" className={filter === id ? "is-active" : ""} onClick={() => setFilter(id)} title={label}><i>{icon}</i><span>{label}</span></button>)}</div>
      <div className="whatsapp-list-tools"><label><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nome, telefone ou empresa" /></label></div>
      <div className="whatsapp-conversation-list">{visible.map((conversation) => { const last = conversation.messages.at(-1); return <div key={conversation.id} className="whatsapp-conversation-item"><button type="button" className={`${conversation.id === active?.id ? "is-active" : ""} ${warning(conversation) ? "is-sla-warning" : ""}`} onClick={() => { setActiveId(conversation.id); setMenuId(""); }}><i className="whatsapp-contact-avatar">{initials(conversation.contactName || conversation.contactPhone)}</i><span><strong>{conversation.contactName || conversation.player?.name || formatPhone(conversation.contactPhone)}{conversation.pinned ? <b className="whatsapp-pin">⌖</b> : null}</strong><small>{last?.body || "Sem mensagens"}</small>{warning(conversation) ? <em>SLA próximo do limite</em> : null}</span><time>{time(conversation.lastMessageAt)}{conversation.unreadCount ? <b>{conversation.unreadCount}</b> : null}</time></button><button className="whatsapp-menu-trigger" type="button" aria-label="Ações da conversa" onClick={() => { setActiveId(conversation.id); setMenuId(menuId === conversation.id ? "" : conversation.id); }}>⋮</button>{menuId === conversation.id ? <div className="whatsapp-conversation-menu"><button onClick={() => menuAction(conversation, "archive")}>▣ {conversation.archivedAt ? "Desarquivar conversa" : "Arquivar conversa"}</button><button onClick={() => menuAction(conversation, "pin")}>⌖ {conversation.pinned ? "Desafixar conversa" : "Fixar conversa"}</button><button onClick={() => menuAction(conversation, "unread")}>✉ Marcar como não lida</button><button onClick={() => menuAction(conversation, "favorite")}>♡ {conversation.favorite ? "Remover dos favoritos" : "Adicionar aos favoritos"}</button><button onClick={() => menuAction(conversation, "list")}>☷ Adicionar à lista</button><hr /><button onClick={() => menuAction(conversation, "clear")}>◇ Limpar conversa</button><button className="is-danger" onClick={() => menuAction(conversation, "delete")}>♙ Excluir conversa</button></div> : null}</div>; })}{!visible.length ? <p>Nenhuma conversa encontrada.</p> : null}</div></aside>
    <main className="whatsapp-chat-main">{active ? <><header><div><i className="whatsapp-contact-avatar">{initials(active.contactName || active.contactPhone)}</i><span><strong>{active.contactName || active.player?.name || formatPhone(active.contactPhone)}</strong><small>WhatsApp · {formatPhone(active.contactPhone)}</small></span></div><span className="whatsapp-chat-channel">WhatsApp</span></header><div className="whatsapp-message-thread">{active.messages.map((message) => <article key={message.id} className={message.direction === "OUTBOUND" ? "outbound" : "inbound"}><p>{message.body}</p><time>{detailTime(message.sentAt)}</time></article>)}</div><form onSubmit={(event) => { event.preventDefault(); if (!body.trim()) return; const form = new FormData(); form.set("conversationId", active.id); form.set("body", body); startTransition(async () => { try { await sendWhatsAppChatMessageAction(form); setBody(""); } catch { setNotice("Não foi possível enviar a mensagem."); } }); }}><input ref={fileInput} type="file" hidden onChange={(event) => { if (event.target.files?.[0]) setNotice(`Anexo selecionado: ${event.target.files[0].name}. O envio de arquivos será liberado na próxima atualização do canal.`); }} /><button type="button" className="whatsapp-composer-icon" title="Anexar arquivo" onClick={() => fileInput.current?.click()}>⌕</button><button type="button" className="whatsapp-composer-icon" title="Novo contato" onClick={() => setShowContact(true)}>♙</button><button type="button" className="whatsapp-composer-icon" title="Inserir emoji" onClick={() => setBody((value) => `${value} 🙂`)}>☺</button><label className="whatsapp-composer-field"><span>MENSAGEM OU LEGENDA</span><textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder="Digite uma mensagem..." rows={1} /></label><button type="button" className="whatsapp-composer-icon" title="Inserir emoji" onClick={() => setBody((value) => `${value} 🙂`)}>☻</button><button className="whatsapp-send-button" disabled={pending} title="Enviar mensagem">➤</button></form></> : <div className="whatsapp-chat-empty"><strong>Selecione uma conversa.</strong></div>}</main>
    <aside className="whatsapp-contact-panel">{active ? <><header><i className="whatsapp-contact-avatar">{initials(active.contactName || active.contactPhone)}</i><strong>{active.contactName || active.player?.name || "Contato do WhatsApp"}</strong><span>Contato no WhatsApp</span></header><dl><div><dt>Telefone</dt><dd>{formatPhone(active.contactPhone)}</dd></div><div><dt>Cliente no sistema</dt><dd>{active.player ? active.player.name : "Não vinculado"}</dd></div>{active.player?.email ? <div><dt>E-mail</dt><dd>{active.player.email}</dd></div> : null}</dl>{!active.player ? <div className="whatsapp-link-client"><strong>{matchedClient ? "Cliente encontrado pelo telefone" : "Vincular a um cliente"}</strong><p>{matchedClient ? matchedClient.name : "Busque pelo nome ou telefone para vincular."}</p>{matchedClient ? <button type="button" className="button button-primary button-small" onClick={() => linkClient(matchedClient.id)} disabled={pending}>Vincular {matchedClient.name}</button> : <><input value={clientQuery} onChange={(event) => setClientQuery(event.target.value)} placeholder="Digite nome ou telefone" /><div className="whatsapp-client-options">{clientOptions.map((client) => <button key={client.id} type="button" onClick={() => linkClient(client.id)}>{client.name}<small>{formatPhone(client.phone)}</small></button>)}</div></>}</div> : null}</> : null}</aside>
    {showContact ? <div className="whatsapp-contact-modal" role="dialog" aria-modal="true"><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); startTransition(async () => { try { const result = await createWhatsAppContactAction(form); setShowContact(false); setNotice(`${result.name} foi adicionado aos clientes.`); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível criar o contato."); } }); }}><header><strong>Novo contato</strong><button type="button" onClick={() => setShowContact(false)}>×</button></header><label>Nome<input name="name" required minLength={3} placeholder="Nome completo" /></label><label>Telefone<input name="phone" required placeholder="(00) 00000-0000" /></label><button className="button button-primary" disabled={pending}>Adicionar contato</button></form></div> : null}
    {notice ? <p className="whatsapp-workspace-notice" role="status">{notice}</p> : null}
  </section>;
}
