/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "whatsapp_message_menu_trigger": [
    "whatsapp-message-menu-trigger", "tw:absolute", "tw:top-[4px]", "tw:right-[4px]",
    "tw:grid", "tw:place-items-center", "tw:w-[22px]", "tw:h-[22px]",
    "tw:min-h-[0]", "tw:pt-[0]", "tw:pr-[0]", "tw:pb-[0]",
    "tw:pl-[0]", "tw:border-t-[length:0]", "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]",
    "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]",
    "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]", "tw:[border-left-style:none]",
    "tw:border-l-[color:currentColor]", "tw:rounded-[5px]", "tw:text-[color:#58756a]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:cursor-pointer", "tw:hover:bg-[color:rgb(0_0_0_/_.06)]", "tw:hover:[background-image:none]",
  ].join(" "),
  "whatsapp_quoted_message": [
    "whatsapp-quoted-message", "tw:grid", "tw:gap-y-[3px]", "tw:gap-x-[3px]",
    "tw:mt-[4px]", "tw:mr-[12px]", "tw:mb-[7px]", "tw:ml-[0]",
    "tw:pt-[7px]", "tw:pr-[9px]", "tw:pb-[7px]", "tw:pl-[9px]",
    "tw:border-l-[length:3px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#2c9b70]", "tw:rounded-[5px]",
    "tw:bg-[color:rgb(40_98_68_/_.065)]", "tw:[background-image:none]", "tw:[&_strong]:text-[color:#207956]", "tw:[&_strong]:text-[.7rem]",
    "tw:[&_span]:[display:-webkit-box]", "tw:[&_span]:[overflow-x:hidden]", "tw:[&_span]:[overflow-y:hidden]", "tw:[&_span]:[-webkit-line-clamp:3]",
    "tw:[&_span]:[-webkit-box-orient:vertical]", "tw:[&_span]:text-[color:#52665e]", "tw:[&_span]:text-[.72rem]", "tw:[&_span]:whitespace-pre-wrap",
  ].join(" "),
  "whatsapp_message_image": [
    "whatsapp-message-image", "tw:block", "tw:w-[min(100%,_360px)]", "tw:max-h-[360px]",
    "tw:[object-fit:cover]", "tw:rounded-[10px]", "tw:mt-[0]", "tw:mr-[0]",
    "tw:mb-[6px]", "tw:ml-[0]", "tw:[cursor:zoom-in]",
  ].join(" "),
  "whatsapp_message_audio": [
    "whatsapp-message-audio", "tw:block", "tw:w-[min(310px,_100%)]", "tw:mt-[0]",
    "tw:mr-[0]", "tw:mb-[6px]", "tw:ml-[0]", "tw:h-[42px]",
    "tw:[accent-color:#128c7e]", "tw:min-w-[270px]", "tw:pt-[2px]", "tw:pr-[2px]",
    "tw:pb-[2px]", "tw:pl-[2px]", "tw:rounded-[999px]", "tw:bg-[color:#e7f4ee]",
    "tw:[background-image:none]",
  ].join(" "),
  "whatsapp_message_video": [
    "whatsapp-message-video", "tw:block", "tw:w-[min(100%,_360px)]", "tw:max-h-[360px]",
    "tw:[object-fit:cover]", "tw:rounded-[10px]", "tw:mt-[0]", "tw:mr-[0]",
    "tw:mb-[6px]", "tw:ml-[0]",
  ].join(" "),
  "whatsapp_message_document": [
    "whatsapp-message-document", "tw:inline-flex", "tw:pt-[8px]", "tw:pr-[10px]",
    "tw:pb-[8px]", "tw:pl-[10px]", "tw:text-[color:inherit]", "tw:bg-[color:rgba(255,255,255,.16)]",
    "tw:[background-image:none]", "tw:rounded-[8px]", "tw:mb-[6px]",
  ].join(" "),
  "whatsapp_message_meta": [
    "whatsapp-message-meta", "tw:flex", "tw:items-baseline", "tw:justify-end",
    "tw:flex-wrap", "tw:gap-y-[4px]", "tw:gap-x-[10px]", "tw:mt-[5px]",
    "tw:[&_>_span]:text-[color:#526b60]", "tw:[&_>_span]:text-[.65rem]", "tw:[&_>_span]:leading-[1.4]", "tw:[&_>_span]:[overflow-wrap:anywhere]",
  ].join(" "),
  "whatsapp_message_reactions": [
    "whatsapp-message-reactions", "tw:flex", "tw:flex-wrap", "tw:gap-y-[4px]",
    "tw:gap-x-[4px]", "tw:mt-[6px]", "tw:[&_button]:inline-flex", "tw:[&_button]:items-center",
    "tw:[&_button]:gap-y-[4px]", "tw:[&_button]:gap-x-[4px]", "tw:[&_button]:min-h-[26px]", "tw:[&_button]:pt-[2px]",
    "tw:[&_button]:pr-[6px]", "tw:[&_button]:pb-[2px]", "tw:[&_button]:pl-[6px]", "tw:[&_button]:border-t-[length:1px]",
    "tw:[&_button]:[border-top-style:solid]", "tw:[&_button]:border-t-[color:#d4e1d9]", "tw:[&_button]:border-r-[length:1px]", "tw:[&_button]:[border-right-style:solid]",
    "tw:[&_button]:border-r-[color:#d4e1d9]", "tw:[&_button]:border-b-[length:1px]", "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:#d4e1d9]",
    "tw:[&_button]:border-l-[length:1px]", "tw:[&_button]:[border-left-style:solid]", "tw:[&_button]:border-l-[color:#d4e1d9]", "tw:[&_button]:rounded-[999px]",
    "tw:[&_button]:bg-[color:#fff]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:cursor-pointer", "tw:[&_button.is-own]:border-t-[color:#6db491]",
    "tw:[&_button.is-own]:border-r-[color:#6db491]", "tw:[&_button.is-own]:border-b-[color:#6db491]", "tw:[&_button.is-own]:border-l-[color:#6db491]", "tw:[&_button.is-own]:bg-[color:#effaf3]",
    "tw:[&_button.is-own]:[background-image:none]", "tw:[&_small]:text-[color:#526b60]", "tw:[&_small]:text-[.63rem]",
  ].join(" "),
  "whatsapp_message_actions": [
    "whatsapp-message-actions", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:min-w-[min(235px,_100%)]", "tw:mt-[9px]", "tw:pt-[8px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(30_75_54_/_.13)]", "tw:[&_>_button]:w-[fit-content]", "tw:[&_>_button]:min-h-[30px]",
    "tw:[&_>_button]:pt-[4px]", "tw:[&_>_button]:pr-[10px]", "tw:[&_>_button]:pb-[4px]", "tw:[&_>_button]:pl-[10px]",
    "tw:[&_>_button]:border-t-[length:1px]", "tw:[&_>_button]:[border-top-style:solid]", "tw:[&_>_button]:border-t-[color:#c6dad0]", "tw:[&_>_button]:border-r-[length:1px]",
    "tw:[&_>_button]:[border-right-style:solid]", "tw:[&_>_button]:border-r-[color:#c6dad0]", "tw:[&_>_button]:border-b-[length:1px]", "tw:[&_>_button]:[border-bottom-style:solid]",
    "tw:[&_>_button]:border-b-[color:#c6dad0]", "tw:[&_>_button]:border-l-[length:1px]", "tw:[&_>_button]:[border-left-style:solid]", "tw:[&_>_button]:border-l-[color:#c6dad0]",
    "tw:[&_>_button]:rounded-[6px]", "tw:[&_>_button]:text-[color:#1c6249]", "tw:[&_>_button]:bg-[color:#fff]", "tw:[&_>_button]:[background-image:none]",
    "tw:[&_>_button]:[font:inherit]", "tw:[&_>_button]:text-[.74rem]", "tw:[&_>_button]:cursor-pointer",
  ].join(" "),
  "whatsapp_reaction_picker": [
    "whatsapp-reaction-picker", "tw:grid", "tw:grid-cols-[repeat(6,_minmax(0,_1fr))]", "tw:gap-y-[3px]",
    "tw:gap-x-[3px]", "tw:[&_button]:grid", "tw:[&_button]:place-items-center", "tw:[&_button]:min-w-[0]",
    "tw:[&_button]:min-h-[32px]", "tw:[&_button]:pt-[4px]", "tw:[&_button]:pr-[4px]", "tw:[&_button]:pb-[4px]",
    "tw:[&_button]:pl-[4px]", "tw:[&_button]:border-t-[length:1px]", "tw:[&_button]:[border-top-style:solid]", "tw:[&_button]:border-t-[color:transparent]",
    "tw:[&_button]:border-r-[length:1px]", "tw:[&_button]:[border-right-style:solid]", "tw:[&_button]:border-r-[color:transparent]", "tw:[&_button]:border-b-[length:1px]",
    "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:transparent]", "tw:[&_button]:border-l-[length:1px]", "tw:[&_button]:[border-left-style:solid]",
    "tw:[&_button]:border-l-[color:transparent]", "tw:[&_button]:rounded-[6px]", "tw:[&_button]:bg-[color:transparent]", "tw:[&_button]:[background-image:none]",
    "tw:[&_button]:text-[1.12rem]", "tw:[&_button]:cursor-pointer", "tw:[&_button:hover]:border-t-[color:#a5cfb6]", "tw:[&_button:hover]:border-r-[color:#a5cfb6]",
    "tw:[&_button:hover]:border-b-[color:#a5cfb6]", "tw:[&_button:hover]:border-l-[color:#a5cfb6]", "tw:[&_button:hover]:bg-[color:#fff]", "tw:[&_button:hover]:[background-image:none]",
    "tw:[&_button.is-own]:border-t-[color:#a5cfb6]", "tw:[&_button.is-own]:border-r-[color:#a5cfb6]", "tw:[&_button.is-own]:border-b-[color:#a5cfb6]", "tw:[&_button.is-own]:border-l-[color:#a5cfb6]",
    "tw:[&_button.is-own]:bg-[color:#fff]", "tw:[&_button.is-own]:[background-image:none]",
  ].join(" "),
} as const;
