"use client";

import { useEffect, useMemo, useState, useTransition } from "react";
import { linkWhatsAppConversationToClientAction, markWhatsAppConversationReadAction, sendWhatsAppChatMessageAction, updateWhatsAppSlaAction } from "@/lib/actions/whatsapp-chat";
import { normalizeBrazilianPhone } from "@/lib/phone";

type Client = { id: string; name: string; phone: string; email: string };
type Conversation = { id: string; contactName: string; contactPhone: string; unreadCount: number; lastMessageAt: string; playerId: string | null; player: Client | null; messages: { id: string; direction: string; body: string; sentAt: string }[] };
const time = (value: string) => new Intl.DateTimeFormat("pt-BR", { hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const detailTime = (value: string) => new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
const initials = (name: string) => name.split(/\s+/).filter(Boolean).slice(0, 2).map((word) => word[0]).join("").toUpperCase() || "WA";
const formatPhone = (value: string) => { const digits = value.replace(/\D/g, ""); return digits.length >= 10 ? `(${digits.slice(-11, -9)}) ${digits.slice(-9, -4)}-${digits.slice(-4)}` : value || "Não informado"; };

export function WhatsAppChatWorkspace({ conversations, connected, clients, slaMinutes }: { conversations: Conversation[]; connected: boolean; clients: Client[]; slaMinutes: number }) {
  const [activeId, setActiveId] = useState(conversations[0]?.id ?? "");
  const [body, setBody] = useState(""); const [query, setQuery] = useState(""); const [slaValue, setSlaValue] = useState(String(slaMinutes)); const [notice, setNotice] = useState(""); const [pending, startTransition] = useTransition();
  const active = conversations.find((conversation) => conversation.id === activeId) ?? conversations[0] ?? null;
  const filtered = useMemo(() => conversations.filter((conversation) => `${conversation.contactName} ${conversation.contactPhone} ${conversation.player?.name ?? ""}`.toLowerCase().includes(query.trim().toLowerCase())), [conversations, query]);
  const matchedClient = useMemo(() => active ? clients.find((client) => normalizeBrazilianPhone(client.phone) === normalizeBrazilianPhone(active.contactPhone)) ?? null : null, [active, clients]);
  const warning = (conversation: Conversation) => conversation.messages.at(-1)?.direction === "INBOUND" && (Date.now() - new Date(conversation.lastMessageAt).getTime()) / 60_000 >= (Number(slaValue) || slaMinutes) * .8;
  useEffect(() => { if (active?.unreadCount) { const form = new FormData(); form.set("conversationId", active.id); void markWhatsAppConversationReadAction(form); } }, [active?.id, active?.unreadCount]);
  useEffect(() => { if (!activeId && conversations[0]) setActiveId(conversations[0].id); }, [activeId, conversations]);
  if (!connected) return <section className="whatsapp-chat-empty"><strong>Conecte o WhatsApp da arena para começar.</strong><span>O QR Code fica em Configurações › Integrações.</span></section>;
  const linkClient = (playerId: string) => { if (!active || !playerId) return; const form = new FormData(); form.set("conversationId", active.id); form.set("playerId", playerId); startTransition(async () => { try { await linkWhatsAppConversationToClientAction(form); setNotice("Cliente vinculado à conversa."); } catch { setNotice("Não foi possível vincular o cliente."); } }); };
  const saveSla = () => { const form = new FormData(); form.set("minutes", slaValue); startTransition(async () => { try { await updateWhatsAppSlaAction(form); setNotice("SLA de atendimento atualizado."); } catch { setNotice("Informe um SLA entre 5 minutos e 24 horas."); } }); };

  return <section className="whatsapp-chat-workspace whatsapp-inbox">
    <aside className="whatsapp-inbox-list"><header><div><span>CAIXA DE ENTRADA</span><strong>Conversas</strong></div><b>{conversations.length}</b></header><div className="whatsapp-list-tools"><label><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar conversa" /></label><div className="whatsapp-sla-control"><span>SLA</span><input value={slaValue} onChange={(event) => setSlaValue(event.target.value.replace(/\D/g, ""))} inputMode="numeric" aria-label="SLA em minutos" /><em>min</em><button type="button" onClick={saveSla} disabled={pending}>Salvar</button></div></div><div className="whatsapp-conversation-list">{filtered.map((conversation) => { const last = conversation.messages.at(-1); return <button key={conversation.id} type="button" className={`${conversation.id === active?.id ? "is-active" : ""} ${warning(conversation) ? "is-sla-warning" : ""}`} onClick={() => setActiveId(conversation.id)}><i className="whatsapp-contact-avatar">{initials(conversation.contactName || conversation.contactPhone)}</i><span><strong>{conversation.contactName || conversation.player?.name || formatPhone(conversation.contactPhone)}</strong><small>{last?.body || "Sem mensagens"}</small>{warning(conversation) ? <em>SLA próximo do limite</em> : null}</span><time>{time(conversation.lastMessageAt)}{conversation.unreadCount ? <b>{conversation.unreadCount}</b> : null}</time></button>; })}{!filtered.length ? <p>Nenhuma conversa encontrada.</p> : null}</div></aside>
    <main className="whatsapp-chat-main">{active ? <><header><div><i className="whatsapp-contact-avatar">{initials(active.contactName || active.contactPhone)}</i><span><strong>{active.contactName || active.player?.name || formatPhone(active.contactPhone)}</strong><small>WhatsApp · {formatPhone(active.contactPhone)}</small></span></div><span className="whatsapp-chat-channel">WhatsApp</span></header><div className="whatsapp-message-thread">{active.messages.map((message) => <article key={message.id} className={message.direction === "OUTBOUND" ? "outbound" : "inbound"}><p>{message.body}</p><time>{detailTime(message.sentAt)}</time></article>)}</div><form onSubmit={(event) => { event.preventDefault(); if (!body.trim()) return; const form = new FormData(); form.set("conversationId", active.id); form.set("body", body); startTransition(async () => { try { await sendWhatsAppChatMessageAction(form); setBody(""); } catch { setNotice("Não foi possível enviar a mensagem."); } }); }}><textarea value={body} onChange={(event) => setBody(event.target.value)} placeholder="Digite uma mensagem" rows={2} /><button className="button button-primary button-small" disabled={pending}>{pending ? "Enviando..." : "Enviar"}</button></form></> : <div className="whatsapp-chat-empty"><strong>Selecione uma conversa.</strong></div>}</main>
    <aside className="whatsapp-contact-panel">{active ? <><header><i className="whatsapp-contact-avatar">{initials(active.contactName || active.contactPhone)}</i><strong>{active.contactName || active.player?.name || "Contato do WhatsApp"}</strong><span>Contato no WhatsApp</span></header><dl><div><dt>Telefone</dt><dd>{formatPhone(active.contactPhone)}</dd></div><div><dt>Cliente no sistema</dt><dd>{active.player ? active.player.name : "Não vinculado"}</dd></div>{active.player?.email ? <div><dt>E-mail</dt><dd>{active.player.email}</dd></div> : null}</dl>{!active.player ? <div className="whatsapp-link-client"><strong>{matchedClient ? "Cliente encontrado pelo telefone" : "Vincular a um cliente"}</strong><p>{matchedClient ? matchedClient.name : "Associe esta conversa ao cadastro correto."}</p>{matchedClient ? <button type="button" className="button button-primary button-small" onClick={() => linkClient(matchedClient.id)} disabled={pending}>Vincular {matchedClient.name}</button> : <select defaultValue="" onChange={(event) => linkClient(event.target.value)} disabled={pending}><option value="">Selecionar cliente</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name} · {formatPhone(client.phone)}</option>)}</select>}</div> : null}</> : null}</aside>
    {notice ? <p className="whatsapp-workspace-notice" role="status">{notice}</p> : null}
  </section>;
}
