import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "whatsapp_contact_avatar": [
    "whatsapp-contact-avatar", "tw:[&_img.whatsapp-photo-expandable]:[cursor:zoom-in]", "tw:[&_img[role=button]:focus-visible]:[outline:2px_solid_var(--primary)]", "tw:[&_img[role=button]:focus-visible]:[outline-offset:2px]",
    "tw:grid", "tw:w-[34px]", "tw:h-[34px]", "tw:place-items-center",
    "tw:rounded-[50%]", "tw:text-[color:#fff]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(135deg,_#2aa676,_#176b8c)]",
    "tw:text-[.68rem]", "tw:not-italic", "tw:font-[850]", "tw:[overflow-x:hidden]",
    "tw:[overflow-y:hidden]", "tw:[flex:0_0_auto]", "tw:[&_img]:block", "tw:[&_img]:w-[100%]",
    "tw:[&_img]:h-[100%]", "tw:[&_img]:[object-fit:cover]", "tw:[&.is-header]:w-[36px]", "tw:[&.is-header]:h-[36px]",
    "tw:[&.is-profile]:w-[58px]", "tw:[&.is-profile]:h-[58px]",
  ].join(" "),
  "whatsapp_chat_empty": [
    "whatsapp-chat-empty", "tw:grid", "tw:min-h-[190px]", "tw:[place-content:center]",
    "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:pt-[24px]", "tw:pr-[24px]",
    "tw:pb-[24px]", "tw:pl-[24px]", "tw:text-[color:#647b93]", "tw:text-center",
    "tw:[&_strong]:text-[color:#173b65]",
  ].join(" "),
  "whatsapp_chat_workspace_whatsapp_inbox": [
    "whatsapp-chat-workspace", "whatsapp-inbox", "tw:grid", "tw:grid-cols-[minmax(260px,_310px)_minmax(400px,_1fr)_minmax(230px,_285px)]",
    "tw:viewport-1100:grid-cols-[minmax(240px,_290px)_minmax(0,_1fr)]", "tw:viewport-720:grid-cols-[1fr]", "tw:min-h-[min(760px,_calc(100vh_-_150px))]", "tw:viewport-720:min-h-[720px]",
    "tw:[@media(min-width:721px)]:min-h-[0]", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#d8e4ee]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#d8e4ee]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d8e4ee]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d8e4ee]", "tw:rounded-[10px]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[&_>_aside]:border-r-[length:1px]", "tw:viewport-720:[&_>_aside]:border-r-[length:0]",
    "tw:[&_>_aside]:[border-right-style:solid]", "tw:viewport-720:[&_>_aside]:[border-right-style:none]", "tw:[&_>_aside]:border-r-[color:#e2eaf2]", "tw:viewport-720:[&_>_aside]:border-r-[color:currentColor]",
    "tw:[&_>_aside]:bg-[color:#fbfdff]", "tw:[&_>_aside]:[background-image:none]", "tw:[&_header]:flex", "tw:[&_header]:items-center",
    "tw:[&_header]:justify-between", "tw:[&_header]:min-h-[58px]", "tw:[&_header]:pt-[0]", "tw:[&_header]:pr-[16px]",
    "tw:[&_header]:pb-[0]", "tw:[&_header]:pl-[16px]", "tw:[&_header]:border-b-[length:1px]", "tw:[&_header]:[border-bottom-style:solid]",
    "tw:[&_header]:border-b-[color:#e2eaf2]", "tw:[&_header]:text-[color:#173b65]", "tw:[&_header_span]:text-[color:#59728d]", "tw:[&_header_span]:text-[.74rem]",
    "tw:[&_>_main]:grid", "tw:[&_>_main]:grid-rows-[auto_minmax(0,_1fr)_auto]", "tw:[&_>_main]:min-w-[0]", "tw:[&_main_header_div]:grid",
    "tw:[&_main_header_div]:gap-y-[2px]", "tw:[&_main_header_div]:gap-x-[2px]", "tw:[&_main_header_small]:text-[color:#71849a]", "tw:[&_main_header_small]:text-[.7rem]",
    "tw:[&_main_form]:grid", "tw:[&_main_form]:grid-cols-[minmax(0,_1fr)_auto]", "tw:[&_main_form]:gap-y-[8px]", "tw:[&_main_form]:gap-x-[8px]",
    "tw:[&_main_form]:pt-[12px]", "tw:[&_main_form]:pr-[12px]", "tw:[&_main_form]:pb-[12px]", "tw:[&_main_form]:pl-[12px]",
    "tw:[&_main_form]:border-t-[length:1px]", "tw:[&_main_form]:[border-top-style:solid]", "tw:[&_main_form]:border-t-[color:#e2eaf2]", "tw:[&_textarea]:min-h-[40px]",
    "tw:[&_textarea]:[resize:vertical]", "tw:viewport-720:[&_>_aside]:max-h-[240px]", "tw:viewport-720:[&_>_aside]:[overflow-y:auto]", "tw:viewport-720:[&_>_aside]:border-b-[length:1px]",
    "tw:viewport-720:[&_>_aside]:[border-bottom-style:solid]", "tw:viewport-720:[&_>_aside]:border-b-[color:#e2eaf2]", "tw:relative", "tw:[&_>_aside]:min-w-[0]",
    "tw:[&_>_.whatsapp-inbox-list_>_header]:min-h-[70px]", "tw:[&_>_.whatsapp-inbox-list_>_header]:pt-[12px]", "tw:[&_>_.whatsapp-inbox-list_>_header]:pr-[15px]", "tw:[&_>_.whatsapp-inbox-list_>_header]:pb-[12px]",
    "tw:[&_>_.whatsapp-inbox-list_>_header]:pl-[15px]", "tw:[&_.whatsapp-conversation-list]:[overflow-y:auto]", "tw:[@media(min-width:721px)]:[&_.whatsapp-conversation-list]:[overflow-y:auto]", "tw:[&_.whatsapp-conversation-list]:block",
    "tw:[&_.whatsapp-conversation-list]:[align-content:initial]", "tw:[&_.whatsapp-conversation-list_>_button]:grid-cols-[34px_minmax(0,_1fr)_auto]", "tw:[&_.whatsapp-conversation-list_>_button]:min-h-[76px]", "tw:[&_.whatsapp-conversation-list_>_button]:pt-[10px]",
    "tw:[&_.whatsapp-conversation-list_>_button]:pr-[12px]", "tw:[&_.whatsapp-conversation-list_>_button]:pb-[10px]", "tw:[&_.whatsapp-conversation-list_>_button]:pl-[12px]", "tw:[&_.whatsapp-conversation-list_>_button_>_span]:min-w-[0]",
    "tw:[&_.whatsapp-conversation-list_>_button_time]:grid", "tw:[&_.whatsapp-conversation-list_>_button_time]:[justify-items:end]", "tw:[&_.whatsapp-conversation-list_>_button_time]:gap-y-[5px]", "tw:[&_.whatsapp-conversation-list_>_button_time]:gap-x-[5px]",
    "tw:[&_.whatsapp-conversation-list_>_button.is-sla-warning]:border-l-[length:3px]", "tw:[&_.whatsapp-conversation-list_>_button.is-sla-warning]:[border-left-style:solid]", "tw:[&_.whatsapp-conversation-list_>_button.is-sla-warning]:border-l-[color:#e0ad27]", "tw:[&_.whatsapp-conversation-list_>_button.is-sla-warning]:bg-[color:#fff8dc]",
    "tw:[&_.whatsapp-conversation-list_>_button.is-sla-warning]:[background-image:none]", "tw:[&_.whatsapp-conversation-list_>_button.is-sla-warning:hover]:bg-[color:#fff3c5]", "tw:[&_.whatsapp-conversation-list_>_button.is-sla-warning:hover]:[background-image:none]", "tw:[&_.whatsapp-conversation-list_>_button.is-sla-warning.is-active]:bg-[color:#fff3c5]",
    "tw:[&_.whatsapp-conversation-list_>_button.is-sla-warning.is-active]:[background-image:none]", "tw:[&_.whatsapp-conversation-list_>_button.is-sla-warning_em]:block", "tw:[&_.whatsapp-conversation-list_>_button.is-sla-warning_em]:mt-[3px]", "tw:[&_.whatsapp-conversation-list_>_button.is-sla-warning_em]:text-[color:#b37405]",
    "tw:[&_.whatsapp-conversation-list_>_button.is-sla-warning_em]:text-[.6rem]", "tw:[&_.whatsapp-conversation-list_>_button.is-sla-warning_em]:not-italic", "tw:[&_.whatsapp-conversation-list_>_button.is-sla-warning_em]:font-[850]", "tw:[&_.whatsapp-conversation-list_>_button.is-active]:bg-[color:#eaf7f1]",
    "tw:[&_.whatsapp-conversation-list_>_button.is-active]:[background-image:none]", "tw:[&_.whatsapp-chat-main_>_header]:bg-[color:#fff]", "tw:[&_.whatsapp-chat-main_>_header]:[background-image:none]", "tw:[&_.whatsapp-chat-main_>_header_>_div]:flex",
    "tw:[&_.whatsapp-chat-main_>_header_>_div]:items-center", "tw:[&_.whatsapp-chat-main_>_header_>_div]:gap-y-[10px]", "tw:[&_.whatsapp-chat-main_>_header_>_div]:gap-x-[10px]", "tw:[&_.whatsapp-chat-main_>_header_>_div]:min-w-[0]",
    "tw:[&_.whatsapp-chat-main_>_header_.whatsapp-contact-avatar]:w-[36px]", "tw:[&_.whatsapp-chat-main_>_header_.whatsapp-contact-avatar]:h-[36px]", "tw:[&_.whatsapp-chat-main_>_header_span_span]:block", "tw:[&_.whatsapp-message-thread]:bg-[color:#efeae2]",
    "tw:[&_.whatsapp-message-thread]:[background-image:radial-gradient(rgb(116_108_92_/_.14)_1px,_transparent_1px),_radial-gradient(rgb(116_108_92_/_.11)_1px,_transparent_1px)]", "tw:[&_.whatsapp-message-thread]:[background-position:0_0,_12px_12px]", "tw:[&_.whatsapp-message-thread]:[background-size:24px_24px]", "tw:[&_.whatsapp-message-thread_article]:text-[color:#253943]",
    "tw:[&_.whatsapp-message-thread_article]:bg-[color:#fff]", "tw:[&_.whatsapp-message-thread_article]:[background-image:none]", "tw:[&_.whatsapp-message-thread_article]:[box-shadow:0_1px_2px_rgb(36_54_57_/_.16)]", "tw:[&_.whatsapp-message-thread_article.outbound]:text-[color:#183e30]",
    "tw:[&_.whatsapp-message-thread_article.outbound]:bg-[color:#d9fdd3]", "tw:[&_.whatsapp-message-thread_article.outbound]:[background-image:none]", "tw:[&_.whatsapp-message-thread_time]:text-[color:#70817b]", "tw:[&_.whatsapp-chat-main_form]:bg-[color:#f0f2f5]",
    "tw:[&_.whatsapp-chat-main_form]:[background-image:none]", "tw:[&_.whatsapp-chat-main_form]:grid-cols-[auto_auto_minmax(0,_1fr)_auto_auto]", "tw:[&_.whatsapp-chat-main_form]:items-stretch", "tw:[&_.whatsapp-chat-main_form]:gap-y-[6px]",
    "tw:[&_.whatsapp-chat-main_form]:gap-x-[6px]", "tw:[&_.whatsapp-chat-main_form]:pt-[10px]", "tw:[&_.whatsapp-chat-main_form]:pr-[12px]", "tw:[&_.whatsapp-chat-main_form]:pb-[10px]",
    "tw:[&_.whatsapp-chat-main_form]:pl-[12px]", "tw:[&_.whatsapp-chat-main_form]:min-h-[82px]", "tw:viewport-720:[&_.whatsapp-chat-main_form]:min-h-[72px]", "tw:[&_.whatsapp-chat-main_form]:relative",
    "tw:[&_.whatsapp-chat-main_textarea]:border-t-[color:#dde5e7]", "tw:[&_.whatsapp-chat-main_textarea]:border-r-[color:#dde5e7]", "tw:[&_.whatsapp-chat-main_textarea]:border-b-[color:#dde5e7]", "tw:[&_.whatsapp-chat-main_textarea]:border-l-[color:#dde5e7]",
    "tw:[&_.whatsapp-chat-main_textarea]:rounded-[8px]", "tw:[&_.whatsapp-chat-main_textarea]:bg-[color:#fff]", "tw:[&_.whatsapp-chat-main_textarea]:[background-image:none]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:w-[100%]",
    "tw:[&_.whatsapp-conversation-item_>_button:first-child]:grid", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:grid-cols-[34px_minmax(0,_1fr)_auto]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:gap-y-[9px]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:gap-x-[9px]",
    "tw:[&_.whatsapp-conversation-item_>_button:first-child]:items-center", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:min-h-[76px]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:pt-[10px]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:pr-[48px]",
    "tw:[&_.whatsapp-conversation-item_>_button:first-child]:pb-[10px]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:pl-[12px]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:border-t-[length:0]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:[border-top-style:none]",
    "tw:[&_.whatsapp-conversation-item_>_button:first-child]:border-t-[color:currentColor]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:border-r-[length:0]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:[border-right-style:none]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:border-r-[color:currentColor]",
    "tw:[&_.whatsapp-conversation-item_>_button:first-child]:border-b-[length:1px]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:[border-bottom-style:solid]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:border-b-[color:#edf1f5]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:border-l-[length:0]",
    "tw:[&_.whatsapp-conversation-item_>_button:first-child]:[border-left-style:none]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:border-l-[color:currentColor]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:text-[color:#254565]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:bg-[color:transparent]",
    "tw:[&_.whatsapp-conversation-item_>_button:first-child]:[background-image:none]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:[font:inherit]", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:text-left", "tw:[&_.whatsapp-conversation-item_>_button:first-child]:cursor-pointer",
    "tw:[&_.whatsapp-composer-field_textarea]:min-h-[38px]", "tw:[&_.whatsapp-composer-field_textarea]:pt-[5px]", "tw:[&_.whatsapp-composer-field_textarea]:pr-[0]", "tw:[&_.whatsapp-composer-field_textarea]:pb-[5px]",
    "tw:[&_.whatsapp-composer-field_textarea]:pl-[0]", "tw:[&_.whatsapp-composer-field_textarea]:border-t-[length:0]", "tw:[&_.whatsapp-composer-field_textarea]:[border-top-style:none]", "tw:[&_.whatsapp-composer-field_textarea]:border-t-[color:currentColor]",
    "tw:[&_.whatsapp-composer-field_textarea]:border-r-[length:0]", "tw:[&_.whatsapp-composer-field_textarea]:[border-right-style:none]", "tw:[&_.whatsapp-composer-field_textarea]:border-r-[color:currentColor]", "tw:[&_.whatsapp-composer-field_textarea]:border-b-[length:0]",
    "tw:[&_.whatsapp-composer-field_textarea]:[border-bottom-style:none]", "tw:[&_.whatsapp-composer-field_textarea]:border-b-[color:currentColor]", "tw:[&_.whatsapp-composer-field_textarea]:border-l-[length:0]", "tw:[&_.whatsapp-composer-field_textarea]:[border-left-style:none]",
    "tw:[&_.whatsapp-composer-field_textarea]:border-l-[color:currentColor]", "tw:[&_.whatsapp-composer-field_textarea]:rounded-[0]", "tw:[&_.whatsapp-composer-field_textarea]:[resize:none]", "tw:[&_.whatsapp-composer-field_textarea]:[outline:0]",
    "tw:[&_.whatsapp-composer-field_textarea]:bg-[color:transparent]", "tw:[&_.whatsapp-composer-field_textarea]:[background-image:none]", "tw:[&_.whatsapp-composer-field_textarea]:leading-[1.45]", "tw:[@media(min-width:721px)]:[&_.whatsapp-conversation-list]:min-h-[0]",
    "tw:[&_.whatsapp-conversation-item_>_button.is-sla-warning]:border-l-[length:3px]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-warning]:[border-left-style:solid]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-warning]:border-l-[color:#e0ad27]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-warning]:bg-[color:#fff8dc]",
    "tw:[&_.whatsapp-conversation-item_>_button.is-sla-warning]:[background-image:none]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-warning]:[animation:whatsapp-sla-warning-pulse_1.55s_ease-in-out_infinite]", "tw:motion-reduce:[&_.whatsapp-conversation-item_>_button.is-sla-warning]:[animation:none]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-warning_em]:text-[color:#a66900]",
    "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue]:border-l-[length:3px]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue]:[border-left-style:solid]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue]:border-l-[color:#d8423b]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue]:bg-[color:#fff1f0]",
    "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue]:[background-image:none]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue]:[animation:whatsapp-sla-overdue-pulse_1.05s_ease-in-out_infinite]", "tw:motion-reduce:[&_.whatsapp-conversation-item_>_button.is-sla-overdue]:[animation:none]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue_em]:block",
    "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue_em]:mt-[3px]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue_em]:text-[color:#bd302a]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue_em]:text-[.6rem]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue_em]:not-italic",
    "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue_em]:font-[850]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue_.whatsapp-contact-avatar]:[box-shadow:0_0_0_2px_#ef9c98]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-warning:hover]:bg-[color:#fff3c5]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-warning:hover]:[background-image:none]",
    "tw:[&_.whatsapp-conversation-item_>_button.is-sla-warning.is-active]:bg-[color:#fff3c5]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-warning.is-active]:[background-image:none]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue:hover]:bg-[color:#ffe3e1]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue:hover]:[background-image:none]",
    "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue.is-active]:bg-[color:#ffe3e1]", "tw:[&_.whatsapp-conversation-item_>_button.is-sla-overdue.is-active]:[background-image:none]", "tw:[&_.whatsapp-conversation-item]:grid", "tw:[&_.whatsapp-conversation-item]:min-h-[76px]",
    "tw:[&_.whatsapp-chat-main_>_header_>_div_>_span]:min-w-[0]", "tw:[&_.whatsapp-chat-main_>_header_>_div_>_span]:grid!", "tw:[&_.whatsapp-chat-main_>_header_>_div_>_span]:gap-y-[3px]", "tw:[&_.whatsapp-chat-main_>_header_>_div_>_span]:gap-x-[3px]",
    "tw:[&_.whatsapp-chat-main_>_header_small]:[overflow-x:hidden]", "tw:[&_.whatsapp-chat-main_>_header_small]:[overflow-y:hidden]", "tw:[&_.whatsapp-chat-main_>_header_small]:text-ellipsis", "tw:[&_.whatsapp-chat-main_>_header_small]:whitespace-nowrap",
    "tw:[&_.whatsapp-chat-main_>_header_small]:static!", "tw:[&_.whatsapp-chat-main_>_header_small]:max-w-[100%]", "tw:[&_.whatsapp-chat-main_>_header_strong]:static!", "tw:[&_.whatsapp-chat-main_>_header_strong]:max-w-[100%]",
    "tw:[&_.whatsapp-chat-main_>_header_strong]:[overflow-x:hidden]", "tw:[&_.whatsapp-chat-main_>_header_strong]:[overflow-y:hidden]", "tw:[&_.whatsapp-chat-main_>_header_strong]:text-ellipsis", "tw:[&_.whatsapp-chat-main_>_header_strong]:whitespace-nowrap",
    "tw:[&_.whatsapp-chat-main_form_>_button[title=\"Novo_contato\"]]:hidden", "tw:[&_.whatsapp-chat-main_form_.whatsapp-emoji-picker]:right-[46px]", "tw:[&_.whatsapp-chat-main_form_.whatsapp-emoji-picker]:bottom-[54px]", "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:grid",
    "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:grid-cols-[40px_40px_minmax(0,_1fr)_40px_40px]", "tw:viewport-600:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:grid-cols-[34px_34px_minmax(0,_1fr)_34px_34px]", "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:items-center", "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:gap-y-[7px]",
    "tw:viewport-600:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:gap-y-[4px]", "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:gap-x-[7px]", "tw:viewport-600:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:gap-x-[4px]", "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:min-h-[74px]",
    "tw:viewport-600:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:min-h-[62px]", "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:pt-[10px]", "tw:viewport-600:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:pt-[8px]", "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:pr-[14px]",
    "tw:viewport-600:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:pr-[7px]", "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:pb-[10px]", "tw:viewport-600:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:pb-[8px]", "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:pl-[14px]",
    "tw:viewport-600:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:pl-[7px]", "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:border-t-[length:1px]", "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:[border-top-style:solid]", "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:border-t-[color:#dce5e8]",
    "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:bg-[color:#f7f9fa]", "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer]:[background-image:none]", "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer_.whatsapp-emoji-picker]:right-[60px]", "tw:[&_.whatsapp-chat-main_>_form.whatsapp-composer_.whatsapp-emoji-picker]:bottom-[66px]",
  ].join(" "),
  "whatsapp_inbox_list": [
    "whatsapp-inbox-list", "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[&_>_header_>_div]:grid",
    "tw:[&_>_header_>_div]:gap-y-[3px]", "tw:[&_>_header_>_div]:gap-x-[3px]", "tw:[&_>_header_span]:text-[color:#087e5b]", "tw:[&_>_header_span]:text-[.62rem]",
    "tw:[&_>_header_span]:font-[900]", "tw:[&_>_header_span]:tracking-[.08em]", "tw:[&_>_header_strong]:text-[color:#173652]", "tw:[&_>_header_strong]:text-[1rem]",
    "tw:[&_>_header_>_b]:grid", "tw:[&_>_header_>_b]:min-w-[22px]", "tw:[&_>_header_>_b]:h-[22px]", "tw:[&_>_header_>_b]:place-items-center",
    "tw:[&_>_header_>_b]:rounded-[999px]", "tw:[&_>_header_>_b]:text-[color:#197454]", "tw:[&_>_header_>_b]:bg-[color:#e4f7ee]", "tw:[&_>_header_>_b]:[background-image:none]",
    "tw:[&_>_header_>_b]:text-[.69rem]", "tw:[@media(min-width:721px)]:grid", "tw:[@media(min-width:721px)]:grid-rows-[auto_auto_auto_minmax(0,_1fr)]", "tw:[@media(min-width:721px)]:min-h-[0]",
    "tw:[&_>_header_>_.whatsapp-header-actions]:flex", "tw:[&_>_header_>_.whatsapp-header-actions]:[grid-auto-flow:column]", "tw:[&_>_header_>_.whatsapp-header-actions]:grid-cols-[none]", "tw:[&_>_header_>_.whatsapp-header-actions]:items-center",
    "tw:[&_>_header_>_.whatsapp-header-actions]:justify-end", "tw:[&_>_header_>_.whatsapp-header-actions]:gap-y-[6px]", "tw:[&_>_header_>_.whatsapp-header-actions]:gap-x-[6px]", "tw:viewport-720:max-h-[280px]",
    "tw:viewport-720:border-b-[length:1px]", "tw:viewport-720:[border-bottom-style:solid]", "tw:viewport-720:border-b-[color:#e2eaf2]",
  ].join(" "),
  "whatsapp_header_actions": [
    "whatsapp-header-actions", "tw:relative", "tw:flex", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:items-center", "tw:flex-nowrap", "tw:[&_>_button]:grid",
    "tw:[&_>_button]:w-[30px]", "tw:[&_>_button]:h-[30px]", "tw:[&_>_button]:place-items-center", "tw:[&_>_button]:pt-[0]",
    "tw:[&_>_button]:pr-[0]", "tw:[&_>_button]:pb-[0]", "tw:[&_>_button]:pl-[0]", "tw:[&_>_button]:border-t-[length:1px]",
    "tw:[&_>_button]:[border-top-style:solid]", "tw:[&_>_button]:border-t-[color:#d9e4ec]", "tw:[&_>_button]:border-r-[length:1px]", "tw:[&_>_button]:[border-right-style:solid]",
    "tw:[&_>_button]:border-r-[color:#d9e4ec]", "tw:[&_>_button]:border-b-[length:1px]", "tw:[&_>_button]:[border-bottom-style:solid]", "tw:[&_>_button]:border-b-[color:#d9e4ec]",
    "tw:[&_>_button]:border-l-[length:1px]", "tw:[&_>_button]:[border-left-style:solid]", "tw:[&_>_button]:border-l-[color:#d9e4ec]", "tw:[&_>_button]:rounded-[7px]",
    "tw:[&_>_button]:text-[color:#294d69]", "tw:[&_>_button]:bg-[color:#fff]", "tw:[&_>_button]:[background-image:none]", "tw:[&_>_button]:[font:inherit]",
    "tw:[&_>_button]:cursor-pointer",
  ].join(" "),
  "whatsapp_sla_popover": [
    "whatsapp-sla-popover", "tw:absolute", "tw:top-[38px]", "tw:right-[0]",
    "tw:z-[5]", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:w-[205px]", "tw:pt-[11px]", "tw:pr-[11px]", "tw:pb-[11px]",
    "tw:pl-[11px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d6e3eb]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d6e3eb]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d6e3eb]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#d6e3eb]", "tw:rounded-[8px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[box-shadow:0_9px_24px_rgb(27_60_82_/_.17)]", "tw:[&_label]:grid", "tw:[&_label]:grid-cols-[1fr_48px_auto]", "tw:[&_label]:items-center",
    "tw:[&_label]:gap-y-[5px]", "tw:[&_label]:gap-x-[5px]", "tw:[&_label]:text-[color:#34536c]", "tw:[&_label]:text-[.68rem]",
    "tw:[&_label]:font-[750]", "tw:[&_input]:w-[48px]", "tw:[&_input]:min-h-[28px]", "tw:[&_input]:pt-[3px]",
    "tw:[&_input]:pr-[3px]", "tw:[&_input]:pb-[3px]", "tw:[&_input]:pl-[3px]", "tw:[&_input]:border-t-[length:1px]",
    "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#d4e0e9]", "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]",
    "tw:[&_input]:border-r-[color:#d4e0e9]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:#d4e0e9]",
    "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#d4e0e9]", "tw:[&_input]:rounded-[5px]",
    "tw:[&_input]:text-center", "tw:[&_button]:[justify-self:end]", "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]",
    "tw:[&_button]:border-t-[color:currentColor]", "tw:[&_button]:border-r-[length:0]", "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]",
    "tw:[&_button]:border-b-[length:0]", "tw:[&_button]:[border-bottom-style:none]", "tw:[&_button]:border-b-[color:currentColor]", "tw:[&_button]:border-l-[length:0]",
    "tw:[&_button]:[border-left-style:none]", "tw:[&_button]:border-l-[color:currentColor]", "tw:[&_button]:text-[color:#167052]", "tw:[&_button]:bg-[color:transparent]",
    "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[.7rem]", "tw:[&_button]:font-[850]", "tw:[&_button]:cursor-pointer",
  ].join(" "),
  "whatsapp_filters": [
    "whatsapp-filters", "tw:grid", "tw:grid-cols-[repeat(5,_1fr)]", "tw:gap-y-[3px]",
    "tw:gap-x-[3px]", "tw:mt-[9px]", "tw:mr-[12px]", "tw:mb-[0]",
    "tw:ml-[12px]", "tw:pt-[4px]", "tw:pr-[4px]", "tw:pb-[4px]",
    "tw:pl-[4px]", "tw:rounded-[8px]", "tw:bg-[color:#f4f6f8]", "tw:[background-image:none]",
    "tw:[&_button]:grid", "tw:[&_button]:min-h-[31px]", "tw:[&_button]:place-items-center", "tw:[&_button]:gap-y-[1px]",
    "tw:[&_button]:gap-x-[1px]", "tw:[&_button]:pt-[3px]", "tw:[&_button]:pr-[1px]", "tw:[&_button]:pb-[3px]",
    "tw:[&_button]:pl-[1px]", "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]",
    "tw:[&_button]:border-r-[length:0]", "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:0]",
    "tw:[&_button]:[border-bottom-style:none]", "tw:[&_button]:border-b-[color:currentColor]", "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]",
    "tw:[&_button]:border-l-[color:currentColor]", "tw:[&_button]:rounded-[6px]", "tw:[&_button]:text-[color:#678095]", "tw:[&_button]:bg-[color:transparent]",
    "tw:[&_button]:[background-image:none]", "tw:[&_button]:cursor-pointer", "tw:[&_button.is-active]:text-[color:#087e5b]", "tw:[&_button.is-active]:bg-[color:#fff]",
    "tw:[&_button.is-active]:[background-image:none]", "tw:[&_button.is-active]:[box-shadow:0_1px_3px_rgb(19_52_74_/_.09)]", "tw:[&_i]:not-italic", "tw:[&_i]:text-[.82rem]",
    "tw:[&_span]:hidden", "tw:[&_span]:text-[.57rem]", "tw:[&_span]:font-[750]",
  ].join(" "),
  "whatsapp_list_tools": [
    "whatsapp-list-tools", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:pt-[10px]", "tw:pr-[12px]", "tw:pb-[10px]", "tw:pl-[12px]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e9eff4]", "tw:[&_label]:flex",
    "tw:[&_label]:items-center", "tw:[&_label]:gap-y-[7px]", "tw:[&_label]:gap-x-[7px]", "tw:[&_label]:min-h-[34px]",
    "tw:[&_label]:pt-[0]", "tw:[&_label]:pr-[9px]", "tw:[&_label]:pb-[0]", "tw:[&_label]:pl-[9px]",
    "tw:[&_label]:border-t-[length:1px]", "tw:[&_label]:[border-top-style:solid]", "tw:[&_label]:border-t-[color:#d9e4ec]", "tw:[&_label]:border-r-[length:1px]",
    "tw:[&_label]:[border-right-style:solid]", "tw:[&_label]:border-r-[color:#d9e4ec]", "tw:[&_label]:border-b-[length:1px]", "tw:[&_label]:[border-bottom-style:solid]",
    "tw:[&_label]:border-b-[color:#d9e4ec]", "tw:[&_label]:border-l-[length:1px]", "tw:[&_label]:[border-left-style:solid]", "tw:[&_label]:border-l-[color:#d9e4ec]",
    "tw:[&_label]:rounded-[7px]", "tw:[&_label]:text-[color:#8092a2]", "tw:[&_input]:min-w-[0]", "tw:[&_input]:w-[100%]",
    "tw:[&_input]:border-t-[length:0]", "tw:[&_input]:[border-top-style:none]", "tw:[&_input]:border-t-[color:currentColor]", "tw:[&_input]:border-r-[length:0]",
    "tw:[&_input]:[border-right-style:none]", "tw:[&_input]:border-r-[color:currentColor]", "tw:[&_input]:border-b-[length:0]", "tw:[&_input]:[border-bottom-style:none]",
    "tw:[&_input]:border-b-[color:currentColor]", "tw:[&_input]:border-l-[length:0]", "tw:[&_input]:[border-left-style:none]", "tw:[&_input]:border-l-[color:currentColor]",
    "tw:[&_input]:[outline:0]", "tw:[&_input]:bg-[color:transparent]", "tw:[&_input]:[background-image:none]", "tw:[&_input]:[font:inherit]",
    "tw:[&_input]:text-[.76rem]",
  ].join(" "),
  "whatsapp_conversation_list": [
    "whatsapp-conversation-list", "tw:grid", "tw:[&_>_button]:grid", "tw:[&_>_button]:grid-cols-[minmax(0,_1fr)_auto]",
    "tw:[&_>_button]:gap-y-[9px]", "tw:[&_>_button]:gap-x-[9px]", "tw:[&_>_button]:items-center", "tw:[&_>_button]:min-h-[68px]",
    "tw:[&_>_button]:pt-[10px]", "tw:[&_>_button]:pr-[14px]", "tw:[&_>_button]:pb-[10px]", "tw:[&_>_button]:pl-[14px]",
    "tw:[&_>_button]:border-t-[length:0]", "tw:[&_>_button]:[border-top-style:none]", "tw:[&_>_button]:border-t-[color:currentColor]", "tw:[&_>_button]:border-r-[length:0]",
    "tw:[&_>_button]:[border-right-style:none]", "tw:[&_>_button]:border-r-[color:currentColor]", "tw:[&_>_button]:border-b-[length:1px]", "tw:[&_>_button]:[border-bottom-style:solid]",
    "tw:[&_>_button]:border-b-[color:#edf1f5]", "tw:[&_>_button]:border-l-[length:0]", "tw:[&_>_button]:[border-left-style:none]", "tw:[&_>_button]:border-l-[color:currentColor]",
    "tw:[&_>_button]:text-[color:#254565]", "tw:[&_>_button]:bg-[color:transparent]", "tw:[&_>_button]:[background-image:none]", "tw:[&_>_button]:[font:inherit]",
    "tw:[&_>_button]:text-left", "tw:[&_>_button]:cursor-pointer", "tw:[&_>_button:hover]:bg-[color:#eef7ff]", "tw:[&_>_button:hover]:[background-image:none]",
    "tw:[&_>_button.is-active]:bg-[color:#eef7ff]", "tw:[&_>_button.is-active]:[background-image:none]", "tw:[&_strong]:block", "tw:[&_strong]:[overflow-x:hidden]",
    "tw:[&_strong]:[overflow-y:hidden]", "tw:[&_strong]:text-ellipsis", "tw:[&_strong]:whitespace-nowrap", "tw:[&_strong]:text-[.8rem]",
    "tw:[&_small]:block", "tw:[&_small]:[overflow-x:hidden]", "tw:[&_small]:[overflow-y:hidden]", "tw:[&_small]:text-ellipsis",
    "tw:[&_small]:whitespace-nowrap", "tw:[&_small]:mt-[3px]", "tw:[&_small]:text-[color:#71849a]", "tw:[&_small]:text-[.71rem]",
    "tw:[&_b]:min-w-[18px]", "tw:[&_b]:pt-[2px]", "tw:[&_b]:pr-[5px]", "tw:[&_b]:pb-[2px]",
    "tw:[&_b]:pl-[5px]", "tw:[&_b]:rounded-[999px]", "tw:[&_b]:text-[color:#fff]", "tw:[&_b]:bg-[color:#1668b5]",
    "tw:[&_b]:[background-image:none]", "tw:[&_b]:text-[.65rem]", "tw:[&_b]:text-center", "tw:[&_time]:text-[color:#7a8ea3]",
    "tw:[&_time]:text-[.65rem]",
  ].join(" "),
  "whatsapp_conversation_item": [
    "whatsapp-conversation-item", "tw:relative", "tw:block!", "tw:grid-cols-[minmax(0,_1fr)_25px]",
    "tw:[&:hover_.whatsapp-menu-trigger]:opacity-[1]", "tw:[&_>_.whatsapp-menu-trigger]:absolute", "tw:[&_>_.whatsapp-menu-trigger]:top-[9px]", "tw:[&_>_.whatsapp-menu-trigger]:right-[8px]",
    "tw:[&_>_.whatsapp-menu-trigger]:z-[4]", "tw:[&_>_.whatsapp-menu-trigger]:w-[28px]", "tw:[&_>_.whatsapp-menu-trigger]:h-[28px]", "tw:[&_>_.whatsapp-menu-trigger]:mt-[0]",
    "tw:[&_>_.whatsapp-menu-trigger]:mr-[0]", "tw:[&_>_.whatsapp-menu-trigger]:mb-[0]", "tw:[&_>_.whatsapp-menu-trigger]:ml-[0]", "tw:[&_>_.whatsapp-menu-trigger]:opacity-[1]",
  ].join(" "),
  "whatsapp_pin": [
    "whatsapp-pin", "tw:[display:inline]", "tw:ml-[4px]", "tw:text-[color:#1a8a64]",
    "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:text-[.7rem]",
  ].join(" "),
  "whatsapp_menu_trigger": [
    "whatsapp-menu-trigger", "tw:grid", "tw:w-[25px]", "tw:h-[27px]",
    "tw:place-items-center", "tw:pt-[0]", "tw:pr-[0]", "tw:pb-[0]",
    "tw:pl-[0]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#c9dce8]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#c9dce8]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#c9dce8]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#c9dce8]", "tw:rounded-[7px]", "tw:text-[color:#234f71]", "tw:bg-[color:#f0f6fa]",
    "tw:[background-image:none]", "tw:[font:inherit]", "tw:cursor-pointer", "tw:[align-self:start]",
    "tw:mt-[8px]", "tw:mr-[7px]", "tw:mb-[0]", "tw:ml-[-31px]",
    "tw:z-[1]", "tw:opacity-[1]", "tw:focus:opacity-[1]", "tw:focus:text-[color:#fff]",
    "tw:focus:bg-[color:#2168a8]", "tw:focus:[background-image:none]", "tw:focus:border-t-[color:#2168a8]", "tw:focus:border-r-[color:#2168a8]",
    "tw:focus:border-b-[color:#2168a8]", "tw:focus:border-l-[color:#2168a8]", "tw:hover:text-[color:#fff]", "tw:hover:bg-[color:#2168a8]",
    "tw:hover:[background-image:none]", "tw:hover:border-t-[color:#2168a8]", "tw:hover:border-r-[color:#2168a8]", "tw:hover:border-b-[color:#2168a8]",
    "tw:hover:border-l-[color:#2168a8]",
  ].join(" "),
  "whatsapp_conversation_menu": [
    "whatsapp-conversation-menu", "tw:absolute", "tw:top-[38px]", "tw:right-[8px]",
    "tw:z-[6]", "tw:grid", "tw:w-[208px]", "tw:pt-[5px]",
    "tw:pr-[5px]", "tw:pb-[5px]", "tw:pl-[5px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#dbe5ec]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#dbe5ec]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dbe5ec]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#dbe5ec]", "tw:rounded-[8px]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[box-shadow:0_10px_24px_rgb(33_61_81_/_.2)]", "tw:[&_button]:pt-[8px]",
    "tw:[&_button]:pr-[9px]", "tw:[&_button]:pb-[8px]", "tw:[&_button]:pl-[9px]", "tw:[&_button]:border-t-[length:0]",
    "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]", "tw:[&_button]:border-r-[length:0]", "tw:[&_button]:[border-right-style:none]",
    "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:0]", "tw:[&_button]:[border-bottom-style:none]", "tw:[&_button]:border-b-[color:currentColor]",
    "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]", "tw:[&_button]:border-l-[color:currentColor]", "tw:[&_button]:rounded-[5px]",
    "tw:[&_button]:text-[color:#334e64]", "tw:[&_button]:bg-[color:transparent]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:[font:inherit]",
    "tw:[&_button]:text-[.72rem]", "tw:[&_button]:text-left", "tw:[&_button]:cursor-pointer", "tw:[&_button]:flex",
    "tw:[&_button]:items-center", "tw:[&_button]:gap-y-[8px]", "tw:[&_button]:gap-x-[8px]", "tw:[&_button:hover]:bg-[color:#f2f7f9]",
    "tw:[&_button:hover]:[background-image:none]", "tw:[&_.is-danger]:text-[color:#c52b28]", "tw:[&_hr]:w-[100%]", "tw:[&_hr]:mt-[4px]",
    "tw:[&_hr]:mr-[0]", "tw:[&_hr]:mb-[4px]", "tw:[&_hr]:ml-[0]", "tw:[&_hr]:border-t-[length:1px]",
    "tw:[&_hr]:[border-top-style:solid]", "tw:[&_hr]:border-t-[color:#edf1f4]", "tw:[&_hr]:border-r-[length:0]", "tw:[&_hr]:[border-right-style:none]",
    "tw:[&_hr]:border-r-[color:currentColor]", "tw:[&_hr]:border-b-[length:0]", "tw:[&_hr]:[border-bottom-style:none]", "tw:[&_hr]:border-b-[color:currentColor]",
    "tw:[&_hr]:border-l-[length:0]", "tw:[&_hr]:[border-left-style:none]", "tw:[&_hr]:border-l-[color:currentColor]",
  ].join(" "),
  "whatsapp_chat_main": [
    "whatsapp-chat-main", "tw:border-r-[length:1px]", "tw:viewport-720:border-r-[length:0]", "tw:[border-right-style:solid]",
    "tw:viewport-720:[border-right-style:none]", "tw:border-r-[color:#e2eaf2]", "tw:viewport-720:border-r-[color:currentColor]", "tw:viewport-720:min-h-[440px]",
    "tw:[@media(min-width:721px)]:min-h-[0]",
  ].join(" "),
  "whatsapp_message_thread": [
    "whatsapp-message-thread", "tw:[&_article]:relative", "tw:[&_article]:[overflow-wrap:anywhere]", "tw:[&_article]:[align-self:flex-start]",
    "tw:[&_article]:max-w-[min(78%,_560px)]", "tw:viewport-720:[&_article]:max-w-[88%]", "tw:[&_article]:pt-[9px]", "tw:[&_article]:pr-[11px]",
    "tw:[&_article]:pb-[9px]", "tw:[&_article]:pl-[11px]", "tw:[&_article]:rounded-[10px_10px_10px_3px]", "tw:[&_article]:text-[color:#24425e]",
    "tw:[&_article]:bg-[color:#fff]", "tw:[&_article]:[background-image:none]", "tw:[&_article]:[box-shadow:0_2px_6px_rgb(23_58_101_/_.07)]", "tw:[&_article:focus]:[outline:none]",
    "tw:[&_article:focus-visible]:[outline:2px_solid_#7db8a1]", "tw:[&_article:focus-visible]:[outline-offset:2px]", "tw:[&_article_>_p]:pr-[18px]", "tw:[&_article.has-actions]:min-w-[min(280px,_78%)]",
    "tw:[&_.whatsapp-message-meta_time]:mt-[0]", "tw:[&_.whatsapp-message-meta_time]:[flex-shrink:0]", "tw:flex", "tw:flex-col",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:[overflow-y:auto]", "tw:pt-[18px]",
    "tw:pr-[18px]", "tw:pb-[18px]", "tw:pl-[18px]", "tw:bg-[color:#f6fafc]",
    "tw:[background-image:none]", "tw:[&_article.outbound]:[align-self:flex-end]", "tw:[&_article.outbound]:rounded-[10px_10px_3px_10px]", "tw:[&_article.outbound]:text-[color:#0c583d]",
    "tw:[&_article.outbound]:bg-[color:#daf5e7]", "tw:[&_article.outbound]:[background-image:none]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:whitespace-pre-wrap", "tw:[&_time]:block",
    "tw:[&_time]:mt-[4px]", "tw:[&_time]:text-[color:#758ba0]", "tw:[&_time]:text-[.62rem]", "tw:[&_time]:text-right",
    "tw:[&_article:has(.whatsapp-message-audio)]:min-w-[min(300px,_80%)]",
  ].join(" "),
  "whatsapp_composer": [
    "whatsapp-composer", "tw:[&_.whatsapp-composer-icon]:grid!", "tw:[&_.whatsapp-composer-icon]:w-[40px]!", "tw:viewport-600:[&_.whatsapp-composer-icon]:w-[34px]!",
    "tw:[&_.whatsapp-composer-icon]:h-[40px]!", "tw:viewport-600:[&_.whatsapp-composer-icon]:h-[34px]!", "tw:[&_.whatsapp-composer-icon]:place-items-center", "tw:[&_.whatsapp-composer-icon]:pt-[0]",
    "tw:[&_.whatsapp-composer-icon]:pr-[0]", "tw:[&_.whatsapp-composer-icon]:pb-[0]", "tw:[&_.whatsapp-composer-icon]:pl-[0]", "tw:[&_.whatsapp-composer-icon]:border-t-[length:0]!",
    "tw:[&_.whatsapp-composer-icon]:[border-top-style:none]!", "tw:[&_.whatsapp-composer-icon]:border-t-[color:currentColor]!", "tw:[&_.whatsapp-composer-icon]:border-r-[length:0]!", "tw:[&_.whatsapp-composer-icon]:[border-right-style:none]!",
    "tw:[&_.whatsapp-composer-icon]:border-r-[color:currentColor]!", "tw:[&_.whatsapp-composer-icon]:border-b-[length:0]!", "tw:[&_.whatsapp-composer-icon]:[border-bottom-style:none]!", "tw:[&_.whatsapp-composer-icon]:border-b-[color:currentColor]!",
    "tw:[&_.whatsapp-composer-icon]:border-l-[length:0]!", "tw:[&_.whatsapp-composer-icon]:[border-left-style:none]!", "tw:[&_.whatsapp-composer-icon]:border-l-[color:currentColor]!", "tw:[&_.whatsapp-composer-icon]:rounded-[10px]!",
    "tw:[&_.whatsapp-composer-icon]:text-[color:#526b78]!", "tw:[&_.whatsapp-composer-icon]:bg-[color:transparent]!", "tw:[&_.whatsapp-composer-icon]:[background-image:none]!", "tw:[&_.whatsapp-record-button]:grid!",
    "tw:[&_.whatsapp-record-button]:w-[40px]!", "tw:viewport-600:[&_.whatsapp-record-button]:w-[34px]!", "tw:[&_.whatsapp-record-button]:h-[40px]!", "tw:viewport-600:[&_.whatsapp-record-button]:h-[34px]!",
    "tw:[&_.whatsapp-record-button]:place-items-center", "tw:[&_.whatsapp-record-button]:pt-[0]", "tw:[&_.whatsapp-record-button]:pr-[0]", "tw:[&_.whatsapp-record-button]:pb-[0]",
    "tw:[&_.whatsapp-record-button]:pl-[0]", "tw:[&_.whatsapp-record-button]:border-t-[length:0]!", "tw:[&_.whatsapp-record-button]:[border-top-style:none]!", "tw:[&_.whatsapp-record-button]:border-t-[color:currentColor]!",
    "tw:[&_.whatsapp-record-button]:border-r-[length:0]!", "tw:[&_.whatsapp-record-button]:[border-right-style:none]!", "tw:[&_.whatsapp-record-button]:border-r-[color:currentColor]!", "tw:[&_.whatsapp-record-button]:border-b-[length:0]!",
    "tw:[&_.whatsapp-record-button]:[border-bottom-style:none]!", "tw:[&_.whatsapp-record-button]:border-b-[color:currentColor]!", "tw:[&_.whatsapp-record-button]:border-l-[length:0]!", "tw:[&_.whatsapp-record-button]:[border-left-style:none]!",
    "tw:[&_.whatsapp-record-button]:border-l-[color:currentColor]!", "tw:[&_.whatsapp-record-button]:rounded-[10px]!", "tw:[&_.whatsapp-record-button]:text-[color:#526b78]!", "tw:[&_.whatsapp-record-button]:bg-[color:transparent]!",
    "tw:[&_.whatsapp-record-button]:[background-image:none]!", "tw:[&_.whatsapp-composer-icon:hover]:text-[color:#087e5b]!", "tw:[&_.whatsapp-composer-icon:hover]:bg-[color:#e5f4ed]!", "tw:[&_.whatsapp-composer-icon:hover]:[background-image:none]!",
    "tw:[&_.whatsapp-composer-icon:hover]:[outline:0]", "tw:[&_.whatsapp-composer-icon:focus-visible]:text-[color:#087e5b]!", "tw:[&_.whatsapp-composer-icon:focus-visible]:bg-[color:#e5f4ed]!", "tw:[&_.whatsapp-composer-icon:focus-visible]:[background-image:none]!",
    "tw:[&_.whatsapp-composer-icon:focus-visible]:[outline:0]", "tw:[&_.whatsapp-record-button:hover]:text-[color:#087e5b]!", "tw:[&_.whatsapp-record-button:hover]:bg-[color:#e5f4ed]!", "tw:[&_.whatsapp-record-button:hover]:[background-image:none]!",
    "tw:[&_.whatsapp-record-button:hover]:[outline:0]", "tw:[&_.whatsapp-record-button:focus-visible]:text-[color:#087e5b]!", "tw:[&_.whatsapp-record-button:focus-visible]:bg-[color:#e5f4ed]!", "tw:[&_.whatsapp-record-button:focus-visible]:[background-image:none]!",
    "tw:[&_.whatsapp-record-button:focus-visible]:[outline:0]", "tw:[&_.whatsapp-record-button.is-recording]:text-[color:#b93333]!", "tw:[&_.whatsapp-record-button.is-recording]:bg-[color:#fce8e8]!", "tw:[&_.whatsapp-record-button.is-recording]:[background-image:none]!",
    "tw:[&_.whatsapp-composer-field]:flex", "tw:[&_.whatsapp-composer-field]:w-[100%]", "tw:[&_.whatsapp-composer-field]:min-w-[0]", "tw:[&_.whatsapp-composer-field]:min-h-[48px]",
    "tw:viewport-600:[&_.whatsapp-composer-field]:min-h-[44px]", "tw:[&_.whatsapp-composer-field]:items-center", "tw:[&_.whatsapp-composer-field]:pt-[4px]", "tw:[&_.whatsapp-composer-field]:pr-[14px]",
    "tw:[&_.whatsapp-composer-field]:pb-[4px]", "tw:[&_.whatsapp-composer-field]:pl-[14px]", "tw:[&_.whatsapp-composer-field]:border-t-[length:1px]", "tw:[&_.whatsapp-composer-field]:[border-top-style:solid]",
    "tw:[&_.whatsapp-composer-field]:border-t-[color:#d0dde1]", "tw:[&_.whatsapp-composer-field]:border-r-[length:1px]", "tw:[&_.whatsapp-composer-field]:[border-right-style:solid]", "tw:[&_.whatsapp-composer-field]:border-r-[color:#d0dde1]",
    "tw:[&_.whatsapp-composer-field]:border-b-[length:1px]", "tw:[&_.whatsapp-composer-field]:[border-bottom-style:solid]", "tw:[&_.whatsapp-composer-field]:border-b-[color:#d0dde1]", "tw:[&_.whatsapp-composer-field]:border-l-[length:1px]",
    "tw:[&_.whatsapp-composer-field]:[border-left-style:solid]", "tw:[&_.whatsapp-composer-field]:border-l-[color:#d0dde1]", "tw:[&_.whatsapp-composer-field]:rounded-[14px]", "tw:[&_.whatsapp-composer-field]:bg-[color:#fff]",
    "tw:[&_.whatsapp-composer-field]:[background-image:none]", "tw:[&_.whatsapp-composer-field]:[box-shadow:0_1px_3px_rgb(23_55_63_/_.05)]", "tw:[&_.whatsapp-composer-field:focus-within]:border-t-[color:#2b9878]", "tw:[&_.whatsapp-composer-field:focus-within]:border-r-[color:#2b9878]",
    "tw:[&_.whatsapp-composer-field:focus-within]:border-b-[color:#2b9878]", "tw:[&_.whatsapp-composer-field:focus-within]:border-l-[color:#2b9878]", "tw:[&_.whatsapp-composer-field:focus-within]:[box-shadow:0_0_0_3px_rgb(43_152_120_/_.13)]", "tw:[&_.whatsapp-composer-field_textarea]:block",
    "tw:[&_.whatsapp-composer-field_textarea]:w-[100%]", "tw:[&_.whatsapp-composer-field_textarea]:min-w-[0]", "tw:[&_.whatsapp-composer-field_textarea]:min-h-[32px]", "tw:[&_.whatsapp-composer-field_textarea]:max-h-[104px]",
    "tw:[&_.whatsapp-composer-field_textarea]:pt-[6px]", "tw:[&_.whatsapp-composer-field_textarea]:pr-[0]", "tw:[&_.whatsapp-composer-field_textarea]:pb-[6px]", "tw:[&_.whatsapp-composer-field_textarea]:pl-[0]",
    "tw:[&_.whatsapp-composer-field_textarea]:border-t-[length:0]", "tw:[&_.whatsapp-composer-field_textarea]:[border-top-style:none]", "tw:[&_.whatsapp-composer-field_textarea]:border-t-[color:currentColor]", "tw:[&_.whatsapp-composer-field_textarea]:border-r-[length:0]",
    "tw:[&_.whatsapp-composer-field_textarea]:[border-right-style:none]", "tw:[&_.whatsapp-composer-field_textarea]:border-r-[color:currentColor]", "tw:[&_.whatsapp-composer-field_textarea]:border-b-[length:0]", "tw:[&_.whatsapp-composer-field_textarea]:[border-bottom-style:none]",
    "tw:[&_.whatsapp-composer-field_textarea]:border-b-[color:currentColor]", "tw:[&_.whatsapp-composer-field_textarea]:border-l-[length:0]", "tw:[&_.whatsapp-composer-field_textarea]:[border-left-style:none]", "tw:[&_.whatsapp-composer-field_textarea]:border-l-[color:currentColor]",
    "tw:[&_.whatsapp-composer-field_textarea]:[outline:0]", "tw:[&_.whatsapp-composer-field_textarea]:text-[color:#223b47]", "tw:[&_.whatsapp-composer-field_textarea]:bg-[color:transparent]", "tw:[&_.whatsapp-composer-field_textarea]:[background-image:none]",
    "tw:[&_.whatsapp-composer-field_textarea]:text-[.88rem]", "tw:[&_.whatsapp-composer-field_textarea]:leading-[1.4]", "tw:[&_.whatsapp-composer-field_textarea]:[resize:vertical]", "tw:[&_.whatsapp-composer-field_textarea::placeholder]:text-[color:#82949b]",
    "tw:[&_.whatsapp-recording-indicator]:min-w-[0]", "tw:[&_.whatsapp-pending-audio]:min-w-[0]", "tw:[&_.whatsapp-recording-indicator_>_i]:w-[8px]", "tw:[&_.whatsapp-recording-indicator_>_i]:h-[8px]",
    "tw:[&_.whatsapp-recording-indicator_>_i]:[flex:0_0_8px]", "tw:[&_.whatsapp-recording-indicator_>_i]:rounded-[50%]", "tw:[&_.whatsapp-recording-indicator_>_i]:bg-[color:#d7433c]", "tw:[&_.whatsapp-recording-indicator_>_i]:[background-image:none]",
    "tw:[&_.whatsapp-recording-indicator_>_i]:[animation:whatsapp-recording-pulse_1s_ease-in-out_infinite]", "tw:[&_.whatsapp-send-button]:w-[40px]", "tw:viewport-600:[&_.whatsapp-send-button]:w-[34px]!", "tw:[&_.whatsapp-send-button]:h-[40px]",
    "tw:viewport-600:[&_.whatsapp-send-button]:h-[34px]!", "tw:[&_.whatsapp-send-button]:rounded-[12px]", "tw:[&_.whatsapp-send-button]:bg-[color:#148c69]", "tw:[&_.whatsapp-send-button]:[background-image:none]",
    "tw:[&_.whatsapp-send-button]:[box-shadow:0_2px_6px_rgb(16_109_81_/_.18)]", "tw:[&_.whatsapp-send-button:hover:not(:disabled)]:bg-[color:#087a59]", "tw:[&_.whatsapp-send-button:hover:not(:disabled)]:[background-image:none]", "tw:[&_.whatsapp-send-button:disabled]:opacity-[.48]",
    "tw:[&_.whatsapp-send-button:disabled]:cursor-not-allowed", "tw:viewport-600:[&_.whatsapp-composer-field]:[padding-inline:9px]", "tw:viewport-600:[&_.whatsapp-recording-indicator_small]:hidden", "tw:viewport-420:[&_.whatsapp-recording-wave_b:nth-child(n_+_11)]:hidden",
  ].join(" "),
  "whatsapp_reply_preview": [
    "whatsapp-reply-preview", "tw:[grid-column:1_/_-1]", "tw:flex", "tw:items-center",
    "tw:justify-between", "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:min-w-[0]",
    "tw:pt-[8px]", "tw:pr-[11px]", "tw:pb-[8px]", "tw:pl-[11px]",
    "tw:border-l-[length:3px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#2c9b70]", "tw:rounded-[5px]",
    "tw:bg-[color:#e4ede7]", "tw:[background-image:none]", "tw:[&_>_div]:grid", "tw:[&_>_div]:gap-y-[3px]",
    "tw:[&_>_div]:gap-x-[3px]", "tw:[&_>_div]:min-w-[0]", "tw:[&_strong]:text-[color:#207956]", "tw:[&_strong]:text-[.73rem]",
    "tw:[&_span]:[overflow-x:hidden]", "tw:[&_span]:[overflow-y:hidden]", "tw:[&_span]:text-[color:#52665e]", "tw:[&_span]:text-[.74rem]",
    "tw:[&_span]:text-ellipsis", "tw:[&_span]:whitespace-nowrap", "tw:[&_button]:[flex-shrink:0]", "tw:[&_button]:min-h-[28px]",
    "tw:[&_button]:pt-[0]", "tw:[&_button]:pr-[6px]", "tw:[&_button]:pb-[0]", "tw:[&_button]:pl-[6px]",
    "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]", "tw:[&_button]:border-r-[length:0]",
    "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:0]", "tw:[&_button]:[border-bottom-style:none]",
    "tw:[&_button]:border-b-[color:currentColor]", "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]", "tw:[&_button]:border-l-[color:currentColor]",
    "tw:[&_button]:text-[color:#577365]", "tw:[&_button]:bg-[color:transparent]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[1.2rem]",
    "tw:[&_button]:cursor-pointer",
  ].join(" "),
  "whatsapp_composer_icon": [
    "whatsapp-composer-icon", "tw:grid", "tw:w-[30px]", "tw:h-[30px]",
    "tw:place-items-center", "tw:pt-[0]", "tw:pr-[0]", "tw:pb-[0]",
    "tw:pl-[0]", "tw:border-t-[length:0]", "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]",
    "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]",
    "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]", "tw:[border-left-style:none]",
    "tw:border-l-[color:currentColor]", "tw:rounded-[7px]", "tw:text-[color:#647889]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:[font:inherit]", "tw:cursor-pointer",
  ].join(" "),
  "whatsapp_composer_icon_whatsapp_record_button": [
    "whatsapp-composer-icon", "whatsapp-record-button", "tw:grid!", "tw:w-[30px]!",
    "tw:h-[30px]!", "tw:place-items-center", "tw:pt-[0]", "tw:pr-[0]",
    "tw:pb-[0]", "tw:pl-[0]", "tw:border-t-[length:0]!", "tw:[border-top-style:none]!",
    "tw:border-t-[color:currentColor]!", "tw:border-r-[length:0]!", "tw:[border-right-style:none]!", "tw:border-r-[color:currentColor]!",
    "tw:border-b-[length:0]!", "tw:[border-bottom-style:none]!", "tw:border-b-[color:currentColor]!", "tw:border-l-[length:0]!",
    "tw:[border-left-style:none]!", "tw:border-l-[color:currentColor]!", "tw:rounded-[7px]", "tw:text-[color:#607889]!",
    "tw:bg-[color:transparent]!", "tw:[background-image:none]!", "tw:[font:inherit]", "tw:cursor-pointer",
    "tw:text-[1rem]!", "tw:[&_svg]:w-[19px]", "tw:[&_svg]:h-[19px]", "tw:[&_svg]:[fill:none]",
    "tw:[&_svg]:[stroke:currentColor]", "tw:[&_svg]:[stroke-width:2]", "tw:[&_svg]:[stroke-linecap:round]", "tw:[&_svg]:[stroke-linejoin:round]",
    "tw:hover:text-[color:#087e5b]!", "tw:hover:bg-[color:#e7f7f0]!", "tw:hover:[background-image:none]!", "tw:hover:rounded-[7px]!",
    "tw:focus-visible:text-[color:#087e5b]!", "tw:focus-visible:bg-[color:#e7f7f0]!", "tw:focus-visible:[background-image:none]!", "tw:focus-visible:rounded-[7px]!",
  ].join(" "),
  "whatsapp_composer_field": [
    "whatsapp-composer-field", "tw:grid", "tw:min-w-[0]", "tw:gap-y-[1px]",
    "tw:gap-x-[1px]", "tw:pt-[8px]", "tw:pr-[10px]", "tw:pb-[8px]",
    "tw:pl-[10px]", "tw:border-t-[length:0]", "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]",
    "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]",
    "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]", "tw:[border-left-style:none]",
    "tw:border-l-[color:currentColor]", "tw:rounded-[0]", "tw:bg-[color:transparent]", "tw:[background-image:none]",
    "tw:w-[100%]", "tw:min-h-[62px]", "tw:viewport-720:min-h-[54px]", "tw:[align-content:start]",
    "tw:[box-shadow:none]", "tw:[&_span]:text-[color:#8493a0]", "tw:[&_span]:text-[.55rem]", "tw:[&_span]:font-[850]",
    "tw:[&_span]:tracking-[.06em]", "tw:[&:has(.whatsapp-recording-indicator)_textarea]:hidden", "tw:[&:has(.whatsapp-pending-audio)_textarea]:hidden", "tw:[&:focus-within]:[outline:0]",
    "tw:[&:focus-within]:[box-shadow:none]",
  ].join(" "),
  "whatsapp_recording_indicator": [
    "whatsapp-recording-indicator", "tw:flex", "tw:w-[100%]", "tw:items-center",
    "tw:gap-y-[7px]", "tw:gap-x-[7px]", "tw:min-h-[30px]", "tw:text-[color:#a72e28]",
    "tw:[&_>_span]:w-[8px]", "tw:[&_>_span]:h-[8px]", "tw:[&_>_span]:[flex:0_0_8px]", "tw:[&_>_span]:rounded-[50%]",
    "tw:[&_>_span]:bg-[color:#d7433c]", "tw:[&_>_span]:[background-image:none]", "tw:[&_>_span]:[animation:whatsapp-recording-pulse_1s_ease-in-out_infinite]", "tw:[&_strong]:text-[.72rem]",
    "tw:[&_small]:text-[color:#8a635f]", "tw:[&_small]:text-[.65rem]",
  ].join(" "),
  "whatsapp_recording_wave": [
    "whatsapp-recording-wave", "tw:flex", "tw:h-[25px]", "tw:items-center",
    "tw:gap-y-[2px]", "tw:gap-x-[2px]", "tw:[&_i]:block", "tw:[&_i]:w-[3px]",
    "tw:[&_i]:h-[15px]", "tw:[&_i]:rounded-[99px]", "tw:[&_i]:bg-[color:#d7433c]", "tw:[&_i]:[background-image:none]",
    "tw:[&_i]:[transform:scaleY(.22)]", "tw:[&_i]:[transform-origin:center]", "tw:[&_i]:[transition:transform_55ms_linear]", "tw:[&_b]:block",
    "tw:[&_b]:w-[3px]", "tw:[&_b]:h-[15px]", "tw:[&_b]:rounded-[99px]", "tw:[&_b]:bg-[color:#d7433c]",
    "tw:[&_b]:[background-image:none]", "tw:[&_b]:[transform-origin:center]", "tw:[&_b]:[transition:transform_55ms_linear]",
  ].join(" "),
  "whatsapp_pending_audio": [
    "whatsapp-pending-audio", "tw:flex", "tw:w-[100%]", "tw:items-center",
    "tw:gap-y-[7px]", "tw:gap-x-[7px]", "tw:min-h-[30px]", "tw:text-[color:#235b43]",
    "tw:[&_audio]:w-[min(310px,_calc(100%_-_32px))]", "tw:[&_audio]:h-[30px]", "tw:[&_button]:grid", "tw:[&_button]:w-[24px]",
    "tw:[&_button]:h-[24px]", "tw:[&_button]:[flex:0_0_24px]", "tw:[&_button]:place-items-center", "tw:[&_button]:border-t-[length:0]",
    "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]", "tw:[&_button]:border-r-[length:0]", "tw:[&_button]:[border-right-style:none]",
    "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:0]", "tw:[&_button]:[border-bottom-style:none]", "tw:[&_button]:border-b-[color:currentColor]",
    "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]", "tw:[&_button]:border-l-[color:currentColor]", "tw:[&_button]:rounded-[50%]",
    "tw:[&_button]:text-[color:#a72e28]", "tw:[&_button]:bg-[color:#ffe8e6]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[1rem]",
    "tw:[&_button]:cursor-pointer",
  ].join(" "),
  "whatsapp_send_button": [
    "whatsapp-send-button", "tw:grid", "tw:w-[31px]", "tw:h-[31px]",
    "tw:place-items-center", "tw:pt-[0]", "tw:pr-[0]", "tw:pb-[0]",
    "tw:pl-[0]", "tw:border-t-[length:0]", "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]",
    "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]",
    "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]", "tw:[border-left-style:none]",
    "tw:border-l-[color:currentColor]", "tw:rounded-[50%]", "tw:text-[color:#fff]", "tw:bg-[color:#76c5ad]",
    "tw:[background-image:none]", "tw:text-[.9rem]", "tw:cursor-pointer", "tw:disabled:opacity-[.65]",
    "tw:disabled:cursor-wait",
  ].join(" "),
  "whatsapp_emoji_picker": [
    "whatsapp-emoji-picker", "tw:absolute", "tw:right-[42px]", "tw:bottom-[0]",
    "tw:grid", "tw:grid-cols-[repeat(6,_34px)]", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:pt-[12px]", "tw:pr-[12px]", "tw:pb-[12px]", "tw:pl-[12px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d8e4ec]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#d8e4ec]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#d8e4ec]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d8e4ec]",
    "tw:rounded-[9px]", "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[box-shadow:0_8px_22px_rgb(29_61_84_/_.2)]",
    "tw:[&_button]:grid", "tw:[&_button]:w-[34px]", "tw:[&_button]:h-[34px]", "tw:[&_button]:place-items-center",
    "tw:[&_button]:pt-[0]", "tw:[&_button]:pr-[0]", "tw:[&_button]:pb-[0]", "tw:[&_button]:pl-[0]",
    "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]", "tw:[&_button]:border-r-[length:0]",
    "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:0]", "tw:[&_button]:[border-bottom-style:none]",
    "tw:[&_button]:border-b-[color:currentColor]", "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]", "tw:[&_button]:border-l-[color:currentColor]",
    "tw:[&_button]:rounded-[6px]", "tw:[&_button]:bg-[color:transparent]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[1.25rem]",
    "tw:[&_button]:cursor-pointer", "tw:[&_button:hover]:bg-[color:#eef6f4]", "tw:[&_button:hover]:[background-image:none]",
  ].join(" "),
  "whatsapp_contact_panel": [
    "whatsapp-contact-panel", "tw:grid", "tw:viewport-1100:hidden", "tw:[align-content:start]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[&_>_header]:grid", "tw:[&_>_header]:[justify-items:center]",
    "tw:[&_>_header]:min-h-[175px]", "tw:[&_>_header]:gap-y-[7px]", "tw:[&_>_header]:gap-x-[7px]", "tw:[&_>_header]:pt-[24px]",
    "tw:[&_>_header]:pr-[14px]", "tw:[&_>_header]:pb-[18px]", "tw:[&_>_header]:pl-[14px]", "tw:[&_>_header]:text-center",
    "tw:[&_>_header_.whatsapp-contact-avatar]:w-[58px]", "tw:[&_>_header_.whatsapp-contact-avatar]:h-[58px]", "tw:[&_>_header_.whatsapp-contact-avatar]:text-[.9rem]", "tw:[&_>_header_strong]:text-[color:#183954]",
    "tw:[&_>_header_strong]:text-[.9rem]", "tw:[&_>_header_span]:text-[color:#7b8d9e]", "tw:[&_>_header_span]:text-[.68rem]", "tw:[&_dl]:grid",
    "tw:[&_dl]:gap-y-[0]", "tw:[&_dl]:gap-x-[0]", "tw:[&_dl]:mt-[0]", "tw:[&_dl]:mr-[0]",
    "tw:[&_dl]:mb-[0]", "tw:[&_dl]:ml-[0]", "tw:[&_dl]:border-t-[length:1px]", "tw:[&_dl]:[border-top-style:solid]",
    "tw:[&_dl]:border-t-[color:#e9eff3]", "tw:[&_dl_>_div]:grid", "tw:[&_dl_>_div]:gap-y-[4px]", "tw:[&_dl_>_div]:gap-x-[4px]",
    "tw:[&_dl_>_div]:pt-[13px]", "tw:[&_dl_>_div]:pr-[16px]", "tw:[&_dl_>_div]:pb-[13px]", "tw:[&_dl_>_div]:pl-[16px]",
    "tw:[&_dl_>_div]:border-b-[length:1px]", "tw:[&_dl_>_div]:[border-bottom-style:solid]", "tw:[&_dl_>_div]:border-b-[color:#edf1f4]", "tw:[&_dt]:text-[color:#71859a]",
    "tw:[&_dt]:text-[.61rem]", "tw:[&_dt]:font-[850]", "tw:[&_dt]:tracking-[.06em]", "tw:[&_dt]:uppercase",
    "tw:[&_dd]:mt-[0]", "tw:[&_dd]:mr-[0]", "tw:[&_dd]:mb-[0]", "tw:[&_dd]:ml-[0]",
    "tw:[&_dd]:[overflow-wrap:anywhere]", "tw:[&_dd]:text-[color:#264965]", "tw:[&_dd]:text-[.75rem]", "tw:[&_dd]:font-[700]",
    "tw:[@media(min-width:721px)]:min-h-[0]", "tw:[@media(min-width:721px)]:[overflow-y:auto]",
  ].join(" "),
  "whatsapp_link_client": [
    "whatsapp-link-client", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:pt-[15px]", "tw:pr-[15px]", "tw:pb-[15px]", "tw:pl-[15px]",
    "tw:[&_strong]:text-[color:#1b405f]", "tw:[&_strong]:text-[.78rem]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#72869a]", "tw:[&_p]:text-[.7rem]",
    "tw:[&_select]:min-w-[0]", "tw:[&_select]:min-h-[34px]", "tw:[&_select]:pt-[5px]", "tw:[&_select]:pr-[7px]",
    "tw:[&_select]:pb-[5px]", "tw:[&_select]:pl-[7px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]",
    "tw:[&_select]:border-t-[color:#d4e0e9]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#d4e0e9]",
    "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:#d4e0e9]", "tw:[&_select]:border-l-[length:1px]",
    "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#d4e0e9]", "tw:[&_select]:rounded-[6px]", "tw:[&_select]:text-[color:#344f66]",
    "tw:[&_select]:bg-[color:#fff]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[.7rem]", "tw:[&_input]:min-h-[34px]",
    "tw:[&_input]:pt-[5px]", "tw:[&_input]:pr-[8px]", "tw:[&_input]:pb-[5px]", "tw:[&_input]:pl-[8px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#d4e0e9]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#d4e0e9]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:#d4e0e9]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#d4e0e9]",
    "tw:[&_input]:rounded-[6px]", "tw:[&_input]:[font:inherit]", "tw:[&_input]:text-[.72rem]",
  ].join(" "),
  "button_button_primary_button_small": sharedUtilities.buttonButtonPrimaryButtonSmall,
  "whatsapp_client_options": [
    "whatsapp-client-options", "tw:grid", "tw:max-h-[168px]", "tw:[overflow-x:auto]",
    "tw:[overflow-y:auto]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#e3ebf0]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#e3ebf0]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e3ebf0]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#e3ebf0]", "tw:rounded-[6px]", "tw:[&_button]:grid", "tw:[&_button]:gap-y-[2px]",
    "tw:[&_button]:gap-x-[2px]", "tw:[&_button]:pt-[7px]", "tw:[&_button]:pr-[8px]", "tw:[&_button]:pb-[7px]",
    "tw:[&_button]:pl-[8px]", "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]",
    "tw:[&_button]:border-r-[length:0]", "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:1px]",
    "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:#edf2f5]", "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]",
    "tw:[&_button]:border-l-[color:currentColor]", "tw:[&_button]:text-[color:#284b67]", "tw:[&_button]:bg-[color:#fff]", "tw:[&_button]:[background-image:none]",
    "tw:[&_button]:[font:inherit]", "tw:[&_button]:text-[.7rem]", "tw:[&_button]:font-[700]", "tw:[&_button]:text-left",
    "tw:[&_button]:cursor-pointer", "tw:[&_button:hover]:bg-[color:#eff8f4]", "tw:[&_button:hover]:[background-image:none]", "tw:[&_small]:text-[color:#74899b]",
    "tw:[&_small]:text-[.63rem]", "tw:[&_small]:font-[500]",
  ].join(" "),
  "whatsapp_create_client": [
    "whatsapp-create-client", "tw:[justify-self:start]", "tw:mt-[3px]", "tw:pt-[6px]",
    "tw:pr-[0]", "tw:pb-[6px]", "tw:pl-[0]", "tw:border-t-[length:0]",
    "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]",
    "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:text-[color:#166a4b]",
    "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:text-[.72rem]", "tw:font-[800]",
    "tw:cursor-pointer",
  ].join(" "),
  "whatsapp_contact_modal": [
    "whatsapp-contact-modal", "tw:absolute", "tw:top-[0]", "tw:right-[0]",
    "tw:bottom-[0]", "tw:left-[0]", "tw:z-[8]", "tw:grid",
    "tw:place-items-center", "tw:pt-[20px]", "tw:pr-[20px]", "tw:pb-[20px]",
    "tw:pl-[20px]", "tw:bg-[color:rgb(21_44_62_/_.2)]", "tw:[background-image:none]", "tw:[&_form]:grid",
    "tw:[&_form]:gap-y-[12px]", "tw:[&_form]:gap-x-[12px]", "tw:[&_form]:w-[min(100%,_360px)]", "tw:[&_form]:pt-[16px]",
    "tw:[&_form]:pr-[16px]", "tw:[&_form]:pb-[16px]", "tw:[&_form]:pl-[16px]", "tw:[&_form]:rounded-[10px]",
    "tw:[&_form]:bg-[color:#fff]", "tw:[&_form]:[background-image:none]", "tw:[&_form]:[box-shadow:0_15px_40px_rgb(17_44_62_/_.24)]", "tw:[&_header]:flex",
    "tw:[&_header]:items-center", "tw:[&_header]:justify-between", "tw:[&_header]:text-[color:#1d3d59]", "tw:[&_header]:text-[.92rem]",
    "tw:[&_header_button]:border-t-[length:0]", "tw:[&_header_button]:[border-top-style:none]", "tw:[&_header_button]:border-t-[color:currentColor]", "tw:[&_header_button]:border-r-[length:0]",
    "tw:[&_header_button]:[border-right-style:none]", "tw:[&_header_button]:border-r-[color:currentColor]", "tw:[&_header_button]:border-b-[length:0]", "tw:[&_header_button]:[border-bottom-style:none]",
    "tw:[&_header_button]:border-b-[color:currentColor]", "tw:[&_header_button]:border-l-[length:0]", "tw:[&_header_button]:[border-left-style:none]", "tw:[&_header_button]:border-l-[color:currentColor]",
    "tw:[&_header_button]:text-[color:#71859a]", "tw:[&_header_button]:bg-[color:transparent]", "tw:[&_header_button]:[background-image:none]", "tw:[&_header_button]:text-[1.3rem]",
    "tw:[&_header_button]:cursor-pointer", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[5px]", "tw:[&_label]:gap-x-[5px]",
    "tw:[&_label]:text-[color:#446078]", "tw:[&_label]:text-[.72rem]", "tw:[&_label]:font-[750]", "tw:[&_input]:min-h-[36px]",
    "tw:[&_input]:pt-[6px]", "tw:[&_input]:pr-[9px]", "tw:[&_input]:pb-[6px]", "tw:[&_input]:pl-[9px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#d5e1e9]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#d5e1e9]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:#d5e1e9]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#d5e1e9]",
    "tw:[&_input]:rounded-[6px]", "tw:[&_input]:[font:inherit]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "whatsapp_image_lightbox": [
    "whatsapp-image-lightbox", "tw:fixed", "tw:z-[1200]", "tw:top-[0]",
    "tw:right-[0]", "tw:bottom-[0]", "tw:left-[0]", "tw:grid",
    "tw:place-items-center", "tw:pt-[28px]", "tw:pr-[28px]", "tw:pb-[28px]",
    "tw:pl-[28px]", "tw:bg-[color:rgb(5_15_25_/_.82)]", "tw:[background-image:none]", "tw:[cursor:zoom-out]",
    "tw:[&_img]:block", "tw:[&_img]:max-w-[min(1120px,_94vw)]", "tw:[&_img]:max-h-[88vh]", "tw:[&_img]:[object-fit:contain]",
    "tw:[&_img]:rounded-[10px]", "tw:[&_img]:[box-shadow:0_20px_70px_rgb(0_0_0_/_.42)]", "tw:[&_img]:[cursor:default]", "tw:[&_button]:fixed",
    "tw:[&_button]:top-[20px]", "tw:[&_button]:right-[24px]", "tw:[&_button]:grid", "tw:[&_button]:w-[38px]",
    "tw:[&_button]:h-[38px]", "tw:[&_button]:place-items-center", "tw:[&_button]:border-t-[length:1px]", "tw:[&_button]:[border-top-style:solid]",
    "tw:[&_button]:border-t-[color:rgb(255_255_255_/_.4)]", "tw:[&_button]:border-r-[length:1px]", "tw:[&_button]:[border-right-style:solid]", "tw:[&_button]:border-r-[color:rgb(255_255_255_/_.4)]",
    "tw:[&_button]:border-b-[length:1px]", "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:rgb(255_255_255_/_.4)]", "tw:[&_button]:border-l-[length:1px]",
    "tw:[&_button]:[border-left-style:solid]", "tw:[&_button]:border-l-[color:rgb(255_255_255_/_.4)]", "tw:[&_button]:rounded-[50%]", "tw:[&_button]:text-[color:#fff]",
    "tw:[&_button]:bg-[color:rgb(0_0_0_/_.25)]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[1.6rem]", "tw:[&_button]:leading-[1]",
    "tw:[&_button]:cursor-pointer",
  ].join(" "),
  "whatsapp_workspace_notice": [
    "whatsapp-workspace-notice", "tw:absolute", "tw:right-[14px]", "tw:viewport-720:right-[10px]",
    "tw:bottom-[12px]", "tw:viewport-720:bottom-[10px]", "tw:z-[3]", "tw:mt-[0]",
    "tw:mr-[0]", "tw:mb-[0]", "tw:ml-[0]", "tw:pt-[8px]",
    "tw:pr-[11px]", "tw:pb-[8px]", "tw:pl-[11px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#bce8cf]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#bce8cf]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#bce8cf]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#bce8cf]", "tw:rounded-[6px]",
    "tw:text-[color:#137547]", "tw:bg-[color:#edfbf3]", "tw:[background-image:none]", "tw:text-[.72rem]",
    "tw:font-[700]", "tw:[box-shadow:0_5px_15px_rgb(31_85_61_/_.12)]",
  ].join(" "),
} as const;
