import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "agency_shell": [
    "agency-shell", "tw:min-h-[100vh]", "tw:grid", "tw:grid-cols-[292px_minmax(0,_1fr)]",
    "tw:viewport-1024:grid-cols-[1fr]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
  ].join(" "),
  "agency_sidebar": [
    "agency-sidebar", "tw:min-h-[100vh]", "tw:viewport-1024:min-h-[0]", "tw:pt-[22px]",
    "tw:viewport-1024:pt-[14px]", "tw:pr-[22px]", "tw:viewport-1024:pr-[14px]", "tw:pb-[22px]",
    "tw:viewport-1024:pb-[14px]", "tw:pl-[22px]", "tw:viewport-1024:pl-[14px]", "tw:border-r-[length:1px]",
    "tw:viewport-1024:border-r-[length:0]", "tw:[border-right-style:solid]", "tw:viewport-1024:[border-right-style:none]", "tw:border-r-[color:rgba(255,_255,_255,_0.12)]",
    "tw:viewport-1024:border-r-[color:currentColor]", "tw:bg-[color:#0a2955]!", "tw:[background-image:radial-gradient(circle_at_85%_16%,_rgb(65_166_231_/_.28),_transparent_30%),_linear-gradient(150deg,_#103e77,_#0a2955_72%)]!", "tw:[background-attachment:fixed]!",
    "tw:[&_.eyebrow]:text-[color:rgba(245,_250,_255,_0.88)]", "tw:[&_.muted]:text-[color:rgba(245,_250,_255,_0.88)]", "tw:[&_.user-name]:text-[color:rgba(245,_250,_255,_0.88)]", "tw:[&_.agency-nav_.nav-group-label]:text-[color:rgba(245,_250,_255,_0.88)]",
    "tw:[&_.agency-nav_.nav-link]:text-[color:rgba(245,_250,_255,_0.88)]", "tw:[&_.agency-nav_.nav-sub-link]:text-[color:rgba(245,_250,_255,_0.88)]", "tw:[&_.agency-nav_.nav-toggle]:text-[color:rgba(245,_250,_255,_0.88)]", "tw:[&_.agency-nav_.nav-toggle]:w-[30px]",
    "tw:[&_.agency-nav_.nav-toggle]:h-[30px]", "tw:[&_.agency-nav_.nav-toggle]:[flex:0_0_30px]", "tw:[&_.agency-nav_.nav-toggle]:ml-[4px]", "tw:[&_.agency-nav_.nav-toggle]:border-t-[length:1px]",
    "tw:[&_.agency-nav_.nav-toggle]:[border-top-style:solid]", "tw:[&_.agency-nav_.nav-toggle]:border-t-[color:rgb(192_221_255_/_.25)]", "tw:[&_.agency-nav_.nav-toggle]:border-r-[length:1px]", "tw:[&_.agency-nav_.nav-toggle]:[border-right-style:solid]",
    "tw:[&_.agency-nav_.nav-toggle]:border-r-[color:rgb(192_221_255_/_.25)]", "tw:[&_.agency-nav_.nav-toggle]:border-b-[length:1px]", "tw:[&_.agency-nav_.nav-toggle]:[border-bottom-style:solid]", "tw:[&_.agency-nav_.nav-toggle]:border-b-[color:rgb(192_221_255_/_.25)]",
    "tw:[&_.agency-nav_.nav-toggle]:border-l-[length:1px]", "tw:[&_.agency-nav_.nav-toggle]:[border-left-style:solid]", "tw:[&_.agency-nav_.nav-toggle]:border-l-[color:rgb(192_221_255_/_.25)]", "tw:[&_.agency-nav_.nav-toggle]:rounded-[7px]",
    "tw:[&_.agency-nav_.nav-toggle]:bg-[color:rgb(255_255_255_/_.08)]", "tw:[&_.agency-nav_.nav-toggle]:[background-image:none]", "tw:[&_.agency-nav_.nav-toggle]:cursor-pointer", "tw:[&_.button-secondary]:border-t-[color:rgba(255,_255,_255,_0.24)]",
    "tw:[&_.button-secondary]:border-r-[color:rgba(255,_255,_255,_0.24)]", "tw:[&_.button-secondary]:border-b-[color:rgba(255,_255,_255,_0.24)]", "tw:[&_.button-secondary]:border-l-[color:rgba(255,_255,_255,_0.24)]", "tw:[&_.button-secondary]:text-[color:#ffffff]",
    "tw:[&_.button-secondary:hover]:border-t-[color:rgba(255,_255,_255,_0.34)]", "tw:[&_.button-secondary:hover]:border-r-[color:rgba(255,_255,_255,_0.34)]", "tw:[&_.button-secondary:hover]:border-b-[color:rgba(255,_255,_255,_0.34)]", "tw:[&_.button-secondary:hover]:border-l-[color:rgba(255,_255,_255,_0.34)]",
    "tw:[&_.button-secondary:hover]:bg-[color:rgba(255,_255,_255,_0.12)]", "tw:[&_.button-secondary:hover]:[background-image:none]", "tw:[&_.button-secondary:hover]:text-[color:#ffffff]", "tw:viewport-1024:border-b-[length:1px]",
    "tw:viewport-1024:[border-bottom-style:solid]", "tw:viewport-1024:border-b-[color:var(--line)]", "tw:[&_.agency-nav_.nav-parent-row]:flex", "tw:[&_.agency-nav_.nav-parent-row]:items-center",
    "tw:[&_.agency-nav_.nav-parent-row]:min-w-[0]", "tw:[&_.agency-nav_.nav-parent-row_>_.nav-link]:min-w-[0]", "tw:[&_.agency-nav_.nav-parent-row_>_.nav-link]:[flex:1]", "tw:[&_.agency-nav_.nav-link-active]:rounded-[7px]",
    "tw:[&_.agency-nav_.nav-link-active]:bg-[color:rgb(103_173_247_/_.22)]", "tw:[&_.agency-nav_.nav-link-active]:[background-image:none]", "tw:[&_.agency-nav_.nav-sub-link-active]:rounded-[7px]", "tw:[&_.agency-nav_.nav-sub-link-active]:bg-[color:rgb(103_173_247_/_.22)]",
    "tw:[&_.agency-nav_.nav-sub-link-active]:[background-image:none]", "tw:viewport-1024:[&_.sidebar-inner]:min-h-[0]", "tw:viewport-1024:[&_.sidebar-inner]:gap-y-[12px]", "tw:viewport-1024:[&_.sidebar-inner]:gap-x-[12px]",
    "tw:viewport-1024:[&_.sidebar-top]:gap-y-[12px]", "tw:viewport-1024:[&_.sidebar-top]:gap-x-[12px]", "tw:viewport-1024:[&_.agency-nav]:gap-y-[10px]", "tw:viewport-1024:[&_.agency-nav]:gap-x-[10px]",
    "tw:viewport-1024:[&_.agency-nav_.nav-group]:hidden", "tw:viewport-1024:[&_.agency-nav-mobile-open_.nav-group]:grid", "tw:viewport-1024:[&_.sidebar-user]:flex", "tw:viewport-1024:[&_.sidebar-user]:items-center",
    "tw:viewport-1024:[&_.sidebar-user]:justify-between", "tw:viewport-1024:[&_.sidebar-user]:gap-y-[12px]", "tw:viewport-1024:[&_.sidebar-user]:gap-x-[12px]", "tw:viewport-1024:[&_.sidebar-user]:pt-[10px]",
    "tw:viewport-1024:[&_.sidebar-user]:border-t-[length:1px]", "tw:viewport-1024:[&_.sidebar-user]:[border-top-style:solid]", "tw:viewport-1024:[&_.sidebar-user]:border-t-[color:rgb(255_255_255_/_.2)]", "tw:viewport-1024:[&_.sidebar-user_.button]:min-h-[32px]",
  ].join(" "),
  "sidebar_inner": [
    "sidebar-inner", "tw:min-h-[calc(100vh_-_44px)]", "tw:viewport-760:min-h-[auto]", "tw:flex",
    "tw:viewport-760:grid", "tw:justify-between", "tw:flex-col", "tw:gap-y-[18px]",
    "tw:gap-x-[18px]",
  ].join(" "),
  "sidebar_top": [
    "sidebar-top", "tw:grid", "tw:gap-y-[14px]", "tw:gap-x-[14px]",
  ].join(" "),
  "agency_brand": [
    "agency-brand", "tw:flex", "tw:items-center", "tw:gap-y-[14px]",
    "tw:gap-x-[14px]", "tw:[&_>_span]:[display:inline-grid]", "tw:[&_>_span]:place-items-center", "tw:[&_>_span]:w-[52px]",
    "tw:[&_>_span]:h-[52px]", "tw:[&_>_span]:rounded-[16px]", "tw:[&_>_span]:bg-[color:var(--brand)]", "tw:[&_>_span]:[background-image:none]",
    "tw:[&_>_span]:text-[color:#ffffff]", "tw:[&_>_span]:text-[0.9rem]", "tw:[&_>_span]:font-[900]", "tw:[&_>_span]:tracking-[0.04em]",
    "tw:[&_strong]:block", "tw:[&_strong]:text-[color:#ffffff]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "agency_main": [
    "agency-main", "tw:min-w-[0]", "tw:pt-[22px]", "tw:viewport-1024:pt-[16px]",
    "tw:pr-[clamp(16px,_2vw,_30px)]", "tw:viewport-1024:pr-[14px]", "tw:pb-[42px]", "tw:viewport-1024:pb-[32px]",
    "tw:pl-[clamp(16px,_2vw,_30px)]", "tw:viewport-1024:pl-[14px]",
  ].join(" "),
  "agency_content": [
    "agency-content", "tw:w-[100%]", "tw:max-w-[none]", "tw:mt-[0]",
    "tw:mr-[0]", "tw:mb-[0]", "tw:ml-[0]", "tw:min-w-[0]",
    "tw:[&_>_.stack-md]:gap-y-[16px]", "tw:[&_>_.stack-md]:gap-x-[16px]", "tw:[&_>_.stack-md_>_.page-header]:absolute", "tw:[&_>_.stack-md_>_.page-header]:w-[1px]",
    "tw:[&_>_.stack-md_>_.page-header]:h-[1px]", "tw:[&_>_.stack-md_>_.page-header]:[overflow-x:hidden]", "tw:[&_>_.stack-md_>_.page-header]:[overflow-y:hidden]", "tw:[&_>_.stack-md_>_.page-header]:[clip:rect(0,_0,_0,_0)]",
    "tw:[&_>_.stack-md_>_.page-header]:whitespace-nowrap", "tw:[&_>_.stack-md_>_.page-header]:[clip-path:inset(50%)]", "tw:[&_.section-card]:min-w-[0]", "tw:[&_.section-card]:border-t-[length:1px]",
    "tw:[&_.section-card]:[border-top-style:solid]", "tw:[&_.section-card]:border-t-[color:#dce7f1]", "tw:[&_.section-card]:border-r-[length:1px]", "tw:[&_.section-card]:[border-right-style:solid]",
    "tw:[&_.section-card]:border-r-[color:#dce7f1]", "tw:[&_.section-card]:border-b-[length:1px]", "tw:[&_.section-card]:[border-bottom-style:solid]", "tw:[&_.section-card]:border-b-[color:#dce7f1]",
    "tw:[&_.section-card]:border-l-[length:1px]", "tw:[&_.section-card]:[border-left-style:solid]", "tw:[&_.section-card]:border-l-[color:#dce7f1]", "tw:[&_.section-card]:rounded-[10px]",
    "tw:[&_.section-card]:bg-[color:#fff]", "tw:[&_.section-card]:[background-image:none]", "tw:[&_.section-card]:[box-shadow:0_4px_16px_rgb(23_60_102_/_.035)]", "tw:[&_.section-card]:pt-[18px]",
    "tw:viewport-560:[&_.section-card]:pt-[14px]", "tw:[&_.section-card]:pr-[18px]", "tw:viewport-560:[&_.section-card]:pr-[14px]", "tw:[&_.section-card]:pb-[18px]",
    "tw:viewport-560:[&_.section-card]:pb-[14px]", "tw:[&_.section-card]:pl-[18px]", "tw:viewport-560:[&_.section-card]:pl-[14px]", "tw:[&_.agency-billing-section]:min-w-[0]",
    "tw:[&_.agency-billing-section]:border-t-[length:1px]", "tw:[&_.agency-billing-section]:[border-top-style:solid]", "tw:[&_.agency-billing-section]:border-t-[color:#dce7f1]", "tw:[&_.agency-billing-section]:border-r-[length:1px]",
    "tw:[&_.agency-billing-section]:[border-right-style:solid]", "tw:[&_.agency-billing-section]:border-r-[color:#dce7f1]", "tw:[&_.agency-billing-section]:border-b-[length:1px]", "tw:[&_.agency-billing-section]:[border-bottom-style:solid]",
    "tw:[&_.agency-billing-section]:border-b-[color:#dce7f1]", "tw:[&_.agency-billing-section]:border-l-[length:1px]", "tw:[&_.agency-billing-section]:[border-left-style:solid]", "tw:[&_.agency-billing-section]:border-l-[color:#dce7f1]",
    "tw:[&_.agency-billing-section]:rounded-[10px]", "tw:[&_.agency-billing-section]:bg-[color:#fff]", "tw:[&_.agency-billing-section]:[background-image:none]", "tw:[&_.agency-billing-section]:[box-shadow:0_4px_16px_rgb(23_60_102_/_.035)]",
    "tw:[&_.agency-billing-section]:pt-[18px]", "tw:viewport-560:[&_.agency-billing-section]:pt-[14px]", "tw:[&_.agency-billing-section]:pr-[18px]", "tw:viewport-560:[&_.agency-billing-section]:pr-[14px]",
    "tw:[&_.agency-billing-section]:pb-[18px]", "tw:viewport-560:[&_.agency-billing-section]:pb-[14px]", "tw:[&_.agency-billing-section]:pl-[18px]", "tw:viewport-560:[&_.agency-billing-section]:pl-[14px]",
    "tw:[&_.agency-billing-section]:gap-y-[16px]", "tw:[&_.agency-billing-section]:gap-x-[16px]", "tw:[&_.agency-arena-card]:min-w-[0]", "tw:[&_.agency-arena-card]:border-t-[length:1px]",
    "tw:[&_.agency-arena-card]:[border-top-style:solid]", "tw:[&_.agency-arena-card]:border-t-[color:#dce7f1]", "tw:[&_.agency-arena-card]:border-r-[length:1px]", "tw:[&_.agency-arena-card]:[border-right-style:solid]",
    "tw:[&_.agency-arena-card]:border-r-[color:#dce7f1]", "tw:[&_.agency-arena-card]:border-b-[length:1px]", "tw:[&_.agency-arena-card]:[border-bottom-style:solid]", "tw:[&_.agency-arena-card]:border-b-[color:#dce7f1]",
    "tw:[&_.agency-arena-card]:border-l-[length:1px]", "tw:[&_.agency-arena-card]:[border-left-style:solid]", "tw:[&_.agency-arena-card]:border-l-[color:#dce7f1]", "tw:[&_.agency-arena-card]:rounded-[10px]",
    "tw:[&_.agency-arena-card]:bg-[color:#fff]", "tw:[&_.agency-arena-card]:[background-image:none]", "tw:[&_.agency-arena-card]:[box-shadow:0_4px_16px_rgb(23_60_102_/_.035)]", "tw:[&_.agency-ticket-card]:min-w-[0]",
    "tw:[&_.agency-ticket-card]:border-t-[length:1px]", "tw:[&_.agency-ticket-card]:[border-top-style:solid]", "tw:[&_.agency-ticket-card]:border-t-[color:#dce7f1]", "tw:[&_.agency-ticket-card]:border-r-[length:1px]",
    "tw:[&_.agency-ticket-card]:[border-right-style:solid]", "tw:[&_.agency-ticket-card]:border-r-[color:#dce7f1]", "tw:[&_.agency-ticket-card]:border-b-[length:1px]", "tw:[&_.agency-ticket-card]:[border-bottom-style:solid]",
    "tw:[&_.agency-ticket-card]:border-b-[color:#dce7f1]", "tw:[&_.agency-ticket-card]:border-l-[length:1px]", "tw:[&_.agency-ticket-card]:[border-left-style:solid]", "tw:[&_.agency-ticket-card]:border-l-[color:#dce7f1]",
    "tw:[&_.agency-ticket-card]:rounded-[10px]", "tw:[&_.agency-ticket-card]:bg-[color:#fff]", "tw:[&_.agency-ticket-card]:[background-image:none]", "tw:[&_.agency-ticket-card]:[box-shadow:0_4px_16px_rgb(23_60_102_/_.035)]",
    "tw:[&_.agency-plan-card]:min-w-[0]", "tw:[&_.agency-plan-card]:border-t-[length:1px]", "tw:[&_.agency-plan-card]:[border-top-style:solid]", "tw:[&_.agency-plan-card]:border-t-[color:#dce7f1]",
    "tw:[&_.agency-plan-card]:border-r-[length:1px]", "tw:[&_.agency-plan-card]:[border-right-style:solid]", "tw:[&_.agency-plan-card]:border-r-[color:#dce7f1]", "tw:[&_.agency-plan-card]:border-b-[length:1px]",
    "tw:[&_.agency-plan-card]:[border-bottom-style:solid]", "tw:[&_.agency-plan-card]:border-b-[color:#dce7f1]", "tw:[&_.agency-plan-card]:border-l-[length:1px]", "tw:[&_.agency-plan-card]:[border-left-style:solid]",
    "tw:[&_.agency-plan-card]:border-l-[color:#dce7f1]", "tw:[&_.agency-plan-card]:rounded-[10px]", "tw:[&_.agency-plan-card]:bg-[color:#f8fbff]", "tw:[&_.agency-plan-card]:[background-image:none]",
    "tw:[&_.agency-plan-card]:[box-shadow:0_4px_16px_rgb(23_60_102_/_.035)]", "tw:[&_.agency-subscription-row]:min-w-[0]", "tw:[&_.agency-subscription-row]:border-t-[length:1px]", "tw:[&_.agency-subscription-row]:[border-top-style:solid]",
    "tw:[&_.agency-subscription-row]:border-t-[color:#e1eaf3]", "tw:[&_.agency-subscription-row]:border-r-[length:1px]", "tw:[&_.agency-subscription-row]:[border-right-style:solid]", "tw:[&_.agency-subscription-row]:border-r-[color:#e1eaf3]",
    "tw:[&_.agency-subscription-row]:border-b-[length:1px]", "tw:[&_.agency-subscription-row]:[border-bottom-style:solid]", "tw:[&_.agency-subscription-row]:border-b-[color:#e1eaf3]", "tw:[&_.agency-subscription-row]:border-l-[length:1px]",
    "tw:[&_.agency-subscription-row]:[border-left-style:solid]", "tw:[&_.agency-subscription-row]:border-l-[color:#e1eaf3]", "tw:[&_.agency-subscription-row]:rounded-[10px]", "tw:[&_.agency-subscription-row]:bg-[color:#fff]",
    "tw:[&_.agency-subscription-row]:[background-image:none]", "tw:[&_.agency-subscription-row]:[box-shadow:0_4px_16px_rgb(23_60_102_/_.035)]", "tw:[&_.agency-invoice-row]:min-w-[0]", "tw:[&_.agency-invoice-row]:border-t-[length:1px]",
    "tw:[&_.agency-invoice-row]:[border-top-style:solid]", "tw:[&_.agency-invoice-row]:border-t-[color:#e1eaf3]", "tw:[&_.agency-invoice-row]:border-r-[length:1px]", "tw:[&_.agency-invoice-row]:[border-right-style:solid]",
    "tw:[&_.agency-invoice-row]:border-r-[color:#e1eaf3]", "tw:[&_.agency-invoice-row]:border-b-[length:1px]", "tw:[&_.agency-invoice-row]:[border-bottom-style:solid]", "tw:[&_.agency-invoice-row]:border-b-[color:#e1eaf3]",
    "tw:[&_.agency-invoice-row]:border-l-[length:1px]", "tw:[&_.agency-invoice-row]:[border-left-style:solid]", "tw:[&_.agency-invoice-row]:border-l-[color:#e1eaf3]", "tw:[&_.agency-invoice-row]:rounded-[10px]",
    "tw:[&_.agency-invoice-row]:bg-[color:#fff]", "tw:[&_.agency-invoice-row]:[background-image:none]", "tw:[&_.agency-invoice-row]:[box-shadow:0_4px_16px_rgb(23_60_102_/_.035)]", "tw:[&_.stat-card]:min-w-[0]",
    "tw:[&_.stat-card]:border-t-[length:1px]", "tw:[&_.stat-card]:[border-top-style:solid]", "tw:[&_.stat-card]:border-t-[color:#dce7f1]", "tw:[&_.stat-card]:border-r-[length:1px]",
    "tw:[&_.stat-card]:[border-right-style:solid]", "tw:[&_.stat-card]:border-r-[color:#dce7f1]", "tw:[&_.stat-card]:border-b-[length:1px]", "tw:[&_.stat-card]:[border-bottom-style:solid]",
    "tw:[&_.stat-card]:border-b-[color:#dce7f1]", "tw:[&_.stat-card]:border-l-[length:1px]", "tw:[&_.stat-card]:[border-left-style:solid]", "tw:[&_.stat-card]:border-l-[color:#dce7f1]",
    "tw:[&_.stat-card]:rounded-[10px]", "tw:[&_.stat-card]:bg-[color:#fff]", "tw:[&_.stat-card]:[background-image:none]", "tw:[&_.stat-card]:[box-shadow:0_4px_16px_rgb(23_60_102_/_.035)]",
    "tw:[&_.stat-card]:pt-[16px]", "tw:[&_.stat-card]:pr-[16px]", "tw:[&_.stat-card]:pb-[16px]", "tw:[&_.stat-card]:pl-[16px]",
    "tw:[&_.section-card_h2]:text-[color:#173961]", "tw:[&_.section-card_h2]:text-[1rem]", "tw:[&_.section-card_h2]:leading-[1.4]", "tw:[&_.agency-billing-section_h2]:text-[color:#173961]",
    "tw:[&_.agency-billing-section_h2]:text-[1rem]", "tw:[&_.agency-billing-section_h2]:leading-[1.4]", "tw:[&_.section-card_.muted]:text-[color:#62788e]", "tw:[&_.section-card_.muted]:text-[.82rem]",
    "tw:[&_.section-card_.muted]:leading-[1.45]", "tw:[&_.agency-billing-section_.muted]:text-[color:#62788e]", "tw:[&_.agency-billing-section_.muted]:text-[.82rem]", "tw:[&_.agency-billing-section_.muted]:leading-[1.45]",
    "tw:[&_.stat-card_strong]:text-[color:#12345a]", "tw:[&_:is(input,_select,_textarea)]:[box-sizing:border-box]", "tw:[&_:is(input,_select,_textarea)]:min-w-[0]", "tw:[&_:is(input,_select,_textarea)]:max-w-[100%]",
    "tw:[&_:is(input,_select,_textarea)]:rounded-[7px]", "tw:[&_:is(.agency-arena-edit-form,_.agency-ticket-controls,_.agency-ticket-message-form,_.agency-subscription-form,_.agency-user-role-form)]:min-w-[0]", "tw:[&_.data-table]:min-w-[620px]", "tw:[&_.section-card:has(.data-table)]:[overflow-x:auto]",
    "tw:[&_.agency-mini-row]:border-t-[color:#e1eaf3]", "tw:[&_.agency-mini-row]:border-r-[color:#e1eaf3]", "tw:[&_.agency-mini-row]:border-b-[color:#e1eaf3]", "tw:[&_.agency-mini-row]:border-l-[color:#e1eaf3]",
    "tw:[&_.agency-plan-create]:grid-cols-[minmax(0,_2fr)_minmax(0,_1fr)_auto]", "tw:viewport-1024:[&_.agency-plan-create]:grid-cols-[minmax(0,_1fr)]", "tw:viewport-1024:[&_.agency-subscription-row]:grid-cols-[minmax(0,_1fr)]", "tw:viewport-1024:[&_.agency-invoice-row]:grid-cols-[repeat(2,_minmax(0,_1fr))]",
    "tw:viewport-560:[&_.agency-invoice-row]:grid-cols-[minmax(0,_1fr)]", "tw:viewport-560:[&_.agency-subscription-form]:flex-wrap", "tw:viewport-560:[&_.agency-subscription-form_select]:[flex-basis:100%]",
  ].join(" "),
} as const;
