import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "app_shell": [
    "app-shell", "tw:min-h-[100vh]", "tw:[overflow-x:hidden]", "tw:grid",
    "tw:viewport-760:block", "tw:grid-cols-[280px_minmax(0,_1fr)]", "tw:viewport-1120:grid-cols-[248px_minmax(0,_1fr)]", "tw:[&_.nav-link-active]:border-t-[color:rgb(83_158_255_/_.56)]",
    "tw:[&_.nav-link-active]:border-r-[color:rgb(83_158_255_/_.56)]", "tw:[&_.nav-link-active]:border-b-[color:rgb(83_158_255_/_.56)]", "tw:[&_.nav-link-active]:border-l-[color:rgb(83_158_255_/_.56)]", "tw:[&_.nav-link-active]:bg-[color:transparent]",
    "tw:[&_.nav-link-active]:[background-image:linear-gradient(135deg,_#0868e5,_#0754c3)]", "tw:[&_.nav-link-active]:text-[color:#fff]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:h-[100dvh]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:min-h-[0]",
    "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:[overflow-x:hidden]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:[overflow-y:hidden]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_>_.sidebar]:h-[100dvh]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_>_.sidebar]:min-h-[0]",
    "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_>_.sidebar]:[overflow-x:hidden]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_>_.sidebar]:[overflow-y:auto]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_>_.sidebar]:[overscroll-behavior:contain]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_>_.sidebar_.sidebar-inner]:min-h-[100%]",
  ].join(" "),
  "sidebar": [
    "sidebar", "tw:z-[20]", "tw:min-h-[100vh]", "tw:viewport-760:min-h-[auto]",
    "tw:pt-[18px]", "tw:viewport-720:pt-[14px]", "tw:pr-[14px]", "tw:viewport-720:pr-[10px]",
    "tw:pb-[18px]", "tw:viewport-720:pb-[14px]", "tw:pl-[14px]", "tw:viewport-720:pl-[10px]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(96_163_255_/_.22)]", "tw:bg-[color:#0a2955]!",
    "tw:[background-image:radial-gradient(circle_at_85%_16%,_rgb(65_166_231_/_.28),_transparent_30%),_linear-gradient(150deg,_#103e77,_#0a2955_72%)]!", "tw:[backdrop-filter:blur(16px)]", "tw:[overflow-x:visible]", "tw:[overflow-y:visible]",
    "tw:[animation:slide-right_480ms_var(--ease-standard)]", "tw:[box-shadow:inset_-1px_0_rgb(255_255_255_/_.04)]", "tw:[background-attachment:fixed]!", "tw:[font-family:'Segoe_UI',_Tahoma,_sans-serif]",
    "tw:[&_.eyebrow]:text-[color:rgba(245,_250,_255,_0.88)]", "tw:[&_.muted]:text-[color:rgba(245,_250,_255,_0.88)]", "tw:[&_.user-name]:text-[color:rgba(245,_250,_255,_0.88)]", "tw:[&_.button-secondary]:border-t-[color:rgba(255,_255,_255,_0.24)]",
    "tw:[&_.button-secondary]:border-r-[color:rgba(255,_255,_255,_0.24)]", "tw:[&_.button-secondary]:border-b-[color:rgba(255,_255,_255,_0.24)]", "tw:[&_.button-secondary]:border-l-[color:rgba(255,_255,_255,_0.24)]", "tw:[&_.button-secondary]:text-[color:#ffffff]",
    "tw:[&_.button-secondary:hover]:border-t-[color:rgba(255,_255,_255,_0.34)]", "tw:[&_.button-secondary:hover]:border-r-[color:rgba(255,_255,_255,_0.34)]", "tw:[&_.button-secondary:hover]:border-b-[color:rgba(255,_255,_255,_0.34)]", "tw:[&_.button-secondary:hover]:border-l-[color:rgba(255,_255,_255,_0.34)]",
    "tw:[&_.button-secondary:hover]:bg-[color:rgba(255,_255,_255,_0.12)]", "tw:[&_.button-secondary:hover]:[background-image:none]", "tw:[&_.button-secondary:hover]:text-[color:#ffffff]", "tw:viewport-760:relative",
    "tw:viewport-760:h-[auto]", "tw:viewport-760:border-b-[length:1px]", "tw:viewport-760:[border-bottom-style:solid]", "tw:viewport-760:border-b-[color:rgba(199,_211,_225,_0.72)]",
    "tw:[&_.arena-notification-panel]:fixed", "tw:[&_.arena-notification-panel]:top-[18px]", "tw:viewport-720:[&_.arena-notification-panel]:top-[12px]", "tw:[&_.arena-notification-panel]:left-[296px]",
    "tw:viewport-720:[&_.arena-notification-panel]:left-[16px]", "tw:[&_.arena-notification-panel]:right-[auto]", "tw:[&_.arena-notification-panel]:w-[min(360px,_calc(100vw_-_32px))]", "tw:viewport-720:[&_.arena-notification-panel]:w-[calc(100vw_-_32px)]",
    "tw:[&_.arena-notification-panel]:max-h-[min(420px,_calc(100vh_-_36px))]", "tw:[&_:where(button,_select,_a)]:[font-family:'Segoe_UI',_Tahoma,_sans-serif]", "tw:[&.sidebar_.nav-link]:font-[560]", "tw:[&.sidebar_.nav-link]:text-[color:#f8fbff]",
    "tw:[&_.nav-sub-link]:font-[560]", "tw:[&_.nav-sub-link]:text-[color:rgb(248_251_255_/_.9)]", "tw:[&_.nav-link-parent]:text-[color:#f8fbff]", "tw:[&_.nav-sub-link-parent]:text-[color:#f8fbff]",
    "tw:[&_.nav-group-label]:text-[color:#c8defd]",
  ].join(" "),
  "sidebar_inner": [
    "sidebar-inner", "tw:min-h-[calc(100vh_-_44px)]", "tw:viewport-760:min-h-[auto]", "tw:flex",
    "tw:viewport-760:grid", "tw:justify-between", "tw:flex-col", "tw:gap-y-[18px]",
    "tw:gap-x-[18px]",
  ].join(" "),
  "sidebar_top": [
    "sidebar-top", "tw:grid", "tw:gap-y-[14px]", "tw:gap-x-[14px]",
  ].join(" "),
  "brand_lockup_sidebar_brand_lockup": [
    "brand-lockup", "sidebar-brand-lockup", "tw:grid", "tw:items-start",
    "tw:gap-y-[7px]", "tw:gap-x-[10px]", "tw:min-w-[220px]", "tw:viewport-760:min-w-[0]",
    "tw:[&_strong]:block", "tw:[&_strong]:text-[.86rem]", "tw:[&_strong]:font-[700]", "tw:[&_strong]:tracking-[-0.02em]",
    "tw:[&_strong]:[overflow-wrap:anywhere]", "tw:[&_strong]:text-[color:#fff]", "tw:pt-[3px]", "tw:pr-[4px]",
    "tw:pb-[12px]", "tw:pl-[4px]", "tw:flex-col", "tw:relative",
    "tw:grid-cols-[minmax(0,_1fr)_auto]", "tw:[grid-template-areas:'logo_logo'_'copy_notification']", "tw:w-[100%]", "tw:[&_.brand-logo-wrap]:w-[100%]!",
    "tw:[&_.brand-logo-wrap]:h-[54px]!", "tw:[&_.brand-logo-wrap]:rounded-[0]!", "tw:[&_.brand-logo-wrap]:[box-shadow:none]!", "tw:[&_.brand-logo-wrap]:[overflow-x:visible]!",
    "tw:[&_.brand-logo-wrap]:[overflow-y:visible]!", "tw:[&_.brand-logo-wrap]:bg-[color:transparent]!", "tw:[&_.brand-logo-wrap]:[background-image:none]!", "tw:[&_.brand-logo-wrap]:border-t-[length:0]!",
    "tw:[&_.brand-logo-wrap]:[border-top-style:none]!", "tw:[&_.brand-logo-wrap]:border-t-[color:currentColor]!", "tw:[&_.brand-logo-wrap]:border-r-[length:0]!", "tw:[&_.brand-logo-wrap]:[border-right-style:none]!",
    "tw:[&_.brand-logo-wrap]:border-r-[color:currentColor]!", "tw:[&_.brand-logo-wrap]:border-b-[length:0]!", "tw:[&_.brand-logo-wrap]:[border-bottom-style:none]!", "tw:[&_.brand-logo-wrap]:border-b-[color:currentColor]!",
    "tw:[&_.brand-logo-wrap]:border-l-[length:0]!", "tw:[&_.brand-logo-wrap]:[border-left-style:none]!", "tw:[&_.brand-logo-wrap]:border-l-[color:currentColor]!", "tw:[&_.brand-logo-wrap]:[grid-area:logo]",
    "tw:[&_.brand-logo]:rounded-[0]!", "tw:[&_.brand-logo]:w-[auto]!", "tw:[&_.brand-logo]:h-[54px]!", "tw:[&_.brand-logo]:[object-fit:contain]",
    "tw:[&_.brand-logo]:max-w-[150px]!", "tw:[&_.brand-logo]:[object-position:left_center]", "tw:[&_.brand-logo]:border-t-[length:0]!", "tw:[&_.brand-logo]:[border-top-style:none]!",
    "tw:[&_.brand-logo]:border-t-[color:currentColor]!", "tw:[&_.brand-logo]:border-r-[length:0]!", "tw:[&_.brand-logo]:[border-right-style:none]!", "tw:[&_.brand-logo]:border-r-[color:currentColor]!",
    "tw:[&_.brand-logo]:border-b-[length:0]!", "tw:[&_.brand-logo]:[border-bottom-style:none]!", "tw:[&_.brand-logo]:border-b-[color:currentColor]!", "tw:[&_.brand-logo]:border-l-[length:0]!",
    "tw:[&_.brand-logo]:[border-left-style:none]!", "tw:[&_.brand-logo]:border-l-[color:currentColor]!", "tw:[&_.brand-logo]:bg-[color:transparent]!", "tw:[&_.brand-logo]:[background-image:none]!",
    "tw:[&_.brand-logo]:[box-shadow:none]!", "tw:[&_.eyebrow]:text-[color:#9ebcf1]", "tw:[&_.eyebrow]:text-[.62rem]", "tw:[&_.eyebrow]:tracking-[.045em]",
    "tw:[&_.arena-notification-bell]:[grid-area:notification]", "tw:[&_.arena-notification-bell]:[align-self:center]", "tw:[&_.arena-notification-bell]:[justify-self:end]", "tw:[&_.arena-notification-bell]:z-[40]",
    "tw:[&_.arena-notification-bell_>_button]:w-[32px]", "tw:[&_.arena-notification-bell_>_button]:h-[32px]",
  ].join(" "),
  "brand_logo_wrap": [
    "brand-logo-wrap", "tw:grid", "tw:place-items-center", "tw:w-[52px]",
    "tw:h-[52px]", "tw:rounded-[16px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgba(255,_255,_255,_0.26)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgba(255,_255,_255,_0.26)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgba(255,_255,_255,_0.26)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgba(255,_255,_255,_0.26)]", "tw:bg-[color:#071e3c]", "tw:[background-image:none]",
    "tw:[box-shadow:0_12px_26px_rgba(2,_20,_48,_0.34)]", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]",
  ].join(" "),
  "brand_logo": [
    "brand-logo", "tw:w-[100%]", "tw:h-[100%]", "tw:[object-fit:cover]",
    "tw:[transition:transform_220ms_var(--ease-standard)]",
  ].join(" "),
  "sidebar_brand_copy": [
    "sidebar-brand-copy", "tw:grid", "tw:gap-y-[2px]", "tw:gap-x-[2px]",
    "tw:[grid-area:copy]", "tw:min-w-[0]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "sidebar_user_sidebar_user_panel": [
    "sidebar-user", "sidebar-user-panel", "tw:grid", "tw:gap-y-[11px]",
    "tw:gap-x-[11px]", "tw:pt-[13px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(108_164_239_/_.26)]", "tw:[&_.button]:w-[100%]", "tw:pr-[12px]", "tw:pb-[13px]",
    "tw:pl-[12px]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(108_164_239_/_.26)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(108_164_239_/_.26)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(108_164_239_/_.26)]", "tw:rounded-[10px]", "tw:bg-[color:rgb(1_21_62_/_.42)]",
    "tw:[background-image:none]", "tw:[box-shadow:0_8px_24px_rgb(0_0_0_/_.14)]", "tw:[&.sidebar-user-panel_.user-name]:text-[color:#fff]", "tw:[&.sidebar-user-panel_.user-name]:text-[.8rem]",
    "tw:[&.sidebar-user-panel_.muted]:text-[color:#9db6de]", "tw:[&.sidebar-user-panel_.muted]:text-[.65rem]", "tw:[&_.button]:min-h-[34px]", "tw:[&_.button]:justify-center",
    "tw:[&_.button]:border-t-[color:rgb(127_177_244_/_.32)]", "tw:[&_.button]:border-r-[color:rgb(127_177_244_/_.32)]", "tw:[&_.button]:border-b-[color:rgb(127_177_244_/_.32)]", "tw:[&_.button]:border-l-[color:rgb(127_177_244_/_.32)]",
    "tw:[&_.button]:bg-[color:rgb(24_83_163_/_.42)]", "tw:[&_.button]:[background-image:none]", "tw:[&_.button]:text-[color:#eaf3ff]", "tw:[&_.button]:text-[.74rem]",
    "tw:[&_.button]:[box-shadow:none]", "tw:[&_.button:hover]:bg-[color:rgb(29_105_203_/_.6)]", "tw:[&_.button:hover]:[background-image:none]",
  ].join(" "),
  "user_copy": [
    "user-copy", "tw:text-left",
  ].join(" "),
  "user_name": [
    "user-name", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:font-[700]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "sidebar_settings_menu": [
    "sidebar-settings-menu", "tw:grid", "tw:gap-y-[3px]", "tw:gap-x-[3px]",
    "tw:pt-[9px]", "tw:pr-[9px]", "tw:pb-[9px]", "tw:pl-[9px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(116_174_245_/_.2)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(116_174_245_/_.2)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgb(116_174_245_/_.2)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(116_174_245_/_.2)]",
    "tw:rounded-[8px]", "tw:bg-[color:rgb(9_49_106_/_.3)]", "tw:[background-image:none]", "tw:[&_>_strong]:text-[color:#e9f3ff]",
    "tw:[&_>_strong]:text-[.7rem]", "tw:[&_>_strong]:font-[800]",
  ].join(" "),
  "sidebar_settings_link": [
    "sidebar-settings-link", "tw:block", "tw:pt-[4px]", "tw:pr-[7px]",
    "tw:pb-[4px]", "tw:pl-[7px]", "tw:rounded-[5px]", "tw:text-[color:rgb(235_245_255_/_.8)]",
    "tw:text-[.69rem]", "tw:[text-decoration:none]", "tw:[transition:background_.15s_ease,_color_.15s_ease]", "tw:hover:bg-[color:rgb(255_255_255_/_.1)]",
    "tw:hover:[background-image:none]", "tw:hover:text-[color:#fff]",
  ].join(" "),
  "button_button_secondary": sharedUtilities.buttonButtonSecondary,
  "app_main": [
    "app-main", "tw:pt-[clamp(16px,_1.5vw,_24px)]", "tw:viewport-760:pt-[18px]", "tw:viewport-720:pt-[16px]",
    "tw:pr-[clamp(16px,_1.5vw,_24px)]", "tw:viewport-760:pr-[18px]", "tw:viewport-720:pr-[16px]", "tw:pb-[clamp(16px,_1.5vw,_24px)]",
    "tw:viewport-760:pb-[18px]", "tw:viewport-720:pb-[16px]", "tw:pl-[clamp(16px,_1.5vw,_24px)]", "tw:viewport-760:pl-[18px]",
    "tw:viewport-720:pl-[16px]", "tw:min-w-[0]", "tw:bg-[color:#ffffff]", "tw:[background-image:none]",
    "tw:[&:has(.commands-page)]:pt-[0]", "tw:[&:has(.commands-page)]:pr-[0]", "tw:[&:has(.commands-page)]:pb-[0]", "tw:[&:has(.commands-page)]:pl-[0]",
    "tw:[&:has(.commands-page)]:bg-[color:#ffffff]", "tw:[&:has(.commands-page)]:[background-image:none]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:h-[100dvh]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:pt-[0]",
    "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:pr-[0]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:pb-[0]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:pl-[0]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:[overflow-x:hidden]",
    "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:[overflow-y:hidden]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:relative", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:min-h-[0]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_>_.content-shell]:absolute",
    "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_>_.content-shell]:top-[0]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_>_.content-shell]:right-[0]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_>_.content-shell]:bottom-[0]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_>_.content-shell]:left-[0]",
    "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_>_.content-shell]:h-[auto]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_>_.content-shell]:min-h-[0]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_.content-shell]:h-[100%]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_.content-shell]:min-h-[0]",
    "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_.content-shell]:[overflow-x:hidden]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)_.content-shell]:[overflow-y:hidden]",
  ].join(" "),
  "content_shell": [
    "content-shell", "tw:w-[100%]", "tw:max-w-[none]", "tw:mt-[0]",
    "tw:mr-[0]", "tw:mb-[0]", "tw:ml-[0]", "tw:min-h-[calc(100vh_-_32px)]",
    "tw:[&:has(.commands-page)]:min-h-[100vh]", "tw:[&:has(.commands-page)]:pt-[20px]", "tw:viewport-760:[&:has(.commands-page)]:pt-[16px]", "tw:[&:has(.commands-page)]:pr-[30px]",
    "tw:viewport-760:[&:has(.commands-page)]:pr-[13px]", "tw:[&:has(.commands-page)]:pb-[34px]", "tw:viewport-760:[&:has(.commands-page)]:pb-[26px]", "tw:[&:has(.commands-page)]:pl-[30px]",
    "tw:viewport-760:[&:has(.commands-page)]:pl-[13px]", "tw:[&:has(.commands-page)]:bg-[color:#ffffff]", "tw:[&:has(.commands-page)]:[background-image:none]", "tw:[&:has(.commands-page)]:max-w-[100%]",
    "tw:[&:has(.agenda-page)]:max-w-[none]", "tw:[&:has(.agenda-page)]:mt-[0]", "tw:[&:has(.agenda-page)]:mr-[0]", "tw:[&:has(.agenda-page)]:mb-[0]",
    "tw:[&:has(.agenda-page)]:ml-[0]", "tw:[&:has(.whatsapp-page)]:min-h-[calc(100vh_-_48px)]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:min-h-[0]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:h-[100%]",
    "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:[overflow-x:hidden]", "tw:[@media(min-width:721px)]:[&:has(.whatsapp-page)]:[overflow-y:hidden]",
  ].join(" "),
  "agency_payment_alert": [
    "agency-payment-alert", "tw:flex", "tw:items-center", "tw:flex-wrap",
    "tw:gap-y-[5px]", "tw:gap-x-[9px]", "tw:mt-[0]", "tw:mr-[0]",
    "tw:mb-[16px]", "tw:ml-[0]", "tw:pt-[12px]", "tw:pr-[14px]",
    "tw:pb-[12px]", "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#e5c275]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#e5c275]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e5c275]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#e5c275]", "tw:rounded-[8px]", "tw:text-[color:#684611]",
    "tw:bg-[color:#fff7df]", "tw:[background-image:none]", "tw:text-[.82rem]", "tw:[&_a]:ml-[auto]",
    "tw:[&_a]:text-[color:#165a9f]", "tw:[&_a]:font-[750]", "tw:[&_a]:[text-decoration:underline]",
  ].join(" "),
} as const;
