/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "arena_notification_bell": [
    "arena-notification-bell", "tw:relative", "tw:z-[6]", "tw:[&_>_button]:relative",
    "tw:[&_>_button]:grid", "tw:[&_>_button]:place-items-center", "tw:[&_>_button]:w-[30px]", "tw:[&_>_button]:h-[30px]",
    "tw:[&_>_button]:border-t-[length:1px]", "tw:[&_>_button]:[border-top-style:solid]", "tw:[&_>_button]:border-t-[color:rgb(255_255_255_/_.34)]", "tw:[&_>_button]:border-r-[length:1px]",
    "tw:[&_>_button]:[border-right-style:solid]", "tw:[&_>_button]:border-r-[color:rgb(255_255_255_/_.34)]", "tw:[&_>_button]:border-b-[length:1px]", "tw:[&_>_button]:[border-bottom-style:solid]",
    "tw:[&_>_button]:border-b-[color:rgb(255_255_255_/_.34)]", "tw:[&_>_button]:border-l-[length:1px]", "tw:[&_>_button]:[border-left-style:solid]", "tw:[&_>_button]:border-l-[color:rgb(255_255_255_/_.34)]",
    "tw:[&_>_button]:rounded-[var(--radius-control)]", "tw:[&_>_button]:bg-[color:rgb(9_54_108_/_.36)]", "tw:[&_>_button]:[background-image:none]", "tw:[&_>_button]:text-[color:#d9f0ff]",
    "tw:[&_>_button]:text-[.93rem]", "tw:[&_>_button]:cursor-pointer", "tw:[&_>_button:hover]:bg-[color:rgb(25_111_187_/_.56)]", "tw:[&_>_button:hover]:[background-image:none]",
    "tw:[&_>_button_b]:absolute", "tw:[&_>_button_b]:top-[-6px]", "tw:[&_>_button_b]:right-[-7px]", "tw:[&_>_button_b]:min-w-[16px]",
    "tw:[&_>_button_b]:pt-[1px]", "tw:[&_>_button_b]:pr-[4px]", "tw:[&_>_button_b]:pb-[1px]", "tw:[&_>_button_b]:pl-[4px]",
    "tw:[&_>_button_b]:border-t-[length:2px]", "tw:[&_>_button_b]:[border-top-style:solid]", "tw:[&_>_button_b]:border-t-[color:#195b9f]", "tw:[&_>_button_b]:border-r-[length:2px]",
    "tw:[&_>_button_b]:[border-right-style:solid]", "tw:[&_>_button_b]:border-r-[color:#195b9f]", "tw:[&_>_button_b]:border-b-[length:2px]", "tw:[&_>_button_b]:[border-bottom-style:solid]",
    "tw:[&_>_button_b]:border-b-[color:#195b9f]", "tw:[&_>_button_b]:border-l-[length:2px]", "tw:[&_>_button_b]:[border-left-style:solid]", "tw:[&_>_button_b]:border-l-[color:#195b9f]",
    "tw:[&_>_button_b]:rounded-[99px]", "tw:[&_>_button_b]:bg-[color:#ef4e57]", "tw:[&_>_button_b]:[background-image:none]", "tw:[&_>_button_b]:text-[color:#fff]",
    "tw:[&_>_button_b]:text-[.6rem]", "tw:[&_>_button_b]:leading-[1.15]",
  ].join(" "),
  "arena_notification_panel": [
    "arena-notification-panel", "tw:absolute", "tw:top-[38px]", "tw:right-[0]",
    "tw:grid", "tw:w-[min(330px,_calc(100vw_-_34px))]", "tw:max-h-[380px]", "tw:[overflow-x:auto]",
    "tw:[overflow-y:auto]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#b7d4e6]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#b7d4e6]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#b7d4e6]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#b7d4e6]", "tw:rounded-[10px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[box-shadow:0_18px_40px_rgb(13_55_88_/_.25)]", "tw:text-[color:#163a5b]", "tw:[&_header]:flex", "tw:[&_header]:justify-between",
    "tw:[&_header]:gap-y-[12px]", "tw:[&_header]:gap-x-[12px]", "tw:[&_header]:pt-[11px]", "tw:[&_header]:pr-[13px]",
    "tw:[&_header]:pb-[11px]", "tw:[&_header]:pl-[13px]", "tw:[&_header]:border-b-[length:1px]", "tw:[&_header]:[border-bottom-style:solid]",
    "tw:[&_header]:border-b-[color:#dce9f0]", "tw:[&_header]:text-[color:#143c5d]", "tw:[&_header]:text-[.78rem]", "tw:[&_header]:items-start",
    "tw:[&_header_span]:text-[color:#466783]", "tw:[&_header_span]:text-[.68rem]", "tw:[&_a]:grid", "tw:[&_a]:gap-y-[4px]",
    "tw:[&_a]:gap-x-[4px]", "tw:[&_a]:pt-[10px]", "tw:[&_a]:pr-[13px]", "tw:[&_a]:pb-[10px]",
    "tw:[&_a]:pl-[13px]", "tw:[&_a]:border-b-[length:1px]", "tw:[&_a]:[border-bottom-style:solid]", "tw:[&_a]:border-b-[color:#edf3f7]",
    "tw:[&_a]:text-[color:#163a5b]", "tw:[&_a]:[text-decoration:none]", "tw:[&_a]:bg-[color:#fff]", "tw:[&_a]:[background-image:none]",
    "tw:[&_a:hover]:bg-[color:#eff8fc]", "tw:[&_a:hover]:[background-image:none]", "tw:[&_a_strong]:text-[.72rem]", "tw:[&_a_strong]:text-[color:#123b63]",
    "tw:[&_a_strong]:font-[800]", "tw:[&_a_strong]:leading-[1.3]", "tw:[&_a_span]:mt-[0]", "tw:[&_a_span]:mr-[0]",
    "tw:[&_a_span]:mb-[0]", "tw:[&_a_span]:ml-[0]", "tw:[&_a_span]:text-[color:#365773]", "tw:[&_a_span]:text-[.67rem]",
    "tw:[&_a_span]:leading-[1.45]", "tw:[&_a_span]:font-[600]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#365773]", "tw:[&_p]:text-[.7rem]",
    "tw:[&_p]:leading-[1.4]", "tw:[&_p]:pt-[15px]", "tw:[&_p]:pr-[13px]", "tw:[&_p]:pb-[15px]",
    "tw:[&_p]:pl-[13px]", "tw:[&_p]:font-[600]", "tw:[&_header_>_div]:grid", "tw:[&_header_>_div]:gap-y-[3px]",
    "tw:[&_header_>_div]:gap-x-[3px]", "tw:[&_header_button]:min-h-[28px]", "tw:[&_header_button]:pt-[5px]", "tw:[&_header_button]:pr-[8px]",
    "tw:[&_header_button]:pb-[5px]", "tw:[&_header_button]:pl-[8px]", "tw:[&_header_button]:border-t-[length:1px]", "tw:[&_header_button]:[border-top-style:solid]",
    "tw:[&_header_button]:border-t-[color:#c8d7e9]", "tw:[&_header_button]:border-r-[length:1px]", "tw:[&_header_button]:[border-right-style:solid]", "tw:[&_header_button]:border-r-[color:#c8d7e9]",
    "tw:[&_header_button]:border-b-[length:1px]", "tw:[&_header_button]:[border-bottom-style:solid]", "tw:[&_header_button]:border-b-[color:#c8d7e9]", "tw:[&_header_button]:border-l-[length:1px]",
    "tw:[&_header_button]:[border-left-style:solid]", "tw:[&_header_button]:border-l-[color:#c8d7e9]", "tw:[&_header_button]:rounded-[6px]", "tw:[&_header_button]:bg-[color:#f7faff]",
    "tw:[&_header_button]:[background-image:none]", "tw:[&_header_button]:text-[color:#1d5b9f]", "tw:[&_header_button]:[font:inherit]", "tw:[&_header_button]:text-[.66rem]",
    "tw:[&_header_button]:font-[600]", "tw:[&_header_button]:cursor-pointer", "tw:[&_header_button:hover]:border-t-[color:#3980d3]", "tw:[&_header_button:hover]:border-r-[color:#3980d3]",
    "tw:[&_header_button:hover]:border-b-[color:#3980d3]", "tw:[&_header_button:hover]:border-l-[color:#3980d3]", "tw:[&_header_button:hover]:bg-[color:#eaf3ff]", "tw:[&_header_button:hover]:[background-image:none]",
    "tw:[&_header_button:disabled]:opacity-[.6]", "tw:[&_header_button:disabled]:cursor-wait", "tw:[&_header_>_div_>_strong]:text-[.74rem]", "tw:[&_header_>_div_>_strong]:font-[600]",
    "tw:[&_header_>_div_>_strong]:tracking-[0]",
  ].join(" "),
} as const;
