/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "side_nav": [
    "side-nav", "tw:grid", "tw:gap-y-[17px]", "tw:gap-x-[17px]",
    "tw:[&_.nav-link-cash]:text-[color:#fff]", "tw:[&_.nav-link-cash]:bg-[color:#118750]", "tw:[&_.nav-link-cash]:[background-image:none]", "tw:[&_.nav-link-cash]:border-t-[color:#118750]",
    "tw:[&_.nav-link-cash]:border-r-[color:#118750]", "tw:[&_.nav-link-cash]:border-b-[color:#118750]", "tw:[&_.nav-link-cash]:border-l-[color:#118750]", "tw:[&_.nav-link-cash]:font-[750]",
    "tw:[&_.nav-link-cash.nav-link-active]:text-[color:#fff]", "tw:[&_.nav-link-cash.nav-link-active]:bg-[color:#118750]", "tw:[&_.nav-link-cash.nav-link-active]:[background-image:none]", "tw:[&_.nav-link-cash.nav-link-active]:border-t-[color:#118750]",
    "tw:[&_.nav-link-cash.nav-link-active]:border-r-[color:#118750]", "tw:[&_.nav-link-cash.nav-link-active]:border-b-[color:#118750]", "tw:[&_.nav-link-cash.nav-link-active]:border-l-[color:#118750]", "tw:[&_.nav-link-cash.nav-link-active]:font-[750]",
    "tw:[&_.nav-link-cash:hover]:text-[color:#fff]", "tw:[&_.nav-link-cash:hover]:bg-[color:#0c7040]", "tw:[&_.nav-link-cash:hover]:[background-image:none]", "tw:[&_.nav-link-cash:hover]:border-t-[color:#0c7040]",
    "tw:[&_.nav-link-cash:hover]:border-r-[color:#0c7040]", "tw:[&_.nav-link-cash:hover]:border-b-[color:#0c7040]", "tw:[&_.nav-link-cash:hover]:border-l-[color:#0c7040]", "tw:[&_.nav-link-cash:focus-visible]:text-[color:#fff]",
    "tw:[&_.nav-link-cash:focus-visible]:bg-[color:#0c7040]", "tw:[&_.nav-link-cash:focus-visible]:[background-image:none]", "tw:[&_.nav-link-cash:focus-visible]:border-t-[color:#0c7040]", "tw:[&_.nav-link-cash:focus-visible]:border-r-[color:#0c7040]",
    "tw:[&_.nav-link-cash:focus-visible]:border-b-[color:#0c7040]", "tw:[&_.nav-link-cash:focus-visible]:border-l-[color:#0c7040]", "tw:[&_.nav-link-cash_.nav-icon]:text-[color:#fff]", "tw:[&_.nav-link-cash_.nav-icon]:bg-[color:rgb(255_255_255_/_.14)]",
    "tw:[&_.nav-link-cash_.nav-icon]:[background-image:none]", "tw:[&_.nav-link-cash_.nav-icon]:border-t-[color:rgb(255_255_255_/_.22)]", "tw:[&_.nav-link-cash_.nav-icon]:border-r-[color:rgb(255_255_255_/_.22)]", "tw:[&_.nav-link-cash_.nav-icon]:border-b-[color:rgb(255_255_255_/_.22)]",
    "tw:[&_.nav-link-cash_.nav-icon]:border-l-[color:rgb(255_255_255_/_.22)]",
  ].join(" "),
  "nav_group": [
    "nav-group", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
  ].join(" "),
  "nav_group_label": [
    "nav-group-label", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:pt-[0]", "tw:pr-[10px]", "tw:pb-[0]",
    "tw:pl-[10px]", "tw:text-[color:#92acd6]", "tw:text-[.62rem]", "tw:font-[500]",
    "tw:tracking-[.06em]", "tw:uppercase",
  ].join(" "),
  "nav_group_links": [
    "nav-group-links", "tw:grid", "tw:gap-y-[4px]", "tw:gap-x-[4px]",
  ].join(" "),
  "nav_link_block": [
    "nav-link-block", "tw:grid", "tw:gap-y-[4px]", "tw:gap-x-[4px]",
  ].join(" "),
  "nav_parent_row": [
    "nav-parent-row", "tw:min-w-[0]",
  ].join(" "),
  "nav_expandable_row": [
    "nav-expandable-row", "tw:flex", "tw:items-stretch", "tw:min-w-[0]",
    "tw:gap-y-[2px]", "tw:gap-x-[2px]",
  ].join(" "),
  "nav_link_nav_link_destination": [
    "nav-link", "nav-link-destination", "tw:flex", "tw:items-center",
    "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:min-h-[45px]", "tw:pt-[6px]",
    "tw:pr-[10px]", "tw:pb-[6px]", "tw:pl-[10px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:transparent]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:transparent]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:transparent]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:transparent]", "tw:rounded-[9px]",
    "tw:text-[color:#eaf2ff]", "tw:font-[700]", "tw:[transition:transform_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:text-[.84rem]",
    "tw:hover:border-t-[color:rgb(120_179_255_/_.32)]", "tw:hover:border-r-[color:rgb(120_179_255_/_.32)]", "tw:hover:border-b-[color:rgb(120_179_255_/_.32)]", "tw:hover:border-l-[color:rgb(120_179_255_/_.32)]",
    "tw:hover:bg-[color:rgb(38_115_206_/_.35)]", "tw:hover:[background-image:none]", "tw:hover:text-[color:#fff]", "tw:hover:[transform:translateY(-1px)]",
    "tw:[&:hover_.nav-icon]:border-t-[color:rgb(195_231_255_/_.42)]", "tw:[&:hover_.nav-icon]:border-r-[color:rgb(195_231_255_/_.42)]", "tw:[&:hover_.nav-icon]:border-b-[color:rgb(195_231_255_/_.42)]", "tw:[&:hover_.nav-icon]:border-l-[color:rgb(195_231_255_/_.42)]",
    "tw:[&:hover_.nav-icon]:bg-[color:rgb(255_255_255_/_.17)]", "tw:[&:hover_.nav-icon]:[background-image:none]", "tw:[&:hover_.nav-icon]:text-[color:#fff]", "tw:[&:hover_.nav-icon]:[transform:scale(1.04)]",
    "tw:[&:hover_.nav-icon_.nav-svg-whatsapp]:text-[color:#6df39a]", "tw:[flex:1_1_auto]", "tw:min-w-[0]",
  ].join(" "),
  "nav_link_active": [
    "nav-link-active", "tw:border-t-[color:rgb(83_158_255_/_.56)]", "tw:border-r-[color:rgb(83_158_255_/_.56)]", "tw:border-b-[color:rgb(83_158_255_/_.56)]",
    "tw:border-l-[color:rgb(83_158_255_/_.56)]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(135deg,_#0868e5,_#0754c3)]", "tw:[box-shadow:0_8px_18px_rgb(0_23_74_/_.28),_inset_0_1px_rgb(255_255_255_/_.12)]",
    "tw:text-[color:#fff]", "tw:font-[500]", "tw:[&_.nav-icon_.nav-svg-whatsapp]:text-[color:#6df39a]", "tw:[&_.nav-icon]:border-t-[color:rgb(255_255_255_/_.24)]",
    "tw:[&_.nav-icon]:border-r-[color:rgb(255_255_255_/_.24)]", "tw:[&_.nav-icon]:border-b-[color:rgb(255_255_255_/_.24)]", "tw:[&_.nav-icon]:border-l-[color:rgb(255_255_255_/_.24)]", "tw:[&_.nav-icon]:bg-[color:rgb(255_255_255_/_.2)]",
    "tw:[&_.nav-icon]:[background-image:none]", "tw:[&_.nav-icon]:text-[color:#fff]", "tw:[&_.nav-icon]:[box-shadow:inset_0_1px_rgb(255_255_255_/_.16),_0_4px_10px_rgb(0_20_62_/_.16)]",
  ].join(" "),
  "nav_icon": [
    "nav-icon", "tw:grid", "tw:place-items-center", "tw:w-[30px]",
    "tw:h-[30px]", "tw:rounded-[8px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_rgb(255_255_255_/_.13),_rgb(255_255_255_/_.06))]",
    "tw:text-[color:#edf6ff]", "tw:leading-[1]", "tw:[flex:0_0_30px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(190_223_255_/_.18)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:rgb(190_223_255_/_.18)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(190_223_255_/_.18)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(190_223_255_/_.18)]", "tw:[box-shadow:inset_0_1px_rgb(255_255_255_/_.08)]",
    "tw:[transition:color_.16s_ease,_border-color_.16s_ease,_background_.16s_ease,_transform_.16s_ease]", "tw:[&_svg]:w-[18px]", "tw:[&_svg]:h-[18px]", "tw:[&_svg]:[stroke-width:1.9]",
    "tw:[&_svg]:[vector-effect:non-scaling-stroke]", "tw:[&_svg]:[shape-rendering:geometricPrecision]", "tw:[&_.nav-svg-whatsapp]:text-[color:#49e179]", "tw:[&_.nav-svg-whatsapp]:[stroke-width:2.05]",
    "tw:[&_.nav-svg-whatsapp]:[filter:drop-shadow(0_1px_1px_rgb(0_21_35_/_.28))]",
  ].join(" "),
  "nav_toggle_nav_expand_toggle": [
    "nav-toggle", "nav-expand-toggle", "tw:grid", "tw:place-items-center",
    "tw:w-[34px]", "tw:h-[32px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:transparent]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:transparent]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:transparent]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:transparent]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:text-[color:rgba(245,_250,_255,_0.82)]", "tw:font-[800]", "tw:[transition:background_160ms_var(--ease-standard),_border-color_160ms_var(--ease-standard),_color_160ms_var(--ease-standard)]",
    "tw:hover:border-t-[color:rgba(255,_255,_255,_0.16)]", "tw:hover:border-r-[color:rgba(255,_255,_255,_0.16)]", "tw:hover:border-b-[color:rgba(255,_255,_255,_0.16)]", "tw:hover:border-l-[color:rgba(255,_255,_255,_0.16)]",
    "tw:hover:bg-[color:rgba(255,_255,_255,_0.14)]", "tw:hover:[background-image:none]", "tw:hover:text-[color:#ffffff]", "tw:[flex:0_0_34px]",
    "tw:min-h-[36px]", "tw:pt-[0]", "tw:pr-[0]", "tw:pb-[0]",
    "tw:pl-[0]", "tw:cursor-pointer", "tw:[&_.nav-chevron]:grid", "tw:[&_.nav-chevron]:place-items-center",
    "tw:[&_.nav-chevron]:[transition:transform_160ms_var(--ease-standard)]", "tw:[&_.nav-chevron-open]:[transform:rotate(90deg)]",
  ].join(" "),
  "nav_chevron": [
    "nav-chevron", "tw:grid", "tw:w-[18px]", "tw:h-[18px]",
    "tw:ml-[auto]", "tw:place-items-center", "tw:text-[color:#c3d8f7]", "tw:[transition:transform_.16s_ease]",
    "tw:[&_svg]:w-[15px]", "tw:[&_svg]:h-[15px]",
  ].join(" "),
  "nav_chevron_open": [
    "nav-chevron-open", "tw:[transform:rotate(180deg)]",
  ].join(" "),
  "nav_link": [
    "nav-link", "tw:flex", "tw:items-center", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]", "tw:min-h-[45px]", "tw:pt-[6px]", "tw:pr-[10px]",
    "tw:pb-[6px]", "tw:pl-[10px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:transparent]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:transparent]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:transparent]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:transparent]", "tw:rounded-[9px]", "tw:text-[color:#eaf2ff]",
    "tw:font-[700]", "tw:[transition:transform_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:text-[.84rem]", "tw:hover:border-t-[color:rgb(120_179_255_/_.32)]",
    "tw:hover:border-r-[color:rgb(120_179_255_/_.32)]", "tw:hover:border-b-[color:rgb(120_179_255_/_.32)]", "tw:hover:border-l-[color:rgb(120_179_255_/_.32)]", "tw:hover:bg-[color:rgb(38_115_206_/_.35)]",
    "tw:hover:[background-image:none]", "tw:hover:text-[color:#fff]", "tw:hover:[transform:translateY(-1px)]", "tw:[&:hover_.nav-icon]:border-t-[color:rgb(195_231_255_/_.42)]",
    "tw:[&:hover_.nav-icon]:border-r-[color:rgb(195_231_255_/_.42)]", "tw:[&:hover_.nav-icon]:border-b-[color:rgb(195_231_255_/_.42)]", "tw:[&:hover_.nav-icon]:border-l-[color:rgb(195_231_255_/_.42)]", "tw:[&:hover_.nav-icon]:bg-[color:rgb(255_255_255_/_.17)]",
    "tw:[&:hover_.nav-icon]:[background-image:none]", "tw:[&:hover_.nav-icon]:text-[color:#fff]", "tw:[&:hover_.nav-icon]:[transform:scale(1.04)]", "tw:[&:hover_.nav-icon_.nav-svg-whatsapp]:text-[color:#6df39a]",
  ].join(" "),
  "nav_submenu": [
    "nav-submenu", "tw:hidden", "tw:gap-y-[2px]", "tw:gap-x-[2px]",
    "tw:ml-[23px]", "tw:pl-[14px]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgb(136_183_247_/_.26)]", "tw:mt-[3px]", "tw:mr-[0]", "tw:mb-[2px]",
    "tw:pt-[2px]", "tw:pr-[0]", "tw:pb-[2px]",
  ].join(" "),
  "nav_submenu_open": [
    "nav-submenu-open", "tw:grid",
  ].join(" "),
  "nav_expandable_row_nav_expandable_row_nested": [
    "nav-expandable-row", "nav-expandable-row-nested", "tw:flex", "tw:items-stretch",
    "tw:min-w-[0]", "tw:gap-y-[2px]", "tw:gap-x-[2px]", "tw:[&_.nav-expand-toggle]:[flex-basis:30px]",
    "tw:[&_.nav-expand-toggle]:w-[30px]", "tw:[&_.nav-expand-toggle]:min-h-[30px]",
  ].join(" "),
  "nav_sub_link_nav_sub_link_destination": [
    "nav-sub-link", "nav-sub-link-destination", "tw:flex", "tw:items-center",
    "tw:min-h-[28px]", "tw:pt-[5px]", "tw:pr-[8px]", "tw:pb-[5px]",
    "tw:pl-[8px]", "tw:rounded-[var(--radius-control)]", "tw:text-[color:#bcd0ef]", "tw:text-[.74rem]",
    "tw:font-[650]", "tw:[transition:background_160ms_var(--ease-standard),_color_160ms_var(--ease-standard),_transform_160ms_var(--ease-standard)]", "tw:relative", "tw:hover:bg-[color:transparent]",
    "tw:hover:[background-image:none]", "tw:hover:text-[color:#fff]", "tw:hover:[transform:translateX(1px)]", "tw:[&:not(.nav-sub-link-parent)::before]:[content:'']",
    "tw:[&:not(.nav-sub-link-parent)::before]:absolute", "tw:[&:not(.nav-sub-link-parent)::before]:left-[-19px]", "tw:[&:not(.nav-sub-link-parent)::before]:top-[50%]", "tw:[&:not(.nav-sub-link-parent)::before]:w-[4px]",
    "tw:[&:not(.nav-sub-link-parent)::before]:h-[4px]", "tw:[&:not(.nav-sub-link-parent)::before]:rounded-[50%]", "tw:[&:not(.nav-sub-link-parent)::before]:bg-[color:currentColor]", "tw:[&:not(.nav-sub-link-parent)::before]:[background-image:none]",
    "tw:[&:not(.nav-sub-link-parent)::before]:[transform:translateY(-50%)]", "tw:[flex:1_1_auto]", "tw:min-w-[0]",
  ].join(" "),
  "nav_sub_link_active": [
    "nav-sub-link-active", "tw:text-[color:#fff]", "tw:bg-[color:transparent]", "tw:[background-image:none]",
  ].join(" "),
  "nav_submenu_nav_submenu_nested": [
    "nav-submenu", "nav-submenu-nested", "tw:hidden", "tw:gap-y-[2px]",
    "tw:gap-x-[2px]", "tw:ml-[5px]", "tw:pl-[14px]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(136_183_247_/_.26)]", "tw:mt-[3px]", "tw:mr-[0]",
    "tw:mb-[2px]", "tw:pt-[2px]", "tw:pr-[0]", "tw:pb-[2px]",
  ].join(" "),
  "nav_sub_link_nav_sub_link_nested": [
    "nav-sub-link", "nav-sub-link-nested", "tw:flex", "tw:items-center",
    "tw:min-h-[28px]", "tw:pt-[5px]", "tw:pr-[8px]", "tw:pb-[5px]",
    "tw:pl-[8px]", "tw:rounded-[var(--radius-control)]", "tw:text-[color:#bcd0ef]", "tw:text-[.74rem]",
    "tw:font-[650]", "tw:[transition:background_160ms_var(--ease-standard),_color_160ms_var(--ease-standard),_transform_160ms_var(--ease-standard)]", "tw:relative", "tw:hover:bg-[color:transparent]",
    "tw:hover:[background-image:none]", "tw:hover:text-[color:#fff]", "tw:hover:[transform:translateX(1px)]", "tw:[&:not(.nav-sub-link-parent)::before]:[content:'']",
    "tw:[&:not(.nav-sub-link-parent)::before]:absolute", "tw:[&:not(.nav-sub-link-parent)::before]:left-[-19px]", "tw:[&:not(.nav-sub-link-parent)::before]:top-[50%]", "tw:[&:not(.nav-sub-link-parent)::before]:w-[4px]",
    "tw:[&:not(.nav-sub-link-parent)::before]:h-[4px]", "tw:[&:not(.nav-sub-link-parent)::before]:rounded-[50%]", "tw:[&:not(.nav-sub-link-parent)::before]:bg-[color:currentColor]", "tw:[&:not(.nav-sub-link-parent)::before]:[background-image:none]",
    "tw:[&:not(.nav-sub-link-parent)::before]:[transform:translateY(-50%)]", "tw:[padding-block:5px]",
  ].join(" "),
  "nav_sub_link": [
    "nav-sub-link", "tw:flex", "tw:items-center", "tw:min-h-[28px]",
    "tw:pt-[5px]", "tw:pr-[8px]", "tw:pb-[5px]", "tw:pl-[8px]",
    "tw:rounded-[var(--radius-control)]", "tw:text-[color:#bcd0ef]", "tw:text-[.74rem]", "tw:font-[650]",
    "tw:[transition:background_160ms_var(--ease-standard),_color_160ms_var(--ease-standard),_transform_160ms_var(--ease-standard)]", "tw:relative", "tw:hover:bg-[color:transparent]", "tw:hover:[background-image:none]",
    "tw:hover:text-[color:#fff]", "tw:hover:[transform:translateX(1px)]", "tw:[&:not(.nav-sub-link-parent)::before]:[content:'']", "tw:[&:not(.nav-sub-link-parent)::before]:absolute",
    "tw:[&:not(.nav-sub-link-parent)::before]:left-[-19px]", "tw:[&:not(.nav-sub-link-parent)::before]:top-[50%]", "tw:[&:not(.nav-sub-link-parent)::before]:w-[4px]", "tw:[&:not(.nav-sub-link-parent)::before]:h-[4px]",
    "tw:[&:not(.nav-sub-link-parent)::before]:rounded-[50%]", "tw:[&:not(.nav-sub-link-parent)::before]:bg-[color:currentColor]", "tw:[&:not(.nav-sub-link-parent)::before]:[background-image:none]", "tw:[&:not(.nav-sub-link-parent)::before]:[transform:translateY(-50%)]",
  ].join(" "),
} as const;
