import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "product_management_stack_md": sharedUtilities.productManagementStackMd,
  "product_management_header": sharedUtilities.productManagementHeader,
  "product_management_actions": [
    "product-management-actions", "tw:flex", "tw:flex-wrap", "tw:justify-end",
    "tw:viewport-620:justify-start", "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:[&_.button]:min-h-[36px]",
    "tw:[&_.button:disabled]:cursor-not-allowed", "tw:[&_.button:disabled]:opacity-[.55]",
  ].join(" "),
  "button_button_small_button_import": [
    "button", "button-small", "button-import", "tw:inline-flex",
    "tw:items-center", "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:min-h-[30px]", "tw:pt-[5px]", "tw:pr-[8px]", "tw:pb-[5px]",
    "tw:pl-[8px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]",
    "tw:text-[color:var(--text)]", "tw:text-[.72rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--line-strong)]",
    "tw:hover:border-r-[color:var(--line-strong)]", "tw:hover:border-b-[color:var(--line-strong)]", "tw:hover:border-l-[color:var(--line-strong)]", "tw:hover:[transform:translateY(-1px)]",
    "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]",
    "tw:[&:active]:[box-shadow:none]",
  ].join(" "),
  "button_button_small_button_import_csv": [
    "button", "button-small", "button-import-csv", "tw:inline-flex",
    "tw:items-center", "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:min-h-[30px]", "tw:pt-[5px]", "tw:pr-[8px]", "tw:pb-[5px]",
    "tw:pl-[8px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]",
    "tw:text-[color:var(--text)]", "tw:text-[.72rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--line-strong)]",
    "tw:hover:border-r-[color:var(--line-strong)]", "tw:hover:border-b-[color:var(--line-strong)]", "tw:hover:border-l-[color:var(--line-strong)]", "tw:hover:[transform:translateY(-1px)]",
    "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]",
    "tw:[&:active]:[box-shadow:none]",
  ].join(" "),
  "button_button_small_button_primary": sharedUtilities.buttonButtonSmallButtonPrimary,
  "product_management_filters": [
    "product-management-filters", "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]",
    "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[10px]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]",
    "tw:[&_>_header]:flex", "tw:[&_>_header]:items-center", "tw:viewport-620:[&_>_header]:items-start", "tw:[&_>_header]:justify-between",
    "tw:[&_>_header]:gap-y-[12px]", "tw:[&_>_header]:gap-x-[12px]", "tw:[&_>_header]:mb-[12px]", "tw:[&_>_header_strong]:text-[.9rem]",
    "tw:[&_>_header_div]:flex", "tw:[&_>_header_div]:gap-y-[7px]", "tw:[&_>_header_div]:gap-x-[7px]", "tw:[&_>_div]:grid",
    "tw:[&_>_div]:grid-cols-[repeat(5,_minmax(130px,_1fr))]", "tw:viewport-920:[&_>_div]:grid-cols-[repeat(3,_minmax(140px,_1fr))]", "tw:viewport-620:[&_>_div]:grid-cols-[1fr]", "tw:[&_>_div]:gap-y-[10px]",
    "tw:[&_>_div]:gap-x-[10px]", "tw:[&_>_div]:[align-items:end]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[5px]",
    "tw:[&_label]:gap-x-[5px]", "tw:[&_label]:text-[color:var(--muted)]", "tw:[&_label]:text-[.73rem]", "tw:[&_label]:font-[750]",
    "tw:[&_.control-toggle]:flex", "tw:[&_.control-toggle]:[align-self:end]", "tw:[&_.control-toggle]:min-h-[var(--control-height)]", "tw:viewport-620:[&_>_header]:flex-col",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "product_list_head": [
    "product-list-head", "tw:grid", "tw:grid-cols-[minmax(210px,_1.4fr)_minmax(130px,_.8fr)_minmax(100px,_.6fr)_minmax(100px,_.6fr)_auto]", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:items-center", "tw:pt-[0]", "tw:pr-[13px]",
    "tw:pb-[8px]", "tw:pl-[13px]", "tw:text-[color:var(--muted)]", "tw:text-[.68rem]",
    "tw:font-[800]", "tw:tracking-[.03em]", "tw:uppercase",
  ].join(" "),
  "product_list": [
    "product-list", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[10px]",
    "tw:bg-[color:var(--panel)]", "tw:[background-image:none]",
  ].join(" "),
  "product_row": [
    "product-row", "tw:grid", "tw:grid-cols-[minmax(210px,_1.4fr)_minmax(130px,_.8fr)_minmax(100px,_.6fr)_minmax(100px,_.6fr)_auto]", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:items-center", "tw:min-h-[62px]", "tw:pt-[10px]",
    "tw:pr-[13px]", "tw:pb-[10px]", "tw:pl-[13px]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:text-[color:var(--text)]", "tw:text-[.8rem]",
    "tw:[&:last-child]:border-b-[length:0]", "tw:[&:last-child]:[border-bottom-style:none]", "tw:[&:last-child]:border-b-[color:currentColor]",
  ].join(" "),
  "product_table_link": [
    "product-table-link", "tw:grid", "tw:gap-y-[2px]", "tw:gap-x-[2px]",
    "tw:text-[color:inherit]", "tw:[text-decoration:none]", "tw:[&_strong]:text-[color:var(--brand-strong)]", "tw:[&:hover_strong]:[text-decoration:underline]",
    "tw:[&_span]:text-[color:var(--muted)]", "tw:[&_span]:text-[.68rem]",
  ].join(" "),
  "stock_alert": [
    "stock-alert", "tw:inline-flex", "tw:items-center", "tw:min-h-[30px]",
    "tw:pt-[0]", "tw:pr-[10px]", "tw:pb-[0]", "tw:pl-[10px]",
    "tw:rounded-[999px]", "tw:text-[0.86rem]", "tw:font-[700]", "tw:bg-[color:rgba(191,_63,_56,_0.1)]",
    "tw:[background-image:none]", "tw:text-[color:var(--danger)]",
  ].join(" "),
  "client_empty": sharedUtilities.clientEmpty,
} as const;
