import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "sponsorship_searchable_select": [
    "sponsorship-searchable-select", "tw:relative", "tw:[&_>_span]:text-[color:#58708f]", "tw:[&_>_span]:text-[.73rem]",
    "tw:[&_>_span]:font-[750]",
  ].join(" "),
  "sponsorship_filter_options": [
    "sponsorship-filter-options", "tw:absolute", "tw:z-[12]", "tw:top-[calc(100%_+_4px)]",
    "tw:right-[0]", "tw:left-[0]", "tw:grid", "tw:max-h-[190px]",
    "tw:[overflow-y:auto]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#bfd2e6]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#bfd2e6]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#bfd2e6]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#bfd2e6]", "tw:rounded-[9px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[box-shadow:0_12px_24px_rgb(16_52_91_/_.18)]", "tw:[&_button]:w-[100%]", "tw:[&_button]:pt-[9px]", "tw:[&_button]:pr-[10px]",
    "tw:[&_button]:pb-[9px]", "tw:[&_button]:pl-[10px]", "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]",
    "tw:[&_button]:border-t-[color:currentColor]", "tw:[&_button]:border-r-[length:0]", "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]",
    "tw:[&_button]:border-b-[length:1px]", "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:#edf2f7]", "tw:[&_button]:border-l-[length:0]",
    "tw:[&_button]:[border-left-style:none]", "tw:[&_button]:border-l-[color:currentColor]", "tw:[&_button]:bg-[color:#fff]", "tw:[&_button]:[background-image:none]",
    "tw:[&_button]:text-[color:#26476d]", "tw:[&_button]:[font:inherit]", "tw:[&_button]:text-[.8rem]", "tw:[&_button]:text-left",
    "tw:[&_button]:cursor-pointer", "tw:[&_span]:w-[100%]", "tw:[&_span]:pt-[9px]", "tw:[&_span]:pr-[10px]",
    "tw:[&_span]:pb-[9px]", "tw:[&_span]:pl-[10px]", "tw:[&_span]:border-t-[length:0]", "tw:[&_span]:[border-top-style:none]",
    "tw:[&_span]:border-t-[color:currentColor]", "tw:[&_span]:border-r-[length:0]", "tw:[&_span]:[border-right-style:none]", "tw:[&_span]:border-r-[color:currentColor]",
    "tw:[&_span]:border-b-[length:1px]", "tw:[&_span]:[border-bottom-style:solid]", "tw:[&_span]:border-b-[color:#edf2f7]", "tw:[&_span]:border-l-[length:0]",
    "tw:[&_span]:[border-left-style:none]", "tw:[&_span]:border-l-[color:currentColor]", "tw:[&_span]:bg-[color:#fff]", "tw:[&_span]:[background-image:none]",
    "tw:[&_span]:text-[color:#26476d]", "tw:[&_span]:[font:inherit]", "tw:[&_span]:text-[.8rem]", "tw:[&_span]:text-left",
    "tw:[&_span]:cursor-pointer", "tw:[&_button:hover]:bg-[color:#eef6ff]", "tw:[&_button:hover]:[background-image:none]", "tw:[&_button:hover]:text-[color:#155cae]",
    "tw:[&_button[aria-selected=true]]:bg-[color:#eef6ff]", "tw:[&_button[aria-selected=true]]:[background-image:none]", "tw:[&_button[aria-selected=true]]:text-[color:#155cae]",
  ].join(" "),
  "sponsorship_filter_form": [
    "sponsorship-filter-form", "tw:flex", "tw:viewport-760:grid", "tw:[flex:1]",
    "tw:flex-wrap", "tw:items-end", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
    "tw:[&_label]:grid", "tw:[&_label]:min-w-[150px]", "tw:[&_label]:[flex:1_1_160px]", "tw:[&_label]:gap-y-[5px]",
    "tw:[&_label]:gap-x-[5px]", "tw:[&_label]:text-[color:#58708f]", "tw:[&_label]:text-[.73rem]", "tw:[&_label]:font-[750]",
    "tw:[&_input]:min-h-[36px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[10px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[10px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#cbd9e8]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#cbd9e8]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:#cbd9e8]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:#cbd9e8]", "tw:[&_input]:rounded-[8px]", "tw:[&_input]:bg-[color:#fff]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:text-[color:#17345e]", "tw:[&_input]:[font:inherit]", "tw:[&_select]:min-h-[36px]", "tw:[&_select]:pt-[0]",
    "tw:[&_select]:pr-[10px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[10px]", "tw:[&_select]:border-t-[length:1px]",
    "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:#cbd9e8]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]",
    "tw:[&_select]:border-r-[color:#cbd9e8]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:#cbd9e8]",
    "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#cbd9e8]", "tw:[&_select]:rounded-[8px]",
    "tw:[&_select]:bg-[color:#fff]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:#17345e]", "tw:[&_select]:[font:inherit]",
    "tw:viewport-760:grid-cols-[1fr]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
} as const;
