import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "sponsorship_dialog_backdrop": [
    "sponsorship-dialog-backdrop", "tw:fixed", "tw:z-[300]", "tw:top-[0]",
    "tw:right-[0]", "tw:bottom-[0]", "tw:left-[0]", "tw:grid",
    "tw:place-items-center", "tw:pt-[20px]", "tw:viewport-640:pt-[12px]", "tw:pr-[20px]",
    "tw:viewport-640:pr-[12px]", "tw:pb-[20px]", "tw:viewport-640:pb-[12px]", "tw:pl-[20px]",
    "tw:viewport-640:pl-[12px]", "tw:bg-[color:rgb(8_27_48_/_.48)]", "tw:[background-image:none]",
  ].join(" "),
  "sponsorship_dialog": [
    "sponsorship-dialog", "tw:w-[min(100%,_720px)]", "tw:max-h-[min(720px,_calc(100dvh_-_40px))]", "tw:viewport-640:max-h-[calc(100dvh_-_24px)]",
    "tw:[overflow-x:auto]", "tw:[overflow-y:auto]", "tw:pt-[20px]", "tw:viewport-640:pt-[16px]",
    "tw:pr-[20px]", "tw:viewport-640:pr-[16px]", "tw:pb-[20px]", "tw:viewport-640:pb-[16px]",
    "tw:pl-[20px]", "tw:viewport-640:pl-[16px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#cbd9e8]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#cbd9e8]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#cbd9e8]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#cbd9e8]", "tw:rounded-[16px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[box-shadow:0_20px_56px_rgb(9_35_67_/_.3)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:items-center",
    "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[16px]", "tw:[&_>_header]:gap-x-[16px]", "tw:[&_>_header]:mb-[18px]",
    "tw:[&_>_header]:pb-[13px]", "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#e2ebf4]",
    "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]",
    "tw:[&_h2]:text-[color:#132d58]", "tw:[&_h2]:text-[1.08rem]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "grid_form_sponsorship_dialog_form": [
    "grid-form", "sponsorship-dialog-form", "tw:grid", "tw:gap-y-[14px]",
    "tw:gap-x-[14px]", "tw:grid-cols-[repeat(3,_minmax(0,_1fr))]", "tw:viewport-1120:grid-cols-[1fr]", "tw:[&_textarea]:w-[100%]",
    "tw:[&_textarea]:pt-[12px]", "tw:[&_textarea]:pr-[14px]", "tw:[&_textarea]:pb-[12px]", "tw:[&_textarea]:pl-[14px]",
    "tw:[&_textarea]:border-t-[length:1px]", "tw:[&_textarea]:[border-top-style:solid]", "tw:[&_textarea]:border-t-[color:var(--line)]", "tw:[&_textarea]:border-r-[length:1px]",
    "tw:[&_textarea]:[border-right-style:solid]", "tw:[&_textarea]:border-r-[color:var(--line)]", "tw:[&_textarea]:border-b-[length:1px]", "tw:[&_textarea]:[border-bottom-style:solid]",
    "tw:[&_textarea]:border-b-[color:var(--line)]", "tw:[&_textarea]:border-l-[length:1px]", "tw:[&_textarea]:[border-left-style:solid]", "tw:[&_textarea]:border-l-[color:var(--line)]",
    "tw:[&_textarea]:rounded-[var(--radius-md)]", "tw:[&_textarea]:bg-[color:var(--panel)]", "tw:[&_textarea]:[background-image:none]", "tw:[&_textarea]:text-[color:var(--text)]",
  ].join(" "),
  "field": sharedUtilities.field,
  "sponsor_benefit_options_form_full": [
    "sponsor-benefit-options", "form-full", "tw:flex", "tw:flex-wrap",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:mt-[0]", "tw:mr-[0]",
    "tw:mb-[0]", "tw:ml-[0]", "tw:pt-[0]", "tw:pr-[0]",
    "tw:pb-[0]", "tw:pl-[0]", "tw:border-t-[length:0]", "tw:[border-top-style:none]",
    "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:[&_legend]:w-[100%]", "tw:[&_legend]:mb-[3px]",
    "tw:[&_legend]:text-[.76rem]", "tw:[&_legend]:font-[750]", "tw:[&_label]:inline-flex", "tw:[&_label]:items-center",
    "tw:[&_label]:gap-y-[5px]", "tw:[&_label]:gap-x-[5px]", "tw:[&_label]:pt-[5px]", "tw:[&_label]:pr-[8px]",
    "tw:[&_label]:pb-[5px]", "tw:[&_label]:pl-[8px]", "tw:[&_label]:border-t-[length:1px]", "tw:[&_label]:[border-top-style:solid]",
    "tw:[&_label]:border-t-[color:var(--border)]", "tw:[&_label]:border-r-[length:1px]", "tw:[&_label]:[border-right-style:solid]", "tw:[&_label]:border-r-[color:var(--border)]",
    "tw:[&_label]:border-b-[length:1px]", "tw:[&_label]:[border-bottom-style:solid]", "tw:[&_label]:border-b-[color:var(--border)]", "tw:[&_label]:border-l-[length:1px]",
    "tw:[&_label]:[border-left-style:solid]", "tw:[&_label]:border-l-[color:var(--border)]", "tw:[&_label]:rounded-[999px]", "tw:[&_label]:bg-[color:var(--surface)]",
    "tw:[&_label]:[background-image:none]", "tw:[&_label]:text-[color:var(--muted)]", "tw:[&_label]:text-[.7rem]", "tw:[&_label]:font-[700]",
    "tw:[&_input]:w-[auto]", "tw:[&_input]:mt-[0]", "tw:[&_input]:mr-[0]", "tw:[&_input]:mb-[0]",
    "tw:[&_input]:ml-[0]", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  "sponsorship_dialog_actions_form_full": [
    "sponsorship-dialog-actions", "form-full", "tw:flex", "tw:justify-end",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:mt-[4px]", "tw:viewport-640:items-stretch",
    "tw:viewport-640:[flex-direction:column-reverse]", "tw:viewport-640:[&_.button]:w-[100%]", "tw:viewport-640:[&_.button]:justify-center", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  "button": sharedUtilities.button,
  "button_button_primary_button_small": sharedUtilities.buttonButtonPrimaryButtonSmall,
  "field_form_full": sharedUtilities.fieldFormFull,
  "field_form_full_sponsor_client_search": [
    "field", "form-full", "sponsor-client-search", "tw:grid",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]",
    "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]",
    "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[14px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]",
    "tw:[&_input]:border-t-[color:var(--line)]", "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]",
    "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]",
    "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]",
    "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:var(--text)]", "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]",
    "tw:[&_select]:min-h-[44px]", "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]",
    "tw:[&_select]:pl-[14px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]",
    "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]",
    "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]",
    "tw:[&_select]:border-l-[color:var(--line)]", "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]",
    "tw:[&_select]:text-[color:var(--text)]", "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]",
    "tw:[&_input:focus]:[transform:translateY(-1px)]", "tw:[&_select:focus]:[outline:none]", "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]",
    "tw:[&_input[type=file]]:pt-[10px]", "tw:[&_input[type=file]]:pr-[14px]", "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]",
    "tw:[&_input[type=checkbox]]:w-[auto]", "tw:[&_input[type=checkbox]]:min-h-[auto]", "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]",
    "tw:[&_input[type=checkbox]]:pb-[0]", "tw:[&_input[type=checkbox]]:pl-[0]", "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]",
    "tw:[&_input[type=radio]]:pt-[0]", "tw:[&_input[type=radio]]:pr-[0]", "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]",
    "tw:[grid-column:1_/_-1]", "tw:relative",
  ].join(" "),
  "sponsor_client_options": [
    "sponsor-client-options", "tw:absolute", "tw:z-[3]", "tw:top-[calc(100%_-_22px)]",
    "tw:right-[0]", "tw:left-[0]", "tw:grid", "tw:max-h-[210px]",
    "tw:[overflow-x:auto]", "tw:[overflow-y:auto]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#bfd2e6]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#bfd2e6]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#bfd2e6]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#bfd2e6]", "tw:rounded-[9px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[box-shadow:0_12px_24px_rgb(16_52_91_/_.18)]", "tw:[&_button]:grid", "tw:[&_button]:gap-y-[2px]",
    "tw:[&_button]:gap-x-[2px]", "tw:[&_button]:pt-[9px]", "tw:[&_button]:pr-[10px]", "tw:[&_button]:pb-[9px]",
    "tw:[&_button]:pl-[10px]", "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]",
    "tw:[&_button]:border-r-[length:0]", "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:1px]",
    "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:#edf2f7]", "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]",
    "tw:[&_button]:border-l-[color:currentColor]", "tw:[&_button]:bg-[color:#fff]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:#26476d]",
    "tw:[&_button]:text-left", "tw:[&_button]:[font:inherit]", "tw:[&_button]:cursor-pointer", "tw:[&_span]:grid",
    "tw:[&_span]:gap-y-[2px]", "tw:[&_span]:gap-x-[2px]", "tw:[&_span]:pt-[9px]", "tw:[&_span]:pr-[10px]",
    "tw:[&_span]:pb-[9px]", "tw:[&_span]:pl-[10px]", "tw:[&_span]:border-t-[length:0]", "tw:[&_span]:[border-top-style:none]",
    "tw:[&_span]:border-t-[color:currentColor]", "tw:[&_span]:border-r-[length:0]", "tw:[&_span]:[border-right-style:none]", "tw:[&_span]:border-r-[color:currentColor]",
    "tw:[&_span]:border-b-[length:1px]", "tw:[&_span]:[border-bottom-style:solid]", "tw:[&_span]:border-b-[color:#edf2f7]", "tw:[&_span]:border-l-[length:0]",
    "tw:[&_span]:[border-left-style:none]", "tw:[&_span]:border-l-[color:currentColor]", "tw:[&_span]:bg-[color:#fff]", "tw:[&_span]:[background-image:none]",
    "tw:[&_span]:text-[color:#26476d]", "tw:[&_span]:text-left", "tw:[&_span]:[font:inherit]", "tw:[&_span]:cursor-pointer",
    "tw:[&_button:hover]:bg-[color:#eef6ff]", "tw:[&_button:hover]:[background-image:none]", "tw:[&_small]:text-[color:#6d839e]",
  ].join(" "),
} as const;
