import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "stack_md": [
    "stack-md", "stock-management-page", "tw:grid", "tw:gap-y-[18px]",
    "tw:gap-x-[18px]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]",
    "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]",
  ].join(" "),
  "sr_only": sharedUtilities.srOnly,
  "page_header_stock_management_header": [
    "page-header", "stock-management-header", "tw:flex", "tw:viewport-760:grid",
    "tw:justify-between", "tw:items-end", "tw:viewport-560:items-start", "tw:gap-y-[18px]",
    "tw:gap-x-[18px]", "tw:mb-[0]", "tw:pt-[4px]", "tw:pr-[0]",
    "tw:pb-[22px]", "tw:pl-[0]", "tw:border-t-[length:0]", "tw:[border-top-style:none]",
    "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:2px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:color-mix(in_srgb,_var(--brand)_24%,_var(--line))]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[0]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:[box-shadow:none]", "tw:[animation:hero-rise_620ms_var(--ease-standard)_both]", "tw:mt-[0]",
    "tw:mr-[0]", "tw:ml-[0]", "tw:[&_h1]:mt-[0]", "tw:[&_h1]:mr-[0]",
    "tw:[&_h1]:mb-[0]", "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[clamp(1.8rem,_2vw,_2.4rem)]", "tw:[&_h1]:leading-[1.04]",
    "tw:[&_h1]:tracking-[-0.04em]", "tw:[&_p]:max-w-[760px]", "tw:[&::after]:[content:'']", "tw:[&::after]:absolute",
    "tw:viewport-720:flex-col",
  ].join(" "),
  "stock_management_metrics": [
    "stock-management-metrics", "tw:flex", "tw:flex-wrap", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[&_span]:inline-flex", "tw:[&_span]:items-baseline", "tw:[&_span]:gap-y-[5px]",
    "tw:[&_span]:gap-x-[5px]", "tw:[&_span]:pt-[7px]", "tw:[&_span]:pr-[9px]", "tw:[&_span]:pb-[7px]",
    "tw:[&_span]:pl-[9px]", "tw:[&_span]:border-t-[length:1px]", "tw:[&_span]:[border-top-style:solid]", "tw:[&_span]:border-t-[color:#d6e3ef]",
    "tw:[&_span]:border-r-[length:1px]", "tw:[&_span]:[border-right-style:solid]", "tw:[&_span]:border-r-[color:#d6e3ef]", "tw:[&_span]:border-b-[length:1px]",
    "tw:[&_span]:[border-bottom-style:solid]", "tw:[&_span]:border-b-[color:#d6e3ef]", "tw:[&_span]:border-l-[length:1px]", "tw:[&_span]:[border-left-style:solid]",
    "tw:[&_span]:border-l-[color:#d6e3ef]", "tw:[&_span]:rounded-[7px]", "tw:[&_span]:text-[color:#60758e]", "tw:[&_span]:bg-[color:#f8fbff]",
    "tw:[&_span]:[background-image:none]", "tw:[&_span]:text-[.7rem]", "tw:[&_b]:text-[color:#153b68]", "tw:[&_b]:text-[.88rem]",
    "tw:[&_.is-attention]:border-t-[color:#f0ca8e]", "tw:[&_.is-attention]:border-r-[color:#f0ca8e]", "tw:[&_.is-attention]:border-b-[color:#f0ca8e]", "tw:[&_.is-attention]:border-l-[color:#f0ca8e]",
    "tw:[&_.is-attention]:text-[color:#8c5b08]", "tw:[&_.is-attention]:bg-[color:#fff9ec]", "tw:[&_.is-attention]:[background-image:none]", "tw:[&_.is-attention_b]:text-[color:#a56404]",
    "tw:viewport-560:w-[100%]",
  ].join(" "),
  "is_attention": [
    "is-attention", "tw:[&_.client-finance-orb]:bg-[color:#c96b28]", "tw:[&_.client-finance-orb]:[background-image:none]",
  ].join(" "),
  "grid_form": sharedUtilities.gridForm,
  "field": sharedUtilities.field,
  "field_field_submit": sharedUtilities.fieldFieldSubmit,
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "stock_operational_list": [
    "stock-operational-list", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#d8e3ef]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#d8e3ef]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d8e3ef]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d8e3ef]", "tw:rounded-[10px]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]",
  ].join(" "),
  "stock_operational_head": [
    "stock-operational-head", "tw:grid", "tw:viewport-900:hidden", "tw:grid-cols-[minmax(190px,_1.15fr)_minmax(120px,_.7fr)_minmax(100px,_.55fr)_minmax(110px,_.55fr)_minmax(360px,_1.8fr)]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:items-center", "tw:min-h-[38px]",
    "tw:pt-[0]", "tw:pr-[14px]", "tw:pb-[0]", "tw:pl-[14px]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dfe8f1]", "tw:bg-[color:#f7faff]",
    "tw:[background-image:none]", "tw:text-[color:#5b7089]", "tw:text-[.66rem]", "tw:font-[800]",
    "tw:tracking-[.045em]", "tw:uppercase",
  ].join(" "),
  "stock_operational_row": [
    "stock-operational-row", "tw:grid", "tw:grid-cols-[minmax(190px,_1.15fr)_minmax(120px,_.7fr)_minmax(100px,_.55fr)_minmax(110px,_.55fr)_minmax(360px,_1.8fr)]", "tw:viewport-900:grid-cols-[minmax(0,_1fr)_minmax(130px,_auto)]",
    "tw:viewport-560:grid-cols-[1fr]", "tw:gap-y-[12px]", "tw:viewport-900:gap-y-[6px]", "tw:gap-x-[12px]",
    "tw:items-center", "tw:min-h-[65px]", "tw:pt-[9px]", "tw:pr-[14px]",
    "tw:pb-[9px]", "tw:pl-[14px]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#e8eef5]", "tw:text-[color:#48607c]", "tw:text-[.78rem]", "tw:[&:last-child]:border-b-[length:0]",
    "tw:[&:last-child]:[border-bottom-style:none]", "tw:[&:last-child]:border-b-[color:currentColor]", "tw:hover:bg-[color:#f8fbff]", "tw:hover:[background-image:none]",
    "tw:[&_>_div:first-child]:min-w-[0]", "tw:[&_strong]:block", "tw:[&_strong]:[overflow-x:hidden]", "tw:[&_strong]:[overflow-y:hidden]",
    "tw:[&_strong]:text-[color:#12365f]", "tw:[&_strong]:text-[.82rem]", "tw:[&_strong]:text-ellipsis", "tw:[&_strong]:whitespace-nowrap",
    "tw:[&_small]:block", "tw:[&_small]:mt-[3px]", "tw:[&_small]:text-[color:#73849a]", "tw:[&_small]:text-[.67rem]",
    "tw:[&_b:not(.stock-alert)]:text-[color:#173a64]", "tw:[&_b:not(.stock-alert)]:text-[.88rem]", "tw:viewport-900:[&_>_:nth-child(2)]:[grid-column:1_/_-1]", "tw:viewport-900:[&_>_:nth-child(3)]:[grid-column:1_/_-1]",
    "tw:viewport-560:[&_>_:nth-child(n+2)]:[grid-column:auto]",
  ].join(" "),
  "stock_alert": [
    "stock-alert", "tw:inline-flex", "tw:items-center", "tw:min-h-[30px]",
    "tw:pt-[0]", "tw:pr-[10px]", "tw:pb-[0]", "tw:pl-[10px]",
    "tw:rounded-[999px]", "tw:text-[0.86rem]", "tw:font-[700]", "tw:bg-[color:rgba(191,_63,_56,_0.1)]",
    "tw:[background-image:none]", "tw:text-[color:var(--danger)]",
  ].join(" "),
  "stock_row_adjust": [
    "stock-row-adjust", "tw:grid", "tw:grid-cols-[110px_58px_minmax(95px,_1fr)_auto]", "tw:viewport-900:grid-cols-[110px_58px_minmax(100px,_1fr)_auto]",
    "tw:viewport-560:grid-cols-[1fr_1fr]", "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:items-center",
    "tw:[&_select]:min-w-[0]", "tw:[&_select]:min-h-[32px]", "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[7px]",
    "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[7px]", "tw:[&_select]:text-[.72rem]", "tw:[&_input]:min-w-[0]",
    "tw:[&_input]:min-h-[32px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[7px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[7px]", "tw:[&_input]:text-[.72rem]", "tw:[&_.button]:min-h-[32px]", "tw:viewport-900:[grid-column:1_/_-1]",
    "tw:viewport-560:[&_input]:[grid-column:1_/_-1]", "tw:viewport-560:[&_select]:[grid-column:1]", "tw:viewport-560:[&_.button]:[grid-column:2]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "client_empty": sharedUtilities.clientEmpty,
} as const;
