import Link from "next/link";
import type { ReactNode } from "react";
import { notFound } from "next/navigation";
import { SafeActionForm } from "@/components/forms/safe-action-form";
import { SubmitButton } from "@/components/forms/submit-button";
import { SectionCard } from "@/components/section-card";
import { NfeImportWorkspace } from "@/components/fiscal/nfe-import-workspace";
import { connectPaymentProviderAction, createCouponAction, createFinancialSettingAction, createProductCategoryAction, reconcileBankAccountBalanceAction, updateFiscalSettingsAction } from "@/lib/actions/finance";
import { requireModuleView } from "@/lib/auth/guards";
import { prisma } from "@/lib/prisma";

const areas = {
  "notas-fiscais": ["Notas Fiscais", "Importe NF-e de compra, acompanhe o histórico e configure a emissão."], fornecedores: ["Fornecedores", "Cadastre parceiros de compra e acompanhe informações de fornecimento."], "categorias-produtos": ["Categorias de Produtos", "Agrupe produtos e serviços para facilitar o PDV, estoque e relatórios."], "formas-pagamento": ["Formas de Pagamentos", "Defina os meios aceitos pela arena."], "contas-bancarias": ["Contas Bancárias", "Centralize contas e saldos bancários utilizados na operação."], cupons: ["Cupons", "Cadastre descontos com período de validade, valor mínimo e limite de uso."], "categorias-financeiras": ["Categorias Financeiras", "Padronize receitas e despesas para os relatórios gerenciais."], "pagamentos-online": ["Conectores de pagamento", "Conecte as contas da arena para receber cobranças no Portal do Atleta."]
} as const;

const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value / 100);
const backLink = () => <Link className="button button-small" href="/financeiro/configuracoes">Voltar às configurações</Link>;
function CreatePanel({ label, children }: { label: string; children: ReactNode }) { return <details className="setting-create-panel"><summary className="button button-primary button-small">{label}</summary><div>{children}</div></details>; }
function Status({ children, tone = "active" }: { children: ReactNode; tone?: "active" | "neutral" }) { return <span className={`settings-status settings-status-${tone}`}>{children}</span>; }
function List({ columns, empty, children }: { columns: string[]; empty: boolean; children: ReactNode }) { return <div className="settings-operational-list"><div className="settings-operational-head">{columns.map((column) => <span key={column}>{column}</span>)}</div>{empty ? <p className="client-empty">Nenhum cadastro nesta área.</p> : children}</div>; }
function FiscalEmission({ settings }: { settings: { provider: string; environment: string; series: string; nextNumber: number; notes: string } | null }) { return <SectionCard title="Configurações de Emissão" description="Defina a numeração interna e o ambiente fiscal da arena."><SafeActionForm action={updateFiscalSettingsAction} className="grid-form" successMessage="Configuração fiscal salva."><div className="field"><label>Modo de emissão<select name="provider" defaultValue={settings?.provider ?? "NONE"}><option value="NONE">Desativada</option><option value="MANUAL">Controle manual</option></select></label></div><div className="field"><label>Ambiente<select name="environment" defaultValue={settings?.environment ?? "SANDBOX"}><option value="SANDBOX">Testes</option><option value="PRODUCTION">Produção</option></select></label></div><div className="field"><label>Série<input name="series" defaultValue={settings?.series ?? ""} /></label></div><div className="field"><label>Próximo número<input name="nextNumber" type="number" min="1" defaultValue={settings?.nextNumber ?? 1} /></label></div><div className="field form-full"><label>Observações<textarea name="notes" defaultValue={settings?.notes ?? ""} /></label></div><div className="field field-submit"><SubmitButton label="Salvar configurações" pendingLabel="Salvando..." className="button button-primary button-small" /></div></SafeActionForm></SectionCard>; }

export default async function FinancialSettingAreaPage(
  props: { params: Promise<{ area: string }>; searchParams?: Promise<{ connectionError?: string; secao?: string }> }
) {
  const searchParams = await props.searchParams;
  const params = await props.params;
  const auth = await requireModuleView("finance");const item = areas[params.area as keyof typeof areas];if (!item) notFound();const area = params.area;
  if (area === "categorias-produtos") {
    const categories = await prisma.productCategory.findMany({ where: { arenaId: auth.arenaId }, include: { _count: { select: { products: true } } }, orderBy: { name: "asc" } });
    return <div className="stack-md settings-page"><SectionCard title={item[0]} description={item[1]}><CreatePanel label="Nova categoria"><SafeActionForm action={createProductCategoryAction} className="grid-form" resetOnSuccess successMessage="Categoria criada."><div className="field"><label>Nome<input name="name" required /></label></div><div className="field field-submit"><SubmitButton label="Salvar categoria" pendingLabel="Salvando..." className="button button-primary button-small" /></div></SafeActionForm></CreatePanel><List columns={["Categoria", "Situação", "Produtos"]} empty={!categories.length}>{categories.map((entry) => <article className="settings-operational-row" key={entry.id}><strong>{entry.name}</strong><Status tone={entry.active ? "active" : "neutral"}>{entry.active ? "Ativa" : "Inativa"}</Status><span>{entry._count.products} produto(s)</span></article>)}</List>{backLink()}</SectionCard></div>;
  }
  if (area === "cupons") {
    const coupons = await prisma.coupon.findMany({ where: { arenaId: auth.arenaId }, orderBy: [{ active: "desc" }, { createdAt: "desc" }] });
    return <div className="stack-md settings-page"><SectionCard title={item[0]} description={item[1]}><CreatePanel label="Novo cupom"><SafeActionForm action={createCouponAction} className="grid-form" resetOnSuccess successMessage="Cupom criado."><div className="field"><label>Código<input name="code" placeholder="Ex.: BEMVINDO10" required /></label></div><div className="field"><label>Tipo<select name="discountType"><option value="PERCENTAGE">Percentual (%)</option><option value="FIXED">Valor fixo (R$)</option></select></label></div><div className="field"><label>Desconto<input name="discountValue" type="number" min="1" required /></label></div><div className="field"><label>Valor mínimo<input name="minimumAmount" placeholder="0,00" /></label></div><div className="field"><label>Limite de usos<input name="maxUses" type="number" min="1" placeholder="Ilimitado" /></label></div><div className="field"><label>Início<input name="startsAt" type="date" /></label></div><div className="field"><label>Fim<input name="endsAt" type="date" /></label></div><div className="field field-submit"><SubmitButton label="Salvar cupom" pendingLabel="Salvando..." className="button button-primary button-small" /></div></SafeActionForm></CreatePanel><List columns={["Cupom", "Desconto", "Utilização", "Situação"]} empty={!coupons.length}>{coupons.map((entry) => <article className="settings-operational-row settings-coupon-row" key={entry.id}><strong>{entry.code}</strong><span>{entry.discountType === "PERCENTAGE" ? `${entry.discountValue}%` : money(entry.discountValue)} · mínimo {money(entry.minimumAmountCents)}</span><span>{entry.maxUses ? `${entry.usesCount}/${entry.maxUses} usos` : "Usos ilimitados"}</span><Status tone={entry.active ? "active" : "neutral"}>{entry.active ? "Ativo" : "Inativo"}</Status></article>)}</List>{backLink()}</SectionCard></div>;
  }
  if (area === "notas-fiscais") {
    const [settings, documents] = await Promise.all([prisma.fiscalSettings.findUnique({ where: { arenaId: auth.arenaId } }), prisma.fiscalDocument.findMany({ where: { arenaId: auth.arenaId }, include: { _count: { select: { items: true } } }, orderBy: { importedAt: "desc" }, take: 30 })]);
    if (searchParams?.secao === "emissao") return <div className="stack-md settings-page"><section className="settings-emission-shell">{backLink()}<FiscalEmission settings={settings} /></section></div>;
    return <div className="stack-md settings-page"><SectionCard title="Importar NF-e de compra" description="Selecione o XML autorizado. A conciliação de produtos abre em seguida, antes da entrada no estoque."><NfeImportWorkspace /></SectionCard><SectionCard title="Notas importadas" description="Acompanhe todas as NF-e recebidas e conciliadas no estoque."><List columns={["Documento", "Emissão", "Itens", "Total"]} empty={!documents.length}>{documents.map((document) => <article className="settings-operational-row settings-invoice-row" key={document.id}><div><strong>NF-e {document.number || "sem número"}</strong><small>{document.supplierName || "Fornecedor não informado"} · série {document.series || "—"}</small></div><span>{document.issuedAt ? new Intl.DateTimeFormat("pt-BR").format(document.issuedAt) : "Sem data"}</span><span>{document._count.items} item(ns)</span><span>{money(document.totalCents)}</span></article>)}</List><Link className="button button-small" href="/financeiro/configuracoes/notas-fiscais?secao=emissao">Configurações de Emissão</Link>{backLink()}</SectionCard></div>;
  }
  if (area === "pagamentos-online") {
    const connections = await prisma.paymentConnection.findMany({ where: { arenaId: auth.arenaId }, select: { provider: true, status: true, displayName: true, accountReference: true } }); const mercadoPago = connections.find((entry) => entry.provider === "MERCADO_PAGO"); const asaas = connections.find((entry) => entry.provider === "ASAAS"); const sicoob = connections.find((entry) => entry.provider === "SICOOB");
    return <div className="stack-md settings-page"><SectionCard title={item[0]} description={item[1]}><div className="payment-connectors-list"><article className="payment-connector-card"><div className="payment-connector-copy"><span className="payment-connector-icon">M</span><div><h2>Mercado Pago</h2><p>{mercadoPago?.status === "CONNECTED" ? `Conta conectada · ${mercadoPago.displayName || mercadoPago.accountReference || ""}` : "PIX e cartão com autorização segura da conta da arena."}</p></div></div><a className="button button-primary button-small" href="/api/integrations/payments/mercado-pago/connect">{mercadoPago?.status === "CONNECTED" ? "Reconectar" : "Conectar"}</a></article><details className="payment-connector-card payment-connector-expand"><summary><strong>Asaas</strong><Status tone={asaas?.status === "CONNECTED" ? "active" : "neutral"}>{asaas?.status === "CONNECTED" ? "Conectado" : "Configurar"}</Status></summary><SafeActionForm action={connectPaymentProviderAction} className="payment-connector-form" successMessage="Conta Asaas conectada e validada."><input type="hidden" name="provider" value="ASAAS" /><label>Ambiente<select name="environment"><option value="PRODUCTION">Produção</option><option value="SANDBOX">Sandbox</option></select></label><label>Chave de API<input name="accessToken" type="password" autoComplete="off" required /></label><SubmitButton label="Validar e conectar" pendingLabel="Validando..." className="button button-primary button-small" /></SafeActionForm></details><details className="payment-connector-card payment-connector-expand"><summary><strong>Sicoob</strong><Status tone={sicoob?.status === "CONFIGURED" ? "active" : "neutral"}>{sicoob?.status === "CONFIGURED" ? "Configurado" : "Configurar"}</Status></summary><SafeActionForm action={connectPaymentProviderAction} className="payment-connector-form payment-connector-form-sicoob" successMessage="Dados do Sicoob configurados."><input type="hidden" name="provider" value="SICOOB" /><label>Ambiente<select name="environment"><option value="PRODUCTION">Produção</option><option value="SANDBOX">Sandbox</option></select></label><label>Client ID<input name="clientId" required /></label><label>Client Secret<input name="clientSecret" type="password" required /></label><label>Chave PIX<input name="pixKey" required /></label><label>Certificado PEM<textarea name="certificate" required /></label><label>Chave privada PEM<textarea name="privateKey" required /></label><label>Senha do certificado<input name="certificatePassword" type="password" /></label><SubmitButton label="Salvar conexão" pendingLabel="Protegendo dados..." className="button button-primary button-small" /></SafeActionForm></details></div>{searchParams?.connectionError ? <p className="form-error">{searchParams.connectionError}</p> : null}{backLink()}</SectionCard></div>;
  }
  const rows = area === "categorias-financeiras" ? (await prisma.financialCategory.findMany({ where: { arenaId: auth.arenaId }, orderBy: { name: "asc" } })).map((entry) => ({ id: "", name: entry.name, detail: entry.type === "BOTH" ? "Receita e despesa" : entry.type === "REVENUE" ? "Receita" : "Despesa", balance: 0 })) : area === "formas-pagamento" ? (await prisma.paymentMethodSetting.findMany({ where: { arenaId: auth.arenaId }, orderBy: { name: "asc" } })).map((entry) => ({ id: "", name: entry.name, detail: entry.active ? "Ativa" : "Inativa", balance: 0 })) : area === "contas-bancarias" ? (await prisma.bankAccount.findMany({ where: { arenaId: auth.arenaId }, orderBy: { name: "asc" } })).map((entry) => ({ id: entry.id, name: entry.name, detail: entry.bankName || "Banco não informado", balance: entry.openingBalanceCents })) : (await prisma.supplier.findMany({ where: { arenaId: auth.arenaId }, orderBy: { name: "asc" } })).map((entry) => ({ id: "", name: entry.name, detail: [entry.document, entry.phone, entry.email].filter(Boolean).join(" · ") || "Sem contato informado", balance: 0 }));
  const bank = area === "contas-bancarias";const columns = bank ? ["Conta", "Banco", "Saldo inicial", "Conferir saldo"] : area === "fornecedores" ? ["Fornecedor", "Contato"] : area === "categorias-financeiras" ? ["Categoria", "Tipo"] : ["Forma de pagamento", "Situação"];
  return <div className="stack-md settings-page"><SectionCard title={item[0]} description={item[1]}><CreatePanel label={bank ? "Nova conta bancária" : area === "fornecedores" ? "Novo fornecedor" : area === "formas-pagamento" ? "Nova forma de pagamento" : "Nova categoria"}><SafeActionForm action={createFinancialSettingAction} className="grid-form" resetOnSuccess successMessage="Cadastro salvo."><input type="hidden" name="area" value={area} /><div className="field"><label>Nome<input name="name" required /></label></div>{area === "categorias-financeiras" ? <div className="field"><label>Tipo<select name="type" defaultValue="BOTH"><option value="BOTH">Receita e despesa</option><option value="REVENUE">Receita</option><option value="EXPENSE">Despesa</option></select></label></div> : null}{bank ? <><div className="field"><label>Banco<input name="bankName" /></label></div><div className="field"><label>Saldo inicial<input name="openingBalance" placeholder="0,00" /></label></div></> : null}{area === "fornecedores" ? <><div className="field"><label>CPF/CNPJ<input name="document" /></label></div><div className="field"><label>Telefone<input name="phone" /></label></div><div className="field"><label>E-mail<input name="email" type="email" /></label></div><div className="field form-full"><label>Observações<input name="notes" /></label></div></> : null}<div className="field field-submit"><SubmitButton label="Salvar" pendingLabel="Salvando..." className="button button-primary button-small" /></div></SafeActionForm></CreatePanel><List columns={columns} empty={!rows.length}>{rows.map((row) => <article className="settings-operational-row" key={`${row.name}-${row.detail}`}><strong>{row.name}</strong><span>{row.detail}</span>{bank ? <><span>{money(row.balance)}</span><SafeActionForm action={reconcileBankAccountBalanceAction} className="settings-balance-form" successMessage="Saldo bancário conciliado."><input type="hidden" name="bankAccountId" value={row.id} /><input name="balance" inputMode="decimal" placeholder="Saldo apurado" required /><SubmitButton label="Conferir" pendingLabel="..." className="button button-small" /></SafeActionForm></> : area === "formas-pagamento" ? <Status tone={row.detail === "Ativa" ? "active" : "neutral"}>{row.detail}</Status> : null}</article>)}</List>{backLink()}</SectionCard></div>;
}
