import Link from "next/link";
import { notFound } from "next/navigation";
import { SafeActionForm } from "@/components/forms/safe-action-form";
import { SubmitButton } from "@/components/forms/submit-button";
import { SectionCard } from "@/components/section-card";
import { createCouponAction, createFinancialSettingAction, createProductCategoryAction, updateFiscalSettingsAction, updateOnlinePaymentSettingsAction } from "@/lib/actions/finance";
import { requireModuleView } from "@/lib/auth/guards";
import { prisma } from "@/lib/prisma";

const areas = {
  "notas-fiscais": ["Notas Fiscais", "Defina o modo de emissão. A integração externa só será ativada após as credenciais do emissor."],
  fornecedores: ["Fornecedores", "Cadastre parceiros de compra e acompanhe informações de fornecimento."],
  "categorias-produtos": ["Categorias de Produtos", "Agrupe produtos e serviços para facilitar o PDV, estoque e relatórios."],
  "formas-pagamento": ["Formas de Pagamentos", "Defina os meios aceitos pela arena."],
  "contas-bancarias": ["Contas Bancárias", "Centralize contas e saldos bancários utilizados na operação."],
  cupons: ["Cupons", "Cadastre descontos com período de validade, valor mínimo e limite de uso."],
  "categorias-financeiras": ["Categorias Financeiras", "Padronize receitas e despesas para os relatórios gerenciais."],
  "pagamentos-online": ["Conectores de pagamento", "Conecte as contas da arena para receber cobranças no Portal do Atleta."],
} as const;

function money(value: number) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value / 100); }
function backLink() { return <Link className="button" href="/financeiro/configuracoes">Voltar às configurações</Link>; }

export default async function FinancialSettingAreaPage({ params }: { params: { area: string } }) {
  const auth = await requireModuleView("finance");
  const item = areas[params.area as keyof typeof areas];
  if (!item) notFound();
  const area = params.area;

  if (area === "categorias-produtos") {
    const categories = await prisma.productCategory.findMany({ where: { arenaId: auth.arenaId }, include: { _count: { select: { products: true } } }, orderBy: { name: "asc" } });
    return <div className="stack-md"><SectionCard title={item[0]} description={item[1]}><SafeActionForm action={createProductCategoryAction} className="grid-form" resetOnSuccess successMessage="Categoria criada."><div className="field"><label>Nome<input name="name" required /></label></div><div className="field field-submit"><SubmitButton label="Adicionar categoria" pendingLabel="Salvando..." className="button button-primary" /></div></SafeActionForm><div className="simple-list">{categories.map((entry) => <div className="simple-item" key={entry.id}><strong>{entry.name}</strong><span>{entry.active ? "Ativa" : "Inativa"} · {entry._count.products} produto(s)</span></div>)}{!categories.length ? <p className="muted">Nenhuma categoria cadastrada.</p> : null}</div>{backLink()}</SectionCard></div>;
  }

  if (area === "cupons") {
    const coupons = await prisma.coupon.findMany({ where: { arenaId: auth.arenaId }, orderBy: [{ active: "desc" }, { createdAt: "desc" }] });
    return <div className="stack-md"><SectionCard title={item[0]} description={item[1]}><SafeActionForm action={createCouponAction} className="grid-form" resetOnSuccess successMessage="Cupom criado."><div className="field"><label>Código<input name="code" placeholder="EX.: BEMVINDO10" required /></label></div><div className="field"><label>Tipo<select name="discountType"><option value="PERCENTAGE">Percentual (%)</option><option value="FIXED">Valor fixo (R$)</option></select></label></div><div className="field"><label>Desconto<input name="discountValue" type="number" min="1" required /></label></div><div className="field"><label>Valor mínimo<input name="minimumAmount" placeholder="0,00" /></label></div><div className="field"><label>Limite de usos<input name="maxUses" type="number" min="1" placeholder="Ilimitado" /></label></div><div className="field"><label>Início<input name="startsAt" type="date" /></label></div><div className="field"><label>Fim<input name="endsAt" type="date" /></label></div><div className="field field-submit"><SubmitButton label="Criar cupom" pendingLabel="Salvando..." className="button button-primary" /></div></SafeActionForm><div className="simple-list">{coupons.map((entry) => <div className="simple-item" key={entry.id}><strong>{entry.code}</strong><span>{entry.discountType === "PERCENTAGE" ? `${entry.discountValue}% de desconto` : money(entry.discountValue)} · mínimo {money(entry.minimumAmountCents)} · {entry.maxUses ? `${entry.usesCount}/${entry.maxUses} usos` : "usos ilimitados"} · {entry.active ? "Ativo" : "Inativo"}</span></div>)}{!coupons.length ? <p className="muted">Nenhum cupom cadastrado.</p> : null}</div>{backLink()}</SectionCard></div>;
  }

  if (area === "notas-fiscais") {
    const settings = await prisma.fiscalSettings.findUnique({ where: { arenaId: auth.arenaId } });
    return <div className="stack-md"><SectionCard title={item[0]} description={item[1]}><SafeActionForm action={updateFiscalSettingsAction} className="grid-form" successMessage="Configuração fiscal salva."><div className="field"><label>Modo de emissão<select name="provider" defaultValue={settings?.provider ?? "NONE"}><option value="NONE">Desativada</option><option value="MANUAL">Emissão manual</option></select></label></div><div className="field"><label>Ambiente<select name="environment" defaultValue={settings?.environment ?? "SANDBOX"}><option value="SANDBOX">Testes</option><option value="PRODUCTION">Produção</option></select></label></div><div className="field"><label>Série<input name="series" defaultValue={settings?.series ?? ""} /></label></div><div className="field"><label>Próximo número<input name="nextNumber" type="number" min="1" defaultValue={settings?.nextNumber ?? 1} /></label></div><div className="field form-full"><label>Observações<textarea name="notes" defaultValue={settings?.notes ?? ""} /></label></div><div className="field field-submit"><SubmitButton label="Salvar configurações" pendingLabel="Salvando..." className="button button-primary" /></div></SafeActionForm><p className="form-note">Nenhuma nota é emitida automaticamente sem a integração fiscal configurada.</p>{backLink()}</SectionCard></div>;
  }

  if (area === "pagamentos-online") {
    const settings = await prisma.onlinePaymentSettings.findUnique({ where: { arenaId: auth.arenaId } });
    const connections = await prisma.paymentConnection.findMany({ where: { arenaId: auth.arenaId }, select: { provider: true, status: true, accountReference: true, lastValidatedAt: true, lastError: true } });
    const mercadoPago = connections.find((connection) => connection.provider === "MERCADO_PAGO");
    return <div className="stack-md"><SectionCard title="Conectores de pagamento" description="Cada arena autoriza a própria conta. Dados de acesso permanecem criptografados e não são exibidos novamente."><div className="simple-list"><div className="simple-item"><div><strong>Mercado Pago</strong><span>{mercadoPago?.status === "CONNECTED" ? `Conta conectada${mercadoPago.accountReference ? ` · ${mercadoPago.accountReference}` : ""}` : "Conecte a conta que receberá PIX e cartão no Portal do Atleta."}</span></div><a className="button button-primary button-small" href="/api/integrations/payments/mercado-pago/connect">{mercadoPago?.status === "CONNECTED" ? "Reconectar" : "Conectar"}</a></div><div className="simple-item"><div><strong>Asaas</strong><span>Em breve: conexão segura por chave da própria conta ou por subconta BaaS.</span></div><span className="muted">Em preparação</span></div><div className="simple-item"><div><strong>Sicoob</strong><span>Em breve: conexão por aplicação e certificado da cooperativa.</span></div><span className="muted">Em preparação</span></div></div>{mercadoPago?.lastError ? <p className="form-note">Última falha: {mercadoPago.lastError}</p> : null}</SectionCard><SectionCard title={item[0]} description={item[1]}><SafeActionForm action={updateOnlinePaymentSettingsAction} className="grid-form" successMessage="Configuração de pagamento online salva."><div className="field"><label>Modo de cobrança<select name="provider" defaultValue={settings?.provider ?? "NONE"}><option value="NONE">Desativada</option><option value="MANUAL">Link/manual</option></select></label></div><div className="field"><label>URL de retorno/webhook<input name="webhookUrl" type="url" defaultValue={settings?.webhookUrl ?? ""} placeholder="https://..." /></label></div><label className="check-option"><input name="pixEnabled" type="checkbox" defaultChecked={settings?.pixEnabled ?? true} /><span>PIX disponível</span></label><label className="check-option"><input name="cardEnabled" type="checkbox" defaultChecked={settings?.cardEnabled ?? false} /><span>Cartão disponível</span></label><div className="field form-full"><label>Instruções ao cliente<textarea name="instructions" defaultValue={settings?.instructions ?? ""} /></label></div><div className="field field-submit"><SubmitButton label="Salvar configurações" pendingLabel="Salvando..." className="button button-primary" /></div></SafeActionForm>{backLink()}</SectionCard></div>;
  }

  const rows = area === "categorias-financeiras" ? (await prisma.financialCategory.findMany({ where: { arenaId: auth.arenaId }, orderBy: { name: "asc" } })).map((entry) => ({ name: entry.name, detail: entry.type === "BOTH" ? "Receita e despesa" : entry.type === "REVENUE" ? "Receita" : "Despesa" })) : area === "formas-pagamento" ? (await prisma.paymentMethodSetting.findMany({ where: { arenaId: auth.arenaId }, orderBy: { name: "asc" } })).map((entry) => ({ name: entry.name, detail: entry.active ? "Ativa" : "Inativa" })) : area === "contas-bancarias" ? (await prisma.bankAccount.findMany({ where: { arenaId: auth.arenaId }, orderBy: { name: "asc" } })).map((entry) => ({ name: entry.name, detail: `${entry.bankName || "Banco não informado"} · saldo inicial ${money(entry.openingBalanceCents)}` })) : (await prisma.supplier.findMany({ where: { arenaId: auth.arenaId }, orderBy: { name: "asc" } })).map((entry) => ({ name: entry.name, detail: [entry.document, entry.phone, entry.email].filter(Boolean).join(" · ") || "Sem contato informado" }));
  return <div className="stack-md"><SectionCard title={item[0]} description={item[1]}><SafeActionForm action={createFinancialSettingAction} className="grid-form" resetOnSuccess successMessage="Cadastro salvo."><input type="hidden" name="area" value={area} /><div className="field"><label>Nome<input name="name" required /></label></div>{area === "categorias-financeiras" ? <div className="field"><label>Tipo<select name="type" defaultValue="BOTH"><option value="BOTH">Receita e despesa</option><option value="REVENUE">Receita</option><option value="EXPENSE">Despesa</option></select></label></div> : null}{area === "contas-bancarias" ? <><div className="field"><label>Banco<input name="bankName" /></label></div><div className="field"><label>Saldo inicial<input name="openingBalance" placeholder="0,00" /></label></div></> : null}{area === "fornecedores" ? <><div className="field"><label>CPF/CNPJ<input name="document" /></label></div><div className="field"><label>Telefone<input name="phone" /></label></div><div className="field"><label>E-mail<input name="email" type="email" /></label></div><div className="field form-full"><label>Observações<input name="notes" /></label></div></> : null}<div className="field field-submit"><SubmitButton label="Adicionar" pendingLabel="Salvando..." className="button button-primary" /></div></SafeActionForm><div className="simple-list">{rows.map((row) => <div className="simple-item" key={`${row.name}-${row.detail}`}><strong>{row.name}</strong><span>{row.detail}</span></div>)}{!rows.length ? <p className="muted">Nenhum cadastro nesta área.</p> : null}</div>{backLink()}</SectionCard></div>;
}
