import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "card_stack_md": [
    "card", "stack-md", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[10px]", "tw:bg-[color:var(--panel)]",
    "tw:[background-image:none]", "tw:[box-shadow:0_5px_16px_rgba(19,_48,_83,_0.05)]", "tw:[animation:rise-in_620ms_var(--ease-standard)_both]", "tw:pt-[24px]",
    "tw:pr-[24px]", "tw:pb-[24px]", "tw:pl-[24px]", "tw:[&_h2]:mt-[0]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[1.35rem]",
    "tw:[&_h2]:leading-[1.2]", "tw:[&_h2]:tracking-[-0.03em]", "tw:grid", "tw:gap-y-[18px]",
    "tw:gap-x-[18px]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]",
    "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]",
  ].join(" "),
  "sr_only": sharedUtilities.srOnly,
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "setting_create_panel": [
    "setting-create-panel", "tw:mb-[14px]", "tw:[&_>_summary]:w-[fit-content]", "tw:[&_>_summary]:[list-style:none]",
    "tw:[&_>_summary]:cursor-pointer", "tw:[&_>_summary::-webkit-details-marker]:hidden", "tw:[&_>_div]:mt-[12px]",
  ].join(" "),
  "button_button_primary_button_small": sharedUtilities.buttonButtonPrimaryButtonSmall,
  "settings_status": [
    "settings-status", "tw:inline-flex", "tw:w-[fit-content]", "tw:pt-[3px]",
    "tw:pr-[7px]", "tw:pb-[3px]", "tw:pl-[7px]", "tw:rounded-[4px]",
    "tw:text-[.66rem]", "tw:font-[800]", "tw:[&.settings-status-revenue]:border-t-[color:#b9e5cf]", "tw:[&.settings-status-revenue]:border-r-[color:#b9e5cf]",
    "tw:[&.settings-status-revenue]:border-b-[color:#b9e5cf]", "tw:[&.settings-status-revenue]:border-l-[color:#b9e5cf]", "tw:[&.settings-status-revenue]:text-[color:#137447]", "tw:[&.settings-status-revenue]:bg-[color:#edf9f1]",
    "tw:[&.settings-status-revenue]:[background-image:none]", "tw:[&.settings-status-expense]:border-t-[color:#f3c4bf]", "tw:[&.settings-status-expense]:border-r-[color:#f3c4bf]", "tw:[&.settings-status-expense]:border-b-[color:#f3c4bf]",
    "tw:[&.settings-status-expense]:border-l-[color:#f3c4bf]", "tw:[&.settings-status-expense]:text-[color:#bb3830]", "tw:[&.settings-status-expense]:bg-[color:#fff0ee]", "tw:[&.settings-status-expense]:[background-image:none]",
    "tw:[&.settings-status-active]:text-[color:#0c7945]", "tw:[&.settings-status-active]:bg-[color:#e6f8ed]", "tw:[&.settings-status-active]:[background-image:none]", "tw:[&.settings-status-neutral]:text-[color:#61758c]",
    "tw:[&.settings-status-neutral]:bg-[color:#eef3f8]", "tw:[&.settings-status-neutral]:[background-image:none]",
  ].join(" "),
  "settings_operational_list": [
    "settings-operational-list", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#d8e3ef]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#d8e3ef]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d8e3ef]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d8e3ef]", "tw:rounded-[10px]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]",
  ].join(" "),
  "settings_operational_head": [
    "settings-operational-head", "tw:grid", "tw:viewport-900:hidden", "tw:grid-cols-[minmax(220px,_1.15fr)_minmax(150px,_.8fr)_minmax(120px,_.55fr)_minmax(120px,_.55fr)]",
    "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:items-center", "tw:min-h-[38px]",
    "tw:pt-[0]", "tw:pr-[14px]", "tw:pb-[0]", "tw:pl-[14px]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dfe8f1]", "tw:bg-[color:#f7faff]",
    "tw:[background-image:none]", "tw:text-[color:#5b7089]", "tw:text-[.66rem]", "tw:font-[800]",
    "tw:tracking-[.045em]", "tw:uppercase",
  ].join(" "),
  "client_empty": sharedUtilities.clientEmpty,
  "grid_form": sharedUtilities.gridForm,
  "field": sharedUtilities.field,
  "field_form_full": sharedUtilities.fieldFormFull,
  "field_field_submit": sharedUtilities.fieldFieldSubmit,
  "stack_md_settings_page": [
    "stack-md", "settings-page", "tw:grid", "tw:gap-y-[18px]",
    "tw:gap-x-[18px]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]",
    "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]",
    "tw:max-w-[1320px]", "tw:[&_>_.card]:relative", "tw:[&_>_.card]:pt-[62px]", "tw:[&_>_.card_>_.button:last-child]:absolute",
    "tw:[&_>_.card_>_.button:last-child]:top-[17px]", "tw:[&_>_.card_>_.button:last-child]:left-[18px]", "tw:[&_>_.card_>_.button:last-child]:w-[fit-content]", "tw:[&_>_.card_>_.button:last-child]:min-h-[32px]",
    "tw:[&_.grid-form_input]:min-h-[34px]", "tw:[&_.grid-form_input]:pt-[7px]", "tw:[&_.grid-form_input]:pr-[9px]", "tw:[&_.grid-form_input]:pb-[7px]",
    "tw:[&_.grid-form_input]:pl-[9px]", "tw:[&_.grid-form_input]:text-[.78rem]", "tw:[&_.grid-form_select]:min-h-[34px]", "tw:[&_.grid-form_select]:pt-[7px]",
    "tw:[&_.grid-form_select]:pr-[9px]", "tw:[&_.grid-form_select]:pb-[7px]", "tw:[&_.grid-form_select]:pl-[9px]", "tw:[&_.grid-form_select]:text-[.78rem]",
    "tw:[&_.grid-form_textarea]:min-h-[68px]", "tw:[&_.grid-form_textarea]:pt-[8px]", "tw:[&_.grid-form_textarea]:pr-[9px]", "tw:[&_.grid-form_textarea]:pb-[8px]",
    "tw:[&_.grid-form_textarea]:pl-[9px]", "tw:[&_.grid-form_textarea]:text-[.78rem]", "tw:[&_.grid-form_:is(input,_select,_textarea)]:rounded-[6px]", "tw:[&_.grid-form]:[align-items:end]",
    "tw:[&_.create-panel_.grid-form]:gap-y-[10px]", "tw:[&_.create-panel_.grid-form]:gap-x-[10px]",
  ].join(" "),
  "settings_operational_row": [
    "settings-operational-row", "tw:grid", "tw:grid-cols-[minmax(220px,_1.15fr)_minmax(150px,_.8fr)_minmax(120px,_.55fr)_minmax(120px,_.55fr)]", "tw:viewport-900:grid-cols-[minmax(0,_1fr)_minmax(120px,_auto)]",
    "tw:viewport-560:grid-cols-[1fr]", "tw:gap-y-[14px]", "tw:viewport-900:gap-y-[7px]", "tw:gap-x-[14px]",
    "tw:items-center", "tw:min-h-[58px]", "tw:pt-[9px]", "tw:pr-[14px]",
    "tw:pb-[9px]", "tw:pl-[14px]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#e8eef5]", "tw:text-[color:#3d536d]", "tw:text-[.78rem]", "tw:[&:last-child]:border-b-[length:0]",
    "tw:[&:last-child]:[border-bottom-style:none]", "tw:[&:last-child]:border-b-[color:currentColor]", "tw:hover:bg-[color:#f8fbff]", "tw:hover:[background-image:none]",
    "tw:[&_strong]:text-[color:#12365f]", "tw:[&_strong]:text-[.82rem]", "tw:[&_small]:block", "tw:[&_small]:mt-[3px]",
    "tw:[&_small]:text-[color:#73849a]", "tw:[&_small]:text-[.68rem]", "tw:[&_>_span]:text-[color:#58708d]", "tw:viewport-900:[&_>_:nth-child(n+3)]:[grid-column:1_/_-1]",
    "tw:viewport-560:[&_>_:nth-child(n+2)]:[grid-column:auto]",
  ].join(" "),
  "settings_coupon_list": [
    "settings-coupon-list", "tw:[&_.settings-operational-head]:grid-cols-[minmax(130px,_.8fr)_minmax(220px,_1.3fr)_minmax(130px,_.7fr)_100px_auto]",
  ].join(" "),
  "settings_operational_row_settings_coupon_row": [
    "settings-operational-row", "settings-coupon-row", "tw:grid", "tw:grid-cols-[minmax(130px,_.8fr)_minmax(220px,_1.3fr)_minmax(130px,_.7fr)_100px_auto]",
    "tw:viewport-900:grid-cols-[minmax(0,_1fr)_auto]", "tw:viewport-560:grid-cols-[1fr]", "tw:gap-y-[14px]", "tw:viewport-900:gap-y-[7px]",
    "tw:gap-x-[14px]", "tw:items-center", "tw:min-h-[58px]", "tw:pt-[9px]",
    "tw:pr-[14px]", "tw:pb-[9px]", "tw:pl-[14px]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e8eef5]", "tw:text-[color:#3d536d]", "tw:text-[.78rem]",
    "tw:[&:last-child]:border-b-[length:0]", "tw:[&:last-child]:[border-bottom-style:none]", "tw:[&:last-child]:border-b-[color:currentColor]", "tw:hover:bg-[color:#f8fbff]",
    "tw:hover:[background-image:none]", "tw:[&_strong]:text-[color:#12365f]", "tw:[&_strong]:text-[.82rem]", "tw:[&_small]:block",
    "tw:[&_small]:mt-[3px]", "tw:[&_small]:text-[color:#73849a]", "tw:[&_small]:text-[.68rem]", "tw:[&_>_span]:text-[color:#58708d]",
    "tw:viewport-900:[&_>_:nth-child(n+3)]:[grid-column:1_/_-1]", "tw:viewport-560:[&_>_:nth-child(n+2)]:[grid-column:auto]",
  ].join(" "),
  "settings_row_actions": [
    "settings-row-actions", "tw:relative", "tw:w-[fit-content]", "tw:[&_>_summary]:w-[fit-content]",
    "tw:[&_>_summary]:[list-style:none]", "tw:[&_>_summary]:cursor-pointer", "tw:[&_>_summary::-webkit-details-marker]:hidden", "tw:[&[open]]:z-[2]",
    "tw:[&[open]_>_form]:min-w-[min(620px,_calc(100vw_-_80px))]", "tw:viewport-700:[&[open]_>_form]:min-w-[0]", "tw:[&[open]_>_form]:mt-[8px]", "tw:[&[open]_>_form]:pt-[12px]",
    "tw:[&[open]_>_form]:pr-[12px]", "tw:[&[open]_>_form]:pb-[12px]", "tw:[&[open]_>_form]:pl-[12px]", "tw:[&[open]_>_form]:border-t-[length:1px]",
    "tw:[&[open]_>_form]:[border-top-style:solid]", "tw:[&[open]_>_form]:border-t-[color:#d8e3ef]", "tw:[&[open]_>_form]:border-r-[length:1px]", "tw:[&[open]_>_form]:[border-right-style:solid]",
    "tw:[&[open]_>_form]:border-r-[color:#d8e3ef]", "tw:[&[open]_>_form]:border-b-[length:1px]", "tw:[&[open]_>_form]:[border-bottom-style:solid]", "tw:[&[open]_>_form]:border-b-[color:#d8e3ef]",
    "tw:[&[open]_>_form]:border-l-[length:1px]", "tw:[&[open]_>_form]:[border-left-style:solid]", "tw:[&[open]_>_form]:border-l-[color:#d8e3ef]", "tw:[&[open]_>_form]:rounded-[9px]",
    "tw:[&[open]_>_form]:bg-[color:#fff]", "tw:[&[open]_>_form]:[background-image:none]", "tw:[&[open]_>_form]:[box-shadow:0_14px_30px_rgb(25_54_85_/_.14)]", "tw:[&[open]_>_form_+_form]:mt-[7px]",
    "tw:viewport-700:[&[open]_>_form]:w-[min(100vw_-_48px,_620px)]",
  ].join(" "),
  "button_button_danger_button_small": sharedUtilities.buttonButtonDangerButtonSmall,
  "settings_emission_shell": [
    "settings-emission-shell", "tw:relative", "tw:pt-[44px]", "tw:[&_>_.button]:absolute",
    "tw:[&_>_.button]:top-[0]", "tw:[&_>_.button]:left-[0]", "tw:[&_>_.button]:w-[fit-content]", "tw:[&_>_.button]:min-h-[32px]",
  ].join(" "),
  "settings_operational_row_settings_invoice_row": [
    "settings-operational-row", "settings-invoice-row", "tw:grid", "tw:grid-cols-[minmax(260px,_1.4fr)_minmax(130px,_.7fr)_100px_120px]",
    "tw:viewport-900:grid-cols-[minmax(0,_1fr)_auto]", "tw:viewport-560:grid-cols-[1fr]", "tw:gap-y-[14px]", "tw:viewport-900:gap-y-[7px]",
    "tw:gap-x-[14px]", "tw:items-center", "tw:min-h-[58px]", "tw:pt-[9px]",
    "tw:pr-[14px]", "tw:pb-[9px]", "tw:pl-[14px]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e8eef5]", "tw:text-[color:#3d536d]", "tw:text-[.78rem]",
    "tw:[&:last-child]:border-b-[length:0]", "tw:[&:last-child]:[border-bottom-style:none]", "tw:[&:last-child]:border-b-[color:currentColor]", "tw:hover:bg-[color:#f8fbff]",
    "tw:hover:[background-image:none]", "tw:[&_strong]:text-[color:#12365f]", "tw:[&_strong]:text-[.82rem]", "tw:[&_small]:block",
    "tw:[&_small]:mt-[3px]", "tw:[&_small]:text-[color:#73849a]", "tw:[&_small]:text-[.68rem]", "tw:[&_>_span]:text-[color:#58708d]",
    "tw:viewport-900:[&_>_:nth-child(n+3)]:[grid-column:1_/_-1]", "tw:viewport-560:[&_>_:nth-child(n+2)]:[grid-column:auto]",
  ].join(" "),
  "payment_connectors_list": [
    "payment-connectors-list", "tw:grid", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
  ].join(" "),
  "payment_connector_card": [
    "payment-connector-card", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)_auto]", "tw:viewport-680:grid-cols-[1fr]",
    "tw:items-center", "tw:gap-y-[18px]", "tw:viewport-680:gap-y-[12px]", "tw:gap-x-[18px]",
    "tw:viewport-680:gap-x-[12px]", "tw:min-h-[82px]", "tw:pt-[14px]", "tw:pr-[18px]",
    "tw:viewport-680:pr-[14px]", "tw:pb-[14px]", "tw:pl-[18px]", "tw:viewport-680:pl-[14px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dce7f2]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#dce7f2]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#dce7f2]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#dce7f2]",
    "tw:rounded-[13px]", "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[box-shadow:0_4px_12px_rgb(15_54_104_/_.025)]",
  ].join(" "),
  "payment_connector_copy": [
    "payment-connector-copy", "tw:flex", "tw:min-w-[0]", "tw:items-center",
    "tw:gap-y-[13px]", "tw:gap-x-[13px]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]",
    "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#14223f]", "tw:[&_h2]:text-[.94rem]",
    "tw:[&_p]:block", "tw:[&_p]:mt-[3px]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#687a91]", "tw:[&_p]:text-[.78rem]", "tw:[&_p]:leading-[1.4]",
    "tw:[&_small]:block", "tw:[&_small]:mt-[3px]", "tw:[&_small]:mr-[0]", "tw:[&_small]:mb-[0]",
    "tw:[&_small]:ml-[0]", "tw:[&_small]:text-[color:#687a91]", "tw:[&_small]:text-[.78rem]", "tw:[&_small]:leading-[1.4]",
  ].join(" "),
  "payment_connector_icon": [
    "payment-connector-icon", "tw:grid", "tw:w-[38px]", "tw:h-[38px]",
    "tw:[flex:0_0_38px]", "tw:place-items-center", "tw:rounded-[10px]", "tw:bg-[color:#eaf3ff]",
    "tw:[background-image:none]", "tw:text-[color:#1c63b7]", "tw:text-[.85rem]", "tw:font-[900]",
  ].join(" "),
  "payment_connector_card_payment_connector_expand": [
    "payment-connector-card", "payment-connector-expand", "tw:block", "tw:grid-cols-[minmax(0,_1fr)_auto]",
    "tw:viewport-680:grid-cols-[1fr]", "tw:items-center", "tw:gap-y-[18px]", "tw:viewport-680:gap-y-[12px]",
    "tw:gap-x-[18px]", "tw:viewport-680:gap-x-[12px]", "tw:min-h-[82px]", "tw:pt-[0]",
    "tw:pr-[0]", "tw:pb-[0]", "tw:pl-[0]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#dce7f2]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#dce7f2]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce7f2]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#dce7f2]", "tw:rounded-[13px]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[box-shadow:0_4px_12px_rgb(15_54_104_/_.025)]", "tw:[&_summary]:grid",
    "tw:[&_summary]:grid-cols-[minmax(0,_1fr)_auto]", "tw:viewport-760:[&_summary]:grid-cols-[1fr]", "tw:[&_summary]:items-center", "tw:[&_summary]:gap-y-[18px]",
    "tw:viewport-760:[&_summary]:gap-y-[10px]", "tw:[&_summary]:gap-x-[18px]", "tw:viewport-760:[&_summary]:gap-x-[10px]", "tw:[&_summary]:min-h-[82px]",
    "tw:[&_summary]:pt-[14px]", "tw:[&_summary]:pr-[18px]", "tw:[&_summary]:pb-[14px]", "tw:[&_summary]:pl-[18px]",
    "tw:[&_summary]:cursor-pointer", "tw:[&_summary]:[list-style:none]", "tw:[&_summary::-webkit-details-marker]:hidden", "tw:[&[open]_summary]:border-b-[length:1px]",
    "tw:[&[open]_summary]:[border-bottom-style:solid]", "tw:[&[open]_summary]:border-b-[color:#e3ebf3]", "tw:[&[open]_summary]:bg-[color:#fbfdff]", "tw:[&[open]_summary]:[background-image:none]",
    "tw:viewport-760:[&_summary_>_.connector-status]:[justify-self:start]",
  ].join(" "),
  "payment_connector_form": [
    "payment-connector-form", "tw:grid", "tw:grid-cols-[145px_minmax(0,_1fr)_auto]", "tw:viewport-760:grid-cols-[1fr]",
    "tw:[align-items:end]", "tw:viewport-760:items-stretch", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:pt-[14px]", "tw:pr-[18px]", "tw:pb-[16px]", "tw:pl-[18px]",
    "tw:bg-[color:#fbfdff]", "tw:[background-image:none]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[5px]",
    "tw:[&_label]:gap-x-[5px]", "tw:[&_label]:text-[color:#62738c]", "tw:[&_label]:text-[.69rem]", "tw:[&_label]:font-[800]",
    "tw:[&_label]:uppercase", "tw:[&_input]:min-w-[0]", "tw:[&_input]:min-h-[36px]", "tw:[&_input]:pt-[7px]",
    "tw:[&_input]:pr-[9px]", "tw:[&_input]:pb-[7px]", "tw:[&_input]:pl-[9px]", "tw:[&_input]:border-t-[length:1px]",
    "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#cdddeb]", "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]",
    "tw:[&_input]:border-r-[color:#cdddeb]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:#cdddeb]",
    "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#cdddeb]", "tw:[&_input]:rounded-[8px]",
    "tw:[&_input]:text-[color:#1e3858]", "tw:[&_input]:bg-[color:#fff]", "tw:[&_input]:[background-image:none]", "tw:[&_input]:[font:inherit]",
    "tw:[&_input]:normal-case", "tw:[&_select]:min-w-[0]", "tw:[&_select]:min-h-[36px]", "tw:[&_select]:pt-[7px]",
    "tw:[&_select]:pr-[9px]", "tw:[&_select]:pb-[7px]", "tw:[&_select]:pl-[9px]", "tw:[&_select]:border-t-[length:1px]",
    "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:#cdddeb]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]",
    "tw:[&_select]:border-r-[color:#cdddeb]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:#cdddeb]",
    "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#cdddeb]", "tw:[&_select]:rounded-[8px]",
    "tw:[&_select]:text-[color:#1e3858]", "tw:[&_select]:bg-[color:#fff]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:[font:inherit]",
    "tw:[&_select]:normal-case", "tw:[&_textarea]:min-w-[0]", "tw:[&_textarea]:min-h-[74px]", "tw:[&_textarea]:pt-[7px]",
    "tw:[&_textarea]:pr-[9px]", "tw:[&_textarea]:pb-[7px]", "tw:[&_textarea]:pl-[9px]", "tw:[&_textarea]:border-t-[length:1px]",
    "tw:[&_textarea]:[border-top-style:solid]", "tw:[&_textarea]:border-t-[color:#cdddeb]", "tw:[&_textarea]:border-r-[length:1px]", "tw:[&_textarea]:[border-right-style:solid]",
    "tw:[&_textarea]:border-r-[color:#cdddeb]", "tw:[&_textarea]:border-b-[length:1px]", "tw:[&_textarea]:[border-bottom-style:solid]", "tw:[&_textarea]:border-b-[color:#cdddeb]",
    "tw:[&_textarea]:border-l-[length:1px]", "tw:[&_textarea]:[border-left-style:solid]", "tw:[&_textarea]:border-l-[color:#cdddeb]", "tw:[&_textarea]:rounded-[8px]",
    "tw:[&_textarea]:text-[color:#1e3858]", "tw:[&_textarea]:bg-[color:#fff]", "tw:[&_textarea]:[background-image:none]", "tw:[&_textarea]:[font:inherit]",
    "tw:[&_textarea]:normal-case", "tw:[&_textarea]:[resize:vertical]",
  ].join(" "),
  "payment_connector_form_payment_connector_form_sicoob": [
    "payment-connector-form", "payment-connector-form-sicoob", "tw:grid", "tw:grid-cols-[repeat(3,_minmax(0,_1fr))]",
    "tw:viewport-760:grid-cols-[1fr]", "tw:[align-items:end]", "tw:viewport-760:items-stretch", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:pt-[14px]", "tw:pr-[18px]", "tw:pb-[16px]",
    "tw:pl-[18px]", "tw:bg-[color:#fbfdff]", "tw:[background-image:none]", "tw:[&_label]:grid",
    "tw:[&_label]:gap-y-[5px]", "tw:[&_label]:gap-x-[5px]", "tw:[&_label]:text-[color:#62738c]", "tw:[&_label]:text-[.69rem]",
    "tw:[&_label]:font-[800]", "tw:[&_label]:uppercase", "tw:[&_input]:min-w-[0]", "tw:[&_input]:min-h-[36px]",
    "tw:[&_input]:pt-[7px]", "tw:[&_input]:pr-[9px]", "tw:[&_input]:pb-[7px]", "tw:[&_input]:pl-[9px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#cdddeb]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#cdddeb]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:#cdddeb]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#cdddeb]",
    "tw:[&_input]:rounded-[8px]", "tw:[&_input]:text-[color:#1e3858]", "tw:[&_input]:bg-[color:#fff]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:[font:inherit]", "tw:[&_input]:normal-case", "tw:[&_select]:min-w-[0]", "tw:[&_select]:min-h-[36px]",
    "tw:[&_select]:pt-[7px]", "tw:[&_select]:pr-[9px]", "tw:[&_select]:pb-[7px]", "tw:[&_select]:pl-[9px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:#cdddeb]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#cdddeb]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:#cdddeb]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#cdddeb]",
    "tw:[&_select]:rounded-[8px]", "tw:[&_select]:text-[color:#1e3858]", "tw:[&_select]:bg-[color:#fff]", "tw:[&_select]:[background-image:none]",
    "tw:[&_select]:[font:inherit]", "tw:[&_select]:normal-case", "tw:[&_textarea]:min-w-[0]", "tw:[&_textarea]:min-h-[74px]",
    "tw:[&_textarea]:pt-[7px]", "tw:[&_textarea]:pr-[9px]", "tw:[&_textarea]:pb-[7px]", "tw:[&_textarea]:pl-[9px]",
    "tw:[&_textarea]:border-t-[length:1px]", "tw:[&_textarea]:[border-top-style:solid]", "tw:[&_textarea]:border-t-[color:#cdddeb]", "tw:[&_textarea]:border-r-[length:1px]",
    "tw:[&_textarea]:[border-right-style:solid]", "tw:[&_textarea]:border-r-[color:#cdddeb]", "tw:[&_textarea]:border-b-[length:1px]", "tw:[&_textarea]:[border-bottom-style:solid]",
    "tw:[&_textarea]:border-b-[color:#cdddeb]", "tw:[&_textarea]:border-l-[length:1px]", "tw:[&_textarea]:[border-left-style:solid]", "tw:[&_textarea]:border-l-[color:#cdddeb]",
    "tw:[&_textarea]:rounded-[8px]", "tw:[&_textarea]:text-[color:#1e3858]", "tw:[&_textarea]:bg-[color:#fff]", "tw:[&_textarea]:[background-image:none]",
    "tw:[&_textarea]:[font:inherit]", "tw:[&_textarea]:normal-case", "tw:[&_textarea]:[resize:vertical]", "tw:[&_label:nth-last-child(3)]:[grid-column:span_1]",
    "tw:[&_label:nth-last-child(2)]:[grid-column:span_1]", "tw:[&_.button]:[justify-self:start]",
  ].join(" "),
  "form_error": sharedUtilities.formError,
  "settings_list_filter": [
    "settings-list-filter", "tw:flex", "tw:flex-wrap", "tw:[align-items:end]",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:mt-[13px]", "tw:mr-[0]",
    "tw:mb-[13px]", "tw:ml-[0]", "tw:[&_input]:w-[min(280px,_100%)]", "tw:[&_input]:min-h-[33px]",
    "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[9px]", "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[9px]",
    "tw:[&_input]:text-[.76rem]", "tw:[&_select]:w-[min(280px,_100%)]", "tw:[&_select]:min-h-[33px]", "tw:[&_select]:pt-[0]",
    "tw:[&_select]:pr-[9px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[9px]", "tw:[&_select]:text-[.76rem]",
    "tw:viewport-700:[&_>_*]:[flex:1_1_100%]",
  ].join(" "),
  "settings_financial_category_list": [
    "settings-financial-category-list", "tw:[&_.settings-operational-head]:grid-cols-[minmax(220px,_1fr)_140px_auto]", "tw:[&_.settings-operational-row]:grid-cols-[minmax(220px,_1fr)_140px_auto]", "tw:viewport-700:[&_.settings-operational-row]:grid-cols-[minmax(0,_1fr)_auto]",
    "tw:viewport-700:[&_.settings-operational-row_>_:nth-child(n+3)]:[grid-column:1_/_-1]",
  ].join(" "),
  "grid_form_settings_inline_form": [
    "grid-form", "settings-inline-form", "tw:grid", "tw:gap-y-[14px]",
    "tw:gap-x-[14px]", "tw:grid-cols-[repeat(3,_minmax(130px,_1fr))]", "tw:viewport-700:grid-cols-[1fr]", "tw:[&_textarea]:w-[100%]",
    "tw:[&_textarea]:pt-[12px]", "tw:[&_textarea]:pr-[14px]", "tw:[&_textarea]:pb-[12px]", "tw:[&_textarea]:pl-[14px]",
    "tw:[&_textarea]:border-t-[length:1px]", "tw:[&_textarea]:[border-top-style:solid]", "tw:[&_textarea]:border-t-[color:var(--line)]", "tw:[&_textarea]:border-r-[length:1px]",
    "tw:[&_textarea]:[border-right-style:solid]", "tw:[&_textarea]:border-r-[color:var(--line)]", "tw:[&_textarea]:border-b-[length:1px]", "tw:[&_textarea]:[border-bottom-style:solid]",
    "tw:[&_textarea]:border-b-[color:var(--line)]", "tw:[&_textarea]:border-l-[length:1px]", "tw:[&_textarea]:[border-left-style:solid]", "tw:[&_textarea]:border-l-[color:var(--line)]",
    "tw:[&_textarea]:rounded-[var(--radius-md)]", "tw:[&_textarea]:bg-[color:var(--panel)]", "tw:[&_textarea]:[background-image:none]", "tw:[&_textarea]:text-[color:var(--text)]",
    "tw:[&_.field-submit]:[align-self:end]",
  ].join(" "),
  "settings_supplier_list": [
    "settings-supplier-list", "tw:[&_.settings-operational-head]:grid-cols-[minmax(220px,_1.15fr)_minmax(180px,_.9fr)_100px_auto]", "tw:[&_.settings-operational-row]:grid-cols-[minmax(220px,_1.15fr)_minmax(180px,_.9fr)_100px_auto]", "tw:viewport-700:[&_.settings-operational-row]:grid-cols-[minmax(0,_1fr)_auto]",
    "tw:[&_.settings-row-actions[open]_>_form]:w-[min(680px,_calc(100vw_-_72px))]", "tw:viewport-700:[&_.settings-row-actions[open]_>_form]:w-[min(100vw_-_48px,_680px)]", "tw:[&_.settings-row-actions[open]_>_form]:min-w-[0]", "tw:[&_.settings-inline-form]:grid-cols-[repeat(3,_minmax(130px,_1fr))]",
    "tw:viewport-700:[&_.settings-inline-form]:grid-cols-[1fr]", "tw:[&_.settings-row-actions]:[justify-self:start]", "tw:viewport-700:[&_.settings-operational-row_>_:nth-child(n+3)]:[grid-column:1_/_-1]",
  ].join(" "),
  "settings_balance_form": [
    "settings-balance-form", "tw:grid", "tw:grid-cols-[minmax(95px,_1fr)_auto]", "tw:viewport-560:grid-cols-[1fr_1fr]",
    "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:items-center", "tw:[&_input]:min-w-[0]",
    "tw:[&_input]:min-h-[31px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[8px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[8px]", "tw:[&_input]:text-[.72rem]", "tw:viewport-560:[&_input]:[grid-column:1_/_-1]",
  ].join(" "),
  "control_toggle": sharedUtilities.controlToggle,
} as const;
