import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "agenda_slot_entry": [
    "agenda-slot-entry", "tw:relative", "tw:flex", "tw:min-w-[0]",
    "tw:pr-[20px]", "tw:min-h-[100%]", "tw:[&_.agenda-slot-trigger]:[flex:1]", "tw:[&_.agenda-slot-trigger]:min-w-[0]",
  ].join(" "),
  "agenda_slot_trigger": [
    "agenda-slot-trigger", "tw:block", "tw:w-[100%]", "tw:min-h-[100%]",
    "tw:border-t-[length:0]", "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]",
    "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]",
    "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]",
    "tw:pt-[0]", "tw:pr-[0]", "tw:pb-[0]", "tw:pl-[0]",
    "tw:text-[color:inherit]", "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:text-left",
    "tw:cursor-pointer",
  ].join(" "),
  "agenda_slot_options": [
    "agenda-slot-options", "tw:absolute", "tw:top-[0]", "tw:right-[0]",
    "tw:z-[6]",
  ].join(" "),
  "agenda_slot_options_trigger": [
    "agenda-slot-options-trigger", "tw:grid", "tw:w-[18px]", "tw:h-[18px]",
    "tw:place-items-center", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(33_86_130_/_.15)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(33_86_130_/_.15)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(33_86_130_/_.15)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgb(33_86_130_/_.15)]", "tw:rounded-[5px]", "tw:bg-[color:rgb(255_255_255_/_.55)]", "tw:[background-image:none]",
    "tw:text-[color:#315b7d]", "tw:text-[.92rem]", "tw:font-[800]", "tw:leading-[1]",
    "tw:cursor-pointer", "tw:hover:bg-[color:#fff]", "tw:hover:[background-image:none]", "tw:hover:border-t-[color:#5c84a6]",
    "tw:hover:border-r-[color:#5c84a6]", "tw:hover:border-b-[color:#5c84a6]", "tw:hover:border-l-[color:#5c84a6]", "tw:[&[aria-expanded=true]]:bg-[color:#fff]",
    "tw:[&[aria-expanded=true]]:[background-image:none]", "tw:[&[aria-expanded=true]]:border-t-[color:#5c84a6]", "tw:[&[aria-expanded=true]]:border-r-[color:#5c84a6]", "tw:[&[aria-expanded=true]]:border-b-[color:#5c84a6]",
    "tw:[&[aria-expanded=true]]:border-l-[color:#5c84a6]",
  ].join(" "),
  "agenda_slot_options_menu": [
    "agenda-slot-options-menu", "tw:absolute", "tw:top-[calc(100%_+_4px)]", "tw:right-[0]",
    "tw:grid", "tw:min-w-[150px]", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line-strong)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line-strong)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line-strong)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line-strong)]",
    "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:[box-shadow:0_10px_22px_rgb(15_23_42_/_.18)]",
    "tw:[&_button]:pt-[8px]", "tw:[&_button]:pr-[10px]", "tw:[&_button]:pb-[8px]", "tw:[&_button]:pl-[10px]",
    "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]", "tw:[&_button]:border-r-[length:0]",
    "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:1px]", "tw:[&_button]:[border-bottom-style:solid]",
    "tw:[&_button]:border-b-[color:var(--line)]", "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]", "tw:[&_button]:border-l-[color:currentColor]",
    "tw:[&_button]:bg-[color:transparent]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:var(--text)]", "tw:[&_button]:text-left",
    "tw:[&_button]:text-[.74rem]", "tw:[&_button]:cursor-pointer", "tw:[&_button:last-child]:border-b-[length:0]", "tw:[&_button:last-child]:[border-bottom-style:none]",
    "tw:[&_button:last-child]:border-b-[color:currentColor]", "tw:[&_button:hover]:bg-[color:var(--brand-soft)]", "tw:[&_button:hover]:[background-image:none]", "tw:[&_.agenda-slot-option-cancel]:text-[color:#b42318]",
    "tw:[&_.agenda-slot-option-cancel:hover]:bg-[color:#fff1f0]", "tw:[&_.agenda-slot-option-cancel:hover]:[background-image:none]", "tw:[&_.agenda-slot-option-free]:text-[color:#9a5b00]", "tw:[&_.agenda-slot-option-free:hover]:bg-[color:#fff7e5]",
    "tw:[&_.agenda-slot-option-free:hover]:[background-image:none]",
  ].join(" "),
  "agenda_slot_backdrop": [
    "agenda-slot-backdrop", "tw:fixed", "tw:top-[0]", "tw:right-[0]",
    "tw:bottom-[0]", "tw:left-[0]", "tw:z-[80]", "tw:grid",
    "tw:place-items-center", "tw:pt-[20px]", "tw:pr-[20px]", "tw:pb-[20px]",
    "tw:pl-[20px]", "tw:bg-[color:rgb(15_23_42_/_.36)]", "tw:[background-image:none]", "tw:[backdrop-filter:blur(6px)]",
  ].join(" "),
  "agenda_slot_dialog_agenda_booking_dialog": [
    "agenda-slot-dialog", "agenda-booking-dialog", "tw:w-[min(100%,_1240px)]", "tw:viewport-680:w-[calc(100%_-_16px)]",
    "tw:grid", "tw:gap-y-[20px]", "tw:gap-x-[20px]", "tw:pt-[28px]",
    "tw:viewport-680:pt-[18px]", "tw:pr-[32px]", "tw:viewport-680:pr-[18px]", "tw:pb-[28px]",
    "tw:viewport-680:pb-[18px]", "tw:pl-[32px]", "tw:viewport-680:pl-[18px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[18px]",
    "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:[box-shadow:0_28px_80px_rgb(15_23_42_/_.28)]", "tw:[&_header]:flex",
    "tw:[&_header]:justify-between", "tw:[&_header]:gap-y-[14px]", "tw:[&_header]:gap-x-[14px]", "tw:[&_header]:items-start",
    "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]",
    "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
    "tw:[&_dl]:grid", "tw:[&_dl]:gap-y-[12px]", "tw:[&_dl]:gap-x-[12px]", "tw:[&_dl]:mt-[0]",
    "tw:[&_dl]:mr-[0]", "tw:[&_dl]:mb-[0]", "tw:[&_dl]:ml-[0]", "tw:[&_dl_div]:grid",
    "tw:[&_dl_div]:gap-y-[3px]", "tw:[&_dl_div]:gap-x-[3px]", "tw:[&_dl_div]:pb-[10px]", "tw:[&_dl_div]:border-b-[length:1px]",
    "tw:[&_dl_div]:[border-bottom-style:solid]", "tw:[&_dl_div]:border-b-[color:var(--line)]", "tw:[&_dt]:text-[color:var(--muted)]", "tw:[&_dt]:text-[.72rem]",
    "tw:[&_dt]:font-[700]", "tw:[&_dt]:uppercase", "tw:[&_dd]:mt-[0]", "tw:[&_dd]:mr-[0]",
    "tw:[&_dd]:mb-[0]", "tw:[&_dd]:ml-[0]", "tw:[&_dd]:font-[700]", "tw:max-h-[calc(100vh_-_24px)]",
    "tw:viewport-680:max-h-[calc(100vh_-_16px)]", "tw:[overflow-x:auto]", "tw:[overflow-y:auto]", "tw:[&_header_span]:text-[color:var(--muted)]",
    "tw:[&_header_span]:text-[.86rem]", "tw:[&_.button-primary:not(.agenda-add-athlete):not(.agenda-split-button)]:border-t-[color:#168149]", "tw:[&_.button-primary:not(.agenda-add-athlete):not(.agenda-split-button)]:border-r-[color:#168149]", "tw:[&_.button-primary:not(.agenda-add-athlete):not(.agenda-split-button)]:border-b-[color:#168149]",
    "tw:[&_.button-primary:not(.agenda-add-athlete):not(.agenda-split-button)]:border-l-[color:#168149]", "tw:[&_.button-primary:not(.agenda-add-athlete):not(.agenda-split-button)]:bg-[color:#188b50]", "tw:[&_.button-primary:not(.agenda-add-athlete):not(.agenda-split-button)]:[background-image:none]", "tw:[&_.button-primary:not(.agenda-add-athlete):not(.agenda-split-button)]:text-[color:#fff]",
    "tw:[&_button[type=submit]]:border-t-[color:#168149]", "tw:[&_button[type=submit]]:border-r-[color:#168149]", "tw:[&_button[type=submit]]:border-b-[color:#168149]", "tw:[&_button[type=submit]]:border-l-[color:#168149]",
    "tw:[&_button[type=submit]]:bg-[color:#188b50]", "tw:[&_button[type=submit]]:[background-image:none]", "tw:[&_button[type=submit]]:text-[color:#fff]", "tw:[&_.button-primary:not(.agenda-add-athlete):not(.agenda-split-button):hover]:bg-[color:#0f713d]",
    "tw:[&_.button-primary:not(.agenda-add-athlete):not(.agenda-split-button):hover]:[background-image:none]", "tw:[&_button[type=submit]:hover]:bg-[color:#0f713d]", "tw:[&_button[type=submit]:hover]:[background-image:none]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "agenda_reservation_client": [
    "agenda-reservation-client", "tw:inline-flex", "tw:items-center", "tw:viewport-720:items-start",
    "tw:gap-y-[8px]", "tw:viewport-720:gap-y-[5px]", "tw:gap-x-[8px]", "tw:viewport-720:gap-x-[5px]",
    "tw:mt-[9px]", "tw:[&_strong]:text-[color:#17345c]", "tw:[&_strong]:text-[.79rem]", "tw:viewport-720:flex-col",
  ].join(" "),
  "agenda_open_comandas_button": [
    "agenda-open-comandas-button", "tw:min-h-[26px]", "tw:pt-[4px]", "tw:pr-[7px]",
    "tw:pb-[4px]", "tw:pl-[7px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#cbd9ea]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#cbd9ea]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#cbd9ea]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#cbd9ea]", "tw:rounded-[6px]", "tw:bg-[color:#f8fbff]",
    "tw:[background-image:none]", "tw:text-[color:#1e5fa9]", "tw:[font:inherit]", "tw:text-[.68rem]",
    "tw:font-[750]", "tw:cursor-pointer", "tw:hover:border-t-[color:#2c74c7]", "tw:hover:border-r-[color:#2c74c7]",
    "tw:hover:border-b-[color:#2c74c7]", "tw:hover:border-l-[color:#2c74c7]", "tw:hover:bg-[color:#ecf5ff]", "tw:hover:[background-image:none]",
    "tw:disabled:opacity-[.6]", "tw:disabled:cursor-wait",
  ].join(" "),
  "button": sharedUtilities.button,
  "agenda_booking_form": [
    "agenda-booking-form", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)]", "tw:gap-y-[18px]",
    "tw:gap-x-[18px]", "tw:[&_>_label]:grid", "tw:[&_>_label]:gap-y-[6px]", "tw:[&_>_label]:gap-x-[6px]",
    "tw:[&_>_label]:text-[.78rem]", "tw:[&_>_label]:font-[700]", "tw:[&.agenda-booking-form_input]:w-[100%]", "tw:[&.agenda-booking-form_input]:min-h-[38px]",
    "tw:[&.agenda-booking-form_input]:pt-[8px]", "tw:[&.agenda-booking-form_input]:pr-[10px]", "tw:[&.agenda-booking-form_input]:pb-[8px]", "tw:[&.agenda-booking-form_input]:pl-[10px]",
    "tw:[&.agenda-booking-form_input]:border-t-[length:1px]", "tw:[&.agenda-booking-form_input]:[border-top-style:solid]", "tw:[&.agenda-booking-form_input]:border-t-[color:var(--line)]", "tw:[&.agenda-booking-form_input]:border-r-[length:1px]",
    "tw:[&.agenda-booking-form_input]:[border-right-style:solid]", "tw:[&.agenda-booking-form_input]:border-r-[color:var(--line)]", "tw:[&.agenda-booking-form_input]:border-b-[length:1px]", "tw:[&.agenda-booking-form_input]:[border-bottom-style:solid]",
    "tw:[&.agenda-booking-form_input]:border-b-[color:var(--line)]", "tw:[&.agenda-booking-form_input]:border-l-[length:1px]", "tw:[&.agenda-booking-form_input]:[border-left-style:solid]", "tw:[&.agenda-booking-form_input]:border-l-[color:var(--line)]",
    "tw:[&.agenda-booking-form_input]:rounded-[9px]", "tw:[&.agenda-booking-form_input]:bg-[color:var(--surface)]", "tw:[&.agenda-booking-form_input]:[background-image:none]", "tw:[&.agenda-booking-form_input]:text-[color:var(--text)]",
    "tw:[&.agenda-booking-form_input]:[font:inherit]", "tw:[&.agenda-booking-form_select]:w-[100%]", "tw:[&.agenda-booking-form_select]:min-h-[38px]", "tw:[&.agenda-booking-form_select]:pt-[8px]",
    "tw:[&.agenda-booking-form_select]:pr-[10px]", "tw:[&.agenda-booking-form_select]:pb-[8px]", "tw:[&.agenda-booking-form_select]:pl-[10px]", "tw:[&.agenda-booking-form_select]:border-t-[length:1px]",
    "tw:[&.agenda-booking-form_select]:[border-top-style:solid]", "tw:[&.agenda-booking-form_select]:border-t-[color:var(--line)]", "tw:[&.agenda-booking-form_select]:border-r-[length:1px]", "tw:[&.agenda-booking-form_select]:[border-right-style:solid]",
    "tw:[&.agenda-booking-form_select]:border-r-[color:var(--line)]", "tw:[&.agenda-booking-form_select]:border-b-[length:1px]", "tw:[&.agenda-booking-form_select]:[border-bottom-style:solid]", "tw:[&.agenda-booking-form_select]:border-b-[color:var(--line)]",
    "tw:[&.agenda-booking-form_select]:border-l-[length:1px]", "tw:[&.agenda-booking-form_select]:[border-left-style:solid]", "tw:[&.agenda-booking-form_select]:border-l-[color:var(--line)]", "tw:[&.agenda-booking-form_select]:rounded-[9px]",
    "tw:[&.agenda-booking-form_select]:bg-[color:var(--surface)]", "tw:[&.agenda-booking-form_select]:[background-image:none]", "tw:[&.agenda-booking-form_select]:text-[color:var(--text)]", "tw:[&.agenda-booking-form_select]:[font:inherit]",
    "tw:[&.agenda-booking-form_textarea]:w-[100%]", "tw:[&.agenda-booking-form_textarea]:min-h-[76px]", "tw:[&.agenda-booking-form_textarea]:pt-[8px]", "tw:[&.agenda-booking-form_textarea]:pr-[10px]",
    "tw:[&.agenda-booking-form_textarea]:pb-[8px]", "tw:[&.agenda-booking-form_textarea]:pl-[10px]", "tw:[&.agenda-booking-form_textarea]:border-t-[length:1px]", "tw:[&.agenda-booking-form_textarea]:[border-top-style:solid]",
    "tw:[&.agenda-booking-form_textarea]:border-t-[color:var(--line)]", "tw:[&.agenda-booking-form_textarea]:border-r-[length:1px]", "tw:[&.agenda-booking-form_textarea]:[border-right-style:solid]", "tw:[&.agenda-booking-form_textarea]:border-r-[color:var(--line)]",
    "tw:[&.agenda-booking-form_textarea]:border-b-[length:1px]", "tw:[&.agenda-booking-form_textarea]:[border-bottom-style:solid]", "tw:[&.agenda-booking-form_textarea]:border-b-[color:var(--line)]", "tw:[&.agenda-booking-form_textarea]:border-l-[length:1px]",
    "tw:[&.agenda-booking-form_textarea]:[border-left-style:solid]", "tw:[&.agenda-booking-form_textarea]:border-l-[color:var(--line)]", "tw:[&.agenda-booking-form_textarea]:rounded-[9px]", "tw:[&.agenda-booking-form_textarea]:bg-[color:var(--surface)]",
    "tw:[&.agenda-booking-form_textarea]:[background-image:none]", "tw:[&.agenda-booking-form_textarea]:text-[color:var(--text)]", "tw:[&.agenda-booking-form_textarea]:[font:inherit]", "tw:[&.agenda-booking-form_textarea]:[resize:vertical]",
    "tw:[&_>_label:nth-child(4)]:[grid-column:1_/_-1]", "tw:viewport-680:[&_>_label:nth-child(4)]:[grid-column:auto]", "tw:[&_footer]:[grid-column:auto]", "tw:[&_footer]:flex",
    "tw:[&_footer]:justify-end", "tw:[&_footer]:gap-y-[10px]", "tw:[&_footer]:gap-x-[10px]",
  ].join(" "),
  "agenda_booking_summary_grid": [
    "agenda-booking-summary-grid", "tw:grid", "tw:grid-cols-[repeat(4,_minmax(0,_1fr))]", "tw:viewport-960:grid-cols-[repeat(2,_minmax(0,_1fr))]",
    "tw:viewport-680:grid-cols-[1fr]", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
  ].join(" "),
  "agenda_booking_summary_card": [
    "agenda-booking-summary-card", "tw:grid", "tw:[align-content:start]", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:min-h-[118px]", "tw:viewport-680:min-h-[0]", "tw:pt-[14px]",
    "tw:pr-[14px]", "tw:pb-[14px]", "tw:pl-[14px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#d9e5f1]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#d9e5f1]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d9e5f1]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d9e5f1]", "tw:rounded-[10px]",
    "tw:bg-[color:#fbfdff]", "tw:[background-image:none]", "tw:[&_>_span]:text-[color:#5d748e]", "tw:[&_>_span]:text-[.66rem]",
    "tw:[&_>_span]:font-[850]", "tw:[&_>_span]:tracking-[.065em]", "tw:[&_>_strong]:text-[color:#112d52]", "tw:[&_>_strong]:text-[1rem]",
    "tw:[&_select]:min-h-[36px]", "tw:[&_input]:min-h-[36px]",
  ].join(" "),
  "agenda_price_editor": [
    "agenda-price-editor", "tw:pt-[0]", "tw:pr-[0]", "tw:pb-[0]",
    "tw:pl-[0]", "tw:border-t-[length:0]", "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]",
    "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]",
    "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]", "tw:[border-left-style:none]",
    "tw:border-l-[color:currentColor]", "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:text-[color:#0d4d93]",
    "tw:[font:inherit]", "tw:text-[1.05rem]", "tw:font-[850]", "tw:text-left",
    "tw:cursor-pointer",
  ].join(" "),
  "agenda_split_button": [
    "agenda-split-button", "tw:[justify-self:start]", "tw:pt-[0]", "tw:pr-[0]",
    "tw:pb-[0]", "tw:pl-[0]", "tw:border-t-[length:0]", "tw:[border-top-style:none]",
    "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:bg-[color:transparent]", "tw:[background-image:none]",
    "tw:text-[color:#2767a7]", "tw:[font:inherit]", "tw:text-[.74rem]", "tw:font-[750]",
    "tw:cursor-pointer",
  ].join(" "),
  "agenda_booking_summary_card_agenda_booking_datetime_card": [
    "agenda-booking-summary-card", "agenda-booking-datetime-card", "tw:grid", "tw:[align-content:start]",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:min-h-[118px]", "tw:viewport-680:min-h-[0]",
    "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]", "tw:pl-[14px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d9e5f1]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#d9e5f1]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#d9e5f1]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d9e5f1]",
    "tw:rounded-[10px]", "tw:bg-[color:#fbfdff]", "tw:[background-image:none]", "tw:[&_>_span]:text-[color:#5d748e]",
    "tw:[&_>_span]:text-[.66rem]", "tw:[&_>_span]:font-[850]", "tw:[&_>_span]:tracking-[.065em]", "tw:[&_>_strong]:text-[color:#112d52]",
    "tw:[&_>_strong]:text-[1rem]", "tw:[&_select]:min-h-[36px]", "tw:[&_input]:min-h-[36px]", "tw:[grid-column:span_1]",
    "tw:viewport-960:[grid-column:auto]", "tw:[&_>_div]:grid", "tw:[&_>_div]:grid-cols-[1fr_1fr]", "tw:[&_>_div]:gap-y-[7px]",
    "tw:[&_>_div]:gap-x-[7px]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[4px]", "tw:[&_label]:gap-x-[4px]",
    "tw:[&_label]:text-[color:#526b86]", "tw:[&_label]:text-[.67rem]", "tw:[&_label]:font-[750]", "tw:[&_label:first-child]:[grid-column:1_/_-1]",
    "tw:[&_small]:text-[color:#7a5d21]", "tw:[&_small]:text-[.68rem]",
  ].join(" "),
  "agenda_booking_extra": [
    "agenda-booking-extra", "tw:grid", "tw:grid-cols-[minmax(220px,_420px)]", "tw:viewport-680:grid-cols-[1fr]",
    "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:text-[color:#526b86]", "tw:text-[.76rem]",
    "tw:font-[750]", "tw:[&_textarea]:min-h-[68px]",
  ].join(" "),
  "agenda_super12_courts": [
    "agenda-super12-courts", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:[grid-column:1_/_-1]", "tw:pt-[12px]", "tw:pr-[12px]", "tw:pb-[12px]",
    "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[10px]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]",
    "tw:[&_>_div]:flex", "tw:[&_>_div]:flex-wrap", "tw:[&_>_div]:gap-y-[8px]", "tw:[&_>_div]:gap-x-[14px]",
    "tw:[&_label]:inline-flex", "tw:[&_label]:gap-y-[6px]", "tw:[&_label]:gap-x-[6px]", "tw:[&_label]:items-center",
    "tw:[&_label]:text-[.8rem]", "tw:[&_label]:font-[700]",
  ].join(" "),
  "agenda_participants": [
    "agenda-participants", "tw:[grid-column:1_/_-1]", "tw:viewport-680:[grid-column:auto]", "tw:grid",
    "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:pt-[16px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:grid-cols-[minmax(210px,_270px)_minmax(0,_1fr)]", "tw:viewport-960:grid-cols-[1fr]",
    "tw:[align-items:start]", "tw:pr-[0]", "tw:pb-[0]", "tw:pl-[0]",
    "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]",
    "tw:[&_h3]:text-[1rem]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:var(--muted)]", "tw:[&_p]:text-[.8rem]",
  ].join(" "),
  "agenda_client_search": [
    "agenda-client-search", "tw:relative", "tw:grid", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:max-w-[270px]", "tw:viewport-960:max-w-[340px]", "tw:[&_label]:grid",
    "tw:[&_label]:gap-y-[6px]", "tw:[&_label]:gap-x-[6px]", "tw:[&_label]:text-[color:#526b86]", "tw:[&_label]:text-[.74rem]",
    "tw:[&_label]:font-[750]", "tw:[&_.button]:[justify-self:start]", "tw:[&_.button]:min-h-[33px]", "tw:[&_.button]:[padding-inline:10px]",
    "tw:[&_.button]:text-[.73rem]", "tw:[&_.agenda-player-suggestions]:absolute", "tw:[&_.agenda-player-suggestions]:z-[2]", "tw:[&_.agenda-player-suggestions]:top-[68px]",
    "tw:[&_.agenda-player-suggestions]:w-[min(270px,_100%)]", "tw:[&_.agenda-player-suggestions]:max-h-[220px]", "tw:[&_.agenda-player-suggestions]:[overflow-x:auto]", "tw:[&_.agenda-player-suggestions]:[overflow-y:auto]",
    "tw:[&_.agenda-player-suggestions]:grid-cols-[1fr]", "tw:[&_.agenda-player-suggestions]:[box-shadow:0_10px_22px_rgb(20_60_95_/_.12)]",
  ].join(" "),
  "agenda_player_suggestions": [
    "agenda-player-suggestions", "tw:grid", "tw:grid-cols-[repeat(auto-fit,_minmax(160px,_1fr))]", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:pt-[7px]", "tw:pr-[7px]", "tw:pb-[7px]",
    "tw:pl-[7px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[8px]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]",
    "tw:[&_button]:pt-[7px]", "tw:[&_button]:pr-[9px]", "tw:[&_button]:pb-[7px]", "tw:[&_button]:pl-[9px]",
    "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]", "tw:[&_button]:border-r-[length:0]",
    "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:0]", "tw:[&_button]:[border-bottom-style:none]",
    "tw:[&_button]:border-b-[color:currentColor]", "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]", "tw:[&_button]:border-l-[color:currentColor]",
    "tw:[&_button]:rounded-[6px]", "tw:[&_button]:bg-[color:#fff]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:var(--brand-strong)]",
    "tw:[&_button]:[font:inherit]", "tw:[&_button]:text-[.78rem]", "tw:[&_button]:font-[700]", "tw:[&_button]:text-left",
    "tw:[&_button]:cursor-pointer", "tw:[&_button:hover]:bg-[color:var(--brand-soft)]", "tw:[&_button:hover]:[background-image:none]",
  ].join(" "),
  "agenda_participant_list": [
    "agenda-participant-list", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:min-w-[0]", "tw:[&_>_p]:mt-[8px]", "tw:[&_>_p]:mr-[0]", "tw:[&_>_p]:mb-[8px]",
    "tw:[&_>_p]:ml-[0]", "tw:[&_>_p]:text-[color:var(--muted)]", "tw:[&_>_p]:text-[.82rem]",
  ].join(" "),
  "agenda_participant_row": [
    "agenda-participant-row", "tw:grid", "tw:grid-cols-[minmax(150px,_1fr)_125px_minmax(155px,_.9fr)_auto]", "tw:viewport-680:grid-cols-[1fr_1fr]",
    "tw:gap-y-[9px]", "tw:gap-x-[9px]", "tw:[align-items:end]", "tw:pt-[10px]",
    "tw:pr-[12px]", "tw:pb-[10px]", "tw:pl-[12px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#e0e9f1]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#e0e9f1]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e0e9f1]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#e0e9f1]", "tw:rounded-[9px]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[4px]",
    "tw:[&_label]:gap-x-[4px]", "tw:[&_label]:text-[.67rem]", "tw:[&_label]:font-[750]", "tw:[&_label]:text-[color:#60758c]",
    "tw:[&_>_strong]:[align-self:center]", "tw:[&_>_strong]:text-[color:#153456]", "tw:[&_>_strong]:text-[.85rem]", "tw:[&.agenda-participant-row_input]:min-h-[34px]",
    "tw:[&.agenda-participant-row_input]:pt-[6px]", "tw:[&.agenda-participant-row_input]:pr-[8px]", "tw:[&.agenda-participant-row_input]:pb-[6px]", "tw:[&.agenda-participant-row_input]:pl-[8px]",
    "tw:[&.agenda-participant-row_select]:min-h-[34px]", "tw:[&.agenda-participant-row_select]:pt-[6px]", "tw:[&.agenda-participant-row_select]:pr-[8px]", "tw:[&.agenda-participant-row_select]:pb-[6px]",
    "tw:[&.agenda-participant-row_select]:pl-[8px]", "tw:[&_.button]:min-h-[34px]", "tw:[&_.button]:[padding-inline:10px]", "tw:[&_.button]:text-[.7rem]",
    "tw:[&_.button]:whitespace-nowrap", "tw:viewport-680:[&_>_strong]:[grid-column:1_/_-1]", "tw:viewport-680:[&_.button]:[justify-self:start]",
  ].join(" "),
  "button_button_danger": sharedUtilities.buttonButtonDanger,
  "form_error": sharedUtilities.formError,
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "agenda_quick_player": [
    "agenda-quick-player", "tw:grid", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
    "tw:mt-[14px]", "tw:pt-[18px]", "tw:pr-[18px]", "tw:pb-[18px]",
    "tw:pl-[18px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[12px]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]",
    "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]",
    "tw:[&_label]:grid", "tw:[&_label]:gap-y-[5px]", "tw:[&_label]:gap-x-[5px]", "tw:[&_label]:text-[.78rem]",
    "tw:[&_label]:font-[700]", "tw:[&_input]:min-h-[38px]", "tw:[&_input]:pt-[8px]", "tw:[&_input]:pr-[10px]",
    "tw:[&_input]:pb-[8px]", "tw:[&_input]:pl-[10px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]",
    "tw:[&_input]:border-t-[color:var(--line)]", "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]",
    "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]",
    "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[9px]", "tw:[&_div]:flex",
    "tw:[&_div]:justify-end", "tw:[&_div]:gap-y-[8px]", "tw:[&_div]:gap-x-[8px]",
  ].join(" "),
} as const;
