/** Local Tailwind utilities for this component. */
const styles = {
  attention: "arena-notification-attention",
  active: "arena-notification-active",
  readAll: "arena-notification-readAll",
  finance: "arena-notification-finance",
  arena: "arena-notification-arena",
  overdue: "arena-notification-overdue",
  "container": [
    "arena-notification-container", "tw:relative", "tw:w-[42px]", "tw:viewport-700:w-[40px]",
    "tw:h-[42px]", "tw:viewport-700:h-[40px]",
  ].join(" "),
  "trigger": [
    "arena-notification-trigger", "tw:relative", "tw:grid", "tw:w-[100%]",
    "tw:h-[100%]", "tw:place-items-center", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(129_211_235_/_.18)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(129_211_235_/_.18)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(129_211_235_/_.18)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(129_211_235_/_.18)]", "tw:rounded-[11px]", "tw:viewport-700:rounded-[10px]",
    "tw:text-[color:#eafff6]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_rgb(18_57_80_/_.72),_rgb(12_39_59_/_.72))]", "tw:[box-shadow:0_8px_18px_rgb(0_0_0_/_.13)]",
    "tw:cursor-pointer", "tw:hover:bg-[color:transparent]", "tw:hover:[background-image:linear-gradient(145deg,_rgb(25_72_98_/_.9),_rgb(14_48_70_/_.9))]", "tw:[&.arena-notification-trigger_svg]:w-[19px]",
    "tw:viewport-700:[&.arena-notification-trigger_svg]:w-[18px]", "tw:[&.arena-notification-trigger_svg]:h-[19px]", "tw:viewport-700:[&.arena-notification-trigger_svg]:h-[18px]", "tw:[&.arena-notification-trigger_svg]:[fill:#d8f7ff]",
    "tw:[&.arena-notification-trigger_svg]:[stroke:#d8f7ff]", "tw:[&.arena-notification-trigger_svg]:[stroke-linecap:round]", "tw:[&.arena-notification-trigger_svg]:[stroke-linejoin:round]", "tw:[&.arena-notification-trigger_svg]:[stroke-width:1.3]",
    "tw:[&.arena-notification-trigger_b]:absolute", "tw:[&.arena-notification-trigger_b]:top-[-5px]", "tw:[&.arena-notification-trigger_b]:right-[-5px]", "tw:[&.arena-notification-trigger_b]:min-w-[16px]",
    "tw:[&.arena-notification-trigger_b]:pt-[2px]", "tw:[&.arena-notification-trigger_b]:pr-[4px]", "tw:[&.arena-notification-trigger_b]:pb-[2px]", "tw:[&.arena-notification-trigger_b]:pl-[4px]",
    "tw:[&.arena-notification-trigger_b]:border-t-[length:2px]", "tw:[&.arena-notification-trigger_b]:[border-top-style:solid]", "tw:[&.arena-notification-trigger_b]:border-t-[color:#123a56]", "tw:[&.arena-notification-trigger_b]:border-r-[length:2px]",
    "tw:[&.arena-notification-trigger_b]:[border-right-style:solid]", "tw:[&.arena-notification-trigger_b]:border-r-[color:#123a56]", "tw:[&.arena-notification-trigger_b]:border-b-[length:2px]", "tw:[&.arena-notification-trigger_b]:[border-bottom-style:solid]",
    "tw:[&.arena-notification-trigger_b]:border-b-[color:#123a56]", "tw:[&.arena-notification-trigger_b]:border-l-[length:2px]", "tw:[&.arena-notification-trigger_b]:[border-left-style:solid]", "tw:[&.arena-notification-trigger_b]:border-l-[color:#123a56]",
    "tw:[&.arena-notification-trigger_b]:rounded-[999px]", "tw:[&.arena-notification-trigger_b]:text-[color:#fff]", "tw:[&.arena-notification-trigger_b]:bg-[color:#e0544e]", "tw:[&.arena-notification-trigger_b]:[background-image:none]",
    "tw:[&.arena-notification-trigger_b]:text-[.57rem]", "tw:[&.arena-notification-trigger_b]:leading-[1]", "tw:[&.arena-notification-trigger_b.arena-notification-attention]:w-[auto]", "tw:[&.arena-notification-trigger_b.arena-notification-attention]:min-w-[18px]",
    "tw:[&.arena-notification-trigger_b.arena-notification-attention]:h-[18px]", "tw:[&.arena-notification-trigger_b.arena-notification-attention]:pt-[1px]", "tw:[&.arena-notification-trigger_b.arena-notification-attention]:pr-[5px]", "tw:[&.arena-notification-trigger_b.arena-notification-attention]:pb-[1px]",
    "tw:[&.arena-notification-trigger_b.arena-notification-attention]:pl-[5px]", "tw:[&.arena-notification-trigger_b.arena-notification-attention]:text-[color:#fff]", "tw:[&.arena-notification-trigger_b.arena-notification-attention]:bg-[color:#dd3d45]", "tw:[&.arena-notification-trigger_b.arena-notification-attention]:[background-image:none]",
    "tw:[&.arena-notification-trigger_b.arena-notification-attention]:[box-shadow:0_0_0_2px_rgb(221_61_69_/_.18)]", "tw:[&.arena-notification-trigger_b.arena-notification-attention]:text-[.72rem]", "tw:[&.arena-notification-trigger_b.arena-notification-attention]:leading-[1.45]",
  ].join(" "),
  "modal": [
    "arena-notification-modal", "tw:absolute", "tw:z-[1001]", "tw:top-[calc(100%_+_9px)]",
    "tw:right-[0]", "tw:viewport-700:right-[-2px]", "tw:grid", "tw:w-[min(370px,_calc(100vw_-_28px))]",
    "tw:max-h-[min(530px,_calc(100vh_-_90px))]", "tw:[overflow-x:auto]", "tw:[overflow-y:auto]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#244a62]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#244a62]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#244a62]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#244a62]", "tw:rounded-[12px]",
    "tw:text-[color:#214963]", "tw:bg-[color:#f9fcff]", "tw:[background-image:none]", "tw:[box-shadow:0_22px_54px_rgb(0_13_27_/_.44)]",
    "tw:[&.arena-notification-modal_>_header]:flex", "tw:[&.arena-notification-modal_>_header]:items-center", "tw:[&.arena-notification-modal_>_header]:justify-between", "tw:[&.arena-notification-modal_>_header]:gap-y-[12px]",
    "tw:[&.arena-notification-modal_>_header]:gap-x-[12px]", "tw:[&.arena-notification-modal_>_header]:pt-[12px]", "tw:[&.arena-notification-modal_>_header]:pr-[13px]", "tw:[&.arena-notification-modal_>_header]:pb-[12px]",
    "tw:[&.arena-notification-modal_>_header]:pl-[13px]", "tw:[&.arena-notification-modal_>_header]:border-b-[length:1px]", "tw:[&.arena-notification-modal_>_header]:[border-bottom-style:solid]", "tw:[&.arena-notification-modal_>_header]:border-b-[color:#c9dce8]",
    "tw:[&.arena-notification-modal_>_header]:bg-[color:#103149]", "tw:[&.arena-notification-modal_>_header]:[background-image:none]", "tw:[&.arena-notification-modal_header_div]:grid", "tw:[&.arena-notification-modal_header_div]:gap-y-[2px]",
    "tw:[&.arena-notification-modal_header_div]:gap-x-[2px]", "tw:[&.arena-notification-modal_header_strong]:text-[color:#fff]", "tw:[&.arena-notification-modal_header_strong]:text-[.82rem]", "tw:[&.arena-notification-modal_header_span]:text-[color:#c2d9e8]",
    "tw:[&.arena-notification-modal_header_span]:text-[.68rem]", "tw:[&.arena-notification-modal_header_>_button]:w-[25px]", "tw:[&.arena-notification-modal_header_>_button]:h-[25px]", "tw:[&.arena-notification-modal_header_>_button]:border-t-[length:0]",
    "tw:[&.arena-notification-modal_header_>_button]:[border-top-style:none]", "tw:[&.arena-notification-modal_header_>_button]:border-t-[color:currentColor]", "tw:[&.arena-notification-modal_header_>_button]:border-r-[length:0]", "tw:[&.arena-notification-modal_header_>_button]:[border-right-style:none]",
    "tw:[&.arena-notification-modal_header_>_button]:border-r-[color:currentColor]", "tw:[&.arena-notification-modal_header_>_button]:border-b-[length:0]", "tw:[&.arena-notification-modal_header_>_button]:[border-bottom-style:none]", "tw:[&.arena-notification-modal_header_>_button]:border-b-[color:currentColor]",
    "tw:[&.arena-notification-modal_header_>_button]:border-l-[length:0]", "tw:[&.arena-notification-modal_header_>_button]:[border-left-style:none]", "tw:[&.arena-notification-modal_header_>_button]:border-l-[color:currentColor]", "tw:[&.arena-notification-modal_header_>_button]:rounded-[6px]",
    "tw:[&.arena-notification-modal_header_>_button]:text-[color:#fff]", "tw:[&.arena-notification-modal_header_>_button]:bg-[color:rgb(255_255_255_/_.16)]", "tw:[&.arena-notification-modal_header_>_button]:[background-image:none]", "tw:[&.arena-notification-modal_header_>_button]:text-[1.1rem]",
    "tw:[&.arena-notification-modal_header_>_button]:cursor-pointer", "tw:[&.arena-notification-modal_>_div]:grid", "tw:[&.arena-notification-modal_a]:grid", "tw:[&.arena-notification-modal_a]:grid-cols-[25px_minmax(0,_1fr)_auto]",
    "tw:[&.arena-notification-modal_a]:items-center", "tw:[&.arena-notification-modal_a]:gap-y-[8px]", "tw:[&.arena-notification-modal_a]:gap-x-[8px]", "tw:[&.arena-notification-modal_a]:pt-[10px]",
    "tw:[&.arena-notification-modal_a]:pr-[12px]", "tw:[&.arena-notification-modal_a]:pb-[10px]", "tw:[&.arena-notification-modal_a]:pl-[12px]", "tw:[&.arena-notification-modal_a]:border-b-[length:1px]",
    "tw:[&.arena-notification-modal_a]:[border-bottom-style:solid]", "tw:[&.arena-notification-modal_a]:border-b-[color:#d7e5ed]", "tw:[&.arena-notification-modal_a]:text-[color:inherit]", "tw:[&.arena-notification-modal_a]:bg-[color:#fff]",
    "tw:[&.arena-notification-modal_a]:[background-image:none]", "tw:[&.arena-notification-modal_a]:[text-decoration:none]", "tw:[&.arena-notification-modal_a:hover]:bg-[color:#eaf6f4]", "tw:[&.arena-notification-modal_a:hover]:[background-image:none]",
    "tw:[&.arena-notification-modal_a_>_i]:grid", "tw:[&.arena-notification-modal_a_>_i]:w-[24px]", "tw:[&.arena-notification-modal_a_>_i]:h-[24px]", "tw:[&.arena-notification-modal_a_>_i]:place-items-center",
    "tw:[&.arena-notification-modal_a_>_i]:rounded-[50%]", "tw:[&.arena-notification-modal_a_>_i]:text-[color:#177560]", "tw:[&.arena-notification-modal_a_>_i]:bg-[color:#e4f6ee]", "tw:[&.arena-notification-modal_a_>_i]:[background-image:none]",
    "tw:[&.arena-notification-modal_a_>_i]:text-[.62rem]", "tw:[&.arena-notification-modal_a_>_i]:not-italic", "tw:[&.arena-notification-modal_a_>_i]:font-[900]", "tw:[&.arena-notification-modal_a_>_i.arena-notification-finance]:text-[color:#1765a2]",
    "tw:[&.arena-notification-modal_a_>_i.arena-notification-finance]:bg-[color:#e7f1fd]", "tw:[&.arena-notification-modal_a_>_i.arena-notification-finance]:[background-image:none]", "tw:[&.arena-notification-modal_a_>_i.arena-notification-finance]:text-[.54rem]", "tw:[&.arena-notification-modal_a_>_i.arena-notification-arena]:text-[color:#9a6814]",
    "tw:[&.arena-notification-modal_a_>_i.arena-notification-arena]:bg-[color:#fff4d9]", "tw:[&.arena-notification-modal_a_>_i.arena-notification-arena]:[background-image:none]", "tw:[&.arena-notification-modal_a_>_i.arena-notification-overdue]:text-[color:#a81720]", "tw:[&.arena-notification-modal_a_>_i.arena-notification-overdue]:bg-[color:#ffe2e3]",
    "tw:[&.arena-notification-modal_a_>_i.arena-notification-overdue]:[background-image:none]", "tw:[&.arena-notification-modal_a_>_span]:grid", "tw:[&.arena-notification-modal_a_>_span]:min-w-[0]", "tw:[&.arena-notification-modal_a_>_span]:gap-y-[2px]",
    "tw:[&.arena-notification-modal_a_>_span]:gap-x-[2px]", "tw:[&.arena-notification-modal_a_strong]:[overflow-x:hidden]", "tw:[&.arena-notification-modal_a_strong]:[overflow-y:hidden]", "tw:[&.arena-notification-modal_a_strong]:text-[color:#123a56]",
    "tw:[&.arena-notification-modal_a_strong]:text-[.74rem]", "tw:[&.arena-notification-modal_a_strong]:text-ellipsis", "tw:[&.arena-notification-modal_a_strong]:whitespace-nowrap", "tw:[&.arena-notification-modal_a_small]:[display:-webkit-box]",
    "tw:[&.arena-notification-modal_a_small]:[overflow-x:hidden]", "tw:[&.arena-notification-modal_a_small]:[overflow-y:hidden]", "tw:[&.arena-notification-modal_a_small]:text-[color:#45647a]", "tw:[&.arena-notification-modal_a_small]:text-[.66rem]",
    "tw:[&.arena-notification-modal_a_small]:leading-[1.35]", "tw:[&.arena-notification-modal_a_small]:[-webkit-line-clamp:2]", "tw:[&.arena-notification-modal_a_small]:[-webkit-box-orient:vertical]", "tw:[&.arena-notification-modal_a_em]:pt-[4px]",
    "tw:[&.arena-notification-modal_a_em]:pr-[6px]", "tw:[&.arena-notification-modal_a_em]:pb-[4px]", "tw:[&.arena-notification-modal_a_em]:pl-[6px]", "tw:[&.arena-notification-modal_a_em]:border-t-[length:1px]",
    "tw:[&.arena-notification-modal_a_em]:[border-top-style:solid]", "tw:[&.arena-notification-modal_a_em]:border-t-[color:#aac7d8]", "tw:[&.arena-notification-modal_a_em]:border-r-[length:1px]", "tw:[&.arena-notification-modal_a_em]:[border-right-style:solid]",
    "tw:[&.arena-notification-modal_a_em]:border-r-[color:#aac7d8]", "tw:[&.arena-notification-modal_a_em]:border-b-[length:1px]", "tw:[&.arena-notification-modal_a_em]:[border-bottom-style:solid]", "tw:[&.arena-notification-modal_a_em]:border-b-[color:#aac7d8]",
    "tw:[&.arena-notification-modal_a_em]:border-l-[length:1px]", "tw:[&.arena-notification-modal_a_em]:[border-left-style:solid]", "tw:[&.arena-notification-modal_a_em]:border-l-[color:#aac7d8]", "tw:[&.arena-notification-modal_a_em]:rounded-[5px]",
    "tw:[&.arena-notification-modal_a_em]:text-[color:#075c91]", "tw:[&.arena-notification-modal_a_em]:bg-[color:#f5fbff]", "tw:[&.arena-notification-modal_a_em]:[background-image:none]", "tw:[&.arena-notification-modal_a_em]:text-[.62rem]",
    "tw:[&.arena-notification-modal_a_em]:not-italic", "tw:[&.arena-notification-modal_a_em]:font-[800]", "tw:[&.arena-notification-modal_>_p]:mt-[0]", "tw:[&.arena-notification-modal_>_p]:mr-[0]",
    "tw:[&.arena-notification-modal_>_p]:mb-[0]", "tw:[&.arena-notification-modal_>_p]:ml-[0]", "tw:[&.arena-notification-modal_>_p]:pt-[20px]", "tw:[&.arena-notification-modal_>_p]:pr-[13px]",
    "tw:[&.arena-notification-modal_>_p]:pb-[20px]", "tw:[&.arena-notification-modal_>_p]:pl-[13px]", "tw:[&.arena-notification-modal_>_p]:text-[color:#34566e]", "tw:[&.arena-notification-modal_>_p]:text-[.75rem]",
  ].join(" "),
  "tabs": [
    "arena-notification-tabs", "tw:flex", "tw:items-center", "tw:gap-y-[5px]",
    "tw:gap-x-[5px]", "tw:pt-[7px]", "tw:pr-[10px]", "tw:pb-[7px]",
    "tw:pl-[10px]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#cbdde8]",
    "tw:bg-[color:#eaf3f8]", "tw:[background-image:none]", "tw:[&.arena-notification-tabs_>_button]:border-t-[length:0]", "tw:[&.arena-notification-tabs_>_button]:[border-top-style:none]",
    "tw:[&.arena-notification-tabs_>_button]:border-t-[color:currentColor]", "tw:[&.arena-notification-tabs_>_button]:border-r-[length:0]", "tw:[&.arena-notification-tabs_>_button]:[border-right-style:none]", "tw:[&.arena-notification-tabs_>_button]:border-r-[color:currentColor]",
    "tw:[&.arena-notification-tabs_>_button]:border-b-[length:0]", "tw:[&.arena-notification-tabs_>_button]:[border-bottom-style:none]", "tw:[&.arena-notification-tabs_>_button]:border-b-[color:currentColor]", "tw:[&.arena-notification-tabs_>_button]:border-l-[length:0]",
    "tw:[&.arena-notification-tabs_>_button]:[border-left-style:none]", "tw:[&.arena-notification-tabs_>_button]:border-l-[color:currentColor]", "tw:[&.arena-notification-tabs_>_button]:rounded-[6px]", "tw:[&.arena-notification-tabs_>_button]:text-[color:#365a71]",
    "tw:[&.arena-notification-tabs_>_button]:bg-[color:transparent]", "tw:[&.arena-notification-tabs_>_button]:[background-image:none]", "tw:[&.arena-notification-tabs_>_button]:text-[.68rem]", "tw:[&.arena-notification-tabs_>_button]:font-[800]",
    "tw:[&.arena-notification-tabs_>_button]:cursor-pointer", "tw:[&.arena-notification-tabs_>_button.arena-notification-active]:text-[color:#064e3b]", "tw:[&.arena-notification-tabs_>_button.arena-notification-active]:bg-[color:#ccefe1]", "tw:[&.arena-notification-tabs_>_button.arena-notification-active]:[background-image:none]",
    "tw:[&.arena-notification-tabs_>_button:not(.arena-notification-readAll)]:pt-[6px]", "tw:[&.arena-notification-tabs_>_button:not(.arena-notification-readAll)]:pr-[8px]", "tw:[&.arena-notification-tabs_>_button:not(.arena-notification-readAll)]:pb-[6px]", "tw:[&.arena-notification-tabs_>_button:not(.arena-notification-readAll)]:pl-[8px]",
    "tw:[&.arena-notification-tabs_b]:ml-[4px]", "tw:[&.arena-notification-tabs_b]:pt-[1px]", "tw:[&.arena-notification-tabs_b]:pr-[4px]", "tw:[&.arena-notification-tabs_b]:pb-[1px]",
    "tw:[&.arena-notification-tabs_b]:pl-[4px]", "tw:[&.arena-notification-tabs_b]:rounded-[99px]", "tw:[&.arena-notification-tabs_b]:text-[color:#fff]", "tw:[&.arena-notification-tabs_b]:bg-[color:#da4b4b]",
    "tw:[&.arena-notification-tabs_b]:[background-image:none]", "tw:[&.arena-notification-tabs_b]:text-[.58rem]", "tw:[&.arena-notification-tabs_>_.arena-notification-readAll]:ml-[auto]", "tw:[&.arena-notification-tabs_>_.arena-notification-readAll]:pt-[6px]",
    "tw:[&.arena-notification-tabs_>_.arena-notification-readAll]:pr-[4px]", "tw:[&.arena-notification-tabs_>_.arena-notification-readAll]:pb-[6px]", "tw:[&.arena-notification-tabs_>_.arena-notification-readAll]:pl-[4px]", "tw:[&.arena-notification-tabs_>_.arena-notification-readAll]:text-[color:#075c91]",
    "tw:[&.arena-notification-tabs_>_button:disabled]:cursor-wait", "tw:[&.arena-notification-tabs_>_button:disabled]:opacity-[.6]",
  ].join(" "),
} as const;
export default styles;
