/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "athlete_login_page": [
    "athlete-login-page", "tw:grid", "tw:min-h-[100dvh]", "tw:place-items-center",
    "tw:pt-[24px]", "tw:viewport-760:pt-[14px]", "tw:pr-[24px]", "tw:viewport-760:pr-[14px]",
    "tw:pb-[24px]", "tw:viewport-760:pb-[14px]", "tw:pl-[24px]", "tw:viewport-760:pl-[14px]",
    "tw:bg-[color:#f1f5fa]", "tw:[background-image:none]", "tw:viewport-760:[align-items:start]",
  ].join(" "),
  "athlete_login_shell": [
    "athlete-login-shell", "tw:grid", "tw:viewport-760:block", "tw:grid-cols-[minmax(330px,_.9fr)_minmax(390px,_1.1fr)]",
    "tw:w-[min(1080px,_100%)]", "tw:min-h-[min(660px,_calc(100dvh_-_48px))]", "tw:viewport-760:min-h-[calc(100dvh_-_28px)]", "tw:[overflow-x:hidden]",
    "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d9e3ee]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d9e3ee]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d9e3ee]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#d9e3ee]", "tw:rounded-[18px]", "tw:viewport-760:rounded-[13px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[box-shadow:0_24px_70px_rgb(18_51_86_/_.12)]",
  ].join(" "),
  "athlete_login_brand": [
    "athlete-login-brand", "tw:flex", "tw:min-w-[0]", "tw:flex-col",
    "tw:justify-between", "tw:gap-y-[32px]", "tw:viewport-760:gap-y-[18px]", "tw:gap-x-[32px]",
    "tw:viewport-760:gap-x-[18px]", "tw:pt-[clamp(28px,_4vw,_54px)]", "tw:viewport-760:pt-[24px]", "tw:pr-[clamp(28px,_4vw,_54px)]",
    "tw:viewport-760:pr-[24px]", "tw:pb-[clamp(28px,_4vw,_54px)]", "tw:viewport-760:pb-[24px]", "tw:pl-[clamp(28px,_4vw,_54px)]",
    "tw:viewport-760:pl-[24px]", "tw:text-[color:#fff]", "tw:bg-[color:transparent]", "tw:[background-image:radial-gradient(circle_at_85%_16%,_rgb(65_166_231_/_.28),_transparent_30%),_linear-gradient(150deg,_#103e77,_#0a2955_72%)]",
    "tw:viewport-760:min-h-[200px]",
  ].join(" "),
  "athlete_login_identity": [
    "athlete-login-identity", "tw:flex", "tw:min-w-[0]", "tw:items-center",
    "tw:gap-y-[13px]", "tw:gap-x-[13px]", "tw:[&_>_img]:grid", "tw:[&_>_img]:w-[44px]",
    "tw:[&_>_img]:h-[44px]", "tw:[&_>_img]:[flex:0_0_44px]", "tw:[&_>_img]:place-items-center", "tw:[&_>_img]:border-t-[length:1px]",
    "tw:[&_>_img]:[border-top-style:solid]", "tw:[&_>_img]:border-t-[color:rgb(255_255_255_/_.45)]", "tw:[&_>_img]:border-r-[length:1px]", "tw:[&_>_img]:[border-right-style:solid]",
    "tw:[&_>_img]:border-r-[color:rgb(255_255_255_/_.45)]", "tw:[&_>_img]:border-b-[length:1px]", "tw:[&_>_img]:[border-bottom-style:solid]", "tw:[&_>_img]:border-b-[color:rgb(255_255_255_/_.45)]",
    "tw:[&_>_img]:border-l-[length:1px]", "tw:[&_>_img]:[border-left-style:solid]", "tw:[&_>_img]:border-l-[color:rgb(255_255_255_/_.45)]", "tw:[&_>_img]:rounded-[10px]",
    "tw:[&_>_img]:bg-[color:rgb(255_255_255_/_.12)]", "tw:[&_>_img]:[background-image:none]", "tw:[&_>_img]:text-[color:#fff]", "tw:[&_>_img]:text-[.9rem]",
    "tw:[&_>_img]:font-[850]", "tw:[&_>_img]:[object-fit:contain]", "tw:[&_>_span:last-child]:min-w-[0]", "tw:[&_strong]:block",
    "tw:[&_strong]:[overflow-wrap:anywhere]", "tw:[&_strong]:tracking-[.1em]", "tw:[&_strong]:text-[.88rem]", "tw:[&_small]:block",
    "tw:[&_small]:[overflow-wrap:anywhere]", "tw:[&_small]:tracking-[.1em]", "tw:[&_small]:mt-[3px]", "tw:[&_small]:text-[color:#c8e2fa]",
    "tw:[&_small]:text-[.57rem]",
  ].join(" "),
  "athlete_login_mark": [
    "athlete-login-mark", "tw:grid", "tw:w-[44px]", "tw:h-[44px]",
    "tw:[flex:0_0_44px]", "tw:place-items-center", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(255_255_255_/_.45)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(255_255_255_/_.45)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(255_255_255_/_.45)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(255_255_255_/_.45)]", "tw:rounded-[10px]", "tw:bg-[color:rgb(255_255_255_/_.12)]",
    "tw:[background-image:none]", "tw:text-[color:#fff]", "tw:text-[.9rem]", "tw:font-[850]",
    "tw:[object-fit:contain]",
  ].join(" "),
  "athlete_login_message": [
    "athlete-login-message", "tw:max-w-[420px]", "tw:[&_>_span]:text-[color:#69d6af]", "tw:[&_>_span]:text-[.69rem]",
    "tw:[&_>_span]:font-[800]", "tw:[&_>_span]:tracking-[.14em]", "tw:[&_h1]:mt-[14px]", "tw:viewport-760:[&_h1]:mt-[8px]",
    "tw:[&_h1]:mr-[0]", "tw:[&_h1]:mb-[16px]", "tw:viewport-760:[&_h1]:mb-[0]", "tw:[&_h1]:ml-[0]",
    "tw:[&_h1]:text-[clamp(2rem,_3.4vw,_3.1rem)]", "tw:viewport-760:[&_h1]:text-[1.4rem]", "tw:[&_h1]:font-[750]", "tw:[&_h1]:leading-[1.08]",
    "tw:[&_h1]:tracking-[-.045em]", "tw:[&_p]:text-[color:#d1e2f3]", "tw:[&_p]:leading-[1.6]", "tw:[&_p]:max-w-[350px]",
    "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
    "tw:[&_p]:text-[.95rem]", "tw:viewport-760:[&_h1]:max-w-[380px]", "tw:viewport-760:[&_>_span]:hidden", "tw:viewport-760:[&_p]:hidden",
  ].join(" "),
  "athlete_login_footer": [
    "athlete-login-footer", "tw:text-[color:#d1e2f3]", "tw:leading-[1.6]", "tw:mt-[0]",
    "tw:mr-[0]", "tw:mb-[0]", "tw:ml-[0]", "tw:text-[.75rem]",
    "tw:viewport-760:hidden",
  ].join(" "),
  "athlete_login_form_panel": [
    "athlete-login-form-panel", "tw:grid", "tw:min-w-[0]", "tw:place-items-center",
    "tw:pt-[clamp(28px,_5vw,_70px)]", "tw:viewport-760:pt-[32px]", "tw:pr-[clamp(28px,_5vw,_70px)]", "tw:viewport-760:pr-[24px]",
    "tw:pb-[clamp(28px,_5vw,_70px)]", "tw:viewport-760:pb-[40px]", "tw:pl-[clamp(28px,_5vw,_70px)]", "tw:viewport-760:pl-[24px]",
    "tw:[&_.public-client-auth]:w-[min(100%,_390px)]", "tw:[&_.public-client-auth]:max-w-[none]", "tw:[&_.public-client-auth]:mt-[0]", "tw:[&_.public-client-auth]:mr-[0]",
    "tw:viewport-760:[&_.public-client-auth]:mr-[auto]", "tw:[&_.public-client-auth]:mb-[0]", "tw:[&_.public-client-auth]:ml-[0]", "tw:viewport-760:[&_.public-client-auth]:ml-[auto]",
    "tw:[&_.public-client-auth]:pt-[0]", "tw:[&_.public-client-auth]:pr-[0]", "tw:[&_.public-client-auth]:pb-[0]", "tw:[&_.public-client-auth]:pl-[0]",
    "tw:[&_.public-client-auth]:border-t-[length:0]", "tw:[&_.public-client-auth]:[border-top-style:none]", "tw:[&_.public-client-auth]:border-t-[color:currentColor]", "tw:[&_.public-client-auth]:border-r-[length:0]",
    "tw:[&_.public-client-auth]:[border-right-style:none]", "tw:[&_.public-client-auth]:border-r-[color:currentColor]", "tw:[&_.public-client-auth]:border-b-[length:0]", "tw:[&_.public-client-auth]:[border-bottom-style:none]",
    "tw:[&_.public-client-auth]:border-b-[color:currentColor]", "tw:[&_.public-client-auth]:border-l-[length:0]", "tw:[&_.public-client-auth]:[border-left-style:none]", "tw:[&_.public-client-auth]:border-l-[color:currentColor]",
    "tw:[&_.public-client-auth]:rounded-[0]", "tw:[&_.public-client-auth]:bg-[color:transparent]", "tw:[&_.public-client-auth]:[background-image:none]", "tw:[&_.public-client-auth]:gap-y-[20px]",
    "tw:[&_.public-client-auth]:gap-x-[20px]", "tw:[&_.public-client-auth_header]:gap-y-[8px]", "tw:[&_.public-client-auth_header]:gap-x-[8px]", "tw:[&_.public-client-auth_header_>_span]:text-[color:#197258]",
    "tw:[&_.public-client-auth_header_>_span]:text-[.69rem]", "tw:[&_.public-client-auth_header_>_span]:font-[800]", "tw:[&_.public-client-auth_header_>_span]:tracking-[.14em]", "tw:[&_.public-client-auth_h2]:text-[color:#12345d]",
    "tw:[&_.public-client-auth_h2]:text-[clamp(1.8rem,_2.7vw,_2.4rem)]", "tw:[&_.public-client-auth_h2]:tracking-[-.04em]", "tw:[&_.public-client-auth_h2]:leading-[1.15]", "tw:[&_.public-client-auth_header_p]:text-[color:#667b91]",
    "tw:[&_.public-client-auth_header_p]:text-[.91rem]", "tw:[&_.public-client-auth_header_p]:leading-[1.5]", "tw:[&_.public-client-auth_form]:gap-y-[16px]", "tw:[&_.public-client-auth_form]:gap-x-[16px]",
    "tw:[&_.public-client-auth_.field]:gap-y-[7px]", "tw:[&_.public-client-auth_.field]:gap-x-[7px]", "tw:[&_.public-client-auth_.field]:text-[color:#233f5e]", "tw:[&_.public-client-auth_.field]:text-[.8rem]",
    "tw:[&_.public-client-auth_input]:min-h-[48px]", "tw:[&_.public-client-auth_input]:[padding-inline:13px]", "tw:[&_.public-client-auth_input]:border-t-[color:#cbd9e8]", "tw:[&_.public-client-auth_input]:border-r-[color:#cbd9e8]",
    "tw:[&_.public-client-auth_input]:border-b-[color:#cbd9e8]", "tw:[&_.public-client-auth_input]:border-l-[color:#cbd9e8]", "tw:[&_.public-client-auth_input]:rounded-[8px]", "tw:[&_.public-client-auth_input]:bg-[color:#fbfdff]",
    "tw:[&_.public-client-auth_input]:[background-image:none]", "tw:[&_.public-client-auth_input]:text-[.91rem]", "tw:[&_.public-client-auth_input:focus-visible]:[outline:2px_solid_#2876b7]", "tw:[&_.public-client-auth_input:focus-visible]:[outline-offset:2px]",
    "tw:[&_.public-client-auth_button:focus-visible]:[outline:2px_solid_#2876b7]", "tw:[&_.public-client-auth_button:focus-visible]:[outline-offset:2px]", "tw:[&_.public-client-auth_form_>_.button]:min-h-[46px]", "tw:[&_.public-client-auth_form_>_.button]:rounded-[8px]",
    "tw:[&_.public-client-auth_form_>_.button]:font-[750]", "tw:[&_.public-client-auth-actions_.button-primary]:min-h-[46px]", "tw:[&_.public-client-auth-actions_.button-primary]:rounded-[8px]", "tw:[&_.public-client-auth-actions_.button-primary]:font-[750]",
    "tw:[&_.public-client-auth-forgot]:mt-[-6px]", "tw:[&_.public-client-auth-forgot]:mr-[0]", "tw:[&_.public-client-auth-forgot]:mb-[0]", "tw:[&_.public-client-auth-forgot]:ml-[auto]",
    "tw:[&_.public-client-auth-forgot]:text-[color:#1b629b]", "tw:[&_.public-client-auth-forgot]:text-[.8rem]", "tw:[&_.public-client-auth-forgot]:[text-decoration:none]", "tw:[&_.public-client-auth-forgot:hover]:[text-decoration:underline]",
    "tw:[&_.public-client-auth-tabs]:pt-[4px]", "tw:[&_.public-client-auth-tabs]:pr-[4px]", "tw:[&_.public-client-auth-tabs]:pb-[4px]", "tw:[&_.public-client-auth-tabs]:pl-[4px]",
    "tw:[&_.public-client-auth-tabs]:rounded-[9px]", "tw:[&_.public-client-auth-tabs]:bg-[color:#eef3f8]", "tw:[&_.public-client-auth-tabs]:[background-image:none]", "tw:[&_.public-client-auth-tabs_button]:min-h-[39px]",
    "tw:[&_.public-client-auth-tabs_button]:text-[.82rem]", "tw:[&_.public-client-auth-tabs_button.active]:text-[color:#123e71]", "tw:[&_.public-client-auth_.muted]:pt-[17px]", "tw:[&_.public-client-auth_.muted]:border-t-[length:1px]",
    "tw:[&_.public-client-auth_.muted]:[border-top-style:solid]", "tw:[&_.public-client-auth_.muted]:border-t-[color:#e4ebf2]", "tw:[&_.public-client-auth_.muted]:text-[color:#667b91]", "tw:[&_.public-client-auth_.muted]:text-[.78rem]",
    "tw:[&_.public-client-auth_.muted]:leading-[1.5]", "tw:viewport-760:items-start",
  ].join(" "),
} as const;
