/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "client_portal_event_image_fallback": [
    "client-portal-event-image-fallback", "tw:grid", "tw:w-[100%]", "tw:[aspect-ratio:16_/_9]",
    "tw:place-items-center", "tw:[object-fit:cover]", "tw:text-[color:#dff8f3]", "tw:bg-[color:transparent]",
    "tw:[background-image:linear-gradient(135deg,_#0a5c61,_#102b46)]", "tw:text-[1.35rem]", "tw:font-[850]",
  ].join(" "),
  "client_portal_event_link": [
    "client-portal-event-link", "tw:block", "tw:leading-[0]",
  ].join(" "),
  "client_portal_event_posts": [
    "client-portal-event-posts", "tw:grid!", "tw:grid-cols-[repeat(auto-fill,_minmax(220px,_280px))]", "tw:viewport-620:grid-cols-[1fr]",
    "tw:gap-y-[12px]!", "tw:gap-x-[12px]!", "tw:[justify-content:start]", "tw:[&_article]:grid",
    "tw:[&_article]:grid-cols-[1fr]", "tw:[&_article]:gap-y-[0]", "tw:[&_article]:gap-x-[0]", "tw:[&_article]:[overflow-x:hidden]",
    "tw:[&_article]:[overflow-y:hidden]", "tw:[&_article]:pt-[0]", "tw:[&_article]:pr-[0]", "tw:[&_article]:pb-[0]",
    "tw:[&_article]:pl-[0]", "tw:[&_article]:border-t-[length:1px]", "tw:[&_article]:[border-top-style:solid]", "tw:[&_article]:border-t-[color:#dce7f0]",
    "tw:[&_article]:border-r-[length:1px]", "tw:[&_article]:[border-right-style:solid]", "tw:[&_article]:border-r-[color:#dce7f0]", "tw:[&_article]:border-b-[length:1px]",
    "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#dce7f0]", "tw:[&_article]:border-l-[length:1px]", "tw:[&_article]:[border-left-style:solid]",
    "tw:[&_article]:border-l-[color:#dce7f0]", "tw:[&_article]:rounded-[9px]", "tw:[&_article]:bg-[color:#fff]", "tw:[&_article]:[background-image:none]",
    "tw:[&_img]:w-[100%]", "tw:[&_img]:[aspect-ratio:16_/_9]", "tw:[&_img]:[object-fit:contain]", "tw:viewport-700:[&_img]:[object-fit:cover]",
    "tw:[&_img]:bg-[color:#0d2030]", "tw:viewport-620:[&_img]:bg-[color:#f2f6fa]", "tw:[&_img]:[background-image:none]", "tw:[&_article_>_div]:pt-[10px]",
    "tw:[&_article_>_div]:pr-[10px]", "tw:[&_article_>_div]:pb-[10px]", "tw:[&_article_>_div]:pl-[10px]", "tw:[&_article_>_div]:bg-[color:#112332]",
    "tw:[&_article_>_div]:[background-image:none]", "tw:[&_p]:whitespace-pre-wrap", "tw:viewport-700:[&_img]:max-h-[none]", "tw:[&_article_>_div_strong]:text-[color:#eef8fc]",
    "tw:[&_article_>_div_p]:text-[color:#a9c0ce]", "tw:viewport-700:[&_article]:w-[100%]",
  ].join(" "),
  "client_portal_event_carousel": [
    "client-portal-event-carousel", "tw:grid", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
    "tw:min-w-[0]",
  ].join(" "),
  "client_portal_event_carousel_track": [
    "client-portal-event-carousel-track", "tw:grid", "tw:[grid-auto-columns:minmax(220px,_280px)]", "tw:viewport-700:[grid-auto-columns:auto]",
    "tw:[grid-auto-flow:column]", "tw:viewport-700:[grid-auto-flow:row]", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:[overflow-x:auto]", "tw:viewport-700:[overflow-x:visible]", "tw:pt-[1px]", "tw:viewport-700:pt-[0]",
    "tw:pr-[1px]", "tw:viewport-700:pr-[0]", "tw:pb-[8px]", "tw:viewport-700:pb-[0]",
    "tw:pl-[1px]", "tw:viewport-700:pl-[0]", "tw:[scroll-snap-type:x_mandatory]", "tw:viewport-700:[scroll-snap-type:none]",
    "tw:[scrollbar-width:thin]", "tw:[&_article]:grid", "tw:[&_article]:grid-cols-[1fr]", "tw:[&_article]:gap-y-[0]",
    "tw:[&_article]:gap-x-[0]", "tw:[&_article]:[overflow-x:hidden]", "tw:[&_article]:[overflow-y:hidden]", "tw:[&_article]:pt-[0]",
    "tw:[&_article]:pr-[0]", "tw:[&_article]:pb-[0]", "tw:[&_article]:pl-[0]", "tw:[&_article]:border-t-[length:1px]",
    "tw:[&_article]:[border-top-style:solid]", "tw:[&_article]:border-t-[color:rgb(124_170_194_/_.24)]", "tw:[&_article]:border-r-[length:1px]", "tw:[&_article]:[border-right-style:solid]",
    "tw:[&_article]:border-r-[color:rgb(124_170_194_/_.24)]", "tw:[&_article]:border-b-[length:1px]", "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:rgb(124_170_194_/_.24)]",
    "tw:[&_article]:border-l-[length:1px]", "tw:[&_article]:[border-left-style:solid]", "tw:[&_article]:border-l-[color:rgb(124_170_194_/_.24)]", "tw:[&_article]:rounded-[9px]",
    "tw:[&_article]:bg-[color:#112332]", "tw:[&_article]:[background-image:none]", "tw:[&_article]:[scroll-snap-align:start]", "tw:[&_img]:grid",
    "tw:[&_img]:w-[100%]", "tw:[&_img]:[aspect-ratio:16_/_9]", "tw:[&_img]:place-items-center", "tw:[&_img]:[object-fit:contain]",
    "tw:viewport-700:[&_img]:[object-fit:cover]", "tw:[&_img]:bg-[color:#0d2030]", "tw:viewport-620:[&_img]:bg-[color:#f2f6fa]", "tw:[&_img]:[background-image:none]",
    "tw:[&_article_>_div]:pt-[10px]", "tw:[&_article_>_div]:pr-[10px]", "tw:[&_article_>_div]:pb-[10px]", "tw:[&_article_>_div]:pl-[10px]",
    "tw:[&_article_>_div]:bg-[color:#112332]", "tw:[&_article_>_div]:[background-image:none]", "tw:[&_p]:mt-[3px]", "tw:[&_p]:whitespace-pre-wrap",
    "tw:viewport-700:[&_img]:max-h-[none]", "tw:[&_article_>_div_strong]:text-[color:#eef8fc]", "tw:[&_article_>_div_p]:text-[color:#a9c0ce]", "tw:viewport-700:grid-cols-[1fr]",
    "tw:viewport-700:[overflow-y:visible]", "tw:viewport-700:[&_article]:w-[100%]",
  ].join(" "),
  "client_portal_event_carousel_controls": [
    "client-portal-event-carousel-controls", "tw:flex", "tw:viewport-700:hidden", "tw:items-center",
    "tw:justify-end", "tw:viewport-620:justify-center", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:text-[color:#a9becb]", "tw:text-[.74rem]", "tw:[&_button]:grid", "tw:[&_button]:w-[30px]",
    "tw:[&_button]:h-[30px]", "tw:[&_button]:place-items-center", "tw:[&_button]:pt-[0]", "tw:[&_button]:pr-[0]",
    "tw:[&_button]:pb-[0]", "tw:[&_button]:pl-[0]", "tw:[&_button]:border-t-[length:1px]", "tw:[&_button]:[border-top-style:solid]",
    "tw:[&_button]:border-t-[color:rgb(121_169_195_/_.28)]", "tw:[&_button]:border-r-[length:1px]", "tw:[&_button]:[border-right-style:solid]", "tw:[&_button]:border-r-[color:rgb(121_169_195_/_.28)]",
    "tw:[&_button]:border-b-[length:1px]", "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:rgb(121_169_195_/_.28)]", "tw:[&_button]:border-l-[length:1px]",
    "tw:[&_button]:[border-left-style:solid]", "tw:[&_button]:border-l-[color:rgb(121_169_195_/_.28)]", "tw:[&_button]:rounded-[7px]", "tw:[&_button]:bg-[color:#102737]",
    "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:#61c9ff]", "tw:[&_button]:cursor-pointer", "tw:[&_button:hover]:border-t-[color:#8eb7dc]",
    "tw:[&_button:hover]:border-r-[color:#8eb7dc]", "tw:[&_button:hover]:border-b-[color:#8eb7dc]", "tw:[&_button:hover]:border-l-[color:#8eb7dc]", "tw:[&_button:hover]:bg-[color:#f2f8fd]",
    "tw:[&_button:hover]:[background-image:none]", "tw:[&_svg]:w-[17px]", "tw:[&_svg]:h-[17px]", "tw:[&_svg]:[fill:none]",
    "tw:[&_svg]:[stroke:currentColor]", "tw:[&_svg]:[stroke-linecap:round]", "tw:[&_svg]:[stroke-linejoin:round]", "tw:[&_svg]:[stroke-width:2]",
  ].join(" "),
} as const;
