import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "dashboard_metric_modal_backdrop": [
    "dashboard-metric-modal-backdrop", "tw:fixed", "tw:z-[100]", "tw:top-[0]",
    "tw:right-[0]", "tw:bottom-[0]", "tw:left-[0]", "tw:grid",
    "tw:place-items-center", "tw:pt-[20px]", "tw:viewport-580:pt-[12px]", "tw:pr-[20px]",
    "tw:viewport-580:pr-[12px]", "tw:pb-[20px]", "tw:viewport-580:pb-[12px]", "tw:pl-[20px]",
    "tw:viewport-580:pl-[12px]", "tw:bg-[color:rgb(9_26_47_/_.42)]", "tw:[background-image:none]", "tw:[backdrop-filter:blur(3px)]",
    "tw:viewport-580:[align-items:end]",
  ].join(" "),
  "dashboard_metric_modal": [
    "dashboard-metric-modal", "tw:grid", "tw:gap-y-[17px]", "tw:gap-x-[17px]",
    "tw:w-[min(580px,_100%)]", "tw:max-h-[min(680px,_calc(100vh_-_40px))]", "tw:viewport-580:max-h-[calc(100vh_-_24px)]", "tw:[overflow-x:auto]",
    "tw:[overflow-y:auto]", "tw:pt-[21px]", "tw:viewport-580:pt-[17px]", "tw:pr-[21px]",
    "tw:viewport-580:pr-[17px]", "tw:pb-[21px]", "tw:viewport-580:pb-[17px]", "tw:pl-[21px]",
    "tw:viewport-580:pl-[17px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#cdddeb]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#cdddeb]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#cdddeb]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#cdddeb]", "tw:rounded-[14px]", "tw:viewport-580:rounded-[13px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[box-shadow:0_24px_70px_rgb(13_39_70_/_.25)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:items-start",
    "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[16px]", "tw:[&_>_header]:gap-x-[16px]", "tw:[&_>_header]:pb-[14px]",
    "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#e3ebf3]", "tw:[&_h2]:mt-[4px]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#15345d]",
    "tw:[&_h2]:text-[1.2rem]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_header_p:last-child]:mt-[5px]", "tw:[&_header_p:last-child]:text-[color:#6a7f98]", "tw:[&_header_p:last-child]:text-[.8rem]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "dashboard_metric_list": [
    "dashboard-metric-list", "tw:grid", "tw:[&_article]:grid", "tw:[&_article]:grid-cols-[34px_minmax(0,_1fr)_auto_auto]",
    "tw:viewport-580:[&_article]:grid-cols-[32px_minmax(0,_1fr)_auto]", "tw:[&_article]:items-center", "tw:[&_article]:gap-y-[10px]", "tw:[&_article]:gap-x-[10px]",
    "tw:[&_article]:pt-[10px]", "tw:[&_article]:pr-[0]", "tw:[&_article]:pb-[10px]", "tw:[&_article]:pl-[0]",
    "tw:[&_article]:border-b-[length:1px]", "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#e7eef5]", "tw:[&_article:last-child]:border-b-[length:0]",
    "tw:[&_article:last-child]:[border-bottom-style:none]", "tw:[&_article:last-child]:border-b-[color:currentColor]", "tw:[&_article_>_div]:grid", "tw:[&_article_>_div]:min-w-[0]",
    "tw:[&_article_>_div]:gap-y-[3px]", "tw:[&_article_>_div]:gap-x-[3px]", "tw:[&_strong]:[overflow-x:hidden]", "tw:[&_strong]:[overflow-y:hidden]",
    "tw:[&_strong]:text-[color:#1a375d]", "tw:[&_strong]:text-[.82rem]", "tw:[&_strong]:text-ellipsis", "tw:[&_strong]:whitespace-nowrap",
    "tw:[&_small]:text-[color:#6d8299]", "tw:[&_small]:text-[.72rem]", "tw:[&_time]:text-[color:#6d8299]", "tw:[&_time]:text-[.72rem]",
    "tw:[&_time]:whitespace-nowrap", "tw:[&_b]:text-[color:#173d67]", "tw:[&_b]:text-[.8rem]", "tw:[&_b]:whitespace-nowrap",
    "tw:viewport-580:[&_time]:[grid-column:2_/_-1]", "tw:viewport-580:[&_b_+_time]:[grid-column:auto]",
  ].join(" "),
  "dashboard_metric_list_icon": [
    "dashboard-metric-list-icon", "tw:grid", "tw:w-[34px]", "tw:h-[34px]",
    "tw:place-items-center", "tw:rounded-[50%]", "tw:bg-[color:#eaf3ff]", "tw:[background-image:none]",
    "tw:text-[color:#1763af]", "tw:text-[.72rem]", "tw:font-[800]",
  ].join(" "),
  "dashboard_metric_empty": [
    "dashboard-metric-empty", "tw:pt-[18px]", "tw:pr-[0]", "tw:pb-[18px]",
    "tw:pl-[0]", "tw:text-[color:#6a7e95]", "tw:text-[.84rem]", "tw:text-center",
  ].join(" "),
  "dashboard_stat_trigger": [
    "dashboard-stat-trigger", "tw:[&.is-dragging]:opacity-[.45]", "tw:cursor-pointer", "tw:relative",
    "tw:block", "tw:min-w-[0]", "tw:pt-[0]", "tw:pr-[0]",
    "tw:pb-[0]", "tw:pl-[0]", "tw:border-t-[length:0]", "tw:[border-top-style:none]",
    "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:bg-[color:transparent]", "tw:[background-image:none]",
    "tw:text-[color:inherit]", "tw:[font:inherit]", "tw:text-left", "tw:[&:active]:cursor-grabbing",
    "tw:[&_.stat-card]:h-[100%]", "tw:[&_.stat-card]:[transition:background_.16s_ease,_box-shadow_.16s_ease,_transform_.16s_ease]", "tw:[&:hover_.stat-card]:bg-[color:#f4f9ff]", "tw:[&:hover_.stat-card]:[background-image:none]",
    "tw:[&:hover_.stat-card]:[box-shadow:inset_0_0_0_1px_#b8d5ee]", "tw:[&:hover_.stat-card]:[transform:translateY(-1px)]", "tw:[&:focus-visible_.stat-card]:bg-[color:#f4f9ff]", "tw:[&:focus-visible_.stat-card]:[background-image:none]",
    "tw:[&:focus-visible_.stat-card]:[box-shadow:inset_0_0_0_1px_#b8d5ee]", "tw:[&:focus-visible_.stat-card]:[transform:translateY(-1px)]", "tw:[&:hover_.dashboard-stat-trigger-hint]:opacity-[1]", "tw:[&:hover_.dashboard-stat-trigger-hint]:[transform:translateY(0)]",
    "tw:[&:focus-visible_.dashboard-stat-trigger-hint]:opacity-[1]", "tw:[&:focus-visible_.dashboard-stat-trigger-hint]:[transform:translateY(0)]", "tw:focus-visible:[outline:2px_solid_var(--brand)]", "tw:focus-visible:[outline-offset:3px]",
    "tw:focus-visible:rounded-[8px]",
  ].join(" "),
  "dashboard_stat_trigger_hint": [
    "dashboard-stat-trigger-hint", "tw:absolute", "tw:right-[16px]", "tw:bottom-[10px]",
    "tw:text-[color:var(--brand-strong)]", "tw:text-[.66rem]", "tw:font-[750]", "tw:opacity-[0]",
    "tw:[transform:translateY(2px)]", "tw:[transition:opacity_.16s_ease,_transform_.16s_ease]",
  ].join(" "),
} as const;
