import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "dashboard_metric_modal_backdrop": [
    "dashboard-metric-modal-backdrop", "tw:fixed", "tw:z-[100]", "tw:top-[0]",
    "tw:right-[0]", "tw:bottom-[0]", "tw:left-[0]", "tw:grid",
    "tw:place-items-center", "tw:pt-[20px]", "tw:viewport-580:pt-[12px]", "tw:pr-[20px]",
    "tw:viewport-580:pr-[12px]", "tw:pb-[20px]", "tw:viewport-580:pb-[12px]", "tw:pl-[20px]",
    "tw:viewport-580:pl-[12px]", "tw:bg-[color:rgb(9_26_47_/_.42)]", "tw:[background-image:none]", "tw:[backdrop-filter:blur(3px)]",
    "tw:viewport-580:[align-items:end]",
  ].join(" "),
  "dashboard_metric_modal": [
    "dashboard-metric-modal", "tw:grid", "tw:gap-y-[17px]", "tw:gap-x-[17px]",
    "tw:w-[min(580px,_100%)]", "tw:max-h-[min(680px,_calc(100vh_-_40px))]", "tw:viewport-580:max-h-[calc(100vh_-_24px)]", "tw:[overflow-x:auto]",
    "tw:[overflow-y:auto]", "tw:pt-[21px]", "tw:viewport-580:pt-[17px]", "tw:pr-[21px]",
    "tw:viewport-580:pr-[17px]", "tw:pb-[21px]", "tw:viewport-580:pb-[17px]", "tw:pl-[21px]",
    "tw:viewport-580:pl-[17px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#cdddeb]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#cdddeb]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#cdddeb]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#cdddeb]", "tw:rounded-[14px]", "tw:viewport-580:rounded-[13px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[box-shadow:0_24px_70px_rgb(13_39_70_/_.25)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:items-start",
    "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[16px]", "tw:[&_>_header]:gap-x-[16px]", "tw:[&_>_header]:pb-[14px]",
    "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#e3ebf3]", "tw:[&_h2]:mt-[4px]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#15345d]",
    "tw:[&_h2]:text-[1.2rem]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_header_p:last-child]:mt-[5px]", "tw:[&_header_p:last-child]:text-[color:#6a7f98]", "tw:[&_header_p:last-child]:text-[.8rem]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "dashboard_metric_list": [
    "dashboard-metric-list", "tw:grid", "tw:[&_article]:grid", "tw:[&_article]:grid-cols-[34px_minmax(0,_1fr)_auto_auto]",
    "tw:viewport-580:[&_article]:grid-cols-[32px_minmax(0,_1fr)_auto]", "tw:[&_article]:items-center", "tw:[&_article]:gap-y-[10px]", "tw:[&_article]:gap-x-[10px]",
    "tw:[&_article]:pt-[10px]", "tw:[&_article]:pr-[0]", "tw:[&_article]:pb-[10px]", "tw:[&_article]:pl-[0]",
    "tw:[&_article]:border-b-[length:1px]", "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#e7eef5]", "tw:[&_article:last-child]:border-b-[length:0]",
    "tw:[&_article:last-child]:[border-bottom-style:none]", "tw:[&_article:last-child]:border-b-[color:currentColor]", "tw:[&_article_>_div]:grid", "tw:[&_article_>_div]:min-w-[0]",
    "tw:[&_article_>_div]:gap-y-[3px]", "tw:[&_article_>_div]:gap-x-[3px]", "tw:[&_strong]:[overflow-x:hidden]", "tw:[&_strong]:[overflow-y:hidden]",
    "tw:[&_strong]:text-[color:#1a375d]", "tw:[&_strong]:text-[.82rem]", "tw:[&_strong]:text-ellipsis", "tw:[&_strong]:whitespace-nowrap",
    "tw:[&_small]:text-[color:#6d8299]", "tw:[&_small]:text-[.72rem]", "tw:[&_time]:text-[color:#6d8299]", "tw:[&_time]:text-[.72rem]",
    "tw:[&_time]:whitespace-nowrap", "tw:[&_b]:text-[color:#173d67]", "tw:[&_b]:text-[.8rem]", "tw:[&_b]:whitespace-nowrap",
    "tw:viewport-580:[&_time]:[grid-column:2_/_-1]", "tw:viewport-580:[&_b_+_time]:[grid-column:auto]",
  ].join(" "),
  "dashboard_metric_list_icon": [
    "dashboard-metric-list-icon", "tw:grid", "tw:w-[34px]", "tw:h-[34px]",
    "tw:place-items-center", "tw:rounded-[50%]", "tw:bg-[color:#eaf3ff]", "tw:[background-image:none]",
    "tw:text-[color:#1763af]", "tw:text-[.72rem]", "tw:font-[800]",
  ].join(" "),
  "dashboard_metric_empty": [
    "dashboard-metric-empty", "tw:pt-[18px]", "tw:pr-[0]", "tw:pb-[18px]",
    "tw:pl-[0]", "tw:text-[color:#6a7e95]", "tw:text-[.84rem]", "tw:text-center",
  ].join(" "),
  "dashboard_stat_trigger": "dashboard-stat-trigger tw:grid tw:min-w-0 tw:gap-2 tw:rounded-xl tw:border tw:border-solid tw:border-[var(--line)] tw:bg-white tw:p-4 tw:text-left tw:cursor-pointer tw:hover:border-[var(--brand)] tw:focus-visible:outline-2 tw:focus-visible:outline-offset-2 tw:focus-visible:outline-[var(--brand)] tw:[&.is-dragging]:opacity-50 tw:[&_.stat-card]:border-0! tw:[&_.stat-card]:p-0! tw:[&_.stat-card]:shadow-none! tw:[&_.stat-card]:bg-transparent! tw:[&_.stat-card]:overflow-visible! tw:[&_.stat-card]:before:hidden! tw:[&_.stat-card_strong]:text-[1.5rem]! tw:[&_.stat-card_strong]:mt-2! tw:[&_.stat-card_strong]:leading-tight! tw:[&_.stat-card_strong]:[overflow-wrap:anywhere] tw:[&_.stat-card_span]:text-xs tw:[&_.stat-card_span]:mt-2",
  "dashboard_stat_trigger_hint": "dashboard-stat-trigger-hint tw:text-[10px] tw:text-[var(--muted)]",
} as const;
