"use client";

import { useState } from "react";
import { useFormState } from "react-dom";
import { confirmGlobalPublicPasswordResetAction, loginGlobalAthleteAction, requestGlobalPublicPasswordResetAction, type PublicClientAuthState } from "@/lib/actions/player-auth";
import { SubmitButton } from "@/components/forms/submit-button";

const initialState: PublicClientAuthState = { error: null };

export function GlobalAthleteAuthForm() {
  const [state, action] = useFormState(loginGlobalAthleteAction, initialState);
  const [requestState, requestAction] = useFormState(requestGlobalPublicPasswordResetAction, initialState);
  const [confirmState, confirmAction] = useFormState(confirmGlobalPublicPasswordResetAction, initialState);
  const [mode, setMode] = useState<"LOGIN" | "REQUEST" | "CONFIRM">("LOGIN");
  const currentState = mode === "LOGIN" ? state : mode === "REQUEST" ? requestState : confirmState;
  return <section className="public-client-auth"><header><span>CONTA DO ATLETA</span><h2>{mode === "LOGIN" ? "Entre no Portal do Atleta" : mode === "REQUEST" ? "Recupere sua senha" : "Crie uma nova senha"}</h2><p>{mode === "LOGIN" ? "Um único acesso para suas arenas, eventos, reservas e pagamentos." : "Enviaremos um código para o WhatsApp cadastrado."}</p></header>{mode === "LOGIN" ? <form action={action}><label className="field">Telefone<input name="phone" inputMode="tel" autoComplete="tel" required /></label><label className="field">Senha<input name="password" type="password" autoComplete="current-password" required /></label><button type="button" className="public-client-auth-forgot" onClick={() => setMode("REQUEST")}>Perdi minha senha</button><SubmitButton label="Entrar" pendingLabel="Entrando..." className="button button-primary" /></form> : mode === "REQUEST" ? <form action={async (formData) => { await requestAction(formData); setMode("CONFIRM"); }}><label className="field">Telefone cadastrado<input name="phone" inputMode="tel" autoComplete="tel" required /></label><div className="public-client-auth-actions"><button type="button" className="button button-small" onClick={() => setMode("LOGIN")}>Voltar</button><SubmitButton label="Enviar código" pendingLabel="Enviando..." className="button button-primary" /></div></form> : <form action={confirmAction}><label className="field">Telefone cadastrado<input name="phone" inputMode="tel" autoComplete="tel" required /></label><label className="field">Código de 6 dígitos<input name="code" inputMode="numeric" autoComplete="one-time-code" maxLength={6} required /></label><label className="field">Nova senha<input name="newPassword" type="password" autoComplete="new-password" minLength={8} required /></label><label className="field">Repita a nova senha<input name="confirmPassword" type="password" autoComplete="new-password" minLength={8} required /></label><div className="public-client-auth-actions"><button type="button" className="button button-small" onClick={() => setMode("LOGIN")}>Voltar</button><SubmitButton label="Salvar nova senha" pendingLabel="Salvando..." className="button button-primary" /></div></form>}{currentState?.error ? <p className={mode !== "LOGIN" && !currentState.error.includes("inválido") && !currentState.error.includes("expirado") && !currentState.error.includes("Revise") ? "form-message form-message-success" : "form-error"}>{currentState.error}</p> : null}{mode === "LOGIN" ? <p className="muted">Ainda não tem conta? Faça seu primeiro cadastro pelo link da sua arena.</p> : null}</section>;
}
