import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "public_client_auth": [
    "public-client-auth", "tw:[&_header_>_span]:text-[color:#08775f]", "tw:[&_header_>_span]:text-[.66rem]", "tw:[&_header_>_span]:font-[850]",
    "tw:[&_header_>_span]:tracking-[.08em]", "tw:grid", "tw:gap-y-[14px]", "tw:gap-x-[14px]",
    "tw:max-w-[560px]", "tw:mt-[28px]", "tw:mr-[auto]", "tw:mb-[10px]",
    "tw:ml-[auto]", "tw:pt-[22px]", "tw:pr-[22px]", "tw:pb-[22px]",
    "tw:pl-[22px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#b9d8e7]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#b9d8e7]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#b9d8e7]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#b9d8e7]", "tw:rounded-[13px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(140deg,_#edf8fc,_#f8fffc)]",
    "tw:[&_header]:grid", "tw:[&_header]:gap-y-[4px]", "tw:[&_header]:gap-x-[4px]", "tw:[&_h2]:mt-[0]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#073d62]",
    "tw:[&_h2]:text-[1.2rem]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_form]:grid", "tw:[&_form]:gap-y-[11px]", "tw:[&_form]:gap-x-[11px]",
    "tw:[&_.field]:grid", "tw:[&_.field]:gap-y-[5px]", "tw:[&_.field]:gap-x-[5px]", "tw:[&_.field]:text-[color:#43536b]",
    "tw:[&_.field]:text-[.76rem]", "tw:[&_.field]:font-[750]", "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[38px]",
    "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[10px]", "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[10px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#cbd9e8]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#cbd9e8]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:#cbd9e8]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#cbd9e8]",
    "tw:[&_input]:rounded-[var(--radius-control)]", "tw:[&_input]:bg-[color:#fff]", "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:#172033]",
    "tw:[&_input]:[font:inherit]",
  ].join(" "),
  "field": sharedUtilities.field,
  "public_client_auth_forgot": [
    "public-client-auth-forgot", "tw:w-[fit-content]", "tw:mt-[-2px]", "tw:mr-[0]",
    "tw:mb-[4px]", "tw:ml-[0]", "tw:pt-[0]", "tw:pr-[0]",
    "tw:pb-[0]", "tw:pl-[0]", "tw:border-t-[length:0]", "tw:[border-top-style:none]",
    "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:text-[color:#2479bc]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:text-[.76rem]", "tw:font-[750]", "tw:[text-decoration:underline]",
    "tw:cursor-pointer",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "public_client_auth_actions": [
    "public-client-auth-actions", "tw:flex", "tw:justify-between", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[&_.button]:min-w-[0]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "form_error": sharedUtilities.formError,
  "muted": sharedUtilities.muted,
} as const;
