/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "tv_stage_tv_stage_empty": [
    "tv-stage", "tv-stage-empty", "tw:min-h-[100vh]", "tw:grid",
    "tw:place-items-center", "tw:pt-[clamp(16px,_2vw,_30px)]", "tw:pr-[clamp(16px,_2vw,_30px)]", "tw:pb-[clamp(16px,_2vw,_30px)]",
    "tw:pl-[clamp(16px,_2vw,_30px)]", "tw:bg-[color:#061827]", "tw:[background-image:linear-gradient(90deg,_rgb(3_16_29_/_.93),_rgb(4_25_39_/_.78)_52%,_rgb(3_17_30_/_.9)),_url('/portal-padel-hero.png')]", "tw:[background-size:cover]",
    "tw:text-[color:#eaf7fb]", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:[animation:tv-ambient-shift_18s_ease-in-out_infinite_alternate]",
    "tw:[background-position:center]", "tw:[font-family:var(--font-body)]", "tw:text-center",
  ].join(" "),
  "tv_shell": [
    "tv-shell", "tw:relative", "tw:w-[min(1720px,_100%)]", "tw:min-h-[min(880px,_calc(100vh_-_32px))]",
    "tw:viewport-760:min-h-[calc(100vh_-_32px)]", "tw:grid", "tw:grid-rows-[auto_1fr_auto]", "tw:gap-y-[clamp(12px,_1.45vw,_22px)]",
    "tw:viewport-760:gap-y-[20px]", "tw:gap-x-[clamp(12px,_1.45vw,_22px)]", "tw:viewport-760:gap-x-[20px]", "tw:[animation:tv-slide-in_720ms_var(--ease-standard)]",
    "tw:pt-[clamp(18px,_2vw,_30px)]", "tw:pr-[clamp(18px,_2vw,_30px)]", "tw:pb-[clamp(18px,_2vw,_30px)]", "tw:pl-[clamp(18px,_2vw,_30px)]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(78_185_196_/_.28)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(78_185_196_/_.28)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgb(78_185_196_/_.28)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(78_185_196_/_.28)]",
    "tw:rounded-[12px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_rgb(10_38_57_/_.91),_rgb(6_25_43_/_.94))]", "tw:[box-shadow:inset_0_1px_rgb(255_255_255_/_.06),_0_28px_70px_rgb(0_0_0_/_.3)]",
    "tw:[backdrop-filter:blur(5px)]", "tw:[font-family:var(--font-body)]",
  ].join(" "),
  "tv_kicker": [
    "tv-kicker", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[6px]",
    "tw:ml-[0]", "tw:text-[color:#ffc44f]", "tw:text-[clamp(0.82rem,_1vw,_1rem)]", "tw:font-[900]",
    "tw:tracking-[0.16em]", "tw:uppercase",
  ].join(" "),
  "tv_arena_logo_tv_arena_logo_empty": [
    "tv-arena-logo", "tv-arena-logo-empty", "tw:w-[clamp(54px,_4.4vw,_78px)]", "tw:h-[auto]",
    "tw:rounded-[0]", "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:[box-shadow:none]",
    "tw:border-t-[length:0]", "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]",
    "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]",
    "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]",
    "tw:[object-fit:contain]", "tw:[margin-inline:auto]",
  ].join(" "),
  "tv_empty_copy": [
    "tv-empty-copy", "tw:mt-[32px]", "tw:mr-[auto]", "tw:mb-[0]",
    "tw:ml-[auto]", "tw:max-w-[780px]", "tw:text-[color:rgba(247,_251,_255,_0.78)]", "tw:text-[clamp(1.5rem,_2.4vw,_2.6rem)]",
    "tw:font-[700]",
  ].join(" "),
  "tv_stage": [
    "tv-stage", "tw:min-h-[100vh]", "tw:grid", "tw:place-items-center",
    "tw:pt-[clamp(16px,_2vw,_30px)]", "tw:pr-[clamp(16px,_2vw,_30px)]", "tw:pb-[clamp(16px,_2vw,_30px)]", "tw:pl-[clamp(16px,_2vw,_30px)]",
    "tw:bg-[color:#061827]", "tw:[background-image:linear-gradient(90deg,_rgb(3_16_29_/_.93),_rgb(4_25_39_/_.78)_52%,_rgb(3_17_30_/_.9)),_url('/portal-padel-hero.png')]", "tw:[background-size:cover]", "tw:text-[color:#eaf7fb]",
    "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:[animation:tv-ambient-shift_18s_ease-in-out_infinite_alternate]", "tw:[background-position:center]",
    "tw:[font-family:var(--font-body)]",
  ].join(" "),
  "tv_header": [
    "tv-header", "tw:grid", "tw:grid-cols-[minmax(260px,_1fr)_minmax(260px,_2fr)_minmax(100px,_1fr)]", "tw:viewport-760:grid-cols-[1fr_auto]",
    "tw:items-center", "tw:gap-y-[24px]", "tw:gap-x-[24px]", "tw:pb-[clamp(14px,_1.5vw,_22px)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(95_185_196_/_.2)]",
  ].join(" "),
  "tv_brand": [
    "tv-brand", "tw:flex", "tw:items-center", "tw:viewport-760:items-start",
    "tw:gap-y-[clamp(16px,_2vw,_26px)]", "tw:gap-x-[clamp(16px,_2vw,_26px)]", "tw:viewport-760:[grid-column:1]", "tw:viewport-760:[grid-row:2]",
  ].join(" "),
  "tv_arena_logo": [
    "tv-arena-logo", "tw:w-[clamp(54px,_4.4vw,_78px)]", "tw:h-[auto]", "tw:rounded-[0]",
    "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:[box-shadow:none]", "tw:border-t-[length:0]",
    "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]",
    "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:[object-fit:contain]",
  ].join(" "),
  "tv_brand_copy": [
    "tv-brand-copy", "tw:grid", "tw:viewport-760:hidden", "tw:min-w-[0]",
    "tw:gap-y-[4px]", "tw:gap-x-[4px]", "tw:[&_span]:text-[color:#4ee8b1]", "tw:[&_span]:text-[clamp(.62rem,_.75vw,_.82rem)]",
    "tw:[&_span]:font-[700]", "tw:[&_span]:tracking-[.12em]", "tw:[&_strong]:[overflow-x:hidden]", "tw:[&_strong]:[overflow-y:hidden]",
    "tw:[&_strong]:text-[color:#f1fbff]", "tw:[&_strong]:text-[clamp(.85rem,_1.1vw,_1.15rem)]", "tw:[&_strong]:text-ellipsis", "tw:[&_strong]:whitespace-nowrap",
    "tw:[&_strong]:font-[650]",
  ].join(" "),
  "tv_title": [
    "tv-title", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-[color:#f4fbff]", "tw:text-[clamp(2rem,_4vw,_4.8rem)]", "tw:viewport-760:text-[clamp(1.7rem,_8vw,_2.6rem)]",
    "tw:leading-[1]", "tw:font-[700]", "tw:tracking-[-.025em]", "tw:text-center",
    "tw:normal-case", "tw:[text-shadow:none]", "tw:[font-family:var(--font-body)]", "tw:viewport-760:[grid-column:1_/_-1]",
    "tw:viewport-760:[grid-row:2]",
  ].join(" "),
  "tv_counter": [
    "tv-counter", "tw:[justify-self:end]", "tw:flex", "tw:items-baseline",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:pt-[10px]", "tw:pr-[14px]",
    "tw:pb-[10px]", "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(81_203_186_/_.32)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(81_203_186_/_.32)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(81_203_186_/_.32)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(81_203_186_/_.32)]", "tw:rounded-[7px]", "tw:bg-[color:rgb(5_83_81_/_.42)]",
    "tw:[background-image:none]", "tw:[animation:tv-soft-pulse_3.8s_ease-in-out_infinite]", "tw:text-[color:#eafff8]", "tw:[&_span]:text-[clamp(1.45rem,_2.1vw,_2.2rem)]",
    "tw:[&_span]:font-[900]", "tw:[&_small]:text-[color:#a7d9d3]", "tw:[&_small]:text-[clamp(0.8rem,_0.98vw,_0.95rem)]", "tw:[&_small]:font-[800]",
    "tw:[&_small]:uppercase", "tw:viewport-760:[grid-column:2]", "tw:viewport-760:[grid-row:2]",
  ].join(" "),
  "tv_slide_frame": [
    "tv-slide-frame", "tw:[animation:tv-slide-in_620ms_var(--ease-standard)]",
  ].join(" "),
  "tv_matches_grid": [
    "tv-matches-grid", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-1120:grid-cols-[1fr]",
    "tw:[align-content:center]", "tw:gap-y-[clamp(14px,_1.65vw,_24px)]", "tw:gap-x-[clamp(14px,_1.65vw,_24px)]", "tw:viewport-760:[&_.tv-match-card:last-child]:[grid-column:auto]",
  ].join(" "),
  "tv_match_card": [
    "tv-match-card", "tw:relative", "tw:grid", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:min-h-[clamp(142px,_17.4vh,_176px)]", "tw:viewport-760:min-h-[auto]", "tw:pt-[clamp(13px,_1.45vw,_22px)]",
    "tw:viewport-760:pt-[20px]", "tw:pr-[clamp(13px,_1.45vw,_22px)]", "tw:viewport-760:pr-[20px]", "tw:pb-[clamp(13px,_1.45vw,_22px)]",
    "tw:viewport-760:pb-[20px]", "tw:pl-[clamp(13px,_1.45vw,_22px)]", "tw:viewport-760:pl-[20px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(106_197_210_/_.2)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:rgb(106_197_210_/_.2)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(106_197_210_/_.2)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(106_197_210_/_.2)]", "tw:rounded-[10px]",
    "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_rgb(17_64_84_/_.8),_rgb(10_39_60_/_.84))]", "tw:[box-shadow:0_18px_42px_rgb(0_0_0_/_.18)]", "tw:[overflow-x:hidden]",
    "tw:[overflow-y:hidden]", "tw:[animation:tv-row-enter_680ms_var(--ease-standard)_both]", "tw:[font-family:var(--font-body)]", "tw:[&:nth-child(2)]:[animation-delay:120ms]",
    "tw:[&:nth-child(3)]:[animation-delay:240ms]", "tw:[&::before]:[content:'']", "tw:[&::before]:absolute", "tw:[&::before]:top-[0]",
    "tw:[&::before]:right-[0]", "tw:[&::before]:bottom-[0]", "tw:[&::before]:left-[0]", "tw:[&::before]:bg-[color:transparent]",
    "tw:[&::before]:[background-image:linear-gradient(110deg,_transparent_0%,_rgba(255,_255,_255,_0.1)_42%,_transparent_68%)]", "tw:[&::before]:opacity-[0]", "tw:[&::before]:[transform:translateX(-120%)]", "tw:[&::before]:[animation:tv-row-sheen_6.5s_ease-in-out_infinite]",
    "tw:[&::before]:[pointer-events:none]", "tw:[&:nth-child(2)::before]:[animation-delay:900ms]", "tw:[&:nth-child(3)::before]:[animation-delay:1800ms]", "tw:viewport-1120:grid-cols-[minmax(116px,_0.42fr)_minmax(0,_1fr)]",
    "tw:viewport-760:grid-cols-[1fr]",
  ].join(" "),
  "tv_match_meta": [
    "tv-match-meta", "tw:grid", "tw:[justify-items:center]", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]", "tw:viewport-760:grid-cols-[1fr]",
  ].join(" "),
  "tv_match_topline": [
    "tv-match-topline", "tw:inline-flex", "tw:items-center", "tw:justify-center",
    "tw:flex-wrap", "tw:gap-y-[10px]", "tw:viewport-760:gap-y-[6px]", "tw:gap-x-[10px]",
    "tw:viewport-760:gap-x-[6px]", "tw:[justify-self:center]", "tw:min-h-[46px]", "tw:viewport-760:min-h-[36px]",
    "tw:pt-[8px]", "tw:viewport-760:pt-[6px]", "tw:pr-[18px]", "tw:viewport-760:pr-[9px]",
    "tw:pb-[8px]", "tw:viewport-760:pb-[6px]", "tw:pl-[18px]", "tw:viewport-760:pl-[9px]",
    "tw:rounded-[7px]", "tw:bg-[color:rgb(6_61_75_/_.86)]", "tw:[background-image:none]", "tw:text-[color:#dffaff]",
    "tw:text-[clamp(1.06rem,_1.22vw,_1.22rem)]", "tw:viewport-760:text-[.68rem]", "tw:font-[700]", "tw:tracking-[.025em]",
    "tw:uppercase", "tw:[animation:tv-label-lift_680ms_var(--ease-standard)_both]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(105_208_197_/_.3)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(105_208_197_/_.3)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(105_208_197_/_.3)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(105_208_197_/_.3)]",
  ].join(" "),
  "tv_match_separator": [
    "tv-match-separator", "tw:text-[color:rgb(214_246_249_/_.5)]",
  ].join(" "),
  "tv_match_time": [
    "tv-match-time", "tw:text-[color:#69efc4]", "tw:text-[clamp(1.26rem,_1.58vw,_1.6rem)]", "tw:viewport-760:text-[.76rem]",
    "tw:font-[900]", "tw:tracking-[0.02em]", "tw:whitespace-nowrap", "tw:[animation:tv-time-glow_4.5s_ease-in-out_infinite]",
  ].join(" "),
  "tv_court_name": [
    "tv-court-name", "tw:text-[color:#69efc4]", "tw:text-[clamp(1.02rem,_1.2vw,_1.24rem)]", "tw:viewport-760:text-[.76rem]",
    "tw:font-[900]", "tw:tracking-[0.06em]", "tw:uppercase", "tw:viewport-1120:[grid-column:2]",
    "tw:viewport-1120:[justify-self:start]", "tw:viewport-760:text-center",
  ].join(" "),
  "tv_match_status": [
    "tv-match-status", "tw:inline-flex", "tw:items-center", "tw:justify-center",
    "tw:min-h-[32px]", "tw:pt-[0]", "tw:pr-[14px]", "tw:pb-[0]",
    "tw:pl-[14px]", "tw:rounded-[6px]", "tw:bg-[color:rgb(0_31_50_/_.35)]", "tw:[background-image:none]",
    "tw:text-[color:#c4e5ea]", "tw:text-[0.84rem]", "tw:font-[700]", "tw:tracking-[.04em]",
    "tw:uppercase", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(126_204_217_/_.2)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(126_204_217_/_.2)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(126_204_217_/_.2)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgb(126_204_217_/_.2)]", "tw:[&.tv-match-status-live]:bg-[color:rgba(28,_140,_94,_0.2)]", "tw:[&.tv-match-status-live]:[background-image:none]", "tw:[&.tv-match-status-live]:text-[color:#7cffbf]",
    "tw:[&.tv-match-status-finished]:bg-[color:rgb(10_101_82_/_.34)]", "tw:[&.tv-match-status-finished]:[background-image:none]", "tw:[&.tv-match-status-finished]:text-[color:#79f0c2]", "tw:[&.tv-match-status-finished]:border-t-[color:rgb(88_203_183_/_.28)]",
    "tw:[&.tv-match-status-finished]:border-r-[color:rgb(88_203_183_/_.28)]", "tw:[&.tv-match-status-finished]:border-b-[color:rgb(88_203_183_/_.28)]", "tw:[&.tv-match-status-finished]:border-l-[color:rgb(88_203_183_/_.28)]",
  ].join(" "),
  "tv_scoreboard": [
    "tv-scoreboard", "tw:grid", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
  ].join(" "),
  "tv_score_row": [
    "tv-score-row", "tw:grid", "tw:grid-cols-[22px_minmax(0,_1.32fr)_auto_22px_minmax(0,_1.32fr)]", "tw:viewport-760:grid-cols-[13px_minmax(0,_1fr)_auto_13px_minmax(0,_1fr)]",
    "tw:items-center", "tw:gap-y-[clamp(8px,_0.8vw,_12px)]", "tw:gap-x-[clamp(8px,_0.8vw,_12px)]", "tw:[&_.tv-team-name:nth-of-type(2)::after]:[animation-delay:700ms]",
    "tw:viewport-760:[&_.tv-vs-line]:[grid-column:1_/_-1]", "tw:viewport-760:[&_.tv-vs-line]:[justify-self:center]",
  ].join(" "),
  "tv_team_side_tv_team_side_home": [
    "tv-team-side", "tv-team-side-home", "tw:w-[100%]", "tw:h-[clamp(38px,_4.45vw,_52px)]",
    "tw:rounded-[7px_0_0_7px]", "tw:[box-shadow:inset_0_0_0_1px_rgba(255,_255,_255,_0.18)]", "tw:bg-[color:#22bb86]", "tw:[background-image:none]",
  ].join(" "),
  "tv_team_name": [
    "tv-team-name", "tw:relative", "tw:block", "tw:min-w-[0]",
    "tw:min-h-[clamp(54px,_5.4vw,_68px)]", "tw:viewport-760:min-h-[46px]", "tw:pt-[clamp(13px,_1.35vw,_17px)]", "tw:viewport-760:pt-[11px]",
    "tw:pr-[clamp(18px,_1.8vw,_24px)]", "tw:viewport-760:pr-[11px]", "tw:pb-[clamp(13px,_1.35vw,_17px)]", "tw:viewport-760:pb-[11px]",
    "tw:pl-[clamp(18px,_1.8vw,_24px)]", "tw:viewport-760:pl-[11px]", "tw:rounded-[0_6px_6px_0]", "tw:bg-[color:rgb(237_251_253_/_.96)]",
    "tw:[background-image:none]", "tw:text-[color:#0a3045]", "tw:text-[clamp(1.24rem,_1.85vw,_1.95rem)]", "tw:viewport-760:text-[.9rem]",
    "tw:leading-[1]", "tw:tracking-[0]", "tw:normal-case", "tw:[overflow-wrap:anywhere]",
    "tw:[box-shadow:0_10px_22px_rgb(0_0_0_/_.14)]", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(112_204_214_/_.26)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:rgb(112_204_214_/_.26)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(112_204_214_/_.26)]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:font-[650]",
    "tw:[&::after]:[content:'']", "tw:[&::after]:absolute", "tw:[&::after]:top-[0]", "tw:[&::after]:right-[0]",
    "tw:[&::after]:bottom-[0]", "tw:[&::after]:left-[0]", "tw:[&::after]:bg-[color:transparent]", "tw:[&::after]:[background-image:linear-gradient(105deg,_transparent_0%,_rgba(255,_196,_79,_0.22)_46%,_transparent_70%)]",
    "tw:[&::after]:[transform:translateX(-130%)]", "tw:[&::after]:[animation:tv-name-sheen_5.8s_ease-in-out_infinite]", "tw:[&::after]:[pointer-events:none]",
  ].join(" "),
  "tv_vs_line": [
    "tv-vs-line", "tw:text-[color:#ffffff]", "tw:text-[clamp(1.06rem,_1.3vw,_1.34rem)]", "tw:font-[900]",
    "tw:tracking-[0.08em]", "tw:uppercase",
  ].join(" "),
  "tv_team_side_tv_team_side_away": [
    "tv-team-side", "tv-team-side-away", "tw:w-[100%]", "tw:h-[clamp(38px,_4.45vw,_52px)]",
    "tw:rounded-[7px_0_0_7px]", "tw:[box-shadow:inset_0_0_0_1px_rgba(255,_255,_255,_0.18)]", "tw:bg-[color:#218bc2]", "tw:[background-image:none]",
  ].join(" "),
  "tv_calendar_stage": [
    "tv-calendar-stage", "tw:grid", "tw:gap-y-[18px]", "tw:gap-x-[18px]",
  ].join(" "),
  "tv_calendar_head": [
    "tv-calendar-head", "tw:grid", "tw:[justify-items:center]", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:text-center", "tw:[&_strong]:text-[color:rgba(255,_255,_255,_0.88)]", "tw:[&_strong]:text-[clamp(1.2rem,_1.6vw,_1.5rem)]",
    "tw:[&_strong]:font-[800]",
  ].join(" "),
  "tv_info_kicker": [
    "tv-info-kicker", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-[color:#4ee8b1]", "tw:text-[0.92rem]", "tw:font-[700]",
    "tw:tracking-[.06em]", "tw:uppercase",
  ].join(" "),
  "tv_calendar_list": [
    "tv-calendar-list", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-1120:grid-cols-[1fr]",
    "tw:gap-y-[clamp(16px,_1.4vw,_22px)]", "tw:gap-x-[clamp(16px,_1.4vw,_22px)]",
  ].join(" "),
  "tv_calendar_card": [
    "tv-calendar-card", "tw:grid", "tw:grid-cols-[176px_minmax(0,_1fr)]", "tw:viewport-760:grid-cols-[1fr]",
    "tw:gap-y-[18px]", "tw:gap-x-[18px]", "tw:items-center", "tw:min-h-[112px]",
    "tw:pt-[20px]", "tw:pr-[22px]", "tw:pb-[20px]", "tw:pl-[22px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(106_197_210_/_.2)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(106_197_210_/_.2)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgb(106_197_210_/_.2)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(106_197_210_/_.2)]",
    "tw:rounded-[10px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_rgb(17_64_84_/_.8),_rgb(10_39_60_/_.84))]", "tw:[box-shadow:0_18px_42px_rgb(0_0_0_/_.18)]",
    "tw:[font-family:var(--font-body)]",
  ].join(" "),
  "tv_calendar_date": [
    "tv-calendar-date", "tw:grid", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:[&_span]:text-[color:rgba(255,_255,_255,_0.7)]", "tw:[&_span]:text-[0.92rem]", "tw:[&_span]:font-[800]", "tw:[&_span]:tracking-[0.08em]",
    "tw:[&_span]:uppercase", "tw:[&_strong]:text-[color:#65efbf]", "tw:[&_strong]:text-[clamp(1.5rem,_2.2vw,_2.2rem)]", "tw:[&_strong]:font-[700]",
    "tw:[&_strong]:tracking-[.06em]",
  ].join(" "),
  "tv_calendar_copy": [
    "tv-calendar-copy", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:[&_small]:text-[color:#65efbf]", "tw:[&_small]:text-[0.9rem]", "tw:[&_small]:font-[700]", "tw:[&_small]:tracking-[.06em]",
    "tw:[&_small]:uppercase", "tw:[&_strong]:text-[color:#ffffff]", "tw:[&_strong]:text-[clamp(1.2rem,_1.8vw,_1.8rem)]", "tw:[&_strong]:leading-[1.08]",
    "tw:[&_strong]:font-[700]", "tw:[&_span]:text-[color:#bbdce3]", "tw:[&_span]:text-[clamp(0.98rem,_1.28vw,_1.18rem)]", "tw:[&_span]:font-[600]",
  ].join(" "),
  "tv_sponsor_stage": [
    "tv-sponsor-stage", "tw:min-h-[58vh]", "tw:grid", "tw:place-items-center",
  ].join(" "),
  "tv_sponsor_panel": [
    "tv-sponsor-panel", "tw:w-[min(1040px,_100%)]", "tw:grid", "tw:[justify-items:center]",
    "tw:gap-y-[20px]", "tw:gap-x-[20px]", "tw:pt-[clamp(28px,_3vw,_44px)]", "tw:pr-[clamp(28px,_3vw,_44px)]",
    "tw:pb-[clamp(28px,_3vw,_44px)]", "tw:pl-[clamp(28px,_3vw,_44px)]", "tw:rounded-[12px]", "tw:bg-[color:transparent]",
    "tw:[background-image:linear-gradient(145deg,_rgb(13_66_78_/_.62),_rgb(6_35_53_/_.62))]", "tw:[box-shadow:none]", "tw:text-center", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(82_196_188_/_.2)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:rgb(82_196_188_/_.2)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(82_196_188_/_.2)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(82_196_188_/_.2)]", "tw:[font-family:var(--font-body)]",
  ].join(" "),
  "tv_sponsor_section_title": [
    "tv-sponsor-section-title", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-[color:#f0fbff]", "tw:text-[clamp(1.8rem,_3vw,_3rem)]", "tw:leading-[1]",
    "tw:font-[700]", "tw:tracking-[.05em]", "tw:uppercase",
  ].join(" "),
  "tv_sponsor_logo_frame": [
    "tv-sponsor-logo-frame", "tw:w-[min(760px,_100%)]", "tw:min-h-[clamp(220px,_34vw,_360px)]", "tw:grid",
    "tw:place-items-center", "tw:pt-[0]", "tw:pr-[0]", "tw:pb-[0]",
    "tw:pl-[0]", "tw:rounded-[0]", "tw:bg-[color:transparent]", "tw:[background-image:none]",
  ].join(" "),
  "tv_sponsor_logo": [
    "tv-sponsor-logo", "tw:block", "tw:w-[min(760px,_100%)]", "tw:max-w-[100%]",
    "tw:max-h-[320px]", "tw:h-[auto]", "tw:[object-fit:contain]",
  ].join(" "),
  "tv_sponsor_fallback": [
    "tv-sponsor-fallback", "tw:text-[clamp(2rem,_4.4vw,_4rem)]", "tw:leading-[1]", "tw:text-[color:#eafff8]",
    "tw:uppercase",
  ].join(" "),
  "tv_sponsor_name": [
    "tv-sponsor-name", "tw:text-[color:#bbdce3]", "tw:text-[clamp(1rem,_1.5vw,_1.3rem)]", "tw:font-[700]",
  ].join(" "),
  "tv_ranking_board": [
    "tv-ranking-board", "tw:grid", "tw:gap-y-[clamp(16px,_1.6vw,_24px)]", "tw:gap-x-[clamp(16px,_1.6vw,_24px)]",
    "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-1024:grid-cols-[1fr]",
  ].join(" "),
  "tv_ranking_card": [
    "tv-ranking-card", "tw:relative", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(106_197_210_/_.2)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(106_197_210_/_.2)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgb(106_197_210_/_.2)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(106_197_210_/_.2)]",
    "tw:rounded-[10px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_rgb(17_64_84_/_.8),_rgb(10_39_60_/_.84))]", "tw:[box-shadow:0_18px_42px_rgb(0_0_0_/_.18)]",
    "tw:grid", "tw:grid-cols-[88px_minmax(0,_1fr)_auto]", "tw:viewport-760:grid-cols-[70px_minmax(0,_1fr)]", "tw:gap-y-[14px]",
    "tw:gap-x-[14px]", "tw:items-center", "tw:min-h-[116px]", "tw:pt-[0]",
    "tw:pr-[clamp(20px,_1.8vw,_28px)]", "tw:pb-[0]", "tw:pl-[clamp(20px,_1.8vw,_28px)]", "tw:[font-family:var(--font-body)]",
    "tw:[&_strong]:block", "tw:[&_strong]:text-[color:#ffffff]", "tw:[&_strong]:text-[clamp(1.5rem,_2.05vw,_2.05rem)]", "tw:[&_strong]:leading-[1.05]",
    "tw:[&_strong]:font-[700]", "tw:[&_small]:text-[color:#65efbf]", "tw:[&_small]:text-[clamp(1rem,_1.35vw,_1.2rem)]", "tw:[&_small]:font-[700]",
    "tw:[&_small]:whitespace-nowrap", "tw:[&_small]:tracking-[.06em]", "tw:viewport-760:[&_small]:[grid-column:2]",
  ].join(" "),
  "tv_ranking_position": [
    "tv-ranking-position", "tw:[display:inline-grid]", "tw:place-items-center", "tw:w-[72px]",
    "tw:h-[72px]", "tw:rounded-[9px]", "tw:bg-[color:rgb(50_221_174_/_.16)]", "tw:[background-image:none]",
    "tw:text-[color:#65efbf]", "tw:text-[clamp(1.24rem,_1.8vw,_1.7rem)]", "tw:font-[700]",
  ].join(" "),
  "tv_spotlight_card_tv_prize_card": [
    "tv-spotlight-card", "tv-prize-card", "tw:relative", "tw:[overflow-x:hidden]",
    "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(108_204_211_/_.28)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(108_204_211_/_.28)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(108_204_211_/_.28)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgb(108_204_211_/_.28)]", "tw:rounded-[10px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_rgb(20_87_102_/_.52),_rgb(7_42_59_/_.42))]",
    "tw:[box-shadow:inset_0_1px_rgb(255_255_255_/_.06),_0_18px_42px_rgb(0_0_0_/_.16)]", "tw:grid", "tw:[align-content:start]", "tw:[justify-items:center]",
    "tw:gap-y-[30px]", "tw:gap-x-[30px]", "tw:min-h-[58vh]", "tw:pt-[clamp(34px,_4vw,_58px)]",
    "tw:pr-[clamp(34px,_4vw,_58px)]", "tw:pb-[clamp(34px,_4vw,_58px)]", "tw:pl-[clamp(34px,_4vw,_58px)]", "tw:text-center",
    "tw:[font-family:var(--font-body)]", "tw:[backdrop-filter:blur(3px)]", "tw:[&_strong]:block", "tw:[&_strong]:text-[color:#ffffff]",
    "tw:[&_strong]:text-[clamp(2.4rem,_5vw,_5.4rem)]", "tw:[&_strong]:leading-[0.96]", "tw:[&_strong]:tracking-[-0.04em]", "tw:[&_strong]:font-[700]",
    "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]",
    "tw:[&_h2]:text-[color:#ffffff]", "tw:[&_h2]:text-[clamp(1.9rem,_3.7vw,_3.75rem)]", "tw:[&_h2]:leading-[1.08]", "tw:[&_h2]:tracking-[-.025em]",
    "tw:[&_h2]:normal-case", "tw:[&_h2]:font-[600]", "tw:[&_p:last-child]:max-w-[900px]", "tw:[&_p:last-child]:mt-[0]",
    "tw:[&_p:last-child]:mr-[0]", "tw:[&_p:last-child]:mb-[0]", "tw:[&_p:last-child]:ml-[0]", "tw:[&_p:last-child]:text-[color:#bbdce3]",
    "tw:[&_p:last-child]:text-[clamp(1.1rem,_1.65vw,_1.45rem)]", "tw:[&_p:last-child]:font-[600]", "tw:[&_p:last-child]:leading-[1.35]", "tw:[&_.tv-info-kicker]:mt-[5px]",
    "tw:[&_.tv-info-kicker]:text-[.78rem]", "tw:[&_.tv-info-kicker]:font-[650]", "tw:[&_.tv-info-kicker]:tracking-[.1em]", "tw:[&_h2]:max-w-[1120px]",
  ].join(" "),
  "tv_prize_cascade": [
    "tv-prize-cascade", "tw:w-[min(980px,_100%)]", "tw:grid", "tw:gap-y-[13px]",
    "tw:gap-x-[13px]", "tw:mt-[10px]",
  ].join(" "),
  "tv_prize_tier": [
    "tv-prize-tier", "tw:grid", "tw:grid-cols-[74px_minmax(0,_1fr)]", "tw:items-center",
    "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:pt-[16px]", "tw:pr-[18px]",
    "tw:pb-[16px]", "tw:pl-[18px]", "tw:rounded-[9px]", "tw:bg-[color:rgb(202_238_242_/_.12)]",
    "tw:[background-image:none]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(184_229_235_/_.14)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(184_229_235_/_.14)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(184_229_235_/_.14)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgb(184_229_235_/_.14)]", "tw:text-left", "tw:[&:nth-child(2)]:ml-[0]", "tw:[&:nth-child(3)]:ml-[0]",
    "tw:[&_strong]:text-[clamp(1.08rem,_1.7vw,_1.6rem)]", "tw:[&_strong]:leading-[1.3]", "tw:[&_strong]:tracking-[0]", "tw:[&_strong]:font-[500]",
    "tw:[&_strong]:text-[color:#e7f5f7]", "tw:[&.tv-prize-tier-order]:[display:inline-grid]", "tw:[&.tv-prize-tier-order]:place-items-center", "tw:[&.tv-prize-tier-order]:w-[64px]",
    "tw:[&.tv-prize-tier-order]:h-[64px]", "tw:[&.tv-prize-tier-order]:rounded-[9px]", "tw:[&.tv-prize-tier-order]:bg-[color:rgb(50_221_174_/_.16)]", "tw:[&.tv-prize-tier-order]:[background-image:none]",
    "tw:[&.tv-prize-tier-order]:text-[color:#65efbf]", "tw:[&.tv-prize-tier-order]:text-[1.05rem]", "tw:[&.tv-prize-tier-order]:font-[700]",
  ].join(" "),
  "tv_prize_tier_order": [
    "tv-prize-tier-order", "tw:[display:inline-grid]", "tw:place-items-center", "tw:w-[64px]",
    "tw:h-[64px]", "tw:rounded-[9px]", "tw:bg-[color:rgb(50_221_174_/_.16)]", "tw:[background-image:none]",
    "tw:text-[color:#65efbf]", "tw:text-[1.05rem]", "tw:font-[700]",
  ].join(" "),
  "tv_spotlight_card_tv_spotlight_card_winner": [
    "tv-spotlight-card", "tv-spotlight-card-winner", "tw:relative", "tw:[overflow-x:hidden]",
    "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(108_204_211_/_.28)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(108_204_211_/_.28)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(108_204_211_/_.28)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgb(108_204_211_/_.28)]", "tw:rounded-[10px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_rgb(20_87_102_/_.52),_rgb(7_42_59_/_.42))]",
    "tw:[box-shadow:inset_0_1px_rgb(255_255_255_/_.06),_0_18px_42px_rgb(0_0_0_/_.16)]", "tw:grid", "tw:[align-content:center]", "tw:[justify-items:center]",
    "tw:gap-y-[18px]", "tw:gap-x-[18px]", "tw:min-h-[58vh]", "tw:pt-[clamp(34px,_4vw,_58px)]",
    "tw:pr-[clamp(34px,_4vw,_58px)]", "tw:pb-[clamp(34px,_4vw,_58px)]", "tw:pl-[clamp(34px,_4vw,_58px)]", "tw:text-center",
    "tw:[font-family:var(--font-body)]", "tw:[backdrop-filter:blur(3px)]", "tw:[&_strong]:block", "tw:[&_strong]:text-[color:rgba(255,_196,_79,_0.98)]",
    "tw:[&_strong]:text-[clamp(2.4rem,_5vw,_5.4rem)]", "tw:[&_strong]:leading-[0.96]", "tw:[&_strong]:tracking-[-0.04em]", "tw:[&_strong]:font-[700]",
    "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]",
    "tw:[&_h2]:text-[color:#ffffff]", "tw:[&_h2]:text-[clamp(2.2rem,_4vw,_4.4rem)]", "tw:[&_h2]:leading-[0.98]", "tw:[&_h2]:tracking-[-.025em]",
    "tw:[&_h2]:normal-case", "tw:[&_h2]:font-[700]", "tw:[&_p:last-child]:max-w-[900px]", "tw:[&_p:last-child]:mt-[0]",
    "tw:[&_p:last-child]:mr-[0]", "tw:[&_p:last-child]:mb-[0]", "tw:[&_p:last-child]:ml-[0]", "tw:[&_p:last-child]:text-[color:#bbdce3]",
    "tw:[&_p:last-child]:text-[clamp(1.1rem,_1.65vw,_1.45rem)]", "tw:[&_p:last-child]:font-[600]", "tw:[&_p:last-child]:leading-[1.35]",
  ].join(" "),
  "tv_progress": [
    "tv-progress", "tw:fixed", "tw:left-[0]", "tw:bottom-[0]",
    "tw:h-[5px]", "tw:w-[100%]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(90deg,_#4ee8b1,_#39aeea)]",
    "tw:[transform-origin:left]", "tw:[animation:tv-progress_10000ms_linear_infinite]",
  ].join(" "),
} as const;
