import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "agenda_online_settings_trigger": [
    "agenda-online-settings-trigger", "tw:grid", "tw:place-items-center", "tw:min-w-[38px]",
    "tw:pt-[0]", "tw:pr-[9px]", "tw:pb-[0]", "tw:pl-[9px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#0d4f88]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#0d4f88]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#0d4f88]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#0d4f88]",
    "tw:rounded-[var(--radius-control)]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_#1684c5,_#0d5c9c)]", "tw:text-[color:#fff]",
    "tw:text-[1.12rem]", "tw:[box-shadow:0_3px_8px_rgb(13_79_136_/_.25)]", "tw:cursor-pointer", "tw:[transition:transform_160ms_var(--ease-standard),_background_160ms_var(--ease-standard)]",
    "tw:hover:bg-[color:transparent]", "tw:hover:[background-image:linear-gradient(145deg,_#0f6fad,_#08477c)]", "tw:hover:[transform:translateY(-1px)]",
  ].join(" "),
  "command_modal_backdrop": sharedUtilities.commandModalBackdrop,
  "online_booking_settings_modal": [
    "online-booking-settings-modal", "tw:w-[min(100%,_660px)]", "tw:grid", "tw:gap-y-[16px]",
    "tw:gap-x-[16px]", "tw:pt-[22px]", "tw:viewport-680:pt-[17px]", "tw:pr-[22px]",
    "tw:viewport-680:pr-[17px]", "tw:pb-[22px]", "tw:viewport-680:pb-[17px]", "tw:pl-[22px]",
    "tw:viewport-680:pl-[17px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[14px]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]",
    "tw:[box-shadow:0_28px_80px_rgb(15_23_42_/_.3)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:items-center",
    "tw:[&_>_header]:gap-y-[12px]", "tw:[&_>_header]:gap-x-[12px]", "tw:[&_header_span]:text-[color:var(--primary)]", "tw:[&_header_span]:text-[.7rem]",
    "tw:[&_header_span]:font-[800]", "tw:[&_header_span]:tracking-[.08em]", "tw:[&_h2]:mt-[2px]", "tw:[&_h2]:mr-[0]",
    "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[1.18rem]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "online_booking_link": [
    "online-booking-link", "tw:flex", "tw:justify-between", "tw:items-center",
    "tw:viewport-680:items-stretch", "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:pt-[11px]",
    "tw:pr-[12px]", "tw:pb-[11px]", "tw:pl-[12px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[10px]",
    "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]", "tw:[&_>_div]:grid", "tw:[&_>_div]:gap-y-[3px]",
    "tw:[&_>_div]:gap-x-[3px]", "tw:[&_>_div]:min-w-[0]", "tw:[&_strong]:text-[.78rem]", "tw:[&_code]:[overflow-x:hidden]",
    "tw:[&_code]:[overflow-y:hidden]", "tw:[&_code]:text-[color:var(--muted)]", "tw:[&_code]:text-[.75rem]", "tw:[&_code]:text-ellipsis",
    "tw:[&_code]:whitespace-nowrap", "tw:viewport-680:flex-col",
  ].join(" "),
  "online_booking_settings_form": [
    "online-booking-settings-form", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-680:grid-cols-[1fr]",
    "tw:gap-y-[13px]", "tw:gap-x-[13px]", "tw:[align-items:start]", "tw:[&_.field]:grid",
    "tw:[&_.field]:[align-content:start]", "tw:[&_.field]:gap-y-[6px]", "tw:[&_.field]:gap-x-[6px]", "tw:[&_.field_input]:[box-sizing:border-box]",
    "tw:[&_.field_input]:w-[100%]", "tw:[&_.field_select]:[box-sizing:border-box]", "tw:[&_.field_select]:w-[100%]", "tw:[&_.field_textarea]:[box-sizing:border-box]",
    "tw:[&_.field_textarea]:w-[100%]", "tw:[&_textarea]:min-h-[82px]", "tw:[&_textarea]:[resize:vertical]", "tw:[&_small]:text-[color:var(--muted)]",
    "tw:[&_small]:text-[.7rem]", "tw:[&_small]:font-[550]", "tw:[&_.control-toggle]:[align-self:center]",
  ].join(" "),
  "field": sharedUtilities.field,
  "online_booking_settings_toggles_form_full": [
    "online-booking-settings-toggles", "form-full", "tw:flex", "tw:flex-wrap",
    "tw:items-center", "tw:gap-y-[12px]", "tw:gap-x-[24px]", "tw:min-h-[34px]",
    "tw:pt-[2px]", "tw:pr-[0]", "tw:pb-[2px]", "tw:pl-[0]",
    "tw:[&_.control-toggle]:min-h-[30px]", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  "control_toggle": sharedUtilities.controlToggle,
  "field_form_full": sharedUtilities.fieldFormFull,
  "online_booking_settings_footer_form_full": [
    "online-booking-settings-footer", "form-full", "tw:flex", "tw:justify-between",
    "tw:items-center", "tw:viewport-680:items-stretch", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:[grid-column:1_/_-1]", "tw:pt-[4px]", "tw:[&_.button]:[text-decoration:none]", "tw:viewport-680:flex-col",
    "tw:viewport-680:[&_.button]:w-[100%]", "tw:viewport-680:[&_.button]:justify-center",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
} as const;
