"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { requestPortalComandaProductAction } from "@/lib/actions/comanda";

type Data = { comandas: { id: string; code: string; openedAt: string; totalCents: number; items: { id: string; name: string; quantity: number; totalCents: number }[] }[]; categories: { id: string; name: string }[]; products: { id: string; name: string; priceCents: number; stockQuantity: number; category: string }[] } | null;
const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value / 100);
const AddIcon = () => <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14" /></svg>;

export function PortalClientComandas({ data, arenaSlug }: { data: Data; arenaSlug: string }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState(""); const [search, setSearch] = useState(""); const [category, setCategory] = useState("Todos"); const router = useRouter();
  const categories = useMemo(() => ["Todos", ...(data?.categories.map((entry) => entry.name) ?? []), ...(data?.products.some((product) => product.category === "Sem categoria") ? ["Sem categoria"] : [])], [data]);
  const products = useMemo(() => (data?.products ?? []).filter((product) => (category === "Todos" || product.category === category) && (!search.trim() || product.name.toLocaleLowerCase("pt-BR").includes(search.trim().toLocaleLowerCase("pt-BR")))).slice(0, 18), [category, data, search]);
  const order = (comandaId: string, productId: string) => { const form = new FormData(); form.set("arenaSlug", arenaSlug); form.set("comandaId", comandaId); form.set("productId", productId); form.set("quantity", "1"); setMessage(""); startTransition(async () => { try { await requestPortalComandaProductAction(form); setMessage("Pedido enviado ao balcão. O item será lançado após a confirmação."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível enviar o pedido."); } }); };
  if (!data) return <section className="athlete-portal-content-panel"><h2>Comandas indisponíveis</h2><p className="muted">Não foi possível carregar suas comandas agora.</p></section>;
  return <section className="athlete-portal-content-panel portal-comandas"><header><span>CONSUMO NA ARENA</span><h2>Minhas comandas</h2><p>Acompanhe todas as suas comandas abertas e peça direto para o bar.</p></header>{message ? <p className="form-feedback">{message}</p> : null}{data.comandas.length ? <div className="portal-comanda-list">{data.comandas.map((comanda) => <article key={comanda.id}><header><div><span className="portal-comanda-status">Aberta</span><strong>Comanda</strong><small>Aberta em {comanda.openedAt}</small></div><b>{money(comanda.totalCents)}</b></header>{comanda.items.length ? <ul>{comanda.items.map((item) => <li key={item.id}><span>{item.quantity}× {item.name}</span><strong>{money(item.totalCents)}</strong></li>)}</ul> : <p className="muted">Nenhum item lançado ainda.</p>}<div className="portal-bar-products"><div className="portal-bar-products-head"><h3>Pedir ao bar</h3><span>{data.products.length} itens</span></div><div className="portal-bar-product-filters"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar produto" aria-label="Buscar produto" /><select value={category} onChange={(event) => setCategory(event.target.value)} aria-label="Filtrar categoria">{categories.map((entry) => <option value={entry} key={entry}>{entry}</option>)}</select></div><div className="portal-bar-product-list">{products.map((product) => <button type="button" key={product.id} disabled={pending} onClick={() => order(comanda.id, product.id)}><span><strong>{product.name}</strong><small>{product.category}</small></span><b>{money(product.priceCents)}</b><i><AddIcon /></i></button>)}</div>{!products.length ? <p className="portal-bar-products-empty">Nenhum produto encontrado.</p> : null}{products.length < data.products.length ? <small className="portal-bar-products-limit">Mostrando até 18 itens. Use a busca ou categoria para encontrar o restante.</small> : null}</div></article>)}</div> : <div className="portal-comanda-empty"><strong>Você não tem comanda aberta.</strong><p>Peça à equipe da arena para abrir sua comanda. Assim que ela estiver aberta, os pedidos aparecem aqui em tempo real.</p></div>}</section>;
}
