import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "athlete_portal_content_panel": [
    "athlete-portal-content-panel", "tw:w-[min(calc(100%_-_32px),_1060px)]", "tw:viewport-700:w-[calc(100%_-_28px)]", "tw:[margin-inline:auto]",
    "tw:mt-[22px]", "tw:viewport-700:mt-[16px]", "tw:pt-[26px]", "tw:viewport-700:pt-[16px]",
    "tw:pr-[26px]", "tw:viewport-700:pr-[16px]", "tw:pb-[26px]", "tw:viewport-700:pb-[16px]",
    "tw:pl-[26px]", "tw:viewport-700:pl-[16px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(120_162_185_/_.2)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(120_162_185_/_.2)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(120_162_185_/_.2)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(120_162_185_/_.2)]", "tw:rounded-[15px]", "tw:bg-[color:#0d1b28]",
    "tw:[background-image:none]", "tw:[box-shadow:0_18px_42px_rgb(0_0_0_/_.2)]", "tw:[&_>_header]:grid", "tw:[&_>_header]:gap-y-[4px]",
    "tw:[&_>_header]:gap-x-[4px]", "tw:[&_>_header]:pb-[17px]", "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]",
    "tw:[&_>_header]:border-b-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-t-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-r-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-l-[color:rgb(135_178_196_/_.16)]",
    "tw:[&_>_header_span]:text-[color:#57d7ae]", "tw:[&_>_header_span]:text-[.66rem]", "tw:[&_>_header_span]:font-[900]", "tw:[&_>_header_span]:tracking-[.12em]",
    "tw:[&_>_header_h2]:mt-[0]", "tw:[&_>_header_h2]:mr-[0]", "tw:[&_>_header_h2]:mb-[0]", "tw:[&_>_header_h2]:ml-[0]",
    "tw:[&_>_header_h2]:text-[color:#f2f9fc]", "tw:[&_>_header_h2]:text-[1.3rem]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "athlete_portal_content_panel_portal_comandas": [
    "athlete-portal-content-panel", "portal-comandas", "tw:w-[min(calc(100%_-_32px),_1060px)]", "tw:viewport-700:w-[calc(100%_-_28px)]",
    "tw:[margin-inline:auto]", "tw:mt-[22px]", "tw:viewport-700:mt-[16px]", "tw:pt-[26px]",
    "tw:viewport-700:pt-[16px]", "tw:pr-[26px]", "tw:viewport-700:pr-[16px]", "tw:pb-[26px]",
    "tw:viewport-700:pb-[16px]", "tw:pl-[26px]", "tw:viewport-700:pl-[16px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(120_162_185_/_.2)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:rgb(120_162_185_/_.2)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(120_162_185_/_.2)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(120_162_185_/_.2)]", "tw:rounded-[15px]",
    "tw:bg-[color:#0d1b28]", "tw:[background-image:none]", "tw:[box-shadow:0_18px_42px_rgb(0_0_0_/_.2)]", "tw:[&_>_header]:grid",
    "tw:[&_>_header]:gap-y-[4px]", "tw:[&_>_header]:gap-x-[4px]", "tw:[&_>_header]:pb-[17px]", "tw:[&_>_header]:border-b-[length:1px]",
    "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-t-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-r-[color:rgb(135_178_196_/_.16)]",
    "tw:[&_>_header]:border-l-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header_span]:text-[color:#57d7ae]", "tw:[&_>_header_span]:text-[.7rem]", "tw:[&_>_header_span]:font-[800]",
    "tw:[&_>_header_span]:tracking-[.08em]", "tw:[&_>_header_h2]:mt-[4px]", "tw:[&_>_header_h2]:mr-[0]", "tw:[&_>_header_h2]:mb-[4px]",
    "tw:[&_>_header_h2]:ml-[0]", "tw:[&_>_header_h2]:text-[color:#f2f9fc]", "tw:[&_>_header_h2]:text-[1.3rem]", "tw:[&_>_header]:mb-[18px]",
  ].join(" "),
  "portal_comanda_list": [
    "portal-comanda-list", "tw:grid", "tw:gap-y-[14px]", "tw:viewport-700:gap-y-[11px]",
    "tw:gap-x-[14px]", "tw:viewport-700:gap-x-[11px]", "tw:[&_>_article]:border-t-[length:1px]", "tw:[&_>_article]:[border-top-style:solid]",
    "tw:[&_>_article]:border-t-[color:#1c6980]", "tw:[&_>_article]:border-r-[length:1px]", "tw:[&_>_article]:[border-right-style:solid]", "tw:[&_>_article]:border-r-[color:#1c6980]",
    "tw:[&_>_article]:border-b-[length:1px]", "tw:[&_>_article]:[border-bottom-style:solid]", "tw:[&_>_article]:border-b-[color:#1c6980]", "tw:[&_>_article]:border-l-[length:1px]",
    "tw:[&_>_article]:[border-left-style:solid]", "tw:[&_>_article]:border-l-[color:#1c6980]", "tw:[&_>_article]:rounded-[12px]", "tw:[&_>_article]:[overflow-x:hidden]",
    "tw:[&_>_article]:[overflow-y:hidden]", "tw:[&_>_article]:bg-[color:#082d3d]", "tw:[&_>_article]:[background-image:none]", "tw:[&_>_article_>_header]:flex",
    "tw:viewport-700:[&_>_article_>_header]:grid", "tw:[&_>_article_>_header]:justify-between", "tw:[&_>_article_>_header]:gap-y-[12px]", "tw:viewport-700:[&_>_article_>_header]:gap-y-[10px]",
    "tw:[&_>_article_>_header]:gap-x-[12px]", "tw:viewport-700:[&_>_article_>_header]:gap-x-[10px]", "tw:[&_>_article_>_header]:pt-[14px]", "tw:viewport-700:[&_>_article_>_header]:pt-[12px]",
    "tw:[&_>_article_>_header]:pr-[16px]", "tw:viewport-700:[&_>_article_>_header]:pr-[13px]", "tw:[&_>_article_>_header]:pb-[14px]", "tw:viewport-700:[&_>_article_>_header]:pb-[12px]",
    "tw:[&_>_article_>_header]:pl-[16px]", "tw:viewport-700:[&_>_article_>_header]:pl-[13px]", "tw:[&_>_article_>_header]:bg-[color:#0d4052]", "tw:[&_>_article_>_header]:[background-image:none]",
    "tw:[&_>_article_>_header]:items-center", "tw:[&_>_article_>_header_div]:grid", "tw:[&_>_article_>_header_div]:gap-y-[3px]", "tw:viewport-700:[&_>_article_>_header_div]:gap-y-[4px]",
    "tw:[&_>_article_>_header_div]:gap-x-[3px]", "tw:viewport-700:[&_>_article_>_header_div]:gap-x-[4px]", "tw:[&_>_article_>_header_strong]:text-[color:#f7fbff]", "tw:[&_>_article_>_header_strong]:text-[.9rem]",
    "tw:viewport-700:[&_>_article_>_header_strong]:text-[.84rem]", "tw:[&_>_article_>_header_b]:text-[color:#6ee6c2]", "tw:[&_>_article_>_header_b]:whitespace-nowrap", "tw:[&_>_article_>_header_b]:text-[.95rem]",
    "tw:viewport-700:[&_>_article_>_header_b]:text-[.86rem]", "tw:[&_>_article_>_header_small]:text-[color:#b7e0e8]", "tw:[&_ul]:mt-[0]", "tw:[&_ul]:mr-[0]",
    "tw:[&_ul]:mb-[0]", "tw:[&_ul]:ml-[0]", "tw:[&_ul]:pt-[0]", "tw:[&_ul]:pr-[16px]",
    "tw:viewport-700:[&_ul]:pr-[13px]", "tw:[&_ul]:pb-[0]", "tw:[&_ul]:pl-[16px]", "tw:viewport-700:[&_ul]:pl-[13px]",
    "tw:[&_ul]:[list-style:none]", "tw:[&_li]:flex", "tw:viewport-700:[&_li]:grid", "tw:[&_li]:justify-between",
    "tw:[&_li]:gap-y-[12px]", "tw:viewport-700:[&_li]:gap-y-[10px]", "tw:[&_li]:gap-x-[12px]", "tw:viewport-700:[&_li]:gap-x-[10px]",
    "tw:[&_li]:pt-[10px]", "tw:viewport-700:[&_li]:pt-[9px]", "tw:[&_li]:pr-[0]", "tw:[&_li]:pb-[10px]",
    "tw:viewport-700:[&_li]:pb-[9px]", "tw:[&_li]:pl-[0]", "tw:[&_li]:text-[color:#ddecf1]", "tw:[&_li]:border-b-[length:1px]",
    "tw:[&_li]:[border-bottom-style:solid]", "tw:[&_li]:border-b-[color:rgba(141,207,219,.16)]", "tw:[&_li_>_span]:min-w-[0]", "tw:[&_li_>_strong]:[flex:0_0_auto]",
    "tw:[&_li_>_strong]:whitespace-nowrap", "tw:viewport-700:[&_>_article_>_header]:grid-cols-[minmax(0,_1fr)_auto]", "tw:viewport-700:[&_>_article_>_header_div]:min-w-[0]", "tw:viewport-700:[&_>_article_>_header_small]:text-[.7rem]",
    "tw:viewport-700:[&_>_article_>_header_b]:[align-self:center]", "tw:viewport-700:[&_li]:grid-cols-[minmax(0,_1fr)_auto]", "tw:viewport-700:[&_li]:text-[.78rem]", "tw:viewport-700:[&_li_>_span]:[overflow-wrap:anywhere]",
    "tw:viewport-700:[&_li_>_span]:leading-[1.32]", "tw:viewport-700:[&_li_>_strong]:[align-self:start]", "tw:viewport-700:[&_li_>_strong]:text-[.76rem]", "tw:[&_>_article_>_.muted]:mt-[0]",
    "tw:[&_>_article_>_.muted]:mr-[0]", "tw:[&_>_article_>_.muted]:mb-[0]", "tw:[&_>_article_>_.muted]:ml-[0]", "tw:[&_>_article_>_.muted]:pt-[12px]",
    "tw:viewport-700:[&_>_article_>_.muted]:pt-[11px]", "tw:[&_>_article_>_.muted]:pr-[16px]", "tw:viewport-700:[&_>_article_>_.muted]:pr-[13px]", "tw:[&_>_article_>_.muted]:pb-[12px]",
    "tw:viewport-700:[&_>_article_>_.muted]:pb-[11px]", "tw:[&_>_article_>_.muted]:pl-[16px]", "tw:viewport-700:[&_>_article_>_.muted]:pl-[13px]", "tw:[&_>_article_>_.muted]:text-[color:#b7d3db]",
    "tw:[&_>_article_>_.muted]:text-[.78rem]", "tw:viewport-700:[&_>_article_>_.muted]:text-[.75rem]", "tw:[&_>_article_>_.muted_+_.portal-bar-products]:pt-[6px]",
  ].join(" "),
  "portal_comanda_status": [
    "portal-comanda-status", "tw:inline-flex", "tw:w-[fit-content]", "tw:items-center",
    "tw:min-h-[20px]", "tw:viewport-700:min-h-[19px]", "tw:pt-[2px]", "tw:pr-[7px]",
    "tw:pb-[2px]", "tw:pl-[7px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(73_231_174_/_.52)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(73_231_174_/_.52)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(73_231_174_/_.52)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(73_231_174_/_.52)]", "tw:rounded-[5px]", "tw:text-[color:#83f2c3]",
    "tw:bg-[color:rgb(13_168_131_/_.18)]", "tw:[background-image:none]", "tw:text-[.63rem]", "tw:viewport-700:text-[.59rem]",
    "tw:font-[850]", "tw:tracking-[.045em]", "tw:uppercase",
  ].join(" "),
  "portal_bar_products": [
    "portal-bar-products", "tw:pt-[15px]", "tw:viewport-700:pt-[13px]", "tw:pr-[16px]",
    "tw:viewport-700:pr-[13px]", "tw:pb-[18px]", "tw:viewport-700:pb-[13px]", "tw:pl-[16px]",
    "tw:viewport-700:pl-[13px]", "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[0]",
    "tw:[&_h3]:ml-[0]", "tw:[&_h3]:text-[color:#b7e0e8]", "tw:[&_h3]:text-[.78rem]", "tw:[&_h3]:uppercase",
    "tw:[&_h3]:tracking-[.06em]", "tw:[&_button]:w-[100%]", "tw:[&_button]:grid", "tw:[&_button]:grid-cols-[minmax(0,1fr)_auto_22px]",
    "tw:viewport-700:[&_button]:grid-cols-[minmax(0,_1fr)_auto_24px]", "tw:[&_button]:gap-y-[8px]", "tw:[&_button]:gap-x-[8px]", "tw:[&_button]:text-left",
    "tw:[&_button]:items-center", "tw:[&_button]:border-t-[length:1px]", "tw:[&_button]:[border-top-style:solid]", "tw:[&_button]:border-t-[color:#245b6c]",
    "tw:[&_button]:border-r-[length:1px]", "tw:[&_button]:[border-right-style:solid]", "tw:[&_button]:border-r-[color:#245b6c]", "tw:[&_button]:border-b-[length:1px]",
    "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:#245b6c]", "tw:[&_button]:border-l-[length:1px]", "tw:[&_button]:[border-left-style:solid]",
    "tw:[&_button]:border-l-[color:#245b6c]", "tw:[&_button]:rounded-[8px]", "tw:[&_button]:pt-[9px]", "tw:[&_button]:pr-[10px]",
    "tw:[&_button]:pb-[9px]", "tw:[&_button]:pl-[10px]", "tw:[&_button]:bg-[color:#0a3546]", "tw:[&_button]:[background-image:none]",
    "tw:[&_button]:text-[color:#fff]", "tw:[&_button]:cursor-pointer", "tw:[&_button:hover]:bg-[color:#104b5c]", "tw:[&_button:hover]:[background-image:none]",
    "tw:[&_button:hover]:border-t-[color:#30cda6]", "tw:[&_button:hover]:border-r-[color:#30cda6]", "tw:[&_button:hover]:border-b-[color:#30cda6]", "tw:[&_button:hover]:border-l-[color:#30cda6]",
    "tw:[&_button:disabled]:opacity-[.6]", "tw:[&_button:disabled]:cursor-wait", "tw:[&_button_span]:grid", "tw:[&_button_span]:gap-y-[2px]",
    "tw:[&_button_span]:gap-x-[2px]", "tw:[&_button_span]:min-w-[0]", "tw:[&_button_strong]:[overflow-x:hidden]", "tw:[&_button_strong]:[overflow-y:hidden]",
    "tw:[&_button_strong]:text-ellipsis", "tw:[&_button_strong]:whitespace-nowrap", "tw:[&_button_small]:text-[color:#9bcbd4]", "tw:[&_button_b]:text-[color:#64e5c3]",
    "tw:[&_button_b]:text-[.75rem]", "tw:[&_button_b]:whitespace-nowrap", "tw:[&_button_i]:grid", "tw:[&_button_i]:place-items-center",
    "tw:[&_button_i]:w-[22px]", "tw:[&_button_i]:h-[22px]", "tw:[&_button_i]:rounded-[50%]", "tw:[&_button_i]:bg-[color:#0da883]",
    "tw:[&_button_i]:[background-image:none]", "tw:[&_button_i_svg]:w-[14px]", "tw:[&_button_i_svg]:h-[14px]", "tw:[&_button_i_svg]:[fill:none]",
    "tw:[&_button_i_svg]:[stroke:currentColor]", "tw:[&_button_i_svg]:[stroke-linecap:round]", "tw:[&_button_i_svg]:[stroke-width:2.4]", "tw:viewport-700:[&_button]:min-h-[49px]",
  ].join(" "),
  "portal_bar_products_head": [
    "portal-bar-products-head", "tw:flex", "tw:items-center", "tw:justify-between",
    "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:[&_span]:text-[color:#8eb6c1]", "tw:[&_span]:text-[.67rem]",
  ].join(" "),
  "portal_bar_product_filters": [
    "portal-bar-product-filters", "tw:grid", "tw:grid-cols-[minmax(0,1fr)_130px]", "tw:viewport-760:grid-cols-[1fr]",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:mt-[10px]", "tw:mr-[0]",
    "tw:mb-[10px]", "tw:ml-[0]", "tw:[&_input]:min-w-[0]", "tw:[&_input]:min-h-[34px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#245b6c]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#245b6c]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:#245b6c]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#245b6c]",
    "tw:[&_input]:rounded-[7px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[9px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[9px]", "tw:[&_input]:text-[color:#effaff]", "tw:[&_input]:bg-[color:#092c3b]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:[font:inherit]", "tw:[&_input]:text-[.73rem]", "tw:[&_select]:min-w-[0]", "tw:[&_select]:min-h-[34px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:#245b6c]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#245b6c]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:#245b6c]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#245b6c]",
    "tw:[&_select]:rounded-[7px]", "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[9px]", "tw:[&_select]:pb-[0]",
    "tw:[&_select]:pl-[9px]", "tw:[&_select]:text-[color:#effaff]", "tw:[&_select]:bg-[color:#092c3b]", "tw:[&_select]:[background-image:none]",
    "tw:[&_select]:[font:inherit]", "tw:[&_select]:text-[.73rem]",
  ].join(" "),
  "portal_bar_product_list": [
    "portal-bar-product-list", "tw:grid", "tw:grid-cols-[repeat(2,minmax(0,1fr))]", "tw:viewport-760:grid-cols-[1fr]",
    "tw:gap-y-[7px]", "tw:gap-x-[7px]",
  ].join(" "),
  "portal_bar_products_empty": [
    "portal-bar-products-empty", "tw:mt-[8px]", "tw:mr-[0]", "tw:mb-[8px]",
    "tw:ml-[0]", "tw:text-[color:#9bcbd4]", "tw:text-[.74rem]",
  ].join(" "),
  "portal_bar_products_limit": [
    "portal-bar-products-limit", "tw:text-[color:#8eb6c1]", "tw:text-[.67rem]", "tw:block",
    "tw:mt-[9px]",
  ].join(" "),
  "portal_comanda_empty": [
    "portal-comanda-empty", "tw:pt-[24px]", "tw:pr-[24px]", "tw:pb-[24px]",
    "tw:pl-[24px]", "tw:border-t-[length:1px]", "tw:[border-top-style:dashed]", "tw:border-t-[color:#287087]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:dashed]", "tw:border-r-[color:#287087]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:dashed]", "tw:border-b-[color:#287087]", "tw:border-l-[length:1px]", "tw:[border-left-style:dashed]",
    "tw:border-l-[color:#287087]", "tw:rounded-[12px]", "tw:bg-[color:#082c3a]", "tw:[background-image:none]",
    "tw:text-[color:#e6f8fb]", "tw:[&_p]:mt-[7px]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#b5d7df]",
  ].join(" "),
} as const;
