import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "portal_editor_modal": [
    "portal-editor-modal", "tw:fixed", "tw:z-[100]", "tw:top-[0]",
    "tw:right-[0]", "tw:bottom-[0]", "tw:left-[0]", "tw:grid",
    "tw:place-items-center", "tw:pt-[20px]", "tw:viewport-620:pt-[12px]", "tw:pr-[20px]",
    "tw:viewport-620:pr-[12px]", "tw:pb-[20px]", "tw:viewport-620:pb-[12px]", "tw:pl-[20px]",
    "tw:viewport-620:pl-[12px]", "tw:bg-[color:rgb(10_29_54_/_.38)]", "tw:[background-image:none]", "tw:[backdrop-filter:blur(3px)]",
    "tw:[&_>_section]:grid", "tw:[&_>_section]:gap-y-[18px]", "tw:[&_>_section]:gap-x-[18px]", "tw:[&_>_section]:w-[min(620px,_100%)]",
    "tw:[&_>_section]:max-h-[calc(100vh_-_40px)]", "tw:viewport-620:[&_>_section]:max-h-[calc(100vh_-_24px)]", "tw:[&_>_section]:[overflow-y:auto]", "tw:[&_>_section]:[overflow-x:hidden]",
    "tw:[&_>_section]:pt-[22px]", "tw:viewport-620:[&_>_section]:pt-[16px]", "tw:[&_>_section]:pr-[22px]", "tw:viewport-620:[&_>_section]:pr-[16px]",
    "tw:[&_>_section]:pb-[22px]", "tw:viewport-620:[&_>_section]:pb-[16px]", "tw:[&_>_section]:pl-[22px]", "tw:viewport-620:[&_>_section]:pl-[16px]",
    "tw:[&_>_section]:border-t-[length:1px]", "tw:[&_>_section]:[border-top-style:solid]", "tw:[&_>_section]:border-t-[color:#d8e5f0]", "tw:[&_>_section]:border-r-[length:1px]",
    "tw:[&_>_section]:[border-right-style:solid]", "tw:[&_>_section]:border-r-[color:#d8e5f0]", "tw:[&_>_section]:border-b-[length:1px]", "tw:[&_>_section]:[border-bottom-style:solid]",
    "tw:[&_>_section]:border-b-[color:#d8e5f0]", "tw:[&_>_section]:border-l-[length:1px]", "tw:[&_>_section]:[border-left-style:solid]", "tw:[&_>_section]:border-l-[color:#d8e5f0]",
    "tw:[&_>_section]:rounded-[14px]", "tw:[&_>_section]:bg-[color:#fff]", "tw:[&_>_section]:[background-image:none]", "tw:[&_>_section]:[box-shadow:0_24px_58px_rgb(12_33_61_/_.25)]",
    "tw:[&_>_section_>_header]:flex", "tw:[&_>_section_>_header]:items-start", "tw:[&_>_section_>_header]:justify-between", "tw:[&_>_section_>_header]:gap-y-[12px]",
    "tw:[&_>_section_>_header]:gap-x-[12px]", "tw:[&_>_section_>_header]:pb-[14px]", "tw:[&_>_section_>_header]:border-b-[length:1px]", "tw:[&_>_section_>_header]:[border-bottom-style:solid]",
    "tw:[&_>_section_>_header]:border-b-[color:#e1eaf2]", "tw:[&_h2]:mt-[2px]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]",
    "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#183657]", "tw:[&_h2]:text-[1.15rem]", "tw:[&_header_button]:grid",
    "tw:[&_header_button]:[flex:0_0_auto]", "tw:[&_header_button]:w-[32px]", "tw:[&_header_button]:h-[32px]", "tw:[&_header_button]:place-items-center",
    "tw:[&_header_button]:border-t-[length:1px]", "tw:[&_header_button]:[border-top-style:solid]", "tw:[&_header_button]:border-t-[color:#d4e0ed]", "tw:[&_header_button]:border-r-[length:1px]",
    "tw:[&_header_button]:[border-right-style:solid]", "tw:[&_header_button]:border-r-[color:#d4e0ed]", "tw:[&_header_button]:border-b-[length:1px]", "tw:[&_header_button]:[border-bottom-style:solid]",
    "tw:[&_header_button]:border-b-[color:#d4e0ed]", "tw:[&_header_button]:border-l-[length:1px]", "tw:[&_header_button]:[border-left-style:solid]", "tw:[&_header_button]:border-l-[color:#d4e0ed]",
    "tw:[&_header_button]:rounded-[7px]", "tw:[&_header_button]:bg-[color:#fff]", "tw:[&_header_button]:[background-image:none]", "tw:[&_header_button]:text-[color:#46627e]",
    "tw:[&_header_button]:text-[1.1rem]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "portal_upload_field": [
    "portal-upload-field", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:text-[color:#244b72]", "tw:text-[.82rem]", "tw:font-[700]", "tw:[&_small]:text-[color:var(--muted)]",
    "tw:[&_small]:font-[500]", "tw:[&_input]:absolute", "tw:[&_input]:w-[1px]", "tw:[&_input]:h-[1px]",
    "tw:[&_input]:opacity-[0]", "tw:[&_input]:[pointer-events:none]",
  ].join(" "),
  "portal_upload_control": [
    "portal-upload-control", "tw:flex", "tw:items-center", "tw:viewport-620:items-start",
    "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:min-h-[46px]", "tw:pt-[8px]",
    "tw:pr-[10px]", "tw:pb-[8px]", "tw:pl-[10px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:dashed]", "tw:border-t-[color:#a9c7e1]", "tw:border-r-[length:1px]", "tw:[border-right-style:dashed]",
    "tw:border-r-[color:#a9c7e1]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:dashed]", "tw:border-b-[color:#a9c7e1]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:dashed]", "tw:border-l-[color:#a9c7e1]", "tw:rounded-[8px]",
    "tw:bg-[color:#f8fbfe]", "tw:[background-image:none]", "tw:cursor-pointer", "tw:[&_strong]:pt-[7px]",
    "tw:[&_strong]:pr-[10px]", "tw:[&_strong]:pb-[7px]", "tw:[&_strong]:pl-[10px]", "tw:[&_strong]:rounded-[6px]",
    "tw:[&_strong]:bg-[color:#e7f0fa]", "tw:[&_strong]:[background-image:none]", "tw:[&_strong]:text-[color:#1d5fae]", "tw:[&_strong]:text-[.76rem]",
    "tw:[&_em]:[overflow-x:hidden]", "tw:[&_em]:[overflow-y:hidden]", "tw:[&_em]:text-[color:#60748a]", "tw:[&_em]:text-[.76rem]",
    "tw:[&_em]:not-italic", "tw:[&_em]:font-[500]", "tw:[&_em]:text-ellipsis", "tw:[&_em]:whitespace-nowrap",
    "tw:viewport-620:flex-col",
  ].join(" "),
  "portal_editor_workspace": [
    "portal-editor-workspace", "tw:grid", "tw:gap-y-[16px]", "tw:gap-x-[16px]",
  ].join(" "),
  "section_card": sharedUtilities.sectionCard2,
  "portal_editor_header": [
    "portal-editor-header", "tw:flex", "tw:items-center", "tw:viewport-620:items-start",
    "tw:justify-between", "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:[&_h2]:mt-[0]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_p]:mt-[4px]",
    "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:var(--muted)]",
    "tw:[&_p]:text-[.82rem]",
  ].join(" "),
  "button_button_primary_button_small": sharedUtilities.buttonButtonPrimaryButtonSmall,
  "client_portal_settings_list": [
    "client-portal-settings-list", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:[&_>_article]:flex", "tw:[&_>_article]:items-center", "tw:viewport-700:[&_>_article]:items-start", "tw:[&_>_article]:justify-between",
    "tw:[&_>_article]:gap-y-[12px]", "tw:[&_>_article]:gap-x-[12px]", "tw:[&_>_article]:pt-[10px]", "tw:[&_>_article]:pr-[0]",
    "tw:[&_>_article]:pb-[10px]", "tw:[&_>_article]:pl-[0]", "tw:[&_>_article]:border-t-[length:1px]", "tw:[&_>_article]:[border-top-style:solid]",
    "tw:[&_>_article]:border-t-[color:#e2eaf1]", "tw:[&_article_>_div]:grid", "tw:[&_article_>_div]:gap-y-[3px]", "tw:[&_article_>_div]:gap-x-[3px]",
    "tw:[&_strong]:text-[color:#1a3658]", "tw:[&_strong]:text-[.82rem]", "tw:[&_span]:text-[color:#64778c]", "tw:[&_span]:text-[.74rem]",
    "tw:[&_.button]:min-h-[32px]", "tw:[&_.button]:text-[.72rem]", "tw:viewport-700:[&_>_article]:flex-col",
  ].join(" "),
  "portal_editor_text": [
    "portal-editor-text", "tw:whitespace-pre-wrap",
  ].join(" "),
  "section_actions": sharedUtilities.sectionActions,
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "button_button_danger_button_small": sharedUtilities.buttonButtonDangerButtonSmall,
  "muted": sharedUtilities.muted,
  "portal_event_post_list": [
    "portal-event-post-list", "tw:grid", "tw:grid-cols-[repeat(auto-fill,_minmax(170px,_190px))]", "tw:viewport-620:grid-cols-[repeat(2,_minmax(0,_1fr))]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:[justify-content:start]", "tw:[&_article]:[overflow-x:hidden]",
    "tw:[&_article]:[overflow-y:hidden]", "tw:[&_article]:border-t-[length:1px]", "tw:[&_article]:[border-top-style:solid]", "tw:[&_article]:border-t-[color:#dce7f0]",
    "tw:[&_article]:border-r-[length:1px]", "tw:[&_article]:[border-right-style:solid]", "tw:[&_article]:border-r-[color:#dce7f0]", "tw:[&_article]:border-b-[length:1px]",
    "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#dce7f0]", "tw:[&_article]:border-l-[length:1px]", "tw:[&_article]:[border-left-style:solid]",
    "tw:[&_article]:border-l-[color:#dce7f0]", "tw:[&_article]:rounded-[9px]", "tw:[&_article]:bg-[color:#fff]", "tw:[&_article]:[background-image:none]",
    "tw:[&_img]:block", "tw:[&_img]:w-[100%]", "tw:[&_img]:[aspect-ratio:4_/_5]", "tw:[&_img]:[object-fit:cover]",
    "tw:[&_article_>_div]:grid", "tw:[&_article_>_div]:gap-y-[6px]", "tw:[&_article_>_div]:gap-x-[6px]", "tw:[&_article_>_div]:pt-[10px]",
    "tw:[&_article_>_div]:pr-[10px]", "tw:[&_article_>_div]:pb-[10px]", "tw:[&_article_>_div]:pl-[10px]", "tw:[&_strong]:text-[color:#183657]",
    "tw:[&_strong]:text-[.8rem]", "tw:[&_span]:text-[color:#64778c]", "tw:[&_span]:text-[.72rem]", "tw:[&_.button]:[justify-self:start]",
    "tw:[&_.button]:mt-[2px]",
  ].join(" "),
  "control_toggle": sharedUtilities.controlToggle,
  "portal_editor_form": [
    "portal-editor-form", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-620:grid-cols-[1fr]",
    "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:[&_.field]:min-w-[0]", "tw:[&_.form-full]:[grid-column:1_/_-1]",
    "tw:viewport-620:[&_.form-full]:[grid-column:auto]", "tw:[&_input]:w-[100%]", "tw:[&_input]:[box-sizing:border-box]", "tw:[&_textarea]:w-[100%]",
    "tw:[&_textarea]:[box-sizing:border-box]", "tw:[&_textarea]:min-h-[132px]", "tw:[&_textarea]:[resize:vertical]",
  ].join(" "),
  "field_form_full": sharedUtilities.fieldFormFull,
  "field": sharedUtilities.field,
  "portal_editor_form_footer": [
    "portal-editor-form-footer", "tw:flex", "tw:[grid-column:1_/_-1]", "tw:viewport-620:[grid-column:auto]",
    "tw:justify-end", "tw:pt-[2px]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "form_full_muted": [
    "form-full", "muted", "tw:[grid-column:1_/_-1]", "tw:mt-[0]",
    "tw:mr-[0]", "tw:mb-[0]", "tw:ml-[0]", "tw:text-[color:var(--muted)]",
  ].join(" "),
  "button_button_danger": sharedUtilities.buttonButtonDanger,
} as const;
