import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "athlete_portal_content_panel_super12_panel": [
    "athlete-portal-content-panel", "super12-panel", "tw:w-[min(calc(100%_-_32px),_1060px)]", "tw:viewport-700:w-[calc(100%_-_28px)]",
    "tw:[margin-inline:auto]", "tw:mt-[22px]", "tw:viewport-700:mt-[16px]", "tw:pt-[26px]",
    "tw:viewport-700:pt-[16px]", "tw:pr-[26px]", "tw:viewport-700:pr-[16px]", "tw:pb-[26px]",
    "tw:viewport-700:pb-[16px]", "tw:pl-[26px]", "tw:viewport-700:pl-[16px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(120_162_185_/_.2)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:rgb(120_162_185_/_.2)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(120_162_185_/_.2)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(120_162_185_/_.2)]", "tw:rounded-[15px]",
    "tw:bg-[color:#0d1b28]", "tw:[background-image:none]", "tw:[box-shadow:0_18px_42px_rgb(0_0_0_/_.2)]", "tw:[&_>_header]:grid",
    "tw:[&_>_header]:gap-y-[4px]", "tw:[&_>_header]:gap-x-[4px]", "tw:[&_>_header]:pb-[17px]", "tw:[&_>_header]:border-b-[length:1px]",
    "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-t-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-r-[color:rgb(135_178_196_/_.16)]",
    "tw:[&_>_header]:border-l-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header_span]:text-[color:#57d7ae]", "tw:[&_>_header_span]:text-[.66rem]", "tw:[&_>_header_span]:font-[900]",
    "tw:[&_>_header_span]:tracking-[.12em]", "tw:[&_>_header_h2]:mt-[0]", "tw:[&_>_header_h2]:mr-[0]", "tw:[&_>_header_h2]:mb-[0]",
    "tw:[&_>_header_h2]:ml-[0]", "tw:[&_>_header_h2]:text-[color:#f2f9fc]", "tw:[&_>_header_h2]:text-[1.3rem]", "tw:grid",
    "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:[&_>_.super12-create]:w-[fit-content]", "tw:[&_>_.super12-create]:max-w-[100%]",
    "tw:[&_>_.super12-create]:[overflow-x:visible]", "tw:[&_>_.super12-create]:[overflow-y:visible]", "tw:[&_>_.super12-create]:border-t-[length:0]", "tw:[&_>_.super12-create]:[border-top-style:none]",
    "tw:[&_>_.super12-create]:border-t-[color:currentColor]", "tw:[&_>_.super12-create]:border-r-[length:0]", "tw:[&_>_.super12-create]:[border-right-style:none]", "tw:[&_>_.super12-create]:border-r-[color:currentColor]",
    "tw:[&_>_.super12-create]:border-b-[length:0]", "tw:[&_>_.super12-create]:[border-bottom-style:none]", "tw:[&_>_.super12-create]:border-b-[color:currentColor]", "tw:[&_>_.super12-create]:border-l-[length:0]",
    "tw:[&_>_.super12-create]:[border-left-style:none]", "tw:[&_>_.super12-create]:border-l-[color:currentColor]", "tw:[&_>_.super12-create]:rounded-[0]", "tw:[&_>_.super12-create]:bg-[color:transparent]",
    "tw:[&_>_.super12-create]:[background-image:none]", "tw:[&_>_.super12-create_>_summary]:inline-flex", "tw:[&_>_.super12-create_>_summary]:w-[auto]", "tw:[&_>_.super12-create_>_summary]:min-h-[34px]",
    "tw:[&_>_.super12-create_>_summary]:items-center", "tw:[&_>_.super12-create_>_summary]:pt-[7px]", "tw:[&_>_.super12-create_>_summary]:pr-[11px]", "tw:[&_>_.super12-create_>_summary]:pb-[7px]",
    "tw:[&_>_.super12-create_>_summary]:pl-[11px]", "tw:[&_>_.super12-create_>_summary]:border-t-[length:1px]", "tw:[&_>_.super12-create_>_summary]:[border-top-style:solid]", "tw:[&_>_.super12-create_>_summary]:border-t-[color:#176aa5]",
    "tw:[&_>_.super12-create_>_summary]:border-r-[length:1px]", "tw:[&_>_.super12-create_>_summary]:[border-right-style:solid]", "tw:[&_>_.super12-create_>_summary]:border-r-[color:#176aa5]", "tw:[&_>_.super12-create_>_summary]:border-b-[length:1px]",
    "tw:[&_>_.super12-create_>_summary]:[border-bottom-style:solid]", "tw:[&_>_.super12-create_>_summary]:border-b-[color:#176aa5]", "tw:[&_>_.super12-create_>_summary]:border-l-[length:1px]", "tw:[&_>_.super12-create_>_summary]:[border-left-style:solid]",
    "tw:[&_>_.super12-create_>_summary]:border-l-[color:#176aa5]", "tw:[&_>_.super12-create_>_summary]:rounded-[8px]", "tw:[&_>_.super12-create_>_summary]:text-[color:#fff]", "tw:[&_>_.super12-create_>_summary]:bg-[color:#176aa5]",
    "tw:[&_>_.super12-create_>_summary]:[background-image:none]", "tw:[&_>_.super12-create_>_summary]:text-[.74rem]", "tw:[&_>_.super12-create_>_summary]:font-[850]", "tw:[&_>_.super12-create_>_summary]:leading-[1]",
    "tw:[&_>_.super12-create_>_summary:hover]:border-t-[color:#0e568a]", "tw:[&_>_.super12-create_>_summary:hover]:border-r-[color:#0e568a]", "tw:[&_>_.super12-create_>_summary:hover]:border-b-[color:#0e568a]", "tw:[&_>_.super12-create_>_summary:hover]:border-l-[color:#0e568a]",
    "tw:[&_>_.super12-create_>_summary:hover]:bg-[color:#0e568a]", "tw:[&_>_.super12-create_>_summary:hover]:[background-image:none]", "tw:[&_>_.super12-create[open]]:w-[100%]", "tw:[&_>_.super12-create[open]]:[overflow-x:hidden]",
    "tw:[&_>_.super12-create[open]]:[overflow-y:hidden]", "tw:[&_>_.super12-create[open]]:border-t-[length:1px]", "tw:[&_>_.super12-create[open]]:[border-top-style:solid]", "tw:[&_>_.super12-create[open]]:border-t-[color:#cfe2ed]",
    "tw:[&_>_.super12-create[open]]:border-r-[length:1px]", "tw:[&_>_.super12-create[open]]:[border-right-style:solid]", "tw:[&_>_.super12-create[open]]:border-r-[color:#cfe2ed]", "tw:[&_>_.super12-create[open]]:border-b-[length:1px]",
    "tw:[&_>_.super12-create[open]]:[border-bottom-style:solid]", "tw:[&_>_.super12-create[open]]:border-b-[color:#cfe2ed]", "tw:[&_>_.super12-create[open]]:border-l-[length:1px]", "tw:[&_>_.super12-create[open]]:[border-left-style:solid]",
    "tw:[&_>_.super12-create[open]]:border-l-[color:#cfe2ed]", "tw:[&_>_.super12-create[open]]:rounded-[12px]", "tw:[&_>_.super12-create[open]]:bg-[color:#f8fcff]", "tw:[&_>_.super12-create[open]]:[background-image:none]",
    "tw:[&_>_.super12-create[open]_>_summary]:w-[100%]", "tw:[&_>_.super12-create[open]_>_summary]:border-t-[length:0]", "tw:[&_>_.super12-create[open]_>_summary]:[border-top-style:none]", "tw:[&_>_.super12-create[open]_>_summary]:border-t-[color:currentColor]",
    "tw:[&_>_.super12-create[open]_>_summary]:border-r-[length:0]", "tw:[&_>_.super12-create[open]_>_summary]:[border-right-style:none]", "tw:[&_>_.super12-create[open]_>_summary]:border-r-[color:currentColor]", "tw:[&_>_.super12-create[open]_>_summary]:border-b-[length:0]",
    "tw:[&_>_.super12-create[open]_>_summary]:[border-bottom-style:none]", "tw:[&_>_.super12-create[open]_>_summary]:border-b-[color:currentColor]", "tw:[&_>_.super12-create[open]_>_summary]:border-l-[length:0]", "tw:[&_>_.super12-create[open]_>_summary]:[border-left-style:none]",
    "tw:[&_>_.super12-create[open]_>_summary]:border-l-[color:currentColor]", "tw:[&_>_.super12-create[open]_>_summary]:rounded-[0]", "tw:[&_>_.super12-create[open]_>_summary]:text-[color:#164460]", "tw:[&_>_.super12-create[open]_>_summary]:bg-[color:transparent]",
    "tw:[&_>_.super12-create[open]_>_summary]:[background-image:none]", "tw:[&_>_.super12-create[open]_>_summary:hover]:text-[color:#0e568a]", "tw:[&_>_.super12-create[open]_>_summary:hover]:bg-[color:#eef7fc]", "tw:[&_>_.super12-create[open]_>_summary:hover]:[background-image:none]",
  ].join(" "),
  "super12_event_list": [
    "super12-event-list", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:[&_>_strong]:text-[color:#24516b]", "tw:[&_>_strong]:text-[.78rem]", "tw:[&_>_div]:flex", "tw:[&_>_div]:flex-wrap",
    "tw:[&_>_div]:gap-y-[7px]", "tw:[&_>_div]:gap-x-[7px]", "tw:[&_a]:grid", "tw:[&_a]:gap-y-[2px]",
    "tw:[&_a]:gap-x-[2px]", "tw:[&_a]:min-w-[180px]", "tw:[&_a]:pt-[9px]", "tw:[&_a]:pr-[11px]",
    "tw:[&_a]:pb-[9px]", "tw:[&_a]:pl-[11px]", "tw:[&_a]:border-t-[length:1px]", "tw:[&_a]:[border-top-style:solid]",
    "tw:[&_a]:border-t-[color:#d2e3ea]", "tw:[&_a]:border-r-[length:1px]", "tw:[&_a]:[border-right-style:solid]", "tw:[&_a]:border-r-[color:#d2e3ea]",
    "tw:[&_a]:border-b-[length:1px]", "tw:[&_a]:[border-bottom-style:solid]", "tw:[&_a]:border-b-[color:#d2e3ea]", "tw:[&_a]:border-l-[length:1px]",
    "tw:[&_a]:[border-left-style:solid]", "tw:[&_a]:border-l-[color:#d2e3ea]", "tw:[&_a]:rounded-[8px]", "tw:[&_a]:text-[color:#24516b]",
    "tw:[&_a]:bg-[color:#fff]", "tw:[&_a]:[background-image:none]", "tw:[&_a]:[text-decoration:none]", "tw:[&_a.active]:border-t-[color:#168b70]",
    "tw:[&_a.active]:border-r-[color:#168b70]", "tw:[&_a.active]:border-b-[color:#168b70]", "tw:[&_a.active]:border-l-[color:#168b70]", "tw:[&_a.active]:bg-[color:#edf9f4]",
    "tw:[&_a.active]:[background-image:none]", "tw:[&_b]:text-[.76rem]", "tw:[&_span]:text-[color:#668094]", "tw:[&_span]:text-[.66rem]",
  ].join(" "),
  "super12_finished": [
    "super12-finished", "tw:grid", "tw:grid-cols-[42px_minmax(0,_1fr)_auto]", "tw:viewport-700:grid-cols-[42px_minmax(0,_1fr)]",
    "tw:items-center", "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:pt-[16px]",
    "tw:pr-[16px]", "tw:pb-[16px]", "tw:pl-[16px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#d5e3eb]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#d5e3eb]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d5e3eb]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d5e3eb]", "tw:rounded-[11px]",
    "tw:bg-[color:#f8fbfd]", "tw:[background-image:none]", "tw:[&_>_span]:grid", "tw:[&_>_span]:w-[42px]",
    "tw:[&_>_span]:h-[42px]", "tw:[&_>_span]:place-items-center", "tw:[&_>_span]:rounded-[50%]", "tw:[&_>_span]:bg-[color:#e8f1f8]",
    "tw:[&_>_span]:[background-image:none]", "tw:[&_>_span]:text-[1.15rem]", "tw:[&_strong]:text-[color:#1b4d68]", "tw:[&_strong]:text-[.86rem]",
    "tw:[&_p]:mt-[3px]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
    "tw:[&_p]:text-[color:#637d8e]", "tw:[&_p]:text-[.74rem]", "tw:[&_.button]:whitespace-nowrap", "tw:viewport-700:[&_.button]:[grid-column:1_/_-1]",
    "tw:viewport-700:[&_.button]:w-[fit-content]",
  ].join(" "),
  "super12_board": [
    "super12-board", "tw:[&_>_header_span]:text-[color:#1264a5]", "tw:[&_>_header_span]:text-[.64rem]", "tw:[&_>_header_span]:font-[900]",
    "tw:[&_>_header_span]:tracking-[.09em]", "tw:grid", "tw:gap-y-[14px]", "tw:gap-x-[14px]",
    "tw:[&_>_header]:flex", "tw:[&_>_header]:items-start", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[12px]",
    "tw:[&_>_header]:gap-x-[12px]", "tw:[&_>_header]:pt-[15px]", "tw:[&_>_header]:pr-[15px]", "tw:[&_>_header]:pb-[15px]",
    "tw:[&_>_header]:pl-[15px]", "tw:[&_>_header]:border-t-[length:1px]", "tw:[&_>_header]:[border-top-style:solid]", "tw:[&_>_header]:border-t-[color:#bfe3d6]",
    "tw:[&_>_header]:border-r-[length:1px]", "tw:[&_>_header]:[border-right-style:solid]", "tw:[&_>_header]:border-r-[color:#bfe3d6]", "tw:[&_>_header]:border-b-[length:1px]",
    "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#bfe3d6]", "tw:[&_>_header]:border-l-[length:1px]", "tw:[&_>_header]:[border-left-style:solid]",
    "tw:[&_>_header]:border-l-[color:#bfe3d6]", "tw:[&_>_header]:rounded-[11px]", "tw:[&_>_header]:bg-[color:transparent]", "tw:[&_>_header]:[background-image:linear-gradient(110deg,_#f0fbf6,_#fbfffd)]",
    "tw:[&_h3]:mt-[4px]", "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[2px]", "tw:[&_h3]:ml-[0]",
    "tw:[&_h3]:text-[color:#124b62]", "tw:[&_h3]:text-[1.05rem]", "tw:[&_header_p]:mt-[0]", "tw:[&_header_p]:mr-[0]",
    "tw:[&_header_p]:mb-[0]", "tw:[&_header_p]:ml-[0]", "tw:[&_header_p]:text-[color:#5e7d7a]", "tw:[&_header_p]:text-[.74rem]",
    "tw:[&_>_header_form]:mt-[0]", "tw:[&_>_header_form]:mr-[0]", "tw:[&_>_header_form]:mb-[0]", "tw:[&_>_header_form]:ml-[0]",
    "tw:viewport-700:[&_>_header]:flex-col",
  ].join(" "),
  "super12_finish_keyword": [
    "super12-finish-keyword", "tw:mt-[8px]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-[color:#315d72]", "tw:text-[.75rem]", "tw:leading-[1.35]",
    "tw:[&_strong]:inline-block", "tw:[&_strong]:ml-[3px]", "tw:[&_strong]:pt-[2px]", "tw:[&_strong]:pr-[6px]",
    "tw:[&_strong]:pb-[2px]", "tw:[&_strong]:pl-[6px]", "tw:[&_strong]:rounded-[4px]", "tw:[&_strong]:text-[color:#fff]",
    "tw:[&_strong]:bg-[color:#1b5c85]", "tw:[&_strong]:[background-image:none]", "tw:[&_strong]:tracking-[.06em]",
  ].join(" "),
  "super12_group": [
    "super12-group", "tw:grid", "tw:gap-y-[9px]", "tw:gap-x-[9px]",
    "tw:[&_h4]:mt-[0]", "tw:[&_h4]:mr-[0]", "tw:[&_h4]:mb-[0]", "tw:[&_h4]:ml-[0]",
    "tw:[&_h4]:text-[color:#174861]", "tw:[&_h4]:text-[.86rem]",
  ].join(" "),
  "super12_group_layout": [
    "super12-group-layout", "tw:grid", "tw:grid-cols-[minmax(0,_1.25fr)_minmax(300px,_.75fr)]", "tw:viewport-700:grid-cols-[1fr]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]",
  ].join(" "),
  "super12_matches": [
    "super12-matches", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:pt-[12px]", "tw:pr-[12px]", "tw:pb-[12px]", "tw:pl-[12px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d3e4eb]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#d3e4eb]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#d3e4eb]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d3e4eb]",
    "tw:rounded-[10px]", "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[&_>_strong]:text-[color:#27526a]",
    "tw:[&_>_strong]:text-[.76rem]", "tw:[&_article]:flex", "tw:[&_article]:items-center", "tw:viewport-700:[&_article]:items-start",
    "tw:[&_article]:justify-between", "tw:[&_article]:gap-y-[10px]", "tw:[&_article]:gap-x-[10px]", "tw:[&_article]:min-h-[39px]",
    "tw:[&_article]:pt-[7px]", "tw:[&_article]:pr-[0]", "tw:[&_article]:pb-[7px]", "tw:[&_article]:pl-[0]",
    "tw:[&_article]:border-t-[length:1px]", "tw:[&_article]:[border-top-style:solid]", "tw:[&_article]:border-t-[color:#edf2f5]", "tw:[&_article_>_div]:flex",
    "tw:[&_article_>_div]:min-w-[0]", "tw:[&_article_>_div]:items-center", "tw:[&_article_>_div]:gap-y-[6px]", "tw:[&_article_>_div]:gap-x-[6px]",
    "tw:[&_article_>_div]:text-[color:#244c64]", "tw:[&_article_>_div]:text-[.72rem]", "tw:[&_article_b]:[overflow-x:hidden]", "tw:[&_article_b]:[overflow-y:hidden]",
    "tw:[&_article_b]:text-ellipsis", "tw:[&_article_b]:whitespace-nowrap", "tw:[&_form]:flex", "tw:[&_form]:items-center",
    "tw:[&_form]:gap-y-[4px]", "tw:[&_form]:gap-x-[4px]", "tw:[&_form]:mt-[0]", "tw:[&_form]:mr-[0]",
    "tw:[&_form]:mb-[0]", "tw:[&_form]:ml-[0]", "tw:[&_form_label]:contents", "tw:[&_form_input]:w-[38px]",
    "tw:[&_form_input]:h-[29px]", "tw:[&_form_input]:border-t-[length:1px]", "tw:[&_form_input]:[border-top-style:solid]", "tw:[&_form_input]:border-t-[color:#cbdde7]",
    "tw:[&_form_input]:border-r-[length:1px]", "tw:[&_form_input]:[border-right-style:solid]", "tw:[&_form_input]:border-r-[color:#cbdde7]", "tw:[&_form_input]:border-b-[length:1px]",
    "tw:[&_form_input]:[border-bottom-style:solid]", "tw:[&_form_input]:border-b-[color:#cbdde7]", "tw:[&_form_input]:border-l-[length:1px]", "tw:[&_form_input]:[border-left-style:solid]",
    "tw:[&_form_input]:border-l-[color:#cbdde7]", "tw:[&_form_input]:rounded-[6px]", "tw:[&_form_input]:pt-[0]", "tw:[&_form_input]:pr-[4px]",
    "tw:[&_form_input]:pb-[0]", "tw:[&_form_input]:pl-[4px]", "tw:[&_form_input]:text-center", "tw:[&_em]:text-[color:#5e7b8e]",
    "tw:[&_em]:text-[.72rem]", "tw:[&_em]:not-italic", "tw:viewport-700:[&_article]:flex-col", "tw:viewport-700:[&_article_>_div]:w-[100%]",
  ].join(" "),
  "super12_standing": [
    "super12-standing", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:pt-[12px]", "tw:pr-[12px]", "tw:pb-[12px]", "tw:pl-[12px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d3e4eb]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#d3e4eb]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#d3e4eb]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d3e4eb]",
    "tw:rounded-[10px]", "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[&_>_strong]:text-[color:#27526a]",
    "tw:[&_>_strong]:text-[.76rem]", "tw:[&_table]:w-[100%]", "tw:[&_table]:[border-collapse:collapse]", "tw:[&_table]:text-[color:#365d73]",
    "tw:[&_table]:text-[.7rem]", "tw:[&_th]:pt-[6px]", "tw:[&_th]:pr-[4px]", "tw:[&_th]:pb-[6px]",
    "tw:[&_th]:pl-[4px]", "tw:[&_th]:border-t-[length:1px]", "tw:[&_th]:[border-top-style:solid]", "tw:[&_th]:border-t-[color:#edf2f5]",
    "tw:[&_th]:text-center", "tw:[&_td]:pt-[6px]", "tw:[&_td]:pr-[4px]", "tw:[&_td]:pb-[6px]",
    "tw:[&_td]:pl-[4px]", "tw:[&_td]:border-t-[length:1px]", "tw:[&_td]:[border-top-style:solid]", "tw:[&_td]:border-t-[color:#edf2f5]",
    "tw:[&_td]:text-center", "tw:[&_th:nth-child(2)]:max-w-[125px]", "tw:[&_th:nth-child(2)]:[overflow-x:hidden]", "tw:[&_th:nth-child(2)]:[overflow-y:hidden]",
    "tw:[&_th:nth-child(2)]:text-left", "tw:[&_th:nth-child(2)]:text-ellipsis", "tw:[&_th:nth-child(2)]:whitespace-nowrap", "tw:[&_td:nth-child(2)]:max-w-[125px]",
    "tw:[&_td:nth-child(2)]:[overflow-x:hidden]", "tw:[&_td:nth-child(2)]:[overflow-y:hidden]", "tw:[&_td:nth-child(2)]:text-left", "tw:[&_td:nth-child(2)]:text-ellipsis",
    "tw:[&_td:nth-child(2)]:whitespace-nowrap", "tw:[&_small]:text-[color:#708796]", "tw:[&_small]:text-[.64rem]",
  ].join(" "),
  "super12_empty": [
    "super12-empty", "tw:pt-[24px]", "tw:pr-[24px]", "tw:pb-[24px]",
    "tw:pl-[24px]", "tw:border-t-[length:1px]", "tw:[border-top-style:dashed]", "tw:border-t-[color:#bad4e0]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:dashed]", "tw:border-r-[color:#bad4e0]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:dashed]", "tw:border-b-[color:#bad4e0]", "tw:border-l-[length:1px]", "tw:[border-left-style:dashed]",
    "tw:border-l-[color:#bad4e0]", "tw:rounded-[10px]", "tw:text-[color:#547386]", "tw:text-center",
    "tw:[&_strong]:text-[color:#164b66]", "tw:[&_p]:mt-[4px]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[.78rem]",
  ].join(" "),
} as const;
