import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "super12_create": [
    "super12-create", "tw:[&_summary_>_span]:text-[color:#1264a5]", "tw:[&_summary_>_span]:text-[.64rem]", "tw:[&_summary_>_span]:font-[900]",
    "tw:[&_summary_>_span]:tracking-[.09em]", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#cfe2ed]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#cfe2ed]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#cfe2ed]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#cfe2ed]", "tw:rounded-[12px]",
    "tw:bg-[color:#f8fcff]", "tw:[background-image:none]", "tw:[&_summary]:grid", "tw:[&_summary]:gap-y-[2px]",
    "tw:[&_summary]:gap-x-[2px]", "tw:[&_summary]:pt-[15px]", "tw:[&_summary]:pr-[17px]", "tw:[&_summary]:pb-[15px]",
    "tw:[&_summary]:pl-[17px]", "tw:[&_summary]:cursor-pointer", "tw:[&_summary]:[list-style:none]", "tw:[&_summary::-webkit-details-marker]:hidden",
    "tw:[&_summary_strong]:text-[color:#164460]", "tw:[&_summary_strong]:text-[.95rem]", "tw:[&_summary_small]:text-[color:#638094]", "tw:[&_summary_small]:text-[.75rem]",
  ].join(" "),
  "super12_create_form": [
    "super12-create-form", "tw:grid", "tw:grid-cols-[minmax(220px,_1fr)_180px_150px]", "tw:viewport-700:grid-cols-[1fr]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:pt-[0]", "tw:pr-[17px]",
    "tw:pb-[17px]", "tw:pl-[17px]", "tw:[&_>_label]:grid", "tw:[&_>_label]:gap-y-[5px]",
    "tw:[&_>_label]:gap-x-[5px]", "tw:[&_>_label]:text-[color:#49677b]", "tw:[&_>_label]:text-[.72rem]", "tw:[&_>_label]:font-[800]",
    "tw:[&_input]:min-h-[36px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#c9dce7]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#c9dce7]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:#c9dce7]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:#c9dce7]", "tw:[&_input]:rounded-[8px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[9px]",
    "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[9px]", "tw:[&_input]:bg-[color:#fff]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:text-[color:#143e5b]", "tw:[&_select]:min-h-[36px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]",
    "tw:[&_select]:border-t-[color:#c9dce7]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#c9dce7]",
    "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:#c9dce7]", "tw:[&_select]:border-l-[length:1px]",
    "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#c9dce7]", "tw:[&_select]:rounded-[8px]", "tw:[&_select]:pt-[0]",
    "tw:[&_select]:pr-[9px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[9px]", "tw:[&_select]:bg-[color:#fff]",
    "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:#143e5b]",
  ].join(" "),
  "super12_selector": [
    "super12-selector", "tw:grid", "tw:[grid-column:1_/_-1]", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:pt-[12px]", "tw:pr-[12px]", "tw:pb-[12px]",
    "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d5e5ed]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d5e5ed]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d5e5ed]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#d5e5ed]", "tw:rounded-[9px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[&_>_div:first-child]:flex", "tw:[&_>_div:first-child]:items-baseline", "tw:viewport-700:[&_>_div:first-child]:items-start", "tw:[&_>_div:first-child]:justify-between",
    "tw:[&_>_div:first-child]:gap-y-[8px]", "tw:[&_>_div:first-child]:gap-x-[8px]", "tw:[&_strong]:text-[color:#17455f]", "tw:[&_strong]:text-[.82rem]",
    "tw:[&_span]:mt-[0]", "tw:[&_span]:mr-[0]", "tw:[&_span]:mb-[0]", "tw:[&_span]:ml-[0]",
    "tw:[&_span]:text-[color:#688195]", "tw:[&_span]:text-[.72rem]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#688195]", "tw:[&_p]:text-[.72rem]",
    "tw:viewport-700:[&_>_div:first-child]:flex-col",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "super12_player_search": [
    "super12-player-search", "tw:relative", "tw:grid", "tw:gap-y-[5px]",
    "tw:gap-x-[5px]", "tw:max-w-[460px]", "tw:text-[color:#49677b]", "tw:text-[.72rem]",
    "tw:font-[800]", "tw:[&_input]:min-h-[37px]", "tw:[&_[role=listbox]]:absolute", "tw:[&_[role=listbox]]:z-[4]",
    "tw:[&_[role=listbox]]:top-[100%]", "tw:[&_[role=listbox]]:right-[0]", "tw:[&_[role=listbox]]:left-[0]", "tw:[&_[role=listbox]]:grid",
    "tw:[&_[role=listbox]]:gap-y-[2px]", "tw:[&_[role=listbox]]:gap-x-[2px]", "tw:[&_[role=listbox]]:max-h-[250px]", "tw:[&_[role=listbox]]:[overflow-x:auto]",
    "tw:[&_[role=listbox]]:[overflow-y:auto]", "tw:[&_[role=listbox]]:pt-[5px]", "tw:[&_[role=listbox]]:pr-[5px]", "tw:[&_[role=listbox]]:pb-[5px]",
    "tw:[&_[role=listbox]]:pl-[5px]", "tw:[&_[role=listbox]]:border-t-[length:1px]", "tw:[&_[role=listbox]]:[border-top-style:solid]", "tw:[&_[role=listbox]]:border-t-[color:#bed8e6]",
    "tw:[&_[role=listbox]]:border-r-[length:1px]", "tw:[&_[role=listbox]]:[border-right-style:solid]", "tw:[&_[role=listbox]]:border-r-[color:#bed8e6]", "tw:[&_[role=listbox]]:border-b-[length:1px]",
    "tw:[&_[role=listbox]]:[border-bottom-style:solid]", "tw:[&_[role=listbox]]:border-b-[color:#bed8e6]", "tw:[&_[role=listbox]]:border-l-[length:1px]", "tw:[&_[role=listbox]]:[border-left-style:solid]",
    "tw:[&_[role=listbox]]:border-l-[color:#bed8e6]", "tw:[&_[role=listbox]]:rounded-[8px]", "tw:[&_[role=listbox]]:bg-[color:#fff]", "tw:[&_[role=listbox]]:[background-image:none]",
    "tw:[&_[role=listbox]]:[box-shadow:0_12px_22px_rgb(21_65_91_/_.14)]", "tw:[&_[role=listbox]_button]:grid", "tw:[&_[role=listbox]_button]:grid-cols-[26px_minmax(0,_1fr)_auto]", "tw:[&_[role=listbox]_button]:items-center",
    "tw:[&_[role=listbox]_button]:gap-y-[7px]", "tw:[&_[role=listbox]_button]:gap-x-[7px]", "tw:[&_[role=listbox]_button]:w-[100%]", "tw:[&_[role=listbox]_button]:min-h-[35px]",
    "tw:[&_[role=listbox]_button]:border-t-[length:0]", "tw:[&_[role=listbox]_button]:[border-top-style:none]", "tw:[&_[role=listbox]_button]:border-t-[color:currentColor]", "tw:[&_[role=listbox]_button]:border-r-[length:0]",
    "tw:[&_[role=listbox]_button]:[border-right-style:none]", "tw:[&_[role=listbox]_button]:border-r-[color:currentColor]", "tw:[&_[role=listbox]_button]:border-b-[length:0]", "tw:[&_[role=listbox]_button]:[border-bottom-style:none]",
    "tw:[&_[role=listbox]_button]:border-b-[color:currentColor]", "tw:[&_[role=listbox]_button]:border-l-[length:0]", "tw:[&_[role=listbox]_button]:[border-left-style:none]", "tw:[&_[role=listbox]_button]:border-l-[color:currentColor]",
    "tw:[&_[role=listbox]_button]:rounded-[6px]", "tw:[&_[role=listbox]_button]:pt-[5px]", "tw:[&_[role=listbox]_button]:pr-[5px]", "tw:[&_[role=listbox]_button]:pb-[5px]",
    "tw:[&_[role=listbox]_button]:pl-[5px]", "tw:[&_[role=listbox]_button]:text-[color:#244f68]", "tw:[&_[role=listbox]_button]:bg-[color:transparent]", "tw:[&_[role=listbox]_button]:[background-image:none]",
    "tw:[&_[role=listbox]_button]:[font:inherit]", "tw:[&_[role=listbox]_button]:text-left", "tw:[&_[role=listbox]_button]:cursor-pointer", "tw:[&_[role=listbox]_button:hover]:bg-[color:#eff8fb]",
    "tw:[&_[role=listbox]_button:hover]:[background-image:none]", "tw:[&_[role=listbox]_span]:grid", "tw:[&_[role=listbox]_span]:w-[24px]", "tw:[&_[role=listbox]_span]:h-[24px]",
    "tw:[&_[role=listbox]_span]:[overflow-x:hidden]", "tw:[&_[role=listbox]_span]:[overflow-y:hidden]", "tw:[&_[role=listbox]_span]:place-items-center", "tw:[&_[role=listbox]_span]:rounded-[50%]",
    "tw:[&_[role=listbox]_span]:text-[color:#fff]", "tw:[&_[role=listbox]_span]:bg-[color:#2c7aac]", "tw:[&_[role=listbox]_span]:[background-image:none]", "tw:[&_[role=listbox]_span]:text-[.58rem]",
    "tw:[&_img]:w-[100%]", "tw:[&_img]:h-[100%]", "tw:[&_img]:[object-fit:cover]", "tw:[&_[role=listbox]_small]:text-[color:#16836b]",
    "tw:[&_[role=listbox]_small]:text-[.65rem]",
  ].join(" "),
  "super12_create_actions": [
    "super12-create-actions", "tw:flex", "tw:[grid-column:1_/_-1]", "tw:items-center",
    "tw:viewport-700:items-start", "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:[&_small]:text-[color:#667f91]",
    "tw:[&_small]:text-[.7rem]", "tw:viewport-700:flex-col",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
} as const;
