import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "public_booking_shell": [
    "public-booking-shell", "tw:w-[min(100%,_1020px)]", "tw:viewport-720:w-[100%]", "tw:mt-[0]",
    "tw:mr-[auto]", "tw:mb-[0]", "tw:ml-[auto]", "tw:pt-[30px]",
    "tw:viewport-720:pt-[16px]", "tw:pr-[30px]", "tw:viewport-720:pr-[16px]", "tw:pb-[30px]",
    "tw:viewport-720:pb-[16px]", "tw:pl-[30px]", "tw:viewport-720:pl-[16px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(255_255_255_/_.42)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:rgb(255_255_255_/_.42)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(255_255_255_/_.42)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(255_255_255_/_.42)]", "tw:rounded-[16px]",
    "tw:viewport-720:rounded-[12px]", "tw:bg-[color:rgb(255_255_255_/_.96)]", "tw:[background-image:none]", "tw:[box-shadow:0_24px_70px_rgb(0_24_47_/_.35)]",
    "tw:[&_>_header]:flex", "tw:[&_>_header]:gap-y-[14px]", "tw:[&_>_header]:gap-x-[14px]", "tw:[&_>_header]:items-center",
    "tw:viewport-720:[&_>_header]:items-start", "tw:[&_>_header]:pt-[0]", "tw:[&_>_header]:pr-[0]", "tw:[&_>_header]:pb-[18px]",
    "tw:[&_>_header]:pl-[0]", "tw:[&_>_header]:border-b-[length:2px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#d4e6f0]",
    "tw:[&_>_header_img]:w-[52px]", "tw:[&_>_header_img]:h-[52px]", "tw:[&_>_header_img]:rounded-[11px]", "tw:[&_>_header_img]:[object-fit:cover]",
    "tw:[&_>_header_img]:bg-[color:#075a87]", "tw:[&_>_header_img]:[background-image:none]", "tw:[&_>_header_img]:[box-shadow:0_5px_12px_rgb(0_59_101_/_.22)]", "tw:[&_header_span]:text-[color:#08775f]",
    "tw:[&_header_span]:text-[.68rem]", "tw:[&_header_span]:font-[850]", "tw:[&_header_span]:tracking-[.1em]", "tw:[&_h1]:mt-[3px]",
    "tw:[&_h1]:mr-[0]", "tw:[&_h1]:mb-[3px]", "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[color:#073d62]",
    "tw:[&_h1]:text-[1.45rem]", "tw:[&_h2]:mt-[22px]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[11px]",
    "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#073d62]", "tw:[&_h2]:text-[1.1rem]", "tw:[&_p]:mt-[0]",
    "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#506a82]",
    "tw:[&_p]:text-[.86rem]",
  ].join(" "),
  "public_booking_shell_embedded": [
    "public-booking-shell-embedded", "tw:w-[100%]", "tw:mt-[0]", "tw:mr-[0]",
    "tw:mb-[0]", "tw:ml-[0]",
  ].join(" "),
  "public_booking_date": [
    "public-booking-date", "tw:flex", "tw:[align-items:end]", "tw:viewport-680:items-stretch",
    "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:mt-[18px]", "tw:[&_label]:grid",
    "tw:[&_label]:gap-y-[5px]", "tw:[&_label]:gap-x-[5px]", "tw:[&_label]:text-[color:#4b5d77]", "tw:[&_label]:text-[.74rem]",
    "tw:[&_label]:font-[750]", "tw:[&_input]:min-h-[36px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[9px]",
    "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[9px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]",
    "tw:[&_input]:border-t-[color:#cbd9e8]", "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#cbd9e8]",
    "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:#cbd9e8]", "tw:[&_input]:border-l-[length:1px]",
    "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#cbd9e8]", "tw:[&_input]:rounded-[var(--radius-control)]", "tw:[&_input]:text-[color:#172033]",
    "tw:[&_input]:bg-[color:#fff]", "tw:[&_input]:[background-image:none]", "tw:[&_input]:[font:inherit]", "tw:viewport-680:flex-col",
    "tw:viewport-720:[&_.button]:w-[100%]", "tw:viewport-720:[&_.button]:justify-center",
  ].join(" "),
  "button": sharedUtilities.button,
  "public_booking_reserved": [
    "public-booking-reserved", "tw:mt-[13px]!", "tw:pt-[9px]", "tw:pr-[10px]",
    "tw:pb-[9px]", "tw:pl-[10px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dbe5ef]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dbe5ef]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dbe5ef]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dbe5ef]", "tw:rounded-[8px]", "tw:bg-[color:#f4f8fc]",
    "tw:[background-image:none]",
  ].join(" "),
  "public_booking_disabled": [
    "public-booking-disabled", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:max-w-[580px]", "tw:mt-[34px]", "tw:mr-[auto]", "tw:mb-[8px]",
    "tw:ml-[auto]", "tw:pt-[22px]", "tw:pr-[22px]", "tw:pb-[22px]",
    "tw:pl-[22px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(86_181_233_/_.38)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(86_181_233_/_.38)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(86_181_233_/_.38)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgb(86_181_233_/_.38)]", "tw:rounded-[12px]", "tw:bg-[color:rgb(10_39_58_/_.7)]", "tw:[background-image:none]",
    "tw:[&_span]:text-[color:#51d6ad]", "tw:[&_span]:text-[.7rem]", "tw:[&_span]:font-[800]", "tw:[&_span]:tracking-[.1em]",
    "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]",
    "tw:[&_h2]:text-[color:#f1f9ff]", "tw:[&_h2]:text-[1.3rem]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#b7cad9]", "tw:[&_p]:leading-[1.5]",
  ].join(" "),
  "athlete_portal_booking": [
    "athlete-portal-booking", "tw:w-[min(calc(100%_-_32px),_1060px)]", "tw:mt-[22px]", "tw:mr-[auto]",
    "tw:mb-[0]", "tw:ml-[auto]", "tw:[&_.public-booking-shell]:border-t-[color:rgb(74_157_181_/_.28)]", "tw:[&_.public-booking-shell]:border-r-[color:rgb(74_157_181_/_.28)]",
    "tw:[&_.public-booking-shell]:border-b-[color:rgb(74_157_181_/_.28)]", "tw:[&_.public-booking-shell]:border-l-[color:rgb(74_157_181_/_.28)]", "tw:[&_.public-booking-shell]:bg-[color:transparent]", "tw:[&_.public-booking-shell]:[background-image:linear-gradient(145deg,_#0d263b,_#091a2d)]",
    "tw:[&_.public-booking-shell]:[box-shadow:inset_0_1px_rgb(255_255_255_/_.04),_0_18px_42px_rgb(0_0_0_/_.22)]", "tw:[&_.public-booking-shell]:text-[color:#eaf5fb]", "tw:[&_.public-booking-shell_>_header]:border-t-[color:rgb(75_151_176_/_.25)]", "tw:[&_.public-booking-shell_>_header]:border-r-[color:rgb(75_151_176_/_.25)]",
    "tw:[&_.public-booking-shell_>_header]:border-b-[color:rgb(75_151_176_/_.25)]", "tw:[&_.public-booking-shell_>_header]:border-l-[color:rgb(75_151_176_/_.25)]", "tw:[&_.public-booking-shell_>_header_img]:border-t-[length:0]", "tw:[&_.public-booking-shell_>_header_img]:[border-top-style:none]",
    "tw:[&_.public-booking-shell_>_header_img]:border-t-[color:currentColor]", "tw:[&_.public-booking-shell_>_header_img]:border-r-[length:0]", "tw:[&_.public-booking-shell_>_header_img]:[border-right-style:none]", "tw:[&_.public-booking-shell_>_header_img]:border-r-[color:currentColor]",
    "tw:[&_.public-booking-shell_>_header_img]:border-b-[length:0]", "tw:[&_.public-booking-shell_>_header_img]:[border-bottom-style:none]", "tw:[&_.public-booking-shell_>_header_img]:border-b-[color:currentColor]", "tw:[&_.public-booking-shell_>_header_img]:border-l-[length:0]",
    "tw:[&_.public-booking-shell_>_header_img]:[border-left-style:none]", "tw:[&_.public-booking-shell_>_header_img]:border-l-[color:currentColor]", "tw:[&_.public-booking-shell_>_header_img]:rounded-[0]", "tw:[&_.public-booking-shell_>_header_img]:bg-[color:transparent]",
    "tw:[&_.public-booking-shell_>_header_img]:[background-image:none]", "tw:[&_.public-booking-shell_>_header_img]:[box-shadow:none]", "tw:[&_.public-booking-shell_>_header_img]:[object-fit:contain]", "tw:[&_.public-booking-shell_h1]:text-[color:#f1f9ff]",
    "tw:[&_.public-booking-shell_h2]:text-[color:#f1f9ff]", "tw:[&_.public-booking-shell_p]:text-[color:#b7cad9]", "tw:[&_.public-booking-date_label]:text-[color:#b7cad9]", "tw:[&_.public-booking-form_.field]:text-[color:#b7cad9]",
    "tw:[&_.public-booking-slot-blocks_strong]:text-[color:#b7cad9]", "tw:[&_.public-booking-date_input]:border-t-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-date_input]:border-r-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-date_input]:border-b-[color:rgb(92_151_190_/_.42)]",
    "tw:[&_.public-booking-date_input]:border-l-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-date_input]:bg-[color:#102b46]", "tw:[&_.public-booking-date_input]:[background-image:none]", "tw:[&_.public-booking-date_input]:text-[color:#edf7ff]",
    "tw:[&_.public-booking-form_input]:border-t-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-form_input]:border-r-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-form_input]:border-b-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-form_input]:border-l-[color:rgb(92_151_190_/_.42)]",
    "tw:[&_.public-booking-form_input]:bg-[color:#102b46]", "tw:[&_.public-booking-form_input]:[background-image:none]", "tw:[&_.public-booking-form_input]:text-[color:#edf7ff]", "tw:[&_.public-booking-form_select]:border-t-[color:rgb(92_151_190_/_.42)]",
    "tw:[&_.public-booking-form_select]:border-r-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-form_select]:border-b-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-form_select]:border-l-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-form_select]:bg-[color:#102b46]",
    "tw:[&_.public-booking-form_select]:[background-image:none]", "tw:[&_.public-booking-form_select]:text-[color:#edf7ff]", "tw:[&_.public-booking-reserved]:border-t-[color:rgb(83_146_192_/_.3)]", "tw:[&_.public-booking-reserved]:border-r-[color:rgb(83_146_192_/_.3)]",
    "tw:[&_.public-booking-reserved]:border-b-[color:rgb(83_146_192_/_.3)]", "tw:[&_.public-booking-reserved]:border-l-[color:rgb(83_146_192_/_.3)]", "tw:[&_.public-booking-reserved]:bg-[color:rgb(19_53_82_/_.62)]", "tw:[&_.public-booking-reserved]:[background-image:none]",
    "tw:[&_.public-booking-reserved]:text-[color:#b9d8f0]", "tw:[&_.public-booking-form]:border-t-[color:rgb(62_173_192_/_.42)]", "tw:[&_.public-booking-form]:border-r-[color:rgb(62_173_192_/_.42)]", "tw:[&_.public-booking-form]:border-b-[color:rgb(62_173_192_/_.42)]",
    "tw:[&_.public-booking-form]:border-l-[color:rgb(62_173_192_/_.42)]", "tw:[&_.public-booking-form]:bg-[color:transparent]", "tw:[&_.public-booking-form]:[background-image:linear-gradient(145deg,_#0c2d42,_#0c2237)]", "tw:[&_.public-booking-slot-block]:border-t-[color:rgb(89_155_194_/_.48)]",
    "tw:[&_.public-booking-slot-block]:border-r-[color:rgb(89_155_194_/_.48)]", "tw:[&_.public-booking-slot-block]:border-b-[color:rgb(89_155_194_/_.48)]", "tw:[&_.public-booking-slot-block]:border-l-[color:rgb(89_155_194_/_.48)]", "tw:[&_.public-booking-slot-block]:bg-[color:#102d49]",
    "tw:[&_.public-booking-slot-block]:[background-image:none]", "tw:[&_.public-booking-slot-block]:text-[color:#e5f2fb]", "tw:[&_.public-booking-slot-block_small]:text-[color:#a8c4d8]", "tw:[&_.public-booking-slot-block:hover]:border-t-[color:#4ee8b1]",
    "tw:[&_.public-booking-slot-block:hover]:border-r-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block:hover]:border-b-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block:hover]:border-l-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block:hover]:bg-[color:rgb(20_83_76_/_.72)]",
    "tw:[&_.public-booking-slot-block:hover]:[background-image:none]", "tw:[&_.public-booking-slot-block:hover]:text-[color:#eafff8]", "tw:[&_.public-booking-slot-block-active]:border-t-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block-active]:border-r-[color:#4ee8b1]",
    "tw:[&_.public-booking-slot-block-active]:border-b-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block-active]:border-l-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block-active]:bg-[color:rgb(20_83_76_/_.72)]", "tw:[&_.public-booking-slot-block-active]:[background-image:none]",
    "tw:[&_.public-booking-slot-block-active]:text-[color:#eafff8]", "tw:[&_.public-booking-slot-block-selected]:border-t-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block-selected]:border-r-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block-selected]:border-b-[color:#4ee8b1]",
    "tw:[&_.public-booking-slot-block-selected]:border-l-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block-selected]:bg-[color:rgb(20_83_76_/_.72)]", "tw:[&_.public-booking-slot-block-selected]:[background-image:none]", "tw:[&_.public-booking-slot-block-selected]:text-[color:#eafff8]",
    "tw:[&_.public-booking-client-summary]:border-t-[color:rgb(62_205_165_/_.4)]", "tw:[&_.public-booking-client-summary]:border-r-[color:rgb(62_205_165_/_.4)]", "tw:[&_.public-booking-client-summary]:border-b-[color:rgb(62_205_165_/_.4)]", "tw:[&_.public-booking-client-summary]:border-l-[color:rgb(62_205_165_/_.4)]",
    "tw:[&_.public-booking-client-summary]:bg-[color:rgb(13_65_59_/_.56)]", "tw:[&_.public-booking-client-summary]:[background-image:none]", "tw:[&_.public-booking-client-summary_strong]:text-[color:#72f2bf]", "tw:[&_.public-booking-total_strong]:text-[color:#72f2bf]",
    "tw:[&_.public-booking-client-summary_small]:text-[color:#b2d7cf]", "tw:[&_.public-booking-total]:border-t-[color:rgb(77_193_162_/_.3)]", "tw:[&_.public-booking-total]:border-r-[color:rgb(77_193_162_/_.3)]", "tw:[&_.public-booking-total]:border-b-[color:rgb(77_193_162_/_.3)]",
    "tw:[&_.public-booking-total]:border-l-[color:rgb(77_193_162_/_.3)]", "tw:[&_.public-booking-reserved-slots]:border-t-[color:rgb(81_173_215_/_.42)]", "tw:[&_.public-booking-reserved-slots]:border-r-[color:rgb(81_173_215_/_.42)]", "tw:[&_.public-booking-reserved-slots]:border-b-[color:rgb(81_173_215_/_.42)]",
    "tw:[&_.public-booking-reserved-slots]:border-l-[color:rgb(81_173_215_/_.42)]", "tw:[&_.public-booking-reserved-slots]:bg-[color:rgb(22_67_94_/_.45)]", "tw:[&_.public-booking-reserved-slots]:[background-image:none]", "tw:[&_.public-booking-reserved-slots_span]:text-[color:#afd9ef]",
    "tw:[&_.public-booking-empty]:border-t-[color:rgb(91_156_195_/_.35)]", "tw:[&_.public-booking-empty]:border-r-[color:rgb(91_156_195_/_.35)]", "tw:[&_.public-booking-empty]:border-b-[color:rgb(91_156_195_/_.35)]", "tw:[&_.public-booking-empty]:border-l-[color:rgb(91_156_195_/_.35)]",
    "tw:[&_.public-booking-empty]:bg-[color:rgb(14_43_67_/_.76)]", "tw:[&_.public-booking-empty]:[background-image:none]", "tw:[&_.public-booking-empty]:text-[color:#afcbe0]", "tw:[&_.public-booking-date_.button]:border-t-[color:rgb(95_168_207_/_.52)]",
    "tw:[&_.public-booking-date_.button]:border-r-[color:rgb(95_168_207_/_.52)]", "tw:[&_.public-booking-date_.button]:border-b-[color:rgb(95_168_207_/_.52)]", "tw:[&_.public-booking-date_.button]:border-l-[color:rgb(95_168_207_/_.52)]", "tw:[&_.public-booking-date_.button]:bg-[color:#146da3]",
    "tw:[&_.public-booking-date_.button]:[background-image:none]", "tw:[&_.public-booking-date_.button]:text-[color:#f2fbff]", "tw:[&_.public-booking-date_.button:hover]:bg-[color:#0d5a89]", "tw:[&_.public-booking-date_.button:hover]:[background-image:none]",
    "tw:[&_.public-booking-date_input::-webkit-calendar-picker-indicator]:[filter:invert(1)_brightness(1.7)]", "tw:[&_.public-booking-date_input::-webkit-calendar-picker-indicator]:cursor-pointer", "tw:[&_.public-booking-court-picker_>_strong]:text-[color:#b7cad9]", "tw:[&_.public-booking-court-card]:border-t-[color:rgb(89_155_194_/_.48)]",
    "tw:[&_.public-booking-court-card]:border-r-[color:rgb(89_155_194_/_.48)]", "tw:[&_.public-booking-court-card]:border-b-[color:rgb(89_155_194_/_.48)]", "tw:[&_.public-booking-court-card]:border-l-[color:rgb(89_155_194_/_.48)]", "tw:[&_.public-booking-court-card]:bg-[color:#102d49]",
    "tw:[&_.public-booking-court-card]:[background-image:none]", "tw:[&_.public-booking-court-card]:text-[color:#e5f2fb]", "tw:[&_.public-booking-court-card_small]:text-[color:#a8c4d8]", "tw:[&_.public-booking-court-card:hover]:border-t-[color:#4ee8b1]",
    "tw:[&_.public-booking-court-card:hover]:border-r-[color:#4ee8b1]", "tw:[&_.public-booking-court-card:hover]:border-b-[color:#4ee8b1]", "tw:[&_.public-booking-court-card:hover]:border-l-[color:#4ee8b1]", "tw:[&_.public-booking-court-card.is-active]:border-t-[color:#4ee8b1]",
    "tw:[&_.public-booking-court-card.is-active]:border-r-[color:#4ee8b1]", "tw:[&_.public-booking-court-card.is-active]:border-b-[color:#4ee8b1]", "tw:[&_.public-booking-court-card.is-active]:border-l-[color:#4ee8b1]", "tw:[&_.public-booking-court-card.is-active]:bg-[color:rgb(20_83_76_/_.72)]",
    "tw:[&_.public-booking-court-card.is-active]:[background-image:none]", "tw:[&_.public-booking-court-card.is-active]:text-[color:#eafff8]", "tw:[&_.public-booking-court-card.is-active_small]:text-[color:#baf5dc]",
  ].join(" "),
  "public_booking_page": [
    "public-booking-page", "tw:min-h-[100vh]", "tw:pt-[38px]", "tw:viewport-720:pt-[12px]",
    "tw:pr-[18px]", "tw:viewport-720:pr-[8px]", "tw:pb-[38px]", "tw:viewport-720:pb-[12px]",
    "tw:pl-[18px]", "tw:viewport-720:pl-[8px]", "tw:bg-[color:#061827]", "tw:[background-image:radial-gradient(circle_at_8%_0,_rgb(35_178_141_/_.17),_transparent_30%),_radial-gradient(circle_at_95%_4%,_rgb(30_139_206_/_.18),_transparent_33%)]",
    "tw:text-[color:#10253a]", "tw:[&_.public-booking-shell]:border-t-[color:rgb(74_157_181_/_.28)]", "tw:[&_.public-booking-shell]:border-r-[color:rgb(74_157_181_/_.28)]", "tw:[&_.public-booking-shell]:border-b-[color:rgb(74_157_181_/_.28)]",
    "tw:[&_.public-booking-shell]:border-l-[color:rgb(74_157_181_/_.28)]", "tw:[&_.public-booking-shell]:bg-[color:transparent]", "tw:[&_.public-booking-shell]:[background-image:linear-gradient(145deg,_#0d263b,_#091a2d)]", "tw:[&_.public-booking-shell]:[box-shadow:inset_0_1px_rgb(255_255_255_/_.04),_0_18px_42px_rgb(0_0_0_/_.22)]",
    "tw:[&_.public-booking-shell]:text-[color:#eaf5fb]", "tw:[&_.public-booking-shell_>_header]:border-t-[color:rgb(75_151_176_/_.25)]", "tw:[&_.public-booking-shell_>_header]:border-r-[color:rgb(75_151_176_/_.25)]", "tw:[&_.public-booking-shell_>_header]:border-b-[color:rgb(75_151_176_/_.25)]",
    "tw:[&_.public-booking-shell_>_header]:border-l-[color:rgb(75_151_176_/_.25)]", "tw:[&_.public-booking-shell_>_header_img]:border-t-[length:0]!", "tw:[&_.public-booking-shell_>_header_img]:[border-top-style:none]!", "tw:[&_.public-booking-shell_>_header_img]:border-t-[color:currentColor]!",
    "tw:[&_.public-booking-shell_>_header_img]:border-r-[length:0]!", "tw:[&_.public-booking-shell_>_header_img]:[border-right-style:none]!", "tw:[&_.public-booking-shell_>_header_img]:border-r-[color:currentColor]!", "tw:[&_.public-booking-shell_>_header_img]:border-b-[length:0]!",
    "tw:[&_.public-booking-shell_>_header_img]:[border-bottom-style:none]!", "tw:[&_.public-booking-shell_>_header_img]:border-b-[color:currentColor]!", "tw:[&_.public-booking-shell_>_header_img]:border-l-[length:0]!", "tw:[&_.public-booking-shell_>_header_img]:[border-left-style:none]!",
    "tw:[&_.public-booking-shell_>_header_img]:border-l-[color:currentColor]!", "tw:[&_.public-booking-shell_>_header_img]:rounded-[0]!", "tw:[&_.public-booking-shell_>_header_img]:bg-[color:transparent]!", "tw:[&_.public-booking-shell_>_header_img]:[background-image:none]!",
    "tw:[&_.public-booking-shell_>_header_img]:[box-shadow:none]!", "tw:[&_.public-booking-shell_>_header_img]:[object-fit:contain]", "tw:[&_.public-booking-shell_h1]:text-[color:#f1f9ff]", "tw:[&_.public-booking-shell_h2]:text-[color:#f1f9ff]",
    "tw:[&_.public-booking-shell_p]:text-[color:#b7cad9]", "tw:[&_.public-booking-date_label]:text-[color:#b7cad9]", "tw:[&_.public-booking-form_.field]:text-[color:#b7cad9]", "tw:[&_.public-booking-slot-blocks_strong]:text-[color:#b7cad9]",
    "tw:[&_.public-booking-date_input]:border-t-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-date_input]:border-r-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-date_input]:border-b-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-date_input]:border-l-[color:rgb(92_151_190_/_.42)]",
    "tw:[&_.public-booking-date_input]:bg-[color:#102b46]", "tw:[&_.public-booking-date_input]:[background-image:none]", "tw:[&_.public-booking-date_input]:text-[color:#edf7ff]", "tw:[&_.public-booking-form_input]:border-t-[color:rgb(92_151_190_/_.42)]",
    "tw:[&_.public-booking-form_input]:border-r-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-form_input]:border-b-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-form_input]:border-l-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-form_input]:bg-[color:#102b46]",
    "tw:[&_.public-booking-form_input]:[background-image:none]", "tw:[&_.public-booking-form_input]:text-[color:#edf7ff]", "tw:[&_.public-booking-form_select]:border-t-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-form_select]:border-r-[color:rgb(92_151_190_/_.42)]",
    "tw:[&_.public-booking-form_select]:border-b-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-form_select]:border-l-[color:rgb(92_151_190_/_.42)]", "tw:[&_.public-booking-form_select]:bg-[color:#102b46]", "tw:[&_.public-booking-form_select]:[background-image:none]",
    "tw:[&_.public-booking-form_select]:text-[color:#edf7ff]", "tw:[&_.public-booking-reserved]:border-t-[color:rgb(83_146_192_/_.3)]", "tw:[&_.public-booking-reserved]:border-r-[color:rgb(83_146_192_/_.3)]", "tw:[&_.public-booking-reserved]:border-b-[color:rgb(83_146_192_/_.3)]",
    "tw:[&_.public-booking-reserved]:border-l-[color:rgb(83_146_192_/_.3)]", "tw:[&_.public-booking-reserved]:bg-[color:rgb(19_53_82_/_.62)]", "tw:[&_.public-booking-reserved]:[background-image:none]", "tw:[&_.public-booking-reserved]:text-[color:#b9d8f0]",
    "tw:[&_.public-booking-form]:border-t-[color:rgb(62_173_192_/_.42)]", "tw:[&_.public-booking-form]:border-r-[color:rgb(62_173_192_/_.42)]", "tw:[&_.public-booking-form]:border-b-[color:rgb(62_173_192_/_.42)]", "tw:[&_.public-booking-form]:border-l-[color:rgb(62_173_192_/_.42)]",
    "tw:[&_.public-booking-form]:bg-[color:transparent]", "tw:[&_.public-booking-form]:[background-image:linear-gradient(145deg,_#0c2d42,_#0c2237)]", "tw:[&_.public-booking-slot-block]:border-t-[color:rgb(89_155_194_/_.48)]", "tw:[&_.public-booking-slot-block]:border-r-[color:rgb(89_155_194_/_.48)]",
    "tw:[&_.public-booking-slot-block]:border-b-[color:rgb(89_155_194_/_.48)]", "tw:[&_.public-booking-slot-block]:border-l-[color:rgb(89_155_194_/_.48)]", "tw:[&_.public-booking-slot-block]:bg-[color:#102d49]", "tw:[&_.public-booking-slot-block]:[background-image:none]",
    "tw:[&_.public-booking-slot-block]:text-[color:#e5f2fb]", "tw:[&_.public-booking-slot-block_small]:text-[color:#a8c4d8]", "tw:[&_.public-booking-slot-block:hover]:border-t-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block:hover]:border-r-[color:#4ee8b1]",
    "tw:[&_.public-booking-slot-block:hover]:border-b-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block:hover]:border-l-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block:hover]:bg-[color:rgb(20_83_76_/_.72)]", "tw:[&_.public-booking-slot-block:hover]:[background-image:none]",
    "tw:[&_.public-booking-slot-block:hover]:text-[color:#eafff8]", "tw:[&_.public-booking-slot-block-active]:border-t-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block-active]:border-r-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block-active]:border-b-[color:#4ee8b1]",
    "tw:[&_.public-booking-slot-block-active]:border-l-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block-active]:bg-[color:rgb(20_83_76_/_.72)]", "tw:[&_.public-booking-slot-block-active]:[background-image:none]", "tw:[&_.public-booking-slot-block-active]:text-[color:#eafff8]",
    "tw:[&_.public-booking-slot-block-selected]:border-t-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block-selected]:border-r-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block-selected]:border-b-[color:#4ee8b1]", "tw:[&_.public-booking-slot-block-selected]:border-l-[color:#4ee8b1]",
    "tw:[&_.public-booking-slot-block-selected]:bg-[color:rgb(20_83_76_/_.72)]", "tw:[&_.public-booking-slot-block-selected]:[background-image:none]", "tw:[&_.public-booking-slot-block-selected]:text-[color:#eafff8]", "tw:[&_.public-booking-client-summary]:border-t-[color:rgb(62_205_165_/_.4)]",
    "tw:[&_.public-booking-client-summary]:border-r-[color:rgb(62_205_165_/_.4)]", "tw:[&_.public-booking-client-summary]:border-b-[color:rgb(62_205_165_/_.4)]", "tw:[&_.public-booking-client-summary]:border-l-[color:rgb(62_205_165_/_.4)]", "tw:[&_.public-booking-client-summary]:bg-[color:rgb(13_65_59_/_.56)]",
    "tw:[&_.public-booking-client-summary]:[background-image:none]", "tw:[&_.public-booking-client-summary_strong]:text-[color:#72f2bf]", "tw:[&_.public-booking-total_strong]:text-[color:#72f2bf]", "tw:[&_.public-booking-client-summary_small]:text-[color:#b2d7cf]",
    "tw:[&_.public-booking-total]:border-t-[color:rgb(77_193_162_/_.3)]", "tw:[&_.public-booking-total]:border-r-[color:rgb(77_193_162_/_.3)]", "tw:[&_.public-booking-total]:border-b-[color:rgb(77_193_162_/_.3)]", "tw:[&_.public-booking-total]:border-l-[color:rgb(77_193_162_/_.3)]",
    "tw:[&_.public-booking-reserved-slots]:border-t-[color:rgb(81_173_215_/_.42)]", "tw:[&_.public-booking-reserved-slots]:border-r-[color:rgb(81_173_215_/_.42)]", "tw:[&_.public-booking-reserved-slots]:border-b-[color:rgb(81_173_215_/_.42)]", "tw:[&_.public-booking-reserved-slots]:border-l-[color:rgb(81_173_215_/_.42)]",
    "tw:[&_.public-booking-reserved-slots]:bg-[color:rgb(22_67_94_/_.45)]", "tw:[&_.public-booking-reserved-slots]:[background-image:none]", "tw:[&_.public-booking-reserved-slots_span]:text-[color:#afd9ef]", "tw:[&_.public-booking-empty]:border-t-[color:rgb(91_156_195_/_.35)]",
    "tw:[&_.public-booking-empty]:border-r-[color:rgb(91_156_195_/_.35)]", "tw:[&_.public-booking-empty]:border-b-[color:rgb(91_156_195_/_.35)]", "tw:[&_.public-booking-empty]:border-l-[color:rgb(91_156_195_/_.35)]", "tw:[&_.public-booking-empty]:bg-[color:rgb(14_43_67_/_.76)]",
    "tw:[&_.public-booking-empty]:[background-image:none]", "tw:[&_.public-booking-empty]:text-[color:#afcbe0]", "tw:[&_.public-booking-date_.button]:border-t-[color:rgb(95_168_207_/_.52)]", "tw:[&_.public-booking-date_.button]:border-r-[color:rgb(95_168_207_/_.52)]",
    "tw:[&_.public-booking-date_.button]:border-b-[color:rgb(95_168_207_/_.52)]", "tw:[&_.public-booking-date_.button]:border-l-[color:rgb(95_168_207_/_.52)]", "tw:[&_.public-booking-date_.button]:bg-[color:#146da3]", "tw:[&_.public-booking-date_.button]:[background-image:none]",
    "tw:[&_.public-booking-date_.button]:text-[color:#f2fbff]", "tw:[&_.public-booking-date_.button:hover]:bg-[color:#0d5a89]", "tw:[&_.public-booking-date_.button:hover]:[background-image:none]", "tw:[&_.public-booking-date_input::-webkit-calendar-picker-indicator]:[filter:invert(1)_brightness(1.7)]",
    "tw:[&_.public-booking-date_input::-webkit-calendar-picker-indicator]:cursor-pointer", "tw:[&_.public-booking-court-picker_>_strong]:text-[color:#b7cad9]", "tw:[&_.public-booking-court-card]:border-t-[color:rgb(89_155_194_/_.48)]", "tw:[&_.public-booking-court-card]:border-r-[color:rgb(89_155_194_/_.48)]",
    "tw:[&_.public-booking-court-card]:border-b-[color:rgb(89_155_194_/_.48)]", "tw:[&_.public-booking-court-card]:border-l-[color:rgb(89_155_194_/_.48)]", "tw:[&_.public-booking-court-card]:bg-[color:#102d49]", "tw:[&_.public-booking-court-card]:[background-image:none]",
    "tw:[&_.public-booking-court-card]:text-[color:#e5f2fb]", "tw:[&_.public-booking-court-card_small]:text-[color:#a8c4d8]", "tw:[&_.public-booking-court-card:hover]:border-t-[color:#4ee8b1]", "tw:[&_.public-booking-court-card:hover]:border-r-[color:#4ee8b1]",
    "tw:[&_.public-booking-court-card:hover]:border-b-[color:#4ee8b1]", "tw:[&_.public-booking-court-card:hover]:border-l-[color:#4ee8b1]", "tw:[&_.public-booking-court-card.is-active]:border-t-[color:#4ee8b1]", "tw:[&_.public-booking-court-card.is-active]:border-r-[color:#4ee8b1]",
    "tw:[&_.public-booking-court-card.is-active]:border-b-[color:#4ee8b1]", "tw:[&_.public-booking-court-card.is-active]:border-l-[color:#4ee8b1]", "tw:[&_.public-booking-court-card.is-active]:bg-[color:rgb(20_83_76_/_.72)]", "tw:[&_.public-booking-court-card.is-active]:[background-image:none]",
    "tw:[&_.public-booking-court-card.is-active]:text-[color:#eafff8]", "tw:[&_.public-booking-court-card.is-active_small]:text-[color:#baf5dc]",
  ].join(" "),
} as const;
