import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "client_finance_section": [
    "client-finance-section", "tw:grid", "tw:gap-y-[5px]", "tw:gap-x-[5px]",
    "tw:pt-[17px]", "tw:viewport-700:pt-[13px]", "tw:pr-[17px]", "tw:viewport-700:pr-[13px]",
    "tw:pb-[17px]", "tw:viewport-700:pb-[13px]", "tw:pl-[17px]", "tw:viewport-700:pl-[13px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(75_132_184_/_.3)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(75_132_184_/_.3)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgb(75_132_184_/_.3)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(75_132_184_/_.3)]",
    "tw:rounded-[14px]", "tw:viewport-700:rounded-[12px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(135deg,_#111f31,_#0c1828)]",
    "tw:[box-shadow:inset_0_1px_rgb(255_255_255_/_.035),_0_10px_20px_rgb(0_0_0_/_.1)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:items-center", "tw:[&_>_header]:justify-between",
    "tw:[&_>_header]:gap-y-[10px]", "tw:[&_>_header]:gap-x-[10px]", "tw:[&_>_header]:pt-[0]", "tw:[&_>_header]:pr-[0]",
    "tw:[&_>_header]:pb-[9px]", "tw:[&_>_header]:pl-[0]", "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]",
    "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]", "tw:[&_h3]:text-[color:#f1f7ff]", "tw:[&_h3]:text-[1rem]",
    "tw:viewport-700:[&_h3]:text-[.9rem]", "tw:[&_>_header_span]:pt-[3px]", "tw:[&_>_header_span]:pr-[8px]", "tw:[&_>_header_span]:pb-[3px]",
    "tw:[&_>_header_span]:pl-[8px]", "tw:[&_>_header_span]:rounded-[999px]", "tw:[&_>_header_span]:bg-[color:#eef5fb]", "tw:[&_>_header_span]:[background-image:none]",
    "tw:[&_>_header_span]:text-[color:#5b7590]", "tw:[&_>_header_span]:text-[.68rem]", "tw:[&_>_header_span]:font-[800]", "tw:[&_>_header_>_div]:flex",
    "tw:[&_>_header_>_div]:items-center", "tw:[&_>_header_>_div]:gap-y-[11px]", "tw:[&_>_header_>_div]:gap-x-[11px]", "tw:[&:nth-of-type(2)_.client-finance-section-icon]:text-[color:#37a9ff]",
    "tw:[&:nth-of-type(2)_.client-finance-section-icon]:bg-[color:rgb(5_47_83_/_.62)]", "tw:[&:nth-of-type(2)_.client-finance-section-icon]:[background-image:none]", "tw:[&_>_header_>_span]:pt-[6px]", "tw:viewport-700:[&_>_header_>_span]:pt-[5px]",
    "tw:[&_>_header_>_span]:pr-[10px]", "tw:viewport-700:[&_>_header_>_span]:pr-[7px]", "tw:[&_>_header_>_span]:pb-[6px]", "tw:viewport-700:[&_>_header_>_span]:pb-[5px]",
    "tw:[&_>_header_>_span]:pl-[10px]", "tw:viewport-700:[&_>_header_>_span]:pl-[7px]", "tw:[&_>_header_>_span]:text-[color:#63eeb3]", "tw:[&_>_header_>_span]:bg-[color:rgb(7_85_61_/_.45)]",
    "tw:[&_>_header_>_span]:[background-image:none]", "tw:[&_.client-finance-section-icon]:[font-family:inherit]", "tw:[&_.client-finance-section-icon]:text-[.78rem]", "tw:[&_.client-finance-section-icon]:font-[900]",
    "tw:[&_.client-finance-section-icon]:tracking-[-.04em]", "tw:viewport-700:[&_>_header_>_span]:text-[.59rem]",
  ].join(" "),
  "client_finance_section_icon": [
    "client-finance-section-icon", "tw:grid", "tw:w-[42px]", "tw:viewport-700:w-[35px]",
    "tw:h-[42px]", "tw:viewport-700:h-[35px]", "tw:place-items-center", "tw:rounded-[50%]",
    "tw:text-[color:#57efb5]", "tw:bg-[color:rgb(5_66_55_/_.56)]", "tw:[background-image:none]", "tw:viewport-700:[&_.client-finance-icon]:w-[22px]",
    "tw:viewport-700:[&_.client-finance-icon]:h-[22px]",
  ].join(" "),
  "client_finance_entry_public_finance_entry": [
    "client-finance-entry", "public-finance-entry", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)_auto_auto]",
    "tw:viewport-640:grid-cols-[minmax(0,_1fr)_auto]", "tw:items-center", "tw:gap-y-[14px]", "tw:viewport-640:gap-y-[8px]",
    "tw:gap-x-[14px]", "tw:viewport-640:gap-x-[8px]", "tw:pt-[11px]", "tw:pr-[0]",
    "tw:pb-[11px]", "tw:pl-[0]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(76_130_177_/_.22)]", "tw:border-r-[color:rgb(76_130_177_/_.22)]", "tw:border-b-[color:rgb(76_130_177_/_.22)]", "tw:border-l-[color:rgb(76_130_177_/_.22)]",
    "tw:[&_>_div]:grid", "tw:[&_>_div]:gap-y-[3px]", "tw:[&_>_div]:gap-x-[3px]", "tw:[&_>_div]:min-w-[0]",
    "tw:[&_strong]:[overflow-x:hidden]", "tw:[&_strong]:[overflow-y:hidden]", "tw:[&_strong]:text-[color:#edf6ff]", "tw:[&_strong]:text-[.82rem]",
    "tw:[&_strong]:text-ellipsis", "tw:[&_strong]:whitespace-nowrap", "tw:[&_small]:text-[color:#a8bece]", "tw:[&_small]:text-[.72rem]",
    "tw:[&_b]:text-[color:#edf6ff]", "tw:[&_b]:text-[.82rem]", "tw:[&_b]:whitespace-nowrap", "tw:[&_em]:min-w-[76px]",
    "tw:[&_em]:text-[color:#a8c1d1]", "tw:[&_em]:text-[.68rem]", "tw:[&_em]:not-italic", "tw:[&_em]:font-[800]",
    "tw:[&_em]:text-right", "tw:viewport-640:[&_em]:text-left", "tw:[&.is-overdue_em]:text-[color:#b04a19]", "tw:[&.is-paid_em]:text-[color:#19835c]",
    "tw:[&_.button]:min-w-[84px]", "tw:[&.is-due-soon]:[margin-inline:-7px]", "tw:[&.is-due-soon]:[padding-inline:7px]", "tw:[&.is-due-soon]:rounded-[8px]",
    "tw:[&.is-due-soon]:bg-[color:#fff8e8]", "tw:[&.is-due-soon]:[background-image:none]", "tw:[&.is-due-soon_small]:text-[color:#99610a]", "tw:[&.is-due-soon_small]:font-[800]",
    "tw:[&.is-due-overdue]:[margin-inline:-7px]", "tw:[&.is-due-overdue]:[padding-inline:7px]", "tw:[&.is-due-overdue]:rounded-[8px]", "tw:[&.is-due-overdue]:bg-[color:#fff1ed]",
    "tw:[&.is-due-overdue]:[background-image:none]", "tw:[&.is-due-overdue_strong]:text-[color:#a13e19]", "tw:[&.is-due-overdue_b]:text-[color:#a13e19]", "tw:[&.is-due-overdue_small]:text-[color:#b34a22]",
    "tw:[&.is-due-overdue_small]:font-[850]", "tw:viewport-640:[&_.button]:[grid-column:1_/_-1]", "tw:viewport-640:[&_.button]:w-[100%]", "tw:viewport-640:[&_.button]:text-center",
    "tw:viewport-640:[&_em]:[grid-column:1_/_-1]", "tw:viewport-640:[&_em]:w-[100%]", "tw:[&.public-finance-entry]:grid-cols-[auto_minmax(0,_1fr)_auto]", "tw:viewport-700:[&.public-finance-entry]:grid-cols-[auto_minmax(0,_1fr)]",
    "tw:[&.public-finance-entry]:gap-y-[11px]", "tw:[&.public-finance-entry]:gap-x-[11px]", "tw:[&.public-finance-entry.is-due-overdue]:[margin-inline:0]", "tw:[&.public-finance-entry.is-due-overdue]:border-t-[length:1px]",
    "tw:[&.public-finance-entry.is-due-overdue]:[border-top-style:solid]", "tw:[&.public-finance-entry.is-due-overdue]:border-t-[color:rgb(241_139_93_/_.38)]", "tw:[&.public-finance-entry.is-due-overdue]:border-r-[length:1px]", "tw:[&.public-finance-entry.is-due-overdue]:[border-right-style:solid]",
    "tw:[&.public-finance-entry.is-due-overdue]:border-r-[color:rgb(241_139_93_/_.38)]", "tw:[&.public-finance-entry.is-due-overdue]:border-b-[length:1px]", "tw:[&.public-finance-entry.is-due-overdue]:[border-bottom-style:solid]", "tw:[&.public-finance-entry.is-due-overdue]:border-b-[color:rgb(241_139_93_/_.38)]",
    "tw:[&.public-finance-entry.is-due-overdue]:border-l-[length:1px]", "tw:[&.public-finance-entry.is-due-overdue]:[border-left-style:solid]", "tw:[&.public-finance-entry.is-due-overdue]:border-l-[color:rgb(241_139_93_/_.38)]", "tw:[&.public-finance-entry.is-due-overdue]:rounded-[9px]",
    "tw:[&.public-finance-entry.is-due-overdue]:pt-[11px]", "tw:[&.public-finance-entry.is-due-overdue]:pr-[11px]", "tw:[&.public-finance-entry.is-due-overdue]:pb-[11px]", "tw:[&.public-finance-entry.is-due-overdue]:pl-[11px]",
    "tw:[&.public-finance-entry.is-due-overdue]:bg-[color:transparent]", "tw:[&.public-finance-entry.is-due-overdue]:[background-image:linear-gradient(135deg,_rgb(74_35_29_/_.78),_rgb(37_29_39_/_.88))]", "tw:[&.public-finance-entry.is-due-overdue_strong]:text-[color:#fff2ec]", "tw:[&.public-finance-entry.is-due-overdue_b]:text-[color:#ffbd9e]",
    "tw:[&.public-finance-entry.is-due-overdue_small]:text-[color:#ffab86]", "tw:[&.public-finance-entry.is-due-overdue_.public-finance-entry-select_span]:border-t-[color:#d78a68]", "tw:[&.public-finance-entry.is-due-overdue_.public-finance-entry-select_span]:border-r-[color:#d78a68]", "tw:[&.public-finance-entry.is-due-overdue_.public-finance-entry-select_span]:border-b-[color:#d78a68]",
    "tw:[&.public-finance-entry.is-due-overdue_.public-finance-entry-select_span]:border-l-[color:#d78a68]", "tw:[&.public-finance-entry.is-due-overdue_.public-finance-entry-select_span]:bg-[color:#271a22]", "tw:[&.public-finance-entry.is-due-overdue_.public-finance-entry-select_span]:[background-image:none]", "tw:[&.public-finance-entry.is-due-overdue_summary]:text-[color:#8ed1ff]",
    "tw:viewport-700:[&.public-finance-entry_>_b]:[grid-column:2]", "tw:[&.public-finance-entry.is-due-soon]:[margin-inline:0]", "tw:[&.public-finance-entry.is-due-soon]:pt-[11px]", "tw:[&.public-finance-entry.is-due-soon]:pr-[11px]",
    "tw:[&.public-finance-entry.is-due-soon]:pb-[11px]", "tw:[&.public-finance-entry.is-due-soon]:pl-[11px]", "tw:[&.public-finance-entry.is-due-soon]:border-t-[length:1px]", "tw:[&.public-finance-entry.is-due-soon]:[border-top-style:solid]",
    "tw:[&.public-finance-entry.is-due-soon]:border-t-[color:rgb(230_176_83_/_.42)]", "tw:[&.public-finance-entry.is-due-soon]:border-r-[length:1px]", "tw:[&.public-finance-entry.is-due-soon]:[border-right-style:solid]", "tw:[&.public-finance-entry.is-due-soon]:border-r-[color:rgb(230_176_83_/_.42)]",
    "tw:[&.public-finance-entry.is-due-soon]:border-b-[length:1px]", "tw:[&.public-finance-entry.is-due-soon]:[border-bottom-style:solid]", "tw:[&.public-finance-entry.is-due-soon]:border-b-[color:rgb(230_176_83_/_.42)]", "tw:[&.public-finance-entry.is-due-soon]:border-l-[length:1px]",
    "tw:[&.public-finance-entry.is-due-soon]:[border-left-style:solid]", "tw:[&.public-finance-entry.is-due-soon]:border-l-[color:rgb(230_176_83_/_.42)]", "tw:[&.public-finance-entry.is-due-soon]:rounded-[9px]", "tw:[&.public-finance-entry.is-due-soon]:bg-[color:transparent]",
    "tw:[&.public-finance-entry.is-due-soon]:[background-image:linear-gradient(135deg,_#352b23,_#272633)]", "tw:[&.public-finance-entry.is-due-soon_strong]:text-[color:#fff7e8]", "tw:[&.public-finance-entry.is-due-soon_b]:text-[color:#fff7e8]", "tw:[&.public-finance-entry.is-due-soon_small]:text-[color:#ffd18a]",
    "tw:[&.public-finance-entry.is-due-soon_summary]:text-[color:#8ed1ff]", "tw:[&.client-finance-comanda]:grid-cols-[minmax(0,_1fr)_auto_auto]", "tw:viewport-640:[&.client-finance-comanda]:grid-cols-[minmax(0,_1fr)_auto]", "tw:[&.client-finance-comanda]:gap-y-[12px]",
    "tw:[&.client-finance-comanda]:gap-x-[12px]", "tw:[&_details]:mt-[2px]", "tw:[&_summary]:w-[fit-content]", "tw:[&_summary]:text-[color:#68baff]",
    "tw:[&_summary]:text-[.7rem]", "tw:[&_summary]:cursor-pointer", "tw:[&_details_p]:mt-[5px]", "tw:[&_details_p]:mr-[0]",
    "tw:[&_details_p]:mb-[0]", "tw:[&_details_p]:ml-[0]", "tw:[&_details_p]:text-[color:#bdd0df]", "tw:[&_details_p]:text-[.72rem]",
    "tw:[&_details_p]:leading-[1.4]",
  ].join(" "),
  "public_finance_entry_select": [
    "public-finance-entry-select", "tw:grid", "tw:w-[20px]", "tw:h-[20px]",
    "tw:[flex:0_0_20px]", "tw:place-items-center", "tw:cursor-pointer", "tw:[&_input]:absolute",
    "tw:[&_input]:w-[1px]", "tw:[&_input]:h-[1px]", "tw:[&_input]:opacity-[0]", "tw:[&_span]:w-[16px]",
    "tw:[&_span]:h-[16px]", "tw:[&_span]:border-t-[length:1px]", "tw:[&_span]:[border-top-style:solid]", "tw:[&_span]:border-t-[color:#5b85a9]",
    "tw:[&_span]:border-r-[length:1px]", "tw:[&_span]:[border-right-style:solid]", "tw:[&_span]:border-r-[color:#5b85a9]", "tw:[&_span]:border-b-[length:1px]",
    "tw:[&_span]:[border-bottom-style:solid]", "tw:[&_span]:border-b-[color:#5b85a9]", "tw:[&_span]:border-l-[length:1px]", "tw:[&_span]:[border-left-style:solid]",
    "tw:[&_span]:border-l-[color:#5b85a9]", "tw:[&_span]:rounded-[5px]", "tw:[&_span]:bg-[color:#081728]", "tw:[&_span]:[background-image:none]",
    "tw:[&_span]:[box-shadow:inset_0_1px_rgb(255_255_255_/_.06)]", "tw:[&_input:checked_+_span]:border-t-[color:#52efb0]", "tw:[&_input:checked_+_span]:border-r-[color:#52efb0]", "tw:[&_input:checked_+_span]:border-b-[color:#52efb0]",
    "tw:[&_input:checked_+_span]:border-l-[color:#52efb0]", "tw:[&_input:checked_+_span]:bg-[color:#148a66]", "tw:[&_input:checked_+_span]:[background-image:none]", "tw:[&_input:checked_+_span]:[box-shadow:inset_0_0_0_3px_#081728]",
    "tw:[&_input:focus-visible_+_span]:[outline:2px_solid_#5daeff]", "tw:[&_input:focus-visible_+_span]:[outline-offset:2px]",
  ].join(" "),
  "client_finance_empty": [
    "client-finance-empty", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:pt-[8px]", "tw:pr-[0]", "tw:pb-[3px]",
    "tw:pl-[0]", "tw:text-[color:#a8bece]", "tw:text-[.8rem]", "tw:viewport-700:text-[.73rem]",
  ].join(" "),
  "public_finance_payment_help": [
    "public-finance-payment-help", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-[color:#a8bece]", "tw:text-[.78rem]", "tw:leading-[1.45]",
  ].join(" "),
  "public_finance_entry_list": [
    "public-finance-entry-list", "tw:grid", "tw:gap-y-[14px]", "tw:gap-x-[14px]",
  ].join(" "),
  "client_finance_section_2": [
    "client-finance-section", "client-finance-comandas", "tw:grid", "tw:gap-y-[5px]",
    "tw:gap-x-[5px]", "tw:pt-[17px]", "tw:viewport-700:pt-[13px]", "tw:pr-[17px]",
    "tw:viewport-700:pr-[13px]", "tw:pb-[17px]", "tw:viewport-700:pb-[13px]", "tw:pl-[17px]",
    "tw:viewport-700:pl-[13px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(75_132_184_/_.3)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(75_132_184_/_.3)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(75_132_184_/_.3)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgb(75_132_184_/_.3)]", "tw:rounded-[14px]", "tw:viewport-700:rounded-[12px]", "tw:bg-[color:transparent]",
    "tw:[background-image:linear-gradient(135deg,_#111f31,_#0c1828)]", "tw:[box-shadow:inset_0_1px_rgb(255_255_255_/_.035),_0_10px_20px_rgb(0_0_0_/_.1)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:items-center",
    "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[10px]", "tw:[&_>_header]:gap-x-[10px]", "tw:[&_>_header]:pt-[0]",
    "tw:[&_>_header]:pr-[0]", "tw:[&_>_header]:pb-[9px]", "tw:[&_>_header]:pl-[0]", "tw:[&_h3]:mt-[0]",
    "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]", "tw:[&_h3]:text-[color:#f1f7ff]",
    "tw:[&_h3]:text-[1rem]", "tw:viewport-700:[&_h3]:text-[.9rem]", "tw:[&_>_header_span]:pt-[3px]", "tw:[&_>_header_span]:pr-[8px]",
    "tw:[&_>_header_span]:pb-[3px]", "tw:[&_>_header_span]:pl-[8px]", "tw:[&_>_header_span]:rounded-[999px]", "tw:[&_>_header_span]:bg-[color:#eef5fb]",
    "tw:[&_>_header_span]:[background-image:none]", "tw:[&_>_header_span]:text-[color:#5b7590]", "tw:[&_>_header_span]:text-[.68rem]", "tw:[&_>_header_span]:font-[800]",
    "tw:[&_>_header_>_div]:flex", "tw:[&_>_header_>_div]:items-center", "tw:[&_>_header_>_div]:gap-y-[11px]", "tw:[&_>_header_>_div]:gap-x-[11px]",
    "tw:[&:nth-of-type(2)_.client-finance-section-icon]:text-[color:#37a9ff]", "tw:[&:nth-of-type(2)_.client-finance-section-icon]:bg-[color:rgb(5_47_83_/_.62)]", "tw:[&:nth-of-type(2)_.client-finance-section-icon]:[background-image:none]", "tw:[&_>_header_>_span]:pt-[6px]",
    "tw:viewport-700:[&_>_header_>_span]:pt-[5px]", "tw:[&_>_header_>_span]:pr-[10px]", "tw:viewport-700:[&_>_header_>_span]:pr-[7px]", "tw:[&_>_header_>_span]:pb-[6px]",
    "tw:viewport-700:[&_>_header_>_span]:pb-[5px]", "tw:[&_>_header_>_span]:pl-[10px]", "tw:viewport-700:[&_>_header_>_span]:pl-[7px]", "tw:[&_>_header_>_span]:text-[color:#63eeb3]",
    "tw:[&_>_header_>_span]:bg-[color:rgb(7_85_61_/_.45)]", "tw:[&_>_header_>_span]:[background-image:none]", "tw:[&_.client-finance-section-icon]:[font-family:inherit]", "tw:[&_.client-finance-section-icon]:text-[.78rem]",
    "tw:[&_.client-finance-section-icon]:font-[900]", "tw:[&_.client-finance-section-icon]:tracking-[-.04em]", "tw:viewport-700:[&_>_header_>_span]:text-[.59rem]",
  ].join(" "),
  "client_finance_comandas_note": [
    "client-finance-comandas-note", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[6px]",
    "tw:ml-[0]", "tw:text-[color:#a8bece]", "tw:text-[.76rem]", "tw:leading-[1.45]",
  ].join(" "),
  "client_finance_entry_client_finance_comanda": [
    "client-finance-entry", "client-finance-comanda", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)_auto_auto]",
    "tw:viewport-640:grid-cols-[minmax(0,_1fr)_auto]", "tw:items-center", "tw:gap-y-[14px]", "tw:viewport-640:gap-y-[8px]",
    "tw:gap-x-[14px]", "tw:viewport-640:gap-x-[8px]", "tw:pt-[11px]", "tw:pr-[0]",
    "tw:pb-[11px]", "tw:pl-[0]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(76_130_177_/_.22)]", "tw:border-r-[color:rgb(76_130_177_/_.22)]", "tw:border-b-[color:rgb(76_130_177_/_.22)]", "tw:border-l-[color:rgb(76_130_177_/_.22)]",
    "tw:[&_>_div]:grid", "tw:[&_>_div]:gap-y-[3px]", "tw:[&_>_div]:gap-x-[3px]", "tw:[&_>_div]:min-w-[0]",
    "tw:[&_strong]:[overflow-x:hidden]", "tw:[&_strong]:[overflow-y:hidden]", "tw:[&_strong]:text-[color:#edf6ff]", "tw:[&_strong]:text-[.82rem]",
    "tw:[&_strong]:text-ellipsis", "tw:[&_strong]:whitespace-nowrap", "tw:[&_small]:text-[color:#a8bece]", "tw:[&_small]:text-[.72rem]",
    "tw:[&_b]:text-[color:#edf6ff]", "tw:[&_b]:text-[.82rem]", "tw:[&_b]:whitespace-nowrap", "tw:[&_em]:min-w-[76px]",
    "tw:[&_em]:text-[color:#a8c1d1]", "tw:[&_em]:text-[.68rem]", "tw:[&_em]:not-italic", "tw:[&_em]:font-[800]",
    "tw:[&_em]:text-right", "tw:viewport-640:[&_em]:text-left", "tw:[&.is-overdue_em]:text-[color:#b04a19]", "tw:[&.is-paid_em]:text-[color:#19835c]",
    "tw:[&_.button]:min-w-[84px]", "tw:[&.is-due-soon]:[margin-inline:-7px]", "tw:[&.is-due-soon]:[padding-inline:7px]", "tw:[&.is-due-soon]:rounded-[8px]",
    "tw:[&.is-due-soon]:bg-[color:#fff8e8]", "tw:[&.is-due-soon]:[background-image:none]", "tw:[&.is-due-soon_small]:text-[color:#99610a]", "tw:[&.is-due-soon_small]:font-[800]",
    "tw:[&.is-due-overdue]:[margin-inline:-7px]", "tw:[&.is-due-overdue]:[padding-inline:7px]", "tw:[&.is-due-overdue]:rounded-[8px]", "tw:[&.is-due-overdue]:bg-[color:#fff1ed]",
    "tw:[&.is-due-overdue]:[background-image:none]", "tw:[&.is-due-overdue_strong]:text-[color:#a13e19]", "tw:[&.is-due-overdue_b]:text-[color:#a13e19]", "tw:[&.is-due-overdue_small]:text-[color:#b34a22]",
    "tw:[&.is-due-overdue_small]:font-[850]", "tw:viewport-640:[&_.button]:[grid-column:1_/_-1]", "tw:viewport-640:[&_.button]:w-[100%]", "tw:viewport-640:[&_.button]:text-center",
    "tw:viewport-640:[&_em]:[grid-column:1_/_-1]", "tw:viewport-640:[&_em]:w-[100%]", "tw:[&.public-finance-entry]:grid-cols-[auto_minmax(0,_1fr)_auto]", "tw:viewport-700:[&.public-finance-entry]:grid-cols-[auto_minmax(0,_1fr)]",
    "tw:[&.public-finance-entry]:gap-y-[11px]", "tw:[&.public-finance-entry]:gap-x-[11px]", "tw:[&.public-finance-entry.is-due-overdue]:[margin-inline:0]", "tw:[&.public-finance-entry.is-due-overdue]:border-t-[length:1px]",
    "tw:[&.public-finance-entry.is-due-overdue]:[border-top-style:solid]", "tw:[&.public-finance-entry.is-due-overdue]:border-t-[color:rgb(241_139_93_/_.38)]", "tw:[&.public-finance-entry.is-due-overdue]:border-r-[length:1px]", "tw:[&.public-finance-entry.is-due-overdue]:[border-right-style:solid]",
    "tw:[&.public-finance-entry.is-due-overdue]:border-r-[color:rgb(241_139_93_/_.38)]", "tw:[&.public-finance-entry.is-due-overdue]:border-b-[length:1px]", "tw:[&.public-finance-entry.is-due-overdue]:[border-bottom-style:solid]", "tw:[&.public-finance-entry.is-due-overdue]:border-b-[color:rgb(241_139_93_/_.38)]",
    "tw:[&.public-finance-entry.is-due-overdue]:border-l-[length:1px]", "tw:[&.public-finance-entry.is-due-overdue]:[border-left-style:solid]", "tw:[&.public-finance-entry.is-due-overdue]:border-l-[color:rgb(241_139_93_/_.38)]", "tw:[&.public-finance-entry.is-due-overdue]:rounded-[9px]",
    "tw:[&.public-finance-entry.is-due-overdue]:pt-[11px]", "tw:[&.public-finance-entry.is-due-overdue]:pr-[11px]", "tw:[&.public-finance-entry.is-due-overdue]:pb-[11px]", "tw:[&.public-finance-entry.is-due-overdue]:pl-[11px]",
    "tw:[&.public-finance-entry.is-due-overdue]:bg-[color:transparent]", "tw:[&.public-finance-entry.is-due-overdue]:[background-image:linear-gradient(135deg,_rgb(74_35_29_/_.78),_rgb(37_29_39_/_.88))]", "tw:[&.public-finance-entry.is-due-overdue_strong]:text-[color:#fff2ec]", "tw:[&.public-finance-entry.is-due-overdue_b]:text-[color:#ffbd9e]",
    "tw:[&.public-finance-entry.is-due-overdue_small]:text-[color:#ffab86]", "tw:[&.public-finance-entry.is-due-overdue_.public-finance-entry-select_span]:border-t-[color:#d78a68]", "tw:[&.public-finance-entry.is-due-overdue_.public-finance-entry-select_span]:border-r-[color:#d78a68]", "tw:[&.public-finance-entry.is-due-overdue_.public-finance-entry-select_span]:border-b-[color:#d78a68]",
    "tw:[&.public-finance-entry.is-due-overdue_.public-finance-entry-select_span]:border-l-[color:#d78a68]", "tw:[&.public-finance-entry.is-due-overdue_.public-finance-entry-select_span]:bg-[color:#271a22]", "tw:[&.public-finance-entry.is-due-overdue_.public-finance-entry-select_span]:[background-image:none]", "tw:[&.public-finance-entry.is-due-overdue_summary]:text-[color:#8ed1ff]",
    "tw:viewport-700:[&.public-finance-entry_>_b]:[grid-column:2]", "tw:[&.public-finance-entry.is-due-soon]:[margin-inline:0]", "tw:[&.public-finance-entry.is-due-soon]:pt-[11px]", "tw:[&.public-finance-entry.is-due-soon]:pr-[11px]",
    "tw:[&.public-finance-entry.is-due-soon]:pb-[11px]", "tw:[&.public-finance-entry.is-due-soon]:pl-[11px]", "tw:[&.public-finance-entry.is-due-soon]:border-t-[length:1px]", "tw:[&.public-finance-entry.is-due-soon]:[border-top-style:solid]",
    "tw:[&.public-finance-entry.is-due-soon]:border-t-[color:rgb(230_176_83_/_.42)]", "tw:[&.public-finance-entry.is-due-soon]:border-r-[length:1px]", "tw:[&.public-finance-entry.is-due-soon]:[border-right-style:solid]", "tw:[&.public-finance-entry.is-due-soon]:border-r-[color:rgb(230_176_83_/_.42)]",
    "tw:[&.public-finance-entry.is-due-soon]:border-b-[length:1px]", "tw:[&.public-finance-entry.is-due-soon]:[border-bottom-style:solid]", "tw:[&.public-finance-entry.is-due-soon]:border-b-[color:rgb(230_176_83_/_.42)]", "tw:[&.public-finance-entry.is-due-soon]:border-l-[length:1px]",
    "tw:[&.public-finance-entry.is-due-soon]:[border-left-style:solid]", "tw:[&.public-finance-entry.is-due-soon]:border-l-[color:rgb(230_176_83_/_.42)]", "tw:[&.public-finance-entry.is-due-soon]:rounded-[9px]", "tw:[&.public-finance-entry.is-due-soon]:bg-[color:transparent]",
    "tw:[&.public-finance-entry.is-due-soon]:[background-image:linear-gradient(135deg,_#352b23,_#272633)]", "tw:[&.public-finance-entry.is-due-soon_strong]:text-[color:#fff7e8]", "tw:[&.public-finance-entry.is-due-soon_b]:text-[color:#fff7e8]", "tw:[&.public-finance-entry.is-due-soon_small]:text-[color:#ffd18a]",
    "tw:[&.public-finance-entry.is-due-soon_summary]:text-[color:#8ed1ff]", "tw:[&.client-finance-comanda]:grid-cols-[minmax(0,_1fr)_auto_auto]", "tw:viewport-640:[&.client-finance-comanda]:grid-cols-[minmax(0,_1fr)_auto]", "tw:[&.client-finance-comanda]:gap-y-[12px]",
    "tw:[&.client-finance-comanda]:gap-x-[12px]", "tw:[&_a]:text-[color:#8ed1ff]", "tw:[&_a]:text-[.74rem]", "tw:[&_a]:font-[750]",
    "tw:[&_a]:[text-decoration:none]", "tw:[&_a]:whitespace-nowrap", "tw:[&_a:hover]:[text-decoration:underline]", "tw:viewport-640:[&_a]:[grid-column:1_/_-1]",
  ].join(" "),
  "public_finance_payment_bar": [
    "public-finance-payment-bar", "tw:sticky", "tw:bottom-[12px]", "tw:z-[2]",
    "tw:flex", "tw:items-center", "tw:viewport-700:items-stretch", "tw:gap-y-[14px]",
    "tw:viewport-700:gap-y-[8px]", "tw:gap-x-[14px]", "tw:viewport-700:gap-x-[8px]", "tw:mt-[14px]",
    "tw:pt-[12px]", "tw:pr-[14px]", "tw:pb-[12px]", "tw:pl-[14px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(73_213_163_/_.52)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(73_213_163_/_.52)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgb(73_213_163_/_.52)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(73_213_163_/_.52)]",
    "tw:rounded-[13px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(135deg,_#123d42,_#10263b)]", "tw:[box-shadow:0_14px_28px_rgb(0_0_0_/_.28)]",
    "tw:[&_>_div]:grid", "tw:[&_>_div]:gap-y-[2px]", "tw:[&_>_div]:gap-x-[2px]", "tw:[&_>_div]:mr-[auto]",
    "tw:[&_strong]:text-[color:#f3fcff]", "tw:[&_strong]:text-[.78rem]", "tw:[&_small]:text-[color:#b5d1da]", "tw:[&_small]:text-[.67rem]",
    "tw:[&_b]:text-[color:#65f5b9]", "tw:[&_b]:text-[1rem]", "tw:[&_b]:whitespace-nowrap", "tw:[&_.button]:min-w-[158px]",
    "tw:viewport-700:[&_.button]:min-w-[0]", "tw:viewport-700:flex-wrap", "tw:viewport-700:[&_>_div]:[flex:1]", "tw:viewport-700:[&_.button]:w-[100%]",
  ].join(" "),
  "button_button_primary_button_small": sharedUtilities.buttonButtonPrimaryButtonSmall,
  "public_finance_payment_error": [
    "public-finance-payment-error", "tw:mt-[10px]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-[color:#ffb6a2]", "tw:text-[.77rem]",
  ].join(" "),
} as const;
