import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "athlete_portal_content_panel_doubles_radar": [
    "athlete-portal-content-panel", "doubles-radar", "tw:w-[min(100%_-_32px,_820px)]", "tw:viewport-700:w-[calc(100%_-_22px)]",
    "tw:[margin-inline:auto]", "tw:mt-[0]", "tw:pt-[0]", "tw:pr-[0]",
    "tw:pb-[0]", "tw:pl-[0]", "tw:border-t-[length:0]", "tw:[border-top-style:none]",
    "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[15px]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:[box-shadow:none]", "tw:[&_>_header]:grid", "tw:[&_>_header]:gap-y-[4px]",
    "tw:[&_>_header]:gap-x-[4px]", "tw:[&_>_header]:pb-[17px]", "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]",
    "tw:[&_>_header]:border-b-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-t-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-r-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-l-[color:rgb(135_178_196_/_.16)]",
    "tw:[&_>_header_span]:text-[color:#57d7ae]", "tw:[&_>_header_span]:text-[.66rem]", "tw:[&_>_header_span]:font-[900]", "tw:[&_>_header_span]:tracking-[.12em]",
    "tw:[&_>_header_h2]:mt-[0]", "tw:[&_>_header_h2]:mr-[0]", "tw:[&_>_header_h2]:mb-[0]", "tw:[&_>_header_h2]:ml-[0]",
    "tw:[&_>_header_h2]:text-[color:#f2f9fc]", "tw:[&_>_header_h2]:text-[1.3rem]", "tw:grid", "tw:gap-y-[16px]",
    "tw:viewport-700:gap-y-[12px]", "tw:gap-x-[16px]", "tw:viewport-700:gap-x-[12px]", "tw:mr-[auto]",
    "tw:mb-[0]", "tw:ml-[auto]", "tw:[&_>_header_p]:mt-[0]", "tw:[&_>_header_p]:mr-[0]",
    "tw:[&_>_header_p]:mb-[0]", "tw:[&_>_header_p]:ml-[0]", "tw:[&_>_header_p]:text-[color:#617b8d]", "tw:[&_>_header_p]:text-[.84rem]",
  ].join(" "),
  "doubles_radar_hero": [
    "doubles-radar-hero", "tw:relative", "tw:min-h-[154px]", "tw:viewport-700:min-h-[155px]",
    "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:pt-[24px]", "tw:viewport-700:pt-[19px]",
    "tw:pr-[26px]", "tw:viewport-700:pr-[12px]", "tw:pb-[24px]", "tw:viewport-700:pb-[19px]",
    "tw:pl-[26px]", "tw:viewport-700:pl-[12px]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgb(72_132_177_/_.23)]", "tw:bg-[color:transparent]", "tw:[background-image:radial-gradient(circle_at_89%_30%,_rgb(90_255_125_/_.36),_transparent_8%),_radial-gradient(circle_at_80%_56%,_rgb(24_244_141_/_.17),_transparent_28%),_linear-gradient(115deg,_transparent_0%,_rgb(7_41_57_/_.22)_69%,_transparent)]", "tw:[&_>_span]:text-[color:#54e8ae]",
    "tw:[&_>_span]:text-[.67rem]", "tw:[&_>_span]:font-[900]", "tw:[&_>_span]:tracking-[.2em]", "tw:[&_h2]:max-w-[550px]",
    "tw:viewport-700:[&_h2]:max-w-[290px]", "tw:[&_h2]:mt-[7px]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[7px]",
    "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#f3f9ff]", "tw:[&_h2]:text-[clamp(1.55rem,_3vw,_2.25rem)]", "tw:viewport-700:[&_h2]:text-[1.55rem]",
    "tw:[&_h2]:tracking-[-.035em]", "tw:[&_p]:max-w-[505px]", "tw:viewport-700:[&_p]:max-w-[275px]", "tw:[&_p]:mt-[0]",
    "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#b4c7d9]",
    "tw:[&_p]:text-[.9rem]", "tw:viewport-700:[&_p]:text-[.78rem]", "tw:[&_p]:leading-[1.45]", "tw:[&_>_.doubles-radar-icon]:absolute",
    "tw:[&_>_.doubles-radar-icon]:right-[31px]", "tw:viewport-700:[&_>_.doubles-radar-icon]:right-[9px]", "tw:[&_>_.doubles-radar-icon]:bottom-[24px]", "tw:viewport-700:[&_>_.doubles-radar-icon]:bottom-[20px]",
    "tw:[&_>_.doubles-radar-icon]:w-[76px]", "tw:viewport-700:[&_>_.doubles-radar-icon]:w-[54px]", "tw:[&_>_.doubles-radar-icon]:h-[76px]", "tw:viewport-700:[&_>_.doubles-radar-icon]:h-[54px]",
    "tw:[&_>_.doubles-radar-icon]:text-[color:#84ff78]", "tw:[&_>_.doubles-radar-icon]:[filter:drop-shadow(0_0_13px_rgb(77_255_129_/_.45))]", "tw:[&_>_.doubles-radar-icon]:[stroke-width:1.2]",
  ].join(" "),
  "doubles_radar_profile": [
    "doubles-radar-profile", "tw:grid", "tw:grid-cols-[74px_minmax(0,_1fr)]", "tw:viewport-700:grid-cols-[58px_minmax(0,_1fr)]",
    "tw:gap-y-[7px]", "tw:gap-x-[14px]", "tw:pt-[18px]", "tw:pr-[18px]",
    "tw:pb-[18px]", "tw:pl-[18px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(67_223_169_/_.35)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(67_223_169_/_.35)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(67_223_169_/_.35)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(67_223_169_/_.35)]", "tw:rounded-[13px]", "tw:bg-[color:transparent]",
    "tw:[background-image:linear-gradient(145deg,_#0c2e35,_#0b1d31)]", "tw:[&_h3]:mt-[4px]", "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[2px]",
    "tw:[&_h3]:ml-[0]", "tw:[&_h3]:text-[color:#f3f8ff]", "tw:[&_h3]:text-[1.1rem]", "tw:[&_p]:mt-[0]",
    "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#a9c0ce]!",
    "tw:[&_p]:text-[.78rem]", "tw:[&_dl]:grid", "tw:[&_dl]:[grid-column:1_/_-1]", "tw:[&_dl]:grid-cols-[repeat(3,_1fr)]",
    "tw:viewport-700:[&_dl]:grid-cols-[1fr]", "tw:[&_dl]:gap-y-[8px]", "tw:[&_dl]:gap-x-[8px]", "tw:[&_dl]:mt-[9px]",
    "tw:[&_dl]:mr-[0]", "tw:[&_dl]:mb-[0]", "tw:[&_dl]:ml-[0]", "tw:[&_dl_div]:pt-[10px]",
    "tw:[&_dl_div]:pr-[10px]", "tw:[&_dl_div]:pb-[10px]", "tw:[&_dl_div]:pl-[10px]", "tw:[&_dl_div]:border-t-[length:1px]",
    "tw:[&_dl_div]:[border-top-style:solid]", "tw:[&_dl_div]:border-t-[color:rgb(75_132_177_/_.3)]", "tw:[&_dl_div]:border-r-[length:1px]", "tw:[&_dl_div]:[border-right-style:solid]",
    "tw:[&_dl_div]:border-r-[color:rgb(75_132_177_/_.3)]", "tw:[&_dl_div]:border-b-[length:1px]", "tw:[&_dl_div]:[border-bottom-style:solid]", "tw:[&_dl_div]:border-b-[color:rgb(75_132_177_/_.3)]",
    "tw:[&_dl_div]:border-l-[length:1px]", "tw:[&_dl_div]:[border-left-style:solid]", "tw:[&_dl_div]:border-l-[color:rgb(75_132_177_/_.3)]", "tw:[&_dl_div]:rounded-[8px]",
    "tw:[&_dl_div]:bg-[color:#10243a]", "tw:[&_dl_div]:[background-image:none]", "tw:[&_dt]:text-[color:#a9c0ce]!", "tw:[&_dt]:text-[.65rem]",
    "tw:[&_dt]:font-[800]", "tw:[&_dt]:uppercase", "tw:[&_dd]:mt-[4px]", "tw:[&_dd]:mr-[0]",
    "tw:[&_dd]:mb-[0]", "tw:[&_dd]:ml-[0]", "tw:[&_dd]:text-[color:#f3f8ff]", "tw:[&_dd]:text-[.8rem]",
    "tw:[&_dd]:font-[800]",
  ].join(" "),
  "doubles_radar_back": [
    "doubles-radar-back", "tw:[grid-column:1_/_-1]", "tw:text-[color:#08745f]", "tw:text-[.75rem]",
    "tw:font-[800]", "tw:[text-decoration:none]",
  ].join(" "),
  "doubles_radar_profile_avatar": [
    "doubles-radar-profile-avatar", "tw:grid", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]",
    "tw:place-items-center", "tw:rounded-[50%]", "tw:text-[color:#fff]", "tw:bg-[color:transparent]",
    "tw:[background-image:linear-gradient(145deg,_#087b63,_#0b6194)]", "tw:text-[1rem]", "tw:font-[900]", "tw:w-[70px]",
    "tw:viewport-700:w-[56px]", "tw:h-[70px]", "tw:viewport-700:h-[56px]", "tw:[grid-row:2_/_span_2]",
    "tw:[&_img]:w-[100%]", "tw:[&_img]:h-[100%]", "tw:[&_img]:[object-fit:cover]",
  ].join(" "),
  "doubles_radar_availability": [
    "doubles-radar-availability", "tw:w-[fit-content]", "tw:pt-[3px]", "tw:pr-[6px]",
    "tw:pb-[3px]", "tw:pl-[6px]", "tw:rounded-[999px]", "tw:text-[color:#79f5bd]",
    "tw:bg-[color:rgb(16_125_78_/_.23)]", "tw:[background-image:none]", "tw:text-[.58rem]", "tw:font-[900]",
    "tw:tracking-[.02em]", "tw:whitespace-nowrap", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(78_237_169_/_.25)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(78_237_169_/_.25)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(78_237_169_/_.25)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(78_237_169_/_.25)]",
  ].join(" "),
  "doubles_radar_request": [
    "doubles-radar-request", "tw:[grid-column:1_/_-1]", "tw:mt-[5px]", "tw:[&_.button]:min-h-[33px]",
  ].join(" "),
  "button_button_primary_button_small": sharedUtilities.buttonButtonPrimaryButtonSmall,
  "doubles_radar_profile_note": [
    "doubles-radar-profile-note", "tw:[grid-column:1_/_-1]", "tw:pt-[9px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#d8ebe4]", "tw:text-[color:#a9c0ce]!", "tw:text-[.72rem]!",
  ].join(" "),
  "doubles_radar_status": [
    "doubles-radar-status", "tw:flex", "tw:items-center", "tw:viewport-700:items-stretch",
    "tw:justify-between", "tw:gap-y-[16px]", "tw:viewport-700:gap-y-[12px]", "tw:gap-x-[16px]",
    "tw:viewport-700:gap-x-[12px]", "tw:pt-[15px]", "tw:viewport-700:pt-[13px]", "tw:pr-[16px]",
    "tw:viewport-700:pr-[13px]", "tw:pb-[15px]", "tw:viewport-700:pb-[13px]", "tw:pl-[16px]",
    "tw:viewport-700:pl-[13px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(56_230_163_/_.42)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(56_230_163_/_.42)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(56_230_163_/_.42)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgb(56_230_163_/_.42)]", "tw:rounded-[15px]", "tw:bg-[color:transparent]", "tw:[background-image:radial-gradient(circle_at_13%_50%,_rgb(40_233_141_/_.16),_transparent_26%),_linear-gradient(110deg,_#0b3a3b,_#0a2532)]",
    "tw:text-[color:#e9fbf4]", "tw:[box-shadow:inset_0_1px_rgb(228_255_244_/_.09),_0_12px_25px_rgb(0_0_0_/_.13)]", "tw:[&.is-off]:border-t-[color:rgb(104_135_162_/_.32)]", "tw:[&.is-off]:border-r-[color:rgb(104_135_162_/_.32)]",
    "tw:[&.is-off]:border-b-[color:rgb(104_135_162_/_.32)]", "tw:[&.is-off]:border-l-[color:rgb(104_135_162_/_.32)]", "tw:[&.is-off]:bg-[color:transparent]", "tw:[&.is-off]:[background-image:linear-gradient(110deg,_#10253b,_#0a1d31)]",
    "tw:[&_>_div]:flex", "tw:[&_>_div]:items-center", "tw:[&_>_div]:gap-y-[11px]", "tw:[&_>_div]:gap-x-[11px]",
    "tw:[&_>_div_>_span]:grid", "tw:[&_>_div_>_span]:w-[58px]", "tw:viewport-700:[&_>_div_>_span]:w-[47px]", "tw:[&_>_div_>_span]:h-[58px]",
    "tw:viewport-700:[&_>_div_>_span]:h-[47px]", "tw:[&_>_div_>_span]:place-items-center", "tw:[&_>_div_>_span]:rounded-[50%]", "tw:[&_>_div_>_span]:bg-[color:transparent]",
    "tw:[&_>_div_>_span]:[background-image:radial-gradient(circle,_rgb(6_44_39_/_.2),_rgb(5_27_37_/_.95))]", "tw:[&_>_div_>_span]:text-[1.05rem]", "tw:[&_>_div_>_span]:[box-shadow:inset_0_0_0_1px_rgb(66_255_180_/_.22),_0_0_20px_rgb(39_255_157_/_.14)]", "tw:[&_>_div_>_span]:text-[color:#43f2ab]",
    "tw:[&.is-off_>_div_>_span]:bg-[color:#dce9ee]", "tw:[&.is-off_>_div_>_span]:[background-image:none]", "tw:[&.is-off_>_div_>_span]:[filter:grayscale(1)]", "tw:[&_strong]:text-[color:#e9fff6]",
    "tw:[&_strong]:text-[1rem]", "tw:viewport-700:[&_strong]:text-[.88rem]", "tw:[&.is-off_strong]:text-[color:#426174]", "tw:[&_p]:mt-[2px]",
    "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#aec8c2]",
    "tw:[&_p]:text-[.8rem]", "tw:viewport-700:[&_p]:text-[.71rem]", "tw:[&_form]:mt-[0]", "tw:[&_form]:mr-[0]",
    "tw:[&_form]:mb-[0]", "tw:[&_form]:ml-[0]", "tw:[&_form]:[flex:0_0_auto]", "tw:viewport-700:flex-col",
    "tw:[&_>_div_>_span_.doubles-radar-icon]:w-[34px]", "tw:viewport-700:[&_>_div_>_span_.doubles-radar-icon]:w-[29px]", "tw:[&_>_div_>_span_.doubles-radar-icon]:h-[34px]", "tw:viewport-700:[&_>_div_>_span_.doubles-radar-icon]:h-[29px]",
    "tw:[&_.button]:min-h-[43px]", "tw:[&_.button]:[padding-inline:17px]", "tw:[&_.button]:border-t-[color:#236ec0]", "tw:[&_.button]:border-r-[color:#236ec0]",
    "tw:[&_.button]:border-b-[color:#236ec0]", "tw:[&_.button]:border-l-[color:#236ec0]", "tw:[&_.button]:rounded-[10px]", "tw:[&_.button]:bg-[color:transparent]",
    "tw:[&_.button]:[background-image:linear-gradient(135deg,_#165890,_#0c315f)]", "tw:viewport-700:[&_form]:w-[100%]", "tw:viewport-700:[&_.button]:w-[100%]",
  ].join(" "),
  "doubles_radar_notifications": [
    "doubles-radar-notifications", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:pt-[13px]", "tw:pr-[13px]", "tw:pb-[13px]", "tw:pl-[13px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(74_131_184_/_.32)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(74_131_184_/_.32)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgb(74_131_184_/_.32)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(74_131_184_/_.32)]",
    "tw:rounded-[10px]", "tw:bg-[color:#0c213a]", "tw:[background-image:none]", "tw:[&_>_strong]:text-[color:#d5e7f6]",
    "tw:[&_>_strong]:text-[.78rem]", "tw:[&_article]:flex", "tw:[&_article]:items-center", "tw:[&_article]:gap-y-[9px]",
    "tw:[&_article]:gap-x-[9px]", "tw:[&_article]:pt-[9px]", "tw:[&_article]:pr-[9px]", "tw:[&_article]:pb-[9px]",
    "tw:[&_article]:pl-[9px]", "tw:[&_article]:border-t-[length:1px]", "tw:[&_article]:[border-top-style:solid]", "tw:[&_article]:border-t-[color:rgb(74_131_184_/_.25)]",
    "tw:[&_article]:border-r-[length:1px]", "tw:[&_article]:[border-right-style:solid]", "tw:[&_article]:border-r-[color:rgb(74_131_184_/_.25)]", "tw:[&_article]:border-b-[length:1px]",
    "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:rgb(74_131_184_/_.25)]", "tw:[&_article]:border-l-[length:1px]", "tw:[&_article]:[border-left-style:solid]",
    "tw:[&_article]:border-l-[color:rgb(74_131_184_/_.25)]", "tw:[&_article]:rounded-[8px]", "tw:[&_article]:bg-[color:#10243d]", "tw:[&_article]:[background-image:none]",
    "tw:[&_article_>_span]:grid", "tw:[&_article_>_span]:w-[28px]", "tw:[&_article_>_span]:h-[28px]", "tw:[&_article_>_span]:place-items-center",
    "tw:[&_article_>_span]:rounded-[50%]", "tw:[&_article_>_span]:bg-[color:#092c31]", "tw:[&_article_>_span]:[background-image:none]", "tw:[&_article_>_span]:text-[color:#50f0b3]",
    "tw:[&_b]:text-[color:#d5e7f6]", "tw:[&_b]:text-[.75rem]", "tw:[&_p]:mt-[2px]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#9fb7ca]", "tw:[&_p]:text-[.72rem]",
    "tw:[&_article_>_span_.doubles-radar-icon]:w-[18px]", "tw:[&_article_>_span_.doubles-radar-icon]:h-[18px]",
  ].join(" "),
  "doubles_radar_filters": [
    "doubles-radar-filters", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))_auto]", "tw:viewport-700:grid-cols-[1fr_1fr]",
    "tw:[align-items:end]", "tw:gap-y-[11px]", "tw:viewport-700:gap-y-[8px]", "tw:gap-x-[11px]",
    "tw:viewport-700:gap-x-[8px]", "tw:pt-[17px]", "tw:viewport-700:pt-[12px]", "tw:pr-[17px]",
    "tw:viewport-700:pr-[12px]", "tw:pb-[17px]", "tw:viewport-700:pb-[12px]", "tw:pl-[17px]",
    "tw:viewport-700:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(75_132_185_/_.3)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(75_132_185_/_.3)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(75_132_185_/_.3)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgb(75_132_185_/_.3)]", "tw:rounded-[14px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(135deg,_#0c213a,_#0b192e)]",
    "tw:[&_label]:grid", "tw:[&_label]:gap-y-[5px]", "tw:[&_label]:gap-x-[5px]", "tw:[&_label]:text-[color:#9db6ca]",
    "tw:[&_label]:text-[.71rem]", "tw:[&_label]:font-[800]", "tw:[&_select]:min-h-[46px]", "tw:[&_select]:pt-[0]",
    "tw:[&_select]:pr-[9px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[9px]", "tw:[&_select]:border-t-[length:1px]",
    "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:rgb(91_134_180_/_.45)]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]",
    "tw:[&_select]:border-r-[color:rgb(91_134_180_/_.45)]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:rgb(91_134_180_/_.45)]",
    "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:rgb(91_134_180_/_.45)]", "tw:[&_select]:rounded-[10px]",
    "tw:[&_select]:text-[color:#f0f7ff]", "tw:[&_select]:bg-[color:transparent]", "tw:[&_select]:[background-image:linear-gradient(135deg,_#1a2f49,_#13243b)]", "tw:[&_select]:text-[.84rem]",
    "tw:[&_select]:font-[750]", "tw:[&_>_div]:flex", "tw:[&_>_div]:gap-y-[7px]", "tw:[&_>_div]:gap-x-[7px]",
    "tw:[&_>_div]:[align-items:end]", "tw:viewport-700:[&_>_div]:justify-start", "tw:viewport-700:[&_>_div]:[grid-column:1_/_-1]", "tw:[&_>_strong]:flex",
    "tw:[&_>_strong]:[grid-column:1_/_-1]", "tw:[&_>_strong]:items-center", "tw:[&_>_strong]:gap-y-[8px]", "tw:[&_>_strong]:gap-x-[8px]",
    "tw:[&_>_strong]:text-[color:#c6d8e9]", "tw:[&_>_strong]:text-[.76rem]", "tw:[&_>_strong]:tracking-[.12em]", "tw:[&_>_strong]:uppercase",
    "tw:[&_>_strong_.doubles-radar-icon]:w-[20px]", "tw:[&_>_strong_.doubles-radar-icon]:h-[20px]", "tw:[&_>_strong_.doubles-radar-icon]:text-[color:#82aef7]", "tw:[&_.button]:min-h-[46px]",
    "tw:[&_.button]:[padding-inline:17px]", "tw:[&_.button]:rounded-[10px]", "tw:viewport-700:[&_>_div_.button]:[flex:1]", "tw:viewport-700:[&_>_div_.button]:justify-center",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "doubles_radar_list": [
    "doubles-radar-list", "tw:grid", "tw:grid-cols-[1fr]", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]", "tw:[&_>_article]:grid", "tw:[&_>_article]:grid-cols-[60px_minmax(0,_1fr)_auto]", "tw:viewport-700:[&_>_article]:grid-cols-[50px_minmax(0,_1fr)]",
    "tw:[&_>_article]:items-center", "tw:[&_>_article]:gap-y-[10px]", "tw:viewport-700:[&_>_article]:gap-y-[9px]", "tw:[&_>_article]:gap-x-[10px]",
    "tw:viewport-700:[&_>_article]:gap-x-[9px]", "tw:[&_>_article]:min-h-[102px]", "tw:viewport-700:[&_>_article]:min-h-[0]", "tw:[&_>_article]:pt-[15px]",
    "tw:viewport-700:[&_>_article]:pt-[12px]", "tw:[&_>_article]:pr-[15px]", "tw:viewport-700:[&_>_article]:pr-[12px]", "tw:[&_>_article]:pb-[15px]",
    "tw:viewport-700:[&_>_article]:pb-[12px]", "tw:[&_>_article]:pl-[15px]", "tw:viewport-700:[&_>_article]:pl-[12px]", "tw:[&_>_article]:border-t-[length:1px]",
    "tw:[&_>_article]:[border-top-style:solid]", "tw:[&_>_article]:border-t-[color:rgb(76_131_179_/_.3)]", "tw:[&_>_article]:border-r-[length:1px]", "tw:[&_>_article]:[border-right-style:solid]",
    "tw:[&_>_article]:border-r-[color:rgb(76_131_179_/_.3)]", "tw:[&_>_article]:border-b-[length:1px]", "tw:[&_>_article]:[border-bottom-style:solid]", "tw:[&_>_article]:border-b-[color:rgb(76_131_179_/_.3)]",
    "tw:[&_>_article]:border-l-[length:1px]", "tw:[&_>_article]:[border-left-style:solid]", "tw:[&_>_article]:border-l-[color:rgb(76_131_179_/_.3)]", "tw:[&_>_article]:rounded-[14px]",
    "tw:[&_>_article]:bg-[color:transparent]", "tw:[&_>_article]:[background-image:linear-gradient(135deg,_#101e31,_#0b182a)]", "tw:[&_>_article]:[box-shadow:inset_0_1px_rgb(255_255_255_/_.035),_0_10px_20px_rgb(0_0_0_/_.1)]", "tw:[&_>_article:hover]:border-t-[color:rgb(70_236_177_/_.55)]",
    "tw:[&_>_article:hover]:border-r-[color:rgb(70_236_177_/_.55)]", "tw:[&_>_article:hover]:border-b-[color:rgb(70_236_177_/_.55)]", "tw:[&_>_article:hover]:border-l-[color:rgb(70_236_177_/_.55)]", "tw:[&_>_article:hover]:[box-shadow:inset_0_1px_rgb(255_255_255_/_.05),_0_0_18px_rgb(36_244_170_/_.1)]",
    "tw:[&_.button]:min-h-[39px]", "tw:viewport-700:[&_.button]:min-h-[33px]", "tw:[&_.button]:pt-[7px]", "tw:[&_.button]:pr-[13px]",
    "tw:[&_.button]:pb-[7px]", "tw:[&_.button]:pl-[13px]", "tw:[&_.button]:text-[.75rem]", "tw:[&_.button]:whitespace-nowrap",
    "tw:[&_.button]:border-t-[color:rgb(106_151_194_/_.36)]", "tw:[&_.button]:border-r-[color:rgb(106_151_194_/_.36)]", "tw:[&_.button]:border-b-[color:rgb(106_151_194_/_.36)]", "tw:[&_.button]:border-l-[color:rgb(106_151_194_/_.36)]",
    "tw:[&_.button]:rounded-[9px]", "tw:[&_.button]:text-[color:#dceaff]", "tw:[&_.button]:bg-[color:#10223a]", "tw:[&_.button]:[background-image:none]",
    "tw:[&_>_header]:flex", "tw:[&_>_header]:items-center", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:pt-[9px]",
    "tw:[&_>_header]:text-[color:#c5d6e5]", "tw:[&_>_header_strong]:text-[.73rem]", "tw:[&_>_header_strong]:tracking-[.13em]", "tw:[&_>_header_strong]:uppercase",
    "tw:[&_>_header_span]:text-[color:#a5b8c9]", "tw:[&_>_header_span]:text-[.75rem]", "tw:viewport-700:[&_.button]:[grid-column:2]", "tw:viewport-700:[&_.button]:w-[fit-content]",
  ].join(" "),
  "doubles_radar_avatar": [
    "doubles-radar-avatar", "tw:grid", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]",
    "tw:place-items-center", "tw:rounded-[50%]", "tw:text-[color:#fff]", "tw:bg-[color:#071827]",
    "tw:[background-image:none]", "tw:text-[.95rem]", "tw:font-[900]", "tw:w-[55px]",
    "tw:viewport-700:w-[47px]", "tw:h-[55px]", "tw:viewport-700:h-[47px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(84_242_182_/_.55)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:rgb(84_242_182_/_.55)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(84_242_182_/_.55)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(84_242_182_/_.55)]", "tw:[&_img]:w-[100%]",
    "tw:[&_img]:h-[100%]", "tw:[&_img]:[object-fit:cover]",
  ].join(" "),
  "doubles_radar_athlete_copy": [
    "doubles-radar-athlete-copy", "tw:min-w-[0]", "tw:[&_>_div]:flex", "tw:[&_>_div]:items-center",
    "tw:[&_>_div]:gap-y-[6px]", "tw:[&_>_div]:gap-x-[6px]", "tw:[&_strong]:[overflow-x:hidden]", "tw:[&_strong]:[overflow-y:hidden]",
    "tw:[&_strong]:text-[color:#f3f8ff]", "tw:[&_strong]:text-[.96rem]", "tw:viewport-700:[&_strong]:text-[.84rem]", "tw:[&_strong]:text-ellipsis",
    "tw:[&_strong]:whitespace-nowrap", "tw:[&_p]:block", "tw:[&_p]:mt-[3px]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#a8bdce]", "tw:[&_p]:text-[.76rem]",
    "tw:viewport-700:[&_p]:text-[.68rem]", "tw:[&_p]:leading-[1.25]", "tw:[&_small]:block", "tw:[&_small]:mt-[3px]",
    "tw:[&_small]:mr-[0]", "tw:[&_small]:mb-[0]", "tw:[&_small]:ml-[0]", "tw:[&_small]:text-[color:#63eaa9]",
    "tw:[&_small]:text-[.76rem]", "tw:viewport-700:[&_small]:text-[.68rem]", "tw:[&_small]:leading-[1.25]",
  ].join(" "),
  "doubles_radar_empty": [
    "doubles-radar-empty", "tw:grid", "tw:[grid-column:1_/_-1]", "tw:gap-y-[4px]",
    "tw:gap-x-[4px]", "tw:pt-[24px]", "tw:pr-[24px]", "tw:pb-[24px]",
    "tw:pl-[24px]", "tw:border-t-[length:1px]", "tw:[border-top-style:dashed]", "tw:border-t-[color:#bcd6e1]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:dashed]", "tw:border-r-[color:#bcd6e1]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:dashed]", "tw:border-b-[color:#bcd6e1]", "tw:border-l-[length:1px]", "tw:[border-left-style:dashed]",
    "tw:border-l-[color:#bcd6e1]", "tw:rounded-[10px]", "tw:text-[color:#547184]", "tw:text-center",
    "tw:[&_strong]:text-[color:#1a4966]", "tw:[&_span]:text-[.8rem]",
  ].join(" "),
  "doubles_radar_icon": [
    "doubles-radar-icon", "tw:block", "tw:[fill:none]", "tw:[stroke:currentColor]",
    "tw:[stroke-linecap:round]", "tw:[stroke-linejoin:round]", "tw:[stroke-width:1.8]",
  ].join(" "),
} as const;
