import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "public_booking_payment_page": [
    "public-booking-payment-page", "tw:grid", "tw:min-h-[100vh]", "tw:place-items-center",
    "tw:pt-[28px]", "tw:viewport-520:pt-[18px]", "tw:pr-[28px]", "tw:viewport-520:pr-[18px]",
    "tw:pb-[28px]", "tw:viewport-520:pb-[18px]", "tw:pl-[28px]", "tw:viewport-520:pl-[18px]",
    "tw:text-[color:#e8f5fb]", "tw:bg-[color:transparent]", "tw:[background-image:radial-gradient(circle_at_18%_12%,_rgb(28_158_175_/_.28),_transparent_27%),_linear-gradient(135deg,_#061522,_#082b3a)]",
  ].join(" "),
  "public_booking_payment_choice": [
    "public-booking-payment-choice", "tw:w-[min(100%,_680px)]", "tw:pt-[34px]", "tw:viewport-520:pt-[24px]",
    "tw:pr-[34px]", "tw:viewport-520:pr-[18px]", "tw:pb-[34px]", "tw:viewport-520:pb-[24px]",
    "tw:pl-[34px]", "tw:viewport-520:pl-[18px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(122_201_215_/_.3)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(122_201_215_/_.3)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(122_201_215_/_.3)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(122_201_215_/_.3)]", "tw:rounded-[18px]", "tw:bg-[color:rgb(7_29_43_/_.8)]",
    "tw:[background-image:none]", "tw:[box-shadow:0_24px_64px_rgb(0_0_0_/_.28)]", "tw:[&_header]:mb-[24px]", "tw:[&_header_span]:text-[color:#49e4b1]",
    "tw:[&_header_span]:text-[.72rem]", "tw:[&_header_span]:font-[750]", "tw:[&_header_span]:tracking-[.1em]", "tw:[&_h1]:mt-[6px]",
    "tw:[&_h1]:mr-[0]", "tw:[&_h1]:mb-[8px]", "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[color:#fff]",
    "tw:[&_h1]:text-[clamp(1.6rem,_4vw,_2.35rem)]", "tw:[&_h1]:tracking-[-.035em]", "tw:[&_header_p]:mt-[0]", "tw:[&_header_p]:mr-[0]",
    "tw:[&_header_p]:mb-[0]", "tw:[&_header_p]:ml-[0]", "tw:[&_header_p]:text-[color:#a7c0cd]", "tw:[&_header_p]:leading-[1.5]",
  ].join(" "),
  "public_booking_payment_summary": [
    "public-booking-payment-summary", "tw:[&_>_span]:text-[color:#49e4b1]", "tw:[&_>_span]:text-[.72rem]", "tw:[&_>_span]:font-[750]",
    "tw:[&_>_span]:tracking-[.1em]", "tw:grid", "tw:gap-y-[9px]", "tw:gap-x-[9px]",
    "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[16px]", "tw:ml-[0]",
    "tw:pt-[14px]", "tw:pr-[15px]", "tw:pb-[14px]", "tw:pl-[15px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(73_228_177_/_.34)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(73_228_177_/_.34)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgb(73_228_177_/_.34)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(73_228_177_/_.34)]",
    "tw:rounded-[12px]", "tw:bg-[color:rgb(14_72_73_/_.36)]", "tw:[background-image:none]", "tw:[&_>_div]:flex",
    "tw:[&_>_div]:[align-items:end]", "tw:viewport-520:[&_>_div]:[align-items:start]", "tw:[&_>_div]:justify-between", "tw:[&_>_div]:gap-y-[18px]",
    "tw:viewport-520:[&_>_div]:gap-y-[10px]", "tw:[&_>_div]:gap-x-[18px]", "tw:viewport-520:[&_>_div]:gap-x-[10px]", "tw:[&_p]:grid",
    "tw:[&_p]:gap-y-[3px]", "tw:[&_p]:gap-x-[3px]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p:last-child]:text-right", "tw:viewport-520:[&_p:last-child]:text-left",
    "tw:[&_strong]:text-[color:#f2fbfd]", "tw:[&_strong]:text-[.94rem]", "tw:[&_p:last-child_strong]:text-[color:#52e2b6]", "tw:[&_p:last-child_strong]:text-[1.12rem]",
    "tw:[&_small]:text-[color:#aec7d1]", "tw:[&_small]:text-[.76rem]", "tw:viewport-520:[&_>_div]:flex-col",
  ].join(" "),
  "public_booking_payment_options": [
    "public-booking-payment-options", "tw:grid", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
    "tw:[&_button]:grid", "tw:[&_button]:grid-cols-[minmax(0,_1fr)_24px]", "tw:[&_button]:items-center", "tw:[&_button]:gap-y-[14px]",
    "tw:[&_button]:gap-x-[14px]", "tw:[&_button]:w-[100%]", "tw:[&_button]:min-h-[70px]", "tw:[&_button]:pt-[13px]",
    "tw:[&_button]:pr-[15px]", "tw:[&_button]:pb-[13px]", "tw:[&_button]:pl-[15px]", "tw:[&_button]:border-t-[length:1px]",
    "tw:[&_button]:[border-top-style:solid]", "tw:[&_button]:border-t-[color:rgb(118_181_201_/_.3)]", "tw:[&_button]:border-r-[length:1px]", "tw:[&_button]:[border-right-style:solid]",
    "tw:[&_button]:border-r-[color:rgb(118_181_201_/_.3)]", "tw:[&_button]:border-b-[length:1px]", "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:rgb(118_181_201_/_.3)]",
    "tw:[&_button]:border-l-[length:1px]", "tw:[&_button]:[border-left-style:solid]", "tw:[&_button]:border-l-[color:rgb(118_181_201_/_.3)]", "tw:[&_button]:rounded-[12px]",
    "tw:[&_button]:bg-[color:rgb(17_54_70_/_.72)]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:#edf8fc]", "tw:[&_button]:text-left",
    "tw:[&_button:hover:not(:disabled)]:border-t-[color:#43dcb0]", "tw:[&_button:hover:not(:disabled)]:border-r-[color:#43dcb0]", "tw:[&_button:hover:not(:disabled)]:border-b-[color:#43dcb0]", "tw:[&_button:hover:not(:disabled)]:border-l-[color:#43dcb0]",
    "tw:[&_button:hover:not(:disabled)]:bg-[color:rgb(23_82_94_/_.82)]", "tw:[&_button:hover:not(:disabled)]:[background-image:none]", "tw:[&_button:hover:not(:disabled)]:[transform:translateY(-1px)]", "tw:[&_button:disabled]:opacity-[.62]",
    "tw:[&_button:disabled]:cursor-wait", "tw:[&_span]:grid", "tw:[&_span]:gap-y-[3px]", "tw:[&_span]:gap-x-[3px]",
    "tw:[&_span]:min-w-[0]", "tw:[&_strong]:text-[.96rem]", "tw:[&_small]:text-[color:#afc5d0]", "tw:[&_small]:text-[.76rem]",
    "tw:[&_svg]:w-[20px]", "tw:[&_svg]:h-[20px]", "tw:[&_svg]:[fill:none]", "tw:[&_svg]:[stroke:#91bbcb]",
    "tw:[&_svg]:[stroke-width:1.9]", "tw:[&_svg]:[stroke-linecap:round]", "tw:[&_svg]:[stroke-linejoin:round]",
  ].join(" "),
  "public_booking_payment_note": [
    "public-booking-payment-note", "tw:mt-[19px]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-[color:#a7c0cd]", "tw:leading-[1.5]", "tw:text-[.8rem]",
  ].join(" "),
  "public_booking_message": sharedUtilities.publicBookingMessage,
} as const;
