import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "athlete_portal_content_panel_public_player_profile": [
    "athlete-portal-content-panel", "public-player-profile", "tw:w-[min(calc(100%_-_32px),_1060px)]", "tw:viewport-700:w-[calc(100%_-_28px)]",
    "tw:[margin-inline:auto]", "tw:mt-[22px]", "tw:viewport-700:mt-[16px]", "tw:pt-[26px]",
    "tw:viewport-700:pt-[16px]", "tw:pr-[26px]", "tw:viewport-700:pr-[16px]", "tw:pb-[26px]",
    "tw:viewport-700:pb-[16px]", "tw:pl-[26px]", "tw:viewport-700:pl-[16px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(120_162_185_/_.2)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:rgb(120_162_185_/_.2)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(120_162_185_/_.2)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(120_162_185_/_.2)]", "tw:rounded-[15px]",
    "tw:bg-[color:#0d1b28]", "tw:[background-image:none]", "tw:[box-shadow:0_18px_42px_rgb(0_0_0_/_.2)]", "tw:[&_>_header]:grid",
    "tw:[&_>_header]:gap-y-[4px]", "tw:[&_>_header]:gap-x-[4px]", "tw:[&_>_header]:pb-[17px]", "tw:[&_>_header]:border-b-[length:1px]",
    "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-t-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-r-[color:rgb(135_178_196_/_.16)]",
    "tw:[&_>_header]:border-l-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header_span]:text-[color:#57d7ae]", "tw:[&_>_header_span]:text-[.66rem]", "tw:[&_>_header_span]:font-[900]",
    "tw:[&_>_header_span]:tracking-[.12em]", "tw:[&_>_header_h2]:mt-[0]", "tw:[&_>_header_h2]:mr-[0]", "tw:[&_>_header_h2]:mb-[0]",
    "tw:[&_>_header_h2]:ml-[0]", "tw:[&_>_header_h2]:text-[color:#f2f9fc]", "tw:[&_>_header_h2]:text-[1.3rem]", "tw:[&_.grid-form_>_.field_>_label]:text-[color:#eaf5fb]",
    "tw:[&_.public-player-padel-profile]:text-[color:#eaf5fb]", "tw:[&_.public-player-padel-profile]:border-t-[color:rgb(65_211_162_/_.34)]", "tw:[&_.public-player-padel-profile]:border-r-[color:rgb(65_211_162_/_.34)]", "tw:[&_.public-player-padel-profile]:border-b-[color:rgb(65_211_162_/_.34)]",
    "tw:[&_.public-player-padel-profile]:border-l-[color:rgb(65_211_162_/_.34)]", "tw:[&_.public-player-padel-profile]:bg-[color:transparent]", "tw:[&_.public-player-padel-profile]:[background-image:linear-gradient(135deg,_#0d2b35,_#10243a)]", "tw:[&_.public-player-padel-profile_legend]:text-[color:#eaf5fb]",
    "tw:[&_.grid-form_input]:border-t-[color:rgb(101_154_194_/_.42)]", "tw:[&_.grid-form_input]:border-r-[color:rgb(101_154_194_/_.42)]", "tw:[&_.grid-form_input]:border-b-[color:rgb(101_154_194_/_.42)]", "tw:[&_.grid-form_input]:border-l-[color:rgb(101_154_194_/_.42)]",
    "tw:[&_.grid-form_input]:text-[color:#edf7ff]", "tw:[&_.grid-form_input]:bg-[color:#102740]", "tw:[&_.grid-form_input]:[background-image:none]", "tw:[&_.grid-form_select]:border-t-[color:rgb(101_154_194_/_.42)]",
    "tw:[&_.grid-form_select]:border-r-[color:rgb(101_154_194_/_.42)]", "tw:[&_.grid-form_select]:border-b-[color:rgb(101_154_194_/_.42)]", "tw:[&_.grid-form_select]:border-l-[color:rgb(101_154_194_/_.42)]", "tw:[&_.grid-form_select]:text-[color:#edf7ff]",
    "tw:[&_.grid-form_select]:bg-[color:#102740]", "tw:[&_.grid-form_select]:[background-image:none]", "tw:[&_.grid-form_textarea]:border-t-[color:rgb(101_154_194_/_.42)]", "tw:[&_.grid-form_textarea]:border-r-[color:rgb(101_154_194_/_.42)]",
    "tw:[&_.grid-form_textarea]:border-b-[color:rgb(101_154_194_/_.42)]", "tw:[&_.grid-form_textarea]:border-l-[color:rgb(101_154_194_/_.42)]", "tw:[&_.grid-form_textarea]:text-[color:#edf7ff]", "tw:[&_.grid-form_textarea]:bg-[color:#102740]",
    "tw:[&_.grid-form_textarea]:[background-image:none]", "tw:[&_.grid-form_input::placeholder]:text-[color:#98b0c1]", "tw:[&_.grid-form_textarea::placeholder]:text-[color:#98b0c1]", "tw:[&_.public-player-padel-profile_p]:text-[color:#a9c5cf]",
    "tw:[&_.public-player-padel-side]:text-[color:#dff5ef]", "tw:[&_.public-player-padel-side]:font-[800]", "tw:[&_.public-player-padel-side_select]:text-[color:#f4fbff]", "tw:[&_.public-player-padel-categories_label]:border-t-[color:rgb(91_173_183_/_.35)]",
    "tw:[&_.public-player-padel-categories_label]:border-r-[color:rgb(91_173_183_/_.35)]", "tw:[&_.public-player-padel-categories_label]:border-b-[color:rgb(91_173_183_/_.35)]", "tw:[&_.public-player-padel-categories_label]:border-l-[color:rgb(91_173_183_/_.35)]", "tw:[&_.public-player-padel-categories_label]:text-[color:#d7eef0]",
    "tw:[&_.public-player-padel-categories_label]:bg-[color:rgb(9_31_46_/_.54)]", "tw:[&_.public-player-padel-categories_label]:[background-image:none]", "tw:[&_.public-player-padel-categories_input:checked_+_span]:text-[color:#68f0bd]", "tw:[&_.public-player-padel-categories_label:has(input:checked)]:border-t-[color:#44dba7]",
    "tw:[&_.public-player-padel-categories_label:has(input:checked)]:border-r-[color:#44dba7]", "tw:[&_.public-player-padel-categories_label:has(input:checked)]:border-b-[color:#44dba7]", "tw:[&_.public-player-padel-categories_label:has(input:checked)]:border-l-[color:#44dba7]", "tw:[&_.public-player-padel-categories_label:has(input:checked)]:bg-[color:rgb(22_108_86_/_.28)]",
    "tw:[&_.public-player-padel-categories_label:has(input:checked)]:[background-image:none]",
  ].join(" "),
  "grid_form": sharedUtilities.gridForm,
  "field_form_full": sharedUtilities.fieldFormFull,
  "field": sharedUtilities.field,
  "field_form_full_public_player_bio": [
    "field", "form-full", "public-player-bio", "tw:grid",
    "tw:gap-y-[5px]", "tw:gap-x-[5px]", "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]",
    "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]",
    "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[14px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]",
    "tw:[&_input]:border-t-[color:var(--line)]", "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]",
    "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]",
    "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]",
    "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:var(--text)]", "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]",
    "tw:[&_select]:min-h-[44px]", "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]",
    "tw:[&_select]:pl-[14px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]",
    "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]",
    "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]",
    "tw:[&_select]:border-l-[color:var(--line)]", "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]",
    "tw:[&_select]:text-[color:var(--text)]", "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]",
    "tw:[&_input:focus]:[transform:translateY(-1px)]", "tw:[&_select:focus]:[outline:none]", "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]",
    "tw:[&_input[type=file]]:pt-[10px]", "tw:[&_input[type=file]]:pr-[14px]", "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]",
    "tw:[&_input[type=checkbox]]:w-[auto]", "tw:[&_input[type=checkbox]]:min-h-[auto]", "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]",
    "tw:[&_input[type=checkbox]]:pb-[0]", "tw:[&_input[type=checkbox]]:pl-[0]", "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]",
    "tw:[&_input[type=radio]]:pt-[0]", "tw:[&_input[type=radio]]:pr-[0]", "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]",
    "tw:[grid-column:1_/_-1]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[6px]", "tw:[&_label]:gap-x-[6px]",
    "tw:[&_textarea]:w-[100%]", "tw:[&_textarea]:min-h-[118px]", "tw:[&_textarea]:[resize:vertical]", "tw:[&_textarea]:leading-[1.45]",
    "tw:[&_small]:text-[color:#9fb8c7]", "tw:[&_small]:text-[.72rem]", "tw:[&_small]:leading-[1.35]",
  ].join(" "),
  "public_player_padel_profile_form_full": [
    "public-player-padel-profile", "form-full", "tw:grid", "tw:gap-y-[9px]",
    "tw:gap-x-[9px]", "tw:mt-[4px]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]",
    "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#cfe4da]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#cfe4da]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#cfe4da]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#cfe4da]", "tw:rounded-[10px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(135deg,_#f0fbf5,_#fbfffd)]",
    "tw:[&_legend]:pt-[0]", "tw:[&_legend]:pr-[5px]", "tw:[&_legend]:pb-[0]", "tw:[&_legend]:pl-[5px]",
    "tw:[&_legend]:text-[color:#146342]", "tw:[&_legend]:text-[.82rem]", "tw:[&_legend]:font-[850]", "tw:[&_>_p]:mt-[0]",
    "tw:[&_>_p]:mr-[0]", "tw:[&_>_p]:mb-[0]", "tw:[&_>_p]:ml-[0]", "tw:[&_>_p]:text-[color:#5c7769]",
    "tw:[&_>_p]:text-[.74rem]", "tw:[&_>_p]:leading-[1.4]", "tw:[&_>_div]:grid", "tw:[&_>_div]:grid-cols-[minmax(0,_1fr)_minmax(190px,_.7fr)]",
    "tw:viewport-620:[&_>_div]:grid-cols-[1fr]", "tw:[&_>_div]:gap-y-[10px]", "tw:[&_>_div]:gap-x-[10px]", "tw:[&_label]:grid",
    "tw:[&_label]:gap-y-[5px]", "tw:[&_label]:gap-x-[5px]", "tw:[&_label]:text-[color:#315946]", "tw:[&_label]:text-[.74rem]",
    "tw:[&_label]:font-[750]", "tw:[&_input]:w-[100%]", "tw:[&_select]:w-[100%]", "tw:[&_.public-player-padel-categories]:grid-cols-[repeat(auto-fit,_minmax(125px,_1fr))]",
    "tw:[&_.public-player-padel-categories]:gap-y-[7px]", "tw:[&_.public-player-padel-categories]:gap-x-[7px]", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  "public_player_padel_side": [
    "public-player-padel-side", "tw:w-[min(100%,_260px)]",
  ].join(" "),
  "public_player_padel_categories": [
    "public-player-padel-categories", "tw:[&_label]:flex!", "tw:[&_label]:items-center", "tw:[&_label]:gap-y-[7px]",
    "tw:[&_label]:gap-x-[7px]", "tw:[&_label]:min-h-[32px]", "tw:[&_label]:pt-[7px]", "tw:[&_label]:pr-[8px]",
    "tw:[&_label]:pb-[7px]", "tw:[&_label]:pl-[8px]", "tw:[&_label]:border-t-[length:1px]", "tw:[&_label]:[border-top-style:solid]",
    "tw:[&_label]:border-t-[color:#cde5da]", "tw:[&_label]:border-r-[length:1px]", "tw:[&_label]:[border-right-style:solid]", "tw:[&_label]:border-r-[color:#cde5da]",
    "tw:[&_label]:border-b-[length:1px]", "tw:[&_label]:[border-bottom-style:solid]", "tw:[&_label]:border-b-[color:#cde5da]", "tw:[&_label]:border-l-[length:1px]",
    "tw:[&_label]:[border-left-style:solid]", "tw:[&_label]:border-l-[color:#cde5da]", "tw:[&_label]:rounded-[7px]", "tw:[&_label]:bg-[color:#fff]",
    "tw:[&_label]:[background-image:none]", "tw:[&_label]:cursor-pointer", "tw:[&_input]:w-auto!", "tw:[&_input]:shrink-0", "tw:[&_input]:[accent-color:#087b63]",
    "tw:[&_span]:leading-[1.2]",
  ].join(" "),
  "field_field_submit": sharedUtilities.fieldFieldSubmit,
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "form_error_form_full": sharedUtilities.formErrorFormFull,
  "form_success_form_full": sharedUtilities.formSuccessFormFull,
} as const;
