import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "public_booking_empty": [
    "public-booking-empty", "tw:pt-[18px]", "tw:pr-[18px]", "tw:pb-[18px]",
    "tw:pl-[18px]", "tw:border-t-[length:1px]", "tw:[border-top-style:dashed]", "tw:border-t-[color:#b8cbe0]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:dashed]", "tw:border-r-[color:#b8cbe0]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:dashed]", "tw:border-b-[color:#b8cbe0]", "tw:border-l-[length:1px]", "tw:[border-left-style:dashed]",
    "tw:border-l-[color:#b8cbe0]", "tw:rounded-[10px]", "tw:bg-[color:#f8fbfe]", "tw:[background-image:none]",
  ].join(" "),
  "public_booking_form_public_booking_form_list": [
    "public-booking-form", "public-booking-form-list", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]",
    "tw:viewport-680:grid-cols-[1fr]", "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:pt-[17px]",
    "tw:pr-[17px]", "tw:pb-[17px]", "tw:pl-[17px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#b9d8e7]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#b9d8e7]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#b9d8e7]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#b9d8e7]", "tw:rounded-[12px]",
    "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(140deg,_#edf8fc,_#f8fffc)]", "tw:[&_.field]:grid", "tw:[&_.field]:gap-y-[5px]",
    "tw:[&_.field]:gap-x-[5px]", "tw:[&_.field]:text-[color:#43536b]", "tw:[&_.field]:text-[.74rem]", "tw:[&_.field]:font-[750]",
    "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[38px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[10px]",
    "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[10px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]",
    "tw:[&_input]:border-t-[color:#cbd9e8]", "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#cbd9e8]",
    "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:#cbd9e8]", "tw:[&_input]:border-l-[length:1px]",
    "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#cbd9e8]", "tw:[&_input]:rounded-[var(--radius-control)]", "tw:[&_input]:bg-[color:#fff]",
    "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:#172033]", "tw:[&_input]:[font:inherit]", "tw:[&_select]:w-[100%]",
    "tw:[&_select]:min-h-[38px]", "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[10px]", "tw:[&_select]:pb-[0]",
    "tw:[&_select]:pl-[10px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:#cbd9e8]",
    "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#cbd9e8]", "tw:[&_select]:border-b-[length:1px]",
    "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:#cbd9e8]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]",
    "tw:[&_select]:border-l-[color:#cbd9e8]", "tw:[&_select]:rounded-[var(--radius-control)]", "tw:[&_select]:bg-[color:#fff]", "tw:[&_select]:[background-image:none]",
    "tw:[&_select]:text-[color:#172033]", "tw:[&_select]:[font:inherit]", "tw:[&_>_.button]:[align-self:end]", "tw:[&_>_.button]:[justify-self:start]",
    "tw:[&_.button-primary]:border-t-[color:#08775f]", "tw:[&_.button-primary]:border-r-[color:#08775f]", "tw:[&_.button-primary]:border-b-[color:#08775f]", "tw:[&_.button-primary]:border-l-[color:#08775f]",
    "tw:[&_.button-primary]:bg-[color:#078565]", "tw:[&_.button-primary]:[background-image:none]", "tw:[&_.button-primary]:[box-shadow:0_4px_10px_rgb(8_119_95_/_.2)]", "tw:viewport-720:[&_>_.button]:w-[100%]",
    "tw:viewport-720:[&_>_.button]:justify-center",
  ].join(" "),
  "public_booking_form": [
    "public-booking-form", "tw:grid", "tw:grid-cols-[repeat(3,_minmax(0,_1fr))]", "tw:viewport-680:grid-cols-[1fr]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:pt-[17px]", "tw:pr-[17px]",
    "tw:pb-[17px]", "tw:pl-[17px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#b9d8e7]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#b9d8e7]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#b9d8e7]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#b9d8e7]", "tw:rounded-[12px]", "tw:bg-[color:transparent]",
    "tw:[background-image:linear-gradient(140deg,_#edf8fc,_#f8fffc)]", "tw:[&_.field]:grid", "tw:[&_.field]:gap-y-[5px]", "tw:[&_.field]:gap-x-[5px]",
    "tw:[&_.field]:text-[color:#43536b]", "tw:[&_.field]:text-[.74rem]", "tw:[&_.field]:font-[750]", "tw:[&_input]:w-[100%]",
    "tw:[&_input]:min-h-[38px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[10px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[10px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#cbd9e8]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#cbd9e8]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:#cbd9e8]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:#cbd9e8]", "tw:[&_input]:rounded-[var(--radius-control)]", "tw:[&_input]:bg-[color:#fff]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:text-[color:#172033]", "tw:[&_input]:[font:inherit]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[38px]",
    "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[10px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[10px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:#cbd9e8]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#cbd9e8]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:#cbd9e8]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#cbd9e8]",
    "tw:[&_select]:rounded-[var(--radius-control)]", "tw:[&_select]:bg-[color:#fff]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:#172033]",
    "tw:[&_select]:[font:inherit]", "tw:[&_>_.button]:[align-self:end]", "tw:[&_>_.button]:[justify-self:start]", "tw:[&_.button-primary]:border-t-[color:#08775f]",
    "tw:[&_.button-primary]:border-r-[color:#08775f]", "tw:[&_.button-primary]:border-b-[color:#08775f]", "tw:[&_.button-primary]:border-l-[color:#08775f]", "tw:[&_.button-primary]:bg-[color:#078565]",
    "tw:[&_.button-primary]:[background-image:none]", "tw:[&_.button-primary]:[box-shadow:0_4px_10px_rgb(8_119_95_/_.2)]", "tw:viewport-720:[&_>_.button]:w-[100%]", "tw:viewport-720:[&_>_.button]:justify-center",
  ].join(" "),
  "public_booking_court_picker": [
    "public-booking-court-picker", "tw:grid", "tw:[grid-column:1_/_-1]", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:[&_>_strong]:text-[color:#43536b]", "tw:[&_>_strong]:text-[.74rem]", "tw:[&_>_div]:grid",
    "tw:[&_>_div]:grid-cols-[repeat(auto-fit,_minmax(145px,_1fr))]", "tw:viewport-520:[&_>_div]:grid-cols-[1fr]", "tw:[&_>_div]:gap-y-[8px]", "tw:[&_>_div]:gap-x-[8px]",
    "tw:[&_>_div]:max-w-[580px]", "tw:viewport-520:[&_>_div]:max-w-[none]",
  ].join(" "),
  "public_booking_court_card": [
    "public-booking-court-card", "tw:grid", "tw:grid-cols-[8px_minmax(0,_1fr)]", "tw:gap-y-[2px]",
    "tw:gap-x-[8px]", "tw:min-h-[57px]", "tw:pt-[8px]", "tw:pr-[10px]",
    "tw:pb-[8px]", "tw:pl-[10px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#9dcde2]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#9dcde2]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#9dcde2]", "tw:border-l-[length:5px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#9dcde2]", "tw:rounded-[9px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:text-[color:#26364d]", "tw:[font:inherit]", "tw:text-left",
    "tw:cursor-pointer", "tw:[&_i]:w-[8px]", "tw:[&_i]:h-[8px]", "tw:[&_i]:[align-self:center]",
    "tw:[&_i]:rounded-[999px]", "tw:[&_span]:min-w-[0]", "tw:[&_span]:[overflow-x:hidden]", "tw:[&_span]:[overflow-y:hidden]",
    "tw:[&_span]:text-[.8rem]", "tw:[&_span]:font-[750]", "tw:[&_span]:text-ellipsis", "tw:[&_span]:whitespace-nowrap",
    "tw:[&_small]:[grid-column:2]", "tw:[&_small]:text-[color:#63748b]", "tw:[&_small]:text-[.67rem]", "tw:hover:border-t-[color:#4ecda4]",
    "tw:hover:border-r-[color:#4ecda4]", "tw:hover:border-b-[color:#4ecda4]", "tw:hover:border-l-[color:#4ecda4]", "tw:[&.is-active]:border-t-[color:#1aa87d]",
    "tw:[&.is-active]:border-r-[color:#1aa87d]", "tw:[&.is-active]:border-b-[color:#1aa87d]", "tw:[&.is-active]:border-l-[color:#1aa87d]", "tw:[&.is-active]:bg-[color:#0a725d]",
    "tw:[&.is-active]:[background-image:none]", "tw:[&.is-active]:text-[color:#fff]", "tw:[&.is-active]:[box-shadow:0_4px_10px_rgb(8_119_95_/_.2)]", "tw:[&.is-active_small]:text-[color:rgb(232_255_246_/_.78)]",
  ].join(" "),
  "field": sharedUtilities.field,
  "public_booking_slot_blocks": [
    "public-booking-slot-blocks", "tw:[grid-column:1_/_-1]", "tw:grid", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:[&_strong]:text-[color:#43536b]", "tw:[&_strong]:text-[.74rem]", "tw:[&_>_div]:flex",
    "tw:viewport-720:[&_>_div]:grid", "tw:[&_>_div]:flex-wrap", "tw:[&_>_div]:gap-y-[7px]", "tw:[&_>_div]:gap-x-[7px]",
    "tw:viewport-720:[&_>_div]:grid-cols-[repeat(2,_minmax(0,_1fr))]",
  ].join(" "),
  "public_booking_slot_block": [
    "public-booking-slot-block", "tw:grid", "tw:gap-y-[2px]", "tw:gap-x-[2px]",
    "tw:min-w-[78px]", "tw:viewport-720:min-w-[0]", "tw:pt-[8px]", "tw:pr-[9px]",
    "tw:pb-[8px]", "tw:pl-[9px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#9dcde2]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#9dcde2]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#9dcde2]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#9dcde2]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:text-[color:#26364d]", "tw:text-left", "tw:cursor-pointer",
    "tw:[&_b]:text-[.78rem]", "tw:[&_small]:text-[color:#63748b]", "tw:[&_small]:text-[.68rem]", "tw:hover:border-t-[color:#08775f]",
    "tw:hover:border-r-[color:#08775f]", "tw:hover:border-b-[color:#08775f]", "tw:hover:border-l-[color:#08775f]", "tw:hover:bg-[color:#dff7ea]",
    "tw:hover:[background-image:none]", "tw:hover:text-[color:#075d48]", "tw:hover:[box-shadow:0_3px_8px_rgb(8_119_95_/_.13)]",
  ].join(" "),
  "public_booking_slot_block_selected": [
    "public-booking-slot-block-selected", "tw:border-t-[color:#1d9074]", "tw:border-r-[color:#1d9074]", "tw:border-b-[color:#1d9074]",
    "tw:border-l-[color:#1d9074]", "tw:bg-[color:#ecfbf3]", "tw:[background-image:none]", "tw:text-[color:#075d48]",
    "tw:[box-shadow:inset_0_0_0_1px_rgb(8_119_95_/_.15)]",
  ].join(" "),
  "public_booking_slot_block_active": [
    "public-booking-slot-block-active", "tw:border-t-[color:#08775f]", "tw:border-r-[color:#08775f]", "tw:border-b-[color:#08775f]",
    "tw:border-l-[color:#08775f]", "tw:bg-[color:#dff7ea]", "tw:[background-image:none]", "tw:text-[color:#075d48]",
    "tw:[box-shadow:0_3px_8px_rgb(8_119_95_/_.13)]",
  ].join(" "),
  "public_booking_slot_block_public_booking_slot_block_conflict": [
    "public-booking-slot-block", "public-booking-slot-block-conflict", "tw:grid", "tw:gap-y-[2px]",
    "tw:gap-x-[2px]", "tw:min-w-[78px]", "tw:viewport-720:min-w-[0]", "tw:pt-[8px]",
    "tw:pr-[9px]", "tw:pb-[8px]", "tw:pl-[9px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#e2a1a1]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#e2a1a1]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e2a1a1]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#e2a1a1]", "tw:rounded-[var(--radius-control)]",
    "tw:bg-[color:#fff0f0]", "tw:[background-image:none]", "tw:text-[color:#a33333]", "tw:text-left",
    "tw:cursor-not-allowed", "tw:[&_b]:text-[.78rem]", "tw:[&_small]:text-[color:#63748b]", "tw:[&_small]:text-[.68rem]",
    "tw:hover:border-t-[color:#08775f]", "tw:hover:border-r-[color:#08775f]", "tw:hover:border-b-[color:#08775f]", "tw:hover:border-l-[color:#08775f]",
    "tw:hover:bg-[color:#dff7ea]", "tw:hover:[background-image:none]", "tw:hover:text-[color:#075d48]", "tw:hover:[box-shadow:0_3px_8px_rgb(8_119_95_/_.13)]",
  ].join(" "),
  "field_public_booking_duration_field": [
    "field", "public-booking-duration-field", "tw:grid", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]", "tw:[&_input]:w-[100%]",
    "tw:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[14px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:text-[color:var(--text)]", "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[44px]",
    "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[14px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:var(--line)]",
    "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:var(--text)]",
    "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_input:focus]:[transform:translateY(-1px)]",
    "tw:[&_select:focus]:[outline:none]", "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]", "tw:[&_input[type=file]]:pt-[10px]",
    "tw:[&_input[type=file]]:pr-[14px]", "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]", "tw:[&_input[type=checkbox]]:w-[auto]",
    "tw:[&_input[type=checkbox]]:min-h-[auto]", "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]", "tw:[&_input[type=checkbox]]:pb-[0]",
    "tw:[&_input[type=checkbox]]:pl-[0]", "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]", "tw:[&_input[type=radio]]:pt-[0]",
    "tw:[&_input[type=radio]]:pr-[0]", "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]", "tw:[align-content:start]",
    "tw:[align-self:start]",
  ].join(" "),
  "public_booking_conflict": [
    "public-booking-conflict", "tw:[grid-column:1_/_-1]", "tw:mt-[0]", "tw:mr-[0]",
    "tw:mb-[0]", "tw:ml-[0]", "tw:text-[color:#ad3030]", "tw:text-[.78rem]",
    "tw:font-[700]",
  ].join(" "),
  "public_booking_client_summary": [
    "public-booking-client-summary", "tw:flex", "tw:justify-between", "tw:items-center",
    "tw:viewport-680:items-stretch", "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:pt-[11px]",
    "tw:pr-[13px]", "tw:pb-[11px]", "tw:pl-[13px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#b8dfd0]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#b8dfd0]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#b8dfd0]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#b8dfd0]", "tw:rounded-[var(--radius-control)]",
    "tw:bg-[color:#effbf6]", "tw:[background-image:none]", "tw:[&_>_div]:grid", "tw:[&_>_div]:gap-y-[3px]",
    "tw:[&_>_div]:gap-x-[3px]", "tw:[&_span]:text-[color:#08775f]", "tw:[&_span]:text-[.66rem]", "tw:[&_span]:font-[850]",
    "tw:[&_span]:tracking-[.08em]", "tw:[&_strong]:text-[color:#07523f]", "tw:[&_strong]:text-[.9rem]", "tw:[&_small]:text-[color:#557367]",
    "tw:[&_small]:text-[.71rem]", "tw:viewport-680:flex-col",
  ].join(" "),
  "public_booking_total": [
    "public-booking-total", "tw:min-w-[112px]", "tw:pl-[14px]", "tw:viewport-680:pl-[0]",
    "tw:border-l-[length:1px]", "tw:viewport-680:border-l-[length:0]", "tw:[border-left-style:solid]", "tw:viewport-680:[border-left-style:none]",
    "tw:border-l-[color:#b8dfd0]", "tw:viewport-680:border-l-[color:currentColor]", "tw:text-right", "tw:viewport-680:text-left",
    "tw:[&_strong]:text-[1rem]", "tw:viewport-680:pt-[9px]", "tw:viewport-680:pr-[0]", "tw:viewport-680:pb-[0]",
    "tw:viewport-680:border-t-[length:1px]", "tw:viewport-680:[border-top-style:solid]", "tw:viewport-680:border-t-[color:#b8dfd0]",
  ].join(" "),
  "public_booking_pending": [
    "public-booking-pending", "tw:[grid-column:1_/_-1]", "tw:grid", "tw:gap-y-[3px]",
    "tw:gap-x-[12px]", "tw:pt-[10px]", "tw:pr-[12px]", "tw:pb-[10px]",
    "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#9edcba]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#9edcba]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#9edcba]", "tw:border-l-[length:4px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#1d9956]", "tw:rounded-[8px]", "tw:bg-[color:#effbf3]", "tw:[background-image:none]",
    "tw:grid-cols-[minmax(0,_1fr)_auto]", "tw:viewport-560:grid-cols-[1fr]", "tw:[&_strong]:text-[color:#0d713c]", "tw:[&_strong]:text-[.76rem]",
    "tw:[&_strong]:[grid-column:1]", "tw:[&_span]:text-[color:#24583d]", "tw:[&_span]:text-[.76rem]", "tw:[&_span]:[grid-column:1]",
    "tw:[&_small]:text-[color:#587563]", "tw:[&_small]:text-[.68rem]", "tw:[&_small]:[grid-column:1]", "tw:[&_.button]:[grid-column:2]",
    "tw:viewport-560:[&_.button]:[grid-column:1]", "tw:[&_.button]:[grid-row:1_/_span_3]", "tw:viewport-560:[&_.button]:[grid-row:auto]", "tw:[&_.button]:[align-self:center]",
    "tw:viewport-560:[&_.button]:[justify-self:start]", "tw:viewport-560:[&_.button]:mt-[5px]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "public_booking_reserved_slots": [
    "public-booking-reserved-slots", "tw:[grid-column:1_/_-1]", "tw:grid", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:pt-[9px]", "tw:pr-[10px]", "tw:pb-[9px]",
    "tw:pl-[10px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#b7d9e9]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#b7d9e9]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#b7d9e9]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#b7d9e9]", "tw:rounded-[8px]", "tw:bg-[color:#f1f8fd]", "tw:[background-image:none]",
    "tw:[&_strong]:text-[color:#43536b]", "tw:[&_strong]:text-[.74rem]", "tw:[&_span]:text-[color:#376783]", "tw:[&_span]:text-[.78rem]",
  ].join(" "),
  "public_booking_message": sharedUtilities.publicBookingMessage,
} as const;
