import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "athlete_portal_content_panel_event_radar": [
    "athlete-portal-content-panel", "event-radar", "tw:w-[min(calc(100%_-_32px),_1060px)]", "tw:viewport-700:w-[calc(100%_-_28px)]",
    "tw:[margin-inline:auto]", "tw:mt-[22px]", "tw:viewport-700:mt-[16px]", "tw:pt-[26px]",
    "tw:viewport-700:pt-[16px]", "tw:pr-[26px]", "tw:viewport-700:pr-[16px]", "tw:pb-[26px]",
    "tw:viewport-700:pb-[16px]", "tw:pl-[26px]", "tw:viewport-700:pl-[16px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(120_162_185_/_.2)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:rgb(120_162_185_/_.2)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(120_162_185_/_.2)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(120_162_185_/_.2)]", "tw:rounded-[15px]",
    "tw:bg-[color:#0d1b28]", "tw:[background-image:none]", "tw:[box-shadow:0_18px_42px_rgb(0_0_0_/_.2)]", "tw:[&_>_header]:grid",
    "tw:[&_>_header]:gap-y-[4px]", "tw:[&_>_header]:gap-x-[4px]", "tw:[&_>_header]:pb-[17px]", "tw:[&_>_header]:border-b-[length:1px]",
    "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-t-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header]:border-r-[color:rgb(135_178_196_/_.16)]",
    "tw:[&_>_header]:border-l-[color:rgb(135_178_196_/_.16)]", "tw:[&_>_header_span]:text-[color:#57d7ae]", "tw:[&_>_header_span]:text-[.66rem]", "tw:[&_>_header_span]:font-[900]",
    "tw:[&_>_header_span]:tracking-[.12em]", "tw:[&_>_header_h2]:mt-[0]", "tw:[&_>_header_h2]:mr-[0]", "tw:[&_>_header_h2]:mb-[0]",
    "tw:[&_>_header_h2]:ml-[0]", "tw:[&_>_header_h2]:text-[color:#f2f9fc]", "tw:[&_>_header_h2]:text-[1.3rem]", "tw:[&_>_header_p]:mt-[0]",
    "tw:[&_>_header_p]:mr-[0]", "tw:[&_>_header_p]:mb-[0]", "tw:[&_>_header_p]:ml-[0]", "tw:[&_>_header_p]:text-[color:#5e7889]",
    "tw:[&_>_header_p]:text-[.82rem]", "tw:[&_>_div]:grid", "tw:[&_>_div]:gap-y-[10px]", "tw:[&_>_div]:gap-x-[10px]",
    "tw:[&_>_div]:mt-[17px]", "tw:[&_article]:grid", "tw:[&_article]:grid-cols-[minmax(130px,_.42fr)_minmax(0,_1fr)_auto]", "tw:viewport-700:[&_article]:grid-cols-[1fr]",
    "tw:[&_article]:items-center", "tw:[&_article]:gap-y-[15px]", "tw:viewport-700:[&_article]:gap-y-[10px]", "tw:[&_article]:gap-x-[15px]",
    "tw:viewport-700:[&_article]:gap-x-[10px]", "tw:[&_article]:pt-[14px]", "tw:[&_article]:pr-[14px]", "tw:[&_article]:pb-[14px]",
    "tw:[&_article]:pl-[14px]", "tw:[&_article]:border-t-[length:1px]", "tw:[&_article]:[border-top-style:solid]", "tw:[&_article]:border-t-[color:#d1e5eb]",
    "tw:[&_article]:border-r-[length:1px]", "tw:[&_article]:[border-right-style:solid]", "tw:[&_article]:border-r-[color:#d1e5eb]", "tw:[&_article]:border-b-[length:1px]",
    "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#d1e5eb]", "tw:[&_article]:border-l-[length:1px]", "tw:[&_article]:[border-left-style:solid]",
    "tw:[&_article]:border-l-[color:#d1e5eb]", "tw:[&_article]:rounded-[11px]", "tw:[&_article]:bg-[color:transparent]", "tw:[&_article]:[background-image:linear-gradient(115deg,_#fbfeff,_#f2fbf7)]",
    "tw:viewport-700:[&_article_.button]:[justify-self:start]",
  ].join(" "),
  "event_radar_embedded": [
    "event-radar-embedded", "tw:w-[min(100%_-_32px,_720px)]", "tw:viewport-700:w-[calc(100%_-_22px)]", "tw:mt-[0]",
    "tw:mr-[auto]", "tw:mb-[0]", "tw:ml-[auto]", "tw:border-t-[color:rgb(77_135_184_/_.3)]",
    "tw:border-r-[color:rgb(77_135_184_/_.3)]", "tw:border-b-[color:rgb(77_135_184_/_.3)]", "tw:border-l-[color:rgb(77_135_184_/_.3)]", "tw:bg-[color:transparent]",
    "tw:[background-image:radial-gradient(circle_at_90%_5%,_rgb(39_227_157_/_.12),_transparent_26%),_linear-gradient(145deg,_#0d2239,_#091727)]", "tw:[&_>_header_p]:text-[color:#aec1d1]", "tw:[&_article]:border-t-[color:rgb(77_135_184_/_.3)]", "tw:[&_article]:border-r-[color:rgb(77_135_184_/_.3)]",
    "tw:[&_article]:border-b-[color:rgb(77_135_184_/_.3)]", "tw:[&_article]:border-l-[color:rgb(77_135_184_/_.3)]", "tw:[&_article]:bg-[color:#102239]", "tw:[&_article]:[background-image:none]",
    "tw:[&_.event-radar-copy_strong]:text-[color:#f3f8ff]", "tw:[&_.event-radar-copy_p]:text-[color:#aec1d1]", "tw:[&_.event-radar-arena]:text-[color:#aec1d1]", "tw:[&_.event-radar-arena_small]:text-[color:#aec1d1]",
    "tw:[&_.event-radar-view-toggle]:bg-[color:#0b1d31]", "tw:[&_.event-radar-view-toggle]:[background-image:none]", "tw:[&_.event-radar-view-toggle_a.active]:text-[color:#56eeb3]", "tw:[&_.event-radar-view-toggle_a.active]:bg-[color:#102b43]",
    "tw:[&_.event-radar-view-toggle_a.active]:[background-image:none]", "tw:viewport-700:pt-[14px]", "tw:viewport-700:pr-[14px]", "tw:viewport-700:pb-[14px]",
    "tw:viewport-700:pl-[14px]", "tw:viewport-700:[&_>_div]:mt-[12px]", "tw:viewport-700:[&_article]:pt-[11px]", "tw:viewport-700:[&_article]:pr-[11px]",
    "tw:viewport-700:[&_article]:pb-[11px]", "tw:viewport-700:[&_article]:pl-[11px]", "tw:viewport-700:[&_.event-radar-copy_strong]:text-[.84rem]",
  ].join(" "),
  "event_radar_view_toggle": [
    "event-radar-view-toggle", "tw:inline-flex!", "tw:w-[fit-content]", "tw:gap-y-[3px]!",
    "tw:gap-x-[3px]!", "tw:mt-[11px]!", "tw:pt-[3px]", "tw:pr-[3px]",
    "tw:pb-[3px]", "tw:pl-[3px]", "tw:rounded-[8px]", "tw:bg-[color:#edf4f6]",
    "tw:[background-image:none]", "tw:[&_a]:pt-[6px]", "tw:[&_a]:pr-[8px]", "tw:[&_a]:pb-[6px]",
    "tw:[&_a]:pl-[8px]", "tw:[&_a]:rounded-[6px]", "tw:[&_a]:text-[color:#5c7487]", "tw:[&_a]:text-[.68rem]",
    "tw:[&_a]:font-[800]", "tw:[&_a]:[text-decoration:none]", "tw:[&_a.active]:text-[color:#08745f]", "tw:[&_a.active]:bg-[color:#fff]",
    "tw:[&_a.active]:[background-image:none]", "tw:[&_a.active]:[box-shadow:0_1px_4px_rgb(18_74_100_/_.12)]",
  ].join(" "),
  "event_radar_arena": [
    "event-radar-arena", "tw:grid", "tw:grid-cols-[32px_minmax(0,_1fr)]", "tw:items-center",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:text-[color:#467286]", "tw:text-[.7rem]",
    "tw:font-[850]", "tw:[&_img]:grid", "tw:[&_img]:w-[32px]", "tw:[&_img]:h-[32px]",
    "tw:[&_img]:place-items-center", "tw:[&_img]:rounded-[7px]", "tw:[&_img]:[object-fit:contain]", "tw:[&_img]:bg-[color:#fff]",
    "tw:[&_img]:[background-image:none]", "tw:[&_img]:text-[color:#08765f]", "tw:[&_b]:grid", "tw:[&_b]:w-[32px]",
    "tw:[&_b]:h-[32px]", "tw:[&_b]:place-items-center", "tw:[&_b]:rounded-[7px]", "tw:[&_b]:[object-fit:contain]",
    "tw:[&_b]:bg-[color:#fff]", "tw:[&_b]:[background-image:none]", "tw:[&_b]:text-[color:#08765f]", "tw:[&_span]:grid",
    "tw:[&_span]:gap-y-[2px]", "tw:[&_span]:gap-x-[2px]", "tw:[&_small]:text-[color:#71899a]", "tw:[&_small]:text-[.61rem]",
    "tw:[&_small]:font-[600]",
  ].join(" "),
  "event_radar_copy": [
    "event-radar-copy", "tw:grid", "tw:gap-y-[5px]", "tw:gap-x-[5px]",
    "tw:[&_strong]:text-[color:#164269]", "tw:[&_strong]:text-[.93rem]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#647d8e]", "tw:[&_p]:text-[.75rem]",
    "tw:[&_p]:leading-[1.4]", "tw:[&_>_div]:flex", "tw:[&_>_div]:flex-wrap", "tw:[&_>_div]:gap-y-[5px]",
    "tw:[&_>_div]:gap-x-[5px]", "tw:[&_em]:pt-[4px]", "tw:[&_em]:pr-[6px]", "tw:[&_em]:pb-[4px]",
    "tw:[&_em]:pl-[6px]", "tw:[&_em]:rounded-[999px]", "tw:[&_em]:text-[color:#187157]", "tw:[&_em]:bg-[color:#e2f5ec]",
    "tw:[&_em]:[background-image:none]", "tw:[&_em]:text-[.63rem]", "tw:[&_em]:not-italic", "tw:[&_em]:font-[850]",
  ].join(" "),
  "button_button_primary_button_small": sharedUtilities.buttonButtonPrimaryButtonSmall,
  "event_radar_status": [
    "event-radar-status", "tw:pt-[4px]", "tw:pr-[6px]", "tw:pb-[4px]",
    "tw:pl-[6px]", "tw:rounded-[999px]", "tw:text-[color:#577588]", "tw:bg-[color:#edf4f7]",
    "tw:[background-image:none]", "tw:text-[.63rem]", "tw:not-italic", "tw:font-[850]",
    "tw:whitespace-nowrap",
  ].join(" "),
  "portal_empty": [
    "portal-empty", "tw:grid", "tw:[justify-items:start]", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:mt-[16px]", "tw:pt-[22px]", "tw:pr-[22px]",
    "tw:pb-[22px]", "tw:pl-[22px]", "tw:border-t-[length:1px]", "tw:[border-top-style:dashed]",
    "tw:border-t-[color:rgb(99_172_195_/_.35)]", "tw:border-r-[length:1px]", "tw:[border-right-style:dashed]", "tw:border-r-[color:rgb(99_172_195_/_.35)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:dashed]", "tw:border-b-[color:rgb(99_172_195_/_.35)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:dashed]", "tw:border-l-[color:rgb(99_172_195_/_.35)]", "tw:rounded-[11px]", "tw:bg-[color:#102232]",
    "tw:[background-image:none]", "tw:[&_strong]:text-[color:#f2f9fc]", "tw:[&_span]:text-[color:#a4bac8]", "tw:[&_span]:text-[.84rem]",
    "tw:[&_.button]:mt-[5px]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
} as const;
