import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "teacher_portal_student_row": [
    "teacher-portal-student-row", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:pt-[0]", "tw:pr-[0]", "tw:pb-[0]", "tw:pl-[0]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(106_184_200_/_.2)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(106_184_200_/_.2)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgb(106_184_200_/_.2)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(106_184_200_/_.2)]",
    "tw:rounded-[7px]", "tw:bg-[color:rgb(2_30_43_/_.24)]", "tw:[background-image:none]", "tw:grid-cols-[minmax(0,_1fr)]",
    "tw:[&_>_span]:grid", "tw:[&_>_span]:gap-y-[3px]", "tw:[&_>_span]:gap-x-[3px]", "tw:[&_strong]:text-[color:#eaf8fb]",
    "tw:[&_strong]:text-[.8rem]", "tw:[&_small]:text-[color:#a7c6d0]", "tw:[&_small]:text-[.72rem]", "tw:[&_>_summary]:flex",
    "tw:[&_>_summary]:items-center", "tw:[&_>_summary]:justify-between", "tw:[&_>_summary]:gap-y-[12px]", "tw:[&_>_summary]:gap-x-[12px]",
    "tw:[&_>_summary]:pt-[7px]", "tw:[&_>_summary]:pr-[10px]", "tw:[&_>_summary]:pb-[7px]", "tw:[&_>_summary]:pl-[10px]",
    "tw:[&_>_summary]:cursor-pointer", "tw:[&_>_summary]:[list-style:none]", "tw:[&_>_summary]:min-h-[44px]", "tw:[&_>_summary::-webkit-details-marker]:hidden",
    "tw:[&_>_summary_>_span]:min-w-[0]", "tw:[&_>_summary_>_span]:grid", "tw:[&_>_summary_>_span]:gap-y-[2px]", "tw:[&_>_summary_>_span]:gap-x-[2px]",
    "tw:[&_>_summary_i]:text-[color:#9bc5d0]", "tw:[&_>_summary_i]:not-italic", "tw:[&_>_summary_i]:[transition:transform_.16s_ease]", "tw:[&[open]_>_summary]:border-b-[length:1px]",
    "tw:[&[open]_>_summary]:[border-bottom-style:solid]", "tw:[&[open]_>_summary]:border-b-[color:rgb(108_184_200_/_.2)]", "tw:[&[open]_>_summary]:bg-[color:rgb(16_79_92_/_.36)]", "tw:[&[open]_>_summary]:[background-image:none]",
    "tw:[&[open]_>_summary_i]:[transform:rotate(180deg)]", "tw:[&_.teacher-student-portal-actions]:pt-[10px]", "tw:[&_.teacher-student-portal-actions]:pr-[10px]", "tw:[&_.teacher-student-portal-actions]:pb-[10px]",
    "tw:[&_.teacher-student-portal-actions]:pl-[10px]", "tw:[&_>_summary_strong]:[overflow-x:hidden]", "tw:[&_>_summary_strong]:[overflow-y:hidden]", "tw:[&_>_summary_strong]:text-[color:#f2fbfc]",
    "tw:[&_>_summary_strong]:text-[.77rem]", "tw:[&_>_summary_strong]:leading-[1.2]", "tw:[&_>_summary_strong]:text-ellipsis", "tw:[&_>_summary_strong]:whitespace-nowrap",
    "tw:[&_>_summary_small]:[overflow-x:hidden]", "tw:[&_>_summary_small]:[overflow-y:hidden]", "tw:[&_>_summary_small]:text-[color:#bad3da]", "tw:[&_>_summary_small]:text-[.66rem]",
    "tw:[&_>_summary_small]:leading-[1.2]", "tw:[&_>_summary_small]:text-ellipsis", "tw:[&_>_summary_small]:whitespace-nowrap",
  ].join(" "),
  "teacher_student_workspace": [
    "teacher-student-workspace", "tw:grid", "tw:gap-y-[9px]", "tw:gap-x-[9px]",
    "tw:pt-[9px]", "tw:pr-[9px]", "tw:pb-[9px]", "tw:pl-[9px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(105_181_198_/_.18)]", "tw:[&_>_nav]:flex",
    "tw:[&_>_nav]:gap-y-[5px]", "tw:[&_>_nav]:gap-x-[5px]", "tw:[&_>_nav_button]:min-h-[28px]", "tw:[&_>_nav_button]:pt-[4px]",
    "tw:[&_>_nav_button]:pr-[9px]", "tw:[&_>_nav_button]:pb-[4px]", "tw:[&_>_nav_button]:pl-[9px]", "tw:[&_>_nav_button]:border-t-[length:1px]",
    "tw:[&_>_nav_button]:[border-top-style:solid]", "tw:[&_>_nav_button]:border-t-[color:rgb(105_181_198_/_.28)]", "tw:[&_>_nav_button]:border-r-[length:1px]", "tw:[&_>_nav_button]:[border-right-style:solid]",
    "tw:[&_>_nav_button]:border-r-[color:rgb(105_181_198_/_.28)]", "tw:[&_>_nav_button]:border-b-[length:1px]", "tw:[&_>_nav_button]:[border-bottom-style:solid]", "tw:[&_>_nav_button]:border-b-[color:rgb(105_181_198_/_.28)]",
    "tw:[&_>_nav_button]:border-l-[length:1px]", "tw:[&_>_nav_button]:[border-left-style:solid]", "tw:[&_>_nav_button]:border-l-[color:rgb(105_181_198_/_.28)]", "tw:[&_>_nav_button]:rounded-[6px]",
    "tw:[&_>_nav_button]:text-[color:#b9d4da]", "tw:[&_>_nav_button]:bg-[color:rgb(6_47_62_/_.45)]", "tw:[&_>_nav_button]:[background-image:none]", "tw:[&_>_nav_button]:text-[.67rem]",
    "tw:[&_>_nav_button]:font-[700]", "tw:[&_>_nav_button.active]:border-t-[color:rgb(79_223_181_/_.56)]", "tw:[&_>_nav_button.active]:border-r-[color:rgb(79_223_181_/_.56)]", "tw:[&_>_nav_button.active]:border-b-[color:rgb(79_223_181_/_.56)]",
    "tw:[&_>_nav_button.active]:border-l-[color:rgb(79_223_181_/_.56)]", "tw:[&_>_nav_button.active]:text-[color:#effffc]", "tw:[&_>_nav_button.active]:bg-[color:rgb(24_113_98_/_.5)]", "tw:[&_>_nav_button.active]:[background-image:none]",
  ].join(" "),
  "teacher_student_action_panel": [
    "teacher-student-action-panel", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:pt-[10px]", "tw:pr-[10px]", "tw:pb-[10px]", "tw:pl-[10px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(105_181_198_/_.22)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(105_181_198_/_.22)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgb(105_181_198_/_.22)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(105_181_198_/_.22)]",
    "tw:rounded-[8px]", "tw:bg-[color:rgb(3_32_46_/_.36)]", "tw:[background-image:none]", "tw:[&_>_header]:flex",
    "tw:[&_>_header]:items-baseline", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[9px]", "tw:[&_>_header]:gap-x-[9px]",
    "tw:[&_>_header_>_span]:text-[color:#bdd9df]", "tw:[&_>_header_>_span]:text-[.69rem]", "tw:[&_>_header_>_strong]:text-[color:#65ecc3]", "tw:[&_>_header_>_strong]:text-[.88rem]",
    "tw:[&_>_header_small]:text-[color:#a9c9d2]", "tw:[&_>_header_small]:text-[.66rem]", "tw:[&_>_header_small]:font-[500]",
  ].join(" "),
  "teacher_student_balance_actions": [
    "teacher-student-balance-actions", "tw:flex", "tw:flex-wrap", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:[&_.button]:w-[auto]", "tw:[&_.button]:min-h-[32px]", "tw:[&_.button]:pt-[6px]",
    "tw:[&_.button]:pr-[10px]", "tw:[&_.button]:pb-[6px]", "tw:[&_.button]:pl-[10px]", "tw:[&_.button]:text-[.68rem]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "button_button_small_button_secondary": [
    "button", "button-small", "button-secondary", "tw:inline-flex",
    "tw:items-center", "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:min-h-[30px]", "tw:pt-[5px]", "tw:pr-[8px]", "tw:pb-[5px]",
    "tw:pl-[8px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:transparent]", "tw:[background-image:none]",
    "tw:text-[color:var(--text)]", "tw:text-[.72rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--line-strong)]",
    "tw:hover:border-r-[color:var(--line-strong)]", "tw:hover:border-b-[color:var(--line-strong)]", "tw:hover:border-l-[color:var(--line-strong)]", "tw:hover:[transform:translateY(-1px)]",
    "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]",
    "tw:[&:active]:[box-shadow:none]",
  ].join(" "),
  "teacher_student_notice_form": [
    "teacher-student-notice-form", "tw:[&_.button]:w-[auto]", "tw:viewport-640:[&_.button]:w-[100%]", "tw:[&_.button]:min-h-[31px]",
    "tw:[&_.button]:pt-[5px]", "tw:[&_.button]:pr-[9px]", "tw:[&_.button]:pb-[5px]", "tw:[&_.button]:pl-[9px]",
    "tw:[&_.button]:[justify-self:end]", "tw:viewport-640:[&_.button]:[justify-self:stretch]", "tw:grid", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:[&_textarea]:min-h-[92px]", "tw:[&_textarea]:pt-[10px]", "tw:[&_textarea]:pr-[10px]",
    "tw:[&_textarea]:pb-[10px]", "tw:[&_textarea]:pl-[10px]", "tw:[&_textarea]:[resize:vertical]", "tw:[&_textarea]:border-t-[length:1px]",
    "tw:[&_textarea]:[border-top-style:solid]", "tw:[&_textarea]:border-t-[color:#4f899b]", "tw:[&_textarea]:border-r-[length:1px]", "tw:[&_textarea]:[border-right-style:solid]",
    "tw:[&_textarea]:border-r-[color:#4f899b]", "tw:[&_textarea]:border-b-[length:1px]", "tw:[&_textarea]:[border-bottom-style:solid]", "tw:[&_textarea]:border-b-[color:#4f899b]",
    "tw:[&_textarea]:border-l-[length:1px]", "tw:[&_textarea]:[border-left-style:solid]", "tw:[&_textarea]:border-l-[color:#4f899b]", "tw:[&_textarea]:rounded-[8px]",
    "tw:[&_textarea]:text-[color:#f1fbfc]", "tw:[&_textarea]:bg-[color:#082f42]", "tw:[&_textarea]:[background-image:none]", "tw:[&_textarea]:[font:inherit]",
    "tw:[&_textarea]:text-[.75rem]", "tw:[&_textarea]:leading-[1.45]", "tw:[&_textarea::placeholder]:text-[color:#afcad2]", "tw:[&_footer]:flex",
    "tw:[&_footer]:items-center", "tw:[&_footer]:justify-between", "tw:[&_footer]:gap-y-[8px]", "tw:[&_footer]:gap-x-[8px]",
    "tw:[&_footer_small]:text-[color:#a6c5cf]", "tw:[&_footer_small]:text-[.66rem]",
  ].join(" "),
  "teacher_student_class_form": [
    "teacher-student-class-form", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[4px]", "tw:[&_label]:gap-x-[4px]",
    "tw:[&_label]:text-[color:#c2dbe1]", "tw:[&_label]:text-[.66rem]", "tw:[&_select]:min-w-[0]", "tw:[&_select]:min-h-[32px]",
    "tw:[&_select]:pt-[6px]", "tw:[&_select]:pr-[8px]", "tw:[&_select]:pb-[6px]", "tw:[&_select]:pl-[8px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:#4f899b]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#4f899b]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:#4f899b]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#4f899b]",
    "tw:[&_select]:rounded-[6px]", "tw:[&_select]:text-[color:#f2fbfc]", "tw:[&_select]:bg-[color:#082f42]", "tw:[&_select]:[background-image:none]",
    "tw:[&_select]:text-[.73rem]", "tw:[&_.button]:w-[auto]", "tw:viewport-640:[&_.button]:w-[100%]", "tw:[&_.button]:min-h-[31px]",
    "tw:[&_.button]:pt-[5px]", "tw:[&_.button]:pr-[9px]", "tw:[&_.button]:pb-[5px]", "tw:[&_.button]:pl-[9px]",
    "tw:[&_.button]:[justify-self:end]", "tw:viewport-640:[&_.button]:[justify-self:stretch]", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)_auto]",
    "tw:viewport-640:grid-cols-[1fr]", "tw:[align-items:end]", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
  ].join(" "),
  "teacher_portal_student_filters": [
    "teacher-portal-student-filters", "tw:grid", "tw:grid-cols-[minmax(180px,_1fr)_minmax(150px,_.55fr)_auto]", "tw:viewport-640:grid-cols-[1fr]",
    "tw:[align-items:end]", "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:pt-[10px]",
    "tw:pr-[10px]", "tw:pb-[10px]", "tw:pl-[10px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(99_178_196_/_.25)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:rgb(99_178_196_/_.25)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(99_178_196_/_.25)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(99_178_196_/_.25)]", "tw:rounded-[9px]",
    "tw:bg-[color:rgb(5_39_53_/_.44)]", "tw:[background-image:none]", "tw:[&_label]:grid", "tw:[&_label]:min-w-[0]",
    "tw:[&_label]:gap-y-[4px]", "tw:[&_label]:gap-x-[4px]", "tw:[&_label]:text-[color:#c6dce2]", "tw:[&_label]:text-[.69rem]",
    "tw:[&_input]:min-w-[0]", "tw:[&_input]:min-h-[34px]", "tw:[&_input]:pt-[7px]", "tw:[&_input]:pr-[9px]",
    "tw:[&_input]:pb-[7px]", "tw:[&_input]:pl-[9px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]",
    "tw:[&_input]:border-t-[color:rgb(118_193_210_/_.48)]", "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:rgb(118_193_210_/_.48)]",
    "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:rgb(118_193_210_/_.48)]", "tw:[&_input]:border-l-[length:1px]",
    "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:rgb(118_193_210_/_.48)]", "tw:[&_input]:rounded-[7px]", "tw:[&_input]:text-[color:#f3fcfd]",
    "tw:[&_input]:bg-[color:rgb(3_34_48_/_.9)]", "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[.78rem]", "tw:[&_input]:font-[600]",
    "tw:[&_select]:min-w-[0]", "tw:[&_select]:min-h-[34px]", "tw:[&_select]:pt-[7px]", "tw:[&_select]:pr-[9px]",
    "tw:[&_select]:pb-[7px]", "tw:[&_select]:pl-[9px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]",
    "tw:[&_select]:border-t-[color:rgb(118_193_210_/_.48)]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:rgb(118_193_210_/_.48)]",
    "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:rgb(118_193_210_/_.48)]", "tw:[&_select]:border-l-[length:1px]",
    "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:rgb(118_193_210_/_.48)]", "tw:[&_select]:rounded-[7px]", "tw:[&_select]:text-[color:#f3fcfd]",
    "tw:[&_select]:bg-[color:rgb(3_34_48_/_.9)]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[.78rem]", "tw:[&_select]:font-[600]",
    "tw:[&_input::placeholder]:text-[color:#b4d0d8]", "tw:[&_input::placeholder]:opacity-[1]", "tw:[&_small]:pb-[8px]", "tw:viewport-640:[&_small]:pb-[0]",
    "tw:[&_small]:text-[color:#a8cbd5]", "tw:[&_small]:text-[.7rem]", "tw:[&_small]:whitespace-nowrap",
  ].join(" "),
  "teacher_portal_student_list": [
    "teacher-portal-student-list", "tw:grid", "tw:gap-y-[5px]", "tw:gap-x-[5px]",
  ].join(" "),
  "teacher_portal_empty_filter": [
    "teacher-portal-empty-filter", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]",
    "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:dashed]", "tw:border-t-[color:rgb(106_184_200_/_.35)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:dashed]", "tw:border-r-[color:rgb(106_184_200_/_.35)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:dashed]", "tw:border-b-[color:rgb(106_184_200_/_.35)]", "tw:border-l-[length:1px]", "tw:[border-left-style:dashed]",
    "tw:border-l-[color:rgb(106_184_200_/_.35)]", "tw:rounded-[8px]", "tw:text-[color:#b6d1d8]", "tw:text-center",
  ].join(" "),
} as const;
