import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "field": [
    "field", "tv-match-source-field", "tw:grid", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]", "tw:[&_input]:w-[100%]",
    "tw:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[14px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:text-[color:var(--text)]", "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[44px]",
    "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[14px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:var(--line)]",
    "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:var(--text)]",
    "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_input:focus]:[transform:translateY(-1px)]",
    "tw:[&_select:focus]:[outline:none]", "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]", "tw:[&_input[type=file]]:pt-[10px]",
    "tw:[&_input[type=file]]:pr-[14px]", "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]", "tw:[&_input[type=checkbox]]:w-[auto]",
    "tw:[&_input[type=checkbox]]:min-h-[auto]", "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]", "tw:[&_input[type=checkbox]]:pb-[0]",
    "tw:[&_input[type=checkbox]]:pl-[0]", "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]", "tw:[&_input[type=radio]]:pt-[0]",
    "tw:[&_input[type=radio]]:pr-[0]", "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]",
  ].join(" "),
  "tv_source_edit_link": [
    "tv-source-edit-link", "tw:w-[max-content]", "tw:max-w-[100%]", "tw:pt-[3px]",
    "tw:pr-[0]", "tw:pb-[3px]", "tw:pl-[0]", "tw:border-t-[length:0]",
    "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]",
    "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:text-[color:#1765ae]",
    "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:[font:inherit]", "tw:text-[.7rem]",
    "tw:text-left", "tw:[text-decoration:underline]", "tw:cursor-pointer",
  ].join(" "),
  "field_tv_source_tournament_field": [
    "field", "tv-source-tournament-field", "tw:grid", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]", "tw:[&_input]:w-[100%]",
    "tw:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[14px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:text-[color:var(--text)]", "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[44px]",
    "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[14px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:var(--line)]",
    "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:var(--text)]",
    "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_input:focus]:[transform:translateY(-1px)]",
    "tw:[&_select:focus]:[outline:none]", "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]", "tw:[&_input[type=file]]:pt-[10px]",
    "tw:[&_input[type=file]]:pr-[14px]", "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]", "tw:[&_input[type=checkbox]]:w-[auto]",
    "tw:[&_input[type=checkbox]]:min-h-[auto]", "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]", "tw:[&_input[type=checkbox]]:pb-[0]",
    "tw:[&_input[type=checkbox]]:pl-[0]", "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]", "tw:[&_input[type=radio]]:pt-[0]",
    "tw:[&_input[type=radio]]:pr-[0]", "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]", "tw:[&_select:disabled]:text-[color:#8295a8]",
    "tw:[&_select:disabled]:bg-[color:#f2f5f8]", "tw:[&_select:disabled]:[background-image:none]",
  ].join(" "),
  "tv_manual_modal_backdrop": [
    "tv-manual-modal-backdrop", "tw:fixed", "tw:z-[100]", "tw:top-[0]",
    "tw:right-[0]", "tw:bottom-[0]", "tw:left-[0]", "tw:grid",
    "tw:[overflow-y:auto]", "tw:place-items-center", "tw:pt-[20px]", "tw:pr-[20px]",
    "tw:pb-[20px]", "tw:pl-[20px]", "tw:bg-[color:rgb(8_22_39_/_.62)]", "tw:[background-image:none]",
  ].join(" "),
  "tv_manual_modal": [
    "tv-manual-modal", "tw:w-[min(100%,_680px)]", "tw:max-h-[calc(100dvh_-_40px)]", "tw:[overflow-y:auto]",
    "tw:pt-[22px]", "tw:viewport-620:pt-[16px]", "tw:pr-[22px]", "tw:viewport-620:pr-[16px]",
    "tw:pb-[22px]", "tw:viewport-620:pb-[16px]", "tw:pl-[22px]", "tw:viewport-620:pl-[16px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#cbdbea]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#cbdbea]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#cbdbea]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#cbdbea]",
    "tw:rounded-[12px]", "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[box-shadow:0_20px_60px_rgb(9_28_52_/_.24)]",
    "tw:[&_>_header]:flex", "tw:[&_>_header]:[align-items:start]", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[16px]",
    "tw:[&_>_header]:gap-x-[16px]", "tw:[&_>_header]:mb-[18px]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]",
    "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#173961]", "tw:[&_h2]:text-[1.2rem]",
    "tw:[&_p]:mt-[4px]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
    "tw:[&_p]:text-[color:#60758b]", "tw:[&_p]:text-[.8rem]",
  ].join(" "),
  "tv_manual_modal_close": [
    "tv-manual-modal-close", "tw:grid", "tw:w-[34px]", "tw:h-[34px]",
    "tw:[flex:0_0_34px]", "tw:place-items-center", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dce6ef]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce6ef]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce6ef]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dce6ef]", "tw:rounded-[7px]", "tw:text-[color:#455f78]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:text-[1.35rem]", "tw:cursor-pointer",
  ].join(" "),
  "tv_manual_warning": [
    "tv-manual-warning", "tw:pt-[10px]", "tw:pr-[12px]", "tw:pb-[10px]",
    "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#e2c78e]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#e2c78e]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e2c78e]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#e2c78e]", "tw:rounded-[7px]", "tw:bg-[color:#fff8e7]", "tw:[background-image:none]",
  ].join(" "),
  "tv_manual_games": [
    "tv-manual-games", "tw:grid", "tw:gap-y-[14px]", "tw:gap-x-[14px]",
  ].join(" "),
  "tv_manual_game": [
    "tv-manual-game", "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]",
    "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dce7f1]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce7f1]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce7f1]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#dce7f1]", "tw:rounded-[9px]", "tw:bg-[color:#fbfdff]", "tw:[background-image:none]",
  ].join(" "),
  "tv_manual_match_form": [
    "tv-manual-match-form", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-620:grid-cols-[minmax(0,_1fr)]",
    "tw:gap-y-[13px]", "tw:gap-x-[13px]", "tw:[&_>_label]:grid", "tw:[&_>_label]:min-w-[0]",
    "tw:[&_>_label]:gap-y-[5px]", "tw:[&_>_label]:gap-x-[5px]", "tw:[&_>_label]:text-[color:#455f7c]", "tw:[&_>_label]:text-[.77rem]",
    "tw:[&_>_label]:font-[700]", "tw:[&_input]:w-[100%]", "tw:[&_input]:min-w-[0]", "tw:[&_input]:min-h-[39px]",
    "tw:[&_input]:pt-[7px]", "tw:[&_input]:pr-[10px]", "tw:[&_input]:pb-[7px]", "tw:[&_input]:pl-[10px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#cbdbea]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#cbdbea]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:#cbdbea]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#cbdbea]",
    "tw:[&_input]:rounded-[7px]", "tw:[&_input]:text-[color:#193957]", "tw:[&_input]:bg-[color:#fff]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:[font:inherit]", "tw:[&_input]:font-[400]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-w-[0]",
    "tw:[&_select]:min-h-[39px]", "tw:[&_select]:pt-[7px]", "tw:[&_select]:pr-[10px]", "tw:[&_select]:pb-[7px]",
    "tw:[&_select]:pl-[10px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:#cbdbea]",
    "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#cbdbea]", "tw:[&_select]:border-b-[length:1px]",
    "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:#cbdbea]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]",
    "tw:[&_select]:border-l-[color:#cbdbea]", "tw:[&_select]:rounded-[7px]", "tw:[&_select]:text-[color:#193957]", "tw:[&_select]:bg-[color:#fff]",
    "tw:[&_select]:[background-image:none]", "tw:[&_select]:[font:inherit]", "tw:[&_select]:font-[400]", "tw:[&_footer]:flex",
    "tw:[&_footer]:[grid-column:1_/_-1]", "tw:viewport-620:[&_footer]:[grid-column:1]", "tw:[&_footer]:justify-end", "tw:[&_footer]:flex-wrap",
    "tw:[&_footer]:gap-y-[9px]", "tw:[&_footer]:gap-x-[9px]", "tw:[&_footer]:mt-[7px]", "tw:[&_footer]:pt-[15px]",
    "tw:[&_footer]:border-t-[length:1px]", "tw:[&_footer]:[border-top-style:solid]", "tw:[&_footer]:border-t-[color:#e5edf4]", "tw:viewport-620:[&_footer_.button]:[flex:1_1_160px]",
    "tw:viewport-620:[&_footer_.button]:justify-center",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "tv_manual_delete": [
    "tv-manual-delete", "tw:flex", "tw:justify-end", "tw:mt-[8px]",
  ].join(" "),
  "button_button_danger": sharedUtilities.buttonButtonDanger,
  "tv_manual_match_form_tv_manual_new_game": [
    "tv-manual-match-form", "tv-manual-new-game", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]",
    "tw:viewport-620:grid-cols-[minmax(0,_1fr)]", "tw:gap-y-[13px]", "tw:gap-x-[13px]", "tw:[&_>_label]:grid",
    "tw:[&_>_label]:min-w-[0]", "tw:[&_>_label]:gap-y-[5px]", "tw:[&_>_label]:gap-x-[5px]", "tw:[&_>_label]:text-[color:#455f7c]",
    "tw:[&_>_label]:text-[.77rem]", "tw:[&_>_label]:font-[700]", "tw:[&_input]:w-[100%]", "tw:[&_input]:min-w-[0]",
    "tw:[&_input]:min-h-[39px]", "tw:[&_input]:pt-[7px]", "tw:[&_input]:pr-[10px]", "tw:[&_input]:pb-[7px]",
    "tw:[&_input]:pl-[10px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:#cbdbea]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#cbdbea]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:#cbdbea]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:#cbdbea]", "tw:[&_input]:rounded-[7px]", "tw:[&_input]:text-[color:#193957]", "tw:[&_input]:bg-[color:#fff]",
    "tw:[&_input]:[background-image:none]", "tw:[&_input]:[font:inherit]", "tw:[&_input]:font-[400]", "tw:[&_select]:w-[100%]",
    "tw:[&_select]:min-w-[0]", "tw:[&_select]:min-h-[39px]", "tw:[&_select]:pt-[7px]", "tw:[&_select]:pr-[10px]",
    "tw:[&_select]:pb-[7px]", "tw:[&_select]:pl-[10px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]",
    "tw:[&_select]:border-t-[color:#cbdbea]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:#cbdbea]",
    "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:#cbdbea]", "tw:[&_select]:border-l-[length:1px]",
    "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:#cbdbea]", "tw:[&_select]:rounded-[7px]", "tw:[&_select]:text-[color:#193957]",
    "tw:[&_select]:bg-[color:#fff]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:[font:inherit]", "tw:[&_select]:font-[400]",
    "tw:[&_footer]:flex", "tw:[&_footer]:[grid-column:1_/_-1]", "tw:viewport-620:[&_footer]:[grid-column:1]", "tw:[&_footer]:justify-end",
    "tw:[&_footer]:flex-wrap", "tw:[&_footer]:gap-y-[9px]", "tw:[&_footer]:gap-x-[9px]", "tw:[&_footer]:mt-[7px]",
    "tw:[&_footer]:pt-[15px]", "tw:[&_footer]:border-t-[length:1px]", "tw:[&_footer]:[border-top-style:solid]", "tw:[&_footer]:border-t-[color:#e5edf4]",
    "tw:viewport-620:[&_footer_.button]:[flex:1_1_160px]", "tw:viewport-620:[&_footer_.button]:justify-center", "tw:pt-[14px]", "tw:pr-[14px]",
    "tw:pb-[14px]", "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dce7f1]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce7f1]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce7f1]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dce7f1]", "tw:rounded-[9px]", "tw:bg-[color:#fbfdff]",
    "tw:[background-image:none]",
  ].join(" "),
} as const;
