/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "tv_sponsor_multiselect": [
    "tv-sponsor-multiselect", "tw:relative", "tw:w-[min(100%,_580px)]",
  ].join(" "),
  "tv_sponsor_multiselect_control": [
    "tv-sponsor-multiselect-control", "tw:flex", "tw:items-center", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:min-h-[46px]", "tw:pt-[6px]", "tw:pr-[10px]",
    "tw:pb-[6px]", "tw:pl-[10px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[9px]", "tw:bg-[color:var(--surface)]",
    "tw:[background-image:none]", "tw:[cursor:text]", "tw:[&:focus-within]:border-t-[color:var(--primary)]", "tw:[&:focus-within]:border-r-[color:var(--primary)]",
    "tw:[&:focus-within]:border-b-[color:var(--primary)]", "tw:[&:focus-within]:border-l-[color:var(--primary)]", "tw:[&:focus-within]:[box-shadow:0_0_0_3px_color-mix(in_srgb,_var(--primary)_14%,_transparent)]",
  ].join(" "),
  "tv_sponsor_tags": [
    "tv-sponsor-tags", "tw:flex", "tw:[flex:1]", "tw:flex-wrap",
    "tw:items-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:min-w-[0]",
    "tw:[&_input]:[flex:1_1_160px]", "tw:[&_input]:min-w-[120px]", "tw:[&_input]:min-h-[30px]", "tw:[&_input]:pt-[0]",
    "tw:[&_input]:pr-[3px]", "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[3px]", "tw:[&_input]:border-t-[length:0]",
    "tw:[&_input]:[border-top-style:none]", "tw:[&_input]:border-t-[color:currentColor]", "tw:[&_input]:border-r-[length:0]", "tw:[&_input]:[border-right-style:none]",
    "tw:[&_input]:border-r-[color:currentColor]", "tw:[&_input]:border-b-[length:0]", "tw:[&_input]:[border-bottom-style:none]", "tw:[&_input]:border-b-[color:currentColor]",
    "tw:[&_input]:border-l-[length:0]", "tw:[&_input]:[border-left-style:none]", "tw:[&_input]:border-l-[color:currentColor]", "tw:[&_input]:[outline:0]",
    "tw:[&_input]:bg-[color:transparent]", "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:var(--text)]",
  ].join(" "),
  "tv_sponsor_tag": [
    "tv-sponsor-tag", "tw:inline-flex", "tw:items-center", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:min-h-[28px]", "tw:pt-[4px]", "tw:pr-[6px]",
    "tw:pb-[4px]", "tw:pl-[9px]", "tw:rounded-[7px]", "tw:bg-[color:var(--brand-soft)]",
    "tw:[background-image:none]", "tw:text-[color:var(--brand-strong)]", "tw:text-[.78rem]", "tw:font-[650]",
    "tw:[&_button]:grid", "tw:[&_button]:w-[19px]", "tw:[&_button]:h-[19px]", "tw:[&_button]:place-items-center",
    "tw:[&_button]:pt-[0]", "tw:[&_button]:pr-[0]", "tw:[&_button]:pb-[0]", "tw:[&_button]:pl-[0]",
    "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]", "tw:[&_button]:border-r-[length:0]",
    "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:0]", "tw:[&_button]:[border-bottom-style:none]",
    "tw:[&_button]:border-b-[color:currentColor]", "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]", "tw:[&_button]:border-l-[color:currentColor]",
    "tw:[&_button]:rounded-[5px]", "tw:[&_button]:bg-[color:transparent]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:inherit]",
    "tw:[&_button_svg]:w-[12px]", "tw:[&_button_svg]:h-[12px]", "tw:[&_button:hover]:bg-[color:color-mix(in_srgb,_var(--primary)_15%,_transparent)]", "tw:[&_button:hover]:[background-image:none]",
  ].join(" "),
  "tv_sponsor_multiselect_arrow": [
    "tv-sponsor-multiselect-arrow", "tw:grid", "tw:w-[30px]", "tw:h-[30px]",
    "tw:[flex:0_0_auto]", "tw:place-items-center", "tw:pt-[0]", "tw:pr-[0]",
    "tw:pb-[0]", "tw:pl-[0]", "tw:border-t-[length:0]", "tw:[border-top-style:none]",
    "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[6px]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:text-[color:var(--muted)]", "tw:hover:bg-[color:var(--brand-soft)]", "tw:hover:[background-image:none]",
    "tw:hover:text-[color:var(--brand-strong)]", "tw:[&_svg]:w-[18px]", "tw:[&_svg]:h-[18px]", "tw:[&_svg]:[transition:transform_160ms_var(--ease-standard)]",
    "tw:[&[aria-expanded=true]_svg]:[transform:rotate(180deg)]",
  ].join(" "),
  "tv_sponsor_multiselect_options": [
    "tv-sponsor-multiselect-options", "tw:relative", "tw:z-[1]", "tw:grid",
    "tw:gap-y-[3px]", "tw:gap-x-[3px]", "tw:max-h-[232px]", "tw:mt-[5px]",
    "tw:[overflow-x:auto]", "tw:[overflow-y:auto]", "tw:pt-[5px]", "tw:pr-[5px]",
    "tw:pb-[5px]", "tw:pl-[5px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[9px]", "tw:bg-[color:var(--surface)]",
    "tw:[background-image:none]", "tw:[box-shadow:0_10px_20px_rgb(15_33_58_/_.1)]", "tw:[&_button]:flex", "tw:[&_button]:justify-between",
    "tw:[&_button]:items-center", "tw:[&_button]:gap-y-[12px]", "tw:[&_button]:gap-x-[12px]", "tw:[&_button]:w-[100%]",
    "tw:[&_button]:min-h-[38px]", "tw:[&_button]:pt-[8px]", "tw:[&_button]:pr-[10px]", "tw:[&_button]:pb-[8px]",
    "tw:[&_button]:pl-[10px]", "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]",
    "tw:[&_button]:border-r-[length:0]", "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:0]",
    "tw:[&_button]:[border-bottom-style:none]", "tw:[&_button]:border-b-[color:currentColor]", "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]",
    "tw:[&_button]:border-l-[color:currentColor]", "tw:[&_button]:rounded-[6px]", "tw:[&_button]:bg-[color:transparent]", "tw:[&_button]:[background-image:none]",
    "tw:[&_button]:text-[color:var(--text)]", "tw:[&_button]:text-left", "tw:[&_button:hover]:bg-[color:var(--brand-soft)]", "tw:[&_button:hover]:[background-image:none]",
    "tw:[&_button:hover]:text-[color:var(--brand-strong)]", "tw:[&_small]:text-[color:var(--muted)]", "tw:[&_small]:text-[.7rem]", "tw:[&_p]:mt-[7px]",
    "tw:[&_p]:mr-[8px]", "tw:[&_p]:mb-[7px]", "tw:[&_p]:ml-[8px]", "tw:[&_p]:text-[color:var(--muted)]",
    "tw:[&_p]:text-[.78rem]",
  ].join(" "),
} as const;
