import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "showcase_shell_showcase_shell_empty": [
    "showcase-shell", "showcase-shell-empty", "tw:grid", "tw:gap-y-[18px]",
    "tw:gap-x-[18px]", "tw:pt-[28px]", "tw:viewport-760:pt-[18px]", "tw:pr-[28px]",
    "tw:viewport-760:pr-[18px]", "tw:pb-[28px]", "tw:viewport-760:pb-[18px]", "tw:pl-[28px]",
    "tw:viewport-760:pl-[18px]", "tw:rounded-[30px]", "tw:viewport-760:rounded-[24px]", "tw:bg-[color:transparent]",
    "tw:[background-image:radial-gradient(circle_at_top_left,_rgba(255,_191,_71,_0.18),_transparent_20%),_radial-gradient(circle_at_bottom_right,_rgba(63,_160,_255,_0.18),_transparent_28%),_linear-gradient(135deg,_#0f1724_0%,_#12263d_48%,_#173c60_100%)]", "tw:[box-shadow:0_26px_56px_rgba(11,_24,_42,_0.24)]", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]",
    "tw:min-h-[420px]", "tw:[align-content:start]",
  ].join(" "),
  "showcase_hero": [
    "showcase-hero", "tw:grid", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
    "tw:text-[color:#f4f9ff]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]",
    "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[clamp(2.3rem,_4vw,_4.6rem)]", "tw:[&_h2]:leading-[0.95]", "tw:[&_h2]:tracking-[-0.05em]",
    "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
    "tw:[&_p]:max-w-[820px]", "tw:[&_p]:text-[color:rgba(228,_239,_251,_0.82)]", "tw:[&_p]:text-[1rem]",
  ].join(" "),
  "showcase_kicker_row": [
    "showcase-kicker-row", "tw:flex", "tw:items-center", "tw:justify-between",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:flex-wrap",
  ].join(" "),
  "showcase_kicker": [
    "showcase-kicker", "tw:inline-flex", "tw:items-center", "tw:min-h-[34px]",
    "tw:pt-[0]", "tw:pr-[14px]", "tw:pb-[0]", "tw:pl-[14px]",
    "tw:rounded-[999px]", "tw:text-[0.8rem]", "tw:font-[800]", "tw:tracking-[0.08em]",
    "tw:uppercase", "tw:bg-[color:rgba(255,_255,_255,_0.12)]", "tw:[background-image:none]", "tw:text-[color:#f7fbff]",
  ].join(" "),
  "showcase_badge": [
    "showcase-badge", "tw:inline-flex", "tw:items-center", "tw:min-h-[34px]",
    "tw:pt-[0]", "tw:pr-[14px]", "tw:pb-[0]", "tw:pl-[14px]",
    "tw:rounded-[999px]", "tw:text-[0.8rem]", "tw:font-[800]", "tw:tracking-[0.08em]",
    "tw:uppercase", "tw:bg-[color:rgba(255,_191,_71,_0.16)]", "tw:[background-image:none]", "tw:text-[color:#ffd88a]",
  ].join(" "),
  "showcase_empty_card": [
    "showcase-empty-card", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:max-w-[760px]", "tw:pt-[28px]", "tw:viewport-760:pt-[18px]", "tw:pr-[28px]",
    "tw:viewport-760:pr-[18px]", "tw:pb-[28px]", "tw:viewport-760:pb-[18px]", "tw:pl-[28px]",
    "tw:viewport-760:pl-[18px]", "tw:rounded-[24px]", "tw:bg-[color:rgba(255,_255,_255,_0.08)]", "tw:[background-image:none]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgba(255,_255,_255,_0.08)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:rgba(255,_255,_255,_0.08)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgba(255,_255,_255,_0.08)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgba(255,_255,_255,_0.08)]",
    "tw:text-[color:#eff7ff]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:rgba(228,_239,_251,_0.8)]",
  ].join(" "),
  "showcase_shell": [
    "showcase-shell", "tw:grid", "tw:gap-y-[18px]", "tw:gap-x-[18px]",
    "tw:pt-[28px]", "tw:viewport-760:pt-[18px]", "tw:pr-[28px]", "tw:viewport-760:pr-[18px]",
    "tw:pb-[28px]", "tw:viewport-760:pb-[18px]", "tw:pl-[28px]", "tw:viewport-760:pl-[18px]",
    "tw:rounded-[30px]", "tw:viewport-760:rounded-[24px]", "tw:bg-[color:transparent]", "tw:[background-image:radial-gradient(circle_at_top_left,_rgba(255,_191,_71,_0.18),_transparent_20%),_radial-gradient(circle_at_bottom_right,_rgba(63,_160,_255,_0.18),_transparent_28%),_linear-gradient(135deg,_#0f1724_0%,_#12263d_48%,_#173c60_100%)]",
    "tw:[box-shadow:0_26px_56px_rgba(11,_24,_42,_0.24)]", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]",
  ].join(" "),
  "showcase_stage": [
    "showcase-stage", "tw:grid", "tw:gap-y-[22px]", "tw:gap-x-[22px]",
    "tw:pt-[clamp(22px,_3vw,_34px)]", "tw:viewport-760:pt-[18px]", "tw:pr-[clamp(22px,_3vw,_34px)]", "tw:viewport-760:pr-[18px]",
    "tw:pb-[clamp(22px,_3vw,_34px)]", "tw:viewport-760:pb-[18px]", "tw:pl-[clamp(22px,_3vw,_34px)]", "tw:viewport-760:pl-[18px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgba(255,_255,_255,_0.08)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:rgba(255,_255,_255,_0.08)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgba(255,_255,_255,_0.08)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgba(255,_255,_255,_0.08)]",
    "tw:rounded-[28px]", "tw:bg-[color:rgba(7,_16,_28,_0.34)]", "tw:[background-image:linear-gradient(145deg,_rgba(255,_255,_255,_0.12),_rgba(255,_255,_255,_0.04))]", "tw:[backdrop-filter:blur(14px)]",
  ].join(" "),
  "showcase_stage_head": [
    "showcase-stage-head", "tw:flex", "tw:viewport-760:grid", "tw:items-start",
    "tw:justify-between", "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:[&_h3]:mt-[0]",
    "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]", "tw:[&_h3]:text-[color:#ffffff]",
    "tw:[&_h3]:text-[clamp(1.8rem,_3vw,_3rem)]", "tw:[&_h3]:leading-[1]", "tw:[&_h3]:tracking-[-0.04em]",
  ].join(" "),
  "showcase_stage_label": [
    "showcase-stage-label", "tw:inline-flex", "tw:items-center", "tw:min-h-[34px]",
    "tw:pt-[0]", "tw:pr-[14px]", "tw:pb-[0]", "tw:pl-[14px]",
    "tw:rounded-[999px]", "tw:text-[0.8rem]", "tw:font-[800]", "tw:tracking-[0.08em]",
    "tw:uppercase", "tw:bg-[color:rgba(63,_160,_255,_0.16)]", "tw:[background-image:none]", "tw:text-[color:#9dd1ff]",
    "tw:mb-[10px]",
  ].join(" "),
  "showcase_order": [
    "showcase-order", "tw:inline-flex", "tw:items-center", "tw:min-h-[34px]",
    "tw:pt-[0]", "tw:pr-[14px]", "tw:pb-[0]", "tw:pl-[14px]",
    "tw:rounded-[999px]", "tw:text-[0.8rem]", "tw:font-[800]", "tw:tracking-[0.08em]",
    "tw:uppercase", "tw:bg-[color:rgba(255,_255,_255,_0.08)]", "tw:[background-image:none]", "tw:text-[color:rgba(236,_244,_252,_0.78)]",
  ].join(" "),
  "showcase_versus": [
    "showcase-versus", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)_auto_minmax(0,_1fr)]", "tw:viewport-1120:grid-cols-[1fr]",
    "tw:gap-y-[20px]", "tw:gap-x-[20px]", "tw:items-center",
  ].join(" "),
  "showcase_team_card": [
    "showcase-team-card", "tw:grid", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
    "tw:min-h-[220px]", "tw:[align-content:center]", "tw:pt-[26px]", "tw:viewport-760:pt-[18px]",
    "tw:pr-[26px]", "tw:viewport-760:pr-[18px]", "tw:pb-[26px]", "tw:viewport-760:pb-[18px]",
    "tw:pl-[26px]", "tw:viewport-760:pl-[18px]", "tw:rounded-[24px]", "tw:bg-[color:rgba(255,_255,_255,_0.04)]",
    "tw:[background-image:linear-gradient(180deg,_rgba(255,_255,_255,_0.16),_rgba(255,_255,_255,_0.05))]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgba(255,_255,_255,_0.08)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgba(255,_255,_255,_0.08)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgba(255,_255,_255,_0.08)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgba(255,_255,_255,_0.08)]", "tw:[box-shadow:inset_0_1px_0_rgba(255,_255,_255,_0.06)]", "tw:[&_strong]:text-[color:#ffffff]", "tw:[&_strong]:text-[clamp(1.8rem,_3vw,_3.2rem)]",
    "tw:[&_strong]:leading-[1]", "tw:[&_strong]:tracking-[-0.04em]",
  ].join(" "),
  "showcase_team_caption": [
    "showcase-team-caption", "tw:text-[color:rgba(202,_220,_239,_0.72)]", "tw:text-[0.86rem]", "tw:font-[700]",
    "tw:tracking-[0.08em]", "tw:uppercase",
  ].join(" "),
  "showcase_versus_badge": [
    "showcase-versus-badge", "tw:grid", "tw:place-items-center", "tw:w-[clamp(74px,_8vw,_110px)]",
    "tw:[aspect-ratio:1]", "tw:rounded-[999px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(135deg,_#ffc65b,_#ff9e3d)]",
    "tw:text-[color:#172134]", "tw:text-[clamp(1.2rem,_2vw,_1.8rem)]", "tw:font-[900]", "tw:tracking-[0.12em]",
    "tw:[box-shadow:0_16px_34px_rgba(255,_165,_63,_0.28)]",
  ].join(" "),
  "showcase_meta_grid": [
    "showcase-meta-grid", "tw:grid", "tw:gap-y-[16px]", "tw:gap-x-[16px]",
    "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-1120:grid-cols-[1fr]",
  ].join(" "),
  "showcase_meta_card": [
    "showcase-meta-card", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:pt-[18px]", "tw:pr-[20px]", "tw:pb-[18px]", "tw:pl-[20px]",
    "tw:rounded-[20px]", "tw:bg-[color:rgba(255,_255,_255,_0.06)]", "tw:[background-image:none]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:rgba(255,_255,_255,_0.08)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:rgba(255,_255,_255,_0.08)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgba(255,_255,_255,_0.08)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgba(255,_255,_255,_0.08)]", "tw:[&_span]:text-[color:rgba(202,_220,_239,_0.72)]",
    "tw:[&_span]:text-[0.82rem]", "tw:[&_span]:font-[700]", "tw:[&_span]:tracking-[0.08em]", "tw:[&_span]:uppercase",
    "tw:[&_strong]:text-[color:#ffffff]", "tw:[&_strong]:text-[1.2rem]", "tw:[&_strong]:tracking-[-0.03em]",
  ].join(" "),
  "showcase_controls": [
    "showcase-controls", "tw:flex", "tw:viewport-760:grid", "tw:items-center",
    "tw:justify-between", "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:flex-wrap",
  ].join(" "),
  "button": sharedUtilities.button,
  "showcase_dots": [
    "showcase-dots", "tw:flex", "tw:items-center", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]", "tw:flex-wrap", "tw:justify-center",
  ].join(" "),
  "showcase_dot": [
    "showcase-dot", "tw:w-[12px]", "tw:h-[12px]", "tw:pt-[0]",
    "tw:pr-[0]", "tw:pb-[0]", "tw:pl-[0]", "tw:border-t-[length:medium]",
    "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:medium]", "tw:[border-right-style:none]",
    "tw:border-r-[color:currentColor]", "tw:border-b-[length:medium]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]",
    "tw:border-l-[length:medium]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[999px]",
    "tw:bg-[color:rgba(255,_255,_255,_0.22)]", "tw:[background-image:none]", "tw:[transition:transform_180ms_var(--ease-standard),_background_180ms_var(--ease-standard)]",
  ].join(" "),
  "showcase_dot_active": [
    "showcase-dot-active", "tw:bg-[color:#ffc65b]", "tw:[background-image:none]", "tw:[transform:scale(1.25)]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "showcase_filmstrip": [
    "showcase-filmstrip", "tw:grid", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:grid-cols-[repeat(auto-fit,_minmax(220px,_1fr))]", "tw:viewport-760:grid-cols-[1fr]",
  ].join(" "),
  "showcase_thumb": [
    "showcase-thumb", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:pt-[16px]", "tw:pr-[16px]", "tw:pb-[16px]", "tw:pl-[16px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgba(255,_255,_255,_0.08)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:rgba(255,_255,_255,_0.08)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgba(255,_255,_255,_0.08)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgba(255,_255,_255,_0.08)]",
    "tw:rounded-[18px]", "tw:bg-[color:rgba(255,_255,_255,_0.05)]", "tw:[background-image:none]", "tw:text-[color:#eef6ff]",
    "tw:text-left", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard)]", "tw:[&_span]:text-[color:rgba(202,_220,_239,_0.72)]", "tw:[&_span]:text-[0.78rem]",
    "tw:[&_span]:font-[700]", "tw:[&_span]:tracking-[0.08em]", "tw:[&_span]:uppercase", "tw:[&_strong]:leading-[1.35]",
    "tw:hover:[transform:translateY(-2px)]", "tw:hover:border-t-[color:rgba(255,_198,_91,_0.44)]", "tw:hover:border-r-[color:rgba(255,_198,_91,_0.44)]", "tw:hover:border-b-[color:rgba(255,_198,_91,_0.44)]",
    "tw:hover:border-l-[color:rgba(255,_198,_91,_0.44)]", "tw:hover:bg-[color:rgba(255,_255,_255,_0.09)]", "tw:hover:[background-image:none]",
  ].join(" "),
  "showcase_thumb_active": [
    "showcase-thumb-active", "tw:[transform:translateY(-2px)]", "tw:border-t-[color:rgba(255,_198,_91,_0.44)]", "tw:border-r-[color:rgba(255,_198,_91,_0.44)]",
    "tw:border-b-[color:rgba(255,_198,_91,_0.44)]", "tw:border-l-[color:rgba(255,_198,_91,_0.44)]", "tw:bg-[color:rgba(255,_255,_255,_0.09)]", "tw:[background-image:none]",
  ].join(" "),
} as const;
