ALTER TABLE "Arena"
  ADD COLUMN "scheduleStartMinute" INTEGER NOT NULL DEFAULT 360,
  ADD COLUMN "scheduleEndMinute" INTEGER NOT NULL DEFAULT 1380,
  ADD COLUMN "scheduleSlotMinutes" INTEGER NOT NULL DEFAULT 30;
