import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "command_action_icon": [
    "command-action-icon", "tw:w-[14px]", "tw:h-[14px]", "tw:[fill:none]",
    "tw:[stroke:currentColor]", "tw:[stroke-linecap:round]", "tw:[stroke-width:2.4]",
  ].join(" "),
  "command_card_command_card_clickable": [
    "command-card", "command-card-clickable", "tw:flex", "tw:flex-col",
    "tw:justify-between", "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:min-h-[205px]",
    "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]", "tw:pl-[14px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]",
    "tw:rounded-[var(--radius-control)]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(145deg,_var(--panel-muted),_var(--panel))]", "tw:[box-shadow:0_8px_18px_rgba(28,_54,_89,_.06)]",
    "tw:[&_strong]:block", "tw:[&_span]:block", "tw:[&_span]:text-[color:var(--muted)]", "tw:[&_span]:text-[.78rem]",
    "tw:[&_small]:block", "tw:[&_small]:text-[color:var(--muted)]", "tw:[&_small]:text-[.78rem]", "tw:[&_header]:flex",
    "tw:[&_header]:justify-between", "tw:[&_header]:gap-y-[8px]", "tw:[&_header]:gap-x-[8px]", "tw:[&_header_small]:text-right",
    "tw:[&_footer]:grid", "tw:[&_footer]:gap-y-[8px]", "tw:[&_footer]:gap-x-[8px]", "tw:[&_footer]:pt-[9px]",
    "tw:[&_footer]:border-t-[length:1px]", "tw:[&_footer]:[border-top-style:solid]", "tw:[&_footer]:border-t-[color:var(--line)]", "tw:[&_footer_>_div:first-child]:flex",
    "tw:[&_footer_>_div:first-child]:items-end", "tw:[&_footer_>_div:first-child]:justify-between", "tw:[&_footer_>_div:first-child_span]:font-[700]", "tw:[&_footer_>_div:first-child_strong]:text-[.94rem]",
    "tw:viewport-760:items-start", "tw:viewport-760:[&_>_div:last-child]:[justify-items:start]", "tw:cursor-pointer", "tw:hover:border-t-[color:var(--brand)]",
    "tw:hover:border-r-[color:var(--brand)]", "tw:hover:border-b-[color:var(--brand)]", "tw:hover:border-l-[color:var(--brand)]", "tw:hover:[box-shadow:0_10px_24px_rgb(15_23_42_/_.1)]",
  ].join(" "),
  "command_card_header_meta": [
    "command-card-header-meta", "tw:grid", "tw:[justify-items:end]", "tw:gap-y-[5px]",
    "tw:gap-x-[5px]",
  ].join(" "),
  "command_new_request_label": [
    "command-new-request-label", "tw:pt-[3px]", "tw:pr-[7px]", "tw:pb-[3px]",
    "tw:pl-[7px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#efba47]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#efba47]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#efba47]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#efba47]", "tw:rounded-[5px]", "tw:text-[color:#8a5700]", "tw:bg-[color:#fff4d9]",
    "tw:[background-image:none]", "tw:text-[.62rem]", "tw:font-[850]", "tw:leading-[1.2]",
    "tw:whitespace-nowrap",
  ].join(" "),
  "command_items": [
    "command-items", "tw:grid", "tw:gap-y-[4px]", "tw:gap-x-[4px]",
    "tw:min-h-[52px]",
  ].join(" "),
  "command_item": [
    "command-item", "tw:relative", "tw:flex", "tw:items-center",
    "tw:justify-between", "tw:gap-y-[7px]", "tw:gap-x-[7px]", "tw:pt-[5px]",
    "tw:pr-[6px]", "tw:pb-[5px]", "tw:pl-[6px]", "tw:rounded-[6px]",
    "tw:bg-[color:color-mix(in_srgb,_var(--panel)_80%,_var(--brand-soft))]", "tw:[background-image:none]", "tw:text-[color:var(--text)]", "tw:text-[.76rem]",
    "tw:[&_span]:text-[color:inherit]", "tw:[&_strong]:text-[color:inherit]", "tw:[&_b]:text-[color:var(--brand-strong)]", "tw:[&:hover_.command-item-controls]:flex",
    "tw:[&:focus-within_.command-item-controls]:flex",
  ].join(" "),
  "command_item_controls": [
    "command-item-controls", "tw:absolute", "tw:right-[4px]", "tw:top-[50%]",
    "tw:hidden", "tw:gap-y-[3px]", "tw:gap-x-[3px]", "tw:pt-[3px]",
    "tw:pr-[3px]", "tw:pb-[3px]", "tw:pl-[3px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[6px]",
    "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:[box-shadow:0_6px_14px_rgba(20,_38,_63,_.15)]", "tw:[transform:translateY(-50%)]",
    "tw:[&_button]:w-[21px]", "tw:[&_button]:h-[21px]", "tw:[&_button]:pt-[0]", "tw:[&_button]:pr-[0]",
    "tw:[&_button]:pb-[0]", "tw:[&_button]:pl-[0]", "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]",
    "tw:[&_button]:border-t-[color:currentColor]", "tw:[&_button]:border-r-[length:0]", "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]",
    "tw:[&_button]:border-b-[length:0]", "tw:[&_button]:[border-bottom-style:none]", "tw:[&_button]:border-b-[color:currentColor]", "tw:[&_button]:border-l-[length:0]",
    "tw:[&_button]:[border-left-style:none]", "tw:[&_button]:border-l-[color:currentColor]", "tw:[&_button]:rounded-[5px]", "tw:[&_button]:bg-[color:var(--brand)]",
    "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:#fff]", "tw:[&_button]:font-[800]",
  ].join(" "),
  "command_items_empty": [
    "command-items-empty", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-[color:var(--muted)]", "tw:text-[.76rem]",
  ].join(" "),
  "command_card_actions": [
    "command-card-actions", "tw:flex", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:[&_.button]:[flex:1]", "tw:[&_.button]:pt-[6px]", "tw:[&_.button]:pr-[8px]", "tw:[&_.button]:pb-[6px]",
    "tw:[&_.button]:pl-[8px]", "tw:[&_.button]:text-[.74rem]",
  ].join(" "),
  "button": sharedUtilities.button,
  "button_button_success": [
    "button", "button-success", "tw:inline-flex", "tw:items-center",
    "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:min-h-[36px]",
    "tw:pt-[0]", "tw:pr-[12px]", "tw:pb-[0]", "tw:pl-[12px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#16803c]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#16803c]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#16803c]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#16803c]",
    "tw:rounded-[var(--radius-control)]", "tw:bg-[color:#238b45]", "tw:[background-image:none]", "tw:text-[color:#fff]",
    "tw:text-[0.86rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--line-strong)]", "tw:hover:border-r-[color:var(--line-strong)]",
    "tw:hover:border-b-[color:var(--line-strong)]", "tw:hover:border-l-[color:var(--line-strong)]", "tw:hover:[transform:translateY(-1px)]", "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]",
    "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]", "tw:[&:active]:[box-shadow:none]",
    "tw:hover:bg-[color:#176f36]", "tw:hover:[background-image:none]",
  ].join(" "),
  "command_card_message": [
    "command-card-message", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-[color:#b42318]", "tw:text-[.72rem]",
  ].join(" "),
  "command_modal_backdrop": sharedUtilities.commandModalBackdrop,
  "command_details_modal": [
    "command-details-modal", "tw:w-[min(100%,_620px)]", "tw:grid", "tw:gap-y-[16px]",
    "tw:gap-x-[16px]", "tw:max-h-[calc(100vh_-_44px)]", "tw:[overflow-x:auto]", "tw:[overflow-y:auto]",
    "tw:pt-[20px]", "tw:pr-[20px]", "tw:pb-[20px]", "tw:pl-[20px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(255_255_255_/_.7)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(255_255_255_/_.7)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgb(255_255_255_/_.7)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(255_255_255_/_.7)]",
    "tw:rounded-[14px]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:[box-shadow:0_26px_80px_rgb(15_23_42_/_.34)]",
    "tw:[&_>_header]:flex", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:items-center", "tw:[&_>_header]:gap-y-[12px]",
    "tw:[&_>_header]:gap-x-[12px]", "tw:[&_>_header]:pb-[14px]", "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]",
    "tw:[&_>_header]:border-b-[color:var(--line)]", "tw:[&_>_footer]:flex", "tw:[&_>_footer]:justify-between", "tw:[&_>_footer]:items-center",
    "tw:[&_>_footer]:gap-y-[12px]", "tw:[&_>_footer]:gap-x-[12px]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]",
    "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]",
    "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_header_span]:block", "tw:[&_header_span]:mb-[3px]",
    "tw:[&_header_span]:text-[color:var(--brand)]", "tw:[&_header_span]:text-[.68rem]", "tw:[&_header_span]:font-[800]", "tw:[&_header_span]:tracking-[.1em]",
    "tw:[&_header_p]:mt-[5px]", "tw:[&_header_p]:text-[color:var(--muted)]", "tw:[&_header_p]:text-[.78rem]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "command_details_items": [
    "command-details-items", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:[&_h3]:text-[.9rem]", "tw:[&_.command-item]:grid", "tw:[&_.command-item]:grid-cols-[minmax(0,_1fr)_auto_auto]", "tw:[&_.command-item]:items-center",
    "tw:[&_.command-item]:gap-y-[10px]", "tw:[&_.command-item]:gap-x-[10px]", "tw:[&_.command-item]:pt-[9px]", "tw:[&_.command-item]:pr-[0]",
    "tw:[&_.command-item]:pb-[9px]", "tw:[&_.command-item]:pl-[0]", "tw:[&_.command-item]:border-b-[length:1px]", "tw:[&_.command-item]:[border-bottom-style:solid]",
    "tw:[&_.command-item]:border-b-[color:var(--line)]",
  ].join(" "),
  "command_details_items_head": [
    "command-details-items-head", "tw:flex", "tw:items-center", "tw:justify-between",
    "tw:gap-y-[10px]", "tw:gap-x-[10px]",
  ].join(" "),
  "button_button_small_button_primary": sharedUtilities.buttonButtonSmallButtonPrimary,
  "command_item_controls_command_details_item_controls": [
    "command-item-controls", "command-details-item-controls", "tw:static", "tw:right-[4px]",
    "tw:top-[50%]", "tw:flex", "tw:gap-y-[3px]", "tw:gap-x-[3px]",
    "tw:pt-[0]", "tw:pr-[0]", "tw:pb-[0]", "tw:pl-[0]",
    "tw:border-t-[length:0]", "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]",
    "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]",
    "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]",
    "tw:rounded-[0]", "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:[box-shadow:none]",
    "tw:[transform:none]", "tw:[&_button]:w-[21px]", "tw:[&_button]:h-[21px]", "tw:[&_button]:pt-[0]",
    "tw:[&_button]:pr-[0]", "tw:[&_button]:pb-[0]", "tw:[&_button]:pl-[0]", "tw:[&_button]:border-t-[length:0]",
    "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]", "tw:[&_button]:border-r-[length:0]", "tw:[&_button]:[border-right-style:none]",
    "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:0]", "tw:[&_button]:[border-bottom-style:none]", "tw:[&_button]:border-b-[color:currentColor]",
    "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]", "tw:[&_button]:border-l-[color:currentColor]", "tw:[&_button]:rounded-[5px]",
    "tw:[&_button]:bg-[color:var(--brand)]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:#fff]", "tw:[&_button]:font-[800]",
  ].join(" "),
  "command_details_empty": [
    "command-details-empty", "tw:grid", "tw:[justify-items:start]", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]", "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]",
    "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:dashed]", "tw:border-t-[color:#b8cde1]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:dashed]", "tw:border-r-[color:#b8cde1]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:dashed]", "tw:border-b-[color:#b8cde1]", "tw:border-l-[length:1px]", "tw:[border-left-style:dashed]",
    "tw:border-l-[color:#b8cde1]", "tw:rounded-[9px]", "tw:bg-[color:#f8fbff]", "tw:[background-image:none]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "command_zero_confirm_modal": [
    "command-zero-confirm-modal", "tw:w-[min(100%,_560px)]", "tw:grid", "tw:gap-y-[16px]",
    "tw:gap-x-[16px]", "tw:pt-[20px]", "tw:pr-[20px]", "tw:pb-[20px]",
    "tw:pl-[20px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(255_255_255_/_.7)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(255_255_255_/_.7)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(255_255_255_/_.7)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgb(255_255_255_/_.7)]", "tw:rounded-[14px]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]",
    "tw:[box-shadow:0_26px_80px_rgb(15_23_42_/_.34)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:items-center",
    "tw:[&_>_header]:gap-y-[12px]", "tw:[&_>_header]:gap-x-[12px]", "tw:[&_>_header]:pb-[14px]", "tw:[&_>_header]:border-b-[length:1px]",
    "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:var(--line)]", "tw:[&_>_footer]:flex", "tw:[&_>_footer]:justify-between",
    "tw:[&_>_footer]:items-center", "tw:[&_>_footer]:gap-y-[12px]", "tw:[&_>_footer]:gap-x-[12px]", "tw:[&_header_span]:block",
    "tw:[&_header_span]:mb-[3px]", "tw:[&_header_span]:text-[color:var(--brand)]", "tw:[&_header_span]:text-[.68rem]", "tw:[&_header_span]:font-[800]",
    "tw:[&_header_span]:tracking-[.1em]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]",
    "tw:[&_h2]:ml-[0]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_>_p]:pt-[14px]", "tw:[&_>_p]:pr-[14px]", "tw:[&_>_p]:pb-[14px]",
    "tw:[&_>_p]:pl-[14px]", "tw:[&_>_p]:border-t-[length:1px]", "tw:[&_>_p]:[border-top-style:solid]", "tw:[&_>_p]:border-t-[color:#f2c778]",
    "tw:[&_>_p]:border-r-[length:1px]", "tw:[&_>_p]:[border-right-style:solid]", "tw:[&_>_p]:border-r-[color:#f2c778]", "tw:[&_>_p]:border-b-[length:1px]",
    "tw:[&_>_p]:[border-bottom-style:solid]", "tw:[&_>_p]:border-b-[color:#f2c778]", "tw:[&_>_p]:border-l-[length:1px]", "tw:[&_>_p]:[border-left-style:solid]",
    "tw:[&_>_p]:border-l-[color:#f2c778]", "tw:[&_>_p]:rounded-[10px]", "tw:[&_>_p]:bg-[color:#fff9eb]", "tw:[&_>_p]:[background-image:none]",
    "tw:[&_>_p]:text-[color:#75551d]", "tw:[&_>_p]:leading-[1.5]",
  ].join(" "),
  "command_product_modal": [
    "command-product-modal", "tw:w-[min(calc(100vw_-_44px),_1080px)]", "tw:viewport-760:w-[100%]", "tw:max-h-[calc(100vh_-_44px)]",
    "tw:[overflow-x:auto]", "tw:[overflow-y:auto]", "tw:pt-[20px]", "tw:viewport-760:pt-[15px]",
    "tw:pr-[20px]", "tw:viewport-760:pr-[15px]", "tw:pb-[20px]", "tw:viewport-760:pb-[15px]",
    "tw:pl-[20px]", "tw:viewport-760:pl-[15px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(255_255_255_/_.7)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(255_255_255_/_.7)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(255_255_255_/_.7)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(255_255_255_/_.7)]", "tw:rounded-[14px]", "tw:bg-[color:var(--panel)]",
    "tw:[background-image:none]", "tw:[box-shadow:0_26px_80px_rgb(15_23_42_/_.34)]", "tw:[animation:rise-in_180ms_var(--ease-standard)]", "tw:[&_>_header]:flex",
    "tw:[&_>_header]:justify-between", "tw:[&_>_header]:items-center", "tw:[&_>_header]:gap-y-[12px]", "tw:[&_>_header]:gap-x-[12px]",
    "tw:[&_>_header]:pb-[14px]", "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:var(--line)]",
    "tw:[&_>_footer]:flex", "tw:[&_>_footer]:justify-between", "tw:[&_>_footer]:items-center", "tw:viewport-760:[&_>_footer]:items-stretch",
    "tw:[&_>_footer]:gap-y-[12px]", "tw:[&_>_footer]:gap-x-[12px]", "tw:[&_>_footer]:pt-[13px]", "tw:[&_>_footer]:border-t-[length:1px]",
    "tw:[&_>_footer]:[border-top-style:solid]", "tw:[&_>_footer]:border-t-[color:var(--line)]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]",
    "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]",
    "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]", "tw:[&_header_span]:block", "tw:[&_header_span]:mb-[3px]",
    "tw:[&_header_span]:text-[color:var(--brand)]", "tw:[&_header_span]:text-[.68rem]", "tw:[&_header_span]:font-[800]", "tw:[&_header_span]:tracking-[.1em]",
    "tw:[&_>_footer_>_div:last-child]:flex", "tw:[&_>_footer_>_div:last-child]:flex-wrap", "tw:[&_>_footer_>_div:last-child]:justify-end", "tw:viewport-760:[&_>_footer_>_div:last-child]:[justify-content:stretch]",
    "tw:[&_>_footer_>_div:last-child]:gap-y-[8px]", "tw:[&_>_footer_>_div:last-child]:gap-x-[8px]", "tw:viewport-760:[&_>_footer]:flex-col", "tw:viewport-760:[&_>_footer_>_div:last-child_.button]:[flex:1]",
  ].join(" "),
  "command_product_toolbar": [
    "command-product-toolbar", "tw:grid", "tw:gap-y-[11px]", "tw:gap-x-[11px]",
    "tw:pt-[16px]", "tw:pr-[0]", "tw:pb-[12px]", "tw:pl-[0]",
  ].join(" "),
  "command_product_search": [
    "command-product-search", "tw:grid", "tw:gap-y-[5px]", "tw:gap-x-[5px]",
    "tw:text-[color:var(--muted)]", "tw:text-[.72rem]", "tw:font-[800]", "tw:[&_input]:min-h-[42px]",
    "tw:[&_input]:pt-[8px]", "tw:[&_input]:pr-[11px]", "tw:[&_input]:pb-[8px]", "tw:[&_input]:pl-[11px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line-strong)]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line-strong)]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:var(--line-strong)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:var(--line-strong)]",
    "tw:[&_input]:rounded-[var(--radius-control)]", "tw:[&_input]:bg-[color:var(--panel-muted)]", "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:var(--text)]",
  ].join(" "),
  "command_product_categories": [
    "command-product-categories", "tw:flex", "tw:flex-wrap", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:[&_button]:min-h-[30px]", "tw:[&_button]:pt-[5px]", "tw:[&_button]:pr-[10px]",
    "tw:[&_button]:pb-[5px]", "tw:[&_button]:pl-[10px]", "tw:[&_button]:border-t-[length:1px]", "tw:[&_button]:[border-top-style:solid]",
    "tw:[&_button]:border-t-[color:var(--line)]", "tw:[&_button]:border-r-[length:1px]", "tw:[&_button]:[border-right-style:solid]", "tw:[&_button]:border-r-[color:var(--line)]",
    "tw:[&_button]:border-b-[length:1px]", "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:var(--line)]", "tw:[&_button]:border-l-[length:1px]",
    "tw:[&_button]:[border-left-style:solid]", "tw:[&_button]:border-l-[color:var(--line)]", "tw:[&_button]:rounded-[999px]", "tw:[&_button]:bg-[color:var(--panel)]",
    "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:var(--muted)]", "tw:[&_button]:text-[.74rem]", "tw:[&_button]:font-[750]",
    "tw:[&_button:hover]:border-t-[color:var(--brand)]", "tw:[&_button:hover]:border-r-[color:var(--brand)]", "tw:[&_button:hover]:border-b-[color:var(--brand)]", "tw:[&_button:hover]:border-l-[color:var(--brand)]",
    "tw:[&_button:hover]:bg-[color:var(--brand-soft)]", "tw:[&_button:hover]:[background-image:none]", "tw:[&_button:hover]:text-[color:var(--brand-strong)]", "tw:[&_.command-product-category-active]:border-t-[color:var(--brand)]",
    "tw:[&_.command-product-category-active]:border-r-[color:var(--brand)]", "tw:[&_.command-product-category-active]:border-b-[color:var(--brand)]", "tw:[&_.command-product-category-active]:border-l-[color:var(--brand)]", "tw:[&_.command-product-category-active]:bg-[color:var(--brand-soft)]",
    "tw:[&_.command-product-category-active]:[background-image:none]", "tw:[&_.command-product-category-active]:text-[color:var(--brand-strong)]",
  ].join(" "),
  "command_product_kanban_command_product_grid": [
    "command-product-kanban", "command-product-grid", "tw:grid", "tw:items-stretch",
    "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:min-h-[250px]", "tw:pt-[4px]",
    "tw:pr-[0]", "tw:pb-[16px]", "tw:pl-[0]", "tw:grid-cols-[repeat(auto-fill,_minmax(210px,_280px))]",
    "tw:viewport-760:grid-cols-[1fr]", "tw:[overflow-x:visible]", "tw:[overflow-y:visible]",
  ].join(" "),
  "command_product_row": [
    "command-product-row", "tw:flex", "tw:justify-between", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:items-center", "tw:min-h-[114px]", "tw:viewport-760:min-h-[98px]",
    "tw:pt-[13px]", "tw:pr-[13px]", "tw:pb-[13px]", "tw:pl-[13px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]",
    "tw:rounded-[10px]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]", "tw:hover:border-t-[color:#b9d0e7]",
    "tw:hover:border-r-[color:#b9d0e7]", "tw:hover:border-b-[color:#b9d0e7]", "tw:hover:border-l-[color:#b9d0e7]", "tw:hover:bg-[color:#f8fbff]",
    "tw:hover:[background-image:none]", "tw:[&_>_div:first-child]:grid", "tw:[&_>_div:first-child]:min-w-[0]", "tw:[&_>_div:first-child]:gap-y-[3px]",
    "tw:[&_>_div:first-child]:gap-x-[3px]", "tw:[&_strong]:[overflow-x:hidden]", "tw:[&_strong]:[overflow-y:hidden]", "tw:[&_strong]:text-ellipsis",
    "tw:[&_strong]:whitespace-nowrap", "tw:[&_strong]:text-[.84rem]", "tw:[&_span]:text-[color:var(--muted)]", "tw:[&_span]:text-[.7rem]",
    "tw:[&_small]:text-[color:var(--muted)]", "tw:[&_small]:text-[.7rem]", "tw:[&_b]:text-[color:var(--brand-strong)]", "tw:[&_b]:text-[.86rem]",
    "tw:viewport-760:flex-row", "tw:[&.is-zero]:border-t-[color:#e7ad49]", "tw:[&.is-zero]:border-r-[color:#e7ad49]", "tw:[&.is-zero]:border-b-[color:#e7ad49]",
    "tw:[&.is-zero]:border-l-[color:#e7ad49]", "tw:[&.is-zero]:bg-[color:#fff9ec]", "tw:[&.is-zero]:[background-image:none]", "tw:[&.is-negative]:border-t-[color:#dc6666]",
    "tw:[&.is-negative]:border-r-[color:#dc6666]", "tw:[&.is-negative]:border-b-[color:#dc6666]", "tw:[&.is-negative]:border-l-[color:#dc6666]", "tw:[&.is-negative]:bg-[color:#fff2f2]",
    "tw:[&.is-negative]:[background-image:none]", "tw:[&.is-zero_small]:text-[color:#98640b]", "tw:[&.is-zero_small]:font-[800]", "tw:[&.is-negative_small]:text-[color:#b42318]",
    "tw:[&.is-negative_small]:font-[850]",
  ].join(" "),
  "command_product_stepper": [
    "command-product-stepper", "tw:grid", "tw:grid-cols-[32px_32px_32px]", "tw:[flex:0_0_auto]",
    "tw:items-center", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[8px]",
    "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:[&_button]:w-[32px]", "tw:[&_button]:h-[34px]",
    "tw:[&_button]:pt-[0]", "tw:[&_button]:pr-[0]", "tw:[&_button]:pb-[0]", "tw:[&_button]:pl-[0]",
    "tw:[&_button]:border-t-[length:0]", "tw:[&_button]:[border-top-style:none]", "tw:[&_button]:border-t-[color:currentColor]", "tw:[&_button]:border-r-[length:0]",
    "tw:[&_button]:[border-right-style:none]", "tw:[&_button]:border-r-[color:currentColor]", "tw:[&_button]:border-b-[length:0]", "tw:[&_button]:[border-bottom-style:none]",
    "tw:[&_button]:border-b-[color:currentColor]", "tw:[&_button]:border-l-[length:0]", "tw:[&_button]:[border-left-style:none]", "tw:[&_button]:border-l-[color:currentColor]",
    "tw:[&_button]:bg-[color:transparent]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:var(--brand-strong)]", "tw:[&_button]:text-[1.15rem]",
    "tw:[&_button]:font-[850]", "tw:[&_button:hover:not(:disabled)]:bg-[color:var(--brand-soft)]", "tw:[&_button:hover:not(:disabled)]:[background-image:none]", "tw:[&_button:disabled]:text-[color:#a4afbd]",
    "tw:[&_output]:grid", "tw:[&_output]:h-[34px]", "tw:[&_output]:place-items-center", "tw:[&_output]:[border-inline:1px_solid_var(--line)]",
    "tw:[&_output]:text-[color:var(--text)]", "tw:[&_output]:text-[.8rem]", "tw:[&_output]:font-[800]",
  ].join(" "),
  "command_product_selection": [
    "command-product-selection", "tw:grid", "tw:gap-y-[2px]", "tw:gap-x-[2px]",
    "tw:[&_strong]:text-[.82rem]", "tw:[&_span]:text-[color:var(--brand-strong)]", "tw:[&_span]:text-[.8rem]", "tw:[&_span]:font-[800]",
  ].join(" "),
  "command_checkout_modal": [
    "command-checkout-modal", "tw:w-[min(calc(100vw_-_44px),_1120px)]", "tw:viewport-760:w-[100%]", "tw:max-h-[calc(100vh_-_44px)]",
    "tw:[overflow-x:auto]", "tw:[overflow-y:auto]", "tw:pt-[20px]", "tw:viewport-760:pt-[15px]",
    "tw:pr-[20px]", "tw:viewport-760:pr-[15px]", "tw:pb-[20px]", "tw:viewport-760:pb-[15px]",
    "tw:pl-[20px]", "tw:viewport-760:pl-[15px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgb(255_255_255_/_.7)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(255_255_255_/_.7)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(255_255_255_/_.7)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgb(255_255_255_/_.7)]", "tw:rounded-[14px]", "tw:bg-[color:var(--panel)]",
    "tw:[background-image:none]", "tw:[box-shadow:0_26px_80px_rgb(15_23_42_/_.34)]", "tw:[animation:rise-in_180ms_var(--ease-standard)]", "tw:relative",
    "tw:[&_>_header]:flex", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:items-center", "tw:[&_>_header]:gap-y-[12px]",
    "tw:[&_>_header]:gap-x-[12px]", "tw:[&_>_header]:pb-[14px]", "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]",
    "tw:[&_>_header]:border-b-[color:var(--line)]", "tw:[&_>_footer]:flex", "tw:[&_>_footer]:justify-between", "tw:[&_>_footer]:items-center",
    "tw:[&_>_footer]:gap-y-[12px]", "tw:[&_>_footer]:gap-x-[12px]", "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]",
    "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]",
    "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_header_span]:block", "tw:[&_header_span]:mb-[3px]",
    "tw:[&_header_span]:text-[color:var(--brand)]", "tw:[&_header_span]:text-[.68rem]", "tw:[&_header_span]:font-[800]", "tw:[&_header_span]:tracking-[.1em]",
    "tw:[&_>_footer_>_div]:flex", "tw:[&_>_footer_>_div]:flex-wrap", "tw:[&_>_footer_>_div]:gap-y-[8px]", "tw:[&_>_footer_>_div]:gap-x-[8px]",
  ].join(" "),
  "command_checkout_balances": [
    "command-checkout-balances", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-760:grid-cols-[1fr]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:pt-[18px]", "tw:pr-[0]",
    "tw:pb-[0]", "tw:pl-[0]", "tw:[&_article]:grid", "tw:[&_article]:grid-cols-[minmax(0,_1fr)_auto]",
    "tw:[&_article]:items-center", "tw:[&_article]:gap-y-[12px]", "tw:[&_article]:gap-x-[12px]", "tw:[&_article]:pt-[14px]",
    "tw:[&_article]:pr-[16px]", "tw:[&_article]:pb-[14px]", "tw:[&_article]:pl-[16px]", "tw:[&_article]:border-t-[length:1px]",
    "tw:[&_article]:[border-top-style:solid]", "tw:[&_article]:border-t-[color:#d7e4f1]", "tw:[&_article]:border-r-[length:1px]", "tw:[&_article]:[border-right-style:solid]",
    "tw:[&_article]:border-r-[color:#d7e4f1]", "tw:[&_article]:border-b-[length:1px]", "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#d7e4f1]",
    "tw:[&_article]:border-l-[length:1px]", "tw:[&_article]:[border-left-style:solid]", "tw:[&_article]:border-l-[color:#d7e4f1]", "tw:[&_article]:rounded-[12px]",
    "tw:[&_article]:bg-[color:#f8fbff]", "tw:[&_article]:[background-image:none]", "tw:[&_article_>_div]:grid", "tw:[&_article_>_div]:gap-y-[3px]",
    "tw:[&_article_>_div]:gap-x-[3px]", "tw:[&_span]:text-[color:var(--muted)]", "tw:[&_span]:text-[.72rem]", "tw:[&_span]:font-[800]",
    "tw:[&_span]:uppercase", "tw:[&_strong]:text-[color:var(--ink)]", "tw:[&_strong]:text-[1.05rem]", "tw:[&_small]:text-[color:var(--muted)]",
    "tw:[&_small]:text-[.74rem]", "tw:[&_.control-toggle]:[justify-self:end]",
  ].join(" "),
  "command_open_debts_summary": [
    "command-open-debts-summary", "tw:flex", "tw:items-center", "tw:justify-end",
    "tw:viewport-620:justify-between", "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:viewport-620:w-[100%]",
  ].join(" "),
  "control_toggle": sharedUtilities.controlToggle,
  "command_credit_amount": [
    "command-credit-amount", "tw:[grid-column:1_/_-1]", "tw:grid", "tw:grid-cols-[auto_minmax(90px,_130px)]",
    "tw:items-center", "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:text-[color:var(--muted)]",
    "tw:text-[.74rem]", "tw:font-[700]", "tw:[&_input]:min-w-[0]", "tw:[&_input]:min-h-[34px]",
    "tw:[&_input]:pt-[6px]", "tw:[&_input]:pr-[8px]", "tw:[&_input]:pb-[6px]", "tw:[&_input]:pl-[8px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:var(--line)]",
    "tw:[&_input]:rounded-[7px]", "tw:[&_input]:bg-[color:#fff]", "tw:[&_input]:[background-image:none]",
  ].join(" "),
  "command_open_debts": [
    "command-open-debts", "tw:flex", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:pt-[10px]", "tw:pr-[0]", "tw:pb-[10px]", "tw:pl-[0]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:flex-col",
    "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[0]", "tw:[&_h3]:ml-[0]",
    "tw:[&_p]:mt-[3px]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
    "tw:[&_p]:text-[color:var(--muted)]", "tw:[&_p]:text-[.76rem]", "tw:[&_label]:grid", "tw:[&_label]:grid-cols-[auto_minmax(0,_1fr)_auto_auto]",
    "tw:viewport-760:[&_label]:grid-cols-[auto_minmax(0,_1fr)_auto]", "tw:[&_label]:gap-y-[9px]", "tw:[&_label]:gap-x-[9px]", "tw:[&_label]:items-center",
    "tw:[&_label]:pt-[9px]", "tw:[&_label]:pr-[10px]", "tw:[&_label]:pb-[9px]", "tw:[&_label]:pl-[10px]",
    "tw:[&_label]:border-t-[length:1px]", "tw:[&_label]:[border-top-style:solid]", "tw:[&_label]:border-t-[color:var(--line)]", "tw:[&_label]:border-r-[length:1px]",
    "tw:[&_label]:[border-right-style:solid]", "tw:[&_label]:border-r-[color:var(--line)]", "tw:[&_label]:border-b-[length:1px]", "tw:[&_label]:[border-bottom-style:solid]",
    "tw:[&_label]:border-b-[color:var(--line)]", "tw:[&_label]:border-l-[length:1px]", "tw:[&_label]:[border-left-style:solid]", "tw:[&_label]:border-l-[color:var(--line)]",
    "tw:[&_label]:rounded-[8px]", "tw:[&_label]:bg-[color:var(--panel-muted)]", "tw:[&_label]:[background-image:none]", "tw:[&_label]:cursor-pointer",
    "tw:[&_label:has(input:checked)]:border-t-[color:var(--brand)]", "tw:[&_label:has(input:checked)]:border-r-[color:var(--brand)]", "tw:[&_label:has(input:checked)]:border-b-[color:var(--brand)]", "tw:[&_label:has(input:checked)]:border-l-[color:var(--brand)]",
    "tw:[&_label:has(input:checked)]:bg-[color:var(--brand-soft)]", "tw:[&_label:has(input:checked)]:[background-image:none]", "tw:[&_span]:grid", "tw:[&_span]:gap-y-[2px]",
    "tw:[&_span]:gap-x-[2px]", "tw:[&_span]:min-w-[0]", "tw:[&_strong]:[overflow-x:hidden]", "tw:[&_strong]:[overflow-y:hidden]",
    "tw:[&_strong]:text-ellipsis", "tw:[&_strong]:whitespace-nowrap", "tw:[&_strong]:text-[.8rem]", "tw:[&_small]:text-[color:var(--muted)]",
    "tw:[&_small]:text-[.68rem]", "tw:[&_small]:not-italic", "tw:[&_em]:text-[color:var(--brand-strong)]", "tw:[&_em]:text-[.68rem]",
    "tw:[&_em]:not-italic", "tw:[&_em]:font-[700]", "tw:[&_em]:whitespace-nowrap", "tw:[&_b]:text-[.8rem]",
    "tw:[&_b]:whitespace-nowrap", "tw:viewport-760:[&_em]:hidden", "tw:[&_.control-toggle]:[flex:0_0_auto]", "tw:[&_.control-toggle_strong]:text-[.72rem]",
  ].join(" "),
  "command_open_debts_head": [
    "command-open-debts-head", "tw:flex", "tw:items-center", "tw:viewport-620:items-start",
    "tw:justify-between", "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:[&_h3]:text-[color:var(--muted)]",
    "tw:[&_h3]:text-[.72rem]", "tw:[&_h3]:font-[700]", "tw:[&_small]:text-[color:var(--muted)]", "tw:[&_small]:text-[.7rem]",
    "tw:[&_small]:whitespace-nowrap", "tw:[&_small_b]:text-[color:var(--text)]", "tw:viewport-620:flex-col",
  ].join(" "),
  "command_open_debt_items": [
    "command-open-debt-items", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:[&_>_label]:mt-[0]", "tw:[&_>_label]:mr-[0]", "tw:[&_>_label]:mb-[0]", "tw:[&_>_label]:ml-[0]",
  ].join(" "),
  "command_checkout_grid": [
    "command-checkout-grid", "tw:grid", "tw:grid-cols-[minmax(240px,_.8fr)_minmax(0,_1.2fr)]", "tw:viewport-760:grid-cols-[1fr]",
    "tw:gap-y-[24px]", "tw:viewport-760:gap-y-[12px]", "tw:gap-x-[24px]", "tw:viewport-760:gap-x-[12px]",
    "tw:pt-[18px]", "tw:pr-[0]", "tw:pb-[18px]", "tw:pl-[0]",
    "tw:[&_>_section]:grid", "tw:[&_>_section]:[align-content:start]", "tw:[&_>_section]:gap-y-[12px]", "tw:[&_>_section]:gap-x-[12px]",
    "tw:[&_>_section:first-child]:pt-[18px]", "tw:[&_>_section:first-child]:pr-[18px]", "tw:[&_>_section:first-child]:pb-[18px]", "tw:[&_>_section:first-child]:pl-[18px]",
    "tw:[&_>_section:first-child]:border-t-[length:1px]", "tw:[&_>_section:first-child]:[border-top-style:solid]", "tw:[&_>_section:first-child]:border-t-[color:#8eb7e5]", "tw:[&_>_section:first-child]:border-r-[length:1px]",
    "tw:[&_>_section:first-child]:[border-right-style:solid]", "tw:[&_>_section:first-child]:border-r-[color:#8eb7e5]", "tw:[&_>_section:first-child]:border-b-[length:1px]", "tw:[&_>_section:first-child]:[border-bottom-style:solid]",
    "tw:[&_>_section:first-child]:border-b-[color:#8eb7e5]", "tw:[&_>_section:first-child]:border-l-[length:1px]", "tw:[&_>_section:first-child]:[border-left-style:solid]", "tw:[&_>_section:first-child]:border-l-[color:#8eb7e5]",
    "tw:[&_>_section:first-child]:rounded-[12px]", "tw:[&_>_section:first-child]:bg-[color:transparent]", "tw:[&_>_section:first-child]:[background-image:linear-gradient(145deg,_#e7f2ff,_#f7fbff)]", "tw:[&_>_section:first-child]:[box-shadow:inset_0_1px_#fff,_0_8px_18px_rgb(30_94_163_/_.09)]",
    "tw:[&_dl]:grid", "tw:[&_dl]:gap-y-[10px]", "tw:[&_dl]:gap-x-[10px]", "tw:[&_dl]:mt-[0]",
    "tw:[&_dl]:mr-[0]", "tw:[&_dl]:mb-[0]", "tw:[&_dl]:ml-[0]", "tw:[&_dl_div]:grid",
    "tw:[&_dl_div]:gap-y-[2px]", "tw:[&_dl_div]:gap-x-[2px]", "tw:[&_dt]:text-[color:var(--muted)]", "tw:[&_dt]:text-[.68rem]",
    "tw:[&_dt]:font-[800]", "tw:[&_dt]:uppercase", "tw:[&_dd]:mt-[0]", "tw:[&_dd]:mr-[0]",
    "tw:[&_dd]:mb-[0]", "tw:[&_dd]:ml-[0]", "tw:[&_dd]:text-[.86rem]", "tw:[&_dd]:font-[700]",
    "tw:[&_>_section:first-child_h3]:text-[color:#0d4d93]", "tw:[&_>_section:first-child_dl_div:last-child]:mt-[3px]", "tw:[&_>_section:first-child_dl_div:last-child]:pt-[10px]", "tw:[&_>_section:first-child_dl_div:last-child]:border-t-[length:1px]",
    "tw:[&_>_section:first-child_dl_div:last-child]:[border-top-style:solid]", "tw:[&_>_section:first-child_dl_div:last-child]:border-t-[color:#bed5ed]", "tw:[&_>_section:first-child_dl_div:last-child_dd]:text-[color:#093e79]", "tw:[&_>_section:first-child_dl_div:last-child_dd]:text-[1rem]",
  ].join(" "),
  "command_checkout_payment_head": [
    "command-checkout-payment-head", "tw:flex", "tw:justify-between", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]", "tw:items-start", "tw:[&_p]:mt-[3px]", "tw:[&_p]:text-[color:var(--muted)]",
    "tw:[&_p]:text-[.76rem]", "tw:viewport-760:flex-col",
  ].join(" "),
  "command_payment_list": [
    "command-payment-list", "tw:grid", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
  ].join(" "),
  "command_payment_row": [
    "command-payment-row", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)_130px_30px]", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:[&_select]:min-w-[0]", "tw:[&_select]:min-h-[34px]", "tw:[&_select]:pt-[5px]",
    "tw:[&_select]:pr-[8px]", "tw:[&_select]:pb-[5px]", "tw:[&_select]:pl-[8px]", "tw:[&_select]:border-t-[length:1px]",
    "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]",
    "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:var(--line)]",
    "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:var(--line)]", "tw:[&_select]:rounded-[7px]",
    "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]", "tw:[&_input]:min-w-[0]", "tw:[&_input]:min-h-[34px]",
    "tw:[&_input]:pt-[5px]", "tw:[&_input]:pr-[8px]", "tw:[&_input]:pb-[5px]", "tw:[&_input]:pl-[8px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:var(--line)]",
    "tw:[&_input]:rounded-[7px]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]", "tw:[&_button]:border-t-[length:1px]",
    "tw:[&_button]:[border-top-style:solid]", "tw:[&_button]:border-t-[color:#e5a1a1]", "tw:[&_button]:border-r-[length:1px]", "tw:[&_button]:[border-right-style:solid]",
    "tw:[&_button]:border-r-[color:#e5a1a1]", "tw:[&_button]:border-b-[length:1px]", "tw:[&_button]:[border-bottom-style:solid]", "tw:[&_button]:border-b-[color:#e5a1a1]",
    "tw:[&_button]:border-l-[length:1px]", "tw:[&_button]:[border-left-style:solid]", "tw:[&_button]:border-l-[color:#e5a1a1]", "tw:[&_button]:rounded-[7px]",
    "tw:[&_button]:bg-[color:#fff5f5]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:#bf2525]", "tw:[&_button]:text-[1rem]",
  ].join(" "),
  "command_checkout_warning": [
    "command-checkout-warning", "tw:pt-[10px]", "tw:pr-[10px]", "tw:pb-[10px]",
    "tw:pl-[10px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#f4cd88]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#f4cd88]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#f4cd88]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#f4cd88]", "tw:rounded-[8px]", "tw:bg-[color:#fff8e8]", "tw:[background-image:none]",
    "tw:text-[color:#875d13]", "tw:text-[.78rem]",
  ].join(" "),
  "command_fiscal_document": [
    "command-fiscal-document", "tw:grid", "tw:gap-y-[5px]", "tw:gap-x-[5px]",
    "tw:mt-[12px]", "tw:text-[color:#38556d]", "tw:text-[.74rem]", "tw:font-[800]",
    "tw:[&_select]:min-h-[36px]", "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[9px]", "tw:[&_select]:pb-[0]",
    "tw:[&_select]:pl-[9px]", "tw:[&_small]:text-[color:#71879a]", "tw:[&_small]:text-[.66rem]", "tw:[&_small]:font-[600]",
  ].join(" "),
  "command_checkout_totals": [
    "command-checkout-totals", "tw:grid", "tw:grid-cols-[repeat(3,_minmax(0,_1fr))]", "tw:viewport-760:grid-cols-[1fr]",
    "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:pt-[10px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:text-[.78rem]", "tw:[&_strong]:block",
    "tw:[&_strong]:mt-[2px]", "tw:[&_strong]:text-[color:var(--ink)]", "tw:[&_strong]:text-[.9rem]",
  ].join(" "),
  "command_checkout_danger_actions": [
    "command-checkout-danger-actions", "tw:justify-start",
  ].join(" "),
  "button_button_danger": sharedUtilities.buttonButtonDanger,
  "button_button_warning": [
    "button", "button-warning", "tw:inline-flex", "tw:items-center",
    "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:min-h-[36px]",
    "tw:pt-[0]", "tw:pr-[12px]", "tw:pb-[0]", "tw:pl-[12px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#c96a16]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#c96a16]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#c96a16]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#c96a16]",
    "tw:rounded-[var(--radius-control)]", "tw:bg-[color:#e57c1a]", "tw:[background-image:none]", "tw:text-[color:#fff]",
    "tw:text-[0.86rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--line-strong)]", "tw:hover:border-r-[color:var(--line-strong)]",
    "tw:hover:border-b-[color:var(--line-strong)]", "tw:hover:border-l-[color:var(--line-strong)]", "tw:hover:[transform:translateY(-1px)]", "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]",
    "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]", "tw:[&:active]:[box-shadow:none]",
    "tw:hover:bg-[color:#bd5e0d]", "tw:hover:[background-image:none]",
  ].join(" "),
  "command_divide_popover": [
    "command-divide-popover", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:absolute", "tw:right-[20px]", "tw:bottom-[68px]", "tw:w-[min(330px,_calc(100%_-_40px))]",
    "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]", "tw:pl-[14px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#e7b178]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#e7b178]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#e7b178]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#e7b178]",
    "tw:rounded-[10px]", "tw:bg-[color:#fffaf3]", "tw:[background-image:none]", "tw:[box-shadow:0_15px_36px_rgb(15_23_42_/_.2)]",
    "tw:[&_p]:text-[color:var(--muted)]", "tw:[&_p]:text-[.76rem]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[4px]",
    "tw:[&_label]:gap-x-[4px]", "tw:[&_label]:text-[.74rem]", "tw:[&_label]:font-[800]", "tw:[&_input]:min-h-[34px]",
    "tw:[&_input]:pt-[6px]", "tw:[&_input]:pr-[8px]", "tw:[&_input]:pb-[6px]", "tw:[&_input]:pl-[8px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:var(--line)]",
    "tw:[&_input]:rounded-[var(--radius-control)]", "tw:[&_input]:bg-[color:#fff]", "tw:[&_input]:[background-image:none]",
  ].join(" "),
} as const;
