import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "commands_new_modal_backdrop": [
    "commands-new-modal-backdrop", "tw:fixed", "tw:z-[95]", "tw:top-[0]",
    "tw:right-[0]", "tw:bottom-[0]", "tw:left-[0]", "tw:grid",
    "tw:place-items-center", "tw:pt-[20px]", "tw:viewport-760:pt-[12px]", "tw:pr-[20px]",
    "tw:viewport-760:pr-[12px]", "tw:pb-[20px]", "tw:viewport-760:pb-[12px]", "tw:pl-[20px]",
    "tw:viewport-760:pl-[12px]", "tw:bg-[color:rgb(12_29_53_/_.38)]", "tw:[background-image:none]", "tw:[backdrop-filter:blur(4px)]",
    "tw:viewport-760:[align-items:end]",
  ].join(" "),
  "commands_new_modal": [
    "commands-new-modal", "tw:grid", "tw:gap-y-[18px]", "tw:gap-x-[18px]",
    "tw:w-[min(100%,_440px)]", "tw:viewport-760:w-[100%]", "tw:pt-[22px]", "tw:viewport-760:pt-[18px]",
    "tw:pr-[22px]", "tw:viewport-760:pr-[18px]", "tw:pb-[22px]", "tw:viewport-760:pb-[18px]",
    "tw:pl-[22px]", "tw:viewport-760:pl-[18px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#d9e5f0]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d9e5f0]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d9e5f0]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#d9e5f0]", "tw:rounded-[15px]", "tw:viewport-760:rounded-[14px]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[box-shadow:0_22px_58px_rgb(12_33_61_/_.2)]", "tw:[&_>_header]:flex",
    "tw:[&_>_header]:items-start", "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[14px]", "tw:[&_>_header]:gap-x-[14px]",
    "tw:[&_>_header]:pb-[15px]", "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#e4ebf3]",
    "tw:[&_header_div]:grid", "tw:[&_header_div]:gap-y-[4px]", "tw:[&_header_div]:gap-x-[4px]", "tw:[&_header_span]:text-[color:#2365b5]",
    "tw:[&_header_span]:text-[.64rem]", "tw:[&_header_span]:font-[850]", "tw:[&_header_span]:tracking-[.07em]", "tw:[&_h2]:mt-[0]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#132743]",
    "tw:[&_h2]:text-[1.15rem]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_header_p]:text-[color:#698097]", "tw:[&_header_p]:text-[.82rem]", "tw:[&_header_p]:leading-[1.45]",
    "tw:[&_.field]:grid", "tw:[&_.field]:gap-y-[6px]", "tw:[&_.field]:gap-x-[6px]", "tw:[&_.field]:text-[color:#49647e]",
    "tw:[&_.field]:text-[.72rem]", "tw:[&_.field]:font-[800]", "tw:[&_select]:min-h-[44px]", "tw:[&_select]:[padding-inline:11px]",
    "tw:[&_select]:border-t-[color:#cad9e7]", "tw:[&_select]:border-r-[color:#cad9e7]", "tw:[&_select]:border-b-[color:#cad9e7]", "tw:[&_select]:border-l-[color:#cad9e7]",
    "tw:[&_select]:rounded-[9px]", "tw:[&_select]:text-[color:#193d64]", "tw:[&_select]:text-[.86rem]",
  ].join(" "),
  "commands_modal_close": [
    "commands-modal-close", "tw:grid", "tw:w-[30px]", "tw:h-[30px]",
    "tw:place-items-center", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d7e2ec]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d7e2ec]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d7e2ec]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#d7e2ec]", "tw:rounded-[8px]", "tw:text-[color:#49647e]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:text-[1.2rem]", "tw:leading-[1]", "tw:cursor-pointer",
    "tw:hover:border-t-[color:#9bbad7]", "tw:hover:border-r-[color:#9bbad7]", "tw:hover:border-b-[color:#9bbad7]", "tw:hover:border-l-[color:#9bbad7]",
    "tw:hover:bg-[color:#f3f8fc]", "tw:hover:[background-image:none]", "tw:hover:text-[color:#1d5792]",
  ].join(" "),
  "field": sharedUtilities.field,
  "commands_client_results": [
    "commands-client-results", "tw:grid", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:max-h-[270px]", "tw:[overflow-x:auto]", "tw:[overflow-y:auto]", "tw:[&_button]:flex",
    "tw:[&_button]:justify-between", "tw:[&_button]:gap-y-[12px]", "tw:[&_button]:gap-x-[12px]", "tw:[&_button]:w-[100%]",
    "tw:[&_button]:pt-[10px]", "tw:[&_button]:pr-[11px]", "tw:[&_button]:pb-[10px]", "tw:[&_button]:pl-[11px]",
    "tw:[&_button]:border-t-[length:1px]", "tw:[&_button]:[border-top-style:solid]", "tw:[&_button]:border-t-[color:var(--line)]", "tw:[&_button]:border-r-[length:1px]",
    "tw:[&_button]:[border-right-style:solid]", "tw:[&_button]:border-r-[color:var(--line)]", "tw:[&_button]:border-b-[length:1px]", "tw:[&_button]:[border-bottom-style:solid]",
    "tw:[&_button]:border-b-[color:var(--line)]", "tw:[&_button]:border-l-[length:1px]", "tw:[&_button]:[border-left-style:solid]", "tw:[&_button]:border-l-[color:var(--line)]",
    "tw:[&_button]:rounded-[8px]", "tw:[&_button]:bg-[color:var(--panel-muted)]", "tw:[&_button]:[background-image:none]", "tw:[&_button]:text-[color:var(--text)]",
    "tw:[&_button]:text-left", "tw:[&_button]:cursor-pointer", "tw:[&_button:hover]:border-t-[color:var(--brand)]", "tw:[&_button:hover]:border-r-[color:var(--brand)]",
    "tw:[&_button:hover]:border-b-[color:var(--brand)]", "tw:[&_button:hover]:border-l-[color:var(--brand)]", "tw:[&_button:hover]:bg-[color:var(--brand-soft)]", "tw:[&_button:hover]:[background-image:none]",
    "tw:[&_button_span]:text-[color:var(--muted)]", "tw:[&_button_span]:text-[.75rem]", "tw:[&_p]:text-[color:var(--muted)]", "tw:[&_p]:text-[.75rem]",
    "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
    "tw:[&_p]:pt-[8px]", "tw:[&_p]:pr-[0]", "tw:[&_p]:pb-[8px]", "tw:[&_p]:pl-[0]",
  ].join(" "),
  "form_error": sharedUtilities.formError,
} as const;
