import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "report_metric": [
    "report-metric", "tw:grid", "tw:gap-y-[5px]", "tw:gap-x-[5px]",
    "tw:min-h-[92px]", "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]",
    "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dbe6f1]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dbe6f1]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dbe6f1]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#dbe6f1]", "tw:rounded-[10px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[box-shadow:0_6px_14px_rgb(24_59_101_/_.04)]", "tw:[&_span]:text-[color:#61768e]", "tw:[&_span]:text-[.7rem]", "tw:[&_span]:font-[750]",
    "tw:[&_strong]:text-[color:#15385f]", "tw:[&_strong]:text-[1.15rem]", "tw:[&.positive_strong]:text-[color:#15764a]", "tw:[&.negative_strong]:text-[color:#b3483d]",
  ].join(" "),
  "report_table": [
    "report-table", "tw:[overflow-x:hidden]", "tw:viewport-800:[overflow-x:visible]", "tw:[overflow-y:hidden]",
    "tw:viewport-800:[overflow-y:visible]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dbe6f1]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dbe6f1]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dbe6f1]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#dbe6f1]", "tw:rounded-[10px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[&_article]:grid", "tw:[&_article]:grid-cols-[repeat(6,_minmax(110px,_1fr))]", "tw:viewport-800:[&_article]:grid-cols-[1fr_1fr]", "tw:[&_article]:gap-y-[12px]",
    "tw:viewport-800:[&_article]:gap-y-[6px]", "tw:[&_article]:gap-x-[12px]", "tw:[&_article]:items-center", "tw:[&_article]:min-h-[54px]",
    "tw:viewport-800:[&_article]:min-h-[0]", "tw:[&_article]:pt-[9px]", "tw:[&_article]:pr-[14px]", "tw:[&_article]:pb-[9px]",
    "tw:[&_article]:pl-[14px]", "tw:[&_article]:border-b-[length:1px]", "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#e8eef5]",
    "tw:[&_article]:text-[color:#4d637e]", "tw:[&_article]:text-[.76rem]", "tw:[&_article:last-of-type]:border-b-[length:0]", "tw:[&_article:last-of-type]:[border-bottom-style:none]",
    "tw:[&_article:last-of-type]:border-b-[color:currentColor]", "tw:[&_article:hover]:bg-[color:#f8fbff]", "tw:[&_article:hover]:[background-image:none]", "tw:[&_article_span:nth-child(2)]:[overflow-x:hidden]",
    "tw:[&_article_span:nth-child(2)]:[overflow-y:hidden]", "tw:[&_article_span:nth-child(2)]:text-[color:#183a62]", "tw:[&_article_span:nth-child(2)]:font-[700]", "tw:[&_article_span:nth-child(2)]:text-ellipsis",
    "tw:[&_article_span:nth-child(2)]:whitespace-nowrap", "tw:viewport-800:[&_article_span:nth-child(2)]:[white-space:normal]", "tw:viewport-800:[&_article_span]:min-w-[0]",
  ].join(" "),
  "report_table_head": [
    "report-table-head", "tw:grid", "tw:viewport-800:hidden", "tw:grid-cols-[repeat(6,_minmax(110px,_1fr))]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:items-center", "tw:min-h-[38px]",
    "tw:pt-[0]", "tw:pr-[14px]", "tw:pb-[0]", "tw:pl-[14px]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e0e8f1]", "tw:bg-[color:#f6f9fd]",
    "tw:[background-image:none]", "tw:text-[color:#60758d]", "tw:text-[.65rem]", "tw:font-[800]",
    "tw:tracking-[.04em]", "tw:uppercase",
  ].join(" "),
  "client_empty": sharedUtilities.clientEmpty,
  "report_summary": [
    "report-summary", "tw:pt-[15px]", "tw:pr-[15px]", "tw:pb-[15px]",
    "tw:pl-[15px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dce6f0]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce6f0]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce6f0]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#dce6f0]", "tw:rounded-[10px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[9px]", "tw:[&_h3]:ml-[0]",
    "tw:[&_h3]:text-[color:#173b65]", "tw:[&_h3]:text-[.86rem]", "tw:[&_>_div]:grid", "tw:[&_article]:grid",
    "tw:[&_article]:grid-cols-[minmax(0,_1fr)_105px_120px]", "tw:viewport-640:[&_article]:grid-cols-[1fr_auto]", "tw:[&_article]:gap-y-[10px]", "tw:viewport-640:[&_article]:gap-y-[3px]",
    "tw:[&_article]:gap-x-[10px]", "tw:[&_article]:items-center", "tw:[&_article]:min-h-[35px]", "tw:[&_article]:border-b-[length:1px]",
    "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#edf1f6]", "tw:[&_article]:text-[color:#5c7089]", "tw:[&_article]:text-[.72rem]",
    "tw:[&_article:last-child]:border-b-[length:0]", "tw:[&_article:last-child]:[border-bottom-style:none]", "tw:[&_article:last-child]:border-b-[color:currentColor]", "tw:[&_article_strong]:text-[color:#284768]",
    "tw:[&_article_b]:text-[color:#15764a]", "tw:[&_article_b]:text-right", "tw:[&_>_div_>_.muted]:mt-[5px]", "tw:[&_>_div_>_.muted]:mr-[0]",
    "tw:[&_>_div_>_.muted]:mb-[5px]", "tw:[&_>_div_>_.muted]:ml-[0]", "tw:[&_>_div_>_.muted]:text-[.74rem]", "tw:viewport-640:[&_article]:pt-[8px]",
    "tw:viewport-640:[&_article]:pr-[0]", "tw:viewport-640:[&_article]:pb-[8px]", "tw:viewport-640:[&_article]:pl-[0]", "tw:viewport-640:[&_article_span]:[grid-column:1]",
    "tw:viewport-640:[&_article_b]:[grid-column:2]", "tw:viewport-640:[&_article_b]:[grid-row:1_/_span_2]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "reservation_report_insights": [
    "reservation-report-insights", "tw:grid", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
  ].join(" "),
  "reservation_report_highlights": [
    "reservation-report-highlights", "tw:grid", "tw:grid-cols-[repeat(3,_minmax(0,_1fr))]", "tw:viewport-640:grid-cols-[1fr]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:[&_article]:pt-[14px]", "tw:[&_article]:pr-[14px]",
    "tw:[&_article]:pb-[14px]", "tw:[&_article]:pl-[14px]", "tw:[&_article]:border-t-[length:1px]", "tw:[&_article]:[border-top-style:solid]",
    "tw:[&_article]:border-t-[color:#dce6f0]", "tw:[&_article]:border-r-[length:1px]", "tw:[&_article]:[border-right-style:solid]", "tw:[&_article]:border-r-[color:#dce6f0]",
    "tw:[&_article]:border-b-[length:1px]", "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#dce6f0]", "tw:[&_article]:border-l-[length:1px]",
    "tw:[&_article]:[border-left-style:solid]", "tw:[&_article]:border-l-[color:#dce6f0]", "tw:[&_article]:rounded-[10px]", "tw:[&_article]:bg-[color:#fff]",
    "tw:[&_article]:[background-image:none]", "tw:[&_article]:grid", "tw:[&_article]:gap-y-[4px]", "tw:[&_article]:gap-x-[4px]",
    "tw:[&_span]:text-[color:#61768e]", "tw:[&_span]:text-[.67rem]", "tw:[&_span]:font-[800]", "tw:[&_span]:tracking-[.03em]",
    "tw:[&_span]:uppercase", "tw:[&_strong]:text-[color:#173b65]", "tw:[&_strong]:text-[.94rem]", "tw:[&_small]:text-[color:#61768e]",
    "tw:[&_small]:text-[.73rem]",
  ].join(" "),
  "reservation_report_courts": [
    "reservation-report-courts", "tw:pt-[0]", "tw:pr-[14px]", "tw:pb-[0]",
    "tw:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dce6f0]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce6f0]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce6f0]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#dce6f0]", "tw:rounded-[10px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[overflow-x:hidden]", "tw:viewport-640:[overflow-x:auto]", "tw:[overflow-y:hidden]", "tw:[&_article]:grid",
    "tw:[&_article]:grid-cols-[minmax(140px,_1fr)_100px_180px]", "tw:[&_article]:gap-y-[12px]", "tw:[&_article]:gap-x-[12px]", "tw:[&_article]:items-center",
    "tw:[&_article]:min-h-[39px]", "tw:[&_article]:border-b-[length:1px]", "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#e7eef5]",
    "tw:[&_article]:text-[color:#536982]", "tw:[&_article]:text-[.76rem]", "tw:[&_article:last-of-type]:border-b-[length:0]", "tw:[&_article:last-of-type]:[border-bottom-style:none]",
    "tw:[&_article:last-of-type]:border-b-[color:currentColor]", "tw:[&_article_strong]:text-[color:#173b65]", "tw:[&_article_>_span:last-child]:flex", "tw:[&_article_>_span:last-child]:items-center",
    "tw:[&_article_>_span:last-child]:justify-end", "tw:[&_article_>_span:last-child]:gap-y-[8px]", "tw:[&_article_>_span:last-child]:gap-x-[8px]", "tw:[&_article_>_span:last-child]:text-[color:#284768]",
    "tw:[&_article_>_span:last-child]:font-[700]", "tw:[&_i]:block", "tw:[&_i]:w-[100px]", "tw:[&_i]:h-[6px]",
    "tw:[&_i]:[overflow-x:hidden]", "tw:[&_i]:[overflow-y:hidden]", "tw:[&_i]:rounded-[999px]", "tw:[&_i]:bg-[color:#e7eef7]",
    "tw:[&_i]:[background-image:none]", "tw:[&_i_b]:block", "tw:[&_i_b]:h-[100%]", "tw:[&_i_b]:rounded-[inherit]",
    "tw:[&_i_b]:bg-[color:#1e7a56]", "tw:[&_i_b]:[background-image:none]", "tw:viewport-640:[&_article]:min-w-[410px]",
  ].join(" "),
  "reservation_report_courts_head": [
    "reservation-report-courts-head", "tw:text-[color:#61768e]", "tw:text-[.67rem]", "tw:font-[800]",
    "tw:tracking-[.03em]", "tw:uppercase", "tw:grid", "tw:grid-cols-[minmax(140px,_1fr)_100px_180px]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:items-center", "tw:min-h-[39px]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e7eef5]", "tw:viewport-640:min-w-[410px]",
  ].join(" "),
  "report_metrics": [
    "report-metrics", "tw:grid", "tw:grid-cols-[repeat(3,_minmax(0,_1fr))]", "tw:viewport-800:grid-cols-[1fr]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]",
  ].join(" "),
  "report_advanced_filter": [
    "report-advanced-filter", "tw:grid", "tw:grid-cols-[repeat(5,_minmax(130px,_1fr))_auto]", "tw:viewport-1000:grid-cols-[repeat(3,_minmax(0,_1fr))]",
    "tw:viewport-640:grid-cols-[1fr]", "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:max-w-[1180px]",
    "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]", "tw:pl-[14px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dce6f0]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#dce6f0]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#dce6f0]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#dce6f0]",
    "tw:rounded-[10px]", "tw:bg-[color:#f8fbff]", "tw:[background-image:none]", "tw:[&_label]:grid",
    "tw:[&_label]:gap-y-[5px]", "tw:[&_label]:gap-x-[5px]", "tw:[&_label]:text-[color:#526983]", "tw:[&_label]:text-[.68rem]",
    "tw:[&_label]:font-[800]", "tw:[&_select]:min-w-[0]", "tw:[&_select]:min-h-[34px]", "tw:[&_select]:pt-[0]",
    "tw:[&_select]:pr-[8px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[8px]", "tw:[&_select]:text-[.74rem]",
    "tw:[&_.button]:[align-self:end]", "tw:[&_.button]:min-h-[34px]", "tw:[&_.button]:whitespace-nowrap", "tw:viewport-1000:[&_.button]:w-[fit-content]",
    "tw:viewport-640:[&_.button]:w-[100%]",
  ].join(" "),
  "button_button_primary_button_small": sharedUtilities.buttonButtonPrimaryButtonSmall,
  "report_summaries": [
    "report-summaries", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-640:grid-cols-[1fr]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]",
  ].join(" "),
  "stack_md_report_page": [
    "stack-md", "report-page", "tw:grid", "tw:gap-y-[18px]",
    "tw:gap-x-[18px]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]",
    "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]",
    "tw:max-w-[1320px]", "tw:[&_.page-header]:items-center", "tw:viewport-800:[&_.page-header]:items-start", "tw:[&_.page-header]:pt-[22px]",
    "tw:[&_.page-header]:pr-[24px]", "tw:[&_.page-header]:pb-[22px]", "tw:[&_.page-header]:pl-[24px]", "tw:[&_.page-header]:border-t-[color:#dce6f1]",
    "tw:[&_.page-header]:border-r-[color:#dce6f1]", "tw:[&_.page-header]:border-b-[color:#dce6f1]", "tw:[&_.page-header]:border-l-[color:#dce6f1]", "tw:[&_.page-header]:[box-shadow:0_8px_20px_rgb(22_57_100_/_.05)]",
    "tw:[&_.page-header_h1]:text-[color:#112f58]", "tw:[&_.page-header_h1]:text-[clamp(1.55rem,_2.3vw,_2.1rem)]", "tw:[&_.page-header_.eyebrow]:mb-[4px]", "tw:[&_.page-header_.muted]:mt-[0]",
    "tw:[&_.page-header_.muted]:mr-[0]", "tw:[&_.page-header_.muted]:mb-[0]", "tw:[&_.page-header_.muted]:ml-[0]", "tw:[&_.page-header_.muted]:text-[.82rem]",
    "tw:viewport-800:[&_.page-header]:flex-col",
  ].join(" "),
  "page_header": sharedUtilities.pageHeader,
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "report_filter": [
    "report-filter", "tw:flex", "tw:[align-items:end]", "tw:viewport-800:items-stretch",
    "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[5px]",
    "tw:[&_label]:gap-x-[5px]", "tw:[&_label]:text-[color:#506783]", "tw:[&_label]:text-[.7rem]", "tw:[&_label]:font-[800]",
    "tw:[&_input]:min-h-[34px]", "tw:[&_input]:[padding-inline:9px]", "tw:viewport-800:flex-col", "tw:viewport-800:[&_.button]:w-[fit-content]",
  ].join(" "),
} as const;
