import Link from "next/link";
import { notFound } from "next/navigation";
import { SectionCard } from "@/components/section-card";
import { requireModuleView } from "@/lib/auth/guards";
import { prisma } from "@/lib/prisma";

const reports = {
  caixa: ["Relatório de Caixa", "Recebimentos e pagamentos efetivados no período."], lancamentos: ["Relatório de Lançamentos", "Receitas e despesas registradas no período."], produtos: ["Relatório de Produtos", "Vendas consolidadas por produto."], estoque: ["Movimentação de Estoque", "Entradas, saídas e contagens registradas."], comandas: ["Histórico de Comandas", "Comandas abertas e finalizadas no período."], dre: ["DRE Gerencial", "Resultado operacional calculado pelos lançamentos."], planos: ["Relatório de Planos", "Planos e assinaturas ativas da arena."], reservas: ["Relatório de Reservas", "Ocupação e agendamentos das quadras."]
} as const;

const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value / 100);
const date = (value: Date | null) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short" }).format(value) : "—";
function range(startValue?: string, endValue?: string) { const now = new Date(); const start = startValue ? new Date(`${startValue}T00:00:00`) : new Date(now.getFullYear(), now.getMonth(), 1); const end = endValue ? new Date(`${endValue}T23:59:59.999`) : new Date(); end.setHours(23, 59, 59, 999); return { start, end }; }
function Metric({ label, value, tone }: { label: string; value: string | number; tone?: "positive" | "negative" }) { return <article className={`report-metric ${tone ?? ""}`}><span>{label}</span><strong>{value}</strong></article>; }
function ReportRows({ headers, rows }: { headers: string[]; rows: { key: string; values: string[] }[] }) { return <div className="report-table"><div className="report-table-head">{headers.map((header) => <span key={header}>{header}</span>)}</div>{rows.map((row) => <article key={row.key}>{row.values.map((value, index) => <span key={`${row.key}-${index}`}>{value}</span>)}</article>)}{!rows.length ? <p className="client-empty">Nenhum registro no período selecionado.</p> : null}</div>; }

export default async function ReportPage({ params, searchParams }: { params: { relatorio: string }; searchParams?: { inicio?: string; fim?: string } }) {
  const auth = await requireModuleView("finance"); const report = reports[params.relatorio as keyof typeof reports]; if (!report) notFound(); const { start, end } = range(searchParams?.inicio, searchParams?.fim); const period = { gte: start, lte: end };
  let metrics: React.ReactNode = null; let headers: string[] = []; let rows: { key: string; values: string[] }[] = [];
  if (params.relatorio === "caixa" || params.relatorio === "lancamentos" || params.relatorio === "dre") {
    const entries = await prisma.financialEntry.findMany({ where: { arenaId: auth.arenaId, createdAt: period, status: { not: "VOIDED" } }, orderBy: { createdAt: "desc" }, take: 100 });
    const revenue = entries.filter((entry) => ["REVENUE", "INCOME"].includes(entry.type)).reduce((sum, entry) => sum + entry.amountCents, 0); const expense = entries.filter((entry) => entry.type === "EXPENSE").reduce((sum, entry) => sum + entry.amountCents, 0);
    metrics = <div className="report-metrics"><Metric label="Receitas" value={money(revenue)} tone="positive" /><Metric label="Despesas" value={money(expense)} tone="negative" /><Metric label="Resultado" value={money(revenue - expense)} tone={revenue >= expense ? "positive" : "negative"} /></div>;
    headers = ["Data", "Descrição", "Categoria", "Tipo", "Valor", "Situação"]; rows = entries.map((entry) => ({ key: entry.id, values: [date(entry.paidAt ?? entry.dueDate ?? entry.createdAt), entry.description, entry.category, ["REVENUE", "INCOME"].includes(entry.type) ? "Receita" : "Despesa", money(entry.amountCents), entry.status === "PAID" ? "Pago" : "Em aberto"] }));
  } else if (params.relatorio === "produtos") {
    const items = await prisma.saleItem.findMany({ where: { sale: { arenaId: auth.arenaId, createdAt: period } }, include: { product: true, sale: { select: { createdAt: true } } }, orderBy: { sale: { createdAt: "desc" } }, take: 100 }); const total = items.reduce((sum, item) => sum + item.totalCents, 0);
    metrics = <div className="report-metrics"><Metric label="Itens vendidos" value={items.reduce((sum, item) => sum + item.quantity, 0)} /><Metric label="Faturamento" value={money(total)} tone="positive" /><Metric label="Produtos movimentados" value={new Set(items.map((item) => item.productId)).size} /></div>; headers = ["Data", "Produto", "Quantidade", "Preço unitário", "Total"]; rows = items.map((item) => ({ key: item.id, values: [date(item.sale.createdAt), item.product.name, String(item.quantity), money(item.unitPriceCents), money(item.totalCents)] }));
  } else if (params.relatorio === "estoque") {
    const movements = await prisma.stockMovement.findMany({ where: { arenaId: auth.arenaId, createdAt: period }, include: { product: true }, orderBy: { createdAt: "desc" }, take: 100 }); metrics = <div className="report-metrics"><Metric label="Movimentações" value={movements.length} /><Metric label="Entradas" value={movements.filter((item) => item.type === "IN").reduce((sum, item) => sum + item.quantity, 0)} tone="positive" /><Metric label="Saídas" value={movements.filter((item) => item.type === "OUT").reduce((sum, item) => sum + item.quantity, 0)} tone="negative" /></div>; headers = ["Data", "Produto", "Tipo", "Quantidade", "Motivo"]; rows = movements.map((item) => ({ key: item.id, values: [date(item.createdAt), item.product.name, item.type === "IN" ? "Entrada" : item.type === "OUT" ? "Saída" : "Contagem", String(item.quantity), item.reason || "—"] }));
  } else if (params.relatorio === "comandas") {
    const comandas = await prisma.comanda.findMany({ where: { arenaId: auth.arenaId, openedAt: period }, include: { sale: true, _count: { select: { items: true } } }, orderBy: { openedAt: "desc" }, take: 100 }); metrics = <div className="report-metrics"><Metric label="Comandas" value={comandas.length} /><Metric label="Abertas" value={comandas.filter((item) => item.status === "OPEN").length} /><Metric label="Total finalizado" value={money(comandas.reduce((sum, item) => sum + (item.sale?.totalCents ?? 0), 0))} tone="positive" /></div>; headers = ["Abertura", "Comanda", "Cliente", "Itens", "Situação", "Total"]; rows = comandas.map((item) => ({ key: item.id, values: [date(item.openedAt), item.code, item.label, String(item._count.items), item.status === "OPEN" ? "Aberta" : "Finalizada", money(item.sale?.totalCents ?? 0)] }));
  } else if (params.relatorio === "planos") {
    const subscriptions = await prisma.studentSubscription.findMany({ where: { arenaId: auth.arenaId }, include: { plan: true, student: true }, orderBy: { createdAt: "desc" }, take: 100 }); metrics = <div className="report-metrics"><Metric label="Assinaturas ativas" value={subscriptions.filter((item) => item.status === "ACTIVE").length} tone="positive" /><Metric label="Planos utilizados" value={new Set(subscriptions.map((item) => item.planId)).size} /><Metric label="Mensalidade ativa" value={money(subscriptions.filter((item) => item.status === "ACTIVE").reduce((sum, item) => sum + item.monthlyPriceCents, 0))} /></div>; headers = ["Aluno", "Plano", "Aulas/mês", "Mensalidade", "Situação"]; rows = subscriptions.map((item) => ({ key: item.id, values: [item.student.name, item.plan.name, String(item.classesPerMonth), money(item.monthlyPriceCents), item.status === "ACTIVE" ? "Ativa" : item.status] }));
  } else {
    const occurrences = await prisma.scheduleOccurrence.findMany({ where: { arenaId: auth.arenaId, startsAt: period }, include: { occurrenceCourts: { include: { court: true } }, participants: true }, orderBy: { startsAt: "desc" }, take: 100 }); metrics = <div className="report-metrics"><Metric label="Reservas" value={occurrences.length} /><Metric label="Canceladas" value={occurrences.filter((item) => item.status === "CANCELLED").length} tone="negative" /><Metric label="Participantes" value={occurrences.reduce((sum, item) => sum + item.participants.length, 0)} /></div>; headers = ["Data", "Reserva", "Quadra", "Participantes", "Situação"]; rows = occurrences.map((item) => ({ key: item.id, values: [date(item.startsAt), item.title, item.occurrenceCourts.map((court) => court.court.name).join(", ") || "—", String(item.participants.length), item.status === "CANCELLED" ? "Cancelada" : "Confirmada"] }));
  }
  return <div className="stack-md report-page"><header className="page-header"><div><p className="eyebrow">RELATÓRIOS</p><h1>{report[0]}</h1><p className="muted">{report[1]}</p></div><Link href="/relatorios" className="button button-small">Voltar aos relatórios</Link></header><SectionCard title="Período" description="Os indicadores e registros abaixo refletem o período selecionado."><form className="report-filter"><label>Data inicial<input name="inicio" type="date" defaultValue={searchParams?.inicio ?? start.toISOString().slice(0, 10)} /></label><label>Data final<input name="fim" type="date" defaultValue={searchParams?.fim ?? end.toISOString().slice(0, 10)} /></label><button className="button button-primary button-small" type="submit">Gerar relatório</button></form></SectionCard>{metrics}<SectionCard title="Registros do relatório" description="Até 100 registros mais recentes do período."><ReportRows headers={headers} rows={rows} /></SectionCard></div>;
}
