import Link from "next/link";
import { notFound } from "next/navigation";
import { SectionCard } from "@/components/section-card";
import { requireModuleView } from "@/lib/auth/guards";
import { prisma } from "@/lib/prisma";

const reports = {
  caixa: ["Relatório de Caixa", "Recebimentos e pagamentos efetivados no período."], lancamentos: ["Relatório de Lançamentos", "Receitas e despesas registradas no período."], produtos: ["Relatório de Produtos", "Vendas consolidadas por produto."], estoque: ["Movimentação de Estoque", "Entradas, saídas e contagens registradas."], comandas: ["Histórico de Comandas", "Comandas abertas e finalizadas no período."], dre: ["DRE Gerencial", "Resultado operacional calculado pelos lançamentos."], planos: ["Relatório de Planos", "Planos e assinaturas ativas da arena."], reservas: ["Relatório de Reservas", "Ocupação e agendamentos das quadras."]
  , "pagamentos-online": ["Pagamentos Online", "Acompanhe cobranças digitais, confirmações e pendências."]
} as const;

const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value / 100);
const date = (value: Date | null) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "short" }).format(value) : "—";
function range(startValue?: string, endValue?: string) { const now = new Date(); const start = startValue ? new Date(`${startValue}T00:00:00`) : new Date(now.getFullYear(), now.getMonth(), 1); const end = endValue ? new Date(`${endValue}T23:59:59.999`) : new Date(); end.setHours(23, 59, 59, 999); return { start, end }; }
function Metric({ label, value, tone }: { label: string; value: string | number; tone?: "positive" | "negative" }) { return <article className={`report-metric ${tone ?? ""}`}><span>{label}</span><strong>{value}</strong></article>; }
function ReportRows({ headers, rows }: { headers: string[]; rows: { key: string; values: string[] }[] }) { return <div className="report-table"><div className="report-table-head">{headers.map((header) => <span key={header}>{header}</span>)}</div>{rows.map((row) => <article key={row.key}>{row.values.map((value, index) => <span key={`${row.key}-${index}`}>{value}</span>)}</article>)}{!rows.length ? <p className="client-empty">Nenhum registro no período selecionado.</p> : null}</div>; }
function Summary({ title, rows }: { title: string; rows: { label: string; count: number; total: number }[] }) { return <section className="report-summary"><h3>{title}</h3><div>{rows.map((row) => <article key={row.label}><strong>{row.label}</strong><span>{row.count} lançamento{row.count === 1 ? "" : "s"}</span><b>{money(row.total)}</b></article>)}{!rows.length ? <p className="muted">Nenhum valor para consolidar neste período.</p> : null}</div></section>; }

export default async function ReportPage({ params, searchParams }: { params: { relatorio: string }; searchParams?: { inicio?: string; fim?: string; tipo?: string; situacao?: string; categoria?: string; forma?: string; banco?: string; professor?: string; pagamento?: string } }) {
  const auth = await requireModuleView("finance"); const report = reports[params.relatorio as keyof typeof reports]; if (!report) notFound(); const { start, end } = range(searchParams?.inicio, searchParams?.fim); const period = { gte: start, lte: end };
  let metrics: React.ReactNode = null; let supplementary: React.ReactNode = null; let headers: string[] = []; let rows: { key: string; values: string[] }[] = [];
  if (params.relatorio === "caixa") {
    metrics = <div className="report-metrics"><Metric label="Caixas configurados" value="0" /><Metric label="Movimentos no período" value="0" /><Metric label="Saldo movimentado" value={money(0)} /></div>;
    supplementary = <section className="report-future-module"><strong>Controle de caixa em preparação</strong><p>Este relatório será alimentado por abertura, suprimentos, sangrias, recebimentos e fechamento de cada caixa. Lançamentos financeiros permanecem no Relatório de Lançamentos.</p></section>;
    headers = ["Data", "Caixa", "Movimento", "Operador", "Valor"]; rows = [];
  } else if (params.relatorio === "lancamentos") {
    const [entries, categories, methods, accounts] = await Promise.all([prisma.financialEntry.findMany({ where: { arenaId: auth.arenaId, createdAt: period, status: { not: "VOIDED" } }, include: { bankAccount: true }, orderBy: { createdAt: "desc" }, take: 250 }), prisma.financialCategory.findMany({ where: { arenaId: auth.arenaId, active: true }, orderBy: { name: "asc" } }), prisma.paymentMethodSetting.findMany({ where: { arenaId: auth.arenaId, active: true }, orderBy: { name: "asc" } }), prisma.bankAccount.findMany({ where: { arenaId: auth.arenaId, active: true }, orderBy: { name: "asc" } })]);
    const filtered = entries.filter((entry) => (!searchParams?.tipo || searchParams.tipo === "TODOS" || entry.type === searchParams.tipo) && (!searchParams?.situacao || searchParams.situacao === "TODOS" || entry.status === searchParams.situacao) && (!searchParams?.categoria || entry.category === searchParams.categoria) && (!searchParams?.forma || entry.paymentMethod === searchParams.forma) && (!searchParams?.banco || entry.bankAccountId === searchParams.banco));
    const revenue = filtered.filter((entry) => ["REVENUE", "INCOME"].includes(entry.type)).reduce((sum, entry) => sum + entry.amountCents, 0); const expense = filtered.filter((entry) => entry.type === "EXPENSE").reduce((sum, entry) => sum + entry.amountCents, 0);
    const grouped = (status: string) => Object.values(filtered.filter((entry) => entry.status === status).reduce<Record<string, { label: string; count: number; total: number }>>((result, entry) => { const label = entry.paymentMethod || "Sem forma de pagamento"; result[label] ??= { label, count: 0, total: 0 }; result[label].count += 1; result[label].total += entry.amountCents; return result; }, {}));
    metrics = <div className="report-metrics"><Metric label="Receitas" value={money(revenue)} tone="positive" /><Metric label="Despesas" value={money(expense)} tone="negative" /><Metric label="Resultado" value={money(revenue - expense)} tone={revenue >= expense ? "positive" : "negative"} /></div>;
    supplementary = <><form className="report-advanced-filter"><input type="hidden" name="inicio" value={searchParams?.inicio ?? start.toISOString().slice(0, 10)} /><input type="hidden" name="fim" value={searchParams?.fim ?? end.toISOString().slice(0, 10)} /><label>Tipo<select name="tipo" defaultValue={searchParams?.tipo ?? "TODOS"}><option value="TODOS">Todos</option><option value="REVENUE">Receitas</option><option value="EXPENSE">Despesas</option></select></label><label>Situação<select name="situacao" defaultValue={searchParams?.situacao ?? "TODOS"}><option value="TODOS">Todas</option><option value="PAID">Quitados</option><option value="PENDING">Em aberto</option></select></label><label>Categoria<select name="categoria" defaultValue={searchParams?.categoria ?? ""}><option value="">Todas</option>{categories.map((item) => <option key={item.id} value={item.name}>{item.name}</option>)}</select></label><label>Forma de pagamento<select name="forma" defaultValue={searchParams?.forma ?? ""}><option value="">Todas</option>{methods.map((item) => <option key={item.id} value={item.name}>{item.name}</option>)}</select></label><label>Conta bancária<select name="banco" defaultValue={searchParams?.banco ?? ""}><option value="">Todas</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="button button-primary button-small" type="submit">Aplicar filtros</button></form><div className="report-summaries"><Summary title="Quitados" rows={grouped("PAID")} /><Summary title="Em aberto" rows={grouped("PENDING")} /></div></>;
    headers = ["Data", "Descrição", "Categoria", "Tipo", "Valor", "Situação"]; rows = filtered.map((entry) => ({ key: entry.id, values: [date(entry.paidAt ?? entry.dueDate ?? entry.createdAt), entry.description, entry.category, ["REVENUE", "INCOME"].includes(entry.type) ? "Receita" : "Despesa", money(entry.amountCents), entry.status === "PAID" ? "Pago" : "Em aberto"] }));
  } else if (params.relatorio === "dre") {
    const entries = await prisma.financialEntry.findMany({ where: { arenaId: auth.arenaId, createdAt: period, status: { not: "VOIDED" } }, orderBy: { createdAt: "desc" }, take: 100 });
    const revenue = entries.filter((entry) => ["REVENUE", "INCOME"].includes(entry.type)).reduce((sum, entry) => sum + entry.amountCents, 0); const expense = entries.filter((entry) => entry.type === "EXPENSE").reduce((sum, entry) => sum + entry.amountCents, 0);
    metrics = <div className="report-metrics"><Metric label="Receitas" value={money(revenue)} tone="positive" /><Metric label="Despesas" value={money(expense)} tone="negative" /><Metric label="Resultado" value={money(revenue - expense)} tone={revenue >= expense ? "positive" : "negative"} /></div>;
    headers = ["Data", "Descrição", "Categoria", "Tipo", "Valor", "Situação"]; rows = entries.map((entry) => ({ key: entry.id, values: [date(entry.paidAt ?? entry.dueDate ?? entry.createdAt), entry.description, entry.category, ["REVENUE", "INCOME"].includes(entry.type) ? "Receita" : "Despesa", money(entry.amountCents), entry.status === "PAID" ? "Pago" : "Em aberto"] }));
  } else if (params.relatorio === "produtos") {
    const items = await prisma.saleItem.findMany({ where: { sale: { arenaId: auth.arenaId, createdAt: period } }, include: { product: true, sale: { select: { createdAt: true } } }, orderBy: { sale: { createdAt: "desc" } }, take: 100 }); const total = items.reduce((sum, item) => sum + item.totalCents, 0);
    metrics = <div className="report-metrics"><Metric label="Itens vendidos" value={items.reduce((sum, item) => sum + item.quantity, 0)} /><Metric label="Faturamento" value={money(total)} tone="positive" /><Metric label="Produtos movimentados" value={new Set(items.map((item) => item.productId)).size} /></div>; headers = ["Data", "Produto", "Quantidade", "Preço unitário", "Total"]; rows = items.map((item) => ({ key: item.id, values: [date(item.sale.createdAt), item.product.name, String(item.quantity), money(item.unitPriceCents), money(item.totalCents)] }));
  } else if (params.relatorio === "estoque") {
    const movements = await prisma.stockMovement.findMany({ where: { arenaId: auth.arenaId, createdAt: period }, include: { product: true }, orderBy: { createdAt: "desc" }, take: 100 }); metrics = <div className="report-metrics"><Metric label="Movimentações" value={movements.length} /><Metric label="Entradas" value={movements.filter((item) => item.type === "IN").reduce((sum, item) => sum + item.quantity, 0)} tone="positive" /><Metric label="Saídas" value={movements.filter((item) => item.type === "OUT").reduce((sum, item) => sum + item.quantity, 0)} tone="negative" /></div>; headers = ["Data", "Produto", "Tipo", "Quantidade", "Motivo"]; rows = movements.map((item) => ({ key: item.id, values: [date(item.createdAt), item.product.name, item.type === "IN" ? "Entrada" : item.type === "OUT" ? "Saída" : "Contagem", String(item.quantity), item.reason || "—"] }));
  } else if (params.relatorio === "comandas") {
    const comandas = await prisma.comanda.findMany({ where: { arenaId: auth.arenaId, openedAt: period }, include: { sale: true, _count: { select: { items: true } } }, orderBy: { openedAt: "desc" }, take: 100 }); metrics = <div className="report-metrics"><Metric label="Comandas" value={comandas.length} /><Metric label="Abertas" value={comandas.filter((item) => item.status === "OPEN").length} /><Metric label="Total finalizado" value={money(comandas.reduce((sum, item) => sum + (item.sale?.totalCents ?? 0), 0))} tone="positive" /></div>; headers = ["Abertura", "Comanda", "Cliente", "Itens", "Situação", "Total"]; rows = comandas.map((item) => ({ key: item.id, values: [date(item.openedAt), item.code, item.label, String(item._count.items), item.status === "OPEN" ? "Aberta" : "Finalizada", money(item.sale?.totalCents ?? 0)] }));
  } else if (params.relatorio === "planos") {
    const [subscriptionsRaw, teachers, planEntries] = await Promise.all([prisma.studentSubscription.findMany({ where: { arenaId: auth.arenaId, createdAt: period }, include: { plan: { include: { teacherAssignments: { where: { active: true } } } }, student: true }, orderBy: { createdAt: "desc" }, take: 250 }), prisma.teacher.findMany({ where: { arenaId: auth.arenaId, active: true }, orderBy: { name: "asc" } }), prisma.financialEntry.findMany({ where: { arenaId: auth.arenaId, planId: { not: null }, createdAt: period, status: { not: "VOIDED" } }, select: { planId: true, status: true } })]);
    const subscriptions = subscriptionsRaw.filter((item) => (!searchParams?.professor || item.plan.teacherAssignments.some((assignment) => assignment.teacherId === searchParams.professor)) && (!searchParams?.pagamento || searchParams.pagamento === "TODOS" || planEntries.some((entry) => entry.planId === item.planId && entry.status === searchParams.pagamento))); const active = subscriptions.filter((item) => item.status === "ACTIVE"); const planSales = Object.values(subscriptions.reduce<Record<string, { label: string; count: number; total: number }>>((result, item) => { result[item.plan.name] ??= { label: item.plan.name, count: 0, total: 0 }; result[item.plan.name].count += 1; result[item.plan.name].total += item.monthlyPriceCents; return result; }, {})).sort((a, b) => b.count - a.count); const monthlySales = Object.values(subscriptions.reduce<Record<string, { label: string; count: number; total: number }>>((result, item) => { const label = new Intl.DateTimeFormat("pt-BR", { month: "long", year: "numeric" }).format(item.createdAt); result[label] ??= { label, count: 0, total: 0 }; result[label].count += 1; result[label].total += item.monthlyPriceCents; return result; }, {})).sort((a, b) => b.count - a.count);
    metrics = <div className="report-metrics"><Metric label="Planos vendidos" value={subscriptions.length} tone="positive" /><Metric label="Assinaturas ativas" value={active.length} /><Metric label="Receita mensal ativa" value={money(active.reduce((sum, item) => sum + item.monthlyPriceCents, 0))} tone="positive" /></div>; supplementary = <><form className="report-advanced-filter"><input type="hidden" name="inicio" value={searchParams?.inicio ?? start.toISOString().slice(0, 10)} /><input type="hidden" name="fim" value={searchParams?.fim ?? end.toISOString().slice(0, 10)} /><label>Professor<select name="professor" defaultValue={searchParams?.professor ?? ""}><option value="">Todos</option>{teachers.map((teacher) => <option key={teacher.id} value={teacher.id}>{teacher.name}</option>)}</select></label><label>Status do pagamento<select name="pagamento" defaultValue={searchParams?.pagamento ?? "TODOS"}><option value="TODOS">Todos</option><option value="PAID">Pago</option><option value="PENDING">Em aberto</option><option value="OVERDUE">Vencido</option></select></label><button className="button button-primary button-small" type="submit">Aplicar filtros</button></form><div className="report-summaries"><Summary title="Planos mais vendidos" rows={planSales.slice(0, 5)} /><Summary title="Períodos com mais vendas" rows={monthlySales.slice(0, 5)} /></div></>; headers = ["Data", "Aluno", "Plano", "Aulas/mês", "Mensalidade", "Situação"]; rows = subscriptions.map((item) => ({ key: item.id, values: [date(item.createdAt), item.student.name, item.plan.name, String(item.classesPerMonth), money(item.monthlyPriceCents), item.status === "ACTIVE" ? "Ativa" : item.status] }));
  } else if (params.relatorio === "pagamentos-online") {
    const payments = await prisma.onlinePaymentCheckout.findMany({ where: { arenaId: auth.arenaId, createdAt: period }, include: { player: { select: { name: true } }, items: true }, orderBy: { createdAt: "desc" }, take: 250 }); const confirmed = payments.filter((item) => item.status === "PAID"); const pending = payments.filter((item) => item.status === "PENDING");
    metrics = <div className="report-metrics"><Metric label="Confirmados" value={money(confirmed.reduce((sum, item) => sum + item.amountCents, 0))} tone="positive" /><Metric label="Pendentes" value={money(pending.reduce((sum, item) => sum + item.amountCents, 0))} /><Metric label="Cobranças geradas" value={payments.length} /></div>; headers = ["Data", "Cliente", "Itens", "Provedor", "Valor", "Situação"]; rows = payments.map((item) => ({ key: item.id, values: [date(item.createdAt), item.player.name, String(item.items.length), item.provider, money(item.amountCents), item.status === "PAID" ? "Confirmado" : item.status === "FAILED" ? "Falhou" : "Pendente"] }));
  } else {
    const occurrences = await prisma.scheduleOccurrence.findMany({ where: { arenaId: auth.arenaId, startsAt: period }, include: { occurrenceCourts: { include: { court: true } }, participants: true }, orderBy: { startsAt: "desc" }, take: 100 }); metrics = <div className="report-metrics"><Metric label="Reservas" value={occurrences.length} /><Metric label="Canceladas" value={occurrences.filter((item) => item.status === "CANCELLED").length} tone="negative" /><Metric label="Participantes" value={occurrences.reduce((sum, item) => sum + item.participants.length, 0)} /></div>; headers = ["Data", "Reserva", "Quadra", "Participantes", "Situação"]; rows = occurrences.map((item) => ({ key: item.id, values: [date(item.startsAt), item.title, item.occurrenceCourts.map((court) => court.court.name).join(", ") || "—", String(item.participants.length), item.status === "CANCELLED" ? "Cancelada" : "Confirmada"] }));
  }
  return <div className="stack-md report-page"><header className="page-header"><div><p className="eyebrow">RELATÓRIOS</p><h1>{report[0]}</h1><p className="muted">{report[1]}</p></div><Link href="/relatorios" className="button button-small">Voltar aos relatórios</Link></header><SectionCard title="Período" description="Os indicadores e registros abaixo refletem o período selecionado."><form className="report-filter"><label>Data inicial<input name="inicio" type="date" defaultValue={searchParams?.inicio ?? start.toISOString().slice(0, 10)} /></label><label>Data final<input name="fim" type="date" defaultValue={searchParams?.fim ?? end.toISOString().slice(0, 10)} /></label><button className="button button-primary button-small" type="submit">Gerar relatório</button></form></SectionCard>{metrics}{supplementary}<SectionCard title="Registros do relatório" description="Até 250 registros mais recentes do período."><ReportRows headers={headers} rows={rows} /></SectionCard></div>;
}
