import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "muted": sharedUtilities.muted,
  "data_table": [
    "data-table", "ranking-detail-table", "tw:w-[100%]", "tw:[border-collapse:separate]",
    "tw:[border-spacing:0]", "tw:[&_thead_th]:pt-[0]", "tw:[&_thead_th]:pr-[12px]", "tw:[&_thead_th]:pb-[14px]",
    "tw:[&_thead_th]:pl-[12px]", "tw:[&_thead_th]:text-[0.78rem]", "tw:[&_thead_th]:font-[700]", "tw:[&_thead_th]:tracking-[0.1em]",
    "tw:[&_thead_th]:uppercase", "tw:[&_thead_th]:text-[color:var(--muted)]", "tw:[&_thead_th]:text-left", "tw:[&_tbody_tr]:bg-[color:#ffffff]",
    "tw:[&_tbody_tr]:[background-image:none]", "tw:[&_tbody_tr_+_tr_td]:border-t-[length:1px]", "tw:[&_tbody_tr_+_tr_td]:[border-top-style:solid]", "tw:[&_tbody_tr_+_tr_td]:border-t-[color:#edf2f7]",
    "tw:[&_tbody_td]:pt-[16px]", "tw:[&_tbody_td]:pr-[12px]", "tw:[&_tbody_td]:pb-[16px]", "tw:[&_tbody_td]:pl-[12px]",
    "tw:[&_tbody_td]:[vertical-align:middle]", "tw:[&_tbody_tr_td:first-child]:[border-top-left-radius:var(--radius-md)]", "tw:[&_tbody_tr_td:first-child]:[border-bottom-left-radius:var(--radius-md)]", "tw:[&_tbody_tr_td:last-child]:[border-top-right-radius:var(--radius-md)]",
    "tw:[&_tbody_tr_td:last-child]:[border-bottom-right-radius:var(--radius-md)]", "tw:viewport-760:block", "tw:viewport-760:[overflow-x:auto]",
  ].join(" "),
  "stack_md_ranking_detail_page": [
    "stack-md", "ranking-detail-page", "tw:grid", "tw:gap-y-[18px]",
    "tw:gap-x-[18px]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]",
    "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]",
    "tw:max-w-[1280px]", "tw:[&_.ranking-general-options]:grid", "tw:[&_.ranking-general-options]:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-680:[&_.ranking-general-options]:grid-cols-[1fr]",
    "tw:[&_.ranking-general-options]:gap-y-[12px]", "tw:[&_.ranking-general-options]:gap-x-[12px]", "tw:[&_.data-table]:w-[100%]", "tw:viewport-680:[&_.data-table]:min-w-[580px]",
    "tw:viewport-680:[&_.card:has(.ranking-detail-table)]:[overflow-x:auto]",
  ].join(" "),
  "page_header_ranking_detail_header": [
    "page-header", "ranking-detail-header", "tw:flex", "tw:viewport-760:grid",
    "tw:justify-between", "tw:[align-items:end]", "tw:viewport-680:items-start", "tw:gap-y-[18px]",
    "tw:gap-x-[18px]", "tw:mb-[0]", "tw:pt-[4px]", "tw:pr-[0]",
    "tw:pb-[18px]", "tw:pl-[0]", "tw:border-t-[length:0]", "tw:[border-top-style:none]",
    "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce7f1]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[0]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:[box-shadow:none]", "tw:[animation:hero-rise_620ms_var(--ease-standard)_both]", "tw:mt-[0]",
    "tw:mr-[0]", "tw:ml-[0]", "tw:[&_h1]:mt-[0]", "tw:[&_h1]:mr-[0]",
    "tw:[&_h1]:mb-[0]", "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[clamp(1.8rem,_2vw,_2.4rem)]", "tw:[&_h1]:leading-[1.04]",
    "tw:[&_h1]:tracking-[-0.04em]", "tw:[&_p]:max-w-[760px]", "tw:[&::after]:[content:'']", "tw:[&::after]:absolute",
    "tw:viewport-720:flex-col",
  ].join(" "),
  "ranking_detail_identity": [
    "ranking-detail-identity", "tw:grid", "tw:gap-y-[4px]", "tw:gap-x-[4px]",
    "tw:min-w-[0]", "tw:[&_>_span]:text-[color:#1a69ae]", "tw:[&_>_span]:text-[.65rem]", "tw:[&_>_span]:font-[800]",
    "tw:[&_>_span]:tracking-[.11em]", "tw:[&_h1]:mt-[0]", "tw:[&_h1]:mr-[0]", "tw:[&_h1]:mb-[0]",
    "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[color:#102b50]", "tw:[&_h1]:text-[clamp(1.45rem,_2vw,_2rem)]", "tw:[&_h1]:leading-[1.15]",
    "tw:[&_h1]:[overflow-wrap:anywhere]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#60778e]", "tw:[&_p]:text-[.8rem]",
  ].join(" "),
  "section_actions": sharedUtilities.sectionActions,
  "button": sharedUtilities.button,
  "section_card_ranking_detail_period": [
    "section-card", "stack-sm", "ranking-detail-period", "tw:pt-[22px]",
    "tw:pr-[0]", "tw:pb-[22px]", "tw:pl-[0]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#dae6f1]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#dae6f1]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dae6f1]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#dae6f1]", "tw:rounded-[10px]",
    "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:[box-shadow:0_5px_18px_rgb(25_59_96_/_.035)]", "tw:[&_>_.section-actions]:flex-wrap",
    "tw:[&_>_.section-actions]:gap-y-[7px]", "tw:[&_>_.section-actions]:gap-x-[7px]", "tw:[&_>_.section-actions_.button]:min-h-[35px]",
  ].join(" "),
  "stack_xs": [
    "stack-xs", "tw:grid", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
  ].join(" "),
  "button_primary": [
    "button-primary", "tw:border-t-[color:var(--brand)]", "tw:border-r-[color:var(--brand)]", "tw:border-b-[color:var(--brand)]",
    "tw:border-l-[color:var(--brand)]", "tw:bg-[color:var(--brand)]", "tw:[background-image:none]", "tw:text-[color:#ffffff]",
    "tw:hover:border-t-[color:var(--brand-strong)]", "tw:hover:border-r-[color:var(--brand-strong)]", "tw:hover:border-b-[color:var(--brand-strong)]", "tw:hover:border-l-[color:var(--brand-strong)]",
    "tw:hover:bg-[color:var(--brand-strong)]", "tw:hover:[background-image:none]",
  ].join(" "),
  "inline_form": sharedUtilities.inlineForm,
  "field": sharedUtilities.field,
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "section_actions_form_full": sharedUtilities.sectionActionsFormFull,
  "form_error": sharedUtilities.formError,
  "stack_md": sharedUtilities.stackMd,
  "section_card": sharedUtilities.sectionCard,
  "button_button_danger": sharedUtilities.buttonButtonDanger,
  "simple_list": sharedUtilities.simpleList,
  "simple_item": sharedUtilities.simpleItem,
} as const;
