import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "regulation_public_shell": [
    "regulation-public-shell", "tw:grid", "tw:grid-cols-[240px_minmax(0,_1fr)]", "tw:gap-y-[16px]",
    "tw:gap-x-[16px]", "tw:min-h-[100vh]", "tw:pt-[4px]", "tw:pr-[4px]",
    "tw:pb-[4px]", "tw:pl-[4px]",
  ].join(" "),
  "public_reg_aside_reveal_up": [
    "public-reg-aside", "reveal-up", "tw:flex", "tw:flex-col",
    "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:pt-[20px]", "tw:pr-[20px]",
    "tw:pb-[20px]", "tw:pl-[20px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[22px]", "tw:bg-[color:transparent]",
    "tw:[background-image:linear-gradient(165deg,_#f5f7ff_0%,_#eef2ff_100%)]", "tw:[box-shadow:var(--shadow)]", "tw:[animation:revealUp_380ms_var(--ease-standard)_both]",
  ].join(" "),
  "public_reg_brand": [
    "public-reg-brand", "tw:pb-[10px]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgba(77,_92,_166,_0.18)]", "tw:flex", "tw:items-center", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:mb-[10px]", "tw:[&_img]:w-[28px]", "tw:[&_img]:h-[28px]",
    "tw:[&_img]:rounded-[999px]", "tw:[&_img]:[object-fit:cover]", "tw:[&_img]:inline-flex", "tw:[&_img]:items-center",
    "tw:[&_img]:justify-center", "tw:[&_img]:font-[700]", "tw:[&_img]:text-[color:#3f4df0]", "tw:[&_img]:bg-[color:#ffffff]",
    "tw:[&_img]:[background-image:none]", "tw:[&_img]:border-t-[length:1px]", "tw:[&_img]:[border-top-style:solid]", "tw:[&_img]:border-t-[color:rgba(77,_92,_166,_0.25)]",
    "tw:[&_img]:border-r-[length:1px]", "tw:[&_img]:[border-right-style:solid]", "tw:[&_img]:border-r-[color:rgba(77,_92,_166,_0.25)]", "tw:[&_img]:border-b-[length:1px]",
    "tw:[&_img]:[border-bottom-style:solid]", "tw:[&_img]:border-b-[color:rgba(77,_92,_166,_0.25)]", "tw:[&_img]:border-l-[length:1px]", "tw:[&_img]:[border-left-style:solid]",
    "tw:[&_img]:border-l-[color:rgba(77,_92,_166,_0.25)]", "tw:[&_span]:w-[28px]", "tw:[&_span]:h-[28px]", "tw:[&_span]:rounded-[999px]",
    "tw:[&_span]:[object-fit:cover]", "tw:[&_span]:inline-flex", "tw:[&_span]:items-center", "tw:[&_span]:justify-center",
    "tw:[&_span]:font-[700]", "tw:[&_span]:text-[color:#3f4df0]", "tw:[&_span]:bg-[color:#ffffff]", "tw:[&_span]:[background-image:none]",
    "tw:[&_span]:border-t-[length:1px]", "tw:[&_span]:[border-top-style:solid]", "tw:[&_span]:border-t-[color:rgba(77,_92,_166,_0.25)]", "tw:[&_span]:border-r-[length:1px]",
    "tw:[&_span]:[border-right-style:solid]", "tw:[&_span]:border-r-[color:rgba(77,_92,_166,_0.25)]", "tw:[&_span]:border-b-[length:1px]", "tw:[&_span]:[border-bottom-style:solid]",
    "tw:[&_span]:border-b-[color:rgba(77,_92,_166,_0.25)]", "tw:[&_span]:border-l-[length:1px]", "tw:[&_span]:[border-left-style:solid]", "tw:[&_span]:border-l-[color:rgba(77,_92,_166,_0.25)]",
    "tw:[&_strong]:text-[0.84rem]",
  ].join(" "),
  "public_reg_kicker": [
    "public-reg-kicker", "tw:text-[color:#4d5ca6]", "tw:text-[0.78rem]", "tw:mt-[0]",
    "tw:mr-[0]", "tw:mb-[12px]", "tw:ml-[0]", "tw:tracking-[0.12em]",
    "tw:uppercase", "tw:font-[700]",
  ].join(" "),
  "public_reg_steps": [
    "public-reg-steps", "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:grid",
  ].join(" "),
  "public_reg_step_public_reg_step_done": [
    "public-reg-step", "public-reg-step-done", "tw:opacity-[1]", "tw:grid-cols-[28px_minmax(0,_1fr)]",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:[align-items:start]", "tw:grid",
    "tw:[transition:opacity_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_span]:w-[28px]", "tw:[&_span]:h-[28px]", "tw:[&_span]:border-t-[length:2px]",
    "tw:[&_span]:border-r-[length:2px]", "tw:[&_span]:border-b-[length:2px]", "tw:[&_span]:border-l-[length:2px]", "tw:[&_span]:[box-shadow:0_0_0_4px_rgba(99,_194,_122,_0.14)]",
    "tw:[&_span]:inline-flex", "tw:[&_span]:items-center", "tw:[&_span]:justify-center", "tw:[&_span]:rounded-[999px]",
    "tw:[&_span]:[border-top-style:solid]", "tw:[&_span]:border-t-[color:#24b76f]", "tw:[&_span]:[border-right-style:solid]", "tw:[&_span]:border-r-[color:#24b76f]",
    "tw:[&_span]:[border-bottom-style:solid]", "tw:[&_span]:border-b-[color:#24b76f]", "tw:[&_span]:[border-left-style:solid]", "tw:[&_span]:border-l-[color:#24b76f]",
    "tw:[&_span]:text-[color:#ffffff]", "tw:[&_span]:font-[700]", "tw:[&_span]:bg-[color:#24b76f]", "tw:[&_span]:[background-image:none]",
    "tw:[&_strong]:text-[0.88rem]", "tw:[&_strong]:block", "tw:[&_small]:block", "tw:[&_small]:text-[color:var(--muted)]",
    "tw:[&_small]:text-[0.76rem]",
  ].join(" "),
  "public_reg_step_public_reg_step_active": [
    "public-reg-step", "public-reg-step-active", "tw:opacity-[1]", "tw:grid-cols-[28px_minmax(0,_1fr)]",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:[align-items:start]", "tw:grid",
    "tw:[transition:opacity_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_span]:w-[28px]", "tw:[&_span]:h-[28px]", "tw:[&_span]:border-t-[length:2px]",
    "tw:[&_span]:border-r-[length:2px]", "tw:[&_span]:border-b-[length:2px]", "tw:[&_span]:border-l-[length:2px]", "tw:[&_span]:[box-shadow:0_0_0_4px_rgba(63,_77,_240,_0.16)]",
    "tw:[&_span]:inline-flex", "tw:[&_span]:items-center", "tw:[&_span]:justify-center", "tw:[&_span]:rounded-[999px]",
    "tw:[&_span]:[border-top-style:solid]", "tw:[&_span]:border-t-[color:#3f4df0]", "tw:[&_span]:[border-right-style:solid]", "tw:[&_span]:border-r-[color:#3f4df0]",
    "tw:[&_span]:[border-bottom-style:solid]", "tw:[&_span]:border-b-[color:#3f4df0]", "tw:[&_span]:[border-left-style:solid]", "tw:[&_span]:border-l-[color:#3f4df0]",
    "tw:[&_span]:text-[color:#3f4df0]", "tw:[&_span]:font-[700]", "tw:[&_span]:bg-[color:#ffffff]", "tw:[&_span]:[background-image:none]",
    "tw:[&_strong]:text-[0.88rem]", "tw:[&_strong]:block", "tw:[&_small]:block", "tw:[&_small]:text-[color:var(--muted)]",
    "tw:[&_small]:text-[0.76rem]",
  ].join(" "),
  "public_reg_status_card": [
    "public-reg-status-card", "tw:grid", "tw:grid-cols-[auto_minmax(0,_1fr)]", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:items-center", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgba(28,_140,_94,_0.22)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgba(28,_140,_94,_0.22)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgba(28,_140,_94,_0.22)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgba(28,_140,_94,_0.22)]", "tw:rounded-[12px]", "tw:bg-[color:transparent]",
    "tw:[background-image:linear-gradient(180deg,_rgba(28,_140,_94,_0.06),_rgba(255,_255,_255,_1))]", "tw:mt-[auto]", "tw:pt-[10px]", "tw:pr-[12px]",
    "tw:pb-[10px]", "tw:pl-[12px]", "tw:[&_strong]:block", "tw:[&_strong]:text-[0.9rem]",
    "tw:[&_p]:block", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:var(--muted)]", "tw:[&_p]:text-[0.78rem]", "tw:[&_.public-reg-status-icon]:w-[34px]",
    "tw:[&_.public-reg-status-icon]:h-[34px]",
  ].join(" "),
  "public_reg_status_icon": [
    "public-reg-status-icon", "tw:grid", "tw:place-items-center", "tw:w-[28px]",
    "tw:h-[28px]", "tw:rounded-[50%]", "tw:bg-[color:rgba(28,_140,_94,_0.12)]", "tw:[background-image:none]",
    "tw:text-[color:var(--success)]", "tw:font-[800]",
  ].join(" "),
  "regulation_public_main_reveal_up": [
    "regulation-public-main", "reveal-up", "tw:[animation-delay:120ms]", "tw:grid",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:pt-[10px]", "tw:pr-[4px]",
    "tw:pb-[4px]", "tw:pl-[4px]", "tw:[&_.regulation-public-content]:mt-[8px]", "tw:[animation:revealUp_380ms_var(--ease-standard)_both]",
  ].join(" "),
  "regulation_public_hero": [
    "regulation-public-hero", "tw:flex", "tw:justify-between", "tw:items-start",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:pt-[6px]", "tw:pr-[0]",
    "tw:pb-[2px]", "tw:pl-[0]", "tw:[&_h1]:mt-[0]", "tw:[&_h1]:mr-[0]",
    "tw:[&_h1]:mb-[0]", "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[clamp(1.6rem,_3vw,_2.4rem)]", "tw:[&_h1]:leading-[1]",
    "tw:[&_h1]:tracking-[-0.05em]",
  ].join(" "),
  "stack_xs": [
    "stack-xs", "tw:grid", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "muted": sharedUtilities.muted,
  "public_reg_hero_badge": [
    "public-reg-hero-badge", "tw:grid", "tw:grid-cols-[auto_minmax(0,_1fr)]", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:items-center", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:rgba(28,_140,_94,_0.22)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgba(28,_140,_94,_0.22)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgba(28,_140,_94,_0.22)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:rgba(28,_140,_94,_0.22)]", "tw:rounded-[12px]", "tw:bg-[color:transparent]",
    "tw:[background-image:linear-gradient(180deg,_rgba(28,_140,_94,_0.08),_rgba(255,_255,_255,_1))]", "tw:min-h-[42px]", "tw:pt-[8px]", "tw:pr-[10px]",
    "tw:pb-[8px]", "tw:pl-[10px]", "tw:text-[color:var(--success)]", "tw:whitespace-nowrap",
    "tw:[&_span]:grid", "tw:[&_span]:place-items-center", "tw:[&_span]:w-[28px]", "tw:[&_span]:h-[28px]",
    "tw:[&_span]:rounded-[50%]", "tw:[&_span]:bg-[color:rgba(28,_140,_94,_0.12)]", "tw:[&_span]:[background-image:none]", "tw:[&_span]:text-[color:var(--success)]",
    "tw:[&_span]:font-[800]", "tw:[&_strong]:block", "tw:[&_strong]:text-[0.9rem]", "tw:[&_small]:block",
    "tw:[&_small]:mt-[0]", "tw:[&_small]:mr-[0]", "tw:[&_small]:mb-[0]", "tw:[&_small]:ml-[0]",
    "tw:[&_small]:text-[color:var(--muted)]", "tw:[&_small]:text-[0.78rem]",
  ].join(" "),
  "regulation_public_content": [
    "regulation-public-content", "tw:grid", "tw:gap-y-[0]", "tw:gap-x-[0]",
    "tw:pt-[14px]", "tw:pr-[18px]", "tw:pb-[14px]", "tw:pl-[18px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dce5f1]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#dce5f1]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#dce5f1]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#dce5f1]",
    "tw:rounded-[18px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(180deg,_#ffffff,_#fbfcfe)]", "tw:[box-shadow:0_12px_26px_rgba(27,_46,_75,_0.07)]",
  ].join(" "),
  "regulation_public_content_head": [
    "regulation-public-content-head", "tw:grid", "tw:grid-cols-[52px_minmax(0,_1fr)]", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:items-center", "tw:pb-[14px]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e6edf5]", "tw:[&_strong]:text-[1rem]", "tw:[&_strong]:leading-[1.3]",
  ].join(" "),
  "regulation_public_content_icon": [
    "regulation-public-content-icon", "tw:grid", "tw:place-items-center", "tw:w-[52px]",
    "tw:h-[52px]", "tw:rounded-[50%]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(180deg,_#edf4ff,_#e3ecff)]",
    "tw:text-[color:var(--brand)]", "tw:text-[1.2rem]", "tw:[box-shadow:inset_0_0_0_1px_rgba(30,_94,_168,_0.1)]",
  ].join(" "),
  "regulation_public_list": [
    "regulation-public-list", "tw:[list-style:none]", "tw:pt-[0]", "tw:pr-[0]",
    "tw:pb-[0]", "tw:pl-[0]", "tw:mt-[0]", "tw:mr-[0]",
    "tw:mb-[0]", "tw:ml-[0]", "tw:grid", "tw:[counter-reset:regulation-line]",
    "tw:[&_li]:grid", "tw:[&_li]:grid-cols-[42px_minmax(0,_1fr)]", "tw:[&_li]:gap-y-[12px]", "tw:[&_li]:gap-x-[12px]",
    "tw:[&_li]:items-center", "tw:[&_li]:pt-[14px]", "tw:[&_li]:pr-[0]", "tw:[&_li]:pb-[14px]",
    "tw:[&_li]:pl-[0]", "tw:[&_li]:border-b-[length:1px]", "tw:[&_li]:[border-bottom-style:solid]", "tw:[&_li]:border-b-[color:#e6edf5]",
    "tw:[&_li]:text-[0.92rem]", "tw:[&_li]:leading-[1.45]", "tw:[&_li]:[counter-increment:regulation-line]", "tw:[&_li:last-child]:border-b-[length:0]",
    "tw:[&_li:last-child]:[border-bottom-style:none]", "tw:[&_li:last-child]:border-b-[color:currentColor]", "tw:[&_li::before]:[content:counter(regulation-line)]", "tw:[&_li::before]:grid",
    "tw:[&_li::before]:place-items-center", "tw:[&_li::before]:w-[30px]", "tw:[&_li::before]:h-[30px]", "tw:[&_li::before]:rounded-[999px]",
    "tw:[&_li::before]:bg-[color:#edf3ff]", "tw:[&_li::before]:[background-image:none]", "tw:[&_li::before]:text-[color:var(--brand)]", "tw:[&_li::before]:font-[700]",
    "tw:[&_li::before]:text-[0.78rem]", "tw:[&_li::marker]:[content:'']",
  ].join(" "),
} as const;
