import { cx } from "@/lib/ui/classes";
import { viewStyles } from "./page.utilities";
import Link from "next/link";
import { SafeActionForm } from "@/components/forms/safe-action-form";
import { SubmitButton } from "@/components/forms/submit-button";
import { OnlineBookingSettingsDialog } from "@/components/online-booking-settings-dialog";
import { copyCourtConfigurationAction, copyCourtWeeklyRuleAction, createCourtAction, createCourtWeeklyRuleAction, deleteCourtWeeklyRuleAction, moveCourtAction, updateCourtSettingsAction, updateCourtWeeklyRuleAction } from "@/lib/actions/calendar";
import { requireModuleView } from "@/lib/auth/guards";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";
type Props = { searchParams?: Promise<{ court?: string }> };
const weekDays = ["Domingo", "Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado"];
const durations = [30, 60, 90, 120, 150, 180, 210, 240];
const time = (value: number) => `${String(Math.floor(value / 60)).padStart(2, "0")}:${String(value % 60).padStart(2, "0")}`;
const price = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value / 100);
const priceInput = (value: number) => (value / 100).toFixed(2).replace(".", ",");
const duration = (value: number) => `${Math.floor(value / 60) ? `${Math.floor(value / 60)}h` : ""}${value % 60 || !Math.floor(value / 60) ? `${value % 60 || ""}${value < 60 ? "min" : ""}` : ""}`;

export default async function AgendaConfiguracaoPage(props: Props) {
  const searchParams = await props.searchParams;
  const auth = await requireModuleView("calendar");
  const [arena, courts] = await Promise.all([
    prisma.arena.findUniqueOrThrow({ where: { id: auth.arenaId }, select: { slug: true, onlineBookingLayout: true, onlineBookingRequiresConfirmation: true, onlineBookingShowReserved: true, onlineBookingPaymentEnabled: true, onlineBookingEnabled: true, onlineBookingLeadTimeMinutes: true, onlineBookingWhatsappMessage: true, onlineBookingWhatsappConfirmationEnabled: true } }),
    prisma.court.findMany({ where: { arenaId: auth.arenaId }, include: { weeklyRules: { orderBy: [{ weekday: "asc" }, { startsAtMinute: "asc" }] } }, orderBy: [{ active: "desc" }, { displayOrder: "asc" }, { name: "asc" }] })
  ]);
  const court = searchParams?.court ? courts.find((item) => item.id === searchParams.court) : undefined;
  return <div className={viewStyles.agenda_config_page}>
    <div className={viewStyles.agenda_config_online_control}><OnlineBookingSettingsDialog settings={{ arenaSlug: arena.slug, layout: arena.onlineBookingLayout, requiresConfirmation: arena.onlineBookingRequiresConfirmation, showReserved: arena.onlineBookingShowReserved, paymentOnlineEnabled: arena.onlineBookingPaymentEnabled, enabled: arena.onlineBookingEnabled, leadTimeMinutes: arena.onlineBookingLeadTimeMinutes, whatsappMessage: arena.onlineBookingWhatsappMessage, whatsappConfirmationEnabled: arena.onlineBookingWhatsappConfirmationEnabled }} /></div>
    <section className={viewStyles.agenda_config_toolbar}><nav className={viewStyles.agenda_court_tabs} aria-label="Quadras cadastradas">{courts.map((item) => <Link key={item.id} href={`/agenda/configuracao/${item.id}`} className={cx(item.id === court?.id ? viewStyles.agenda_court_tab_agenda_court_tab_active : viewStyles.agenda_court_tab)} style={{ borderLeftColor: item.color }}><i style={{ backgroundColor: item.color }} />{item.name}<span>{item.active ? "Ativa" : "Inativa"}</span></Link>)}{!courts.length ? <span className={viewStyles.agenda_court_tabs_empty}>Nenhuma quadra cadastrada.</span> : null}</nav><SafeActionForm action={createCourtAction} className={viewStyles.agenda_create_court_inline} resetOnSuccess successMessage="Quadra cadastrada."><input name="name" placeholder="Nova quadra" required /><SubmitButton label="Adicionar" pendingLabel="Salvando..." className={viewStyles.button_button_primary} /></SafeActionForm></section>
    {court ? <section className={viewStyles.agenda_court_workspace}><div className={viewStyles.agenda_court_workspace_bar}><strong>{court.name}</strong><span>Identidade, reserva online e períodos.</span></div>
      <div className={viewStyles.court_settings_grid}><SafeActionForm action={updateCourtSettingsAction} className={viewStyles.court_online_settings} successMessage="Configuração atualizada."><input type="hidden" name="courtId" value={court.id} /><label className={viewStyles.field}>Cor da quadra<input name="color" type="color" defaultValue={court.color} /></label><label className={viewStyles.field}>Intervalo para reserva online<select name="onlineSlotMinutes" defaultValue={court.onlineSlotMinutes}>{[15, 30, 45, 60].map((minutes) => <option key={minutes} value={minutes}>{minutes} minutos</option>)}</select></label><fieldset><legend>Combinações permitidas online</legend><div className={viewStyles.court_duration_options}>{durations.map((item) => <label key={item}><input name="onlineDurationMinutes" type="checkbox" value={item} defaultChecked={court.onlineDurationMinutes.includes(item)} />{duration(item)}</label>)}</div></fieldset><SubmitButton label="Salvar reserva online" pendingLabel="Salvando..." className={viewStyles.button_button_primary} /></SafeActionForm><div className={viewStyles.court_order_settings}><strong>Ordem na agenda</strong><p>Define a sequência das colunas da grade diária.</p><div><SafeActionForm action={moveCourtAction} className={viewStyles.court_order_action}><input type="hidden" name="courtId" value={court.id} /><input type="hidden" name="direction" value="up" /><SubmitButton label="↑ Subir" pendingLabel="..." className={viewStyles.button} /></SafeActionForm><SafeActionForm action={moveCourtAction} className={viewStyles.court_order_action}><input type="hidden" name="courtId" value={court.id} /><input type="hidden" name="direction" value="down" /><SubmitButton label="↓ Descer" pendingLabel="..." className={viewStyles.button} /></SafeActionForm></div></div></div>
      {courts.length > 1 ? <SafeActionForm action={copyCourtConfigurationAction} className={viewStyles.court_copy_settings} successMessage="Configuração aplicada." confirmKeyword="APLICAR" confirmPrompt="Atenção: esta alteração substituirá a grade de horários das quadras selecionadas. Horários já agendados podem ser perdidos. Digite APLICAR para continuar."><input type="hidden" name="sourceCourtId" value={court.id} /><strong>Aplicar a outras quadras</strong><span>Copia faixas, preço, disponibilidade e reserva online. Cor e ordem são preservadas.</span><div>{courts.filter((item) => item.id !== court.id).map((item) => <label key={item.id}><input name="targetCourtId" type="checkbox" value={item.id} />{item.name}</label>)}</div><SubmitButton label="Aplicar configuração" pendingLabel="Aplicando..." className={viewStyles.button} /></SafeActionForm> : null}
      <SafeActionForm action={createCourtWeeklyRuleAction} className={viewStyles.weekly_rule_form} resetOnSuccess successMessage="Faixa cadastrada."><input name="courtId" type="hidden" value={court.id} /><div className={viewStyles.field}><label>Dia da semana</label><select name="weekday" defaultValue="1">{weekDays.map((day, index) => <option key={day} value={index}>{day}</option>)}</select></div><div className={viewStyles.field}><label>Início</label><input name="startTime" type="time" defaultValue="07:00" required /></div><div className={viewStyles.field}><label>Fim</label><input name="endTime" type="time" defaultValue="08:00" required /></div><div className={viewStyles.field}><label>Valor por intervalo</label><input name="price" inputMode="decimal" defaultValue="0,00" required /></div><label className={viewStyles.checkbox_field}><input name="available" type="checkbox" defaultChecked />Disponível para reserva online</label><SubmitButton label="Adicionar faixa" pendingLabel="Salvando..." className={viewStyles.button_button_primary} /></SafeActionForm>
      <div className={viewStyles.weekly_rule_list}>{weekDays.map((day, weekday) => { const rules = court.weeklyRules.filter((rule) => rule.weekday === weekday); return <section key={day} className={viewStyles.weekly_rule_day}><h3>{day}</h3>{rules.length ? <ul>{rules.map((rule) => <li key={rule.id}><span>{time(rule.startsAtMinute)}–{time(rule.endsAtMinute)}</span><strong>{price(rule.priceCents)}</strong><span className={cx(rule.available ? "status-badge status-active" : "status-badge")}>{rule.available ? "Disponível" : "Indisponível"}</span><details className={viewStyles.weekly_rule_edit}><summary>Editar</summary><SafeActionForm action={updateCourtWeeklyRuleAction} className={viewStyles.weekly_rule_edit_form} successMessage="Faixa atualizada." closeClosestDetailsOnSuccess confirmKeyword="ALTERAR" confirmPrompt="Atenção: alterar esta grade de horários pode fazer com que horários já agendados sejam perdidos. Revise os agendamentos afetados e digite ALTERAR para continuar."><input type="hidden" name="ruleId" value={rule.id} /><label>Início<input name="startTime" type="time" defaultValue={time(rule.startsAtMinute)} required /></label><label>Fim<input name="endTime" type="time" defaultValue={time(rule.endsAtMinute)} required /></label><label>Valor por intervalo<input name="price" inputMode="decimal" defaultValue={priceInput(rule.priceCents)} required /></label><label className="weekly-rule-availability"><input name="available" type="checkbox" defaultChecked={rule.available} /><span>Disponível</span></label><SubmitButton label="Salvar" pendingLabel="Salvando..." className={viewStyles.button_button_primary_button_small} /></SafeActionForm></details><SafeActionForm action={copyCourtWeeklyRuleAction} className={viewStyles.weekly_rule_copy}><input type="hidden" name="ruleId" value={rule.id} /><select name="targetWeekday" aria-label={`Copiar período ${time(rule.startsAtMinute)} para outro dia`} defaultValue=""><option value="" disabled>Copiar para…</option><option value="ALL">Todos os períodos</option>{weekDays.map((targetDay, targetWeekday) => targetWeekday !== weekday ? <option value={targetWeekday} key={targetDay}>{targetDay}</option> : null)}</select><SubmitButton label="Copiar" pendingLabel="..." className={viewStyles.button_button_small} /></SafeActionForm><SafeActionForm action={deleteCourtWeeklyRuleAction} confirmKeyword="REMOVER" confirmPrompt="Atenção: remover esta faixa da grade pode fazer com que horários já agendados sejam perdidos. Digite REMOVER para continuar."><input type="hidden" name="ruleId" value={rule.id} /><SubmitButton label="Remover" pendingLabel="Removendo..." className={viewStyles.button_button_danger_button_small} /></SafeActionForm></li>)}</ul> : <p className={viewStyles.muted}>Sem faixa cadastrada.</p>}</section>; })}</div>
    </section> : <section className={viewStyles.agenda_court_empty}>Selecione uma quadra para configurar seus períodos.</section>}
  </div>;
}
