import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "agenda_config_page": [
    "agenda-config-page", "tw:grid", "tw:w-[100%]", "tw:gap-y-[16px]",
    "tw:gap-x-[16px]",
  ].join(" "),
  "agenda_config_online_control": [
    "agenda-config-online-control", "tw:flex", "tw:justify-end", "tw:mb-[8px]",
    "tw:[&_.agenda-online-settings-trigger]:static",
  ].join(" "),
  "agenda_config_toolbar": [
    "agenda-config-toolbar", "tw:flex", "tw:items-center", "tw:viewport-760:items-stretch",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:min-w-[0]", "tw:pt-[10px]",
    "tw:pr-[12px]", "tw:pb-[10px]", "tw:pl-[12px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[14px]",
    "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:[box-shadow:var(--shadow-sm)]", "tw:viewport-760:flex-col",
  ].join(" "),
  "agenda_court_tabs": [
    "agenda-court-tabs", "tw:flex", "tw:[flex:1]", "tw:min-w-[0]",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:[overflow-x:auto]", "tw:pb-[2px]",
    "tw:viewport-760:w-[100%]",
  ].join(" "),
  "agenda_court_tab_agenda_court_tab_active": [
    "agenda-court-tab", "agenda-court-tab-active", "tw:grid", "tw:gap-y-[2px]",
    "tw:gap-x-[2px]", "tw:min-w-[112px]", "tw:pt-[9px]", "tw:pr-[12px]",
    "tw:pb-[9px]", "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--primary)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--primary)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--primary)]", "tw:border-l-[length:5px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--primary)]", "tw:rounded-[9px]", "tw:text-[color:#fff]",
    "tw:[text-decoration:none]", "tw:text-[.84rem]", "tw:font-[700]", "tw:whitespace-nowrap",
    "tw:grid-cols-[8px_minmax(0,_1fr)]", "tw:[&_i]:w-[8px]", "tw:[&_i]:h-[8px]", "tw:[&_i]:[align-self:center]",
    "tw:[&_i]:rounded-[999px]", "tw:[&_span]:text-[color:color-mix(in_srgb,_#fff_78%,_transparent)]", "tw:[&_span]:text-[.68rem]", "tw:[&_span]:font-[600]",
    "tw:[&_span]:[grid-column:2]", "tw:hover:border-t-[color:var(--primary)]", "tw:hover:border-r-[color:var(--primary)]", "tw:hover:border-b-[color:var(--primary)]",
    "tw:hover:border-l-[color:var(--primary)]", "tw:hover:text-[color:var(--primary)]", "tw:bg-[color:var(--primary)]", "tw:[background-image:none]",
    "tw:[box-shadow:0_5px_12px_color-mix(in_srgb,_var(--primary)_28%,_transparent)]",
  ].join(" "),
  "agenda_court_tab": [
    "agenda-court-tab", "tw:grid", "tw:gap-y-[2px]", "tw:gap-x-[2px]",
    "tw:min-w-[112px]", "tw:pt-[9px]", "tw:pr-[12px]", "tw:pb-[9px]",
    "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:5px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[9px]", "tw:text-[color:var(--text)]", "tw:[text-decoration:none]",
    "tw:text-[.84rem]", "tw:font-[700]", "tw:whitespace-nowrap", "tw:grid-cols-[8px_minmax(0,_1fr)]",
    "tw:[&_i]:w-[8px]", "tw:[&_i]:h-[8px]", "tw:[&_i]:[align-self:center]", "tw:[&_i]:rounded-[999px]",
    "tw:[&_span]:text-[color:var(--muted)]", "tw:[&_span]:text-[.68rem]", "tw:[&_span]:font-[600]", "tw:[&_span]:[grid-column:2]",
    "tw:hover:border-t-[color:var(--primary)]", "tw:hover:border-r-[color:var(--primary)]", "tw:hover:border-b-[color:var(--primary)]", "tw:hover:border-l-[color:var(--primary)]",
    "tw:hover:text-[color:var(--primary)]",
  ].join(" "),
  "agenda_court_tabs_empty": [
    "agenda-court-tabs-empty", "tw:[align-self:center]", "tw:text-[color:var(--muted)]", "tw:text-[.84rem]",
  ].join(" "),
  "agenda_create_court_inline": [
    "agenda-create-court-inline", "tw:flex", "tw:[flex:0_0_auto]", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:items-center", "tw:[&_input]:w-[155px]", "tw:viewport-760:[&_input]:w-[auto]",
    "tw:[&_input]:min-h-[38px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[10px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[10px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[9px]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:text-[color:var(--text)]", "tw:viewport-760:w-[100%]", "tw:viewport-760:[&_input]:[flex:1]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "agenda_court_workspace": [
    "agenda-court-workspace", "tw:w-[100%]", "tw:pt-[18px]", "tw:viewport-760:pt-[14px]",
    "tw:pr-[18px]", "tw:viewport-760:pr-[14px]", "tw:pb-[18px]", "tw:viewport-760:pb-[14px]",
    "tw:pl-[18px]", "tw:viewport-760:pl-[14px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[14px]", "tw:bg-[color:var(--panel)]",
    "tw:[background-image:none]", "tw:[box-shadow:var(--shadow-sm)]", "tw:grid", "tw:gap-y-[16px]",
    "tw:gap-x-[16px]",
  ].join(" "),
  "agenda_court_workspace_bar": [
    "agenda-court-workspace-bar", "tw:flex", "tw:justify-between", "tw:gap-y-[12px]",
    "tw:viewport-760:gap-y-[3px]", "tw:gap-x-[12px]", "tw:viewport-760:gap-x-[3px]", "tw:items-baseline",
    "tw:viewport-760:items-start", "tw:[&_strong]:text-[1.08rem]", "tw:[&_span]:text-[color:var(--muted)]", "tw:[&_span]:text-[.84rem]",
    "tw:viewport-760:flex-col",
  ].join(" "),
  "court_settings_grid": [
    "court-settings-grid", "tw:grid", "tw:grid-cols-[minmax(0,_1.5fr)_minmax(210px,_.5fr)]", "tw:viewport-900:grid-cols-[repeat(2,_minmax(0,_1fr))]",
    "tw:viewport-700:grid-cols-[1fr]", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
  ].join(" "),
  "court_online_settings": [
    "court-online-settings", "tw:grid", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]", "tw:pl-[14px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]",
    "tw:rounded-[12px]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]", "tw:grid-cols-[100px_minmax(160px,_.7fr)_minmax(260px,_1.3fr)_auto]",
    "tw:viewport-900:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-700:grid-cols-[1fr]", "tw:[align-items:end]", "tw:[&_fieldset]:min-w-[0]",
    "tw:[&_fieldset]:mt-[0]", "tw:[&_fieldset]:mr-[0]", "tw:[&_fieldset]:mb-[0]", "tw:[&_fieldset]:ml-[0]",
    "tw:[&_fieldset]:pt-[0]", "tw:[&_fieldset]:pr-[0]", "tw:[&_fieldset]:pb-[0]", "tw:[&_fieldset]:pl-[0]",
    "tw:[&_fieldset]:border-t-[length:0]", "tw:[&_fieldset]:[border-top-style:none]", "tw:[&_fieldset]:border-t-[color:currentColor]", "tw:[&_fieldset]:border-r-[length:0]",
    "tw:[&_fieldset]:[border-right-style:none]", "tw:[&_fieldset]:border-r-[color:currentColor]", "tw:[&_fieldset]:border-b-[length:0]", "tw:[&_fieldset]:[border-bottom-style:none]",
    "tw:[&_fieldset]:border-b-[color:currentColor]", "tw:[&_fieldset]:border-l-[length:0]", "tw:[&_fieldset]:[border-left-style:none]", "tw:[&_fieldset]:border-l-[color:currentColor]",
    "tw:[&_legend]:mb-[6px]", "tw:[&_legend]:text-[.72rem]", "tw:[&_legend]:font-[700]", "tw:viewport-900:[&_fieldset]:[grid-column:1_/_-1]",
  ].join(" "),
  "field": sharedUtilities.field,
  "court_duration_options": [
    "court-duration-options", "tw:flex", "tw:flex-wrap", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:[&_label]:inline-flex", "tw:[&_label]:items-center", "tw:[&_label]:gap-y-[5px]",
    "tw:[&_label]:gap-x-[5px]", "tw:[&_label]:text-[.76rem]", "tw:[&_label]:font-[700]",
  ].join(" "),
  "court_order_settings": [
    "court-order-settings", "tw:grid", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]", "tw:pl-[14px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]",
    "tw:rounded-[12px]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]", "tw:[&_strong]:block",
    "tw:[&_strong]:mb-[-4px]", "tw:[&_strong]:text-[.94rem]", "tw:[&_strong]:leading-[1.25]", "tw:[&_p]:mt-[0]",
    "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:var(--muted)]",
    "tw:[&_p]:text-[.84rem]", "tw:[&_p]:leading-[1.45]", "tw:[&_>_div]:flex", "tw:[&_>_div]:gap-y-[10px]",
    "tw:[&_>_div]:gap-x-[10px]", "tw:[&_>_div]:items-start",
  ].join(" "),
  "court_order_action": [
    "court-order-action", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:min-w-[0]", "tw:[&_.form-success]:pt-[8px]", "tw:[&_.form-success]:pr-[10px]", "tw:[&_.form-success]:pb-[8px]",
    "tw:[&_.form-success]:pl-[10px]", "tw:[&_.form-success]:text-[.8rem]", "tw:[&_.form-error]:pt-[8px]", "tw:[&_.form-error]:pr-[10px]",
    "tw:[&_.form-error]:pb-[8px]", "tw:[&_.form-error]:pl-[10px]", "tw:[&_.form-error]:text-[.8rem]",
  ].join(" "),
  "button": sharedUtilities.button,
  "court_copy_settings": [
    "court-copy-settings", "tw:grid", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:pt-[14px]", "tw:pr-[14px]", "tw:pb-[14px]", "tw:pl-[14px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]",
    "tw:rounded-[12px]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]", "tw:[&_label]:inline-flex",
    "tw:[&_label]:items-center", "tw:[&_label]:gap-y-[5px]", "tw:[&_label]:gap-x-[5px]", "tw:[&_label]:text-[.76rem]",
    "tw:[&_label]:font-[700]", "tw:[&_span]:mt-[0]", "tw:[&_span]:mr-[0]", "tw:[&_span]:mb-[0]",
    "tw:[&_span]:ml-[0]", "tw:[&_span]:text-[color:var(--muted)]", "tw:[&_span]:text-[.84rem]", "tw:[&_span]:leading-[1.45]",
    "tw:[&_>_div]:flex", "tw:[&_>_div]:flex-wrap", "tw:[&_>_div]:gap-y-[10px]", "tw:[&_>_div]:gap-x-[10px]",
    "tw:[&_>_.button]:[justify-self:start]", "tw:[&_>_.button]:min-h-[34px]", "tw:[&_>_.button]:[padding-inline:11px]",
  ].join(" "),
  "weekly_rule_form": [
    "weekly-rule-form", "tw:grid", "tw:grid-cols-[1.4fr_repeat(3,_minmax(90px,_1fr))_minmax(150px,_1.3fr)_auto]", "tw:viewport-900:grid-cols-[repeat(2,_minmax(0,_1fr))]",
    "tw:viewport-700:grid-cols-[1fr]", "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:[align-items:end]",
  ].join(" "),
  "checkbox_field": [
    "checkbox-field", "tw:flex", "tw:gap-y-[7px]", "tw:gap-x-[7px]",
    "tw:items-center", "tw:min-h-[42px]", "tw:text-[.78rem]", "tw:font-[700]",
  ].join(" "),
  "weekly_rule_list": [
    "weekly-rule-list", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-700:grid-cols-[1fr]",
    "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:mt-[2px]",
  ].join(" "),
  "weekly_rule_day": [
    "weekly-rule-day", "tw:pt-[12px]", "tw:pr-[12px]", "tw:pb-[12px]",
    "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[10px]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]",
    "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[8px]", "tw:[&_h3]:ml-[0]",
    "tw:[&_h3]:text-[.82rem]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[.78rem]", "tw:[&_ul]:grid", "tw:[&_ul]:gap-y-[6px]",
    "tw:[&_ul]:gap-x-[6px]", "tw:[&_ul]:mt-[0]", "tw:[&_ul]:mr-[0]", "tw:[&_ul]:mb-[0]",
    "tw:[&_ul]:ml-[0]", "tw:[&_ul]:pt-[0]", "tw:[&_ul]:pr-[0]", "tw:[&_ul]:pb-[0]",
    "tw:[&_ul]:pl-[0]", "tw:[&_ul]:[list-style:none]", "tw:[&_li]:grid", "tw:[&_li]:grid-cols-[minmax(94px,_1fr)_minmax(86px,_auto)_minmax(104px,_auto)_auto]",
    "tw:viewport-700:[&_li]:grid-cols-[1fr_1fr]", "tw:[&_li]:gap-y-[8px]", "tw:[&_li]:gap-x-[8px]", "tw:[&_li]:items-center",
    "tw:[&_li]:pt-[7px]", "tw:[&_li]:pr-[8px]", "tw:[&_li]:pb-[7px]", "tw:[&_li]:pl-[8px]",
    "tw:[&_li]:rounded-[8px]", "tw:[&_li]:bg-[color:var(--panel)]", "tw:[&_li]:[background-image:none]", "tw:[&_li]:text-[.78rem]",
  ].join(" "),
  "weekly_rule_edit": [
    "weekly-rule-edit", "tw:relative", "tw:[&_>_summary]:text-[color:var(--brand-strong)]", "tw:[&_>_summary]:text-[.72rem]",
    "tw:[&_>_summary]:font-[750]", "tw:[&_>_summary]:cursor-pointer", "tw:[&_>_summary]:[list-style:none]", "tw:[&_>_summary::-webkit-details-marker]:hidden",
    "tw:[&_>_summary::after]:[content:'⌄']", "tw:[&_>_summary::after]:ml-[4px]", "tw:[&[open]_>_summary::after]:[content:'⌃']",
  ].join(" "),
  "weekly_rule_edit_form": [
    "weekly-rule-edit-form", "tw:absolute", "tw:z-[12]", "tw:top-[calc(100%_+_6px)]",
    "tw:right-[0]", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(110px,_1fr))]", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:w-[min(370px,_80vw)]", "tw:pt-[11px]", "tw:pr-[11px]",
    "tw:pb-[11px]", "tw:pl-[11px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#cfddea]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#cfddea]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#cfddea]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#cfddea]", "tw:rounded-[9px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[box-shadow:0_12px_28px_rgb(21_55_85_/_.18)]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[3px]",
    "tw:[&_label]:gap-x-[3px]", "tw:[&_label]:text-[color:#526981]", "tw:[&_label]:text-[.64rem]", "tw:[&_label]:font-[750]",
    "tw:[&_input]:min-w-[0]", "tw:[&_input]:min-h-[31px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[7px]",
    "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[7px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]",
    "tw:[&_input]:border-t-[color:#c9d8e7]", "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:#c9d8e7]",
    "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:#c9d8e7]", "tw:[&_input]:border-l-[length:1px]",
    "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:#c9d8e7]", "tw:[&_input]:rounded-[6px]", "tw:[&_input]:text-[color:#173a5d]",
    "tw:[&_input]:[font:inherit]", "tw:[&_input]:text-[.74rem]", "tw:[&_.checkbox-field]:min-h-[31px]", "tw:[&_.button]:[justify-self:end]",
    "tw:[&_.weekly-rule-availability]:inline-flex", "tw:[&_.weekly-rule-availability]:gap-y-[6px]", "tw:[&_.weekly-rule-availability]:gap-x-[6px]", "tw:[&_.weekly-rule-availability]:items-center",
    "tw:[&_.weekly-rule-availability]:min-h-[31px]", "tw:[&_.weekly-rule-availability]:pt-[0]", "tw:[&_.weekly-rule-availability]:pr-[2px]", "tw:[&_.weekly-rule-availability]:pb-[0]",
    "tw:[&_.weekly-rule-availability]:pl-[2px]", "tw:[&_.weekly-rule-availability]:text-[.68rem]", "tw:[&_.weekly-rule-availability_input]:w-[15px]", "tw:[&_.weekly-rule-availability_input]:min-h-[15px]",
    "tw:[&_.weekly-rule-availability_input]:[accent-color:#168149]",
  ].join(" "),
  "button_button_primary_button_small": sharedUtilities.buttonButtonPrimaryButtonSmall,
  "weekly_rule_copy": [
    "weekly-rule-copy", "tw:inline-flex", "tw:items-center", "tw:gap-y-[4px]",
    "tw:gap-x-[4px]", "tw:[&_select]:max-w-[118px]", "tw:[&_select]:min-h-[27px]", "tw:[&_select]:pt-[3px]",
    "tw:[&_select]:pr-[5px]", "tw:[&_select]:pb-[3px]", "tw:[&_select]:pl-[5px]", "tw:[&_select]:text-[.68rem]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "button_button_danger_button_small": sharedUtilities.buttonButtonDangerButtonSmall,
  "muted": sharedUtilities.muted,
  "agenda_court_empty": [
    "agenda-court-empty", "tw:w-[100%]", "tw:pt-[18px]", "tw:pr-[18px]",
    "tw:pb-[18px]", "tw:pl-[18px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[14px]", "tw:bg-[color:var(--panel)]",
    "tw:[background-image:none]", "tw:[box-shadow:var(--shadow-sm)]", "tw:text-[color:var(--muted)]", "tw:text-[.84rem]",
  ].join(" "),
} as const;
