import Link from "next/link";
import { SafeActionForm } from "@/components/forms/safe-action-form";
import { SubmitButton } from "@/components/forms/submit-button";
import { copyCourtConfigurationAction, createCourtAction, createCourtWeeklyRuleAction, deleteCourtWeeklyRuleAction, moveCourtAction, updateCourtSettingsAction } from "@/lib/actions/calendar";
import { requireModuleView } from "@/lib/auth/guards";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";
type Props = { searchParams?: { court?: string } };
const weekDays = ["Domingo", "Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado"];
const durations = [30, 60, 90, 120, 150, 180, 210, 240];
const time = (value: number) => `${String(Math.floor(value / 60)).padStart(2, "0")}:${String(value % 60).padStart(2, "0")}`;
const price = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value / 100);
const duration = (value: number) => `${Math.floor(value / 60) ? `${Math.floor(value / 60)}h` : ""}${value % 60 || !Math.floor(value / 60) ? `${value % 60 || ""}${value < 60 ? "min" : ""}` : ""}`;

export default async function AgendaConfiguracaoPage({ searchParams }: Props) {
  const auth = await requireModuleView("calendar");
  const courts = await prisma.court.findMany({ where: { arenaId: auth.arenaId }, include: { weeklyRules: { orderBy: [{ weekday: "asc" }, { startsAtMinute: "asc" }] } }, orderBy: [{ active: "desc" }, { displayOrder: "asc" }, { name: "asc" }] });
  const court = searchParams?.court ? courts.find((item) => item.id === searchParams.court) : undefined;
  return <div className="agenda-config-page">
    <section className="agenda-config-toolbar"><nav className="agenda-court-tabs" aria-label="Quadras cadastradas">{courts.map((item) => <Link key={item.id} href={`/agenda/configuracao/${item.id}`} className={item.id === court?.id ? "agenda-court-tab agenda-court-tab-active" : "agenda-court-tab"} style={{ borderLeftColor: item.color }}><i style={{ backgroundColor: item.color }} />{item.name}<span>{item.active ? "Ativa" : "Inativa"}</span></Link>)}{!courts.length ? <span className="agenda-court-tabs-empty">Nenhuma quadra cadastrada.</span> : null}</nav><SafeActionForm action={createCourtAction} className="agenda-create-court-inline" resetOnSuccess successMessage="Quadra cadastrada."><input name="name" placeholder="Nova quadra" required /><SubmitButton label="Adicionar" pendingLabel="Salvando..." className="button button-primary" /></SafeActionForm></section>
    {court ? <section className="agenda-court-workspace"><div className="agenda-court-workspace-bar"><strong>{court.name}</strong><span>Identidade, reserva online e períodos.</span></div>
      <div className="court-settings-grid"><SafeActionForm action={updateCourtSettingsAction} className="court-online-settings" successMessage="Configuração atualizada."><input type="hidden" name="courtId" value={court.id} /><label className="field">Cor da quadra<input name="color" type="color" defaultValue={court.color} /></label><label className="field">Intervalo para reserva online<select name="onlineSlotMinutes" defaultValue={court.onlineSlotMinutes}>{[15, 30, 45, 60].map((minutes) => <option key={minutes} value={minutes}>{minutes} minutos</option>)}</select></label><fieldset><legend>Combinações permitidas online</legend><div className="court-duration-options">{durations.map((item) => <label key={item}><input name="onlineDurationMinutes" type="checkbox" value={item} defaultChecked={court.onlineDurationMinutes.includes(item)} />{duration(item)}</label>)}</div></fieldset><SubmitButton label="Salvar reserva online" pendingLabel="Salvando..." className="button button-primary" /></SafeActionForm><div className="court-order-settings"><strong>Ordem na agenda</strong><p>Define a sequência das colunas da grade diária.</p><div><SafeActionForm action={moveCourtAction} className="court-order-action"><input type="hidden" name="courtId" value={court.id} /><input type="hidden" name="direction" value="up" /><SubmitButton label="↑ Subir" pendingLabel="..." className="button" /></SafeActionForm><SafeActionForm action={moveCourtAction} className="court-order-action"><input type="hidden" name="courtId" value={court.id} /><input type="hidden" name="direction" value="down" /><SubmitButton label="↓ Descer" pendingLabel="..." className="button" /></SafeActionForm></div></div></div>
      {courts.length > 1 ? <SafeActionForm action={copyCourtConfigurationAction} className="court-copy-settings" successMessage="Configuração aplicada."><input type="hidden" name="sourceCourtId" value={court.id} /><strong>Aplicar a outras quadras</strong><span>Copia faixas, preço, disponibilidade e reserva online. Cor e ordem são preservadas.</span><div>{courts.filter((item) => item.id !== court.id).map((item) => <label key={item.id}><input name="targetCourtId" type="checkbox" value={item.id} />{item.name}</label>)}</div><SubmitButton label="Aplicar configuração" pendingLabel="Aplicando..." className="button" /></SafeActionForm> : null}
      <SafeActionForm action={createCourtWeeklyRuleAction} className="weekly-rule-form" resetOnSuccess successMessage="Faixa cadastrada."><input name="courtId" type="hidden" value={court.id} /><div className="field"><label>Dia da semana</label><select name="weekday" defaultValue="1">{weekDays.map((day, index) => <option key={day} value={index}>{day}</option>)}</select></div><div className="field"><label>Início</label><input name="startTime" type="time" defaultValue="07:00" required /></div><div className="field"><label>Fim</label><input name="endTime" type="time" defaultValue="08:00" required /></div><div className="field"><label>Valor do horário</label><input name="price" inputMode="decimal" defaultValue="0,00" required /></div><label className="checkbox-field"><input name="available" type="checkbox" defaultChecked />Disponível para reserva online</label><SubmitButton label="Adicionar faixa" pendingLabel="Salvando..." className="button button-primary" /></SafeActionForm>
      <div className="weekly-rule-list">{weekDays.map((day, weekday) => { const rules = court.weeklyRules.filter((rule) => rule.weekday === weekday); return <section key={day} className="weekly-rule-day"><h3>{day}</h3>{rules.length ? <ul>{rules.map((rule) => <li key={rule.id}><span>{time(rule.startsAtMinute)}–{time(rule.endsAtMinute)}</span><strong>{price(rule.priceCents)}</strong><span className={rule.available ? "status-badge status-active" : "status-badge"}>{rule.available ? "Disponível" : "Indisponível"}</span><SafeActionForm action={deleteCourtWeeklyRuleAction}><input type="hidden" name="ruleId" value={rule.id} /><SubmitButton label="Remover" pendingLabel="Removendo..." className="button button-danger button-small" /></SafeActionForm></li>)}</ul> : <p className="muted">Sem faixa cadastrada.</p>}</section>; })}</div>
    </section> : <section className="agenda-court-empty">Selecione uma quadra para configurar seus períodos.</section>}
  </div>;
}
