import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "stack_md": sharedUtilities.stackMd,
  "page_header": sharedUtilities.pageHeader,
  "stack_xs": [
    "stack-xs", "tw:grid", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "muted": sharedUtilities.muted,
  "calendar_workspace": [
    "calendar-workspace", "tw:grid", "tw:grid-cols-[320px_minmax(0,_1fr)]", "tw:viewport-1024:grid-cols-[1fr]",
    "tw:gap-y-[18px]", "tw:gap-x-[18px]", "tw:[align-items:start]",
  ].join(" "),
  "calendar_side_panel": [
    "calendar-side-panel", "tw:grid", "tw:gap-y-[16px]", "tw:gap-x-[16px]",
    "tw:sticky", "tw:viewport-1024:static", "tw:top-[24px]",
  ].join(" "),
  "calendar_mini_card": [
    "calendar-mini-card", "tw:grid", "tw:gap-y-[16px]", "tw:gap-x-[16px]",
    "tw:pt-[18px]", "tw:pr-[18px]", "tw:pb-[18px]", "tw:pl-[18px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]",
    "tw:rounded-[18px]", "tw:bg-[color:#ffffff]", "tw:[background-image:none]", "tw:[box-shadow:var(--shadow-soft)]",
    "tw:[&_h2]:mt-[0]", "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]",
    "tw:[&_h2]:text-[color:var(--text)]", "tw:[&_h2]:text-[1.05rem]",
  ].join(" "),
  "calendar_mini_head": [
    "calendar-mini-head", "tw:flex", "tw:items-center", "tw:justify-between",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:[&_strong]:text-[color:var(--text)]", "tw:[&_strong]:[text-transform:capitalize]",
    "tw:[&_div]:inline-flex", "tw:[&_div]:gap-y-[8px]", "tw:[&_div]:gap-x-[8px]", "tw:[&_a]:inline-flex",
    "tw:[&_a]:items-center", "tw:[&_a]:justify-center", "tw:[&_a]:w-[34px]", "tw:[&_a]:h-[34px]",
    "tw:[&_a]:rounded-[999px]", "tw:[&_a]:text-[color:var(--brand)]", "tw:[&_a]:[text-decoration:none]", "tw:[&_a]:text-[1.55rem]",
    "tw:[&_a]:leading-[1]", "tw:[&_a]:[transition:background-color_160ms_ease,_color_160ms_ease]", "tw:[&_a:hover]:bg-[color:var(--brand-soft)]", "tw:[&_a:hover]:[background-image:none]",
    "tw:[&_a:hover]:text-[color:var(--brand-strong)]",
  ].join(" "),
  "calendar_mini_weekdays": [
    "calendar-mini-weekdays", "tw:grid", "tw:grid-cols-[repeat(7,_minmax(0,_1fr))]", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:text-center", "tw:text-[color:var(--muted)]", "tw:text-[0.72rem]",
  ].join(" "),
  "calendar_mini_grid": [
    "calendar-mini-grid", "tw:grid", "tw:grid-cols-[repeat(7,_minmax(0,_1fr))]", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:text-center",
  ].join(" "),
  "calendar_mini_day": [
    "calendar-mini-day", "tw:relative", "tw:inline-flex", "tw:items-center",
    "tw:justify-center", "tw:min-h-[32px]", "tw:rounded-[999px]", "tw:text-[color:var(--text)]",
    "tw:text-[0.86rem]", "tw:[text-decoration:none]",
  ].join(" "),
  "calendar_mini_muted": [
    "calendar-mini-muted", "tw:text-[color:var(--muted)]", "tw:opacity-[0.58]",
  ].join(" "),
  "calendar_mini_active": [
    "calendar-mini-active", "tw:bg-[color:var(--brand)]", "tw:[background-image:none]", "tw:text-[color:#ffffff]",
    "tw:font-[800]", "tw:[&::after]:bg-[color:#ffffff]", "tw:[&::after]:[background-image:none]",
  ].join(" "),
  "calendar_mini_has_events": [
    "calendar-mini-has-events", "tw:[&::after]:[content:'']", "tw:[&::after]:absolute", "tw:[&::after]:bottom-[3px]",
    "tw:[&::after]:w-[4px]", "tw:[&::after]:h-[4px]", "tw:[&::after]:rounded-[999px]", "tw:[&::after]:bg-[color:var(--brand)]",
    "tw:[&::after]:[background-image:none]",
  ].join(" "),
  "calendar_filter_stack": [
    "calendar-filter-stack", "tw:grid", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
  ].join(" "),
  "field": sharedUtilities.field,
  "button_button_primary_button_block": sharedUtilities.buttonButtonPrimaryButtonBlock,
  "button_button_block": [
    "button", "button-block", "tw:inline-flex", "tw:items-center",
    "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:min-h-[36px]",
    "tw:pt-[0]", "tw:pr-[12px]", "tw:pb-[0]", "tw:pl-[12px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]",
    "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:text-[color:var(--text)]",
    "tw:text-[0.86rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--line-strong)]", "tw:hover:border-r-[color:var(--line-strong)]",
    "tw:hover:border-b-[color:var(--line-strong)]", "tw:hover:border-l-[color:var(--line-strong)]", "tw:hover:[transform:translateY(-1px)]", "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]",
    "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]", "tw:[&:active]:[box-shadow:none]",
    "tw:w-[100%]",
  ].join(" "),
  "calendar_agenda_board_calendar_drag_scroll": [
    "calendar-agenda-board", "calendar-drag-scroll", "tw:[overflow-x:auto]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[18px]",
    "tw:bg-[color:#ffffff]", "tw:[background-image:none]", "tw:cursor-grab", "tw:[&.calendar-dragging]:cursor-grabbing",
    "tw:[&.calendar-dragging_*]:select-none",
  ].join(" "),
  "calendar_agenda_days": [
    "calendar-agenda-days", "tw:grid", "tw:min-w-[860px]", "tw:sticky",
    "tw:top-[0]", "tw:z-[2]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:bg-[color:#f7f9fc]", "tw:[background-image:none]", "tw:[&_>_span]:sticky",
    "tw:[&_>_span]:left-[0]", "tw:[&_>_span]:z-[4]", "tw:[&_>_span]:bg-[color:#f7f9fc]", "tw:[&_>_span]:[background-image:none]",
    "tw:[&_>_span]:border-r-[length:1px]", "tw:[&_>_span]:[border-right-style:solid]", "tw:[&_>_span]:border-r-[color:var(--line)]",
  ].join(" "),
  "calendar_agenda_day_calendar_agenda_day_today": [
    "calendar-agenda-day", "calendar-agenda-day-today", "tw:grid", "tw:gap-y-[4px]",
    "tw:gap-x-[4px]", "tw:[justify-items:center]", "tw:min-h-[86px]", "tw:pt-[18px]",
    "tw:pr-[10px]", "tw:pb-[18px]", "tw:pl-[10px]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:text-[color:#6b819d]", "tw:[&_span]:text-[0.76rem]",
    "tw:[&_span]:font-[800]", "tw:[&_span]:uppercase", "tw:[&_span]:tracking-[0.06em]", "tw:[&_strong]:text-[color:var(--brand)]",
    "tw:[&_strong]:text-[1.6rem]", "tw:[&_span]:text-[color:var(--brand)]",
  ].join(" "),
  "calendar_agenda_day": [
    "calendar-agenda-day", "tw:grid", "tw:gap-y-[4px]", "tw:gap-x-[4px]",
    "tw:[justify-items:center]", "tw:min-h-[86px]", "tw:pt-[18px]", "tw:pr-[10px]",
    "tw:pb-[18px]", "tw:pl-[10px]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:text-[color:#6b819d]", "tw:[&_span]:text-[0.76rem]", "tw:[&_span]:font-[800]",
    "tw:[&_span]:uppercase", "tw:[&_span]:tracking-[0.06em]", "tw:[&_strong]:text-[color:#56718f]", "tw:[&_strong]:text-[1.6rem]",
  ].join(" "),
  "calendar_agenda_grid": [
    "calendar-agenda-grid", "tw:grid", "tw:min-w-[860px]",
  ].join(" "),
  "calendar_time_column": [
    "calendar-time-column", "tw:grid", "tw:grid-rows-[repeat(17,_72px)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:bg-[color:#ffffff]", "tw:[background-image:none]",
    "tw:sticky", "tw:left-[0]", "tw:z-[3]", "tw:[&_span]:pt-[0]",
    "tw:[&_span]:pr-[12px]", "tw:[&_span]:pb-[0]", "tw:[&_span]:pl-[12px]", "tw:[&_span]:text-[color:#587494]",
    "tw:[&_span]:text-[0.82rem]", "tw:[&_span]:font-[700]", "tw:[&_span]:[transform:translateY(-8px)]",
  ].join(" "),
  "calendar_time_day": [
    "calendar-time-day", "tw:relative", "tw:min-h-[1224px]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:bg-[color:#ffffff]", "tw:[background-image:none]",
  ].join(" "),
  "calendar_hour_line": [
    "calendar-hour-line", "tw:block", "tw:h-[72px]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#e7edf5]",
  ].join(" "),
  "calendar_time_event": [
    "calendar-time-event", "tw:absolute", "tw:left-[8px]", "tw:right-[8px]",
    "tw:border-t-[length:medium]", "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:medium]",
    "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:medium]", "tw:[border-bottom-style:none]",
    "tw:border-b-[color:currentColor]", "tw:border-l-[length:6px]", "tw:[border-left-style:solid]", "tw:border-l-[color:currentColor]",
    "tw:grid", "tw:[align-content:space-between]", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:pt-[12px]", "tw:pr-[12px]",
    "tw:pb-[12px]", "tw:pl-[12px]", "tw:rounded-[0_14px_14px_0]", "tw:text-left",
    "tw:cursor-pointer", "tw:[text-decoration:none]", "tw:[box-shadow:0_10px_22px_rgba(35,_50,_70,_0.08)]", "tw:[&_strong]:text-[color:inherit]",
    "tw:[&_strong]:text-[0.9rem]", "tw:[&_strong]:leading-[1.2]", "tw:[&_span]:text-[color:inherit]", "tw:[&_span]:text-[0.78rem]",
    "tw:[&_span]:font-[800]", "tw:[&.calendar-time-event-lessons]:bg-[color:rgba(43,_122,_95,_0.12)]", "tw:[&.calendar-time-event-lessons]:[background-image:none]", "tw:[&.calendar-time-event-lessons]:text-[color:#2b7a5f]",
    "tw:[&.calendar-time-event-tournaments]:bg-[color:rgba(147,_100,_12,_0.14)]", "tw:[&.calendar-time-event-tournaments]:[background-image:none]", "tw:[&.calendar-time-event-tournaments]:text-[color:#93640c]", "tw:[&.calendar-time-event-matches]:bg-[color:rgba(18,_93,_156,_0.12)]",
    "tw:[&.calendar-time-event-matches]:[background-image:none]", "tw:[&.calendar-time-event-matches]:text-[color:#125d9c]", "tw:[&.calendar-time-event-tv]:bg-[color:rgba(110,_76,_181,_0.13)]", "tw:[&.calendar-time-event-tv]:[background-image:none]",
    "tw:[&.calendar-time-event-tv]:text-[color:#6e4cb5]",
  ].join(" "),
} as const;
