import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "sponsor_empty_state": [
    "sponsor-empty-state", "tw:grid", "tw:gap-y-[5px]", "tw:gap-x-[5px]",
    "tw:max-w-[520px]", "tw:pt-[18px]", "tw:pr-[18px]", "tw:pb-[18px]",
    "tw:pl-[18px]", "tw:border-t-[length:1px]", "tw:[border-top-style:dashed]", "tw:border-t-[color:#c8d8e8]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:dashed]", "tw:border-r-[color:#c8d8e8]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:dashed]", "tw:border-b-[color:#c8d8e8]", "tw:border-l-[length:1px]", "tw:[border-left-style:dashed]",
    "tw:border-l-[color:#c8d8e8]", "tw:rounded-[14px]", "tw:bg-[color:#f8fbfe]", "tw:[background-image:none]",
    "tw:text-[color:#526987]", "tw:[&_strong]:text-[color:#132d58]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#6f829f]", "tw:[&_p]:text-[.82rem]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "stack_md": [
    "stack-md", "sponsorship-plan-workspace", "tw:grid", "tw:gap-y-[18px]",
    "tw:gap-x-[18px]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]",
    "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]",
  ].join(" "),
  "sponsorship_back": [
    "sponsorship-back", "tw:w-[fit-content]", "tw:text-[color:#1661bd]", "tw:text-[.83rem]",
    "tw:font-[750]",
  ].join(" "),
  "sponsorship_plan_hero": [
    "sponsorship-plan-hero", "tw:flex", "tw:items-center", "tw:viewport-680:items-stretch",
    "tw:justify-between", "tw:gap-y-[18px]", "tw:gap-x-[18px]", "tw:pt-[8px]",
    "tw:pr-[0]", "tw:pb-[18px]", "tw:pl-[0]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce7f2]", "tw:[&_h1]:mt-[5px]", "tw:[&_h1]:mr-[0]",
    "tw:[&_h1]:mb-[5px]", "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[color:#173466]", "tw:[&_h1]:text-[clamp(1.45rem,_2.4vw,_2.05rem)]",
    "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
    "tw:[&_p]:text-[color:#62799a]", "tw:viewport-680:flex-col", "tw:viewport-680:[&_>_.button]:w-[100%]", "tw:viewport-680:[&_>_.button]:justify-center",
  ].join(" "),
  "eyebrow": sharedUtilities.eyebrow,
  "sponsorship_metrics": [
    "sponsorship-metrics", "tw:grid", "tw:grid-cols-[repeat(3,_minmax(0,_1fr))]", "tw:viewport-680:grid-cols-[1fr]",
    "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:[&_article]:grid", "tw:[&_article]:gap-y-[5px]",
    "tw:[&_article]:gap-x-[5px]", "tw:[&_article]:min-h-[88px]", "tw:[&_article]:pt-[17px]", "tw:[&_article]:pr-[17px]",
    "tw:[&_article]:pb-[17px]", "tw:[&_article]:pl-[17px]", "tw:[&_article]:border-t-[length:1px]", "tw:[&_article]:[border-top-style:solid]",
    "tw:[&_article]:border-t-[color:#dce7f2]", "tw:[&_article]:border-r-[length:1px]", "tw:[&_article]:[border-right-style:solid]", "tw:[&_article]:border-r-[color:#dce7f2]",
    "tw:[&_article]:border-b-[length:1px]", "tw:[&_article]:[border-bottom-style:solid]", "tw:[&_article]:border-b-[color:#dce7f2]", "tw:[&_article]:border-l-[length:1px]",
    "tw:[&_article]:[border-left-style:solid]", "tw:[&_article]:border-l-[color:#dce7f2]", "tw:[&_article]:rounded-[13px]", "tw:[&_article]:bg-[color:#fff]",
    "tw:[&_article]:[background-image:none]", "tw:[&_span]:text-[color:#657c9d]", "tw:[&_span]:text-[.78rem]", "tw:[&_strong]:text-[color:#123464]",
    "tw:[&_strong]:text-[1.35rem]",
  ].join(" "),
  "section_card_sponsorship_companies_panel": [
    "section-card", "sponsorship-companies-panel", "tw:pt-[22px]", "tw:pr-[0]",
    "tw:pb-[22px]", "tw:pl-[0]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[0]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:[box-shadow:none]", "tw:[&_>_header]:flex", "tw:[&_>_header]:items-center",
    "tw:[&_>_header]:justify-between", "tw:[&_>_header]:gap-y-[16px]", "tw:[&_>_header]:gap-x-[16px]", "tw:[&_h2]:mt-[0]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_header_p]:mt-[4px]",
    "tw:[&_header_p]:mr-[0]", "tw:[&_header_p]:mb-[0]", "tw:[&_header_p]:ml-[0]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "sponsorship_company_directory": [
    "sponsorship-company-directory", "tw:grid", "tw:gap-y-[9px]", "tw:gap-x-[9px]",
    "tw:[&_>_article]:flex", "tw:[&_>_article]:items-center", "tw:viewport-680:[&_>_article]:items-stretch", "tw:[&_>_article]:justify-between",
    "tw:[&_>_article]:gap-y-[14px]", "tw:[&_>_article]:gap-x-[14px]", "tw:[&_>_article]:pt-[12px]", "tw:[&_>_article]:pr-[14px]",
    "tw:[&_>_article]:pb-[12px]", "tw:[&_>_article]:pl-[14px]", "tw:[&_>_article]:border-t-[length:1px]", "tw:[&_>_article]:[border-top-style:solid]",
    "tw:[&_>_article]:border-t-[color:#dce7f2]", "tw:[&_>_article]:border-r-[length:1px]", "tw:[&_>_article]:[border-right-style:solid]", "tw:[&_>_article]:border-r-[color:#dce7f2]",
    "tw:[&_>_article]:border-b-[length:1px]", "tw:[&_>_article]:[border-bottom-style:solid]", "tw:[&_>_article]:border-b-[color:#dce7f2]", "tw:[&_>_article]:border-l-[length:1px]",
    "tw:[&_>_article]:[border-left-style:solid]", "tw:[&_>_article]:border-l-[color:#dce7f2]", "tw:[&_>_article]:rounded-[11px]", "tw:[&_>_article]:bg-[color:#fbfdff]",
    "tw:[&_>_article]:[background-image:none]", "tw:viewport-680:[&_>_article]:flex-col",
  ].join(" "),
  "sponsor_company_identity": [
    "sponsor-company-identity", "tw:flex", "tw:items-center", "tw:gap-y-[11px]",
    "tw:gap-x-[11px]", "tw:min-w-[0]", "tw:[&_img]:grid", "tw:[&_img]:w-[40px]",
    "tw:[&_img]:h-[40px]", "tw:[&_img]:[flex:0_0_40px]", "tw:[&_img]:place-items-center", "tw:[&_img]:[object-fit:contain]",
    "tw:[&_img]:rounded-[9px]", "tw:[&_img]:bg-[color:#e8f1fd]", "tw:[&_img]:[background-image:none]", "tw:[&_img]:text-[color:#1761b8]",
    "tw:[&_img]:font-[850]", "tw:[&_>_span]:grid", "tw:[&_>_span]:w-[40px]", "tw:[&_>_span]:h-[40px]",
    "tw:[&_>_span]:[flex:0_0_40px]", "tw:[&_>_span]:place-items-center", "tw:[&_>_span]:[object-fit:contain]", "tw:[&_>_span]:rounded-[9px]",
    "tw:[&_>_span]:bg-[color:#e8f1fd]", "tw:[&_>_span]:[background-image:none]", "tw:[&_>_span]:text-[color:#1761b8]", "tw:[&_>_span]:font-[850]",
    "tw:[&_>_div]:grid", "tw:[&_>_div]:gap-y-[3px]", "tw:[&_>_div]:gap-x-[3px]", "tw:[&_strong]:text-[color:#183764]",
    "tw:[&_small]:text-[color:#6b819e]", "tw:[&_small]:text-[.74rem]",
  ].join(" "),
  "sponsorship_company_actions": [
    "sponsorship-company-actions", "tw:flex", "tw:flex-wrap", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:viewport-680:[&_.button]:[flex:1]", "tw:viewport-680:[&_.button]:justify-center",
  ].join(" "),
  "button_button_danger_button_small_sponsor_delete_button": [
    "button", "button-danger", "button-small", "sponsor-delete-button",
    "tw:inline-flex", "tw:items-center", "tw:justify-center", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:min-h-[30px]", "tw:pt-[0]!", "tw:pr-[0]!",
    "tw:pb-[0]!", "tw:pl-[0]!", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#c92921]!", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#c92921]!",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#c92921]!", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#c92921]!", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:#c92921]!",
    "tw:[background-image:url(data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2024%2024%22%20fill%3D%22none%22%20stroke%3D%22white%22%20stroke-width%3D%222%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%3E%3Cpath%20d%3D%22M3%206h18%22%2F%3E%3Cpath%20d%3D%22M8%206V4h8v2%22%2F%3E%3Cpath%20d%3D%22M19%206l-1%2014H6L5%206%22%2F%3E%3Cpath%20d%3D%22M10%2011v5M14%2011v5%22%2F%3E%3C%2Fsvg%3E)]", "tw:text-[color:transparent]!", "tw:text-[0]!", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]",
    "tw:hover:border-t-[color:var(--danger)]", "tw:hover:border-r-[color:var(--danger)]", "tw:hover:border-b-[color:var(--danger)]", "tw:hover:border-l-[color:var(--danger)]",
    "tw:hover:[transform:translateY(-1px)]", "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait",
    "tw:[&:active]:[transform:translateY(0)]", "tw:[&:active]:[box-shadow:none]", "tw:hover:bg-[color:#a91f19]!", "tw:hover:[background-image:none]",
    "tw:hover:text-[color:#992f29]", "tw:w-[32px]", "tw:min-w-[32px]!", "tw:h-[32px]",
    "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:[background-position:center]", "tw:[background-repeat:no-repeat]",
    "tw:[background-size:15px]", "tw:[text-indent:0]",
  ].join(" "),
} as const;
