/** Reusable Tailwind primitives shared by system and Portal components. */
export const sharedUtilities = {
  stackMd: [
    "stack-md", "tw:grid", "tw:gap-y-[18px]", "tw:gap-x-[18px]",
    "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]", "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]",
    "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]",
  ].join(" "),
  pageHeader: [
    "page-header", "tw:flex", "tw:viewport-760:grid", "tw:justify-between",
    "tw:items-start", "tw:gap-y-[18px]", "tw:gap-x-[18px]", "tw:mb-[0]",
    "tw:pt-[4px]", "tw:pr-[0]", "tw:pb-[22px]", "tw:pl-[0]",
    "tw:border-t-[length:0]", "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]",
    "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:2px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:color-mix(in_srgb,_var(--brand)_24%,_var(--line))]", "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]",
    "tw:rounded-[0]", "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:[box-shadow:none]",
    "tw:[animation:hero-rise_620ms_var(--ease-standard)_both]", "tw:mt-[0]", "tw:mr-[0]", "tw:ml-[0]",
    "tw:[&_h1]:mt-[0]", "tw:[&_h1]:mr-[0]", "tw:[&_h1]:mb-[0]", "tw:[&_h1]:ml-[0]",
    "tw:[&_h1]:text-[clamp(1.8rem,_2vw,_2.4rem)]", "tw:[&_h1]:leading-[1.04]", "tw:[&_h1]:tracking-[-0.04em]", "tw:[&_p]:max-w-[760px]",
    "tw:[&::after]:[content:'']", "tw:[&::after]:absolute", "tw:viewport-720:flex-col",
  ].join(" "),
  eyebrow: [
    "eyebrow", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-[color:var(--brand)]", "tw:text-[0.74rem]", "tw:font-[700]",
    "tw:tracking-[0.12em]", "tw:uppercase",
  ].join(" "),
  muted: [
    "muted", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-[color:var(--muted)]",
  ].join(" "),
  ticketStatus: [
    "ticket-status", "tw:inline-flex", "tw:items-center", "tw:min-h-[28px]",
    "tw:pt-[0]", "tw:pr-[10px]", "tw:pb-[0]", "tw:pl-[10px]",
    "tw:rounded-[999px]", "tw:text-[0.74rem]", "tw:font-[800]", "tw:uppercase",
    "tw:tracking-[0.04em]", "tw:[&.ticket-status-open]:bg-[color:rgba(18,_93,_156,_0.1)]", "tw:[&.ticket-status-open]:[background-image:none]", "tw:[&.ticket-status-open]:text-[color:var(--brand)]",
    "tw:[&.ticket-status-in_progress]:bg-[color:rgba(18,_93,_156,_0.1)]", "tw:[&.ticket-status-in_progress]:[background-image:none]", "tw:[&.ticket-status-in_progress]:text-[color:var(--brand)]", "tw:[&.ticket-status-waiting_customer]:bg-[color:rgba(147,_100,_12,_0.12)]",
    "tw:[&.ticket-status-waiting_customer]:[background-image:none]", "tw:[&.ticket-status-waiting_customer]:text-[color:#93640c]", "tw:[&.ticket-status-resolved]:bg-[color:rgba(28,_140,_94,_0.12)]", "tw:[&.ticket-status-resolved]:[background-image:none]",
    "tw:[&.ticket-status-resolved]:text-[color:var(--success)]", "tw:[&.ticket-status-closed]:bg-[color:rgba(28,_140,_94,_0.12)]", "tw:[&.ticket-status-closed]:[background-image:none]", "tw:[&.ticket-status-closed]:text-[color:var(--success)]",
  ].join(" "),
  button: [
    "button", "tw:inline-flex", "tw:items-center", "tw:justify-center",
    "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:min-h-[36px]", "tw:pt-[0]",
    "tw:pr-[12px]", "tw:pb-[0]", "tw:pl-[12px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[var(--radius-control)]",
    "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:text-[color:var(--text)]", "tw:text-[0.86rem]",
    "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--line-strong)]", "tw:hover:border-r-[color:var(--line-strong)]", "tw:hover:border-b-[color:var(--line-strong)]",
    "tw:hover:border-l-[color:var(--line-strong)]", "tw:hover:[transform:translateY(-1px)]", "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]",
    "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]", "tw:[&:active]:[box-shadow:none]",
  ].join(" "),
  buttonButtonPrimary: [
    "button", "button-primary", "tw:inline-flex", "tw:items-center",
    "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:min-h-[36px]",
    "tw:pt-[0]", "tw:pr-[12px]", "tw:pb-[0]", "tw:pl-[12px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--brand)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--brand)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--brand)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--brand)]",
    "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--brand)]", "tw:[background-image:none]", "tw:text-[color:#ffffff]",
    "tw:text-[0.86rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--brand-strong)]", "tw:hover:border-r-[color:var(--brand-strong)]",
    "tw:hover:border-b-[color:var(--brand-strong)]", "tw:hover:border-l-[color:var(--brand-strong)]", "tw:hover:[transform:translateY(-1px)]", "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]",
    "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]", "tw:[&:active]:[box-shadow:none]",
    "tw:hover:bg-[color:var(--brand-strong)]", "tw:hover:[background-image:none]",
  ].join(" "),
  buttonButtonSecondary: [
    "button", "button-secondary", "tw:inline-flex", "tw:items-center",
    "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:min-h-[36px]",
    "tw:pt-[0]", "tw:pr-[12px]", "tw:pb-[0]", "tw:pl-[12px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]",
    "tw:rounded-[var(--radius-control)]", "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:text-[color:var(--text)]",
    "tw:text-[0.86rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--line-strong)]", "tw:hover:border-r-[color:var(--line-strong)]",
    "tw:hover:border-b-[color:var(--line-strong)]", "tw:hover:border-l-[color:var(--line-strong)]", "tw:hover:[transform:translateY(-1px)]", "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]",
    "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]", "tw:[&:active]:[box-shadow:none]",
  ].join(" "),
  dataTable: [
    "data-table", "tw:w-[100%]", "tw:[border-collapse:separate]", "tw:[border-spacing:0]",
    "tw:[&_thead_th]:pt-[0]", "tw:[&_thead_th]:pr-[12px]", "tw:[&_thead_th]:pb-[14px]", "tw:[&_thead_th]:pl-[12px]",
    "tw:[&_thead_th]:text-[0.78rem]", "tw:[&_thead_th]:font-[700]", "tw:[&_thead_th]:tracking-[0.1em]", "tw:[&_thead_th]:uppercase",
    "tw:[&_thead_th]:text-[color:var(--muted)]", "tw:[&_thead_th]:text-left", "tw:[&_tbody_tr]:bg-[color:#ffffff]", "tw:[&_tbody_tr]:[background-image:none]",
    "tw:[&_tbody_tr_+_tr_td]:border-t-[length:1px]", "tw:[&_tbody_tr_+_tr_td]:[border-top-style:solid]", "tw:[&_tbody_tr_+_tr_td]:border-t-[color:#edf2f7]", "tw:[&_tbody_td]:pt-[16px]",
    "tw:[&_tbody_td]:pr-[12px]", "tw:[&_tbody_td]:pb-[16px]", "tw:[&_tbody_td]:pl-[12px]", "tw:[&_tbody_td]:[vertical-align:middle]",
    "tw:[&_tbody_tr_td:first-child]:[border-top-left-radius:var(--radius-md)]", "tw:[&_tbody_tr_td:first-child]:[border-bottom-left-radius:var(--radius-md)]", "tw:[&_tbody_tr_td:last-child]:[border-top-right-radius:var(--radius-md)]", "tw:[&_tbody_tr_td:last-child]:[border-bottom-right-radius:var(--radius-md)]",
    "tw:viewport-760:block", "tw:viewport-760:[overflow-x:auto]",
  ].join(" "),
  tableSubtext: [
    "table-subtext", "tw:block", "tw:mt-[4px]", "tw:text-[color:var(--muted)]",
    "tw:text-[0.88rem]", "tw:font-[500]",
  ].join(" "),
  pill: [
    "pill", "tw:inline-flex", "tw:items-center", "tw:justify-center",
    "tw:min-h-[34px]", "tw:pt-[0]", "tw:pr-[12px]", "tw:pb-[0]",
    "tw:pl-[12px]", "tw:rounded-[999px]", "tw:bg-[color:var(--brand-soft)]", "tw:[background-image:none]",
    "tw:text-[color:var(--brand-strong)]", "tw:text-[0.88rem]", "tw:font-[700]",
  ].join(" "),
  formError: [
    "form-error", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:pt-[12px]", "tw:pr-[14px]", "tw:pb-[12px]",
    "tw:pl-[14px]", "tw:rounded-[0]", "tw:text-[.86rem]", "tw:leading-[1.45]",
    "tw:bg-[color:rgba(191,_63,_56,_0.08)]", "tw:[background-image:none]", "tw:text-[color:#b42318]", "tw:[grid-column:1_/_-1]",
    "tw:viewport-680:[grid-column:auto]", "tw:font-[700]",
  ].join(" "),
  agencyStatsGrid: [
    "agency-stats-grid", "tw:grid", "tw:grid-cols-[repeat(4,_minmax(0,_1fr))]", "tw:viewport-1024:grid-cols-[1fr]",
    "tw:gap-y-[14px]", "tw:gap-x-[14px]",
  ].join(" "),
  statCard: [
    "stat-card", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[10px]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]",
    "tw:[box-shadow:0_5px_16px_rgba(19,_48,_83,_0.05)]", "tw:[animation:rise-in_620ms_var(--ease-standard)_both]", "tw:relative", "tw:pt-[22px]",
    "tw:pr-[22px]", "tw:pb-[22px]", "tw:pl-[22px]", "tw:[overflow-x:hidden]",
    "tw:[overflow-y:hidden]", "tw:[&::before]:[content:'']", "tw:[&::before]:absolute", "tw:[&::before]:top-[0]",
    "tw:[&::before]:right-[auto]", "tw:[&::before]:bottom-[0]", "tw:[&::before]:left-[0]", "tw:[&::before]:w-[4px]",
    "tw:[&::before]:bg-[color:transparent]", "tw:[&::before]:[background-image:linear-gradient(180deg,_var(--brand)_0%,_#7eb0e8_100%)]", "tw:[&::before]:[transform-origin:top]", "tw:[&::before]:[animation:line-grow-vertical_720ms_100ms_var(--ease-standard)_both]",
    "tw:[&_strong]:block", "tw:[&_strong]:mt-[14px]", "tw:[&_strong]:text-[2rem]", "tw:[&_strong]:leading-[1]",
    "tw:[&_strong]:tracking-[-0.05em]", "tw:[&_span]:block", "tw:[&_span]:mt-[10px]", "tw:[&_span]:text-[color:var(--muted)]",
  ].join(" "),
  checkOption: [
    "check-option", "tw:flex", "tw:items-center", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]", "tw:min-h-[44px]", "tw:pt-[10px]", "tw:pr-[12px]",
    "tw:pb-[10px]", "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[var(--radius-md)]", "tw:bg-[color:var(--panel-muted)]",
    "tw:[background-image:none]", "tw:cursor-pointer", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard)]", "tw:hover:[transform:translateY(-1px)]",
    "tw:hover:border-t-[color:var(--line-strong)]", "tw:hover:border-r-[color:var(--line-strong)]", "tw:hover:border-b-[color:var(--line-strong)]", "tw:hover:border-l-[color:var(--line-strong)]",
    "tw:hover:bg-[color:#ffffff]", "tw:hover:[background-image:none]", "tw:[&_input]:w-[18px]", "tw:[&_input]:h-[18px]",
    "tw:[&_input]:mt-[0]", "tw:[&_input]:mr-[0]", "tw:[&_input]:mb-[0]", "tw:[&_input]:ml-[0]",
    "tw:[&_input]:[accent-color:var(--brand)]", "tw:[&_input]:[flex-shrink:0]",
  ].join(" "),
  field: [
    "field", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]", "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[44px]",
    "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]", "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[14px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:var(--line)]",
    "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:var(--text)]",
    "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[44px]", "tw:[&_select]:pt-[0]",
    "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[14px]", "tw:[&_select]:border-t-[length:1px]",
    "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]",
    "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:var(--line)]",
    "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:var(--line)]", "tw:[&_select]:rounded-[var(--radius-md)]",
    "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:var(--text)]", "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]",
    "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_input:focus]:[transform:translateY(-1px)]", "tw:[&_select:focus]:[outline:none]",
    "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]", "tw:[&_input[type=file]]:pt-[10px]", "tw:[&_input[type=file]]:pr-[14px]",
    "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]", "tw:[&_input[type=checkbox]]:w-[auto]", "tw:[&_input[type=checkbox]]:min-h-[auto]",
    "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]", "tw:[&_input[type=checkbox]]:pb-[0]", "tw:[&_input[type=checkbox]]:pl-[0]",
    "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]", "tw:[&_input[type=radio]]:pt-[0]", "tw:[&_input[type=radio]]:pr-[0]",
    "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]",
  ].join(" "),
  buttonButtonPrimaryButtonSmall: [
    "button", "button-primary", "button-small", "tw:inline-flex",
    "tw:items-center", "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:min-h-[30px]", "tw:pt-[5px]", "tw:pr-[8px]", "tw:pb-[5px]",
    "tw:pl-[8px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--brand)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--brand)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--brand)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--brand)]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--brand)]", "tw:[background-image:none]",
    "tw:text-[color:#ffffff]", "tw:text-[.72rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--brand-strong)]",
    "tw:hover:border-r-[color:var(--brand-strong)]", "tw:hover:border-b-[color:var(--brand-strong)]", "tw:hover:border-l-[color:var(--brand-strong)]", "tw:hover:[transform:translateY(-1px)]",
    "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]",
    "tw:[&:active]:[box-shadow:none]", "tw:hover:bg-[color:var(--brand-strong)]", "tw:hover:[background-image:none]",
  ].join(" "),
  buttonButtonSmall: [
    "button", "button-small", "tw:inline-flex", "tw:items-center",
    "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:min-h-[30px]",
    "tw:pt-[5px]", "tw:pr-[8px]", "tw:pb-[5px]", "tw:pl-[8px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]",
    "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--panel)]", "tw:[background-image:none]", "tw:text-[color:var(--text)]",
    "tw:text-[.72rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--line-strong)]", "tw:hover:border-r-[color:var(--line-strong)]",
    "tw:hover:border-b-[color:var(--line-strong)]", "tw:hover:border-l-[color:var(--line-strong)]", "tw:hover:[transform:translateY(-1px)]", "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]",
    "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]", "tw:[&:active]:[box-shadow:none]",
  ].join(" "),
  buttonButtonDangerButtonSmall: [
    "button", "button-danger", "button-small", "tw:inline-flex",
    "tw:items-center", "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:min-h-[30px]", "tw:pt-[5px]", "tw:pr-[8px]", "tw:pb-[5px]",
    "tw:pl-[8px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#b42318]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#b42318]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#b42318]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#b42318]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:#b42318]", "tw:[background-image:none]",
    "tw:text-[color:#fff]", "tw:text-[.72rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--danger)]",
    "tw:hover:border-r-[color:var(--danger)]", "tw:hover:border-b-[color:var(--danger)]", "tw:hover:border-l-[color:var(--danger)]", "tw:hover:[transform:translateY(-1px)]",
    "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]",
    "tw:[&:active]:[box-shadow:none]", "tw:hover:bg-[color:rgba(191,_63,_56,_0.14)]", "tw:hover:[background-image:none]", "tw:hover:text-[color:#992f29]",
  ].join(" "),
  buttonButtonDanger: [
    "button", "button-danger", "tw:inline-flex", "tw:items-center",
    "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]", "tw:min-h-[36px]",
    "tw:pt-[0]", "tw:pr-[12px]", "tw:pb-[0]", "tw:pl-[12px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#b42318]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#b42318]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#b42318]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#b42318]",
    "tw:rounded-[var(--radius-control)]", "tw:bg-[color:#b42318]", "tw:[background-image:none]", "tw:text-[color:#fff]",
    "tw:text-[0.86rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--danger)]", "tw:hover:border-r-[color:var(--danger)]",
    "tw:hover:border-b-[color:var(--danger)]", "tw:hover:border-l-[color:var(--danger)]", "tw:hover:[transform:translateY(-1px)]", "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]",
    "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]", "tw:[&:active]:[box-shadow:none]",
    "tw:hover:bg-[color:rgba(191,_63,_56,_0.14)]", "tw:hover:[background-image:none]", "tw:hover:text-[color:#992f29]",
  ].join(" "),
  twoColumnGrid: [
    "two-column-grid", "tw:grid", "tw:gap-y-[18px]", "tw:gap-x-[18px]",
    "tw:grid-cols-[minmax(0,_1.35fr)_minmax(320px,_0.95fr)]", "tw:viewport-1120:grid-cols-[1fr]",
  ].join(" "),
  pageBreadcrumb: [
    "page-breadcrumb", "tw:flex", "tw:items-center", "tw:gap-y-[10px]",
    "tw:gap-x-[10px]", "tw:text-[color:#1763c5]", "tw:text-[.88rem]", "tw:[&_i]:text-[color:#9dafc6]",
    "tw:[&_i]:text-[1.2rem]", "tw:[&_i]:not-italic", "tw:[&_strong]:text-[color:#0f58b7]",
  ].join(" "),
  gridForm: [
    "grid-form", "tw:min-w-0", "tw:[&>*]:min-w-0", "tw:[&_input]:min-w-0", "tw:[&_select]:min-w-0", "tw:grid", "tw:gap-y-[14px]", "tw:gap-x-[14px]",
    "tw:grid-cols-[repeat(3,_minmax(0,_1fr))]", "tw:viewport-1120:grid-cols-[1fr]", "tw:[&_textarea]:w-[100%]", "tw:[&_textarea]:pt-[12px]",
    "tw:[&_textarea]:pr-[14px]", "tw:[&_textarea]:pb-[12px]", "tw:[&_textarea]:pl-[14px]", "tw:[&_textarea]:border-t-[length:1px]",
    "tw:[&_textarea]:[border-top-style:solid]", "tw:[&_textarea]:border-t-[color:var(--line)]", "tw:[&_textarea]:border-r-[length:1px]", "tw:[&_textarea]:[border-right-style:solid]",
    "tw:[&_textarea]:border-r-[color:var(--line)]", "tw:[&_textarea]:border-b-[length:1px]", "tw:[&_textarea]:[border-bottom-style:solid]", "tw:[&_textarea]:border-b-[color:var(--line)]",
    "tw:[&_textarea]:border-l-[length:1px]", "tw:[&_textarea]:[border-left-style:solid]", "tw:[&_textarea]:border-l-[color:var(--line)]", "tw:[&_textarea]:rounded-[var(--radius-md)]",
    "tw:[&_textarea]:bg-[color:var(--panel)]", "tw:[&_textarea]:[background-image:none]", "tw:[&_textarea]:text-[color:var(--text)]",
  ].join(" "),
  fieldFormFull: [
    "field", "form-full", "tw:grid", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]", "tw:[&_input]:w-[100%]",
    "tw:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[14px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:text-[color:var(--text)]", "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[44px]",
    "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[14px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:var(--line)]",
    "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:var(--text)]",
    "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_input:focus]:[transform:translateY(-1px)]",
    "tw:[&_select:focus]:[outline:none]", "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]", "tw:[&_input[type=file]]:pt-[10px]",
    "tw:[&_input[type=file]]:pr-[14px]", "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]", "tw:[&_input[type=checkbox]]:w-[auto]",
    "tw:[&_input[type=checkbox]]:min-h-[auto]", "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]", "tw:[&_input[type=checkbox]]:pb-[0]",
    "tw:[&_input[type=checkbox]]:pl-[0]", "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]", "tw:[&_input[type=radio]]:pt-[0]",
    "tw:[&_input[type=radio]]:pr-[0]", "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  fieldFieldSubmit: [
    "field", "field-submit", "tw:grid", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]", "tw:[&_input]:w-[100%]",
    "tw:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[14px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:text-[color:var(--text)]", "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[44px]",
    "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[14px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:var(--line)]",
    "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:var(--text)]",
    "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_input:focus]:[transform:translateY(-1px)]",
    "tw:[&_select:focus]:[outline:none]", "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]", "tw:[&_input[type=file]]:pt-[10px]",
    "tw:[&_input[type=file]]:pr-[14px]", "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]", "tw:[&_input[type=checkbox]]:w-[auto]",
    "tw:[&_input[type=checkbox]]:min-h-[auto]", "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]", "tw:[&_input[type=checkbox]]:pb-[0]",
    "tw:[&_input[type=checkbox]]:pl-[0]", "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]", "tw:[&_input[type=radio]]:pt-[0]",
    "tw:[&_input[type=radio]]:pr-[0]", "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]", "tw:[align-self:end]",
  ].join(" "),
  inlineForm: [
    "inline-form", "tw:[&_select]:min-h-[42px]", "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]",
    "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[14px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]",
    "tw:[&_select]:border-t-[color:var(--line)]", "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]",
    "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]",
    "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:var(--line)]", "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]",
    "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:var(--text)]", "tw:[&_input]:w-[96px]", "tw:[&_input]:min-h-[44px]",
    "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]", "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[14px]",
    "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]", "tw:[&_input]:border-r-[length:1px]",
    "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]",
    "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:var(--line)]",
    "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:var(--text)]",
    "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_input:focus]:[transform:translateY(-1px)]",
    "tw:flex", "tw:items-center", "tw:gap-y-[10px]", "tw:gap-x-[10px]",
    "tw:flex-wrap",
  ].join(" "),
  statsGrid: [
    "stats-grid", "tw:grid", "tw:gap-y-[18px]", "tw:gap-x-[18px]",
    "tw:grid-cols-[repeat(4,_minmax(0,_1fr))]", "tw:viewport-1120:grid-cols-[1fr]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]",
    "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]", "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]",
  ].join(" "),
  buttonButtonPrimaryButtonBlock: [
    "button", "button-primary", "button-block", "tw:inline-flex",
    "tw:items-center", "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:min-h-[36px]", "tw:pt-[0]", "tw:pr-[12px]", "tw:pb-[0]",
    "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--brand)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--brand)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--brand)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--brand)]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--brand)]", "tw:[background-image:none]",
    "tw:text-[color:#ffffff]", "tw:text-[0.86rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--brand-strong)]",
    "tw:hover:border-r-[color:var(--brand-strong)]", "tw:hover:border-b-[color:var(--brand-strong)]", "tw:hover:border-l-[color:var(--brand-strong)]", "tw:hover:[transform:translateY(-1px)]",
    "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]",
    "tw:[&:active]:[box-shadow:none]", "tw:hover:bg-[color:var(--brand-strong)]", "tw:hover:[background-image:none]", "tw:w-[100%]",
  ].join(" "),
  sectionActions: [
    "section-actions", "tw:flex", "tw:flex-wrap", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]",
  ].join(" "),
  srOnly: [
    "sr-only", "tw:absolute", "tw:w-[1px]", "tw:h-[1px]",
    "tw:pt-[0]", "tw:pr-[0]", "tw:pb-[0]", "tw:pl-[0]",
    "tw:mt-[-1px]", "tw:mr-[-1px]", "tw:mb-[-1px]", "tw:ml-[-1px]",
    "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:[clip:rect(0,_0,_0,_0)]", "tw:border-t-[length:0]",
    "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:0]", "tw:[border-right-style:none]",
    "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]",
  ].join(" "),
  clientEmpty: [
    "client-empty", "tw:pt-[26px]", "tw:pr-[26px]", "tw:pb-[26px]",
    "tw:pl-[26px]", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-[color:#75849a]", "tw:text-center", "tw:text-[.8rem]",
  ].join(" "),
  controlToggle: [
    "control-toggle", "tw:inline-flex!", "tw:items-center", "tw:gap-y-[7px]",
    "tw:gap-x-[7px]", "tw:min-h-[var(--control-height)]", "tw:cursor-pointer", "tw:select-none",
    "tw:[&_input]:absolute", "tw:[&_input]:[inline-size:1px]!", "tw:[&_input]:[block-size:1px]", "tw:[&_input]:[overflow-x:hidden]",
    "tw:[&_input]:[overflow-y:hidden]", "tw:[&_input]:[clip:rect(0_0_0_0)]", "tw:[&_input]:[clip-path:inset(50%)]", "tw:[&_input]:whitespace-nowrap",
    "tw:[&_span]:relative", "tw:[&_span]:[inline-size:30px]", "tw:[&_span]:[block-size:17px]", "tw:[&_span]:[flex:0_0_auto]",
    "tw:[&_span]:border-t-[length:1px]", "tw:[&_span]:[border-top-style:solid]", "tw:[&_span]:border-t-[color:#b8423a]", "tw:[&_span]:border-r-[length:1px]",
    "tw:[&_span]:[border-right-style:solid]", "tw:[&_span]:border-r-[color:#b8423a]", "tw:[&_span]:border-b-[length:1px]", "tw:[&_span]:[border-bottom-style:solid]",
    "tw:[&_span]:border-b-[color:#b8423a]", "tw:[&_span]:border-l-[length:1px]", "tw:[&_span]:[border-left-style:solid]", "tw:[&_span]:border-l-[color:#b8423a]",
    "tw:[&_span]:rounded-[999px]", "tw:[&_span]:bg-[color:#c94c43]", "tw:[&_span]:[background-image:none]", "tw:[&_span]:[box-shadow:inset_0_1px_2px_rgb(66_14_10_/_.22)]",
    "tw:[&_span]:[transition:background_160ms_var(--ease-standard),_border-color_160ms_var(--ease-standard)]", "tw:[&_span::after]:[content:'']", "tw:[&_span::after]:absolute", "tw:[&_span::after]:top-[2px]",
    "tw:[&_span::after]:left-[2px]", "tw:[&_span::after]:[inline-size:11px]", "tw:[&_span::after]:[block-size:11px]", "tw:[&_span::after]:rounded-[50%]",
    "tw:[&_span::after]:bg-[color:#fff]", "tw:[&_span::after]:[background-image:none]", "tw:[&_span::after]:[box-shadow:0_1px_2px_rgb(15_23_42_/_.24)]", "tw:[&_span::after]:[transition:transform_160ms_var(--ease-standard)]",
    "tw:[&_input:checked_+_span]:border-t-[color:#238448]", "tw:[&_input:checked_+_span]:border-r-[color:#238448]", "tw:[&_input:checked_+_span]:border-b-[color:#238448]", "tw:[&_input:checked_+_span]:border-l-[color:#238448]",
    "tw:[&_input:checked_+_span]:bg-[color:#2fa457]", "tw:[&_input:checked_+_span]:[background-image:none]", "tw:[&_input:checked_+_span::after]:[transform:translateX(13px)]", "tw:[&_input:focus-visible_+_span]:[outline:2px_solid_var(--brand)]",
    "tw:[&_input:focus-visible_+_span]:[outline-offset:2px]", "tw:[&_em]:text-[color:var(--muted)]", "tw:[&_em]:text-[.75rem]", "tw:[&_em]:not-italic",
    "tw:[&_em]:font-[650]",
  ].join(" "),
  simpleItem: [
    "simple-item", "tw:flex", "tw:viewport-760:grid", "tw:items-center",
    "tw:justify-between", "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:pt-[16px]",
    "tw:pr-[16px]", "tw:pb-[16px]", "tw:pl-[16px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[var(--radius-md)]",
    "tw:bg-[color:#ffffff]", "tw:[background-image:none]", "tw:[transition:transform_200ms_var(--ease-standard),_border-color_200ms_var(--ease-standard),_box-shadow_200ms_var(--ease-standard),_background_200ms_var(--ease-standard)]", "tw:hover:[transform:translateY(-2px)]",
    "tw:hover:border-t-[color:var(--line-strong)]", "tw:hover:border-r-[color:var(--line-strong)]", "tw:hover:border-b-[color:var(--line-strong)]", "tw:hover:border-l-[color:var(--line-strong)]",
    "tw:hover:[box-shadow:0_12px_22px_rgba(31,_61,_95,_0.06)]", "tw:hover:bg-[color:#ffffff]", "tw:hover:[background-image:none]",
  ].join(" "),
  simpleList: [
    "simple-list", "tw:grid", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]", "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]",
  ].join(" "),
  productManagementStackMd: [
    "product-management", "stack-md", "tw:gap-y-[18px]", "tw:gap-x-[18px]",
    "tw:grid", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]",
    "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]",
  ].join(" "),
  productManagementHeader: [
    "product-management-header", "tw:flex", "tw:items-center", "tw:viewport-620:items-start",
    "tw:justify-between", "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:[&_h1]:mt-[0]",
    "tw:[&_h1]:mr-[0]", "tw:[&_h1]:mb-[0]", "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[1.7rem]",
    "tw:[&_h1]:tracking-[-.035em]", "tw:viewport-620:flex-col",
  ].join(" "),
  buttonButtonSmallButtonPrimary: [
    "button", "button-small", "button-primary", "tw:inline-flex",
    "tw:items-center", "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:min-h-[30px]", "tw:pt-[5px]", "tw:pr-[8px]", "tw:pb-[5px]",
    "tw:pl-[8px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--brand)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--brand)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--brand)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--brand)]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:var(--brand)]", "tw:[background-image:none]",
    "tw:text-[color:#ffffff]", "tw:text-[.72rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--brand-strong)]",
    "tw:hover:border-r-[color:var(--brand-strong)]", "tw:hover:border-b-[color:var(--brand-strong)]", "tw:hover:border-l-[color:var(--brand-strong)]", "tw:hover:[transform:translateY(-1px)]",
    "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]",
    "tw:[&:active]:[box-shadow:none]", "tw:hover:bg-[color:var(--brand-strong)]", "tw:hover:[background-image:none]",
  ].join(" "),
  buttonButtonSecondaryButtonSmall: [
    "button", "button-secondary", "button-small", "tw:inline-flex",
    "tw:items-center", "tw:justify-center", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:min-h-[30px]", "tw:pt-[5px]", "tw:pr-[8px]", "tw:pb-[5px]",
    "tw:pl-[8px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:transparent]", "tw:[background-image:none]",
    "tw:text-[color:var(--text)]", "tw:text-[.72rem]", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]", "tw:hover:border-t-[color:var(--line-strong)]",
    "tw:hover:border-r-[color:var(--line-strong)]", "tw:hover:border-b-[color:var(--line-strong)]", "tw:hover:border-l-[color:var(--line-strong)]", "tw:hover:[transform:translateY(-1px)]",
    "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait", "tw:[&:active]:[transform:translateY(0)]",
    "tw:[&:active]:[box-shadow:none]",
  ].join(" "),
  sectionActionsFormFull: [
    "section-actions", "form-full", "tw:flex", "tw:flex-wrap",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  sectionCard: [
    "section-card", "stack-sm", "tw:pt-[22px]", "tw:pr-[0]",
    "tw:pb-[22px]", "tw:pl-[0]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[0]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:[box-shadow:none]",
  ].join(" "),
  tournamentManagementPageStackMd: [
    "tournament-management-page", "stack-md", "tw:max-w-[1240px]", "tw:mt-[0]",
    "tw:mr-[auto]", "tw:mb-[0]", "tw:ml-[auto]", "tw:pt-[24px]",
    "tw:viewport-760:pt-[16px]", "tw:pr-[24px]", "tw:viewport-760:pr-[16px]", "tw:pb-[24px]",
    "tw:viewport-760:pb-[16px]", "tw:pl-[24px]", "tw:viewport-760:pl-[16px]", "tw:grid",
    "tw:gap-y-[18px]", "tw:gap-x-[18px]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]",
    "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]", "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]",
    "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]",
  ].join(" "),
  pageHeaderTournamentManagementHeader: [
    "page-header", "tournament-management-header", "tw:flex", "tw:viewport-760:grid",
    "tw:justify-between", "tw:items-start", "tw:gap-y-[20px]", "tw:gap-x-[20px]",
    "tw:mb-[0]", "tw:pt-[4px]", "tw:pr-[0]", "tw:pb-[22px]",
    "tw:pl-[0]", "tw:border-t-[length:0]", "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]",
    "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:2px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:color-mix(in_srgb,_var(--brand)_24%,_var(--line))]", "tw:border-l-[length:0]", "tw:[border-left-style:none]",
    "tw:border-l-[color:currentColor]", "tw:rounded-[0]", "tw:bg-[color:transparent]", "tw:[background-image:none]",
    "tw:[box-shadow:none]", "tw:[animation:hero-rise_620ms_var(--ease-standard)_both]", "tw:mt-[0]", "tw:mr-[0]",
    "tw:ml-[0]", "tw:[&_h1]:mt-[0]", "tw:[&_h1]:mr-[0]", "tw:[&_h1]:mb-[0]",
    "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[clamp(1.8rem,_2vw,_2.4rem)]", "tw:[&_h1]:leading-[1.04]", "tw:[&_h1]:tracking-[-0.04em]",
    "tw:[&_p]:max-w-[760px]", "tw:[&::after]:[content:'']", "tw:[&::after]:absolute", "tw:viewport-720:flex-col",
  ].join(" "),
  sectionCard2: [
    "section-card", "tw:pt-[22px]", "tw:pr-[0]", "tw:pb-[22px]",
    "tw:pl-[0]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:0]",
    "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]", "tw:[border-left-style:none]",
    "tw:border-l-[color:currentColor]", "tw:rounded-[0]", "tw:bg-[color:transparent]", "tw:[background-image:none]",
    "tw:[box-shadow:none]",
  ].join(" "),
  authSwitch: [
    "auth-switch", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:text-center", "tw:text-[color:var(--muted)]", "tw:text-[0.92rem]",
    "tw:[&_a]:text-[color:var(--brand)]", "tw:[&_a]:font-[700]", "tw:[&_a]:[text-decoration:none]", "tw:[&_a:hover]:text-[color:var(--brand-strong)]",
  ].join(" "),
  authPageLoginPage: [
    "auth-page", "login-page", "tw:min-h-[100dvh]", "tw:grid",
    "tw:place-items-center", "tw:pt-[0]", "tw:viewport-760:pt-[14px]", "tw:pr-[0]",
    "tw:viewport-760:pr-[14px]", "tw:pb-[0]", "tw:viewport-760:pb-[14px]", "tw:pl-[0]",
    "tw:viewport-760:pl-[14px]", "tw:bg-[color:#f1f5fa]", "tw:[background-image:none]", "tw:viewport-760:[align-items:start]",
  ].join(" "),
  loginShell: [
    "login-shell", "tw:grid", "tw:grid-cols-[minmax(340px,_.9fr)_minmax(420px,_1.1fr)]", "tw:viewport-760:grid-cols-[minmax(0,_1fr)]",
    "tw:w-[min(1080px,_calc(100%_-_48px))]", "tw:viewport-760:w-[100%]", "tw:min-h-[min(660px,_calc(100dvh_-_72px))]", "tw:viewport-760:min-h-[calc(100dvh_-_28px)]",
    "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#d9e3ee]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d9e3ee]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d9e3ee]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#d9e3ee]", "tw:rounded-[18px]", "tw:viewport-760:rounded-[13px]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[box-shadow:0_24px_70px_rgb(18_51_86_/_.12)]",
  ].join(" "),
  loginFormPanel: [
    "login-form-panel", "tw:grid", "tw:min-w-[0]", "tw:place-items-center",
    "tw:pt-[clamp(28px,_5vw,_70px)]", "tw:viewport-760:pt-[40px]", "tw:pr-[clamp(28px,_5vw,_70px)]", "tw:viewport-760:pr-[24px]",
    "tw:pb-[clamp(28px,_5vw,_70px)]", "tw:viewport-760:pb-[40px]", "tw:pl-[clamp(28px,_5vw,_70px)]", "tw:viewport-760:pl-[24px]",
    "tw:viewport-760:[align-items:start]",
  ].join(" "),
  loginFormContent: [
    "login-form-content", "tw:w-[min(100%,_390px)]", "tw:[&_h1]:mt-[12px]", "tw:[&_h1]:mr-[0]",
    "tw:[&_h1]:mb-[8px]", "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[color:#12345d]", "tw:[&_h1]:text-[clamp(1.8rem,_2.7vw,_2.4rem)]",
    "tw:[&_h1]:tracking-[-.04em]", "tw:[&_.auth-switch]:mt-[28px]", "tw:[&_.auth-switch]:pt-[22px]", "tw:[&_.auth-switch]:border-t-[length:1px]",
    "tw:[&_.auth-switch]:[border-top-style:solid]", "tw:[&_.auth-switch]:border-t-[color:#e4ebf2]", "tw:[&_.auth-switch]:text-[.8rem]", "tw:viewport-760:mt-[0]",
    "tw:viewport-760:mr-[auto]", "tw:viewport-760:mb-[0]", "tw:viewport-760:ml-[auto]",
  ].join(" "),
  loginFormEyebrow: [
    "login-form-eyebrow", "tw:text-[color:#197258]", "tw:text-[.69rem]", "tw:font-[800]",
    "tw:tracking-[.14em]",
  ].join(" "),
  loginFormIntro: [
    "login-form-intro", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[30px]",
    "tw:ml-[0]", "tw:text-[color:#667b91]", "tw:text-[.91rem]", "tw:leading-[1.5]",
  ].join(" "),
  athletePortalPage: [
    "athlete-portal-page", "tw:min-h-[100vh]", "tw:pt-[0]", "tw:pr-[0]",
    "tw:pb-[84px]", "tw:viewport-700:pb-[86px]", "tw:pl-[0]", "tw:bg-[color:#06111c]",
    "tw:[background-image:none]", "tw:text-[color:#eef7fb]", "tw:[&_>_.athlete-portal-league-nav]:sticky", "tw:[&_>_.athlete-portal-league-nav]:z-[21]",
    "tw:[&_>_.athlete-portal-league-nav]:top-[0]", "tw:[&_>_.athlete-portal-league-nav]:w-[min(calc(100%_-_32px),_1060px)]", "tw:viewport-700:[&_>_.athlete-portal-league-nav]:w-[calc(100%_-_28px)]", "tw:[&_>_.athlete-portal-league-nav]:pt-[8px]",
    "tw:viewport-700:[&_>_.athlete-portal-league-nav]:pt-[7px]", "tw:[&_>_.athlete-portal-league-nav]:bg-[color:rgb(6_17_29_/_.94)]", "tw:[&_>_.athlete-portal-league-nav]:[background-image:none]", "tw:[&_>_.athlete-portal-league-nav]:[backdrop-filter:blur(12px)]",
    "tw:viewport-700:[&_>_.athlete-portal-league-nav_a]:text-[.72rem]", "tw:[&_.portal-ranking-table]:border-t-[color:rgb(122_165_188_/_.28)]", "tw:[&_.portal-ranking-table]:border-r-[color:rgb(122_165_188_/_.28)]", "tw:[&_.portal-ranking-table]:border-b-[color:rgb(122_165_188_/_.28)]",
    "tw:[&_.portal-ranking-table]:border-l-[color:rgb(122_165_188_/_.28)]", "tw:[&_.portal-ranking-table]:bg-[color:#102333]", "tw:[&_.portal-ranking-table]:[background-image:none]", "tw:[&_.portal-ranking-table_th]:border-t-[color:rgb(122_165_188_/_.18)]",
    "tw:[&_.portal-ranking-table_th]:border-r-[color:rgb(122_165_188_/_.18)]", "tw:[&_.portal-ranking-table_th]:border-b-[color:rgb(122_165_188_/_.18)]", "tw:[&_.portal-ranking-table_th]:border-l-[color:rgb(122_165_188_/_.18)]", "tw:[&_.portal-ranking-table_th]:text-[color:#a8c8da]",
    "tw:[&_.portal-ranking-table_th]:bg-[color:#142c3e]", "tw:[&_.portal-ranking-table_th]:[background-image:none]", "tw:[&_.portal-ranking-table_td]:border-t-[color:rgb(122_165_188_/_.18)]", "tw:[&_.portal-ranking-table_td]:border-r-[color:rgb(122_165_188_/_.18)]",
    "tw:[&_.portal-ranking-table_td]:border-b-[color:rgb(122_165_188_/_.18)]", "tw:[&_.portal-ranking-table_td]:border-l-[color:rgb(122_165_188_/_.18)]", "tw:[&_.portal-ranking-table_td]:text-[color:#dbeaf2]", "tw:[&_.portal-ranking-table_td]:bg-[color:#102333]",
    "tw:[&_.portal-ranking-table_td]:[background-image:none]", "tw:[&_.portal-rule]:border-t-[color:#48d6ae]", "tw:[&_.portal-rule]:border-r-[color:#48d6ae]", "tw:[&_.portal-rule]:border-b-[color:#48d6ae]",
    "tw:[&_.portal-rule]:border-l-[color:#48d6ae]", "tw:[&_.portal-rule]:text-[color:#dcecf4]", "tw:[&_.portal-rule]:bg-[color:#102b35]", "tw:[&_.portal-rule]:[background-image:none]",
    "tw:[&_.public-league-rules_>_article]:border-t-[color:#48d6ae]", "tw:[&_.public-league-rules_>_article]:border-r-[color:#48d6ae]", "tw:[&_.public-league-rules_>_article]:border-b-[color:#48d6ae]", "tw:[&_.public-league-rules_>_article]:border-l-[color:#48d6ae]",
    "tw:[&_.public-league-rules_>_article]:text-[color:#dcecf4]", "tw:[&_.public-league-rules_>_article]:bg-[color:#102b35]", "tw:[&_.public-league-rules_>_article]:[background-image:none]", "tw:[&_.portal-rule_p]:text-[color:#dcecf4]",
    "tw:[&_.public-league-rules_article_p]:text-[color:#dcecf4]", "tw:[&_.public-league-rules_article_header_strong]:text-[color:#dcecf4]",
  ].join(" "),
  athletePortalHero: [
    "athlete-portal-hero", "tw:pt-[34px]", "tw:viewport-700:pt-[16px]", "tw:pr-[max(20px,_calc((100vw_-_1060px)_/_2))]",
    "tw:viewport-700:pr-[24px]", "tw:pb-[30px]", "tw:viewport-700:pb-[17px]", "tw:pl-[max(20px,_calc((100vw_-_1060px)_/_2))]",
    "tw:viewport-700:pl-[24px]", "tw:text-[color:#fff]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(90deg,_rgb(3_17_31_/_.97)_0%,_rgb(4_20_35_/_.88)_50%,_rgb(2_25_33_/_.35)_100%),_url('/portal-padel-hero.png')]",
    "tw:viewport-700:[background-image:linear-gradient(90deg,_rgb(2_14_30_/_.88)_0%,_rgb(2_18_34_/_.72)_48%,_rgb(1_27_34_/_.32)_100%),_url('/portal-padel-hero.png')]", "tw:[box-shadow:inset_0_-1px_rgb(114_240_197_/_.18),_0_18px_48px_rgb(0_0_0_/_.28)]", "tw:[padding-block:22px]", "tw:relative",
    "tw:[overflow-x:visible]", "tw:[overflow-y:visible]", "tw:min-h-[286px]", "tw:viewport-700:min-h-[0]",
    "tw:[background-position:center]", "tw:viewport-700:[background-position:64%_center]", "tw:[background-size:cover]", "tw:z-[1000]",
    "tw:[&::after]:absolute", "tw:[&::after]:top-[auto]", "tw:[&::after]:right-[-120px]", "tw:[&::after]:bottom-[-210px]",
    "tw:[&::after]:left-[auto]", "tw:[&::after]:w-[460px]", "tw:[&::after]:h-[460px]", "tw:[&::after]:rounded-[50%]",
    "tw:[&::after]:bg-[color:transparent]", "tw:[&::after]:[background-image:radial-gradient(circle,_rgb(8_226_161_/_.18),_transparent_68%)]", "tw:[&::after]:[content:'']", "tw:[&::after]:[pointer-events:none]",
  ].join(" "),
  athletePortalHeroInner: [
    "athlete-portal-hero-inner", "tw:grid", "tw:w-[min(100%,_1060px)]", "tw:mt-[0]",
    "tw:mr-[auto]", "tw:mb-[0]", "tw:ml-[auto]", "tw:[align-items:start]",
    "tw:justify-between", "tw:gap-y-[26px]", "tw:viewport-700:gap-y-[12px]", "tw:gap-x-[26px]",
    "tw:viewport-700:gap-x-[12px]", "tw:relative", "tw:z-[1]", "tw:grid-cols-[1fr]",
    "tw:viewport-700:flex-col",
  ].join(" "),
  athletePortalBrand: [
    "athlete-portal-brand", "tw:flex", "tw:items-center", "tw:viewport-700:items-start",
    "tw:gap-y-[12px]", "tw:viewport-700:gap-y-[7px]", "tw:gap-x-[12px]", "tw:viewport-700:gap-x-[7px]",
    "tw:min-w-[0]", "tw:min-h-[82px]", "tw:viewport-700:min-h-[0]", "tw:flex-wrap",
    "tw:[&_img]:w-[66px]", "tw:viewport-700:[&_img]:w-[58px]", "tw:[&_img]:h-[66px]", "tw:viewport-700:[&_img]:h-[58px]",
    "tw:[&_img]:border-t-[length:1px]", "tw:[&_img]:[border-top-style:solid]", "tw:[&_img]:border-t-[color:rgb(255_255_255_/_.2)]", "tw:[&_img]:border-r-[length:1px]",
    "tw:[&_img]:[border-right-style:solid]", "tw:[&_img]:border-r-[color:rgb(255_255_255_/_.2)]", "tw:[&_img]:border-b-[length:1px]", "tw:[&_img]:[border-bottom-style:solid]",
    "tw:[&_img]:border-b-[color:rgb(255_255_255_/_.2)]", "tw:[&_img]:border-l-[length:1px]", "tw:[&_img]:[border-left-style:solid]", "tw:[&_img]:border-l-[color:rgb(255_255_255_/_.2)]",
    "tw:[&_img]:rounded-[18px]", "tw:[&_img]:[object-fit:cover]", "tw:[&_img]:bg-[color:rgb(255_255_255_/_.94)]", "tw:[&_img]:[background-image:none]",
    "tw:[&_img]:[box-shadow:0_10px_24px_rgb(0_0_0_/_.24)]", "tw:[&_span]:text-[color:#7be4c5]", "tw:[&_span]:text-[.65rem]", "tw:[&_span]:font-[900]",
    "tw:[&_span]:tracking-[.12em]", "tw:[&_h1]:mt-[2px]", "tw:[&_h1]:mr-[0]", "tw:[&_h1]:mb-[2px]",
    "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[color:#fff]", "tw:[&_h1]:text-[clamp(2rem,_3.4vw,_2.65rem)]", "tw:viewport-700:[&_h1]:text-[1.55rem]",
    "tw:[&_h1]:tracking-[-.04em]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:rgb(255_255_255_/_.82)]", "tw:[&_p]:text-[.86rem]", "tw:viewport-700:[&_p]:text-[.78rem]",
    "tw:[&_>_div]:grid", "tw:[&_>_div]:[justify-items:start]", "tw:[&_>_div]:gap-y-[2px]", "tw:[&_>_div]:gap-x-[2px]",
    "tw:[&_.athlete-portal-arena-logo]:block", "tw:[&_.athlete-portal-arena-logo]:w-[min(176px,_42vw)]", "tw:[&_.athlete-portal-arena-logo]:h-[28px]", "tw:[&_.athlete-portal-arena-logo]:border-t-[length:0]",
    "tw:[&_.athlete-portal-arena-logo]:[border-top-style:none]", "tw:[&_.athlete-portal-arena-logo]:border-t-[color:currentColor]", "tw:[&_.athlete-portal-arena-logo]:border-r-[length:0]", "tw:[&_.athlete-portal-arena-logo]:[border-right-style:none]",
    "tw:[&_.athlete-portal-arena-logo]:border-r-[color:currentColor]", "tw:[&_.athlete-portal-arena-logo]:border-b-[length:0]", "tw:[&_.athlete-portal-arena-logo]:[border-bottom-style:none]", "tw:[&_.athlete-portal-arena-logo]:border-b-[color:currentColor]",
    "tw:[&_.athlete-portal-arena-logo]:border-l-[length:0]", "tw:[&_.athlete-portal-arena-logo]:[border-left-style:none]", "tw:[&_.athlete-portal-arena-logo]:border-l-[color:currentColor]", "tw:[&_.athlete-portal-arena-logo]:rounded-[0]",
    "tw:[&_.athlete-portal-arena-logo]:bg-[color:transparent]", "tw:[&_.athlete-portal-arena-logo]:[background-image:none]", "tw:[&_.athlete-portal-arena-logo]:[box-shadow:none]", "tw:[&_.athlete-portal-arena-logo]:[object-fit:contain]",
    "tw:[&_.athlete-portal-arena-logo]:[object-position:left_center]", "tw:[&_>_.athlete-portal-arena-logo]:block", "tw:[&_>_.athlete-portal-arena-logo]:w-[min(176px,_42vw)]", "tw:viewport-700:[&_>_.athlete-portal-arena-logo]:w-[min(168px,_52vw)]",
    "tw:[&_>_.athlete-portal-arena-logo]:h-[32px]", "tw:viewport-700:[&_>_.athlete-portal-arena-logo]:h-[28px]", "tw:[&_>_.athlete-portal-arena-logo]:[flex:0_0_52px]", "tw:[&_>_.athlete-portal-arena-logo]:place-items-center",
    "tw:[&_>_.athlete-portal-arena-logo]:border-t-[length:0]", "tw:[&_>_.athlete-portal-arena-logo]:[border-top-style:none]", "tw:[&_>_.athlete-portal-arena-logo]:border-t-[color:currentColor]", "tw:[&_>_.athlete-portal-arena-logo]:border-r-[length:0]",
    "tw:[&_>_.athlete-portal-arena-logo]:[border-right-style:none]", "tw:[&_>_.athlete-portal-arena-logo]:border-r-[color:currentColor]", "tw:[&_>_.athlete-portal-arena-logo]:border-b-[length:0]", "tw:[&_>_.athlete-portal-arena-logo]:[border-bottom-style:none]",
    "tw:[&_>_.athlete-portal-arena-logo]:border-b-[color:currentColor]", "tw:[&_>_.athlete-portal-arena-logo]:border-l-[length:0]", "tw:[&_>_.athlete-portal-arena-logo]:[border-left-style:none]", "tw:[&_>_.athlete-portal-arena-logo]:border-l-[color:currentColor]",
    "tw:[&_>_.athlete-portal-arena-logo]:rounded-[0]", "tw:[&_>_.athlete-portal-arena-logo]:text-[color:#d9fff0]", "tw:[&_>_.athlete-portal-arena-logo]:bg-[color:transparent]", "tw:[&_>_.athlete-portal-arena-logo]:[background-image:none]",
    "tw:[&_>_.athlete-portal-arena-logo]:[box-shadow:none]", "tw:[&_>_.athlete-portal-arena-logo]:[object-fit:contain]", "tw:[&_>_.athlete-portal-arena-logo]:pt-[0]", "tw:[&_>_.athlete-portal-arena-logo]:pr-[0]",
    "tw:[&_>_.athlete-portal-arena-logo]:pb-[0]", "tw:[&_>_.athlete-portal-arena-logo]:pl-[0]", "tw:[&_>_.athlete-portal-arena-logo]:[flex-basis:auto]", "tw:[&_>_.athlete-portal-arena-logo]:[object-position:left_center]",
    "tw:[&_>_.athlete-portal-mark]:grid", "tw:[&_>_.athlete-portal-mark]:w-[52px]", "tw:[&_>_.athlete-portal-mark]:h-[52px]", "tw:[&_>_.athlete-portal-mark]:[flex:0_0_52px]",
    "tw:[&_>_.athlete-portal-mark]:place-items-center", "tw:[&_>_.athlete-portal-mark]:border-t-[length:1px]", "tw:[&_>_.athlete-portal-mark]:[border-top-style:solid]", "tw:[&_>_.athlete-portal-mark]:border-t-[color:rgb(255_255_255_/_.36)]",
    "tw:[&_>_.athlete-portal-mark]:border-r-[length:1px]", "tw:[&_>_.athlete-portal-mark]:[border-right-style:solid]", "tw:[&_>_.athlete-portal-mark]:border-r-[color:rgb(255_255_255_/_.36)]", "tw:[&_>_.athlete-portal-mark]:border-b-[length:1px]",
    "tw:[&_>_.athlete-portal-mark]:[border-bottom-style:solid]", "tw:[&_>_.athlete-portal-mark]:border-b-[color:rgb(255_255_255_/_.36)]", "tw:[&_>_.athlete-portal-mark]:border-l-[length:1px]", "tw:[&_>_.athlete-portal-mark]:[border-left-style:solid]",
    "tw:[&_>_.athlete-portal-mark]:border-l-[color:rgb(255_255_255_/_.36)]", "tw:[&_>_.athlete-portal-mark]:rounded-[13px]", "tw:[&_>_.athlete-portal-mark]:text-[color:#d9fff0]", "tw:[&_>_.athlete-portal-mark]:bg-[color:rgb(0_40_64_/_.22)]",
    "tw:[&_>_.athlete-portal-mark]:[background-image:none]", "tw:[&_>_.athlete-portal-mark]:[box-shadow:0_8px_18px_rgb(0_25_45_/_.16)]", "tw:[&_>_.athlete-portal-mark]:[object-fit:contain]", "tw:viewport-700:[&_>_div]:w-[100%]",
    "tw:viewport-700:[&_h1]:leading-[1.04]", "tw:viewport-700:flex-col",
  ].join(" "),
  athletePortalMark: [
    "athlete-portal-mark", "tw:w-[66px]", "tw:viewport-700:w-[58px]", "tw:h-[66px]",
    "tw:viewport-700:h-[58px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:rgb(255_255_255_/_.2)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:rgb(255_255_255_/_.2)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:rgb(255_255_255_/_.2)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:rgb(255_255_255_/_.2)]", "tw:rounded-[18px]", "tw:[object-fit:cover]", "tw:bg-[color:rgb(255_255_255_/_.94)]",
    "tw:[background-image:none]", "tw:[box-shadow:0_10px_24px_rgb(0_0_0_/_.24)]", "tw:grid", "tw:place-items-center",
    "tw:text-[.82rem]", "tw:font-[900]", "tw:tracking-[.08em]",
  ].join(" "),
  athletePortalBrandCopy: [
    "athlete-portal-brand-copy", "tw:grid", "tw:min-w-[min(260px,_100%)]", "tw:viewport-700:min-w-[0]",
    "tw:gap-y-[2px]", "tw:viewport-700:gap-y-[1px]", "tw:gap-x-[2px]", "tw:viewport-700:gap-x-[1px]",
    "tw:pt-[2px]", "tw:viewport-700:pt-[0]", "tw:[&_.athlete-portal-arena-name]:[overflow-x:hidden]", "tw:[&_.athlete-portal-arena-name]:[overflow-y:hidden]",
    "tw:[&_.athlete-portal-arena-name]:text-[color:#b7f4dd]", "tw:[&_.athlete-portal-arena-name]:text-[.64rem]", "tw:viewport-700:[&_.athlete-portal-arena-name]:text-[.56rem]", "tw:[&_.athlete-portal-arena-name]:font-[900]",
    "tw:[&_.athlete-portal-arena-name]:tracking-[.1em]", "tw:viewport-700:[&_.athlete-portal-arena-name]:tracking-[.13em]", "tw:[&_.athlete-portal-arena-name]:text-ellipsis", "tw:[&_.athlete-portal-arena-name]:uppercase",
    "tw:[&_.athlete-portal-arena-name]:whitespace-nowrap", "tw:[&_h1]:mt-[0]", "tw:[&_h1]:mr-[0]", "tw:[&_h1]:mb-[0]",
    "tw:[&_h1]:ml-[0]", "tw:[&_h1]:text-[clamp(1.28rem,_2.6vw,_1.75rem)]", "tw:viewport-700:[&_h1]:text-[1.55rem]", "tw:[&_p]:[overflow-x:hidden]",
    "tw:[&_p]:[overflow-y:hidden]", "tw:[&_p]:max-w-[600px]", "tw:viewport-700:[&_p]:max-w-[250px]", "tw:[&_p]:text-[color:rgb(255_255_255_/_.78)]",
    "tw:[&_p]:text-ellipsis", "tw:[&_p]:whitespace-nowrap", "tw:viewport-700:[&_h1]:leading-[1.04]", "tw:viewport-700:pr-[0]",
    "tw:viewport-700:pb-[0]", "tw:viewport-700:pl-[0]",
  ].join(" "),
  formSuccess: [
    "form-success", "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]",
    "tw:ml-[0]", "tw:pt-[12px]", "tw:pr-[14px]", "tw:pb-[12px]",
    "tw:pl-[14px]", "tw:rounded-[0]", "tw:text-[0.95rem]", "tw:leading-[1.45]",
    "tw:bg-[color:rgba(28,_140,_94,_0.08)]", "tw:[background-image:none]", "tw:text-[color:var(--success)]",
  ].join(" "),
  commandModalBackdrop: [
    "command-modal-backdrop", "tw:fixed", "tw:z-[95]", "tw:top-[0]",
    "tw:right-[0]", "tw:bottom-[0]", "tw:left-[0]", "tw:grid",
    "tw:place-items-center", "tw:pt-[22px]", "tw:viewport-760:pt-[12px]", "tw:pr-[22px]",
    "tw:viewport-760:pr-[12px]", "tw:pb-[22px]", "tw:viewport-760:pb-[12px]", "tw:pl-[22px]",
    "tw:viewport-760:pl-[12px]", "tw:bg-[color:rgb(15_23_42_/_.48)]", "tw:[background-image:none]", "tw:[backdrop-filter:blur(7px)]",
  ].join(" "),
  formErrorFormFull: [
    "form-error", "form-full", "tw:mt-[0]", "tw:mr-[0]",
    "tw:mb-[0]", "tw:ml-[0]", "tw:pt-[12px]", "tw:pr-[14px]",
    "tw:pb-[12px]", "tw:pl-[14px]", "tw:rounded-[0]", "tw:text-[.86rem]",
    "tw:leading-[1.45]", "tw:bg-[color:rgba(191,_63,_56,_0.08)]", "tw:[background-image:none]", "tw:text-[color:#b42318]",
    "tw:[grid-column:1_/_-1]", "tw:viewport-680:[grid-column:auto]", "tw:font-[700]",
  ].join(" "),
  formSuccessFormFull: [
    "form-success", "form-full", "tw:mt-[0]", "tw:mr-[0]",
    "tw:mb-[0]", "tw:ml-[0]", "tw:pt-[12px]", "tw:pr-[14px]",
    "tw:pb-[12px]", "tw:pl-[14px]", "tw:rounded-[0]", "tw:text-[0.95rem]",
    "tw:leading-[1.45]", "tw:bg-[color:rgba(28,_140,_94,_0.08)]", "tw:[background-image:none]", "tw:text-[color:var(--success)]",
    "tw:[grid-column:1_/_-1]",
  ].join(" "),
  mutedFormFull: [
    "muted", "form-full", "tw:mt-[0]", "tw:mr-[0]",
    "tw:mb-[0]", "tw:ml-[0]", "tw:text-[color:var(--muted)]", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  fieldFieldSubmitFormFull: [
    "field", "field-submit", "form-full", "tw:grid",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]",
    "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]",
    "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[14px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]",
    "tw:[&_input]:border-t-[color:var(--line)]", "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]",
    "tw:[&_input]:border-b-[length:1px]", "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]",
    "tw:[&_input]:[border-left-style:solid]", "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]",
    "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:var(--text)]", "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]",
    "tw:[&_select]:min-h-[44px]", "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]",
    "tw:[&_select]:pl-[14px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]",
    "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]",
    "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]",
    "tw:[&_select]:border-l-[color:var(--line)]", "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]",
    "tw:[&_select]:text-[color:var(--text)]", "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]",
    "tw:[&_input:focus]:[transform:translateY(-1px)]", "tw:[&_select:focus]:[outline:none]", "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]",
    "tw:[&_input[type=file]]:pt-[10px]", "tw:[&_input[type=file]]:pr-[14px]", "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]",
    "tw:[&_input[type=checkbox]]:w-[auto]", "tw:[&_input[type=checkbox]]:min-h-[auto]", "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]",
    "tw:[&_input[type=checkbox]]:pb-[0]", "tw:[&_input[type=checkbox]]:pl-[0]", "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]",
    "tw:[&_input[type=radio]]:pt-[0]", "tw:[&_input[type=radio]]:pr-[0]", "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]",
    "tw:[align-self:end]", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  playerInlineActions: [
    "player-inline-actions", "tw:inline-flex", "tw:items-center", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:[flex-shrink:0]",
  ].join(" "),
  playerInlineTextButtonPlayerInlineTextButtonSave: [
    "player-inline-text-button", "player-inline-text-button-save", "tw:focus-visible:[outline:none]", "tw:focus-visible:[box-shadow:0_0_0_4px_rgba(18,_93,_156,_0.1)]",
    "tw:min-h-[auto]", "tw:pt-[0]", "tw:pr-[0]", "tw:pb-[0]",
    "tw:pl-[0]", "tw:border-t-[length:medium]", "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]",
    "tw:border-r-[length:medium]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:medium]",
    "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:medium]", "tw:[border-left-style:none]",
    "tw:border-l-[color:currentColor]", "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:text-[color:var(--brand)]",
    "tw:text-[0.86rem]", "tw:font-[700]", "tw:hover:text-[color:var(--brand-strong)]",
  ].join(" "),
  playerInlineTextButton: [
    "player-inline-text-button", "tw:focus-visible:[outline:none]", "tw:focus-visible:[box-shadow:0_0_0_4px_rgba(18,_93,_156,_0.1)]", "tw:min-h-[auto]",
    "tw:pt-[0]", "tw:pr-[0]", "tw:pb-[0]", "tw:pl-[0]",
    "tw:border-t-[length:medium]", "tw:[border-top-style:none]", "tw:border-t-[color:currentColor]", "tw:border-r-[length:medium]",
    "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]", "tw:border-b-[length:medium]", "tw:[border-bottom-style:none]",
    "tw:border-b-[color:currentColor]", "tw:border-l-[length:medium]", "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]",
    "tw:bg-[color:transparent]", "tw:[background-image:none]", "tw:text-[color:var(--muted)]", "tw:text-[0.86rem]",
    "tw:font-[700]", "tw:hover:text-[color:var(--text)]",
  ].join(" "),
  playerInlineIconButton: [
    "player-inline-icon-button", "tw:inline-flex", "tw:items-center", "tw:justify-center",
    "tw:w-[28px]", "tw:h-[28px]", "tw:pt-[0]", "tw:pr-[0]",
    "tw:pb-[0]", "tw:pl-[0]", "tw:border-t-[length:medium]", "tw:[border-top-style:none]",
    "tw:border-t-[color:currentColor]", "tw:border-r-[length:medium]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:medium]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:medium]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[999px]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:text-[color:var(--muted)]", "tw:cursor-pointer", "tw:[transition:color_160ms_ease,_background-color_160ms_ease,_transform_160ms_ease]",
    "tw:hover:bg-[color:rgba(18,_93,_156,_0.08)]", "tw:hover:[background-image:none]", "tw:hover:text-[color:var(--brand)]", "tw:hover:[transform:translateY(-1px)]",
    "tw:focus-visible:[outline:none]", "tw:focus-visible:[box-shadow:0_0_0_4px_rgba(18,_93,_156,_0.1)]", "tw:[&_svg]:w-[16px]", "tw:[&_svg]:h-[16px]",
  ].join(" "),
  publicBookingMessage: [
    "public-booking-message", "tw:[grid-column:1_/_-1]", "tw:text-[color:#176b3b]!", "tw:font-[700]",
  ].join(" "),
  teacherPlanEditModal: [
    "teacher-plan-edit-modal", "tw:fixed", "tw:z-[90]", "tw:top-[0]",
    "tw:right-[0]", "tw:bottom-[0]", "tw:left-[0]", "tw:grid",
    "tw:place-items-center", "tw:pt-[20px]", "tw:viewport-600:pt-[12px]", "tw:pr-[20px]",
    "tw:viewport-600:pr-[12px]", "tw:pb-[20px]", "tw:viewport-600:pb-[12px]", "tw:pl-[20px]",
    "tw:viewport-600:pl-[12px]", "tw:bg-[color:rgb(10_29_54_/_.34)]", "tw:[background-image:none]", "tw:[backdrop-filter:blur(3px)]",
    "tw:[&_.teacher-plan-edit-form]:static", "tw:[&_.teacher-plan-edit-form]:w-[auto]", "tw:[&_.teacher-plan-edit-form]:pt-[0]", "tw:[&_.teacher-plan-edit-form]:pr-[0]",
    "tw:[&_.teacher-plan-edit-form]:pb-[0]", "tw:[&_.teacher-plan-edit-form]:pl-[0]", "tw:[&_.teacher-plan-edit-form]:border-t-[length:0]", "tw:[&_.teacher-plan-edit-form]:[border-top-style:none]",
    "tw:[&_.teacher-plan-edit-form]:border-t-[color:currentColor]", "tw:[&_.teacher-plan-edit-form]:border-r-[length:0]", "tw:[&_.teacher-plan-edit-form]:[border-right-style:none]", "tw:[&_.teacher-plan-edit-form]:border-r-[color:currentColor]",
    "tw:[&_.teacher-plan-edit-form]:border-b-[length:0]", "tw:[&_.teacher-plan-edit-form]:[border-bottom-style:none]", "tw:[&_.teacher-plan-edit-form]:border-b-[color:currentColor]", "tw:[&_.teacher-plan-edit-form]:border-l-[length:0]",
    "tw:[&_.teacher-plan-edit-form]:[border-left-style:none]", "tw:[&_.teacher-plan-edit-form]:border-l-[color:currentColor]", "tw:[&_.teacher-plan-edit-form]:rounded-[0]", "tw:[&_.teacher-plan-edit-form]:[box-shadow:none]",
    "tw:viewport-600:[align-items:end]",
  ].join(" "),
  teacherPlanEditDialog: [
    "teacher-plan-edit-dialog", "tw:grid", "tw:gap-y-[15px]", "tw:gap-x-[15px]",
    "tw:w-[min(390px,_100%)]", "tw:pt-[19px]", "tw:pr-[19px]", "tw:pb-[19px]",
    "tw:pl-[19px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d8e5f0]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d8e5f0]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d8e5f0]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#d8e5f0]", "tw:rounded-[13px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[box-shadow:0_22px_54px_rgb(12_33_61_/_.22)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:items-start", "tw:[&_>_header]:justify-between",
    "tw:[&_>_header]:gap-y-[12px]", "tw:[&_>_header]:gap-x-[12px]", "tw:[&_>_header]:pb-[12px]", "tw:[&_>_header]:border-b-[length:1px]",
    "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#e3ebf3]", "tw:[&_h2]:mt-[3px]", "tw:[&_h2]:mr-[0]",
    "tw:[&_h2]:mb-[0]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#12213f]", "tw:[&_h2]:text-[1.05rem]",
  ].join(" "),
  teacherPlanEditClose: [
    "teacher-plan-edit-close", "tw:grid", "tw:w-[30px]", "tw:h-[30px]",
    "tw:place-items-center", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d4e0ed]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d4e0ed]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d4e0ed]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#d4e0ed]", "tw:rounded-[7px]", "tw:text-[color:#42607e]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:text-[1.1rem]", "tw:cursor-pointer",
  ].join(" "),
  teacherPlanEditForm: [
    "teacher-plan-edit-form", "tw:absolute", "tw:z-[15]", "tw:top-[calc(100%_+_6px)]",
    "tw:right-[0]", "tw:grid", "tw:w-[min(340px,_calc(100vw_-_48px))]", "tw:viewport-600:w-[min(320px,_calc(100vw_-_42px))]",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:pt-[11px]", "tw:pr-[11px]",
    "tw:pb-[11px]", "tw:pl-[11px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#c9dceb]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#c9dceb]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#c9dceb]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#c9dceb]", "tw:rounded-[10px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[box-shadow:0_12px_28px_rgb(17_53_84_/_.16)]", "tw:[&_label]:grid", "tw:[&_label]:gap-y-[3px]",
    "tw:[&_label]:gap-x-[3px]", "tw:[&_label]:text-[color:#506980]", "tw:[&_label]:text-[.68rem]", "tw:[&_label]:font-[750]",
    "tw:[&_input]:min-h-[32px]", "tw:[&_input]:pt-[5px]", "tw:[&_input]:pr-[8px]", "tw:[&_input]:pb-[5px]",
    "tw:[&_input]:pl-[8px]", "tw:[&_input]:text-[.78rem]", "tw:[&_.button]:[justify-self:end]",
  ].join(" "),
  teacherPlanEditActions: [
    "teacher-plan-edit-actions", "tw:flex", "tw:justify-end", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:mt-[3px]", "tw:[&_.button]:min-h-[34px]",
  ].join(" "),
  sectionCardStackMdCategoryOperationPanel: [
    "section-card", "stack-md", "category-operation-panel", "tw:pt-[18px]",
    "tw:viewport-760:pt-[16px]", "tw:pr-[20px]", "tw:viewport-760:pr-[16px]", "tw:pb-[18px]",
    "tw:viewport-760:pb-[16px]", "tw:pl-[20px]", "tw:viewport-760:pl-[16px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#d7e4f1]", "tw:border-r-[length:0]", "tw:[border-right-style:none]",
    "tw:border-r-[color:#d7e4f1]", "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:#d7e4f1]",
    "tw:border-l-[length:0]", "tw:[border-left-style:none]", "tw:border-l-[color:#d7e4f1]", "tw:rounded-[16px]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[box-shadow:0_8px_22px_rgb(17_62_112_/_.055)]", "tw:grid",
    "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]",
    "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]", "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]",
    "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]", "tw:[&_>_.page-header]:items-center", "tw:[&_>_.page-header]:pb-[12px]", "tw:[&_>_.page-header]:border-b-[length:1px]",
    "tw:[&_>_.page-header]:[border-bottom-style:solid]", "tw:[&_>_.page-header]:border-b-[color:#e2ebf4]", "tw:[&_.page-header_h3]:mt-[0]", "tw:[&_.page-header_h3]:mr-[0]",
    "tw:[&_.page-header_h3]:mb-[0]", "tw:[&_.page-header_h3]:ml-[0]", "tw:[&_.page-header_h3]:text-[color:#0b3568]", "tw:[&_.page-header_h3]:text-[1.05rem]",
    "tw:[&_.grid-form]:pt-[12px]", "tw:[&_.grid-form]:pr-[12px]", "tw:[&_.grid-form]:pb-[12px]", "tw:[&_.grid-form]:pl-[12px]",
    "tw:[&_.grid-form]:border-t-[length:1px]", "tw:[&_.grid-form]:[border-top-style:solid]", "tw:[&_.grid-form]:border-t-[color:#dce8f4]", "tw:[&_.grid-form]:border-r-[length:1px]",
    "tw:[&_.grid-form]:[border-right-style:solid]", "tw:[&_.grid-form]:border-r-[color:#dce8f4]", "tw:[&_.grid-form]:border-b-[length:1px]", "tw:[&_.grid-form]:[border-bottom-style:solid]",
    "tw:[&_.grid-form]:border-b-[color:#dce8f4]", "tw:[&_.grid-form]:border-l-[length:1px]", "tw:[&_.grid-form]:[border-left-style:solid]", "tw:[&_.grid-form]:border-l-[color:#dce8f4]",
    "tw:[&_.grid-form]:rounded-[11px]", "tw:[&_.grid-form]:bg-[color:#f8fbff]", "tw:[&_.grid-form]:[background-image:none]", "tw:[&_.section-actions]:pt-[12px]",
    "tw:[&_.section-actions]:pr-[12px]", "tw:[&_.section-actions]:pb-[12px]", "tw:[&_.section-actions]:pl-[12px]", "tw:[&_.section-actions]:border-t-[length:1px]",
    "tw:[&_.section-actions]:[border-top-style:solid]", "tw:[&_.section-actions]:border-t-[color:#dce8f4]", "tw:[&_.section-actions]:border-r-[length:1px]", "tw:[&_.section-actions]:[border-right-style:solid]",
    "tw:[&_.section-actions]:border-r-[color:#dce8f4]", "tw:[&_.section-actions]:border-b-[length:1px]", "tw:[&_.section-actions]:[border-bottom-style:solid]", "tw:[&_.section-actions]:border-b-[color:#dce8f4]",
    "tw:[&_.section-actions]:border-l-[length:1px]", "tw:[&_.section-actions]:[border-left-style:solid]", "tw:[&_.section-actions]:border-l-[color:#dce8f4]", "tw:[&_.section-actions]:rounded-[11px]",
    "tw:[&_.section-actions]:bg-[color:#f8fbff]", "tw:[&_.section-actions]:[background-image:none]", "tw:[&_.section-actions]:flex", "tw:[&_.section-actions]:flex-wrap",
    "tw:[&_.section-actions]:items-center", "tw:[&_.section-actions]:gap-y-[8px]", "tw:[&_.section-actions]:gap-x-[8px]", "tw:[&_.category-game-filter-toolbar]:pt-[12px]",
    "tw:[&_.category-game-filter-toolbar]:pr-[12px]", "tw:[&_.category-game-filter-toolbar]:pb-[12px]", "tw:[&_.category-game-filter-toolbar]:pl-[12px]", "tw:[&_.category-game-filter-toolbar]:border-t-[length:1px]",
    "tw:[&_.category-game-filter-toolbar]:[border-top-style:solid]", "tw:[&_.category-game-filter-toolbar]:border-t-[color:#dce8f4]", "tw:[&_.category-game-filter-toolbar]:border-r-[length:1px]", "tw:[&_.category-game-filter-toolbar]:[border-right-style:solid]",
    "tw:[&_.category-game-filter-toolbar]:border-r-[color:#dce8f4]", "tw:[&_.category-game-filter-toolbar]:border-b-[length:1px]", "tw:[&_.category-game-filter-toolbar]:[border-bottom-style:solid]", "tw:[&_.category-game-filter-toolbar]:border-b-[color:#dce8f4]",
    "tw:[&_.category-game-filter-toolbar]:border-l-[length:1px]", "tw:[&_.category-game-filter-toolbar]:[border-left-style:solid]", "tw:[&_.category-game-filter-toolbar]:border-l-[color:#dce8f4]", "tw:[&_.category-game-filter-toolbar]:rounded-[11px]",
    "tw:[&_.category-game-filter-toolbar]:bg-[color:#f8fbff]", "tw:[&_.category-game-filter-toolbar]:[background-image:none]", "tw:[&_.category-game-filter-toolbar]:[align-items:end]", "tw:[&_.section-actions_.button]:min-h-[36px]",
    "tw:[&_.section-actions_.button]:[padding-inline:12px]", "tw:[&_.simple-item]:border-t-[color:#dce7f2]", "tw:[&_.simple-item]:border-r-[color:#dce7f2]", "tw:[&_.simple-item]:border-b-[color:#dce7f2]",
    "tw:[&_.simple-item]:border-l-[color:#dce7f2]", "tw:[&_.simple-item]:bg-[color:#fff]", "tw:[&_.simple-item]:[background-image:none]", "tw:[&_.simple-item]:[box-shadow:none]",
    "tw:[&_.category-game-row]:border-t-[color:#dce7f2]", "tw:[&_.category-game-row]:border-r-[color:#dce7f2]", "tw:[&_.category-game-row]:border-b-[color:#dce7f2]", "tw:[&_.category-game-row]:border-l-[color:#dce7f2]",
    "tw:[&_.category-game-row]:bg-[color:#fff]", "tw:[&_.category-game-row]:[background-image:none]", "tw:[&_.category-game-row]:[box-shadow:none]", "tw:[&_.category-game-row]:pt-[15px]",
    "tw:[&_.category-game-row]:pr-[16px]", "tw:[&_.category-game-row]:pb-[15px]", "tw:[&_.category-game-row]:pl-[16px]", "tw:[&_.category-game-row]:rounded-[12px]",
    "tw:[&_.simple-item:hover]:border-t-[color:#bfd4eb]", "tw:[&_.simple-item:hover]:border-r-[color:#bfd4eb]", "tw:[&_.simple-item:hover]:border-b-[color:#bfd4eb]", "tw:[&_.simple-item:hover]:border-l-[color:#bfd4eb]",
    "tw:[&_.simple-item:hover]:[box-shadow:0_6px_16px_rgb(17_62_112_/_.06)]", "tw:[&_.category-game-row:hover]:border-t-[color:#bfd4eb]", "tw:[&_.category-game-row:hover]:border-r-[color:#bfd4eb]", "tw:[&_.category-game-row:hover]:border-b-[color:#bfd4eb]",
    "tw:[&_.category-game-row:hover]:border-l-[color:#bfd4eb]", "tw:[&_.category-game-row:hover]:[box-shadow:0_6px_16px_rgb(17_62_112_/_.06)]", "tw:[&_.simple-grid_>_.section-card]:pt-[16px]", "tw:[&_.simple-grid_>_.section-card]:pr-[16px]",
    "tw:[&_.simple-grid_>_.section-card]:pb-[16px]", "tw:[&_.simple-grid_>_.section-card]:pl-[16px]", "tw:[&_.simple-grid_>_.section-card]:border-t-[color:#dce7f2]", "tw:[&_.simple-grid_>_.section-card]:border-r-[color:#dce7f2]",
    "tw:[&_.simple-grid_>_.section-card]:border-b-[color:#dce7f2]", "tw:[&_.simple-grid_>_.section-card]:border-l-[color:#dce7f2]", "tw:[&_.simple-grid_>_.section-card]:rounded-[13px]", "tw:[&_.simple-grid_>_.section-card]:bg-[color:#fff]",
    "tw:[&_.simple-grid_>_.section-card]:[background-image:none]", "tw:[&_.simple-grid_>_.section-card]:[box-shadow:none]",
  ].join(" "),
} as const;
