import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "stack_md_sponsorship_management_page": [
    "stack-md", "sponsorship-management-page", "tw:grid", "tw:gap-y-[18px]",
    "tw:gap-x-[18px]", "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]",
    "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]", "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]",
    "tw:max-w-[1120px]",
  ].join(" "),
  "sponsorship_management_toolbar": [
    "sponsorship-management-toolbar", "tw:flex", "tw:items-end", "tw:viewport-760:items-stretch",
    "tw:justify-between", "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:pt-[14px]",
    "tw:pr-[14px]", "tw:pb-[14px]", "tw:pl-[14px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#dce7f2]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#dce7f2]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce7f2]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#dce7f2]", "tw:rounded-[14px]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:viewport-760:flex-col", "tw:viewport-760:[&_>_.button]:w-[100%]",
    "tw:viewport-760:[&_>_.button]:justify-center",
  ].join(" "),
  "active_event_list_sponsor_plan_list": [
    "active-event-list", "sponsor-plan-list", "tw:grid", "tw:grid-cols-[repeat(auto-fit,_minmax(290px,_360px))]",
    "tw:viewport-640:grid-cols-[1fr]", "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:[justify-content:start]",
  ].join(" "),
  "active_event_row_sponsor_plan_row": [
    "active-event-row", "sponsor-plan-row", "tw:grid", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:min-h-[0]", "tw:pt-[18px]", "tw:pr-[18px]",
    "tw:pb-[18px]", "tw:pl-[18px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dce7f2]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce7f2]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce7f2]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dce7f2]", "tw:rounded-[14px]", "tw:bg-[color:#fff]",
    "tw:[background-image:none]", "tw:[box-shadow:0_8px_22px_rgb(19_55_104_/_.055)]", "tw:[&_>_div:first-child]:grid", "tw:[&_>_div:first-child]:[align-content:start]",
    "tw:[&_>_div:first-child]:gap-y-[5px]", "tw:[&_>_div:first-child]:gap-x-[5px]", "tw:viewport-760:items-start", "tw:viewport-760:flex-col",
    "tw:[&_strong]:block", "tw:[&_strong]:text-[color:#132d58]", "tw:[&_strong]:text-[1rem]", "tw:[&_span]:block",
    "tw:[&_span]:mt-[0]", "tw:[&_span]:mr-[0]", "tw:[&_span]:mb-[0]", "tw:[&_span]:ml-[0]",
    "tw:[&_span]:text-[color:#7184a5]", "tw:[&_span]:text-[.78rem]", "tw:[&_.sponsor-benefit-tags]:mt-[5px]",
  ].join(" "),
  "sponsor_benefit_tags": [
    "sponsor-benefit-tags", "tw:[&_span]:inline-flex", "tw:[&_span]:items-center", "tw:[&_span]:gap-y-[5px]",
    "tw:[&_span]:gap-x-[5px]", "tw:[&_span]:pt-[5px]", "tw:[&_span]:pr-[8px]", "tw:[&_span]:pb-[5px]",
    "tw:[&_span]:pl-[8px]", "tw:[&_span]:border-t-[length:1px]", "tw:[&_span]:[border-top-style:solid]", "tw:[&_span]:border-t-[color:var(--border)]",
    "tw:[&_span]:border-r-[length:1px]", "tw:[&_span]:[border-right-style:solid]", "tw:[&_span]:border-r-[color:var(--border)]", "tw:[&_span]:border-b-[length:1px]",
    "tw:[&_span]:[border-bottom-style:solid]", "tw:[&_span]:border-b-[color:var(--border)]", "tw:[&_span]:border-l-[length:1px]", "tw:[&_span]:[border-left-style:solid]",
    "tw:[&_span]:border-l-[color:var(--border)]", "tw:[&_span]:rounded-[999px]", "tw:[&_span]:bg-[color:var(--surface)]", "tw:[&_span]:[background-image:none]",
    "tw:[&_span]:text-[color:var(--muted)]", "tw:[&_span]:text-[.7rem]", "tw:[&_span]:font-[700]", "tw:flex",
    "tw:flex-wrap", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
  ].join(" "),
  "sponsor_company_list": [
    "sponsor-company-list", "tw:grid", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:[&_>_strong]:text-[.78rem]",
  ].join(" "),
  "sponsor_company_row": [
    "sponsor-company-row", "tw:grid", "tw:grid-cols-[32px_minmax(0,_1fr)_auto]", "tw:items-center",
    "tw:gap-y-[9px]", "tw:gap-x-[9px]", "tw:pt-[8px]", "tw:pr-[10px]",
    "tw:pb-[8px]", "tw:pl-[10px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--border)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--border)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--border)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--border)]", "tw:rounded-[9px]", "tw:bg-[color:var(--surface-muted)]",
    "tw:[background-image:none]", "tw:[&_img]:w-[32px]", "tw:[&_img]:h-[32px]", "tw:[&_img]:[object-fit:contain]",
    "tw:[&_img]:rounded-[7px]", "tw:[&_img]:bg-[color:var(--surface)]", "tw:[&_img]:[background-image:none]", "tw:[&_>_span]:w-[32px]",
    "tw:[&_>_span]:h-[32px]", "tw:[&_>_span]:[object-fit:contain]", "tw:[&_>_span]:rounded-[7px]", "tw:[&_>_span]:bg-[color:var(--surface)]",
    "tw:[&_>_span]:[background-image:none]", "tw:[&_>_span]:grid", "tw:[&_>_span]:place-items-center", "tw:[&_>_span]:text-[.72rem]",
    "tw:[&_>_span]:font-[800]", "tw:[&_b]:[overflow-x:hidden]", "tw:[&_b]:[overflow-y:hidden]", "tw:[&_b]:text-ellipsis",
    "tw:[&_b]:whitespace-nowrap", "tw:[&_b]:text-[.82rem]", "tw:[&_.button]:min-w-[30px]", "tw:[&_.button]:[padding-inline:7px]",
  ].join(" "),
  "button_button_danger_button_small_sponsor_delete_button": [
    "button", "button-danger", "button-small", "sponsor-delete-button",
    "tw:inline-flex", "tw:items-center", "tw:justify-center", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:min-h-[30px]", "tw:pt-[0]!", "tw:pr-[0]!",
    "tw:pb-[0]!", "tw:pl-[0]!", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#c92921]!", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#c92921]!",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#c92921]!", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#c92921]!", "tw:rounded-[var(--radius-control)]", "tw:bg-[color:#c92921]!",
    "tw:[background-image:url(data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2024%2024%22%20fill%3D%22none%22%20stroke%3D%22white%22%20stroke-width%3D%222%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%3E%3Cpath%20d%3D%22M3%206h18%22%2F%3E%3Cpath%20d%3D%22M8%206V4h8v2%22%2F%3E%3Cpath%20d%3D%22M19%206l-1%2014H6L5%206%22%2F%3E%3Cpath%20d%3D%22M10%2011v5M14%2011v5%22%2F%3E%3C%2Fsvg%3E)]", "tw:text-[color:transparent]!", "tw:text-[0]!", "tw:[transition:transform_180ms_var(--ease-standard),_border-color_180ms_var(--ease-standard),_background_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_color_180ms_var(--ease-standard)]",
    "tw:hover:border-t-[color:var(--danger)]", "tw:hover:border-r-[color:var(--danger)]", "tw:hover:border-b-[color:var(--danger)]", "tw:hover:border-l-[color:var(--danger)]",
    "tw:hover:[transform:translateY(-1px)]", "tw:hover:[box-shadow:0_10px_20px_rgba(28,_54,_89,_0.08)]", "tw:disabled:opacity-[0.72]", "tw:disabled:cursor-wait",
    "tw:[&:active]:[transform:translateY(0)]", "tw:[&:active]:[box-shadow:none]", "tw:hover:bg-[color:#a91f19]!", "tw:hover:[background-image:none]",
    "tw:hover:text-[color:#992f29]", "tw:w-[32px]", "tw:min-w-[32px]!", "tw:h-[32px]",
    "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:[background-position:center]", "tw:[background-repeat:no-repeat]",
    "tw:[background-size:15px]", "tw:[text-indent:0]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "active_event_actions": [
    "active-event-actions", "tw:flex", "tw:flex-wrap", "tw:[align-self:end]",
    "tw:justify-start", "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:[&_.button]:min-h-[36px]",
    "tw:[&_.button]:[padding-inline:12px]", "tw:[&_.button]:text-[.78rem]", "tw:[&_.button]:font-[700]",
  ].join(" "),
  "button_button_primary_button_small": sharedUtilities.buttonButtonPrimaryButtonSmall,
  "button_button_secondary_button_small": sharedUtilities.buttonButtonSecondaryButtonSmall,
  "sponsor_empty_state": [
    "sponsor-empty-state", "tw:grid", "tw:gap-y-[5px]", "tw:gap-x-[5px]",
    "tw:max-w-[520px]", "tw:pt-[18px]", "tw:pr-[18px]", "tw:pb-[18px]",
    "tw:pl-[18px]", "tw:border-t-[length:1px]", "tw:[border-top-style:dashed]", "tw:border-t-[color:#c8d8e8]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:dashed]", "tw:border-r-[color:#c8d8e8]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:dashed]", "tw:border-b-[color:#c8d8e8]", "tw:border-l-[length:1px]", "tw:[border-left-style:dashed]",
    "tw:border-l-[color:#c8d8e8]", "tw:rounded-[14px]", "tw:bg-[color:#f8fbfe]", "tw:[background-image:none]",
    "tw:text-[color:#526987]", "tw:[&_strong]:text-[color:#132d58]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#6f829f]", "tw:[&_p]:text-[.82rem]",
  ].join(" "),
} as const;
