import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "stack_md": sharedUtilities.stackMd,
  "arena_settings_layout": [
    "arena-settings-layout", "tw:grid", "tw:grid-cols-[220px_minmax(0,_1fr)]", "tw:viewport-760:grid-cols-[1fr]",
    "tw:gap-y-[22px]", "tw:viewport-760:gap-y-[14px]", "tw:gap-x-[22px]", "tw:viewport-760:gap-x-[14px]",
    "tw:[align-items:start]",
  ].join(" "),
  "arena_settings_nav": [
    "arena-settings-nav", "tw:sticky", "tw:viewport-760:static", "tw:top-[20px]",
    "tw:grid", "tw:gap-y-[4px]", "tw:gap-x-[4px]", "tw:pt-[10px]",
    "tw:viewport-760:pt-[6px]", "tw:pr-[10px]", "tw:viewport-760:pr-[6px]", "tw:pb-[10px]",
    "tw:viewport-760:pb-[6px]", "tw:pl-[10px]", "tw:viewport-760:pl-[6px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#dce7f5]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#dce7f5]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce7f5]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#dce7f5]", "tw:rounded-[14px]",
    "tw:bg-[color:#f8fbff]", "tw:[background-image:none]", "tw:viewport-760:grid-cols-[repeat(4,_minmax(0,_1fr))]",
  ].join(" "),
  "arena_settings_nav_link": [
    "arena-settings-nav-link", "is-active", "tw:flex", "tw:items-center",
    "tw:min-h-[38px]", "tw:viewport-760:min-h-[36px]", "tw:pt-[8px]", "tw:viewport-760:pt-[7px]",
    "tw:pr-[10px]", "tw:viewport-760:pr-[6px]", "tw:pb-[8px]", "tw:viewport-760:pb-[7px]",
    "tw:pl-[10px]", "tw:viewport-760:pl-[6px]", "tw:rounded-[9px]", "tw:text-[color:#3e587b]",
    "tw:text-[.86rem]", "tw:viewport-760:text-[.74rem]", "tw:font-[700]", "tw:[text-decoration:none]",
    "tw:[transition:background_.16s_ease,_color_.16s_ease,_box-shadow_.16s_ease]", "tw:hover:bg-[color:#edf5ff]", "tw:hover:[background-image:none]", "tw:hover:text-[color:#0e5bb5]",
    "tw:[&.is-active]:bg-[color:#1261bb]", "tw:[&.is-active]:[background-image:none]", "tw:[&.is-active]:text-[color:#fff]", "tw:[&.is-active]:[box-shadow:0_5px_12px_rgba(18,_97,_187,_.2)]",
    "tw:viewport-760:justify-center", "tw:viewport-760:text-center",
  ].join(" "),
  "arena_settings_nav_link_2": [
    "arena-settings-nav-link", "tw:flex", "tw:items-center", "tw:min-h-[38px]",
    "tw:viewport-760:min-h-[36px]", "tw:pt-[8px]", "tw:viewport-760:pt-[7px]", "tw:pr-[10px]",
    "tw:viewport-760:pr-[6px]", "tw:pb-[8px]", "tw:viewport-760:pb-[7px]", "tw:pl-[10px]",
    "tw:viewport-760:pl-[6px]", "tw:rounded-[9px]", "tw:text-[color:#3e587b]", "tw:text-[.86rem]",
    "tw:viewport-760:text-[.74rem]", "tw:font-[700]", "tw:[text-decoration:none]", "tw:[transition:background_.16s_ease,_color_.16s_ease,_box-shadow_.16s_ease]",
    "tw:hover:bg-[color:#edf5ff]", "tw:hover:[background-image:none]", "tw:hover:text-[color:#0e5bb5]", "tw:[&.is-active]:bg-[color:#1261bb]",
    "tw:[&.is-active]:[background-image:none]", "tw:[&.is-active]:text-[color:#fff]", "tw:[&.is-active]:[box-shadow:0_5px_12px_rgba(18,_97,_187,_.2)]", "tw:viewport-760:justify-center",
    "tw:viewport-760:text-center",
  ].join(" "),
  "arena_settings_content": [
    "arena-settings-content", "tw:min-w-[0]",
  ].join(" "),
  "arena_profile_layout": [
    "arena-profile-layout", "tw:grid", "tw:grid-cols-[220px_minmax(0,_1fr)]", "tw:viewport-760:grid-cols-[1fr]",
    "tw:gap-y-[24px]", "tw:gap-x-[24px]", "tw:[align-items:start]",
  ].join(" "),
  "arena_logo_preview": [
    "arena-logo-preview", "tw:grid", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
    "tw:[justify-items:center]", "tw:pt-[18px]", "tw:pr-[18px]", "tw:pb-[18px]",
    "tw:pl-[18px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[var(--radius-lg)]", "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]",
    "tw:text-center", "tw:[&_img]:w-[150px]", "tw:[&_img]:h-[150px]", "tw:[&_img]:[object-fit:contain]",
    "tw:[&_img]:rounded-[50%]", "tw:[&_img]:bg-[color:#ffffff]", "tw:[&_img]:[background-image:none]", "tw:[&_img]:[box-shadow:var(--shadow)]",
  ].join(" "),
  "arena_whatsapp_panel": [
    "arena-whatsapp-panel", "tw:grid", "tw:gap-y-[16px]", "tw:gap-x-[16px]",
    "tw:max-w-[720px]",
  ].join(" "),
  "arena_whatsapp_panel_header": [
    "arena-whatsapp-panel-header", "tw:[&_strong]:block", "tw:[&_strong]:mt-[6px]", "tw:[&_strong]:text-[color:#17385f]",
    "tw:[&_p]:mt-[4px]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
  ].join(" "),
  "agency_connection_status": [
    "agency-connection-status", "tw:inline-flex", "tw:items-center", "tw:gap-y-[6px]",
    "tw:gap-x-[6px]", "tw:text-[color:#9a6311]", "tw:text-[.68rem]", "tw:font-[800]",
    "tw:[&_i]:w-[7px]", "tw:[&_i]:h-[7px]", "tw:[&_i]:rounded-[50%]", "tw:[&_i]:bg-[color:#dca239]",
    "tw:[&_i]:[background-image:none]", "tw:[&.is-connected]:text-[color:#15704e]", "tw:[&.is-connected_i]:bg-[color:#1cab72]", "tw:[&.is-connected_i]:[background-image:none]",
  ].join(" "),
  "agency_whatsapp_qr": [
    "agency-whatsapp-qr", "tw:flex", "tw:items-center", "tw:viewport-620:items-start",
    "tw:gap-y-[18px]", "tw:gap-x-[18px]", "tw:pt-[13px]", "tw:pr-[13px]",
    "tw:pb-[13px]", "tw:pl-[13px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#cfe0ec]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#cfe0ec]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#cfe0ec]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#cfe0ec]", "tw:rounded-[10px]", "tw:bg-[color:#f8fbfd]",
    "tw:[background-image:none]", "tw:[&_img]:w-[170px]", "tw:viewport-620:[&_img]:w-[150px]", "tw:[&_img]:h-[170px]",
    "tw:viewport-620:[&_img]:h-[150px]", "tw:[&_img]:[object-fit:contain]", "tw:[&_img]:rounded-[7px]", "tw:[&_img]:bg-[color:#fff]",
    "tw:[&_img]:[background-image:none]", "tw:[&_>_div]:grid", "tw:[&_>_div]:gap-y-[5px]", "tw:[&_>_div]:gap-x-[5px]",
    "tw:[&_strong]:text-[color:#194166]", "tw:[&_strong]:text-[.84rem]", "tw:[&_.safe-action-form]:mt-[5px]", "tw:viewport-620:flex-col",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "button_button_primary_button_small": sharedUtilities.buttonButtonPrimaryButtonSmall,
  "arena_whatsapp_reset": [
    "arena-whatsapp-reset", "tw:grid", "tw:[justify-items:start]", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:mt-[18px]", "tw:pt-[14px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#d9e3eb]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]",
    "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#65748b]", "tw:[&_p]:text-[.82rem]",
    "tw:[&_.safe-action-form]:mt-[0]", "tw:[&_.safe-action-form]:mr-[0]", "tw:[&_.safe-action-form]:mb-[0]", "tw:[&_.safe-action-form]:ml-[0]",
  ].join(" "),
  "button_button_danger_button_small": sharedUtilities.buttonButtonDangerButtonSmall,
  "form_error": sharedUtilities.formError,
} as const;
