import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "stack_md_workspace_page_tournament_games_page": [
    "stack-md", "workspace-page", "tournament-games-page", "tw:grid",
    "tw:gap-y-[24px]", "tw:viewport-720:gap-y-[18px]", "tw:gap-x-[24px]", "tw:viewport-720:gap-x-[18px]",
    "tw:[&_>_*:nth-child(1)]:[animation-delay:40ms]", "tw:[&_>_*:nth-child(2)]:[animation-delay:100ms]", "tw:[&_>_*:nth-child(3)]:[animation-delay:160ms]", "tw:[&_>_*:nth-child(4)]:[animation-delay:220ms]",
    "tw:[&_>_.section-card:last-child]:border-b-[length:1px]", "tw:[&_>_.section-card:last-child]:[border-bottom-style:solid]", "tw:[&_>_.section-card:last-child]:border-b-[color:var(--line)]", "tw:pt-[5px]",
    "tw:pr-[0]", "tw:pb-[44px]", "tw:pl-[0]", "tw:[&_.page-header]:pt-[4px]",
    "tw:[&_.page-header]:pr-[0]", "tw:[&_.page-header]:pb-[20px]", "tw:[&_.page-header]:pl-[0]", "tw:[&_.page-header]:border-b-[length:1px]",
    "tw:[&_.page-header]:[border-bottom-style:solid]", "tw:[&_.page-header]:border-b-[color:#dfe7f1]", "tw:[&_.page-header_h1]:text-[color:#102b56]", "tw:[&_.page-header_h1]:text-[clamp(1.75rem,_2.3vw,_2.25rem)]",
    "tw:[&_.page-header_h1]:tracking-[-.045em]", "tw:[&_.stats-grid]:gap-y-[16px]", "tw:[&_.stats-grid]:gap-x-[16px]", "tw:[&_.stat-card]:pt-[20px]",
    "tw:[&_.stat-card]:pr-[20px]", "tw:[&_.stat-card]:pb-[20px]", "tw:[&_.stat-card]:pl-[20px]", "tw:[&_.stat-card]:border-t-[length:1px]",
    "tw:[&_.stat-card]:[border-top-style:solid]", "tw:[&_.stat-card]:border-t-[color:#e2e9f3]", "tw:[&_.stat-card]:border-r-[length:1px]", "tw:[&_.stat-card]:[border-right-style:solid]",
    "tw:[&_.stat-card]:border-r-[color:#e2e9f3]", "tw:[&_.stat-card]:border-b-[length:1px]", "tw:[&_.stat-card]:[border-bottom-style:solid]", "tw:[&_.stat-card]:border-b-[color:#e2e9f3]",
    "tw:[&_.stat-card]:border-l-[length:1px]", "tw:[&_.stat-card]:[border-left-style:solid]", "tw:[&_.stat-card]:border-l-[color:#e2e9f3]", "tw:[&_.stat-card]:rounded-[14px]",
    "tw:[&_.stat-card]:bg-[color:#fff]", "tw:[&_.stat-card]:[background-image:none]", "tw:[&_.stat-card]:[box-shadow:0_8px_22px_rgba(19,_55,_104,_.06)]", "tw:[&_.dashboard-grid]:gap-y-[18px]",
    "tw:[&_.dashboard-grid]:gap-x-[18px]", "tw:[&_.section-card]:pt-[21px]", "tw:viewport-720:[&_.section-card]:pt-[16px]", "tw:[&_.section-card]:pr-[21px]",
    "tw:viewport-720:[&_.section-card]:pr-[16px]", "tw:[&_.section-card]:pb-[21px]", "tw:viewport-720:[&_.section-card]:pb-[16px]", "tw:[&_.section-card]:pl-[21px]",
    "tw:viewport-720:[&_.section-card]:pl-[16px]", "tw:[&_.section-card]:border-t-[length:1px]", "tw:[&_.section-card]:[border-top-style:solid]", "tw:[&_.section-card]:border-t-[color:#e2e9f3]",
    "tw:[&_.section-card]:border-r-[length:1px]", "tw:[&_.section-card]:[border-right-style:solid]", "tw:[&_.section-card]:border-r-[color:#e2e9f3]", "tw:[&_.section-card]:border-b-[length:1px]",
    "tw:[&_.section-card]:[border-bottom-style:solid]", "tw:[&_.section-card]:border-b-[color:#e2e9f3]", "tw:[&_.section-card]:border-l-[length:1px]", "tw:[&_.section-card]:[border-left-style:solid]",
    "tw:[&_.section-card]:border-l-[color:#e2e9f3]", "tw:[&_.section-card]:rounded-[14px]", "tw:[&_.section-card]:bg-[color:#fff]", "tw:[&_.section-card]:[background-image:none]",
    "tw:[&_.section-card]:[box-shadow:0_8px_22px_rgba(19,_55,_104,_.05)]", "tw:[&_.section-card_+_.section-card]:border-t-[length:1px]", "tw:[&_.section-card_+_.section-card]:[border-top-style:solid]", "tw:[&_.section-card_+_.section-card]:border-t-[color:#e2e9f3]",
    "tw:max-w-[1180px]",
  ].join(" "),
  "page_header": sharedUtilities.pageHeader,
  "eyebrow": sharedUtilities.eyebrow,
  "muted": sharedUtilities.muted,
  "button": sharedUtilities.button,
  "section_card_tournament_games_list": [
    "section-card", "tournament-games-list", "tw:pt-[0]", "tw:pr-[0]",
    "tw:pb-[0]", "tw:pl-[0]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:0]", "tw:[border-right-style:none]", "tw:border-r-[color:currentColor]",
    "tw:border-b-[length:0]", "tw:[border-bottom-style:none]", "tw:border-b-[color:currentColor]", "tw:border-l-[length:0]",
    "tw:[border-left-style:none]", "tw:border-l-[color:currentColor]", "tw:rounded-[0]", "tw:bg-[color:transparent]",
    "tw:[background-image:none]", "tw:[box-shadow:none]", "tw:grid", "tw:gap-y-[0]",
    "tw:gap-x-[0]", "tw:[overflow-x:hidden]", "tw:[overflow-y:hidden]", "tw:[&_>_header]:pt-[18px]",
    "tw:[&_>_header]:pr-[20px]", "tw:[&_>_header]:pb-[18px]", "tw:[&_>_header]:pl-[20px]", "tw:[&_>_header]:border-b-[length:1px]",
    "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#e2eaf3]", "tw:[&_>_header_h2]:mt-[0]", "tw:[&_>_header_h2]:mr-[0]",
    "tw:[&_>_header_h2]:mb-[0]", "tw:[&_>_header_h2]:ml-[0]", "tw:[&_>_header_h2]:text-[color:#17365e]", "tw:[&_>_header_h2]:text-[1rem]",
    "tw:[&_>_header_p]:mt-[4px]", "tw:[&_>_header_p]:mr-[0]", "tw:[&_>_header_p]:mb-[0]", "tw:[&_>_header_p]:ml-[0]",
    "tw:[&_>_header_p]:text-[color:#6c8098]", "tw:[&_>_header_p]:text-[.78rem]", "tw:[&_>_article]:grid", "tw:[&_>_article]:grid-cols-[minmax(260px,_1fr)_minmax(480px,_1.35fr)]",
    "tw:viewport-820:[&_>_article]:grid-cols-[1fr]", "tw:[&_>_article]:items-center", "tw:[&_>_article]:gap-y-[20px]", "tw:viewport-820:[&_>_article]:gap-y-[12px]",
    "tw:[&_>_article]:gap-x-[20px]", "tw:viewport-820:[&_>_article]:gap-x-[12px]", "tw:[&_>_article]:pt-[15px]", "tw:[&_>_article]:pr-[20px]",
    "tw:[&_>_article]:pb-[15px]", "tw:[&_>_article]:pl-[20px]", "tw:[&_>_article]:border-b-[length:1px]", "tw:[&_>_article]:[border-bottom-style:solid]",
    "tw:[&_>_article]:border-b-[color:#e6edf4]", "tw:viewport-460:[&_>_article]:[padding-inline:13px]", "tw:viewport-460:[&_>_header]:[padding-inline:13px]",
  ].join(" "),
  "tournament_games_identification": [
    "tournament-games-identification", "tw:grid", "tw:gap-y-[5px]", "tw:gap-x-[5px]",
    "tw:[&_span]:text-[color:#3670a9]", "tw:[&_span]:text-[.7rem]", "tw:[&_span]:font-[800]", "tw:[&_span]:tracking-[.03em]",
    "tw:[&_strong]:text-[color:#17345a]", "tw:[&_strong]:text-[.85rem]", "tw:[&_b]:text-[color:#8398ad]",
  ].join(" "),
  "tournament_game_schedule": [
    "tournament-game-schedule", "tw:grid", "tw:grid-cols-[minmax(120px,_1fr)_minmax(100px,_.8fr)_minmax(130px,_1fr)_auto]", "tw:viewport-820:grid-cols-[repeat(2,_minmax(0,_1fr))]",
    "tw:viewport-460:grid-cols-[1fr]", "tw:[align-items:end]", "tw:gap-y-[8px]", "tw:gap-x-[8px]",
    "tw:[&_label]:grid", "tw:[&_label]:gap-y-[4px]", "tw:[&_label]:gap-x-[4px]", "tw:[&_label]:text-[color:#59718c]",
    "tw:[&_label]:text-[.68rem]", "tw:[&_label]:font-[750]", "tw:[&_input]:min-h-[36px]", "tw:[&_input]:text-[.78rem]",
    "tw:[&_select]:min-h-[36px]", "tw:[&_select]:text-[.78rem]", "tw:[&_.button]:min-h-[36px]", "tw:[&_.button]:whitespace-nowrap",
    "tw:viewport-820:[&_.button]:[grid-column:1_/_-1]", "tw:viewport-460:[&_.button]:[grid-column:auto]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
} as const;
