import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "athlete_portal_settings_form": [
    "athlete-portal-settings-form", "tw:grid", "tw:gap-y-[14px]", "tw:gap-x-[14px]",
    "tw:[&_.form-note]:mt-[0]", "tw:[&_.form-note]:mr-[0]", "tw:[&_.form-note]:mb-[0]", "tw:[&_.form-note]:ml-[0]",
    "tw:[&_>_.button]:[justify-self:start]",
  ].join(" "),
  "athlete_portal_logo_upload": [
    "athlete-portal-logo-upload", "tw:grid", "tw:gap-y-[6px]", "tw:gap-x-[6px]",
    "tw:max-w-[580px]", "tw:pt-[13px]", "tw:pr-[13px]", "tw:pb-[13px]",
    "tw:pl-[13px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d5e5ed]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#d5e5ed]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#d5e5ed]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#d5e5ed]", "tw:rounded-[10px]", "tw:bg-[color:#f8fcff]", "tw:[background-image:none]",
    "tw:[&_>_span]:text-[color:#174660]", "tw:[&_>_span]:text-[.82rem]", "tw:[&_>_span]:font-[800]", "tw:[&_input]:max-w-[100%]",
    "tw:[&_input]:text-[color:#315b72]", "tw:[&_input]:[font:inherit]", "tw:[&_input]:text-[.78rem]", "tw:[&_small]:text-[color:#668092]",
    "tw:[&_small]:text-[.72rem]", "tw:[&_small]:not-italic", "tw:[&_small]:leading-[1.4]", "tw:[&_em]:text-[color:#08765f]",
    "tw:[&_em]:text-[.72rem]", "tw:[&_em]:not-italic", "tw:[&_em]:leading-[1.4]", "tw:[&_em]:font-[700]",
  ].join(" "),
  "athlete_portal_settings_list": [
    "athlete-portal-settings-list", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-700:grid-cols-[1fr]",
    "tw:gap-y-[9px]", "tw:gap-x-[9px]",
  ].join(" "),
  "control_toggle_athlete_portal_setting": [
    "control-toggle", "athlete-portal-setting", "tw:flex", "tw:items-center",
    "tw:gap-y-[7px]", "tw:gap-x-[7px]", "tw:min-h-[58px]", "tw:cursor-pointer",
    "tw:select-none", "tw:[&_input]:absolute", "tw:[&_input]:[inline-size:1px]!", "tw:[&_input]:[block-size:1px]",
    "tw:[&_input]:[overflow-x:hidden]", "tw:[&_input]:[overflow-y:hidden]", "tw:[&_input]:[clip:rect(0_0_0_0)]", "tw:[&_input]:[clip-path:inset(50%)]",
    "tw:[&_input]:whitespace-nowrap", "tw:[&_span]:relative", "tw:[&_span]:[inline-size:30px]", "tw:[&_span]:[block-size:17px]",
    "tw:[&_span]:[flex:0_0_auto]", "tw:[&_span]:border-t-[length:1px]", "tw:[&_span]:[border-top-style:solid]", "tw:[&_span]:border-t-[color:#b8423a]",
    "tw:[&_span]:border-r-[length:1px]", "tw:[&_span]:[border-right-style:solid]", "tw:[&_span]:border-r-[color:#b8423a]", "tw:[&_span]:border-b-[length:1px]",
    "tw:[&_span]:[border-bottom-style:solid]", "tw:[&_span]:border-b-[color:#b8423a]", "tw:[&_span]:border-l-[length:1px]", "tw:[&_span]:[border-left-style:solid]",
    "tw:[&_span]:border-l-[color:#b8423a]", "tw:[&_span]:rounded-[999px]", "tw:[&_span]:bg-[color:#c94c43]", "tw:[&_span]:[background-image:none]",
    "tw:[&_span]:[box-shadow:inset_0_1px_2px_rgb(66_14_10_/_.22)]", "tw:[&_span]:[transition:background_160ms_var(--ease-standard),_border-color_160ms_var(--ease-standard)]", "tw:[&_span::after]:[content:'']", "tw:[&_span::after]:absolute",
    "tw:[&_span::after]:top-[2px]", "tw:[&_span::after]:left-[2px]", "tw:[&_span::after]:[inline-size:11px]", "tw:[&_span::after]:[block-size:11px]",
    "tw:[&_span::after]:rounded-[50%]", "tw:[&_span::after]:bg-[color:#fff]", "tw:[&_span::after]:[background-image:none]", "tw:[&_span::after]:[box-shadow:0_1px_2px_rgb(15_23_42_/_.24)]",
    "tw:[&_span::after]:[transition:transform_160ms_var(--ease-standard)]", "tw:[&_input:checked_+_span]:border-t-[color:#238448]", "tw:[&_input:checked_+_span]:border-r-[color:#238448]", "tw:[&_input:checked_+_span]:border-b-[color:#238448]",
    "tw:[&_input:checked_+_span]:border-l-[color:#238448]", "tw:[&_input:checked_+_span]:bg-[color:#2fa457]", "tw:[&_input:checked_+_span]:[background-image:none]", "tw:[&_input:checked_+_span::after]:[transform:translateX(13px)]",
    "tw:[&_input:focus-visible_+_span]:[outline:2px_solid_var(--brand)]", "tw:[&_input:focus-visible_+_span]:[outline-offset:2px]", "tw:[&_em]:text-[color:#698091]", "tw:[&_em]:text-[.7rem]",
    "tw:[&_em]:not-italic", "tw:[&_em]:font-[500]", "tw:pt-[10px]", "tw:pr-[12px]",
    "tw:pb-[10px]", "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dce8ee]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce8ee]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce8ee]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dce8ee]", "tw:rounded-[10px]", "tw:bg-[color:#fbfdff]",
    "tw:[background-image:none]", "tw:[&_div]:grid", "tw:[&_div]:gap-y-[2px]", "tw:[&_div]:gap-x-[2px]",
    "tw:[&_strong]:text-[color:#174660]", "tw:[&_strong]:text-[.8rem]", "tw:[&_em]:leading-[1.3]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
} as const;
