import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "public_reg_shell": [
    "public-reg-shell", "tw:grid", "tw:grid-cols-[280px_minmax(0,_1fr)]", "tw:viewport-980:grid-cols-[1fr]",
    "tw:gap-y-[18px]", "tw:gap-x-[18px]",
  ].join(" "),
  "public_reg_aside_reveal_up": [
    "public-reg-aside", "reveal-up", "tw:flex", "tw:flex-col",
    "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:pt-[20px]", "tw:pr-[20px]",
    "tw:pb-[20px]", "tw:pl-[20px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[22px]", "tw:bg-[color:transparent]",
    "tw:[background-image:linear-gradient(165deg,_#f5f7ff_0%,_#eef2ff_100%)]", "tw:[box-shadow:var(--shadow)]", "tw:[animation:revealUp_380ms_var(--ease-standard)_both]",
  ].join(" "),
  "public_reg_brand": [
    "public-reg-brand", "tw:pb-[10px]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:rgba(77,_92,_166,_0.18)]", "tw:flex", "tw:items-center", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:mb-[10px]", "tw:[&_img]:w-[28px]", "tw:[&_img]:h-[28px]",
    "tw:[&_img]:rounded-[999px]", "tw:[&_img]:[object-fit:cover]", "tw:[&_img]:inline-flex", "tw:[&_img]:items-center",
    "tw:[&_img]:justify-center", "tw:[&_img]:font-[700]", "tw:[&_img]:text-[color:#3f4df0]", "tw:[&_img]:bg-[color:#ffffff]",
    "tw:[&_img]:[background-image:none]", "tw:[&_img]:border-t-[length:1px]", "tw:[&_img]:[border-top-style:solid]", "tw:[&_img]:border-t-[color:rgba(77,_92,_166,_0.25)]",
    "tw:[&_img]:border-r-[length:1px]", "tw:[&_img]:[border-right-style:solid]", "tw:[&_img]:border-r-[color:rgba(77,_92,_166,_0.25)]", "tw:[&_img]:border-b-[length:1px]",
    "tw:[&_img]:[border-bottom-style:solid]", "tw:[&_img]:border-b-[color:rgba(77,_92,_166,_0.25)]", "tw:[&_img]:border-l-[length:1px]", "tw:[&_img]:[border-left-style:solid]",
    "tw:[&_img]:border-l-[color:rgba(77,_92,_166,_0.25)]", "tw:[&_span]:w-[28px]", "tw:[&_span]:h-[28px]", "tw:[&_span]:rounded-[999px]",
    "tw:[&_span]:[object-fit:cover]", "tw:[&_span]:inline-flex", "tw:[&_span]:items-center", "tw:[&_span]:justify-center",
    "tw:[&_span]:font-[700]", "tw:[&_span]:text-[color:#3f4df0]", "tw:[&_span]:bg-[color:#ffffff]", "tw:[&_span]:[background-image:none]",
    "tw:[&_span]:border-t-[length:1px]", "tw:[&_span]:[border-top-style:solid]", "tw:[&_span]:border-t-[color:rgba(77,_92,_166,_0.25)]", "tw:[&_span]:border-r-[length:1px]",
    "tw:[&_span]:[border-right-style:solid]", "tw:[&_span]:border-r-[color:rgba(77,_92,_166,_0.25)]", "tw:[&_span]:border-b-[length:1px]", "tw:[&_span]:[border-bottom-style:solid]",
    "tw:[&_span]:border-b-[color:rgba(77,_92,_166,_0.25)]", "tw:[&_span]:border-l-[length:1px]", "tw:[&_span]:[border-left-style:solid]", "tw:[&_span]:border-l-[color:rgba(77,_92,_166,_0.25)]",
    "tw:[&_strong]:text-[0.84rem]",
  ].join(" "),
  "public_reg_kicker": [
    "public-reg-kicker", "tw:text-[color:#4d5ca6]", "tw:text-[0.78rem]", "tw:mt-[0]",
    "tw:mr-[0]", "tw:mb-[12px]", "tw:ml-[0]", "tw:tracking-[0.12em]",
    "tw:uppercase", "tw:font-[700]",
  ].join(" "),
  "public_reg_steps": [
    "public-reg-steps", "tw:gap-y-[10px]", "tw:gap-x-[10px]", "tw:grid",
  ].join(" "),
  "public_reg_step_public_reg_step_done": [
    "public-reg-step", "public-reg-step-done", "tw:opacity-[1]", "tw:grid-cols-[28px_minmax(0,_1fr)]",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:[align-items:start]", "tw:grid",
    "tw:[transition:opacity_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_span]:w-[28px]", "tw:[&_span]:h-[28px]", "tw:[&_span]:border-t-[length:2px]",
    "tw:[&_span]:border-r-[length:2px]", "tw:[&_span]:border-b-[length:2px]", "tw:[&_span]:border-l-[length:2px]", "tw:[&_span]:[box-shadow:0_0_0_4px_rgba(99,_194,_122,_0.14)]",
    "tw:[&_span]:inline-flex", "tw:[&_span]:items-center", "tw:[&_span]:justify-center", "tw:[&_span]:rounded-[999px]",
    "tw:[&_span]:[border-top-style:solid]", "tw:[&_span]:border-t-[color:#24b76f]", "tw:[&_span]:[border-right-style:solid]", "tw:[&_span]:border-r-[color:#24b76f]",
    "tw:[&_span]:[border-bottom-style:solid]", "tw:[&_span]:border-b-[color:#24b76f]", "tw:[&_span]:[border-left-style:solid]", "tw:[&_span]:border-l-[color:#24b76f]",
    "tw:[&_span]:text-[color:#ffffff]", "tw:[&_span]:font-[700]", "tw:[&_span]:bg-[color:#24b76f]", "tw:[&_span]:[background-image:none]",
    "tw:[&_strong]:text-[0.88rem]", "tw:[&_strong]:block", "tw:[&_small]:block", "tw:[&_small]:text-[color:var(--muted)]",
    "tw:[&_small]:text-[0.76rem]",
  ].join(" "),
  "public_reg_step": [
    "public-reg-step", "tw:opacity-[0.72]", "tw:grid-cols-[28px_minmax(0,_1fr)]", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[align-items:start]", "tw:grid", "tw:[transition:opacity_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]",
    "tw:[&_span]:w-[28px]", "tw:[&_span]:h-[28px]", "tw:[&_span]:border-t-[length:2px]", "tw:[&_span]:border-r-[length:2px]",
    "tw:[&_span]:border-b-[length:2px]", "tw:[&_span]:border-l-[length:2px]", "tw:[&_span]:[box-shadow:0_0_0_4px_rgba(29,_77,_209,_0.08)]", "tw:[&_span]:inline-flex",
    "tw:[&_span]:items-center", "tw:[&_span]:justify-center", "tw:[&_span]:rounded-[999px]", "tw:[&_span]:[border-top-style:solid]",
    "tw:[&_span]:border-t-[color:#9ca7da]", "tw:[&_span]:[border-right-style:solid]", "tw:[&_span]:border-r-[color:#9ca7da]", "tw:[&_span]:[border-bottom-style:solid]",
    "tw:[&_span]:border-b-[color:#9ca7da]", "tw:[&_span]:[border-left-style:solid]", "tw:[&_span]:border-l-[color:#9ca7da]", "tw:[&_span]:text-[color:#4d5ca6]",
    "tw:[&_span]:font-[700]", "tw:[&_span]:bg-[color:#ffffff]", "tw:[&_span]:[background-image:none]", "tw:[&_strong]:text-[0.88rem]",
    "tw:[&_strong]:block", "tw:[&_small]:block", "tw:[&_small]:text-[color:var(--muted)]", "tw:[&_small]:text-[0.76rem]",
  ].join(" "),
  "public_reg_step_active": [
    "public-reg-step-active", "tw:[&_span]:border-t-[color:#3f4df0]", "tw:[&_span]:border-r-[color:#3f4df0]", "tw:[&_span]:border-b-[color:#3f4df0]",
    "tw:[&_span]:border-l-[color:#3f4df0]", "tw:[&_span]:bg-[color:#ffffff]", "tw:[&_span]:[background-image:none]", "tw:[&_span]:text-[color:#3f4df0]",
    "tw:[&_span]:[box-shadow:0_0_0_4px_rgba(63,_77,_240,_0.16)]", "tw:opacity-[1]",
  ].join(" "),
  "public_reg_form_reveal_up": [
    "public-reg-form", "reveal-up", "tw:[animation-delay:120ms]", "tw:grid",
    "tw:gap-y-[14px]", "tw:gap-x-[14px]", "tw:[animation:revealUp_380ms_var(--ease-standard)_both]",
  ].join(" "),
  "public_reg_card": [
    "public-reg-card", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:var(--line)]", "tw:rounded-[20px]", "tw:bg-[color:#ffffff]", "tw:[background-image:none]",
    "tw:pt-[16px]", "tw:pr-[16px]", "tw:pb-[16px]", "tw:pl-[16px]",
    "tw:[box-shadow:var(--shadow)]",
  ].join(" "),
  "public_reg_card_head": [
    "public-reg-card-head", "tw:[&_h3]:mt-[0]", "tw:[&_h3]:mr-[0]", "tw:[&_h3]:mb-[0]",
    "tw:[&_h3]:ml-[0]", "tw:[&_p]:mt-[4px]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[12px]",
    "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:var(--muted)]",
  ].join(" "),
  "public_reg_grid_public_reg_grid_2": [
    "public-reg-grid", "public-reg-grid-2", "tw:grid", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-980:grid-cols-[1fr]",
  ].join(" "),
  "field": sharedUtilities.field,
  "public_reg_select": [
    "public-reg-select", "tw:[appearance:none]", "tw:[background-image:linear-gradient(45deg,_transparent_50%,_#4d5ca6_50%),_linear-gradient(135deg,_#4d5ca6_50%,_transparent_50%)]", "tw:[background-position:calc(100%_-_18px)_50%,_calc(100%_-_12px)_50%]",
    "tw:[background-size:6px_6px,_6px_6px]", "tw:[background-repeat:no-repeat]", "tw:pr-[34px]!",
  ].join(" "),
  "public_reg_date": [
    "public-reg-date", "tw:[color-scheme:light]", "tw:[&::-webkit-calendar-picker-indicator]:cursor-pointer", "tw:[&::-webkit-calendar-picker-indicator]:opacity-[0.86]",
  ].join(" "),
  "public_reg_submit": [
    "public-reg-submit", "tw:flex", "tw:justify-end", "tw:viewport-980:[justify-content:stretch]",
    "tw:viewport-980:[&_.button]:w-[100%]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "form_error_form_full": sharedUtilities.formErrorFormFull,
  "form_success_form_full_reveal_up": [
    "form-success", "form-full", "reveal-up", "tw:[animation-delay:180ms]",
    "tw:mt-[0]", "tw:mr-[0]", "tw:mb-[0]", "tw:ml-[0]",
    "tw:pt-[12px]", "tw:pr-[14px]", "tw:pb-[12px]", "tw:pl-[14px]",
    "tw:rounded-[0]", "tw:text-[0.95rem]", "tw:leading-[1.45]", "tw:bg-[color:rgba(28,_140,_94,_0.08)]",
    "tw:[background-image:none]", "tw:text-[color:var(--success)]", "tw:[grid-column:1_/_-1]", "tw:[animation:revealUp_380ms_var(--ease-standard)_both]",
  ].join(" "),
} as const;
