import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "stack_md": sharedUtilities.stackMd,
  "grid_form_section_card_ranking_configuration_form": [
    "grid-form", "section-card", "ranking-configuration-form", "tw:grid",
    "tw:gap-y-[15px]", "tw:gap-x-[20px]", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-680:grid-cols-[1fr]",
    "tw:[&_textarea]:w-[100%]", "tw:[&_textarea]:pt-[12px]", "tw:[&_textarea]:pr-[14px]", "tw:[&_textarea]:pb-[12px]",
    "tw:[&_textarea]:pl-[14px]", "tw:[&_textarea]:border-t-[length:1px]", "tw:[&_textarea]:[border-top-style:solid]", "tw:[&_textarea]:border-t-[color:var(--line)]",
    "tw:[&_textarea]:border-r-[length:1px]", "tw:[&_textarea]:[border-right-style:solid]", "tw:[&_textarea]:border-r-[color:var(--line)]", "tw:[&_textarea]:border-b-[length:1px]",
    "tw:[&_textarea]:[border-bottom-style:solid]", "tw:[&_textarea]:border-b-[color:var(--line)]", "tw:[&_textarea]:border-l-[length:1px]", "tw:[&_textarea]:[border-left-style:solid]",
    "tw:[&_textarea]:border-l-[color:var(--line)]", "tw:[&_textarea]:rounded-[var(--radius-md)]", "tw:[&_textarea]:bg-[color:var(--panel)]", "tw:[&_textarea]:[background-image:none]",
    "tw:[&_textarea]:text-[color:var(--text)]", "tw:pt-[22px]", "tw:pr-[0]", "tw:pb-[22px]",
    "tw:pl-[0]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dae6f1]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dae6f1]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dae6f1]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#dae6f1]", "tw:rounded-[10px]", "tw:bg-[color:transparent]", "tw:[background-image:none]",
    "tw:[box-shadow:none]",
  ].join(" "),
  "form_full_ranking_configuration_heading": [
    "form-full", "ranking-configuration-heading", "tw:[grid-column:1_/_-1]", "tw:[&_h2]:mt-[0]",
    "tw:[&_h2]:mr-[0]", "tw:[&_h2]:mb-[4px]", "tw:[&_h2]:ml-[0]", "tw:[&_h2]:text-[color:#173b62]",
    "tw:[&_h2]:text-[1.05rem]", "tw:[&_p]:mt-[0]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[.79rem]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "field": sharedUtilities.field,
  "field_form_full": sharedUtilities.fieldFormFull,
  "ranking_general_options_form_full": [
    "ranking-general-options", "form-full", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]",
    "tw:viewport-680:grid-cols-[1fr]", "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  "ranking_general_control": [
    "ranking-general-control", "tw:grid", "tw:grid-cols-[18px_minmax(0,_1fr)]", "tw:gap-y-[12px]",
    "tw:gap-x-[12px]", "tw:[align-items:start]", "tw:min-h-[88px]", "tw:pt-[16px]",
    "tw:pr-[16px]", "tw:pb-[16px]", "tw:pl-[16px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:var(--line)]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:var(--line)]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:var(--line)]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:var(--line)]", "tw:rounded-[var(--radius-md)]",
    "tw:bg-[color:var(--panel-muted)]", "tw:[background-image:none]", "tw:cursor-pointer", "tw:[&:has(input:disabled)]:opacity-[0.62]",
    "tw:[&:has(input:disabled)]:cursor-not-allowed", "tw:[&_input]:w-[18px]", "tw:[&_input]:h-[18px]", "tw:[&_input]:mt-[2px]",
    "tw:[&_input]:mr-[0]", "tw:[&_input]:mb-[0]", "tw:[&_input]:ml-[0]", "tw:[&_input]:[accent-color:var(--brand)]",
  ].join(" "),
  "ranking_general_control_copy": [
    "ranking-general-control-copy", "tw:grid", "tw:gap-y-[4px]", "tw:gap-x-[4px]",
    "tw:min-w-[0]", "tw:[&_strong]:leading-[1.25]", "tw:[&_small]:text-[color:var(--muted)]", "tw:[&_small]:leading-[1.4]",
  ].join(" "),
  "muted_form_full": sharedUtilities.mutedFormFull,
  "form_error_form_full": sharedUtilities.formErrorFormFull,
  "form_success_form_full": sharedUtilities.formSuccessFormFull,
  "section_actions_form_full": sharedUtilities.sectionActionsFormFull,
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "section_card": sharedUtilities.sectionCard,
  "section_actions": sharedUtilities.sectionActions,
  "button_button_danger": sharedUtilities.buttonButtonDanger,
} as const;
