import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "safe_action_confirmation_backdrop": [
    "safe-action-confirmation-backdrop", "tw:fixed", "tw:top-[0]", "tw:right-[0]",
    "tw:bottom-[0]", "tw:left-[0]", "tw:z-[1000]", "tw:grid",
    "tw:place-items-center", "tw:pt-[20px]", "tw:viewport-520:pt-[12px]", "tw:pr-[20px]",
    "tw:viewport-520:pr-[12px]", "tw:pb-[20px]", "tw:viewport-520:pb-[12px]", "tw:pl-[20px]",
    "tw:viewport-520:pl-[12px]", "tw:bg-[color:rgb(15_28_42_/_.42)]", "tw:[background-image:none]", "tw:viewport-520:[align-items:end]",
    "tw:[&_.safe-action-confirmation]:static", "tw:[&_.safe-action-confirmation]:[transform:none]",
  ].join(" "),
  "safe_action_confirmation": [
    "safe-action-confirmation", "tw:grid", "tw:gap-y-[16px]", "tw:gap-x-[16px]",
    "tw:w-[min(100%,_420px)]", "tw:viewport-520:w-[100%]", "tw:max-h-[min(600px,_calc(100dvh_-_40px))]", "tw:viewport-520:max-h-[calc(100dvh_-_24px)]",
    "tw:[overflow-x:auto]", "tw:[overflow-y:auto]", "tw:pt-[20px]", "tw:viewport-520:pt-[17px]",
    "tw:pr-[20px]", "tw:viewport-520:pr-[17px]", "tw:pb-[20px]", "tw:viewport-520:pb-[17px]",
    "tw:pl-[20px]", "tw:viewport-520:pl-[17px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#ead6d4]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#ead6d4]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#ead6d4]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#ead6d4]", "tw:rounded-[12px]", "tw:text-[color:#264154]",
    "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[box-shadow:0_24px_56px_rgb(13_31_45_/_.28)]", "tw:[&_header]:flex",
    "tw:[&_header]:items-center", "tw:[&_header]:gap-y-[11px]", "tw:[&_header]:gap-x-[11px]", "tw:[&_header_div]:grid",
    "tw:[&_header_div]:gap-y-[2px]", "tw:[&_header_div]:gap-x-[2px]", "tw:[&_header_strong]:text-[color:#243a4c]", "tw:[&_header_strong]:text-[.96rem]",
    "tw:[&_header_span]:text-[color:#738597]", "tw:[&_header_span]:text-[.72rem]", "tw:[&_>_p]:mt-[0]", "tw:[&_>_p]:mr-[0]",
    "tw:[&_>_p]:mb-[0]", "tw:[&_>_p]:ml-[0]", "tw:[&_>_p]:text-[color:#5d7183]", "tw:[&_>_p]:text-[.78rem]",
    "tw:[&_>_p]:leading-[1.5]", "tw:[&_>_label]:grid", "tw:[&_>_label]:gap-y-[6px]", "tw:[&_>_label]:gap-x-[6px]",
    "tw:[&_>_label]:text-[color:#3a5569]", "tw:[&_>_label]:text-[.72rem]", "tw:[&_>_label]:font-[800]", "tw:[&_>_label_input]:w-[100%]",
    "tw:[&_>_label_input]:min-h-[36px]", "tw:[&_>_label_input]:pt-[7px]", "tw:[&_>_label_input]:pr-[9px]", "tw:[&_>_label_input]:pb-[7px]",
    "tw:[&_>_label_input]:pl-[9px]", "tw:[&_>_label_input]:border-t-[length:1px]", "tw:[&_>_label_input]:[border-top-style:solid]", "tw:[&_>_label_input]:border-t-[color:#d4e0e8]",
    "tw:[&_>_label_input]:border-r-[length:1px]", "tw:[&_>_label_input]:[border-right-style:solid]", "tw:[&_>_label_input]:border-r-[color:#d4e0e8]", "tw:[&_>_label_input]:border-b-[length:1px]",
    "tw:[&_>_label_input]:[border-bottom-style:solid]", "tw:[&_>_label_input]:border-b-[color:#d4e0e8]", "tw:[&_>_label_input]:border-l-[length:1px]", "tw:[&_>_label_input]:[border-left-style:solid]",
    "tw:[&_>_label_input]:border-l-[color:#d4e0e8]", "tw:[&_>_label_input]:rounded-[6px]", "tw:[&_>_label_input]:[font:inherit]", "tw:[&_footer]:flex",
    "tw:[&_footer]:justify-end", "tw:[&_footer]:gap-y-[8px]", "tw:[&_footer]:gap-x-[8px]", "tw:[&_footer_.button]:min-w-[88px]",
    "tw:[&_footer_.button]:min-h-[34px]", "tw:[&_footer_.button]:pt-[6px]", "tw:[&_footer_.button]:pr-[12px]", "tw:[&_footer_.button]:pb-[6px]",
    "tw:[&_footer_.button]:pl-[12px]", "tw:[&_footer_.button]:rounded-[7px]", "tw:[&_footer_.button]:text-[.74rem]", "tw:viewport-520:[&_footer_.button]:[flex:1]",
  ].join(" "),
  "safe_action_confirmation_icon": [
    "safe-action-confirmation-icon", "tw:grid", "tw:w-[32px]", "tw:h-[32px]",
    "tw:[flex:0_0_32px]", "tw:place-items-center", "tw:rounded-[50%]", "tw:text-[color:#bc302a]",
    "tw:bg-[color:#fff1f0]", "tw:[background-image:none]", "tw:text-[1.05rem]", "tw:font-[900]",
  ].join(" "),
  "button": sharedUtilities.button,
  "button_button_danger": sharedUtilities.buttonButtonDanger,
  "form_error_form_full": sharedUtilities.formErrorFormFull,
  "form_success_form_full": sharedUtilities.formSuccessFormFull,
} as const;
