import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "tournament_editor_form": [
    "tournament-editor-form", "tw:grid", "tw:gap-y-[18px]", "tw:gap-x-[18px]",
    "tw:max-w-[1120px]", "tw:[&_>_.form-error]:mt-[0]", "tw:[&_>_.form-error]:mr-[0]", "tw:[&_>_.form-error]:mb-[0]",
    "tw:[&_>_.form-error]:ml-[0]", "tw:[&_>_.form-success]:mt-[0]", "tw:[&_>_.form-success]:mr-[0]", "tw:[&_>_.form-success]:mb-[0]",
    "tw:[&_>_.form-success]:ml-[0]",
  ].join(" "),
  "tournament_editor_section": [
    "tournament-editor-section", "tw:grid", "tw:gap-y-[20px]", "tw:gap-x-[20px]",
    "tw:pt-[22px]", "tw:viewport-720:pt-[17px]", "tw:pr-[22px]", "tw:viewport-720:pr-[17px]",
    "tw:pb-[22px]", "tw:viewport-720:pb-[17px]", "tw:pl-[22px]", "tw:viewport-720:pl-[17px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dfe8f3]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#dfe8f3]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#dfe8f3]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#dfe8f3]",
    "tw:rounded-[14px]", "tw:bg-[color:#fff]", "tw:[background-image:none]", "tw:[box-shadow:0_8px_22px_rgb(19_55_104_/_.045)]",
    "tw:[&_>_header]:flex", "tw:[&_>_header]:items-start", "tw:[&_>_header]:gap-y-[12px]", "tw:viewport-720:[&_>_header]:gap-y-[10px]",
    "tw:[&_>_header]:gap-x-[12px]", "tw:viewport-720:[&_>_header]:gap-x-[10px]", "tw:[&_>_header]:pb-[16px]", "tw:[&_>_header]:border-b-[length:1px]",
    "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#e8eef5]", "tw:[&_>_header_>_span]:grid", "tw:[&_>_header_>_span]:place-items-center",
    "tw:[&_>_header_>_span]:w-[32px]", "tw:[&_>_header_>_span]:h-[32px]", "tw:[&_>_header_>_span]:rounded-[8px]", "tw:[&_>_header_>_span]:bg-[color:#eaf2ff]",
    "tw:[&_>_header_>_span]:[background-image:none]", "tw:[&_>_header_>_span]:text-[color:#1262c4]", "tw:[&_>_header_>_span]:text-[.68rem]", "tw:[&_>_header_>_span]:font-[800]",
    "tw:[&_>_header_>_span]:tracking-[.06em]", "tw:[&_>_header_h2]:mt-[0]", "tw:[&_>_header_h2]:mr-[0]", "tw:[&_>_header_h2]:mb-[0]",
    "tw:[&_>_header_h2]:ml-[0]", "tw:[&_>_header_h2]:text-[color:#132e59]", "tw:[&_>_header_h2]:text-[1.05rem]", "tw:[&_>_header_p]:mt-[4px]",
    "tw:[&_>_header_p]:mr-[0]", "tw:[&_>_header_p]:mb-[0]", "tw:[&_>_header_p]:ml-[0]", "tw:[&_>_header_p]:text-[color:#687c96]",
    "tw:[&_>_header_p]:text-[.82rem]", "tw:[&_>_header_p]:leading-[1.45]",
  ].join(" "),
  "tournament_editor_grid": [
    "tournament-editor-grid", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-720:grid-cols-[1fr]",
    "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:[&_.field]:min-w-[0]", "tw:[&_.field.form-full]:[grid-column:1_/_-1]",
    "tw:viewport-720:[&_.field.form-full]:[grid-column:auto]", "tw:[&_textarea]:min-h-[118px]", "tw:[&_textarea]:[resize:vertical]",
  ].join(" "),
  "field_form_full": sharedUtilities.fieldFormFull,
  "field": sharedUtilities.field,
  "tournament_editor_section_tournament_editor_publication": [
    "tournament-editor-section", "tournament-editor-publication", "tw:grid", "tw:gap-y-[20px]",
    "tw:gap-x-[20px]", "tw:pt-[22px]", "tw:viewport-720:pt-[17px]", "tw:pr-[22px]",
    "tw:viewport-720:pr-[17px]", "tw:pb-[22px]", "tw:viewport-720:pb-[17px]", "tw:pl-[22px]",
    "tw:viewport-720:pl-[17px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#dfe8f3]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dfe8f3]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dfe8f3]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#dfe8f3]", "tw:rounded-[14px]", "tw:bg-[color:transparent]", "tw:[background-image:linear-gradient(135deg,_#fbfdff_0%,_#f3f8ff_100%)]",
    "tw:[box-shadow:0_8px_22px_rgb(19_55_104_/_.045)]", "tw:[&_>_header]:flex", "tw:[&_>_header]:items-start", "tw:[&_>_header]:gap-y-[12px]",
    "tw:viewport-720:[&_>_header]:gap-y-[10px]", "tw:[&_>_header]:gap-x-[12px]", "tw:viewport-720:[&_>_header]:gap-x-[10px]", "tw:[&_>_header]:pb-[16px]",
    "tw:[&_>_header]:border-b-[length:1px]", "tw:[&_>_header]:[border-bottom-style:solid]", "tw:[&_>_header]:border-b-[color:#e8eef5]", "tw:[&_>_header_>_span]:grid",
    "tw:[&_>_header_>_span]:place-items-center", "tw:[&_>_header_>_span]:w-[32px]", "tw:[&_>_header_>_span]:h-[32px]", "tw:[&_>_header_>_span]:rounded-[8px]",
    "tw:[&_>_header_>_span]:bg-[color:#eaf2ff]", "tw:[&_>_header_>_span]:[background-image:none]", "tw:[&_>_header_>_span]:text-[color:#1262c4]", "tw:[&_>_header_>_span]:text-[.68rem]",
    "tw:[&_>_header_>_span]:font-[800]", "tw:[&_>_header_>_span]:tracking-[.06em]", "tw:[&_>_header_h2]:mt-[0]", "tw:[&_>_header_h2]:mr-[0]",
    "tw:[&_>_header_h2]:mb-[0]", "tw:[&_>_header_h2]:ml-[0]", "tw:[&_>_header_h2]:text-[color:#132e59]", "tw:[&_>_header_h2]:text-[1.05rem]",
    "tw:[&_>_header_p]:mt-[4px]", "tw:[&_>_header_p]:mr-[0]", "tw:[&_>_header_p]:mb-[0]", "tw:[&_>_header_p]:ml-[0]",
    "tw:[&_>_header_p]:text-[color:#687c96]", "tw:[&_>_header_p]:text-[.82rem]", "tw:[&_>_header_p]:leading-[1.45]",
  ].join(" "),
  "field_form_full_tournament_public_slug": [
    "field", "form-full", "tournament-public-slug", "tw:grid",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]",
    "tw:[&_input]:w-[100%]", "tw:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]",
    "tw:[&_input]:pb-[0]", "tw:[&_input]:pl-[14px]", "tw:[&_input]:border-t-[length:0]", "tw:[&_input]:[border-top-style:none]",
    "tw:[&_input]:border-t-[color:currentColor]", "tw:[&_input]:border-r-[length:0]", "tw:[&_input]:[border-right-style:none]", "tw:[&_input]:border-r-[color:currentColor]",
    "tw:[&_input]:border-b-[length:0]", "tw:[&_input]:[border-bottom-style:none]", "tw:[&_input]:border-b-[color:currentColor]", "tw:[&_input]:border-l-[length:0]",
    "tw:[&_input]:[border-left-style:none]", "tw:[&_input]:border-l-[color:currentColor]", "tw:[&_input]:rounded-[0]", "tw:[&_input]:bg-[color:var(--panel)]",
    "tw:[&_input]:[background-image:none]", "tw:[&_input]:text-[color:var(--text)]", "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]",
    "tw:[&_select]:min-h-[44px]", "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]",
    "tw:[&_select]:pl-[14px]", "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]",
    "tw:[&_select]:border-r-[length:1px]", "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]",
    "tw:[&_select]:[border-bottom-style:solid]", "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]",
    "tw:[&_select]:border-l-[color:var(--line)]", "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]",
    "tw:[&_select]:text-[color:var(--text)]", "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:none]",
    "tw:[&_input:focus]:[transform:translateY(-1px)]", "tw:[&_select:focus]:[outline:none]", "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]",
    "tw:[&_input[type=file]]:pt-[10px]", "tw:[&_input[type=file]]:pr-[14px]", "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]",
    "tw:[&_input[type=checkbox]]:w-[auto]", "tw:[&_input[type=checkbox]]:min-h-[auto]", "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]",
    "tw:[&_input[type=checkbox]]:pb-[0]", "tw:[&_input[type=checkbox]]:pl-[0]", "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]",
    "tw:[&_input[type=radio]]:pt-[0]", "tw:[&_input[type=radio]]:pr-[0]", "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]",
    "tw:[grid-column:1_/_-1]", "tw:[&_>_div]:grid", "tw:[&_>_div]:grid-cols-[auto_minmax(0,_1fr)]", "tw:[&_>_div]:[overflow-x:hidden]",
    "tw:[&_>_div]:[overflow-y:hidden]", "tw:[&_>_div]:border-t-[length:1px]", "tw:[&_>_div]:[border-top-style:solid]", "tw:[&_>_div]:border-t-[color:#cbd9e9]",
    "tw:[&_>_div]:border-r-[length:1px]", "tw:[&_>_div]:[border-right-style:solid]", "tw:[&_>_div]:border-r-[color:#cbd9e9]", "tw:[&_>_div]:border-b-[length:1px]",
    "tw:[&_>_div]:[border-bottom-style:solid]", "tw:[&_>_div]:border-b-[color:#cbd9e9]", "tw:[&_>_div]:border-l-[length:1px]", "tw:[&_>_div]:[border-left-style:solid]",
    "tw:[&_>_div]:border-l-[color:#cbd9e9]", "tw:[&_>_div]:rounded-[9px]", "tw:[&_>_div]:bg-[color:#fff]", "tw:[&_>_div]:[background-image:none]",
    "tw:[&_>_div:focus-within]:border-t-[color:#4385d3]", "tw:[&_>_div:focus-within]:border-r-[color:#4385d3]", "tw:[&_>_div:focus-within]:border-b-[color:#4385d3]", "tw:[&_>_div:focus-within]:border-l-[color:#4385d3]",
    "tw:[&_>_div:focus-within]:[box-shadow:0_0_0_3px_rgb(36_112_205_/_.12)]", "tw:[&_>_div_span]:flex", "tw:[&_>_div_span]:items-center", "tw:[&_>_div_span]:pt-[0]",
    "tw:[&_>_div_span]:pr-[11px]", "tw:[&_>_div_span]:pb-[0]", "tw:[&_>_div_span]:pl-[11px]", "tw:[&_>_div_span]:border-r-[length:1px]",
    "tw:[&_>_div_span]:[border-right-style:solid]", "tw:[&_>_div_span]:border-r-[color:#dce6f1]", "tw:[&_>_div_span]:bg-[color:#edf4fb]", "tw:[&_>_div_span]:[background-image:none]",
    "tw:[&_>_div_span]:text-[color:#53708f]", "tw:[&_>_div_span]:text-[.84rem]", "tw:[&_>_div_span]:whitespace-nowrap", "tw:[&_input]:min-w-[0]",
    "tw:[&_input]:[box-shadow:none]", "tw:[&_p]:mt-[7px]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]",
    "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#647994]", "tw:[&_p]:text-[.77rem]", "tw:[&_p]:leading-[1.4]",
  ].join(" "),
  "tournament_radar_setting_form_full": [
    "tournament-radar-setting", "form-full", "tw:grid", "tw:grid-cols-[auto_minmax(0,_1fr)]",
    "tw:items-center", "tw:gap-y-[11px]", "tw:gap-x-[11px]", "tw:pt-[14px]",
    "tw:pr-[14px]", "tw:pb-[14px]", "tw:pl-[14px]", "tw:border-t-[length:1px]",
    "tw:[border-top-style:solid]", "tw:border-t-[color:#cce6d8]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]",
    "tw:border-r-[color:#cce6d8]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#cce6d8]",
    "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#cce6d8]", "tw:rounded-[10px]",
    "tw:bg-[color:#f2fbf6]", "tw:[background-image:none]", "tw:cursor-pointer", "tw:[&_>_input]:absolute",
    "tw:[&_>_input]:opacity-[0]", "tw:[&_>_input]:[pointer-events:none]", "tw:[&_>_span]:relative", "tw:[&_>_span]:w-[34px]",
    "tw:[&_>_span]:h-[20px]", "tw:[&_>_span]:rounded-[999px]", "tw:[&_>_span]:bg-[color:#b9c7d5]", "tw:[&_>_span]:[background-image:none]",
    "tw:[&_>_span]:[transition:background_.15s_ease]", "tw:[&_>_span::after]:absolute", "tw:[&_>_span::after]:top-[3px]", "tw:[&_>_span::after]:left-[3px]",
    "tw:[&_>_span::after]:w-[14px]", "tw:[&_>_span::after]:h-[14px]", "tw:[&_>_span::after]:rounded-[50%]", "tw:[&_>_span::after]:bg-[color:#fff]",
    "tw:[&_>_span::after]:[background-image:none]", "tw:[&_>_span::after]:[content:'']", "tw:[&_>_span::after]:[transition:transform_.15s_ease]", "tw:[&_>_input:checked_+_span]:bg-[color:#1eaa67]",
    "tw:[&_>_input:checked_+_span]:[background-image:none]", "tw:[&_>_input:checked_+_span::after]:[transform:translateX(14px)]", "tw:[&_strong]:text-[color:#146142]", "tw:[&_strong]:text-[.87rem]",
    "tw:[&_p]:mt-[3px]", "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]",
    "tw:[&_p]:text-[color:#5c7a6a]", "tw:[&_p]:text-[.78rem]", "tw:[&_p]:leading-[1.4]", "tw:[grid-column:1_/_-1]",
  ].join(" "),
  "currency_input": [
    "currency-input", "tw:flex", "tw:items-center", "tw:[overflow-x:hidden]",
    "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#c9d8e9]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#c9d8e9]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#c9d8e9]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#c9d8e9]", "tw:rounded-[9px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[&:focus-within]:border-t-[color:var(--brand)]", "tw:[&:focus-within]:border-r-[color:var(--brand)]", "tw:[&:focus-within]:border-b-[color:var(--brand)]", "tw:[&:focus-within]:border-l-[color:var(--brand)]",
    "tw:[&:focus-within]:[box-shadow:0_0_0_3px_color-mix(in_srgb,_var(--brand)_15%,_transparent)]", "tw:[&_>_span]:pt-[0]", "tw:[&_>_span]:pr-[10px]", "tw:[&_>_span]:pb-[0]",
    "tw:[&_>_span]:pl-[10px]", "tw:[&_>_span]:text-[color:#48617f]", "tw:[&_>_span]:font-[700]", "tw:[&_input]:min-w-[0]",
    "tw:[&_input]:border-t-[length:0]!", "tw:[&_input]:[border-top-style:none]!", "tw:[&_input]:border-t-[color:currentColor]!", "tw:[&_input]:border-r-[length:0]!",
    "tw:[&_input]:[border-right-style:none]!", "tw:[&_input]:border-r-[color:currentColor]!", "tw:[&_input]:border-b-[length:0]!", "tw:[&_input]:[border-bottom-style:none]!",
    "tw:[&_input]:border-b-[color:currentColor]!", "tw:[&_input]:border-l-[length:0]!", "tw:[&_input]:[border-left-style:none]!", "tw:[&_input]:border-l-[color:currentColor]!",
    "tw:[&_input]:[box-shadow:none]!",
  ].join(" "),
  "tournament_editor_footer": [
    "tournament-editor-footer", "tw:flex", "tw:items-center", "tw:viewport-720:items-stretch",
    "tw:justify-between", "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:pt-[4px]",
    "tw:pr-[2px]", "tw:pb-[4px]", "tw:pl-[2px]", "tw:[&_p]:mt-[0]",
    "tw:[&_p]:mr-[0]", "tw:[&_p]:mb-[0]", "tw:[&_p]:ml-[0]", "tw:[&_p]:text-[color:#687c96]",
    "tw:[&_p]:text-[.82rem]", "tw:[&_.button]:min-w-[156px]", "tw:viewport-720:flex-col", "tw:viewport-720:[&_.button]:w-[100%]",
  ].join(" "),
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "form_error_form_full": sharedUtilities.formErrorFormFull,
  "form_success_form_full": sharedUtilities.formSuccessFormFull,
} as const;
