import { sharedUtilities } from "@/components/ui/shared.utilities";
/** Tailwind utilities scoped to this component. Semantic markers support state and DOM queries. */
export const viewStyles = {
  "field_tournament_category_add_field": [
    "field", "tournament-category-add-field", "tw:grid", "tw:gap-y-[8px]",
    "tw:gap-x-[8px]", "tw:[&_label]:text-[0.92rem]", "tw:[&_label]:font-[600]", "tw:[&_input]:w-[100%]",
    "tw:[&_input]:min-h-[44px]", "tw:[&_input]:pt-[0]", "tw:[&_input]:pr-[14px]", "tw:[&_input]:pb-[0]",
    "tw:[&_input]:pl-[14px]", "tw:[&_input]:border-t-[length:1px]", "tw:[&_input]:[border-top-style:solid]", "tw:[&_input]:border-t-[color:var(--line)]",
    "tw:[&_input]:border-r-[length:1px]", "tw:[&_input]:[border-right-style:solid]", "tw:[&_input]:border-r-[color:var(--line)]", "tw:[&_input]:border-b-[length:1px]",
    "tw:[&_input]:[border-bottom-style:solid]", "tw:[&_input]:border-b-[color:var(--line)]", "tw:[&_input]:border-l-[length:1px]", "tw:[&_input]:[border-left-style:solid]",
    "tw:[&_input]:border-l-[color:var(--line)]", "tw:[&_input]:rounded-[var(--radius-md)]", "tw:[&_input]:bg-[color:var(--panel)]", "tw:[&_input]:[background-image:none]",
    "tw:[&_input]:text-[color:var(--text)]", "tw:[&_input]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_select]:w-[100%]", "tw:[&_select]:min-h-[44px]",
    "tw:[&_select]:pt-[0]", "tw:[&_select]:pr-[14px]", "tw:[&_select]:pb-[0]", "tw:[&_select]:pl-[14px]",
    "tw:[&_select]:border-t-[length:1px]", "tw:[&_select]:[border-top-style:solid]", "tw:[&_select]:border-t-[color:var(--line)]", "tw:[&_select]:border-r-[length:1px]",
    "tw:[&_select]:[border-right-style:solid]", "tw:[&_select]:border-r-[color:var(--line)]", "tw:[&_select]:border-b-[length:1px]", "tw:[&_select]:[border-bottom-style:solid]",
    "tw:[&_select]:border-b-[color:var(--line)]", "tw:[&_select]:border-l-[length:1px]", "tw:[&_select]:[border-left-style:solid]", "tw:[&_select]:border-l-[color:var(--line)]",
    "tw:[&_select]:rounded-[var(--radius-md)]", "tw:[&_select]:bg-[color:var(--panel)]", "tw:[&_select]:[background-image:none]", "tw:[&_select]:text-[color:var(--text)]",
    "tw:[&_select]:[transition:border-color_180ms_var(--ease-standard),_box-shadow_180ms_var(--ease-standard),_transform_180ms_var(--ease-standard)]", "tw:[&_input:focus]:[outline:none]", "tw:[&_input:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_input:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_input:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_input:focus]:[transform:translateY(-1px)]",
    "tw:[&_select:focus]:[outline:none]", "tw:[&_select:focus]:border-t-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-r-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:border-b-[color:rgba(30,_94,_168,_0.44)]",
    "tw:[&_select:focus]:border-l-[color:rgba(30,_94,_168,_0.44)]", "tw:[&_select:focus]:[box-shadow:0_0_0_4px_rgba(30,_94,_168,_0.12)]", "tw:[&_select:focus]:[transform:translateY(-1px)]", "tw:[&_input[type=file]]:pt-[10px]",
    "tw:[&_input[type=file]]:pr-[14px]", "tw:[&_input[type=file]]:pb-[10px]", "tw:[&_input[type=file]]:pl-[14px]", "tw:[&_input[type=checkbox]]:w-[auto]",
    "tw:[&_input[type=checkbox]]:min-h-[auto]", "tw:[&_input[type=checkbox]]:pt-[0]", "tw:[&_input[type=checkbox]]:pr-[0]", "tw:[&_input[type=checkbox]]:pb-[0]",
    "tw:[&_input[type=checkbox]]:pl-[0]", "tw:[&_input[type=radio]]:w-[auto]", "tw:[&_input[type=radio]]:min-h-[auto]", "tw:[&_input[type=radio]]:pt-[0]",
    "tw:[&_input[type=radio]]:pr-[0]", "tw:[&_input[type=radio]]:pb-[0]", "tw:[&_input[type=radio]]:pl-[0]", "tw:[&_.field-inline]:grid",
    "tw:[&_.field-inline]:grid-cols-[minmax(0,_1fr)_auto]", "tw:viewport-620:[&_.field-inline]:grid-cols-[1fr]", "tw:[&_.field-inline]:gap-y-[10px]", "tw:[&_.field-inline]:gap-x-[10px]",
    "tw:[&_.field-inline]:[align-items:end]",
  ].join(" "),
  "button": sharedUtilities.button,
  "tournament_category_manager_list": [
    "tournament-category-manager-list", "tw:grid", "tw:gap-y-[12px]", "tw:gap-x-[12px]",
  ].join(" "),
  "tournament_category_manager_card": [
    "tournament-category-manager-card", "tw:grid", "tw:gap-y-[14px]", "tw:gap-x-[14px]",
    "tw:pt-[18px]", "tw:pr-[18px]", "tw:pb-[18px]", "tw:pl-[18px]",
    "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#d7e2ef]", "tw:border-r-[length:1px]",
    "tw:[border-right-style:solid]", "tw:border-r-[color:#d7e2ef]", "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]",
    "tw:border-b-[color:#d7e2ef]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]", "tw:border-l-[color:#d7e2ef]",
    "tw:rounded-[12px]", "tw:bg-[color:#fbfdff]", "tw:[background-image:none]",
  ].join(" "),
  "tournament_category_manager_card_header": [
    "tournament-category-manager-card-header", "tw:flex", "tw:items-start", "tw:viewport-620:items-stretch",
    "tw:justify-between", "tw:gap-y-[16px]", "tw:gap-x-[16px]", "tw:[&_>_div]:grid",
    "tw:[&_>_div]:gap-y-[5px]", "tw:[&_>_div]:gap-x-[5px]", "tw:[&_strong]:text-[color:#142f5d]", "tw:[&_span]:text-[color:#6b7f9b]",
    "tw:[&_span]:text-[.82rem]", "tw:viewport-620:flex-col", "tw:viewport-620:[&_.button]:w-[fit-content]",
  ].join(" "),
  "button_button_small": sharedUtilities.buttonButtonSmall,
  "tournament_category_standard": [
    "tournament-category-standard", "tw:grid", "tw:grid-cols-[minmax(0,_1fr)_minmax(220px,_360px)]", "tw:viewport-620:grid-cols-[1fr]",
    "tw:gap-y-[12px]", "tw:gap-x-[12px]", "tw:items-center", "tw:text-[color:#324967]",
    "tw:text-[.86rem]", "tw:font-[700]",
  ].join(" "),
  "currency_input": [
    "currency-input", "tw:flex", "tw:items-center", "tw:[overflow-x:hidden]",
    "tw:[overflow-y:hidden]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]", "tw:border-t-[color:#c9d8e9]",
    "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#c9d8e9]", "tw:border-b-[length:1px]",
    "tw:[border-bottom-style:solid]", "tw:border-b-[color:#c9d8e9]", "tw:border-l-[length:1px]", "tw:[border-left-style:solid]",
    "tw:border-l-[color:#c9d8e9]", "tw:rounded-[9px]", "tw:bg-[color:#fff]", "tw:[background-image:none]",
    "tw:[&:focus-within]:border-t-[color:var(--brand)]", "tw:[&:focus-within]:border-r-[color:var(--brand)]", "tw:[&:focus-within]:border-b-[color:var(--brand)]", "tw:[&:focus-within]:border-l-[color:var(--brand)]",
    "tw:[&:focus-within]:[box-shadow:0_0_0_3px_color-mix(in_srgb,_var(--brand)_15%,_transparent)]", "tw:[&_>_span]:pt-[0]", "tw:[&_>_span]:pr-[10px]", "tw:[&_>_span]:pb-[0]",
    "tw:[&_>_span]:pl-[10px]", "tw:[&_>_span]:text-[color:#48617f]", "tw:[&_>_span]:font-[700]", "tw:[&_input]:min-w-[0]",
    "tw:[&_input]:border-t-[length:0]!", "tw:[&_input]:[border-top-style:none]!", "tw:[&_input]:border-t-[color:currentColor]!", "tw:[&_input]:border-r-[length:0]!",
    "tw:[&_input]:[border-right-style:none]!", "tw:[&_input]:border-r-[color:currentColor]!", "tw:[&_input]:border-b-[length:0]!", "tw:[&_input]:[border-bottom-style:none]!",
    "tw:[&_input]:border-b-[color:currentColor]!", "tw:[&_input]:border-l-[length:0]!", "tw:[&_input]:[border-left-style:none]!", "tw:[&_input]:border-l-[color:currentColor]!",
    "tw:[&_input]:[box-shadow:none]!",
  ].join(" "),
  "tournament_category_link_toggle": [
    "tournament-category-link-toggle", "tw:flex", "tw:items-center", "tw:gap-y-[9px]",
    "tw:gap-x-[9px]", "tw:text-[color:#233c5d]", "tw:text-[.86rem]", "tw:[&_input]:w-[16px]",
    "tw:[&_input]:h-[16px]", "tw:[&_input]:[accent-color:var(--brand)]",
  ].join(" "),
  "muted": sharedUtilities.muted,
  "tournament_category_link_options": [
    "tournament-category-link-options", "tw:grid", "tw:grid-cols-[repeat(2,_minmax(0,_1fr))]", "tw:viewport-620:grid-cols-[1fr]",
    "tw:gap-y-[8px]", "tw:gap-x-[8px]", "tw:pt-[12px]", "tw:pr-[12px]",
    "tw:pb-[12px]", "tw:pl-[12px]", "tw:border-t-[length:1px]", "tw:[border-top-style:solid]",
    "tw:border-t-[color:#dce7f3]", "tw:border-r-[length:1px]", "tw:[border-right-style:solid]", "tw:border-r-[color:#dce7f3]",
    "tw:border-b-[length:1px]", "tw:[border-bottom-style:solid]", "tw:border-b-[color:#dce7f3]", "tw:border-l-[length:1px]",
    "tw:[border-left-style:solid]", "tw:border-l-[color:#dce7f3]", "tw:rounded-[9px]", "tw:bg-[color:#f3f8fd]",
    "tw:[background-image:none]", "tw:[&_label]:flex", "tw:[&_label]:items-center", "tw:[&_label]:gap-y-[7px]",
    "tw:[&_label]:gap-x-[7px]", "tw:[&_label]:text-[color:#3b536f]", "tw:[&_label]:text-[.83rem]", "tw:[&_input]:[accent-color:var(--brand)]",
  ].join(" "),
  "section_actions": sharedUtilities.sectionActions,
  "button_button_primary": sharedUtilities.buttonButtonPrimary,
  "form_error": sharedUtilities.formError,
  "form_success": sharedUtilities.formSuccess,
} as const;
